### ISSUE TITLE
terminal size and lines issues

### ISSUE THREAD

**Issue by perfluxion** [Microsoft/WSL#1001]
I've been having trouble with lines not wrapping or cursor position going off by a line sometimes, especially when tab completing past a line length, or using the arrows keys to cross a line wrap, but sometimes even just pressing delete a bunch.  This seems to primarily happen when I am ssh'd to another system, so this may be related to a console size issue I noticed which is easier to state:

start a new terminal with bash
$ stty size
25 80
$ echo $LINES $COLUMNS
25 80
$ tput lines; tput cols
25
80

resize the terminal by dragging up, and these will still report 25x80
resize by dragging diagonally
now those values are updated

This causes at least some of the line issues with screen in an ssh session, with the terminal looking truncated.

My windows install: Version 10.0.14393 Build 14393

**Comment by vwsc2015** [comment]
you can use another terminal, CMD, powershell, or ConEMU

**Comment by db0xcc** [comment]
@vwsc2015 , maybe I'm just completely misunderstanding your comment, as what you are suggesting doesn't make sense to me.

bash, cmd, and powershell are shells, not a terminal.  The job of a terminal in windows is probably handled by conhost.  A search seems to indicate ConEMU relies on conhost as well.

So launching powershell, then running the command bash, is not a different terminal.  I checked and the same issue I listed above happens in powershell -> bash.  This seems like a silly check, so I'm worried I've completely misunderstood your comment.  Can you please clarify?

**Comment by fpqc** [comment]
@db0xcc There are tons of conhost bugs atm, and for the moment, I suggest running an X terminal emulator with vcXsrv.  If you roll over to my github page, I have a preconfigured copy of st with a default size hack in the int main  and some color and font patches applied (a pretty minimal fork, since configuration is done through config.h) that works pretty clean out of the box with really no problems so far (I previously suggested rxvt, but that requires a few more steps and hacks).

To build it and have it work right, you need the ubuntu packages 
`libx11-dev` `libxft-dev` and `fonts-powerline`.  

To get it running, all you need is to do is run vcXsrv, git clone the repo, enter it, `make clean`, `make`, `sudo make install`, and run it with 
`DISPLAY=:0 st`

I put my config on github to share with this WSL forum.  Here's how it looks with oh-my-zsh:

![2016-08-28](https://cloud.githubusercontent.com/assets/6083371/18037580/2c7fed4c-6d56-11e6-81c4-68ad9be5a862.png)

My launch command is `DISPLAY=:0 st -e /bin/zsh`

**Comment by db0xcc** [comment]
@fpqc Thanks, this looks like a great work around while they are fixing up the windows terminal.

**Comment by fpqc** [comment]
@db0xcc Oh btw you should use tmux in st for scrollback support. st does not keep its own scrollback buffer.

**Comment by jrtc27** [comment]
Have you tried `kill -WINCH $$`? Generally that fixes things for me on resize. My guess is SIGWINCHes are going missing.

**Comment by zadjii-msft** [comment]
It does seem that resizing the height outside an alternate buffer doesn't send the event.

However, I'm not totally sure this is fixable behavior. Right now the console only sends size change events when the *buffer* size changes, not when the *window* size does. This is legacy behavior back to... who knows when. So that can't just quickly be fixed unfortunately. We'll have some discussion about investigating this more

**Comment by bitcrazed** [comment]
Thanks for reporting. As @zadjii-msft says - this may not be soemthing we can easily fix for a number of reasons. We have filed this issue, however, and will take a look at what we _might_ be able to do here.

**Note:** If you don't pound on the Console and file issues, we'll have a harder time finding and prioritizing bugs. While it may be a little painful in the short term, we greatly appreciate your help finding these issues so that we can log & (eventually) fix them 😜

**Comment by zadjii-msft** [comment]
Changing from bug to feature, as this is actually feature level work and not a simple bug fix.

This is tracked internally as MSFT:8708175

**Comment by nick4fake** [comment]
Well, calling incorrect behavior "feature" instead of "bug" won't change anything. While I really appreciate Microsoft for bash on windows, this bug is something that ruins user experience.

**Comment by fpqc** [comment]
@nick4fake Does this still even happen in 1703?

**Comment by zadjii-msft** [comment]
@nick4fake I'm not saying that the behavior is a feature. The "Feature" label is for fixes that require a feature level of work vs a bug level fix - it's a subtle distinction that doesn't really mean anything externally, but it helps us differentiate our work internally at Microsoft. 

And actually, looking through the code, I think this got checked in a few weeks back, for a related issue. from the looks of it, it should be in the next Insiders build :)

**Comment by nick4fake** [comment]
Thank you for a really quick answer.

Yes, I have 1703. But after you mentioned that this should be already in prod I have checked PowerShell - and it looks like everything is ok. Probably ConEmu developers should update their application as well.

**Comment by nick4fake** [comment]
There is same issue with Intellij IDEA terminal. Why does it affect multiple terminals from different vendors?

**Comment by fpqc** [comment]
Because almost all software with embedded console/terminal uses WinPTY as a backend, at least that's my guess.

**Comment by nick4fake** [comment]
Well, what I am talking about is that this issue does not look as "fixed", as it still affects various terminal emulators.

**Comment by zadjii-msft** [comment]
@nick4fake "fixinbound" means that the fix for this bug is coming to an upcoming Insider's build soon. I don't believe that it's already out yet, but I'm not sure. If, once the fix is out for conhost, other terminal emulators still don't work correctly, then I'd recommend opening issues on them for not supporting the fixed behavior correctly. As @fpqc mentioned, WinPTY is a good place to start for those issues.

**Comment by fpqc** [comment]
@nick4fake the way that third party consoles work for Windows right now is kind of a huge ugly hack (the console team mentioned that they're working on creating some new plumbing to obviate these hacks).  Basically, the third-party consoles set up a periodic poll on a hidden console window that pauses the window, then reads off all the text on the screen, unpauses, and finally provides the dumped screen in a sort of pty-compatible format.  This hack underlies both WinPTY (used in VSCode and likely IntelliJ) as well as ConEMU/cmder.  

Since all of the third-party consoles use the same hack that depends on reading off the screen of the Windows console directly, problems/bugs/unimplemented features in conhost itself will be directly mirrored in the third-party consoles.

I have to say though I am interested by one particular case that doesn't use any hack at all: The proprietary version of Visual Studio and also the powershell ISE both have integrated consoles without using third-party hacks like WinPTY or ConEMU, at least to my knowledge..

**Comment by eyzhao** [comment]
Ran into this issue too. I found an admittable hacky workaround, in case this helps others. I noticed that after using Vim, the screen size readjusts properly. So I mapped an alias

`alias fix="vim -c ':q'"`

in my bashrc. When you run `fix` from bash, it quickly opens and shuts vim, resetting the column width.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing. If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
