### ISSUE TITLE
Can't install Ubuntu distribution due to missing (or wrong PATH env var) files

### ISSUE THREAD

**Issue by alberto-delgado-maersk** [microsoft/WSL#10033]
### Windows Version

Microsoft Windows [Version 10.0.22621.1635]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 2204.31.0

### Repro Steps

I had to re-installed WSL2 in my windows machine (Ubuntu was installed before).  The previous version was WSL1 upgraded to WSL2.  I followed the steps below:
1) Run in Powershell with admin rights: `wsl --install`. Got the following output:
```
The requested operation requires elevation.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Installing: Ubuntu
Ubuntu has been installed.
The requested operation is successful. Changes will not be effective until the system is rebooted.
```
2) Restarted laptop,  Ubuntu started by itself and got the following output:
Ubuntu is already installed.
```
Launching Ubuntu...
Installing, this may take a few minutes...
/bin/bash: line 1: rm: command not found
/bin/bash: line 1: mkdir: command not found
/bin/bash: line 1: ln: command not found
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:
```
3) Typed a new user name and got the error below:
`/bin/bash: line 1: adduser: command not found`

**Additional info**:

I tried to install Debian to see whether I'd get a similar problem.  Managed to install it but got the error message below:
```
Installation successful!
-bash: dircolors: command not found 
```
And when I run Linux commands, e.g., `ls`, I get the following error:
`-bash: ls: command not found`

I echoed the PATH env var and could not find a path to any linux bin folder, e.g.,  `/bin` or `/sbin`.

### Expected Behavior

Ubuntu installs successfully

### Actual Behavior

Ubuntu fails to install due to error when creating user

**Comment by Jrograms** [comment]
I'm having the same issue and have tried a bunch of ways to remedy it. I've tried 

- simple unregister, uninstall, reinstall on distributions
- restarting/ resetting WSL through Apps and Features (the amount of times I have had to restart my machine to ensure that the components are also disabled and then enabled is nothing short of infuriating)
- multiple distros
- checking that certain lines in the config are commented out or not present

I've even found temporary work arounds. However, those temporary work around are suppose to be permanent (manually **re-configuring the Unix paths by editing both the /.bashrc and /.profile files** and the then making sure they should work by refreshing bash + more  and even creating new users from root; which is one of the main things that does not happen due to the issue). These didn't last past using wsl commands. **It would set the path to reflect only the windows path values.**

I am using the same version of WSL (1.2.5.0) but **Windows Build 10.0.19045.3031**.

Any assistance is appreciated.

**Comment by alberto-delgado-maersk** [comment]
It seems that at some point I had added the below env var to windows:
![image](https://github.com/microsoft/WSL/assets/70290614/4d887499-2cda-486e-b927-ce36d21a5964)

This was screwing up the PATH in ubuntu.  I removed the env var,  reinstalled ubuntu and all works fine now
