### ISSUE TITLE
wsl: Nested virtualization is not supported on this machine. -- Then starts anyway

### ISSUE THREAD

**Issue by thebalaa** [microsoft/WSL#10041]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian GNU/Linux 11

### Other Software

virt-manager / KVM

### Repro Steps

This following only recently started happening.

Launching WSL from within a Windows 11 virtual machine running inside virt-manager on an Ubuntu 20.04 host results in:
```
"wsl: Nested virtualization is not supported on this machine."
user@DESKTOP-12345 ~$
```
WSL appears to boot up and work as expected.

### Expected Behavior

No message about nested virtualization not being supported should appear, as was the case previously.

### Actual Behavior

wsl: Nested virtualization is not supported on this machine.

Then wsl appears to work but the error leads me to be concerned I am not getting virtualization benefits?

**Comment by elsaco** [comment]
@thebalaa what CPU are you using? And did you enable nested virtualization in KVM? To check if nested virtualization is available on your system for Intel CPUs type `cat /sys/module/kvm_intel/parameters/nested` and for AMD CPUs type `cat /sys/module/kvm_amd/parameters/nested`. If the output is `1` you have nested virtualization.

**Comment by benhillis** [comment]
This is just a warning that your processor does not support the processor feature required for running nested VMs.

**Comment by thebalaa** [comment]
@benhillis sorry for not being more clear.

My processor is a Ryzen 5950X which, to the best of my understanding, does support nested virtualization. The motivation for this ticket was that this message appears on a system where it was previously not appearing. The system or VM hadn't even been restarted.

**Comment by Entropy512** [comment]
@benhillis Can you clarify a question I have:

Using RedHat's terminology for nesting at https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/configuring_and_managing_windows_virtual_machines/creating-nested-virtual-machines might help here to avoid confusion:

1. Is this error stating that Windows (as an L1 guest) cannot virtualize WSL2 as an L2 guest and thus WSL2 performance will be severely degraded due to operating in an emulated machine?
2. Or is it stating that WSL2 (as an L2 guest) cannot further virtualize any guests within it?

If 1 - this is wrong, a Threadripper Pro 7995WX absolutely does support nested virt and the L0 host OS (Ubuntu Server 24.04) definitely detects it
If 2 - yeah this is fine, maybe your warning should be made more clear in terms of its meaning

**Comment by Tomorrow9** [comment]
I'm using Windows 11 build 26300.8142 on ESXi host, also encounter this issue. The message "wsl: Nested virtualization is not supported on this machine." only displays the first time I execute command in WSL, the second time executing the command, there is no such message.

WSL is downloaded from github.
```
wsl --version
WSL version: 2.6.3.0  Kernel version: 6.6.87.2-1  WSLg version: 1.0.71  MSRDC version: 1.2.6353  Direct3D version: 1.611.1-81528511  DXCore version: 10.0.26100.1-240331-1435.ge-release  Windows version: 10.0.26300.8142
```
```
wsl --status
Default Version: 2  WSL1 is not supported with your current machine configuration.  Please enable the \"Windows Subsystem for Linux\" optional component to use WSL1.
```
```
wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```
While when executing command "wsl.exe -d Ubuntu cat /etc/os-release", it returns
```
wsl : wsl: Nested virtualization is not supported on this
...
```
Nested virtualization is enabled on VM, and VBS is running in this guest OS.
