### ISSUE TITLE
run docker cli in wsl , there  isn't  exist docker cli executable file

### ISSUE THREAD

**Issue by marol1210** [microsoft/WSL#10097]
### Windows Version

Microsoft Windows [版本 10.0.22621.1755]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

alpine-3.18.0

### Other Software

Docker Desktop 4.12.0 (85629)

### Repro Steps

1. download alpine-3.18.0.tar , wsl.exe --import it
2. start docker desktop , enable wsl engine , use distro from  setup 1
3. enter wsl environment , exec docker cli , and display cli not find .

![image](https://github.com/microsoft/WSL/assets/7519301/c4fe46c5-1190-40c1-9763-12843633fbb3)

### Expected Behavior

can exec docker cli

### Actual Behavior

can't exec docker cli.    error:  no such file or directory

**Comment by NotTheDr01ds** [comment]
This would really be an issue to file against Docker, of course.

It's been a while since I used Docker Desktop with Alpine, but I *thought* the binaries used to be statically linked.  However, if that was the case, it doesn't appear to be any longer.

Keep in mind that Alpine does *not* provide standard `glibc` support like most distributions, so binaries that are dynamically linked against it will fall on Alpine.

See [this Stack Overflow answer](https://stackoverflow.com/a/66974607/11810933) for some background, and potential solutions, e.g.:

```
su -
apk add libc6-compat
exit
docker
```

**Comment by marol1210** [comment]
nice ,  big thanks
