### ISSUE TITLE
WSL export - Error code: Wsl/Service/0x80070070

### ISSUE THREAD

**Issue by cforce** [microsoft/WSL#10272]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2965

### Repro Steps

wsl --export Ubuntu "C:\temp\UbuntuExport"

### Expected Behavior

Export at C:\temp\UbuntuExport

### Actual Behavior

C:\temp>wsl --export Ubuntu "C:\temp\UbuntuExport"
Export in progress, this may take a few minutes.
There is not enough space on the disk.
Error code: Wsl/Service/0x80070070

C:\temp>wslconfig /l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop
docker-desktop-data

C:\temp>fsutil volume diskfree c:
Total free bytes        :   155.435.548.672 (144,8 GB)
Total bytes             : 1.021.435.703.296 (951,3 GB)
Total quota free bytes  :   155.435.548.672 (144,8 GB)

**Comment by benhillis** [comment]
How large is your Ubuntu VHD?

**Comment by cforce** [comment]
76 GB around

**Comment by RebeccaStevens** [comment]
Same error for me? Any workaround known?

**Comment by aj-ats** [comment]
The problem is still 100% reproducible in 2025.
I am exporting to a brand new 128gb 3.0 usb drive 
```
PS D:\> wsl --export Ubuntu D:\ubuntu.tar
Export in progress, this may take a few minutes. (4092 MB)

There is not enough space on the disk.
Error code: Wsl/Service/0x80070070
```

This is peak Microsoft behavior:

- Ship a broken feature
- Ignore it for years
- Close the issue because “inactivity” (sure, it’s GitHub policy, but come on)
- Leave users completely screwed

The problem is still 100% reproducible in 2025.
I’m trying to export my distro to an external drive because my host SSD is full. And guess why my SSD is full? Because of https://github.com/microsoft/WSL/issues/4699.

So now I’m here, on this abandoned 2023 thread, trying to work around a 5+ year old bug with another half-broken feature that Microsoft also refuses to maintain.
I actually like WSL when it works. The only reason I even use it is because my work forces me onto Windows. But right now it’s becoming borderline unusable, and the complete radio silence from the team is infuriating.
Fix your shit, Microsoft.
