### ISSUE TITLE
WSL2 stopped running windows tools seemingly all of a sudden - cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/WSL#10389]
### Windows Version

Microsoft Windows [Version 10.0.22000.2176]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

22.04

### Repro Steps

Just running any windows executable results in the same error -  **cannot execute binary file: Exec format error**
This is a regression. It worked just a few days ago.

### Expected Behavior

Windows tools can be run without problems.

### Actual Behavior

cannot execute binary file: Exec format error

### Diagnostic Logs

Not sure which ones for this particular issue. Please, advise.

**Comment by elsaco** [comment]
@MarkKharitonov this issue is tracked by https://github.com/microsoft/WSL/issues/8843

Check what packages were updated lately. Newer releases of systemd add a new unit file, `systemd-binfmt.service`, that's messing the `WSLInterop` setting in `/proc/sys/fs/binfmt_misc`. One solution is to add back `WSLInterop`. I prefer to mask `systemd-binfmt.service`. This restores `/proc/sys/fs/binfmt_misc/WSLInterop` setting.

**Comment by MikeBarberry** [comment]
^ This worked for me on Windows 11 WSL version 1.2.5.0

**Comment by MarkKharitonov** [comment]
@elsaco - your advice with the `/etc/binfmt.d/wsl.conf` worked as advertised.
Thank you very much.

**Comment by RobertoMaurizzi** [comment]
Happened to me after upgrading my WSL Ubuntu 20.04 to 22.04. Creating the file in `/etc/binfmt.d/` fixed it, thanks!

**Comment by wolszakp** [comment]
> If you don't want to prevent systemd unit file from running (there are other binary formats that are registerd by the service) add a config file in `/etc/binfmt.d/` and it will be picked-up by systemd and register WSLInterop:
> 
> ```
> elsaco@lobster:~$ cat /etc/binfmt.d/wsl.conf
> :WSLInterop:M::MZ::/init:PF
> ```


Thanks, it works for me as well.
