### ISSUE TITLE
wslpath fails to convert from windows to mixed mode (and vice versa)

### ISSUE THREAD

**Issue by slycordinator** [microsoft/WSL#10457]
### Windows Version

Microsoft Windows [Version 10.0.19045.3324]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian 12

### Repro Steps

1) run /usr/bin/wslpath -m 'C:\Windows'
2) run /usr/bin/wslpath -w 'C:/Windows' 

### Expected Behavior

utility to convert paths correctly

`# /usr/bin/wslpath -m 'C:\Windows'`
expected output='C:/Windows'

`# /usr/bin/wslpath -w 'C:/Windows'`
expected output='C:\Windows'

### Actual Behavior

Utility outputs invalid characters that at first glance appear to be blank.

```
# /usr/bin/wslpath -m 'C:\Windows'
CWindows
# /usr/bin/wslpath -w 'C:/Windows'
C\Windows
```

**Comment by OneBlue** [comment]
Thank you for reporting this @slycordinator.

`-w` and `-m` are for converting from a WSL path to a Windows path. What this is doing in this case is trying to translate 'C:\windows' as a relative path into a Windows path. The character you're seeing wslpath trying to escape ':', since it's an invalid character in an NTFS path.

What you probably want to do is: 

```
$ wslpath -u 'C:\windows'
/mnt/c/windows
```
