### ISSUE TITLE
The whole windows OS will freeze when i use: `wsl --shutdown`

### ISSUE THREAD

**Issue by LinArcX** [microsoft/WSL#10485]
### Windows Version

Microsoft Windows [Version 10.0.19045.3324]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian buster-10

### Repro Steps

just run `wsl --shutdown`. from 5 times, my system will freeze 4 times and I can't do anything except force shutdown with power button on my laptop.

### Expected Behavior

`wsl --shutdown` should work smoothly without affecting the host windows os or freeze anything.

### Actual Behavior

just run `wsl --shutdown`. from 5 times, my system will freeze 4 times and I can't do anything except force shutdown with power button on my laptop.

**Comment by wbedard** [comment]
- I experienced (possibly) this issue just today.  In my case, I had recently updated both the graphics driver and a process performance driver (Process Lasso...) when I noticed that my machine would occasionally freeze for a few seconds, typically when closing down a random program. Since my computer is normally rock-stable, I prepared to shutdown my computer to start tracing the issue down, focusing on these recent updates.  As I was closing everything in my session down, I issued the wsl --shutdown command and my computer froze.  While I assumed the system would recover in a few seconds as with the other freezes, the WSL-associated freeze persisted even after 10 minutes, at which point I hard reset.
- I don't normally leave WSL running in the background but I had been performing some Docker tutorials in this session and had left my Debian-based WSL session running in a Windows Terminal tab for a few days when the freezes started happening.
- I am happy to provide dumps and logs for troubleshooting but would request guidance on at what point those artifacts should be collected, given that at the point of the system freeze, they will not be available.
