### ISSUE TITLE
Filesystem problems: Consolidated

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/WSL#1051]
Consolidated problems.

**Comment by SRGOM** [comment]
Its very likely that I'm doing something really stupid here but I see that my Windows fs is inconsistent in terms of actual content. Can someone verify (or tell me what I'm doing wrong)?

Steps:

Powershell
```
PS C:\Users\WINDOWSUSERNAME\projects\sample\cpp> cat .\Makefile
main: main.cpp
```

WSL:
```
[X220 /mnt/c/Users/WINDOWSUSERNAME/projects/sample/cpp]cat makefile
all:
        g++ $(P).cpp -o $(P)
```

Expected:
Both should have same data

Seeing: 
Both have different data, one has `main: main.cpp`, the other has `g++ ...`

Windows ver:
Microsoft Windows [Version 10.0.14393]

**Comment by iz0eyj** [comment]
@SRGOM Yesterday I ran into a problem, seemingly random, in the management of access rights.
I have many directories mapped through symlink to the Win side and yesterday the MonoDevelop could not modify the files contained in one of them.
I haven't reported it because I can't figure out how to replicate it.
I also had the problem of the files created and/or modified on the side Win not visible from WSL but I don't opened a thread because he had already been reported.

**Comment by iz0eyj** [comment]
Cannt umount ntfs drive:

Frederick @ BEAST: ~ $ mount
Mount:/proc/self/mountinfo: parse error: ignore entry at line 17.
Mount:/proc/self/mountinfo: parse error: ignore entry at line 18.
lxfs on/type rootfs (rw, noatime)
data on/data type lxfs (rw, noatime)
cache on/cache type lxfs (rw, noatime)
MNT on/mnt type lxfs (rw, noatime)
sysfs on/sys type sysfs (rw, noatime)
proc type proc (rw, noatime) on/proc
cgroup cgroup on type/acct (rw, noatime)
None on/dev type tmpfs (rw, noatime, mode = 755)
devpts on/dev/pts type devpts (rw, noatime)
None on/run type tmpfs (rw, noatime, mode = 755)
None on/run/lock type tmpfs (rw, noatime)
None on/run/shm type tmpfs (rw, noatime)
None on/run/user type tmpfs (rw, noatime, mode = 755)
None on/mnt/c type drvfs (rw, noatime)
None on/mnt/d type drvfs (rw, noatime)
None on/mnt/x type drvfs (rw, noatime) *** TARGET DRIVE ***
binfmt_misc on/proc/sys/fs/binfmt_misc type binfmt_misc (rw, nosuid, nodev, noexec, relatime)

Frederick @ BEAST: ~ $ sudo umount/mnt/x
umount:/proc/self/mountinfo: parse error: ignore entry at line 17. *** ERROR ***
umount:/proc/self/mountinfo: parse error: ignore entry at line 18.

Frederick @ BEAST: ~ $ ls-al/mnt
total 20
drwxr-xr-x 2 root root 0 Sep 5 14:12.
drwxrwxrwx 2 root root 0 Sep 2 14:34 ...
drwxrwxrwx 2 root root 0 Jun 12:12 4 c
drwxrwxrwx 2 root root 0 Jun 12:12 4 d
drwxrwxrwx 2 root root 0 Sep 5 14:12 x * * * X IS STILL HERE ***

If i try to disconnect it from Win I get this becaus X is still in use:
![cattura](https://cloud.githubusercontent.com/assets/6331284/18247869/619394aa-7375-11e6-8fac-7c0ce843fc54.JPG)

**Comment by rodrymbo** [comment]
Just a quick note here until the Devs get back from Labor Day Weekend:

`Makefile` and `makefile` are different files to NTFS and Linux/WSL, but until lately Windows has been blocked from making both files in the same folder because Windows is insensitive to difference in case. It still gets confused because it can't tell the difference. Linux relies on this behavior (case sensitivity), so it has been made available on the WSL side. Since Windows doesn't handle it very well, when you use it in a folder  on the WSL side, don't use that folder with Windows, or if you do, expect strange things to happen.

The VolFS file system (all file paths that don't begin with /mnt, such as /home) has been set up to be much closer to Linux standards than is normally available under Windows. Consequently the Windows side hasn't been able to create files properly in VolFS, and it may never get this capability. %LOCALAPPDATA%\lxss has been hidden from Windows, which some might think is a clue not to use Windows there. If you need to access files in VolFS (e.g. /home/whatever) first use Bash.exe to copy them to someplace that begins with /mnt, then use Windows to your heart's content on them, then use Bash.exe to copy them back when you are done. (At least for now.)

Yes those are inconsistencies, but they are [pretty well known](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/). Whether they are bugs or features is another story. If you accept the two rules (don't use the WSL to create both `Makefile` and `makefile` in folders where Windows might need to read them, and don't use Windows to access files in `%LOCALAPPDATA%\lxss`) things actually aren't too bad. If you break those rules, inconsistencies  can be expected. 

You might be able to get more traction suggesting how those design decisions should have been handled on the [Uservoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) site.

The handling of symlinks and hardlinks has been problemmatic. The current design seems to rely on different functionality for it between the WSL side and the Windows side. The design decision that was made says that NTFS symlinks and other reparse points probably won't work from the WSL side, and symlinks and hard links made while you are in Bash.exe (WSL) won't work on the Windows side. Some of us think that at least existing NTFS reparse points should be honored/followed when encountered in WSL (assuming permissions allow) even if you can't create or change them while in WSL. But that's not how the devs implemented it. So for now, you might want to use a naming scheme or something so you can tell which ones were made (and can only be used) in WSL, and which are reparse points in Windows that won't work properly in WSL.

Good luck enumerating these and other inconsistencies.

**Comment by GSam** [comment]
@rodrymbo 

> Consequently the Windows side hasn't been able to create files properly in VolFS, and it may never get this capability.

I've managed to get a guest share running of Samba's smbd that is plausibly accessible from Windows. That provides an interesting avenue to this overall problem.

**Comment by rodrymbo** [comment]
@GSam - it's actually [pretty simple to get the ssh server running](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10), at which point one can use sftp to access files in VolFS. Several programs I know and use (e.g. Notepad++) can access SFTP servers pretty much as readily as local filesystems. 

Congrats on getting Samba running! Don't say it too loud or others will ask you how you did it. ;)

**Comment by vpArth** [comment]
Yeah, @GSam, how you did it? Using some patched version? Original smbd failed to start because can't to get network interfaces...

**Comment by therealkenc** [comment]
Ran course. [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md)
