### ISSUE TITLE
2 compte Microsoft avec la même adresse mail

### ISSUE THREAD

**Issue by arcstorming** [microsoft/WSL#10519]
Bonsoir j'ai un problème j'ai 2 comptes Microsoft avec la même adresse mail. Mon compte principale avec toute mes données de jeu et personnel est le compte fantôme que j'ai plus accès. Et l'autre compte est un compte qui la remplacer avec rien dessus que j'ai accès. J'aimerai récupérer le compte fantôme mais le problème c'est que je sais pas comment. SI vous pouvez ressoudre mon problème merci.

**Comment by zcobol** [comment]
Here's the English version via translate.google.com:

`Good evening I have a problem I have 2 Microsoft accounts with the same email address. My main account with all my game and personal data is the ghost account that I no longer have access to. And the other account is an account that replaces it with nothing on it that I have access to. I would like to recover the ghost account but the problem is that I don't know how. If you can solve my problem thank you.`

and it doesn't look like a WSL issue!

**Comment by OneBlue** [comment]
This issue is not related to WSL. Closing.
