### ISSUE TITLE
Recycle Bin Support

### ISSUE THREAD

**Issue by shafayetejaman** [microsoft/WSL#10605]
WSL vs-code does not move the deleted files to the Windows trash bin, it deletes the files permanently.
It should move the files to the recycle bin because its vary common to delete files by mistake.

**Comment by SHREYASH96OG** [comment]
You can recover the VS Code files to the previous version. If you accidentally deleted Visual Studio Code, you need to go to the folder which includes the deleted file and then restore the previous version of the folder. This method is also suitable for restoring the previous version of overwritten VS Code files.

It is mentioned that this method requires users to have turned on File History or created a restoring point. Otherwise, it is useless.

Follow the steps to recover permanently deleted Visual Studio Code files.

Step 1. Locate the folder which includes the deleted Visual Studio Code files.

Step 2. Right-click the folder and select “Restore previous versions”.
![vscode _file_re](https://github.com/microsoft/WSL/assets/96031865/003c36e2-6040-4477-b0da-3faa032a2768)
Step 3. According to the name and date modified, select the version you want to recover and click “Restore” > “OK”.

**Comment by SHREYASH96OG** [comment]
Simplest way to recover file that is deleted by mistake is by using undo button in from Edit option
![Screenshot from 2023-10-07 23-19-27](https://github.com/microsoft/WSL/assets/96031865/8ade9a27-742e-496c-a32d-b518e6770f48)

Hope This Simple method helps you

**Comment by shafayetejaman** [comment]
still not a user-friendly experience and ctrl + z does not work with folders

**Comment by OneBlue** [comment]
This is not something that WSL controls. 
I recommend opening an issue on [vscode](https://github.com/microsoft/vscode/issues)

**Comment by Lysander086** [comment]
> This is not something that WSL controls.
I recommend opening an issue on [vscode](https://github.com/microsoft/vscode/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen)


@OneBlue 
this is a file deleted from VS code and deletion would move the file to the recycle bin of the Windows 11. 
I think this should be taken charged by WSL.

<img width="599" height="46" alt="Image" src="https://github.com/user-attachments/assets/be57395e-e7b0-4953-8b7e-90fa9476b6e9" />
