### ISSUE TITLE
wsl --install --no-launch does not install the distro

### ISSUE THREAD

**Issue by fanoush** [microsoft/WSL#10646]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

any

### Repro Steps

```
wsl --install Ubuntu-22.04 --no-launch --web-download
Downloading: Ubuntu 22.04 LTS
Installing: Ubuntu 22.04 LTS
Ubuntu 22.04 LTS has been installed.

wsl -l -v
  NAME                   STATE           VERSION
  Debian                 Stopped         2
```
Ubuntu is not in the list

### Expected Behavior

Ubuntu-22.04  is fully installed so that `wsl -l -v` would list the distro and it would still not launch it so I do not end in interactive linux shell.

### Actual Behavior

`wsl -l -v` does not list the distro as installed

`wsl --help` says
```
            --no-launch, -n
                Do not launch the distribution after install.
```
However it does something different than described. Not only it does not launch it, it also does not install it =  it does not install the distro into registry `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` so it is not visible via `wsl --list`. And the only way to continue is to call ``wsl --install Ubuntu-22.04` again (!?) which will in this case  not download distro from microsoft store but just continue and run the create user step and finishes registry setup and then launches the distro linux shell.

So there is no way to really install it fully without ending in interactlive linux bash shell command line.

However  I understand that for finishing the install user and password is needed. The registry has `DefaultUid` which needs to be filled and the vhd file with root filesystem needs to be modified to have username with password created before it is usable so that step needs to be done for finishing the install.

To skip the interactive step the --install would need to have something like  --username and --password, then it could modify the rootfs, install registry keys and still not launch the distro at all.

Or without those parameters it could setup the user interactively like it does now and then exit without launching the linux shell.

**Comment by OneBlue** [comment]
This is by design. WSL doesn't actually "install" the distribution but only the application which registers the distribution. There is unfortunately no way for WSL to control what ubuntu.exe / debian.exe and others do when invoked, which is why we added this --no-launch flag to prevent launching the distribution executable in the first place.

**Comment by panayasagam** [comment]
Been struggling with the same thing for a while now.
It turns out after running `--install`, you have a `ubuntu` executable available.
You can use that to complete the installation AND regain scripting control once the installation is done:

```powershell
# Run something before the installation

wsl --install Ubuntu --no-launch
# This ask the user for a new username and password, then release the script
ubuntu install

# Run something after the installation
```

Taking this a step further, you could provide `--autoinstall SOME_CONFIG_FILE` and have it install Ubuntu with a default user and password.

https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html

**Comment by fanoush** [comment]
Thanks for the tip. What I was actually trying to do, when reporting this issue,  was to download the distro by `wsl --install` and then immediately export it via `wsl --export ... --vhd` and then uninstalling it so I could have vhd of clean unmodified system for doing wsl --import-in-place later possibly on another computer.

So I expected that wsl --install --no-launch would somehow prepare this  for export with the distro registered but no user/password set and that I could possibly continue with the personalization later after --import. But never mind, it was not that important.
