### ISSUE TITLE
Bash network unuseable if started after antivirus

### ISSUE THREAD

**Issue by krisclarkdev** [Microsoft/WSL#1065]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  Bash network unuseable if started after antivirus
- Expected results
  To be able to use network with bash regardless of antivirus
- Actual results (with terminal output if applicable)
  Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main libcairo2 amd64 1.13.0~20140204-0ubuntu1.1
  Connection failed [IP: 2001:67c:1360:8001::21 80]

Issue is similar to networking issue [here](http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/problems-reinstalling-bash-on-ubuntu-on-windows/bb32e0a5-e711-410b-b28b-ebc561d5b4d8?auth=1).
- Your Windows build number
  14393.105
- Steps / commands required to reproduce the error
  Open bash with anti-virus shutdown, not disabled.  Then preform any network dependent operation.  For A-B testing run apt-get install git  this will work.  Then remove git.  Exit bash and start your antivirus and reinstall git.  This will fail.  If bash is opened before antivirus starts then antivirus is started after bash then the network in bash will work.
- Strace of the failing command
  NA
- Required packages and commands to install
  NA

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by rodrymbo** [comment]
This simply means your antivirus (and/or firewall) is doing what it is supposed to do: block programs or networking it doesn't know about. WSL is a beta program, by definition it is new. Most antivirus/firewall programs, especially the more paranoid, block **new** things by default. The other part of the issue is that it may be impossible to tell your antivirus/firewall program to allow WSL programs or networking, because they are using a new functionality in Windows that didn't exist when the AV programs were produced.

**Comment by sunilmut** [comment]
All AV/firewall related discussions are captured in #475.  Please refer to that issue for further details. Marking this one as duplicate.
