### ISSUE TITLE
WSL2 does not boot with localy installed DNS server

### ISSUE THREAD

**Issue by suikast42** [microsoft/WSL#10889]
### Windows Version

Windows 11 Enterprise 10.0.22621

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04.3 LTS

### Other Software

[technitium dns](https://technitium.com/dns/)

### Repro Steps

I have installed [technitium dns](https://technitium.com/dns/) as windows service. 

When I boot my host and try start WSL2 then the I hot the error:

```
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\<user>\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
Press any key to continue...
```

When I turn off the DNS service  start WSL2 and start the DNS server then everything is running fine. Even if I do shutdown wsl with  `wsl --shutdown`

### Expected Behavior

WSL2 starts

### Actual Behavior

```
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\<user>\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
Press any key to continue...
```

**Comment by oakrc** [comment]
I experience the same issue on Windows Pro build 22631.2861 & WSL2. I'm using Acrylic DNS Proxy and WSL distro fails to start with the same error. Stopping the service allows the distro to start, then starting the service afterwards doesn't interfere with WSL.

**Comment by oakrc** [comment]
Here's the logs:
[WslLogs-2024-01-06_10-37-59.zip](https://github.com/microsoft/WSL/files/13850839/WslLogs-2024-01-06_10-37-59.zip)

**Comment by OneBlue** [comment]
Here's the root cause: 

```
1528	False	Microsoft.Windows.Hyper.V.NetMgmt	NetMgmt::GetNetworkAdapterType	0	01-06-2024 10:38:29.747	"	"	"Adapter: 	{279ACCDE-1C2A-493F-B760-8D7959ED3291}
ErrorID: 	-2147217406
Message: 	netcfg->FindNetworkAdapterWithInstanceGuid returned an error"				3912	3736	2		00000000-0000-0000-0000-000000000000		

```

@keith-horton: Is a known issue ?

**Comment by keith-horton** [comment]
Sorry, that's not the root cause. The original source of the failure is this:

 2064 03912.03244 2024-01-06T10:38:28.920 [Microsoft-Windows-Host-Network-Service] 'IpICSHlpStartDnsServer' : '0xFFFFFFFF'. 
 2065 03912.03244 2024-01-06T10:38:28.920 [Microsoft-Windows-Host-Network-Service] ActivityError: PartA_PrivTags=16777216 wilActivity={ hresult=4294967295, ... }  

@oakrc , can you please see if the shared access service is running. From the traces we have, it looks like attempts to RPC to that service are failing.

sc query sharedaccess


We'll need network logs to hopefully pinpoint what failed. https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1

Thanks!

**Comment by notseb** [comment]
I had the same issue with Win 11 Pro 22000.2538 and Technitium DNS Server. 
[WslLogs-2024-01-15_08-58-53.zip](https://github.com/microsoft/WSL/files/13936419/WslLogs-2024-01-15_08-58-53.zip)
Stopping the service/Uninstalling fixes it.

**Comment by johnrix** [comment]
Same problem for me with Technitium also.
[WslLogs-2024-02-08_22-37-36.zip](https://github.com/microsoft/WSL/files/14215399/WslLogs-2024-02-08_22-37-36.zip)

PS C:\Users\john> sc query sharedaccess

SERVICE_NAME: sharedaccess
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by keith-horton** [comment]
This looks to be failing because SharedAccess is trying to bind to 0.0.0.0:53, but something is already bound to that port. If Technitium runs a DNS Server, then that would prevent WSL to start in this mode.

If you are on Windows 11, you can use dnsTunneling instead (which is actually more reliable).

**Comment by johnrix** [comment]
I'm not 100% certain what DNS tunnelling will do for me off-hand. I see a few posts about it being added last year, and now being enabled by default, but I didn't find a clear explanation of how it works or how to make use of it. Do you have a link handy?

My use case for Technitium is to define wildcard subdomains that all route to my WSL instance that is running my development web server. Can DNS tunnelling step in and address that?

In any case, I did find after my earlier post above that switching Technitium to bind to 127.0.0.1:53 instead of 0.0.0.0:53 solved the start up issue for me, which is consistent with your summation above.

**Comment by johnrix** [comment]
Would I be able to set up that wildcard A record as described with DNS tunnelling? Although Technitium is fine at the moment, I would be happy to remove it from my toolchest if I can achieve the same without it.
