### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by ElGoorf** [Microsoft/WSL#1088]
I sudo `rm -R`'d a directory, which didn't delete. It now remains, but in blue text (see screenshot). If I try to delete it via windows, I get told I don't have permissions. `ls -l` shows the directory, but with permissions: "d????????????". Any modifications I try to make to the folder, or permissions, I get told the directory doesn't exist.

![image](https://cloud.githubusercontent.com/assets/1381698/18593817/07fb168e-7c35-11e6-9cc5-04201e4046ff.png)

> root@DESKTOP-EGHC1UB:/mnt/f/Web Dev# ls -l
> ls: cannot access react-game-lobby-browser: No such file or directory
> total 64
> drwxrwxrwx 2 root root 0 Jun 30 21:26 accountability
> drwxrwxrwx 2 root root 0 Nov  7  2015 angular-sandbox
> drwxrwxrwx 2 root root 0 Apr  6 16:15 card-game
> drwxrwxrwx 2 root root 0 Mar 30 10:04 charts.radiox.co.uk
> drwxrwxrwx 2 root root 0 Mar 29 11:33 ClassicHOF
> drwxrwxrwx 2 root root 0 Oct 20  2015 google-maps-drag-file
> drwxrwxrwx 2 root root 0 Apr  6 15:29 halloffame.classicfm.com
> drwxrwxrwx 2 root root 0 Mar 26 15:27 logs
> drwxrwxrwx 2 root root 0 Jul 12 14:41 node-card-game
> drwxrwxrwx 2 root root 0 Jul 12 00:25 node-cards
> drwxrwxrwx 2 root root 0 Sep 12  2015 node-irc-tracker
> drwxrwxrwx 2 root root 0 Aug 12 21:19 promo.capitalradio.co.uk
> drwxrwxrwx 2 root root 0 Mar 30 18:00 promo.heart.co.uk
> drwxrwxrwx 2 root root 0 Mar 30 18:18 promo.lbc.co.uk
> drwxrwxrwx 2 root root 0 Aug 12 21:14 promo.musicradio.com
> drwxrwxrwx 2 root root 0 Sep 15 11:14 react
> d????????? ? ?    ?    ?            ? react-game-lobby-browser
> drwxrwxrwx 2 root root 0 Sep 15 14:59 react-tweets
> drwxrwxrwx 2 root root 0 Dec 18  2015 SmoothXmasTop50
> drwxrwxrwx 2 root root 0 Oct 20  2015 travel-app
> drwxrwxrwx 2 root root 0 Oct 24  2015 travel-app-angular
> drwxrwxrwx 2 root root 0 Oct 20  2015 travel-app - Copy

Update: I gave up and closed terminal, at which point the folder instantly disappeared.

**Comment by iz0eyj** [comment]
@ElGoorf I esperienced this issue using Win side folder linked (symlink) with WSL.
I solved by deleting the link, trying to delete the file from Windows (impossible), and then after waiting a bit ... puffffff, the file disappeared. At that point I created the link again.
So you can try to delete it from Win side.

**Comment by rodrymbo** [comment]
I've seen it too. After a while (or a restart) the file deletion does actually complete. It acts like something in the system is working to delete the file and just hasn't completed the task for some reason, or else that bash doesn't get the message that the file is actually gone, like a view of the filesystem needs to be refreshed.

**Comment by hirnlego** [comment]
I'm experiencing this problem as well.  I have a Symfony 2 site in development and sometimes, when reinstalling the assets, one or more files remains in the assets dir with question marks instead of the normal stats. E.g.:

`-????????? ? ?    ?    ?            ? ladda.min.js` 

If I try to delete the file via Windows Explorer it says that I don't have permission. This happens even if I try to change the permissions, it complains that I don't have read permission and there nothing I can do.

Waiting/rebooting is not the best solution here...

**Comment by therealkenc** [comment]
This is an old one that went chirping crickets out of the gate for lack of CLI repro steps to end up in the `-?????????` permissions state. Lots of filesystem water under the bridge since the submission. If the OP or anyone can repro the strange perms state on the April 2018 release (aka RS4 aka release 1803 aka build 17134) please reboot this one in a new issue.

**Comment by rainabba** [comment]
I just hit this again after doing `rm -rf node_modules` (which has an absurd number of folders/files in case you're not familiar), then hitting Ctrl-C because it was taking WAY too long. I then tried to Shift-Delete in Explorer and it appeared to work until it started reporting folders/files not found. I expected it was from the `rm -rf` so I used the 'skip' option and let it complete. Now I see the folder in Explorer, but if I try to do anything with it, I'm told it doesn't exist and in Ubuntu 18.04 (running on 1803), I see the odd ACL entry and can't remove or chown it, even with sudo.

I've hit this before and I believe a reboot was required. Going to try restarting Explorer (after I close ALL my work) and if that doesn't take, I'll reboot; then I'll report back.
