### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by lioupayphone** [Microsoft/WSL#1099]
Bash on Ubuntu on Windows is an awesome tool. But I think it will be a perfect tool if some features were supported in future.
1. user-defined color and font defination: you know changing the default font and color scheme in cmd/powershell is very difficult. 
2. mouse support: when using vim/emacs, mouse scrolling is important if editing a large file.
3. clipboard shortcut is not supported well: I guess this is a bug (maybe).

**Comment by fpqc** [comment]
All of these things will probably be available in the future and are already on Uservoice related to the planned upgrades to conhost.

The other option is the project https://github.com/mintty/wsltty

Which uses a cygwin terminal-aware bridge to replace the conhost-only bash.exe.  If you run the wslbridge directly, it is almost exactly like running bash.exe (the terminfo used is the one for cygwin's bash (cygbash?) running as a Windows console program instead of xterm, used by bash.exe).  Microsoft's bash.exe, I think, tries to parse or convert  some of the xterm escape sequences, and this is where a lot of the bugs seem to be coming from.

When you run the wslbridge in mintty, mintty identifies itself as xterm-256color, and the wslbridge will pipe it unconverted xterm escape sequences, which I think would show up really weird in conhost, since not all are supported

**Comment by therealkenc** [comment]
[wsltty](https://github.com/mintty/wsltty) is a great project. Mintty supports [Sixel](https://en.wikipedia.org/wiki/Sixel), which means [libsixel](https://github.com/saitoha/libsixel) works. So... xterm in [Xsixel](https://github.com/saitoha/xserver-sixel) on Bash on UoW in Mintty is possible. Which is wrong. So very very wrong.

![wsl-xterm-xsixel](https://cloud.githubusercontent.com/assets/7049700/18698337/2531d494-7f7e-11e6-9ff5-15e67660693d.png)

**Comment by zadjii-msft** [comment]
Whadda you know, give them true color, and they ask for sixel support. Next I'm guessing you'll want 3D video support directly to the console? :P  

I kid, I kid. In all seriousness:
 1. I'd love to have a better way of doing that. You're absolutely right that the current "Colors" dialog is a little bit terrible. It's definitely pretty high on my personal wants list, but not necessarily super high on the backlog (relatively speaking)
 2. Yea that'd be cool. I'd be into that.  *stares nervously at Insiders cadence*
 3. That's a little tricky. Everyone has their own prefered way of copy-pasting - Ctrl-C/V, Right Click, Middle Click, Ctrl+Shift-C/V, etc. These are all options I'd love to add to the properties sheet if we get a chance to get around to updating it, so, yes, it's definitely on the backlog.

**Comment by fpqc** [comment]
@zadjii-msft I think that the ConEMU guy has already figured out a way to hook conhost to grab mouse escape sequences.  Presumably if he can do it with at-runtime hooking, it's possible to do with access to the Windows sourcecode =].

Also, he may also have gotten sixels to work.  He's got image thumbnail previews running in the FAR manager (or maybe he's doing it with a dirty and horrible hack!) 

Good luck!

**Comment by therealkenc** [comment]
YouTube videos [stream okay in mintty](https://github.com/saitoha/FFmpeg-SIXEL), though the palette based protocol could suckless (I still love the Ballmer video). The GL [demo](https://raw.githubusercontent.com/saitoha/libsixel/data/data/example_opengl.gif) works okay too, though agreed it could be faster. OpenGL extensions after someone decides what numbers to put in the new CSI codes and pushes a PR to mintty... 😜

**Comment by neurogenesis** [comment]
One of the reasons I switched to Macs in the first place was iTerm. The native support for Linux terminals, ssh/scp and all the BSD & GNU goodness of tools like grep / awk / sed.

Up to that point I had been using cygwin + local ssh server + putty to localhost. This worked, but obviously wasn't ideal.

Would really love to see a terminal on the windows OS that has the functionality of iTerm (windows, tabs, tmux support, profiles, triggered events, regex searches, etc.). Would love it if MS would just throw some $$ and resources at the iTerm project for a port. Being able to use the same terminal app across Mac and Win would be fantastic.

**Comment by fpqc** [comment]
@neurogenesis Eh?  I'm sure we'll see tabs sooner or later, and I think it's very likely that we'll be able to run tmux in WSL in conhost, then the Windows-side cmd or powershell in tmux (you can already do this with cbwin if you really want).

**Comment by neurogenesis** [comment]
Sorry, my bad for not going into detail with the additional functionality that a terminal app like iTerm offers.

Multiple native panes in the same window (not just tabs). The regex searches & highlighting (useful for highlighting incoming events), ability to dynamically switch profiles with keyboard shortcuts (or automatically switching color profiles when running sudo or connecting to a different host). Rich support for fonts and terminal colors. Configurable hot keys / key mapping.

Instead most win options are little better than a DOS cmd prompt window (with a handful of improvements inherited from powershell, like finally supporting window resizing).

I applaud the better support for native-ish access to Linux shells and utilities. But there is still a huge gap in terminal usability on the windows platform.

**Comment by fpqc** [comment]
@neurogenesis You can run gnome-terminal or tilda with an X11 server.

**Comment by neurogenesis** [comment]
I think ConEmu is probably the closest to iTerm. Good enough for the short-term, and hopefully some of their features will keep pace with iTerm.

Still some issues with login and shell selection though (not terminal related but more just the entrypoint into the subsystem. I noticed there was a feature request for full shell login support. What's the roadmap look like for BashOnWindows?

**Comment by fpqc** [comment]
@neurogenesis More syscalls, more sockopts, more ioctls, better FS performance.

Oh  and they're try

**Comment by alatnet** [comment]
Well, since this is a feature request for WSL.
Can I suggest a way to update the subsystem without having to join the insider program?
So for those that are running a stable RTM (or something like that) version of win 10 can easily update the subsystem and gain the features of newer versions of the subsystem like the windows interop.

**Comment by Nogitsune101** [comment]
Personally I'd like to see more access to networking components.  A large amount of the issues I've run into seem to have been network related.  Some kind of Windows side network mapping configuration utility for bash would be ideal allowing for virtual network adapters in linux that can be bridged to windows and alternative ip addresses.  I think this would solve some of the port conflict issues I'm having with server services I use.  localhost could then remain for Windows but I could assign 127.0.1.1 or even 192.168.0.201 to WSL. If you could register hostnames into Windows that would also save me a trip to the hosts file in Windows too.

Extending functionality in some languages that don't quite have the tools built for them involve calling calling console commands (These are generally avoided because of security issues/compatibility) but some third party libraries do this and not having access to all standard linux commands in /usr/bin can be a headache.  If ifconfig doesn't work, I wonder what other things don't work . . .

Having Windows drive mount points in /mnt/ is nice, it is more useful to have them in dev to be mounted wherever they are needed using fstab.  For now linking them is an alternative, but I find it annoying (and I haven't tested but probably doesn't work if symlinks are not allowed in services).  

This one is a long shot, but since we are talking integration, adding NFS support to Windows 10 Pro or including it in the developer tools for WSL would be really really nice.  Currently, this is only available in Windows 10 Enterprise.

I apologize in advance if I'm repeating anything already said but I'd really like to switch off Virtualbox for development . . . so . . . waiting patiently.

**Comment by DarthSpock** [comment]
@zadjii-msft 

> Whadda you know, give them true color, and they ask for sixel support. Next I'm guessing you'll want 3D video support directly to the console?  :P 

All kidding aside, it would be great if this was a reality, not just for WSL but Powershell and *maybe* CMD. I don't want have to do all that leg work of installing Cygwin, then [wslbridge](https://github.com/rprichard/wslbridge), then [wsltty](https://github.com/mintty/wsltty). I feel that's too much effort plus I'm installing something that I could use instead of WSL. I rather not install Cygwin at all. I created a [Uservoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/33181663-libsixel-support-for-cmd-powershell-wsl) requesting this native support under the Console/Terminal label since this pertains to terminal capabilities.

**Comment by fpqc** [comment]
WSLBridge is a one step installation..

**Comment by DarthSpock** [comment]
WSLBridge doesn't install WSLTTY. Plus the fact all these things exist prove that it's not currently part of the existing infrastructure. I'm just thinking if it turns out they aren't going to do any GUI work, then they can at least put support into having sixel out of the box. Frankly I'm surprised someone hasn't put a request for it already. I've noticed from the small few mentions you made about it in two other console issues this would be something you'd want as well.  Lastly, I'm not willing to install Cygwin if I'm using WSL. If I'm installing Cygwin, then I'm not looking at using WSL until it's more POSIXy but still with plenty of interop like Cygwin has. I don't believe I'm only one with that viewpoint. Also, it would very hard to justify to a corporation to install both for the same purpose. Wsltty and wslbridge are good for at home, not so much in the corporate environment. Feel free to correct me if that isn't how it really is.

**Comment by fpqc** [comment]
wsltty and conemu now support native-launch of wslbridge without installing or maintaining a cygwin installation.  ConEmu has a default task now that works perfectly (it launches wslbridge through its built-in cygwin bridge).

**Comment by DarthSpock** [comment]
Thanks for educating me. I didn't realize it was all-together in one install. Trying to recreate the above shown image of sixel using wsltty. Looks like a few more steps are needed for sixel anyways. Still the Windows Console can still do native support for it, even if it's not installed by default. Powershell would probably need to do something so they could just `git` libsixel but as long as the underlying` conhost` supports it, I'd say we are good.

**Comment by fpqc** [comment]
Conhost doesn't support sixels. WSLbridge connects a pty through tcp rather than to a conhost  instance.  Conemu has a native bridge that takes a cygwin pty (this is what wslbridge provides) and connects to it. Wsltty connects Mintty to the same cygwin pty.  Neither method goes through conhost.

wslbridge does launch conhost and hides it,  but this is likely no longer necessary since background instances of WSL are now allowed.

**Comment by DarthSpock** [comment]
I was saying Conhost doesn't support sixels. That's what I would like to see changed. Basically I want wsltty to become useless to WSL. Anything wsltty can do, I think MS should make the console do. This is more than just sixels of course but that would be a starting point.

**Comment by bitcrazed** [comment]
Thanks for the asks, but please only include one bug/ask per issue - it's difficult to effectively manage multiple asks/issues in one thread.
 
1. user-defined color and font defination: you know changing the default font and color scheme in cmd/powershell is very difficult.
2. mouse support: when using vim/emacs, mouse scrolling is important if editing a large file.
3. clipboard shortcut is not supported well: I guess this is a bug (maybe).

In [Creators Update (1703)](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/), we:
1. Added [24-bit color support](https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/)
1. Added mouse scroll & click support

In [Win10's Console in Fall Creators Update (1709)](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-windows-console-in-windows-10-fall-creators-update/), we:
1. [Updated the default Console color palette](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) (on new Installs) for the first time, improving colors on LCD screens, improving contrast, etc.
1. [Shipped a ColorTool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) that allows you configure the Console's color palette to colors specified in theme files

In [Win10 Spring 2018 Update (1803)](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/), we:
1. [Added CTRL + SHIFT + [C|V] Copy/Paste support](https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/) for Linux Console instances.

Therefore, closing this issue for now. If you have further issues or asks, please open new issues (or comment on existing issues) in our [Console Issues](https://github.com/microsoft/console) repo.
