### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by qggjonny** [Microsoft/WSL#1112]
You did a great job, but Chinese display is not perfect, and I can't type Chinese.Please support Chinese display and input，thx

**Comment by imjakey** [comment]
chinese input is ok, but input panel can't display.
![ec7a290e-2cf9-4b97-a7eb-51dc6ca294fc](https://cloud.githubusercontent.com/assets/2662273/18757431/7ee77dfa-8126-11e6-8f4b-154c433c1308.JPG)

兄弟，你好，哈哈！

**Comment by qggjonny** [comment]
Which input method do you use? I use the input method of the os, it can not input

**Comment by fpqc** [comment]
@qggjonny Try using http://github.com/mintty/wsltty

**Comment by qggjonny** [comment]
@fpqc thank you! It is perfect.But I hope Microsoft can support Chinese on bash on wsl.

**Comment by fpqc** [comment]
@qggjonny Yeah, they are very much aware of the problems with the console support for lots of stuff, but I don't know how high on the list localization is.  I think they are probably trying to get simple latin-alphabet text entry working pretty much bug free, then tackling localization support, fixing it all at once.  wsltty stays in UTF-8 from beginning to end, so there is no weird half-finished console conversion of text and escapes.  

I don't mean to dismiss MS's efforts to improve the native console experience, but you can use mintty for great wsl support (using the wslbridge, which is where the magic happens), and even for good Windows console support using the winpty project, which allows you to run generic Windows console programs like cmd and powershell also  inside of a cygwin terminal like mintty.

Unfortunately because of incompatible licenses, it is not possible for MS to just replace a core OS component like the console host with some random github projects using cygwin, so MS is going to unfortunately have to reinvent  the wheel on this occasion, sort of like how FreeBSD had to reimplement tons of coreutils code in 2010-2014 bc the gnu coreutils were not under a compatible license with the BSD one.

The upshot, however, is that once MS upgrades the console, they will probably be able to just forget about it for another 20 years, since the only innovation I can think of in the land of vterms in the last 15 years is support for 24-bit color escapes.

**Comment by fpqc** [comment]
Ignore my previous post. 14931 has 24-bit color support native.  That's basically half of the big steps.  The other half is probably mouse support.

**Comment by abcfy2** [comment]
Sogou pinyin input method cannot work. I can't call for the input method. And, if the file or directory contains Chinese characters, the `<TAB>` key cannot complete the path correctly.

![qq 20161204213642](https://cloud.githubusercontent.com/assets/5327677/20866542/13af795c-ba6a-11e6-96d3-e4f47f0eacd7.png)
![qq 20161204213835](https://cloud.githubusercontent.com/assets/5327677/20866541/12e76f34-ba6a-11e6-8238-e1fffee6b057.png)

windows version: `Microsoft Windows [版本 10.0.14393]`

**Comment by therealkenc** [comment]
Dangling console tag issue. There have been lots of improvements to Windows console since 14393, and if I understand correctly there is more to come. Please reboot this one in the [Windows Console Tracker](https://github.com/microsoft/console) if you are seeing problems rendering Chinese characters correctly.
