### ISSUE TITLE
Official Win32 API for pty functionality

### ISSUE THREAD

**Issue by be5invis** [Microsoft/WSL#1117]
So we can implement a native tmux in Windows, and run Bash and PowerShell side-by-side.

**Comment by fpqc** [comment]
Already done in cygwin, and can also be done in WSL.  Maybe this might be implemented in an official Win32 api as part of the console team's work, but we will see.

**Comment by bitcrazed** [comment]
Thanks for the ask; we're looking at ways to address this.

**Comment by ericblade** [comment]
Is this possibly related to how since going to AU, I can no longer Remote Desktop into anything else on my network?  RD complains that I already have a console session running (and it isn't clear if it means on the remote, or on the local)  (not entirely sure I understand what the problem is here, though, just thought about it when I read the email notification)

**Comment by fpqc** [comment]
@ericblade No way.  I am running WSL insider builds at work on the pc I use to administer the server.  No problems with (direct) remote desktop or Remote Desktop over Hyper-V

**Comment by ericblade** [comment]
Thanks. I suspect that the problem lay on the remotes, but the error message isn't clear.

**Comment by fpqc** [comment]
@ericblade If you have the opportunity, try a clean reinstall with AU.

**Comment by be5invis** [comment]
@rprichard

**Comment by be5invis** [comment]
@benhillis @miniksa @zadjii-msft
Any progress?

**Comment by DarthSpock** [comment]
This issue should be closed. https://github.com/Microsoft/console/issues/57 was created for this ask, which has been implemented in Insider build 17711 and just awaiting a few critical bug fixes before ready for public consumption.
