### ISSUE TITLE
Duplicate installs and environment path

### ISSUE THREAD

**Issue by artofit** [Microsoft/WSL#1119]
Win 10 64bits

Hi,

Several command line tools are installed on my PC.
If I run in a DOS window, commands such as "convert, ffmpeg, etc." no problem.

If I try with bash, than:
for convert it says: to sudo apt-get install <packet>
for ffmeg it says that the command can't be found. See also bug #1080

It's rather stupid to re-install apps + version & compilation will surely differ between the "dos" version and the "bash" version.

The bash ought to take the environment path and execute from there.

Imagine, if one has to install all the command line apps & tools (Java, etc.) is just duplicate, than it's better a VM or a dual-boot Win / Linux.

Thanks

**Comment by fpqc** [comment]
You're trying to run the Linux version of those programs.  Bash on Windows is actually a linux emulator built with a big driver attached to the NT kernel.  There are (unofficially, discovered by poking around at undocumented interfaces and files) plans to allow running of Windows applications from inside of this Linux layer.  There is an executable (actually a symlink, whatever) `/usr/bin/winrun` that will allow you to execute Windows executables from inside of bash.

The other option maybe is to just use Cygwin, which does what you want.  "BashOnUbuntuOnWindows (aka Windows Subsystem for Linux)" is in reality a replacement for running a virtual machine, not so much for using "Bash" on windows.  It allows compilation and running of native linux binaries by allowing the usual Linux syscalls to change context into the Kernel mode, but when they try to get executed by the NT kernel, the kernel sends them to the WSL drivers (lxss/lxcore) for translation.  

The reason why the drivers actually live in ring 0 is partially for speed and partially because it removes the overhead of trapping calls to ring 0 in usermode (basically the only way to do this is with virtualization).  The syscalls are really made, they really get sent to the kernel, and the kernel really executes them and really communicates with hardware.
