### ISSUE TITLE
'E342: Out of memory!' error in Vim after WSL update to 2.1.4.0

### ISSUE THREAD

**Issue by ianisl** [microsoft/WSL#11256]
### Windows Version

Microsoft Windows [Version 10.0.19045.4046]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04.6 LTS

### Other Software

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar  6 2024 20:00:24)
Included patches: 1-151

### Repro Steps

Disable automount via `wsl.conf`. Mount `/mnt/c/Users/<username>` via CIFS : 

```sh
sudo mkdir -p "/mnt/c/Users/<username>" && sudo mount -t cifs -o credentials="/path/to/credentials/file",uid=1000,gid=1000,vers=2.0,iocharset=utf8,file_mode=0777,dir_mode=0777 "//<host_address>/Users/<username>" "/mnt/c/Users/<username>"
```

Open a file on the mounted  `/mnt/c/Users/<username>` in vim. Make changes and save.

Note: I have been using CIFS to access my Windows home directory without any issue for the past ~2 years. In my experience (and on my machine) this provides a much faster access to the Windows home directory than via automount.

### Expected Behavior

The file should save successfully without errors.

### Actual Behavior

Vim displays the error message upon saving:

```
E342: Out of memory!  (allocating 18446744073709551615 bytes)
```

The file seems however to save correctly.

The issue does not appear when: 
- Editing a file on the WSL2 drive
- Editing a file in `/mnt/c/Users/<username>` if the latter is mounted via automount. I would however like to find a fix, since in my experience (and on my machine) mounting the Windows home directory via CIFS provides a much faster access than via automount. I have been using this solution without any issue for the past ~2 years and have only encountered an issue today, after an automatic WSL update to `2.1.4.0`.

What I have tried:
- Trying to set `experimental.autoMemoryReclaim` to `disabled` or `gradual` in `.wslconfig`, since the default option value seems to have changed in `2.1.3.0` (is it possible that my WSL updated directly from a prior version to `2.1.4.0`?)

**Comment by paultag** [comment]
I found this when trying to see if anyone else had seen this issue -- I found this when working on some cursed filesystem bits; I send a PR to vim -- it may be worth checking to see if this does anything for you too https://github.com/vim/vim/pull/14169 @ianisl

**Comment by ianisl** [comment]
Thanks! I'll check it ASAP and let you know.

**Comment by ianisl** [comment]
I can confirm that applying vim patch 9.1.0162 solves my issue 👍 

In your bug report in [https://github.com/vim/vim/pull/14169#issue-2177421617](https://github.com/vim/vim/pull/14169) you write that vim was probably masking a filesystem error in this case, so I'll leave this issue open since it may point to a new WSL issue relative to file systems mounted as CIFS.

**Comment by paultag** [comment]
Yeah absolutely! It means your listxattr call was returning something other than not supported -- if you're able to run an strace, you may be able to find the offending xattr call to help narrow down what needs to be fixed (if anything! The vim behavior was slightly buggy)

**Comment by ianisl** [comment]
Ok, so I must admit I'm not sure what I am doing here 😅, however if that can help I ran:

```
$ echo "init" > test.txt
$ strace -o trace.txt vim test.txt
```

Then modified `test.txt`, left vim.

This yields a `trace.txt` where the only occurence of `listxattr` is:

```
listxattr("test.txt~", NULL, 0)         = -1 EAGAIN (Resource temporarily unavailable)
```

**Comment by paultag** [comment]
@ianisl This is perfect! I think this is enough for the Microsoft folks to triage here (I'm just a passerby; I don't have a windows box to test with, so this is great!) -- `listxattr(2)` under CIFS here is returning `EAGAIN`, which is not `ENOTSUP` (the syscall vim checked for), which is leading to the return value (`-1`) being set to `U64_MAX`.

```
     35 EAGAIN Resource temporarily unavailable.  This is a temporary condi-
         tion and later calls to the same routine may complete normally.
```

Now, `listxattr(2)` and `stat(2)` (I only mention `stat` since the `listxattr` docs point there for other valid errnos) don't have EAGAIN as a possible returned errno, but it's also not /entirely/ unreasonable here.

IMHO `vim` was unambiguously in the wrong here, but it may be worth having someone check that CIFS showing this behavior with `listxattr` is expected here. I agree with you that this should remain open until someone on the WSL/CIFS team can triage, but I think that the fix is to update vim, at least for now.

**Comment by ianisl** [comment]
@paultag thanks for the feedback, let's this if this could be helpful for the WSL/CIFS team!

**Comment by rg9400** [comment]
This is almost certainly related to https://github.com/microsoft/WSL/issues/11227, where I am also having this error with CIFS resource being temporarily available. This is specific to the updated kernel version to 5.15.146.1-2, latest WSL versions with earlier kernel versions work fine.

**Comment by tianon** [comment]
Hilariously, I can confirm this in the other direction (and only even recognized it because I'm friends with @paultag and chatted with him when he found that Vim bug so the symptom was immediately familiar :joy:).

I've got my WSL filesystem mounted on `D:`, and I'm using "Git Bash" from _Windows_ (and the `vim.exe` included with it) to edit files that live in Linux/WSL, and on write I get this same error even though the write succeeds! :smile:

(Using `vim -C` to set `compatible` or `:set compatible` both do not prevent the error in my testing FWIW.)

Hopefully some near-future update to Git for Windows will include Paul's patch and make this go away. :rocket:
