### ISSUE TITLE
How to prevent access to WSL1/2 distributions in Windows 10/11

### ISSUE THREAD

**Issue by JeongJaecheol** [microsoft/WSL#11455]
I don't want access to the WSL1/2 distribution other than deleting it from Windows 10/11. (For example, changing the root account password of the distribution, accessing the distribution directory, etc.)
For these, are the 3 methods below possible?
1. Always request login when accessing distribution shell from Windows terminal, etc.
2. wsl2's vhdx file encrytion
3. Block access to \\wsl$ in File Explorer or require distribution login or password.

**Comment by JeongJaecheol** [comment]
/question

2024년 4월 12일 (금) 19:53, github-actions[bot] ***@***.***>님이 작성:

**Comment by OneBlue** [comment]
@JeongJaecheol: This is unfortunately impossible by design. Even if let's say WSL added a form of password protection, the place where the distribution files are themselves stored is accessible to the user (Either %appdata%\Local\lxss for WSL1, or ext4.vhdx for WSL2).

If you want additional protection for your linux distribution, the easiest way would be to have a dedicated Windows account that would own the distributions, and then elevate / switch to that account when you want to access WSL.
