### ISSUE TITLE
Unable to launch wsl2

### ISSUE THREAD

**Issue by ReinForce-II** [microsoft/WSL#11474]
### Windows Version

10.0.22631.3007

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04

### Repro Steps

type wsl in powershell

### Expected Behavior

wsl2 launched with no errors

### Actual Behavior

```
The distribution failed to start. Error code: 5, failure step: 2
Error code: Wsl/Service/CreateInstance/E_FAIL
```

**Comment by FreedSoul** [comment]
@ReinForce-II i have the same issue, how did you resolve it?

**Comment by ReinForce-II** [comment]
> @ReinForce-II i have the same issue, how did you resolve it?

In my case, the rootfs is corrupted, run e2fsck on it solved the problem.

**Comment by FreedSoul** [comment]
i cant even start wsl, can you give some insights or links, how to run e2fsck?

**Comment by ReinForce-II** [comment]
> i cant even start wsl, can you give some insights or links, how to run e2fsck?

attach the vhdx containing rootfs of wsl2 to another linux system

**Comment by FreedSoul** [comment]
whoever that get this error message, the problem is that, you have your ext filesystem corrupted, because a dirty shutdown (in my case close vscode then quickly shutdown the pc) or power outage, you can repair the issue [here](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error) or follow this other [thread ](https://github.com/microsoft/WSL/issues/10140)

**Comment by new-TonyWang** [comment]
> whoever that get this error message, the problem is that, you have your ext filesystem corrupted, because a dirty shutdown (in my case close vscode then quickly shutdown the pc) or power outage, you can repair the issue [here](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error) or follow this other [thread ](https://github.com/microsoft/WSL/issues/10140)

TKS,this worked for me

**Comment by zhhugh** [comment]
I fixed it，here is the details:
## Issue Description

When WSL2 shows the following error:
```
The distribution failed to start. Error code: 5, failure step: 2
Error code: Wsl/Service/CreateInstance/E_FAIL
```

This is typically caused by filesystem corruption due to:
- Abnormal shutdown
- Power outage
- Quick shutdown while programs like VSCode are still running
- Other scenarios that lead to a "dirty shutdown"

## Repair Steps

### 1. Preparation

1. First, backup your corrupted vhdx file:
   - The original file is usually located at: `%USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\LocalState\ext4.vhdx`
   - Copy this file to a safe location

2. Create a new Linux instance in WSL for repair:
```powershell
wsl --install -d Ubuntu-20.04
```

### 2. Install Repair Tools

In the newly created WSL instance, run:
```bash
sudo apt update
sudo apt install qemu-utils
```

### 3. Repair the Filesystem

1. Enable the nbd module:
```bash
sudo modprobe nbd
```

2. Mount the vhdx file that needs repair (use your actual backup file path):
```bash
sudo qemu-nbd -c /dev/nbd0 -f vhdx /mnt/path/to/your/ext4.vhdx
```

3. Run filesystem check and repair:
```bash
sudo e2fsck -f /dev/nbd0
```

4. When prompted during repair, you can type 'a' to automatically answer 'yes' to all questions

5. After completion, unmount:
```bash
sudo qemu-nbd -d /dev/nbd0
```

### 4. Replace the File

1. Shut down all WSL instances:
```powershell
wsl --shutdown
```

2. Replace files:
   - Rename the original corrupted file as backup
   - Copy the repaired file to the original location

### 5. Testing

Start WSL to test if the repair was successful:
```powershell
wsl -d Ubuntu
```

## Important Notes

1. Always backup the original file before starting the repair process
2. Filesystem corruption is usually caused by improper shutdown, develop good shutdown habits
3. If issues occur after repair, you can restore using the renamed original file
4. Ensure you have enough disk space for the backup files
5. The repair process requires administrative privileges in WSL

## Prevention Tips

To avoid similar issues:
1. Ensure all WSL instances are properly closed before shutting down
2. Use `wsl --shutdown` command to properly close WSL
3. Don't force shutdown your computer while WSL is running
4. Consider using a UPS if power outages are common in your area

## Troubleshooting

If you encounter issues during repair:
1. Make sure you have sufficient disk space
2. Verify that you have administrative privileges
3. Check that the paths to your vhdx files are correct
4. Ensure no WSL instances are running during the repair

## Credits

This guide is based on real-world experience fixing WSL2 filesystem corruption. Feel free to share and improve this guide.

## References

- [WSL2 Documentation](https://learn.microsoft.com/en-us/windows/wsl/)
- [e2fsck Manual](https://man7.org/linux/man-pages/man8/e2fsck.8.html)
- [QEMU-NBD Documentation](https://www.qemu.org/docs/master/tools/qemu-nbd.html)

**Comment by LandRover** [comment]
@zhhugh thanks for the detailed solution, it worked for me, and I could recover my WSL via e2fsck from another instance.

**Comment by tbcbcabral** [comment]
> I fixed it，here is the details:
> ## Issue Description
> 
> When WSL2 shows the following error:
> 
> ```
> The distribution failed to start. Error code: 5, failure step: 2
> Error code: Wsl/Service/CreateInstance/E_FAIL
> ```
> 
> This is typically caused by filesystem corruption due to:
> 
>     * Abnormal shutdown
> 
>     * Power outage
> 
>     * Quick shutdown while programs like VSCode are still running
> 
>     * Other scenarios that lead to a "dirty shutdown"
> 
> 
> ## Repair Steps
> ### 1. Preparation
> 
>     1. First, backup your corrupted vhdx file:
>        
>        * The original file is usually located at: `%USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\LocalState\ext4.vhdx`
>        * Copy this file to a safe location
> 
>     2. Create a new Linux instance in WSL for repair:
> 
> 
> wsl --install -d Ubuntu-20.04
> 
> ### 2. Install Repair Tools
> 
> In the newly created WSL instance, run:
> 
> sudo apt update
> sudo apt install qemu-utils
> 
> ### 3. Repair the Filesystem
> 
>     1. Enable the nbd module:
> 
> 
> sudo modprobe nbd
> 
>     2. Mount the vhdx file that needs repair (use your actual backup file path):
> 
> 
> sudo qemu-nbd -c /dev/nbd0 -f vhdx /mnt/path/to/your/ext4.vhdx
> 
>     3. Run filesystem check and repair:
> 
> 
> sudo e2fsck -f /dev/nbd0
> 
>     4. When prompted during repair, you can type 'a' to automatically answer 'yes' to all questions
> 
>     5. After completion, unmount:
> 
> 
> sudo qemu-nbd -d /dev/nbd0
> 
> ### 4. Replace the File
> 
>     1. Shut down all WSL instances:
> 
> 
> wsl --shutdown
> 
>     2. Replace files:
>        
>        * Rename the original corrupted file as backup
>        * Copy the repaired file to the original location
> 
> 
> ### 5. Testing
> 
> Start WSL to test if the repair was successful:
> 
> wsl -d Ubuntu
> 
> ## Important Notes
> 
>     1. Always backup the original file before starting the repair process
> 
>     2. Filesystem corruption is usually caused by improper shutdown, develop good shutdown habits
> 
>     3. If issues occur after repair, you can restore using the renamed original file
> 
>     4. Ensure you have enough disk space for the backup files
> 
>     5. The repair process requires administrative privileges in WSL
> 
> 
> ## Prevention Tips
> 
> To avoid similar issues:
> 
>     1. Ensure all WSL instances are properly closed before shutting down
> 
>     2. Use `wsl --shutdown` command to properly close WSL
> 
>     3. Don't force shutdown your computer while WSL is running
> 
>     4. Consider using a UPS if power outages are common in your area
> 
> 
> ## Troubleshooting
> 
> If you encounter issues during repair:
> 
>     1. Make sure you have sufficient disk space
> 
>     2. Verify that you have administrative privileges
> 
>     3. Check that the paths to your vhdx files are correct
> 
>     4. Ensure no WSL instances are running during the repair
> 
> 
> ## Credits
> 
> This guide is based on real-world experience fixing WSL2 filesystem corruption. Feel free to share and improve this guide.
> ## References
> 
>     * [WSL2 Documentation](https://learn.microsoft.com/en-us/windows/wsl/)
> 
>     * [e2fsck Manual](https://man7.org/linux/man-pages/man8/e2fsck.8.html)
> 
>     * [QEMU-NBD Documentation](https://www.qemu.org/docs/master/tools/qemu-nbd.html)

Thank you @zhhugh this fixed it for me too! Following your instructions closely did it.

**Comment by harvastum** [comment]
Hey, I ran into this problem, but in my case the issue and the solution were much more trivial; I just ran out of disk space on the drive hosting the .vhdx file. It's worth to take a glance at your volumes and to free up some space before attempting more complicated troubleshooting steps. In my case, WSL started up again as if nothing went wrong in the first place after I removed some old files.

**Comment by SaifeldeenAdel** [comment]
@harvastum thank you for making me notice that!

**Comment by heroes75** [comment]
[zhhugh](https://github.com/zhhugh)  thank it's work for me not at first but when i tried ubuntu 24.04 it's works so thank you 😭😭😭
