### ISSUE TITLE
Windows File Explorer: created files aren't visible in Bash

### ISSUE THREAD

**Issue by piotrek-k** [Microsoft/WSL#1152]
BashOnWindows has its own folder tree, just like in all linux based operating systems. Reportedly, going to `%localappdata%\lxss` in windows file explorer should show me all those files.

There is a problem with exploring those files in Windows File Explorer (WFE):

When I create new file in WFE, this file is not visible in bash (`ls` command doesn't show anything). In opposite way it works correctly: if I create file in bash (`touch file.txt`) it is correctly displayed in WFE.

Only creating file causes problems. When I create it on "bash side", I can modify/delete this easily on "windows side" and bash sees changes.

Windows Version: 10.0.14393

**Comment by aseering** [comment]
@piotrek-k -- thanks for posting, but this is a frequently-asked question that's answered on a variety of tickets including (most recently) #1141 ,  WSL filesystems are discussed in detail in [this blog post](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/).

In short, this is expected behavior:  Native Linux files require metadata (such as POSIX file permissions) that Windows applications do not understand.  `%localappdata%\lxss` is meant to be opaque data storage for WSL; you're not intended to work with it directly.  (Hence its location in `%localappdata%`.)

If you want to share files between the two environments, you can put them in the Windows filesystem and access them via `/mnt/c/` in Linux.

**Comment by fpqc** [comment]
Yes. The way I have taken to explaining it is that it's hidden for a reason.

**Comment by taraszka** [comment]
That's fine but if you break sudoers like I did you won't be able to fix it from the Windows. I think lxss or Microsoft Windows should have some kind of inotify() in place to update the require metadata.

**Comment by coldacid** [comment]
There used to be an app available from MSDN downloads that would let you view (and possibly edit) NTFS extended attributes, but it disappeared some time ago. Would be very helpful if the WSL team would dig it out of storage and make it available again, or at least provide a tool that would fix up missing/bad EAs needed for WSL.

**Comment by fpqc** [comment]
@coldacid @Rolisoft wrote a small lib and cmdline tool called ntfsea that you can drive through python.  Look in his WSL distribution switcher.

**Comment by sunilmut** [comment]
I think these are valuable feedback. We are using [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to help us prioritize our work going forward. If you can also provide this feedback there as well, that would be greatly useful.

**Comment by RoliSoft** [comment]
@coldacid @fpqc Note: there's no command line app for that. Only a C library. That being said, I could create a quick `fix_file` app which just makes the file reappear again. (By writing something like uid/gid 1000 and set perms to 666 or something.)

**Comment by therealkenc** [comment]
The OP was by-design per Adam's [post](https://github.com/Microsoft/WSL/issues/1152#issuecomment-250938896). Topic landing zone is #1524.
