### ISSUE TITLE
docker cannot start after installing linux-msft-wsl-6.6.y

### ISSUE THREAD

**Issue by bs340248** [microsoft/WSL#11742]
### Windows Version

Microsoft Windows [Version 10.0.22631.3810]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3+

### Distro Version

Debian 11

### Repro Steps

1)Install Docker in Debian (not in Windows).
2)Run "docker image ls". All good.
3)Compile and install linux-msft-wsl-6.6.y kernel from Git.
4)Run "docker image ls". Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Expected Behavior

Run "docker image ls". It reports all installed images.

### Actual Behavior

Run "docker image ls". It reports
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Diagnostic Logs

I tried command "dockerd" and here is the error:
INFO[2024-07-03T14:56:01.609154816+02:00] Starting up
INFO[2024-07-03T14:56:01.768529492+02:00] [graphdriver] using prior storage driver: overlay2
INFO[2024-07-03T14:56:01.769406490+02:00] Loading containers: start.
WARN[2024-07-03T14:56:02.295454881+02:00] Could not load necessary modules for IPSEC rules: protocol not supported
INFO[2024-07-03T14:56:02.304720573+02:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2024-07-03T14:56:02.318493061+02:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
failed to start daemon: Error initializing network controller: error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.7 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))

**Comment by bs340248** [comment]
[WslLogs-2024-07-03_15-52-46.zip](https://github.com/user-attachments/files/16085933/WslLogs-2024-07-03_15-52-46.zip)

**Comment by zcobol** [comment]
@bs340248 you need to install the modules also. Docker is not finding the `br_netfilter` module. Run `journalctl -u docker` for details, or `journal -xeu docker`.

For older kernels the module is builtin:
```
ubuntu@noble:~$ ls /lib/modules/
5.15.153.1-microsoft-standard-WSL2

ubuntu@noble:~$ modinfo br_netfilter
name:           br_netfilter
filename:       (builtin)
description:    Linux ethernet netfilter firewall bridge
author:         Bart De Schuymer <bdschuym@pandora.be>
author:         Lennert Buytenhek <buytenh@gnu.org>
license:        GPL
file:           net/bridge/br_netfilter
```

**Comment by pvoliveira** [comment]
I'm also having the same issue, I followed the steps from [here ](https://learn.microsoft.com/en-us/community/content/wsl-user-msft-kernel-v6#1---building-the-microsoft-linux-kernel-v61x)to get the modules installed but after restart the WSL instance the issue remains.

**Comment by bs340248** [comment]
@zcobol Thank you for your tips. However, I had the modules installed.

I tried modinfo br_netfilter. Here is the output.
```
filename:       /lib/modules/6.6.36.3+/kernel/net/bridge/br_netfilter.ko
description:    Linux ethernet netfilter firewall bridge
author:         Bart De Schuymer <bdschuym@pandora.be>
author:         Lennert Buytenhek <buytenh@gnu.org>
license:        GPL
depends:        bridge
retpoline:      Y
intree:         Y
name:           br_netfilter
vermagic:       6.6.36.3+ SMP preempt mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        47:DE:3D:BF:7D:C3:EA:D0:80:A2:56:8C:DB:F0:83:07:B6:8E:74:05
sig_hashalgo:   sha512
signature:      2A:33:04:6C:A9:E6:BA:13:2E:66:F5:E2:59:5A:5C:6F:9D:3A:BF:4C:
```

I also executed journalctl -u docker. Here is the output.
```
Jul 03 17:13:08 wyWIN-R60 systemd[1]: Starting Docker Application Container Engine...
Jul 03 17:13:10 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:10.247217900+02:00" level=info msg="Starting up"
Jul 03 17:13:10 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:10.742555900+02:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jul 03 17:13:10 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:10.845913900+02:00" level=info msg="Loading containers: start."
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:11.185893600+02:00" level=warning msg="Could not load necessary modules for IPSEC rules: prot>
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:11.230542100+02:00" level=warning msg="could not create bridge network for id efadb92932fabf5>
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:11.234231700+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 1>
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: time="2024-07-03T17:13:11.245916900+02:00" level=info msg="stopping event stream following graceful shutdown" error=>
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: failed to start daemon: Error initializing network controller: error creating default "bridge" network: Failed to Se>
Jul 03 17:13:11 wyWIN-R60 dockerd[543]: Try `iptables -h' or 'iptables --help' for more information.
Jul 03 17:13:11 wyWIN-R60 dockerd[543]:  (exit status 2))
Jul 03 17:13:11 wyWIN-R60 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 17:13:11 wyWIN-R60 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 03 17:13:11 wyWIN-R60 systemd[1]: Failed to start Docker Application Container Engine.
Jul 03 17:13:13 wyWIN-R60 systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
```

**Comment by zcobol** [comment]
`docker` fails to start with:

```
ubuntu@noble:~$ sudo iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  RULE_INSERT failed (No such file or directory): rule in chain POSTROUTING
```

Kernel used for testing:

```
ubuntu@noble:~$ uname -r
6.6.36.3-microsoft-standard-WSL2
ubuntu@noble:~$ lsmod
Module                  Size  Used by
nf_conntrack_netlink    53248  0
br_netfilter           32768  0
bridge                335872  1 br_netfilter
stp                    12288  1 bridge
llc                    16384  2 bridge,stp
intel_rapl_msr         16384  0
intel_rapl_common      36864  1 intel_rapl_msr
crc32c_intel           16384  0
configfs               61440  1
ip_tables              32768  0
autofs4                53248  0
```

Something changed between WSL kernels! Let's find out what.

**Comment by kelsey-steele** [comment]
Hi all o/ 

This is due to config changes that happened in the WSL2 kernel release [linux-msft-wsl-6.6.36.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3). Some of the configs Docker requires were changed to be loadable modules instead of their previously built-in state. 

WSL2 now has loadable module support ( yay \o/ ), except when using a custom kernel, at least for now. By module support I mean using 'modprobe' or modules auto-loading when they're called (i.e. running 'dockerd' should load all the modules it needs to run and will do so in an upcoming WSL release that includes the [linux-msft-wsl-6.6.36.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3) kernel.) You can still use insmod to load modules individually with a custom kernel. Or you can edit the kernel config file to set all loadable modules you want to be built-in before compiling your kernel (recommended route). 

Fwiw, you can use the old 5.15 config ( [5.15 config-wsl (x86)](https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.15.y/arch/x86/configs/config-wsl) / [5.15 config-wsl-arm64](https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.15.y/arch/arm64/configs/config-wsl-arm64) ) to build [linux-msft-wsl-6.6.36.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3) and go back to your prior config state if you'd like. You will just need to select values for any newly added configs between 5.15 and 6.6 when building.

When running the Docker check-config.sh (found under [docker.docs Kernel Compatibility](https://docs.docker.com/config/daemon/troubleshoot/#kernel-compatibility)), we can see which configs are now modules and should either be set to built-in in your configs or you can always load them individually:

> Generally Necessary:
> - cgroup hierarchy: properly mounted [/sys/fs/cgroup]
> - CONFIG_NAMESPACES: enabled
> - CONFIG_NET_NS: enabled
> - CONFIG_PID_NS: enabled
> - CONFIG_IPC_NS: enabled
> - CONFIG_UTS_NS: enabled
> - CONFIG_CGROUPS: enabled
> - CONFIG_CGROUP_CPUACCT: enabled
> - CONFIG_CGROUP_DEVICE: enabled
> - CONFIG_CGROUP_FREEZER: enabled
> - CONFIG_CGROUP_SCHED: enabled
> - CONFIG_CPUSETS: enabled
> - CONFIG_MEMCG: enabled
> - CONFIG_KEYS: enabled
> - CONFIG_VETH: enabled
> - CONFIG_BRIDGE: enabled (as module)
> - CONFIG_BRIDGE_NETFILTER: enabled (as module)
> - CONFIG_IP_NF_FILTER: enabled (as module)
> - CONFIG_IP_NF_MANGLE: enabled (as module)
> - CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
> - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
> - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
> - CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
> - CONFIG_NETFILTER_XT_MARK: enabled (as module)
> - CONFIG_IP_NF_NAT: enabled (as module)
> - CONFIG_NF_NAT: enabled
> - CONFIG_POSIX_MQUEUE: enabled
> - CONFIG_CGROUP_BPF: enabled

I made sure Docker is running with this kernel release with the recommended config changes and by default in the upcoming WSL release that will include the kernel [linux-msft-wsl-6.6.36.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3). For extra reference, here are the modules that get auto loaded when I run 'dockerd' in the upcoming WSL release:

> Module                  Size  Used by
> xt_conntrack           12288  1
> xt_MASQUERADE          16384  1
> nf_conntrack_netlink    45056  0
> xfrm_user              49152  1
> xfrm_algo              16384  1 xfrm_user
> xt_addrtype            12288  2
> nft_compat             16384  4
> br_netfilter           28672  0
> bridge                282624  1 br_netfilter
> stp                    12288  1 bridge
> llc                    12288  2 bridge,stp



I added a new note to the [linux-msft-wsl-6.6.36.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3) release to hopefully bring better attention to these config changes.

Thank you so much for being early users of this WSL2 kernel, testing, and reporting! I hope this information helps. :)

**Comment by bs340248** [comment]
I can confirm that using the config-wsl file from linux-msft-wsl-6.1.y fixed the issue.
Thank you all for your help!

**Comment by kelsey-steele** [comment]
@bs340248 thanks for testing and closing this out! If the linux-msft-wsl-6.1.y config works for all your needs, great! 

Just fyi that the linux-msft-wsl-5.15.y config was actually kept more up to date since the 6.1 WSL2 kernel never officially got released and I was blocked pushing more updates out for that. :(  

There really isn't a huge difference between the two configs. One at the top of my head was enabling support for Yubikeys on 5.15 which 6.1 didn't get. Though for the 6.1 configs, any new configs added between 5.15 and 6.1 we chose values that we thought best fit for WSL, so suppose 6.1 gets a point for that. Probably for most people, either 5.15 or 6.1 config is fine if not wanting to customize the 6.6 config. 

I did get a bit wide eyed seeing the comment and instructions for using the linux-msft-wsl-6.1.y source code. The config file is fine, though the source code is very outdated. Please nobody use that and move to the linux-msft-wsl-6.6.y release. :)

**Comment by mihaiflorinpopa** [comment]
@kelsey-steele Works fine, indeed, with the 5.15 wsl-config file. Also enabled some CONFIG_DUMMY and CONFIG_NETFILTER_XT_MATCH_BPF for Docker, but those are optional. Any ETA when the new wsl-config file is going to be rolled out with all the configs updated? Thanks!

**Comment by kelsey-steele** [comment]
> @kelsey-steele Works fine, indeed, with the 5.15 wsl-config file. Also enabled some CONFIG_DUMMY and CONFIG_NETFILTER_XT_MATCH_BPF for Docker, but those are optional. Any ETA when the new wsl-config file is going to be rolled out with all the configs updated? Thanks!

I don't have a release date to provide, though it is likely a WSL pre-release including the 6.6 kernel will be getting sent out to insiders in the next week or two.

**Comment by mihaiflorinpopa** [comment]
> > @kelsey-steele Works fine, indeed, with the 5.15 wsl-config file. Also enabled some CONFIG_DUMMY and CONFIG_NETFILTER_XT_MATCH_BPF for Docker, but those are optional. Any ETA when the new wsl-config file is going to be rolled out with all the configs updated? Thanks!
> 
> I don't have a release date to provide, though it is likely a WSL pre-release including the 6.6 kernel will be getting sent out to insiders in the next week or two.

@kelsey-steele Thanks! When that drops for insiders, how do we go about the kernel modules and headers like it's detailed [here](https://learn.microsoft.com/en-us/community/content/wsl-user-msft-kernel-v6)? Do we have to do anything about them to install them or are they pre-packaged in the kernel release?

**Comment by kelsey-steele** [comment]
@mihaiflorinpopa once WSL releases with the 6.6 kernel, the kernel and modules will be pre-packaged and automatically apply when updating to it. Make sure to remove the "kernel=<path to kernel>" from your .wslconfig for the default kernel to be used and module support to be enabled. You'll be able to find the modules under /lib/modules/.

Hopefully the next WSL release and with the default 6.6 kernel will do everything you need! If not and you still find needing a custom kernel, remember module support will continue to be disabled with custom kernels (at least for now), so use a kernel config with everything you need built in (i.e. the last 5.15 config or your own custom file).

**Comment by eapotapov** [comment]
@kelsey-steele  , thanks for the information!

One thing that concerns me is that I'm currently merging flags from 5.15 to 6.6. In cases where they were "=y" in 5.15 and are now "=m" in 6.6, I see a number of flags that have been moved from "=y" to "=m", probably with the idea of optimizing by moving rarely used features to autoloadable modules.

The problem is with custom builds. I think that a number of applications (like Docker Desktop) were expecting features to be built-in, and if custom kernel builds won't support autoloading for a long time, it's going to be a breaking change.

Maybe it would be better to keep previously built-in features as "=y" and move previously unset features to "=m"?

**Comment by eapotapov** [comment]
https://gist.github.com/eapotapov/e64d8ce1d35064cf0dcd0dcd57577bdf

I've merged the 5.15 config into the existing 6.6 configuration. Whenever there was a "=y" in 5.15 and a "=m" in 6.6 for the same variable, it is now "=y" in the config.

Use it in ./Microsoft/config-wsl

Additionally, there were a couple of variables present in 5.15 but missing in 6.6 that I have added. I'm not sure if they are necessary, but I think they won't hurt.

I started trying to compile the kernel because I wanted to enable eBPF. I was using [this article](https://massoudasadiblog.blogspot.com/2024/07/ebpf-on-wsl2-kernel-version-6x-ubuntu.html) for guidance. The variables mentioned there are also added (with "=y" everywhere instead of "=m").

I just checked, and both eBPF and Docker Desktop are working.

Still, I'm not sure if this is a reliable solution, but it works for now. I will update in a week or so to confirm its reliability.

**Comment by kelsey-steele** [comment]
@eapotapov, thank you for testing and reporting! 

We’re hopeful module support for custom kernels will be available soon, though we don’t have an ETA at the moment. The new WSL configs were designed with module support in mind and to work with the default kernel.

I’m glad to hear you got everything working by making all the modules built-in! This will build-in a lot you won't need and can have a heavy impact on kernel size and boot speed. If you’re interested in optimizing, I recommend using the WSL2 kernel 6.6 or 5.15 configs and building in (=y) the configurations suggested by [docker.docs Kernel Compatibility](https://docs.docker.com/config/daemon/troubleshoot/#kernel-compatibility) and the recommended eBPF configurations you found. I believe this should get Docker Desktop with a custom kernel working for you, though verification is needed. Using the [5.15 configs](https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-5.15.y/Microsoft) would require less modifying.

**Comment by bit-hope** [comment]
Here is the Docker check-config.sh (found under [docker.docs Kernel Compatibility](https://docs.docker.com/config/daemon/troubleshoot/#kernel-compatibility)).


1. **At least, you must modify follow configs in Microsoft/config-wsl from 'm' to 'y':**
    CONFIG_BRIDGE=y
    CONFIG_BRIDGE_NETFILTER=y
    CONFIG_NFT_COMPAT=y
    CONFIG_NETFILTER_XT_NAT=y
    CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y
    CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
    CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y

    **The above modification works well for me.**

    **After rebuilding the kernel and login in WSL, you need run follow scripts:**
        `sudo systemctl stop docker` 
        `sudo ip link del docker0`
        `sudo rm -rf /var/lib/docker/network`
        `sudo systemctl start docker`

   If an error such like "error locating sandbox id 32791b12df33f576fa34a88cc67ceb89e3d8c21582a47ccc5532eb5414f4010f: sandbox 32791b12df33f576fa34a88cc67ceb89e3d8c21582a47ccc5532eb5414f4010f not found" occurred, you need use `docker rm xxx` to remove your existed containers and rerun them with `docker run -dti xxx`.


3. **Also, you can modify more configs as you need:**
    CONFIG_NETFILTER_XT_MARK=y
    
    CONFIG_IP_NF_IPTABLES=y
    CONFIG_IP_NF_FILTER=y
    CONFIG_IP_NF_NAT=y
    CONFIG_IP_NF_TARGET_MASQUERADE=y
    CONFIG_IP_NF_TARGET_REDIRECT=y
    CONFIG_IP_NF_MANGLE=y
    
    CONFIG_IP_VS=y
    CONFIG_NETFILTER_XT_MATCH_IPVS=y

_Originally posted by @bit-hope in https://github.com/microsoft/WSL/issues/11771#issuecomment-2272556114_

**Comment by thepromptninjaneer** [comment]
I'm having trouble getting docker to start using a custom built `5.15.153.1` kernel.  I rebuilt the kernel in order to enable webcam support and loading that built kernel vis .wslconfig (camera works as expected)--- but now docker won't start up and it keeps looping asking for elevated access to update wsl.  I haven't been able to find anyone experiencing a similar issue.

In the end I cancel out and get this:

`wsl update failed: updating wsl: elevated update failed: the operating system denied access to the specified file`

I'm pretty sure that this has something to do with the custom built image I made but I'm not well versed with building and using the kernel.  Anyone have any sage advice on how to properly rebuild 5.15.153.1 and what I need to set the config variables to so that docker works?  Any breadcrumbs would certainly help!  TIA.

**Comment by uocnb** [comment]
Thanks @bit-hope! The config work well for me with latest kernel 6.6.36.6.

**Comment by yuvald-sweet-security** [comment]
@bit-hope the config changes recommended by Docker's `check-config.sh` script are not enough for Docker Desktop because Docker Desktop uses some additional stuff (for example, it mounts the Docker CLI tools from a disk image called `docker-wsl-cli.iso` and thus requires the kernel to be built with `CONFIG_ISO9660_FS=y`).

The configuration supplied by @eapotapov is sufficient but is probably excessive. It would be nice if we could get a list of required config flags for Docker Desktop from the folks at Docker so that we can configure the kernel to contain only the required stuff.

**Comment by aerophobic** [comment]
Came across this issue myself and found an easy appraoch to solve it: https://blog.thetechcorner.sk/posts/Update-WSL2-kernel-to-6-6-x/

Credits to and big thanks to @eapotapov and @ard3ny 🙏🏼

**Comment by sonzai-furenzoku** [comment]
@bit-hope Thank you so much, that really solved my problem!
