### ISSUE TITLE
Launching ELF binary from Windows as root, rather than as unprivileged user

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/WSL#1203]
Is there, or can there be, a means to do this?

To further explain my use case, I am invoking various ELF binaries from Windows using `bash.exe -c foo`, which works perfectly when they can run as an unprivileged user. Unfortunately, when they need to run as root, the only way I'm aware of to do this is using `sudo` via bash -c, which requires that the user password be entered in the bash console, which is undesirable for automated operation.

**Comment by stehufntdev** [comment]
Not sure if this would work for your environment, but one option would be to use `lxrun.exe /setdefaultuser root` in your automation around the places that need to have root access and set it back when it's not needed.

**Comment by rodrymbo** [comment]
It's Linux. If you can imagine it, someone has probably made a way for you to do it.

To fix `sudo` so it doesn't ask for a password, read the man pages, then use `sudo visudo` to edit the configuration file (which is called sudoers, but you don't really need to know that and shouldn't mess with it if you encounter it when you wander around). Find the line that begins with `%sudo` and make it read

`%sudo   ALL=(ALL:ALL) NOPASSWD: ALL`

Now sudo won't ask for a password, though you should test it interactively before relying on it.

Since root in WSL is not really an administrative user, I'd recommend that the devs make NOPASSWD: the default for sudoers. It would make the UX much more pleasant for folks without really compromising security. 

Another option I've pondered but not tried is using [lxrun to change the default user](https://msdn.microsoft.com/en-us/commandline/wsl/reference) in the CMD script, running the -c command, then changing it back. Sounds complicated, and the sudoers trick should make it so it's not needed.

**Comment by fpqc** [comment]
If you are doing a sudoers entry for nopasswd, it is highly recommended to set it for only one specific command.  So you could set it to allow sudoer execution of starting sshd and that's it.

Much more secure for now.  It won't even allow you to execute it with any other flags or args.

**Comment by cerebrate** [comment]
@stehufntdev The main problem I can foresee is that `lxrun.exe /setdefaultuser root` changes a global setting, and some of this automation is intended to run in the background, which seems to be begging for a race condition.

@rodrymbo Ah, good thought! That solves my immediate problem. I'd still like to see a means of doing this that isn't dependent on sudo, though, since I can see some of these tools being distributed in the future, and I'd prefer to minimize the configuration changes needed.

**Comment by rodrymbo** [comment]
> @cerebrate: "I'd still like to see a means of doing this that isn't dependent on sudo, though, since I can see some of these tools being distributed in the future, and I'd prefer to minimize the configuration changes needed."

Superuser is hard to get to, and rightly so. I guess the strategy could depend on how you are using it and if you are limited to WSL. 

Sudo with no password is the only tool that comes to mind that would let you launch from the Windows side (`bash.exe -c`), at least at this point, except maybe `suid`. Depending on what it is you are trying to do, suid might work, cringe-worthy as that might normally be, but it could take even more configuration (and planning, and analysis) to implement securely than sudo. 

Maybe one of the linux gurus with more experience can come up with something else? Again, it would depend on exactly what your process is trying to do that currently requires superuser.

It would probably be good to prioritize on "Linuxy" solutions. So instead of starting the command with `bash.exe -c` from Task Scheduler (for example), one could run it from cron instead. Of course you'd need to launch cron somehow or at least make sure it is running at the time when your command needs to run, and at this point the most convenient way to do that is if sudo is configured to at least let the linux user run cron without a password. The devs have speculated about ways to make services run in future releases of WSL, which might mean you could in the future require or expect cron to be running all the time. Of course if you are not talking about a task that could be scheduled, the discussion of cron is moot, but I think it illustrates a "linuxy" solution which depends on a bit of configuration change (assuring that the user has set up cron to run) but not something too radical or unusual (cron is one of those basic unix/linux tools, and it is not so unusual to expect it to be running). 

I suppose we could ask the devs to add an optional "--user " argument to bash.exe, so you could run things directly as root from the Windows side; that would be convenient for many applications, including starting services like cron when the Windows user logs in. One could make a case for such an option in the [uservoice area](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash), especially if one can be specific about how it would let us accomplish a particular task or several tasks. Or maybe the devs would say that "sudo" with no password is a better "best practice" to follow.

I'd normally agree with @fpqc about using the bare minimum with superuser privileges, and that applies to sudo or suid or services like cron for that matter. There's value in not getting used to the relaxed security environment WSL provides, where running something as WSL's root can at worst only mess up the WSL environment (unless a Windows privilege escalation bug is found, but that's a slight risk with any program, and would probably apply to non-superusers anyway). Still, WSL security is fundamentally different than a multiuser linux environment, so maybe suid isn't such a stretch for a WSL program, or maybe another WSL-only or "non-Linuxy" solution might become apparent.

**Comment by ionescu007** [comment]
@cerebrate For what it's worth, the COM API does support launching the binary as a specific user. You can see the appropriate relevant call in my LxLaunch project. When Microsoft documents the interface, you can hopefully legitimately do the same as well.

For now, keep in mind that the value actually comes from a registry value, so with some clever (but annoying) registry tricks, you should be able to 1) change the key to 0 2) restart the service (IIRC it's cached) 3) launch your binary 4) change the key back to 500 5) restart the service

**Comment by Brian-Perkins** [comment]
A new -u or --user flag has been added to wsl.exe in Insider Build [17704](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17704)

**Comment by therealkenc** [comment]
> A new -u or --user flag has been added

No `--rootfolder` yet though. As an alternative than Alex's restart-service trick to avoid the caching issues, you can also just keep stuffing new GUIDs into the registry and then clean them up. Basically IPC by tempfile.
