### ISSUE TITLE
Some Linux/macOS support

### ISSUE THREAD

**Issue by ericcurtin** [microsoft/WSL#12078]
I think it would be useful if we build Linux and macOS versions of wsl.exe (obviously my preference is Linux).

Doesn't have to support the same level of features, but if it could download a wsl artefact and convert to a .qcow2 even that would be very useful to boot via qemu on Linux and macOS.

**Comment by OneBlue** [comment]
Unfortunately that's not possible because WSL distributions are only filesystems (they don't contain kernels or initramfs), and even if they did, the initramfs that WSL uses wouldn't be compatible with qemu. 

One thing you could theoretically do would be to have your own kernel + initrd and use a custom init to chroot into a WSL distro that you previously extracted, but this isn't something that WSL could realistically support.
