### ISSUE TITLE
WSL steals UDP Ports from Windows

### ISSUE THREAD

**Issue by avlec** [microsoft/WSL#12228]
### Windows Version

Microsoft Windows [Version 10.0.22621.3880]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 24.04

### Other Software

Using python to check for a basic UDP socket connection to rule out application specific quirks.

### Repro Steps

Launch WSL. Try opening UDP ports until you get the following error message and that doesn't correspond to a port a real application is using in WSL or Windows (checked via netstat).

> OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

I was seeing a large range of ports that were unusable after starting WSL. I was seeing this range [44619, 48715] (4097 ports) being made un-bindable. If I start WSL with some application using a port in that range the range would shift. I was seeing this shift down to [37794, 41890] (4097 ports)

### Expected Behavior

Launching WSL doesn't cause a blanket range of ports to be made unavailable in Windows but are still available in WSL. The ports shouldn't be 

### Actual Behavior

Launching WSL causes a blanket range of ports to be made available only inside WSL.

That is I can open UDP sockets on those ports within WSL but not in Windows.

**Comment by zcobol** [comment]
@avlec please specify what `networkingMode`  you're using.

**Comment by avlec** [comment]
Sorry I meant to put that in the post. I'm using mirrored networking

**Comment by OneBlue** [comment]
This is probably due to the fact that mirrored networking pre-reserves ports when starting WSL. assigning to @keith-horton

**Comment by keith-horton** [comment]
Right - this is by design with Mirrored mode.

Because Windows uses a global port pool, and mirrored mode forwards packets so the container has the same MAC and IP addressing as the host, we must give the WSL container a unique range of TCP+UDP ports that Linux can use as its ephemeral ports.
Similarly, if an application in WSL tries to directly bind() to a port, we must ensure it's 'reserved' on the host so that it's exclusively used by the WSL container.

**Comment by keith-horton** [comment]
Yeah, sorry about the confusion. If you launch the apps *before* starting WSL, we'll keep moving to find a different contiguous port range to configure in Linux.

If you need to know what was configured, you can run something like the following in Linux to read the programmed ephemeral port range: sysctl net.ipv4.ip_local_port_range.

**Comment by keith-horton** [comment]
if it's cool with you, I'll go ahead and close this.

**Comment by avlec** [comment]
Yeah that's the workaround I got to anyways. Or shutting down WSL then opening the app that uses the ports. However, I did notice that sometimes after closing WSL that some ports were still unbind-able, that might be worth looking into.

The workaround seems fine, as this is buried in internals it might change spontaneously one day and work better.

Thanks for the help, and for pointing out the sysctl endpoint

**Comment by savely-krasovsky** [comment]
@avlec in my case I cannot bind neither TCP or UDP at those ports. Our corporate VPN uses port within range to receieve authorization code callback from OAuth2 flow and fails to run local HTTP server due to this problem. `wsl.exe --shutdown` helps, but are there any proper solutions? Why it occupies those ports only after running some amount of time?
