### ISSUE TITLE
Starting bash.exe inside of bash.exe in 14951 crashes immediately

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#1228]
I sort of guessed that this would be the best way to break everything:

![2016-10-19](https://cloud.githubusercontent.com/assets/6083371/19545171/40608c98-9652-11e6-80eb-badcc23928d4.png)

Also interesting:

![2016-10-19 2](https://cloud.githubusercontent.com/assets/6083371/19545248/b83d8e32-9652-11e6-9e3c-f794cc78ed3c.png)

Just wondering if this will ever be supported.  I'm guessing this will require some of the planned upgrades to conhost to actually work right.

Example use-case:

You're in bash, but you want to run a batchfile that uses bash.exe for redirection, so you do

`cmd.exe /c datbatch.bat`

This is what happens:

![2016-10-19 3](https://cloud.githubusercontent.com/assets/6083371/19545497/c2a7d06a-9654-11e6-9ef3-d92e918f8e19.png)

**Comment by benhillis** [comment]
I like to call this scenario "Inception."

@fpqc I think you'll agree this is a somewhat lower priority that other things, but I'd like it if this worked.

**Comment by fpqc** [comment]
Yeah. I just knew that this did not work well with Xilun's cbwin, and I didn't expect it to work here on first release.

**Comment by ddfznt** [comment]
Cmd does not have tabs, would be nice open a new `window bash.exe` within the `/bin/bash` 🤔

**Comment by fpqc** [comment]
Yep.

**Comment by fpqc** [comment]
@benhillis Probably until you decide lx-side security, it is good that this won't work, since if implemented naively, you could try to escalate privileges with 
`lxrun.exe /setdefaultuser root` then `bash.exe`

I do see that trying to get to `%localappdata%\lxss\rootfs` is blocked from inside bash though, which is a good call.

However, I think you should if possible block all of `%localappdata%\lxss` since if people are backing up or switching distros with @RoliSoft's scripts will have copies of `/etc/shadow` readable, although maybe the solution is to ask Rolisoft to store them inside of /root.

**Comment by goreliu** [comment]
`/init cmd /C bash -c "touch /tmp/aa"` run failed, but `/init cmd /C 'bash -c "touch /tmp/aa" < filename'` works. The problem is cased by stdin of bash.

**Comment by CherryDT** [comment]
@ddfznt I don't think there is any good way to mitigate this type of attack, as long as the idea of "root" in WSL is a different thing than elevation is in Windows (with all the protections which are in place there, applied to WSL in some way - but it will be almost impossible to practically implement, I think).

Because as soon as a WSL program can do _any_ interop to Windows, there will be ways to exploit this to get root privilege in WSL. I can imagine hundreds of different ways (simple example: using `reg.exe` to write an autorun entry which does `cmd.exe /c "lxrun /setdefaultuser root && bash -c /tmp/something_evil.sh"`, but there are many other ways). Now even if the actual "launch Windows program from Linux" part could be eliminated, there would be tons of other ways, for example doing the thing listed above differently by dropping a batch file in the user's autorun folder via `/mnt` instead of using registry.

**Comment by benhillis** [comment]
I've introduced a change that will allow launching bash.exe or wsl.exe from within an existing window.  This change will be available in a Windows Insider build in the coming weeks.

**Comment by fpqc** [comment]
Neat!

**Comment by sunilmut** [comment]
This should be fixed in the Insider build [17017](https://msdn.microsoft.com/en-us/commandline/wsl/release-notes#build-17017).
