### ISSUE TITLE
terminfo patch from 8 to 16 colors

### ISSUE THREAD

**Issue by Erhie** [Microsoft/WSL#1252]
I missed the usage of 16 colors in VIM

e.g.
_:highlight Comment ctermfg=12_
delivers not the expected color

to put things right**:**
**patch Terminfo of xterm**
_infocmp xterm >xterm.ti_
change to **colors#16** with _vim xterm.ti_
compile
_sudo tic xterm.ti_

Result
new /etc/terminfo/x/xterm

Windows Version 10.0.14393 Build 14393
Ubuntu on Windows DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Comment by fpqc** [comment]
I don't understand.

Are you asking why this doesn't work?

**Comment by Erhie** [comment]
I propose to take the patched /etc/terminfo/x/xterm in the next release

**Comment by fpqc** [comment]
Erhie, it's not a terminfo problem though.  The console atm is dropping the color palette down.

**Comment by Erhie** [comment]
Thank you for your comment!
But the console atm is able to use 16 colors.
You can test it with colortest-16
And VIM orientate themselves obviously to the entry in terminfo 

Erhie

**Comment by fpqc** [comment]
@Erhie try setting $TERM=xterm-256color ?

**Comment by Erhie** [comment]
I tried it, but has side effects
16 colors is the target for the implemented console atm 
Erhy

**Comment by fpqc** [comment]
@Erhie hmm. Maybe MS should submit a new terminfo to the terminfo database and emit a TERM=windows?

**Comment by zadjii-msft** [comment]
So, the console Is adding support for full 256 color in the next release, so I doubt xterm-256color should be a problem then.

I'm under the impression that `:highlight Comment ctermfg=12` should work, even on `TERM=xterm`, is that not the case?

Oh weird, that seems to not work on WSL, but it's totally fine on my Ubuntu 15.10 VM. I'll investigate.

**Comment by fpqc** [comment]
@zadjii-msft by the way, in the console properties menu, any chance you could rearrange the colorboxes so they are in a 2x8 rectangle instead of 1x16?  It's very hard to tell which colorbox corresponds to which color in the palette.  In most TEs on Linux, you have Black atop grey, white atop another grey, then red, blue, green, yellow, purple, and teal (not in that order!) atop their darker corresponding colors.

**Comment by zadjii-msft** [comment]
@fpqc Don't even get me started on that dialog. It's been itching for a full rewrite for some time now. I hate it. It's on the backlog :)

**Comment by fpqc** [comment]
@zadjii-msft Excellent! That dialog, even with its recent improvements, has a distinct Windows 2000 feel.  Also I've found it to be buggy, and now when I launch bash from the Runline (Win+R), it's stuck as white text on a sky blue background, and I can't get any changes to stick.

**Comment by zadjii-msft** [comment]
@fpqc That doesn't sound right, are you changing the Defaults or the Properties?

**Comment by fpqc** [comment]
@zadjii-msft Properties.  Have never changed the defaults.  If you want me to dump a registry entry for you, I'd be happy to do it, just give me a path.

**Comment by zadjii-msft** [comment]
@fpqc can I get `HKCU/Console` and `HKCU/Console/%SystemRoot%_bash.exe`?

**Comment by fpqc** [comment]
Yep!

[HKCUConsole.reg.txt](https://github.com/Microsoft/BashOnWindows/files/548661/HKCUConsole.reg.txt)
[HKCUConsolebash.reg.txt](https://github.com/Microsoft/BashOnWindows/files/548660/HKCUConsolebash.reg.txt)

**Comment by bitcrazed** [comment]
"How'd you guys manage that prime real estate"

By being in the OS since the dark ages ;)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
