### ISSUE TITLE
no blinking characters in ncurses apps

### ISSUE THREAD

**Issue by Erhie** [Microsoft/WSL#1258]
Tested ncurses app and detected,
that the attribute A_BLINK has no effect.

There is a definition in terminfo for blinking:
blink=\E[5m
For what?

It would be fine, when characters are able to blink.

Thank you
Erhie

**Comment by fpqc** [comment]
@Erhie probably an un-implemented ANSI escape sequence.

**Comment by Erhie** [comment]
would be nice, if someone implements also this escape sequence for blinking characters
Erhie

**Comment by fpqc** [comment]
@Erhie It's probably coming sooner or later.  The coming year will allegedly be the year of big major console improvements, according to the console team.  See #111 posts by miniksa.

**Comment by zadjii-msft** [comment]
Yea we definitely don't support blinking characters ATM. But it's on the backlog :)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. We currently don't support blinking characters in the Console. It is on the backlog though and we'll consider for a future release
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
