### ISSUE TITLE
Reset colour intensity doesn't work

### ISSUE THREAD

**Issue by Fydon** [Microsoft/WSL#1276]
- A brief description
  When setting text output to bold [using escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes) and then resetting the intensity, the reset doesn't work. It does work on Linux, as well as Cygwin on Windows.
- Expected results
  Intensity is changed back to normal.
- Actual results (with terminal output if applicable)
  Bold text persists.
- Your Windows build number
  14393.321
- Steps / All commands required to reproduce the error from a brand new installation
  Run `echo -e "\033[1mhello\033[22mthere"`. `hello` is correctly in bold, but `there` is still bold after the intensity reset. The foreground colour of the cosole is also bold after the command has exited.

**Comment by zadjii-msft** [comment]
Yes, we're aware `CSI 22 m` doesn't work. On the feature backlog, item 9553354

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is on our internal backlog and will be implemented when we build a new text renderer
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
