### ISSUE TITLE
sshfs doesn't work, something with fuse

### ISSUE THREAD

**Issue by elisaado** [Microsoft/WSL#1309]
I tried to mount my raspberry pi to a folder via sshfs, i installed it via `sudo apt-get install sshfs`, and then I tried to mount my raspberry pi.

Normally it should just mount the folder as an external drive or something.

But what happend is this:
```
eli@xxxxxx:~$ sshfs  xx@xxxxxx.xx: RPi
fuse: device not found, try 'modprobe fuse' first
```

So I did what they want me to do:

```
eli@PROBOOK:~$ sudo modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin'
```

* Your Windows build number
14393

* Steps / All commands required to reproduce the error from a brand new installation 
```
sudo apt-get install sshfs
cd ~
mkdir folder
sshfs username@server: folder
```
And the thing what I did, don't know if it has anything to do with it:
`sudo modprobe fuser`

* Strace of the failing command
(it was too long...)

* Required packages and commands to install
sshfs

**Comment by fpqc** [comment]
Since it uses a kernelmode driver (FUSE has one kernel module and then mounts filesystems in userspace by leveraging that driver), it won't work.  

In theory, it is possible we might see this in the future because there are undocumented NT kernelmode driver interfaces on the lxss/lxcore pico driver pair that could be used to create such a driver, but the driver would have to be a Windows driver programmed against that interface, which is practically very difficult (and for now not worthwhile, since the interface is probably highly unstable, as it was only found by reverse engineer Alex Ionescu poking around with IDA pro and a kernel debugger).

**Comment by therealkenc** [comment]
@fpqc No FUSE would be a WSL-side thing. FUSE an interface to the kernel VFS, not an interface to block and character devices (ultimately device major/minor numbers).

@elisaado there's a [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) entry for this. Feel free to up-vote; there's a lot of use cases including `sshfs` for it.

**Comment by benhillis** [comment]
@therealkenc is right. We've looked at adding FUSE support and it is going to be a significant time investment, so voting on User Voice is the best way to help us prioritize the work.

**Comment by elisaado** [comment]
Wait, so it could technically work? I voted and hope to see this feature! And yeah @therealkenc is indeed right about that FUSE is at the WSL side.

**Comment by therealkenc** [comment]
It could technically work. This is really a dup of #412 which is marked as 'feature' (we can dream).

**Comment by runzexia** [comment]
I hope to see this feature!
