### ISSUE TITLE
Possible security breach hole regarding LXSS?

### ISSUE THREAD

**Issue by DJviolin** [Microsoft/WSL#1313]
After experiencing a ransomware attack in my family and having 3 in our workplace, I'm courious: a virus can use the tools that's inside LXSS? Or worse, modifying the host files, permissions or encrypt them? One particular virus used VBscript self executed inside a zip (email attachment) to download the encryption tool in my office. For the same reason, I renamed the Powershell folders on my PC and turned off VBscript execution in the registry. Java, Flash also not installed.

A linux distro comes with Python and Perl which are the perfect tools for spread some nasty stuff. LXSS apps not part of PATH of the host, which is good if we think about security. Of course, LXSS only installed by developers, that's why I think never be the target of hackers.

Having an install option flag to not share the entire host file system to LXSS under `/mnt` or only share the selected folders will be an option to not be possible to modify the entire file system to an attacker (if it's possible)?

**Comment by fpqc** [comment]
Right now the security is mainly through a mix of obscurity and Windows security. Ransomware is particularly menacing because it does not need to maintain persistence for an unlimited time and doesn't require administrative privileges, another reason why you need to be very careful with things like public Windows/Samba shares, mandatory lockout timers, disallowing caching of credentials, backups, the works, enforce group policy to require UAC & password for all administrative actions.  

Like the beginning of WW2, you need to assume that because of user error,  the bomber will always get through.

Compromise of WSL has the exact same level privilege to be gained as compromise of an unprivileged user by design (although it is yet to be seen how well the new kernel/driver attack surface holds up against sustained attack).

**Comment by benhillis** [comment]
@DJviolin the ability to configure which drives are mounted under /mnt is something we're definitely something that's on our backlog.

**Comment by fpqc** [comment]
@benhillis You will also need to either come up with a way to sandbox win32 executables launched from inside WSL accessing parts of the Windows filesystem that aren't mounted, or you have to add a way to disable interop for some users (either mess around with permissions and ownership of /init (require root, restrict to a usergroup, or implement either Linux ACLs or capabilities, there are a number of options).

The addition of custom low-integrity tokens for WSL users could be an ideal solution, since it would provide a non-breaking way to emulate Linux permissions directly in the Windows ACLs, the tokens could be used to propagate permissions to interop, plus it would allow direct writing from Win32 applications to VolFS, because all Win32 file operations (to my knowledge) respect the Windows ACLs.

The idea would be that each Windows user would have a root token (this is identical to the User's token).  Then each created UNIX user in WSL would have a restricted subtoken of the User's root token that by default is denied by all ACLs unless they have permission granted.   

I'm thinking of something along the lines of attaching something like an active directory group to each Windows user, and making Linux groups and Users correspond to subgroups and users of that AD group.

**Comment by therealkenc** [comment]
The improvements Ben alluded to back in Nov 2016 are available in the April Update.
