### ISSUE TITLE
Editing Linux files

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/WSL#1319]
So from reading through the issues and working with the linux subsystem, I have learned that you cannot edit the files created in linux subsystem with a Windows editor. So my question is, is it expected that I use vim or any other non-gui editors? Or are we suppose to install something like Xming and forward the display and in the linux system install a gui app there? Thanks for any insight you can give

**Comment by fpqc** [comment]
No, just don't edit them in /home/youruser.  Make a folder in Windows, call it 

`%userprofile%\projects`

In Windows subsystem for linux, do the following:

`ln -s /mnt/c/Users/[YourWindowsUserName]/projects ~/projects`

Any Linux-related file that you want to edit, edit it in `~/projects`, and you will be 100% fine.

The problem is that files edited on the Linux Filesystem with a Windows editor deletes important extended attributes that the linux filesystem uses, because Windows editors can't understand them.

**Comment by jrock2004** [comment]
Thanks. I will give this a try

**Comment by tjfryan** [comment]
@fpqc Is it safe to assume that editing a file this way won't trigger inotify events?

**Comment by fpqc** [comment]
@tjfryan There was an update and supposedly it will now.

**Comment by tjfryan** [comment]
@fpqc I've heard that inotify is now implemented, but the way I've always assumed inotify to work is that the operating system sends an update when you edit a file, as you're using that operating system to edit the file.  If you're editing a file from Windows-land (via notepad or vscode or what have you) will inotify trigger in WSL-land?

**Comment by fpqc** [comment]
@tjfryan Yeah, they said they did it somehow on DriveFS. Just try it!

**Comment by therealkenc** [comment]
Discussion ran course. Options for editing in WSL:

- Use DrvFs (`/mnt/c`) and a Win32 editor
- Use a console editor like vim and nano
- Use a graphic editor like Sublime or GEdit with VcXsvr/Xming, but be on your own if you run into difficulties because the scenario is not currently officially supported.
