### ISSUE TITLE
Ctrl+Meta modifiers don't work on keys

### ISSUE THREAD

**Issue by hacker65536** [Microsoft/WSL#1337]
```bash
$ echo aaa bbb ccc
aaa bbb ccc
```

```bash
$ echo #  ctrl+[ ,  2
(arg: 2)   # ctrl + alt + y it's not working
```

```
>ver

Microsoft Windows [Version 10.0.14393]
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by zadjii-msft** [comment]
So after looking at this a bit, it's not that this particular command doesn't work, but more generally, that using the ctrl and meta modifiers simultaneously doesn't seem to work.

I'm gonna update the title accordingly, and filed MSFT:9765193 to track this

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
