### ISSUE TITLE
Console not respects font bearings

### ISSUE THREAD

**Issue by zerocool4u2** [Microsoft/WSL#1359]
This is probably a console issue
* A brief description
In RS1 you could use any font that is configured to be a monospace one in its settings, in my current version 14955.1000(slow ring insider preview) the bearing parameters of each character are not get used for chars that are bigger than the minimal width in point of the font, for example, the current max size you could use in a monospace font of 1228 points of width is 20 on the left bearing, 20 on the right one and a width of 1188 for the character itself, currently if you exceed those parameters you get a chars that uses two spaces in the console independent of what is seted for that specifically char.

* Expected results
The previous behavior of using the bearings and width of char to determinate the space that is used in the console, with this way you could trick it with negative right bearings and add a glyph plus a blank space to show it, i guess that the current behavior would be kept, in this case linux should "know" that that characters uses two spaces. Ideally if you set a char to use double, triple spaces, it would recognize that the char use that size

* Actual results (with terminal output if applicable)
If you have a double size glyph or char the terminal would print this correctly, but will leave a trail of blanks spaces at the end of your output, same result if you have a double size glyph seted to use a single space.

* Your Windows build number
14955.1000
* Steps / All commands required to reproduce the error from a brand new installation 
Is kind hard to see it because the blank spaces are seen at the end your output, one way to do it would be
    * Use a font that have double space glyph, echo that character and a trail of the width of your console, `tput cols` would give this value
    * If you have configured zsh with oh-my-zsh, the right prompts show the problems when you have double size glyphs on the plugins, for each double size icon you have, it will give a trail space that messed it with the width of your console a forces it to prompt on a new line
* Strace of the failing command
-

* Required packages and commands to install
If you want to check it with zsh, use apt-get and clone oh-my-zsh, then use any font with double size icons, nerdfonts have many of those.

The image shows what i mean for bearings and the char configurations, you can see that i get 3 trailing spaces that pushes the content of the right prompt to the next line and let it you unable to write on the first line after the git data, the cursor should be after "master > ", but you get it on the next line on top of the first char, currently you can have only one icon without getting an error, two or more would produce n-1 trailing spaces, that's the only behavior i couldn't identify why, my best guest is that you can set an empty space after the left prompt, who fixes the calculations of the columns for that side, if you have only one icon on the right prompt you still gets the error.
![sin titulo](https://cloud.githubusercontent.com/assets/1785923/20256338/92d7cbd4-aa21-11e6-83f1-f3397c8ae464.png)

Sorry about the bad english. regards!

**Comment by zerocool4u2** [comment]
found a patch solution for now, changing the buffer size of the screen to a bigger size than the actual size of the screen would leave room for the trailing spaces(as much as icons i would spect), not ideal, but at least it shows more or less as spected, i'm printing twice the "history" plugin to be able to see all the content on every moment.
![sin titulo2](https://cloud.githubusercontent.com/assets/1785923/20257096/43924202-aa26-11e6-9ef3-86ccedbe97a3.png)
d.

**Comment by fpqc** [comment]
@zerocool4u2 put your zsh config and font up on github that's so cool looking!!!!

**Comment by zerocool4u2** [comment]
@fpqc I'm gonna do that in the future, the font is courier prime code, but is a patched version by myself and a current work in progress, when this is fixed I'm gonna be able to have the guidelines for finishing the patch, the theme is powerlevel9k for oh-my-zsh and here are the colors, regards

1. 0 0 0
* 0 84 158
* 100 152 0
* 42 161 152
* 190 20 0
* 123 50 153
* 180 156 0
* 202 202 202
* 124 124 124 
* 37 138 209
* 0 220 0
* 137 215 191
* 219 50 46
* 211 122 255
* 220 220 0
* 255 255 255

![sin titulo3](https://cloud.githubusercontent.com/assets/1785923/20282525/d5ce61d8-aa93-11e6-8edd-fa318a794543.png)

**Comment by fpqc** [comment]
export your bash.exe regkey

HKCU\Console\bash.exe I believe.

**Comment by zadjii-msft** [comment]
Pinging @paulcam206 @miniksa for insight. Did we make a change to which monospace fonts are valid/how certain characters are rendered? I vaguely recall something like that happening, but I could be mistaken.

In general, I'd say that if you're doing something to "trick" the console into doing something for your specific use case, then I'd not expect it to work in all future releases :P

**Comment by miniksa** [comment]
The short answer is: you're being trickier than the console can handle right now and this will probably change and might break in the future when we work on improving rendering.

The longer answer is:
Right now, the internals of the console only understand two possible scenarios:
- 1 character = 1 column.
- 1 character = 2 columns.

And note that is integer columns. Exactly 1 or exactly 2 columns. No decimals, no partial columns. If you have slightly too few or too many pixels, it's going to render strangely. 

The console has long used this assumption that characters are either exactly 1 or 2 columns wide. 
The rule was:
- If this Unicode codepoint belongs to a generally Western range of characters, it is 1 column wide.
- If this Unicode codepoint belongs to a generally full-width Chinese, Japanese, or Korean range of characters, it is 2 columns wide.
- Otherwise, ask GDI how many pixels wide this character will be in the current font and divide by the width in pixels of the character '0'. If it's larger than one '0' in width, it is 2 columns. Otherwise, it is 1 column.

The thing that changed recently is that I updated this algorithm to better encompass a wider range of Unicode values using the definitions at http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt. This improved the width check for some ranges of Unicode characters but didn't fully cover all sorts of things including zero width characters and an arbitrary N characters fitting an arbitrary M columns.

The console will then feed "runs" of text into GDI and assume that it will render them exactly as it guessed at perfectly 1 or 2 columns per character and use that raw assumption when performing math calculations between raw pixel values from invalid paint regions, mouse clicks, etc. and the character row/column positioning. 

This falls down when GDI decides to render something at not perfect 1x or 2x multiples of column widths, when a character isn't exactly a 1x or 2x pixel multiple of the '0' character, or when you change to a font with a different estimated width between when the character was inserted into the buffer and when it was rendered.

The rendering system in the console is very naïve and makes assumptions that don't always hold up like in your case here. The way that this was dealt with in the past was to limit you to using only a defined list of fonts hardcoded in the system. I believe there were 6 fonts total and in any given codepage, that was typically further restricted to offer you between 1 and 3 valid fonts.

We removed that hard coded list restriction (and now only check if the font reports monospaced/fixed-width) because we believe that our customers can figure out which fonts work for them and to choose a different font when it isn't working right. But we're not all the way there yet on improving the renderer to remove these old long standing and arguably bad assumptions. Improving this area is definitely on the backlog. 

There is a lot more to discuss in terms of how the console stores characters, how the console chooses to render text, and what my plans are for improving this in the future. I hope to make it the topic of a future blog post like I've mentioned elsewhere on GitHub whenever I can get @bitcrazed to help me.

**Comment by zerocool4u2** [comment]
@miniksa Thanks for your time, i really appreciate it, all the changes makes sense, 1x or 2x is perfect for most scenarios and is great to have a more insightful view of what its happening under the hood. By what i understand now, the problem would be more easy to explain with an example, lets say i have 192 columns width, if i print 192 1x chars it would be ok, but if i print 191 1x and 1 2x, columns would say this is 192 columns long, but in fact it would be 193, so it will push the last character to the next line, now i understand what where the "trailing white spaces" that i mentioned before and if you try to position the cursor at some col it would be shifted by that difference or if the cols exceed the width it would be placed at the newline, thanks again, regards!

**Comment by zerocool4u2** [comment]
@miniksa the bearings are working again =D, I suppose that I should close this =)
![bash](https://user-images.githubusercontent.com/1785923/33522556-2e622736-d7ce-11e7-839b-36437b359bad.png)

**Comment by miniksa** [comment]
Great to hear! Yes, you are welcome to close it.

**Comment by fpqc** [comment]
@zerocool4u2 what font is that? That's amazing!

**Comment by zerocool4u2** [comment]
[Courier Prime Code Patched half barrels and extra standard glyphs.zip](https://github.com/Microsoft/WSL/files/1530031/Courier.Prime.Code.Patched.half.barrels.and.extra.standard.glyphs.zip)
@fpqc Is a custom version of Courier Primer Code, I've been working in this one for a while, thanks @miniksa, regards!

**Comment by fpqc** [comment]
@zerocool4u2 any chance you could put the project on github or something?
