### ISSUE TITLE
[open_sockraw] socket(): Protocol  not supported.

### ISSUE THREAD

**Issue by fhackman** [microsoft/WSL#1383]
whenever i use hping3 i get the following error
[open_sockraw] socket(): Protocol  not supported.
[main] can’t open raw socket
please Help me

**Comment by sunilmut** [comment]
Raw sockets are currently only limited to the ICMP protocol. If you can share the strace (`strace -o <cmd> -ff <trace_file>`, we can identify what exactly is missing/going on. Thanks for trying out WSL!

**Comment by sunilmut** [comment]
Also, do identify which Windows build you are on.

**Comment by madisonleavo** [comment]
I have the same error when running 
`$ tcptraceroute host 1883`
`libnet_init() failed: libnet_open_raw4(): SOCK_RAW allocation failed: Protocol not supported`

` $ sudo traceroute -T -p port host`
`socket: Protocol not supported`

Version 1607 (OS Build 14393.953)

**Comment by sunilmut** [comment]
@madisonleavo - Thanks for your feedback. Yes, `tracepath/traceroute` currently does not work on WSL. See #717. I am marking this duplicate. [Here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) is the user voice page for the same, please upvote if you would like us to prioritize this.

Also, we have made significant updates to WSL since the 14393 build (Anniversary Update). You will definitely have a better experience with WSL if you can upgrade.

**Comment by v0idst4r** [comment]
```
[open_pcap] pcap_open_live: eth1: socket: Invalid argument
[main] open_pcap failed
```
On 1709 (16299.248)

**Comment by ksaltik** [comment]
Creators update still same error

**Comment by floreslorca** [comment]
this still doesnt work

**Comment by rastuch** [comment]
> this still doesnt work tried on Kali Linux

this same.

**Comment by OhMySynaticall** [comment]
[open_pcap] pcap_open_live: socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported
[main] open_pcap failed
This is my problem need some help

**Comment by therealkenc** [comment]
This one was deemed /dupe #717 but not closed.
