### ISSUE TITLE
Some mouse wheel actions and trackpad gestures are erroneously translated into Mouse Button 5 events

### ISSUE THREAD

**Issue by lilred** [Microsoft/WSL#1390]
This is on build 14965, on a Surface Book, using a Microsoft Sculpt Comfort mouse. The problem is two-fold:

1. The trackpad gesture for "scroll up" triggers a downwards scroll. "scroll down" works as expected.
2. Middle-clicking with a mouse triggers a downwards scroll.

I am giving two reproductions: the first shows how this issue can come up in the real world, and the second is a lower-level perspective which elucidates what is happening.

Repro 1 (real world):

1. Open `vim ~/.bashrc`.
2. Enter `:set mouse=a`.
3. Use a mouse's scroll wheel to scroll up and down; notice that the document does indeed scroll up and down.
4. Use the trackpad to scroll up and down; notice that in either direction the document scrolls down.
5. Press the mouse's middle button; notice that the document scrolls down.

Repro 2 (low-level perspective):

1. enter `echo -e "\e[?1000h\e[?1006h"` (as defined in `ctlseqs`: repo: 1000h "send mouse X & Y on button press and release", and 1006h is "format in decimal").

2. Use a mouse wheel to scroll up. Notice that `64:xx:yy:M` gets printed, corresponding to "Mouse Button 4" (see `ctlseqs` document).

3. Use a mouse wheel to scroll down. Notice that `65:xx:yy:M` gets printed, corresponding to "Mouse Button 5".

4. Use a trackpad to scroll up and down. Notice that in both directions `65:xx:yy:M` gets printed, corresponding to "Mouse Button 5" (AKA scroll down).

5. Press the mouse's middle button. Notice that a stream of `65:xx:yy:M` events get printed. (Expected result: a single `2:xx:yy:M` should print.)

**Comment by zadjii-msft** [comment]
@lilred out of curiosity, does the trackpad scrolling work in a plain old CMD session? Or even in the normal bash output? Or does this only manifest in mouse-mode applications?

**Comment by lilred** [comment]
Trackpad scrolling works properly in cmd.exe and in non-mouse mode applications.

**Comment by zadjii-msft** [comment]
Ah, good to know. Makes the amount of code that needs inspecting very small :) I've opened MSFT:9893723 to track this issue.

**Comment by zadjii-msft** [comment]
This one I was able to figure out. Turns out on trackpad devices, they scroll in increments less that `SCROLL_DELTA`, and we were ignoring anything less than that. So I fixed that.

As far as the mouse sending scroll events on the middle click, I believe that may be due to an overly sensitive mouse wheel. I know one of my mice is particularly tricky to middle click with, due to the fact that it will scroll just slightly when I try clicking it (just enough to scroll away from the link I was trying to click on :P).

**Comment by lilred** [comment]
>As far as the mouse sending scroll events on the middle click, I believe that may be due to an overly sensitive mouse wheel.

Since this is a Microsoft Sculpt mouse, it would be unfortunate if it didn't work properly with Bash on Windows ;)

I'll try to find a native Ubuntu install to test the middle-click with and report back with what behaviour I observe.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
