### ISSUE TITLE
[question] user-space linux API vs full virtualization performance?

### ISSUE THREAD

**Issue by georgir** [Microsoft/WSL#1417]
How much lighter or better performant is the current user-space-only approach compared to for example a headless virtual machine running stock linux kernel with a custom module (like "vmware tools" or vbox "guest additions" or hyper-v "linux integration services") that can be used to launch, monitor and control processes with tty redirection, in a way that the fancy cmd terminal integrations can still happen?

And has there actually been any consideration of the possibility to plan and develop the cmd terminal integration/tty redirection in such a way that they can benefit not only LXSS but other subsystems?

**Comment by aseering** [comment]
@georgir -- something close to the "headless virtual machine" approach that you describe already exists as [Docker for Windows](https://www.docker.com/).  A lot of people use it; it's very effective.  I think WSL has somewhat-different objectives.

Performance-wise, anecdotally / in my experience, WSL has no significant advantage over Linux processes running in Linux user-space.  Its disk-IO performance has actually been reported as being several times worse than that of a Linux VM at the moment; there are a few issues tracking that problem.  To me, this is no surprise:  VMs for the most part have very low overhead these days, and Linux is an efficient piece of code; Windows is not going to beat Linux at Linux's own game.

(VMs do have memory overhead, off the top of my head I think typically hundreds of MB, and you have to wait for them to boot.  This can matter in resource-constrained environments.)

The way in which WSL has a reason to win in my opinion is that tight integrations with Windows should be much easier.  Yes, you can do anything with a VM that you can do with something like WSL; but if WSL makes it dramatically easier to implement those integrations, then we'll see more of them and they will work better.  We're already starting to see some of this:  (Note that many of these only work in recent Insider builds.)

* Filesystem integration:  Accessing a Windows file from a WSL application works roughly as well as accessing a Windows file from a Windows application.  You can edit the code for your project using a Windows editor while the project runs in Linux, and the running project can live-update as you make your changes.  From the NT kernel's perspective, it's just two processes both accessing a file.  In contrast, while VMs these days can access files on the host, it's often [complex](https://social.technet.microsoft.com/Forums/windows/en-US/ba1d4fdf-9eee-46ae-bdc8-fcbc807b1d0f/how-can-i-access-the-host-file-system-from-a-hyperv-image?forum=winserverhyperv), [slow](https://github.com/docker/docker/issues/21485), [fragile](https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/15), [and](https://www.virtualbox.org/ticket/10031) [buggy](https://communities.vmware.com/message/2440375).
* WSL processes can launch native Windows processes directly.  You can have a Linux shell script that launches a bunch of command-line Windows processes and pipes data between them.
* You can launch a Web-server process listening on TCP `localhost` within WSL and navigate to it on `localhost` within a Windows browser.  No need to mess with IP addresses or firewalls because the TCP stack is shared.  (In fact, because of the previous point, you can have your Linux script automatically launch that browser window for you.  Common Web-dev workflow.)
* You can manage your individual Linux processes from the Windows Task Manager, and using third-party tools aimed at managing Windows processes.
* Also, lots of terminal integrations -- for example, you can edit your C++ code in a Windows-based IDE and have it compile a Linux binary using Linux compilers -- but that's arguably implicitly also provided by your requirement that the VM-based approach have good terminal integrations.

Again, you *could* do everything above with a VM.  WSL's gamble is that a complete WSL-based software-development ecosystem, including not just the core Linux compatibility layer (which is a huge pile of complexity) but also these and presumably many more integrations, will as a whole be more robust and faster to implement than the same using a VM.

Note that the WSL team's initial target audience is developers using Windows to develop Linux software -- that particular use case, using existing graphical Windows development tools to manipulate Linux software, benefits from very tight integration.  (WSL is also a gamble that this is a large and important target audience.  My expectation is that a large number of people will think that WSL is nuts for targeting such a silly use case, and a different large number of people will eagerly line up to use it to solve exactly that use case :-) )


To answer your second question:  Yes, the terminal integrations are already being used by other third-party programs.

**Comment by fpqc** [comment]
@aseering Also running a vm takes substantial amounts of resources on something like a laptop.  WSL can share system resources with your Windows system, without having to assign dedicated CPU and memory to  a VM.

**Comment by aseering** [comment]
@fpqc -- have you tried running, for example, Docker (with its embedded mini-VM)?  If you install Ubuntu Desktop in a VM, sure it has a whole lot of overhead.  But if you cut out the entire userspace and strip the kernel down to the essentials needed to run in a virtualized environment, and you tune that VM for efficiency, it still has some overhead, but it's plenty lightweight enough that I'm happy to leave it running on my laptop.

**Comment by therealkenc** [comment]
@aseering is right. Any bloat having to do with VMs is mostly self-inflicted (by the user or by the VM implementer, or both). Any performance overhead you see is "device layer" related, and that's mostly noise wiped out by Moore's Law for any given moment in history plus six months.

You're also exactly right that there's nothing you can't do with WSL that you haven't been able to do in a VM for the last decade. The entire "Run any Desktop Environment in WSL" issue could be a Stack Overflow thread with the title "How do I make XcXsrv run with Ubuntu". Filesystem integration is smb/cifs or vboxsf. Wsltty is neat, but it actually communicates over ipv4 and amounts to "a better PuTTY without the security because localhost".

The recent pipe interop is novel, but the fact that it uses the ADSS Bus is actually just implementation detail. You could have done `/dev/lxss` on Real Linux™ with a kernel module or even CUSE, and done the IPC over ipv4<sup><sub>1</sub></sup>. That is, `LxssManager` and `bash.exe` didn't need to be written by Microsoft at all. Shimming the syscalls and ELF is literally the _hardest_ way to go have gone about the whole exercise, which is precisely what makes it all so damn cool.

<sup><sub>1</sub></sup><sub>mapping memory between WSL/Windows has new possibilities that streaming IPC doesn't, but you can do mmap with VM technology too - that's the "driver layer" related stuff aforementioned</sub>

**Comment by therealkenc** [comment]
Ran course.
