### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by itamblyn** [Microsoft/WSL#1428]
On a linux box, I can do

sudo apt-get install ssh

This will enable incoming ssh connections. Bash on windows doesn't seem to behave this way...

**Comment by aseering** [comment]
Thanks @itamblyn for posting!  WSL doesn't support Linux daemons/services very well right now.  The specific case of ssh is discussed in #612 .

**Comment by fpqc** [comment]
Because upstart/systemd don't start on WSL for now, but given that we now have cgfs implemented, it might be coming.

**Comment by itamblyn** [comment]
Thanks for the quick reply.

I followed that thread just now, and I notice a few things

1) I have to use sudo to get it to start (i.e. sudo start sshd server)

2) after it starts, and I run ssh localhost, I get "Permission denied
(publickey)"

I deleted my .ssh directory to see if that matters - it does not.

Do I need to modify something in /etc/sshd/ssh_config ?

- Isaac

**Comment by fpqc** [comment]
You can add a sudoers entry to allow nopasswd execution of the sshd binary (not on port 22, try 2222).  This is a major duplicate since there is a 100-post thread discussing running sshd on WSL.

**Comment by itamblyn** [comment]
Re: 100 post thread - shouldn't there be a simple doc somewhere that
indicates how to do this? This is a pretty common thing people will want to
do. :)

- Isaac

**Comment by fpqc** [comment]
@itamblyn @aseering made a forum with a bunch of workaround guides.  I forget the URL offhand so I am pinging him.

**Comment by rodrymbo** [comment]
[Here's the link.](https://wsl-forum.qztc.io/viewtopic.php?f=6&t=10)

It may include some workarounds that aren't really needed any more, but it should give you the idea.

The principle is pretty clear: sshd can start from a bash script, so even if systemd/upstart is not working properly (yet), it is not an impossible task. (Bash scripts are why we are here, after all). The trick is that the Bash.exe window in which sshd runs must not close. (Actually, it is the last open bash.exe windows that must not close, otherwise the whole WSL subsystem is shut down.)

Service and systemctl, if they work at all, manually start the service. Sometimes one can fool onseself into thinking traditional services might work as expected. They don't. Yet. So use Windows Task Scheduler to start a bash script on login that runs sshd and then doesn't close its bash.exe window and it is almost like having it run as a system service. 

So:

- services don't run automatically just because you install them (yet)
- most programs, e.g. sshd, run just fine, with perhaps a bit of tweaking
- it's possible to have them run automatically when you log in, if you observe the oddities of the WSL environment

**Comment by itamblyn** [comment]
Thanks!

- Isaac

**Comment by therealkenc** [comment]
#612.
