### ISSUE TITLE
Terminal is ... clunky

### ISSUE THREAD

**Issue by itamblyn** [Microsoft/WSL#1429]
This isn't so much a bug or a feature request as it is a comment. I find that that default terminal emulator is ... clunky. It doesn't feel like an xterm style emulator that I would have in linux. It reminds me of the old cygwin days (the default terminal was like putty, but the xterm version wasn't that bad). This isn't a deal breaker, but a nicer terminal window would make a big difference :)

**Comment by fpqc** [comment]
I understand, but Rome wasn't built in a day.  The console team is working on providing a modern client/server model for the new console subsystem (Redstone 3 roadmapped feature), but remember that a big rework/rewrite of large parts has to keep things backwards compatibile.

**Comment by itamblyn** [comment]
Fair enough. I hesitated even posting it, but to be honest little things
like this end up being a big deal in terms of people being willing to work
with a tool for day to day work.

That said, I am very impressed with how well things are working already.
It's pretty neat!

- Isaac

**Comment by fpqc** [comment]
@itamblyn I think it could be really cool for e.g. nano server.  If the Recovery dialogue/Console for nano server could be replaced with a stripped down proper console, that would be pretty great.

**Comment by aseering** [comment]
@itamblyn -- thanks for posting; I think the console team is aware of this and is working on it, but I'm sure they appreciate the reminder that people are looking forward to their work :-)

It's hard in part because of backwards compatibility -- a Windows console behaves differently from a Linux terminal, and there's lots of very-old terminal code out there that depends on some of the obscure behavioral edge cases.  Building a program that correctly handles all the old behavior and all the new behavior at the same time is a little tricky.  If you're willing to use a new program entirely, there are already alternatives, such as [wsltty](https://github.com/mintty/wsltty).

Are you familiar with the [WSL UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)?  It has largely been co-opted by WSL at this point, but it was originally intended as a place for people to post specific requests for improving the console.

**Comment by quiret** [comment]
Please never change that caps-lock triggers on Windows uniformly per button-down event. On Linux they like typewriters so it trigger on button-up for release.

**Comment by fpqc** [comment]
@quiret Yeah, also the sane clipboard of Windows.

**Comment by Trozz** [comment]
@fpqc what do you mean sane clipboard? the clipboard on a standard windows machine is worse in usage than on most linux counterparts, the ability to highlight and perform a shallow copy/paste without overriding the buffer is a great move on Linux...

**Comment by CherryDT** [comment]
Btw if you want xterm, you can just use xterm (or anything other terminal which runs on Ubuntu).

All you need to do is install an X server on Windows (I recommend VcXsrv because it works much better for me than Xming, in areas such as clipboard sharing, taskbar integration and such), set your `DISPLAY` variable to `:0` in WSL and install and run `xterm`. You could also make yourself a little VBScript which runs `bash -c DISPLAY=:0 xterm` in a hidden window so you don't have an additional useless console window open.

**Comment by fpqc** [comment]
@cherrydt yeah we know.

**Comment by LordMonoxide** [comment]
I just run sshd and use msys2 to `ssh localhost`... works fantastically
