### ISSUE TITLE
3rd party autohotkey keyboard layout delayed typing, clunky, sluggish, fine in powershell

### ISSUE THREAD

**Issue by HenningJW** [Microsoft/WSL#1486]
* A brief description
When using the [bone layout](https://wiki.neo-layout.org/attachment/wiki/Bone2/bone.exe) via 32bit autohotkey script that uses  DllCall("SendInput,xxx") to send inputs every keyboard input is sluggish. This is especially noticeable when holding backspace, in powershell etc. the cursor stops immediately when releasing the key, in bash on windows continues for quite some characters. It feels like a buffer is filled. Also the combination of capslock+c, which should return | returns ° instead. So I am not sure if the input to the ahk script is triggering the "bug" or the output, I am willing to investigate here.

However everything is working as intended when I start powershell and run bash in it.

* Expected results
No sluggish typing, working like powershell.

* Actual results (with terminal output if applicable)
sluggish typing

* Your Windows build number
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393

* Steps / All commands required to reproduce the error from a brand new installation 
Start bone.exe and start to type. Best to see if you type a long string an press backspace until it auto repeats and depress and watch the cursor.
* Strace of the failing command
not applicable
* Required packages and commands to install
bone.exe

**Comment by fpqc** [comment]
Disable the BoneLayout inside of the console and enable it with the Linux Locale and Keymap settings.  WSL does very special processing on keyboard input and using sendinput will not work correctly with it.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and may have been fixed in recent Win10 builds
1. Linux expects raw keystrokes so preprocessing keystrokes in Windows and then sending them into a Linux instance is likely to get very messy, very quickly. If you want to remap keys, try doing so from within Linux itself, rather than in Windows
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
