### ISSUE TITLE
Hosts file is not inherit on bash

### ISSUE THREAD

**Issue by yupal** [Microsoft/WSL#149]
Maybe this is more a feature than a bug, 
but the hosts file in Windows should be linked to one in linux

**Comment by nuclearmistake** [comment]
```ln -sf /mnt/c/WINDOWS/System32/Drivers/etc/hosts /etc/hosts```?

**Comment by russalex** [comment]
Interesting idea.  At this point we have deliberately not tried to keep WSL in sync with Windows files simply due to the confusion on if one or the other changes.  This is something we should revisit in the future.

I would suggest putting this in [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash).

**Comment by bitcrazed** [comment]
Closing for now. Please add to https://aka.ms/winbashuv if you would like us to revisit.

**Comment by benhillis** [comment]
I'd like to keep this one open.  I plan on looking at this soon.

**Comment by kamil7x** [comment]
Hello, how's it going? I know that I can link hosts file by myself, but I think, it should be added by default

**Comment by ccampbellsoln** [comment]
Any news  on this? I can link the file and open it but it is read only. `"/etc/hosts" [readonly][dos] 139L, 4077C`. Is there another work around?

**Comment by sunilmut** [comment]
`/etc/hosts` now inherits from the Windows `hosts` file since Insider build [16184](https://github.com/Microsoft/BashOnWindows/issues/149#issuecomment-325663156). But, this change is currently only available on Windows Insider build, but, will also be available on Fall Creators Update.

**Comment by jienco** [comment]
I just tested the feature in the Insider build and works well. Thanks very much for this feature!

**Comment by strarsis** [comment]
Found this:
https://github.com/shayne/go-wsl2-host
