### ISSUE TITLE
display issue well using powerhshell 6.0 alpha14

### ISSUE THREAD

**Issue by chantisnake** [Microsoft/WSL#1539]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
the powershell inside the WSL does not display correctly

* Expected results
it works...

* Actual results (with terminal output if applicable)
![test](https://cloud.githubusercontent.com/assets/10100995/21471203/6a814fac-caa1-11e6-82f9-ab2fa8458a34.gif)
this happens both on the default host and conemu

* Your Windows build number
Version 1607 build 14393.576

* Steps / All commands required to reproduce the error from a brand new installation 
```
sudo apt-get install libunwind8
sudo dpkg -i powershell_6.0.0-alpha.14-1ubuntu1.14.04.1_amd64.deb
powershell
```

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @chantisnake , thanks for reporting this!

Would you consider joining the [Insider program](http://insider.windows.com/) and trying out an Insider build?  Either on your own machine, or by downloading a Preview [VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

A *lot* of console issues have been fixed in recent Insider builds.  Those fixes will make it to stable Windows in a few months, when the next stable release comes out.

**Comment by leojbgiusti** [comment]
I can confirm on 14986 that when entering a command the cursor resets back to the top of the screen overwriting the output of the previous command.

p.s. what is the best way to capture the GIFs of Bash?

**Comment by chantisnake** [comment]
screen to gif

**Comment by sunilmut** [comment]
Thanks for the report. Looks related to console. @zadjii-msft or @bitcrazed should be able to provide some information around this.

**Comment by zadjii-msft** [comment]
This is a pretty well known issue - see #988, #980, #933. This comes down to a quirk in the dotnet core's linux implementation that didn't play well with conhost. The bug was opened up on them (I can't find the thread ATM), and IIRC they resolved it and should be coming in a future dotnet release.

**Comment by lypanov** [comment]
From the Powershell/.NET Linux  side there is no movement on this. I've switched to using Token2Shell/MD Windows 10 Application which solves this and many many other problems with conhost.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
