### ISSUE TITLE
Tab completion in cmd.exe broken inside Bash

### ISSUE THREAD

**Issue by leojbgiusti** [Microsoft/WSL#1542]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Attempting to tab complete a path in cmd.exe launched from within bash doesn't work. I hope this is not a duplicate.

* Expected results

Path to be completed when tab is pressed.

* Actual results (with terminal output if applicable)

Tab character inserted rather than path completed

* Your Windows build number

14986

* Steps / All commands required to reproduce the error from a brand new installation 

/mnt/c/Windows/System32/cmd.exe
dir C:/U <tab> - fails at the tab

* Strace of the failing command

none - happens in a Windows .exe

* Required packages and commands to install

none

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
@leojbgiusti That would require a shell modification or a zsh plugin.

**Comment by benhillis** [comment]
This is a known issue on our backlog, but as @fpqc mentions this will require some changes to the NT console code.

**Comment by fpqc** [comment]
@benhillis By the way, this happens even if you launched cmd interop from inside of Mintty through the wslbridge, so I think it might need not necessarily console enhancement but actually cmd.exe enhancement (perhaps forcing cmd.exe to launch specifically with terminal processing enabled on inputs with `SetConsoleMode(cmdInputHandle,ENABLE_VIRTUAL_TERMINAL_INPUT)`, so I don't know if it's quite just a console fix.

It's not so obvious how to do this, however, since those console modes on handles are by design not inherited.  Or maybe I'm mistaken and actually it is being inherited and we want to disable it, not sure.

**Comment by benhillis** [comment]
@fpqc - You're spot on about the console mode being what's holding this up. The root of the issue is that the console mode is not a per-handle attribute.

**Comment by jcekstrom** [comment]
Has there been any movement on this issue?

**Comment by benhillis** [comment]
@jcekstrom - Yes. Coming to a skip-ahead Insider build near you soon.

**Comment by benhillis** [comment]
Functionality was added in 17618.
