### ISSUE TITLE
[Console] Support unofficial tmux clipboard control sequences

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#1594]
@zadjii-msft @bitcrazed 

Heya, Mike, Rich.  There's a new function in tmux (enabled by default if the terminfo file has the flag "Ms").  

Here's the thing from the manpage:
```
set-clipboard [on | off]
                     Attempt to set the terminal clipboard content using the \e]52;...\007 xterm(1) escape sequences.  This option is on by default if there is an Ms entry in the terminfo(5) description for the client terminal. 
```

The option can also be turned on manually if the terminfo does not support this with:
```
set-option -g set-clipboard on
```

I don't know how hard this would be to implement, because I don't know what kind of code you're working with, but this would give proper support for the tmux clipboard inside the Windows console with no fussing around with X servers or whatever, since it's only controlled by escape sequences.  This option is in the tmux git builds, not sure if it's in the official release yet.

Also, nb: This is also another example where distributing your own terminfo file would be extremely useful, since the "Ms" extension is unofficial (the unofficial "Tc" extension also enables truecolor in tmux as well). 

Edit: [Here](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html) is the documentation for xterm.  The control sequence you want to look at is
```
OSC 52 ; Pt ST
```

**Comment by fpqc** [comment]
In other news I spent last night learning to program by hacking this into `st`. The only rough part is that the escape is emitted with the selected text in base64 encoding.  Going to see if I can convince the tmux people to also emit unicode with the escape mode OSC 53 or something.  Maybe I'll make a PR or something.

**Comment by fpqc** [comment]
@zadjii-msft @miniksa This one is a piece of cake. I implemented it in `st`, `st-wayland`, and even in tmux's own internal terminal environment (to allow passing clipboards up to the top instance in the case of nested tmux instances).  I've never written a C program in my life, but in `st` and the wayland variant, it was five lines of code, and in the case of tmux, it was about thirty, so I assume you guys could do it in about 3 minutes pecking at the keys with only your noses lol.

**Comment by miniksa** [comment]
@fpqc, we're not concerned about the coding proficiency of our own noses. :P We realize that the implementation of this particular sequence is easy. 

However, given we're a part of Windows, we can't always just jump on whatever little feature we think would be cool and implement it. (Occasionally we get that opportunity and boy do we have fun!) We have to consider and rank this against the other requirements that we have from all customers of the console (including those other than Bash on Windows/WSL). Sometimes the console moves slowly to the WSL world because we're actually implementing things that influence our other customers (Powershell, CMD, Azure, OneCore, Nano Server, IoT Core, and many more) and the 100% success metric for that feature for the WSL customer is "don't break anything." :)

Also as part of a massive software project, we have to remain synchronized with the schedule that our company places upon us to perform bug fixing and stabilization during certain times of the year and implement new features in other times of the year. It's a big no-no to introduce a feature when the software product is stabilizing for RTM. 

In any note, I do agree this would be a cool feature to add, but I cannot guarantee a timeline for you right now. We do include items tagged Backlog+Console+Feature on this tracker as a part of our feature ranking for our next cycle. The best I can promise you right now is that your feedback has been tracked and will be prioritized and ranked in our next planning cycle. 

Thank you for your understanding and thank you very much for your continued enthusiasm and feedback for Bash on Windows/WSL. :)

**Comment by fpqc** [comment]
I know, I know! I was also just happy that I got a commit in tmux like one of the actually competent bros =3

**Comment by therealkenc** [comment]
Dangling console tag. Not sure the state of this one but please check out the [_Windows Console issue tracker_](https://github.com/microsoft/console).
