### ISSUE TITLE
Mysql Server Starts with Warnings,

### ISSUE THREAD

**Issue by andrey-borgoyakov** [Microsoft/WSL#1611]
Can someone  explain me how to fix next several warnings when mysql server start?
`sudo service mysql start
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  1789 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
 * Starting MySQL database server mysqld                                                                                                    No directory, logging in with HOME=/
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  2203 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
                                                                                                                                     [ OK ]
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.`

What are these errors?
Thanks

**Comment by aseering** [comment]
Hi @andrey-borgoyakov !  The Upstart warnings are because WSL doesn't support Upstart.  This means that Upstart can't track the process, but usually that's fine because you are starting and running it manually anyway.  So it should be safe to ignore them.  I'm not aware of any way to fix them.

Note that the next release of WSL will drop Upstart entirely in favor of systemd, as part of WSL's move to Ubuntu 16.04.  Systemd has its own issues; I'm guessing the WSL team is spending their time improving systemd support rather than improving Upstart support.

WSL also doesn't support Plymouth.  Plymouth is the program that manages Ubuntu's boot splash screen.  WSL doesn't boot, not in the traditional sense; it therefore doesn't have a boot splash screen.  I'm guessing that this part of the script is checking whether it's launching MySQL during system start-up; if so, it might choose to display differently so as to integrate with Plymouth.  It's not running, so you can safely ignore this message as well.  I'm not sitting in front of my Windows machine right now, but it would be interesting to know whether this check still prints the "Aborted (core dumped)" message in the latest [Insider build](http://insider.windows.com) -- Insider builds have a *lot* of updates, bugfixes, and improvements right now.

The "No directory, logging in with HOME=/" issue looks like a configuration issue, but it may be a problem with WSL's handling of user accounts.  I'd suggest looking in `/etc/passwd` for the MySQL user account to verify whether its listed home directory exists.  If not, then something went wrong during package setup; you should create the directory.  If it does exist, then I would suggest trying to log in as the mysql service's user account using something like `sudo -u <user> -i`.  If that doesn't work, and if it does work for you on a regular Linux machine, then please file another bug in this ticket-tracker with the details.

The remaining comments are, I think (?), just informational and are supposed to appear as part of the normal MySQL startup process.

Incidentally, if you're posting a multiline block of log messages, try surrounding it with three backticks rather than just one.  That will turn it into a block comment, which I think is what you want here.

**Comment by aseering** [comment]
Incidentally:  WSL, as you're seeing, doesn't have very good support for daemon processes right now.  What a lot of people have been doing is, just install the Windows version of the MySQL server; then install the Linux client and configure it to connect to `127.0.0.1` (NOT `localhost` -- MySQL in particular has special-case handling of the magic string "localhost" that breaks a lot of things including WSL).  Most client apps and drivers will see the server and connect to it just fine, and not care that it's technically a Windows process.

**Comment by therealkenc** [comment]
Ubuntu no longer uses `upstart` per Adam's comment. Ref #1329 #2000. I think much of the "database not closed cleanly" difficulties step from daemons dying a horrible death when the last terminal closed, prior to 17046. If MySQL problems persist in the April 2018 Windows 10 release (aka RS4 aka 1803 aka 17134) please reboot this one with a new issue submission.
