### ISSUE TITLE
Feature request: A persistent, guake-style terminal emulator

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/WSL#1621]
I close the windows terminals absent-mindedly all the time and I lose my place.  Please add a bash.exe feature of a guake-style global keystroke toggled, persistent session.  None of the terminal emulators available do a perfect job of this.

**Comment by fpqc** [comment]
Rich Turner mentioned this waws something he personally wanted to add, and he's the Senior PM on the console, so it might just make it in =).

**Comment by jackblades** [comment]
@JasonKleban 
Hi, I don't think any emulators currently do it and having one that covers all the cases would be nice.

However this can be achieved with wsltty (its a terminal emulator) and some autohotkey.

`
F1::
	ShowHideToggle("ahk_class mintty", "C:\Users\Username\AppData\Local\wsltty\bin\mintty.exe -w full --wsl -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/bash -c ~/tmux.sh")
Return

ShowHideToggle(WinTitle, Cmd) {
	DetectHiddenWindows, On
    if WinExist(WinTitle)
    	if IsWinVisible(WinTitle) {
			if WinActive(WinTitle)
				WinHide
			else
				WinActivate
    	} else {
			WinShow
			WinActivate
    	}
	else {
		Run %Cmd%
		WinActivate
	}
}

IsWinVisible(WinTitle) {
	WinGet, Style, Style, %WinTitle% 
	Transform, Result, BitAnd, %Style%, 0x10000000 ; 0x10000000 is WS_VISIBLE. 
	if Result <> 0 ;Window is Visible
		Return 1
	Else  ;Window is Hidden
		Return 0
}
`

This script will launch wsltty in fullscreen mode (-w full) and toggle show/hide on repeated keypresses of F1.

Cheers,
Ajit

**Comment by CherryDT** [comment]
Did you take a look at ConEmu's Quake Mode?

**Comment by fpqc** [comment]
@CherryDT Yeah but ConEMU is pretty buggy right now with WSL (not that it's Maximus's fault, a lot of the interface is built around hacks).

**Comment by jackblades** [comment]
It might be obvious but does not seem so from the above discussion, so I'll just add that wsltty != ConEmu and in my experience did not have any showstopping bugs.

**Comment by fpqc** [comment]
@jackblades If you're using wsltty in conemu, I highly suggest you move over to the following instead:

`set MSYSTEM=MINGW64 & conemu-msys2-64.exe /usr/bin/wslbridge -C ~ -t "/path/to/shell"`

This uses conemu's direct display functionality instead of conemu serving as a little host for a window. Getting this working right uses msys-2.0.dll, the conemu-msys2-64.exe, and wslbridge frontend and backend.  There is also a cygwin version of the connector (conemu-cyg-64), which has a slightly different setup.

**Comment by jackblades** [comment]
@fpqc I'm not using it within ConEmu currently but I'll try it out -- a unified terminal for both bash and powershell is only a dream right now :D

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. Future features should be upvoted/posted in our [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/filters/top?query=quake)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
