### ISSUE TITLE
The apt progress bar is not shown correctly and causes artifacts instead

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/WSL#1627]
Wheneven I'm using `apt` (not `apt-get`), the progress bar doesn't work properly.

I expect it to look like this: http://www.omgubuntu.co.uk/wp-content/uploads/2014/04/apt-progress.png

But on WSL the progress bar at the bottom only flickers into existence every now and then for a split-second, instead I causes leftovers from the invisible progress bar whenever the install progresses and the screen scrolls, as shown here: https://www.dropbox.com/s/yd5rs0cx9ey4i6q/2017-01-21%2014_02_49-david%40CHE-X1_%20~.png?dl=0

I'm on build 14986 right now but it has been like that ever since I first installed WSL on build 14393.

I have installed ConEmu, but the behavior is the same inside ConEmu, in the normal console window and also in the VSCode integrated terminal.

**Comment by fpqc** [comment]
Mike Griese mentioned that apt is a program they are specifically testing and targeting for console display bugs, so I think you can rest assured that it will be displaying properly sooner or later!

**Comment by zadjii-msft** [comment]
I'm fairly sure this isn't fixed in 14986, but it's definitely a lot better in a coming build.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
