### ISSUE TITLE
Duplicate special characters

### ISSUE THREAD

**Issue by Majsvaffla** [Microsoft/WSL#1630]
* A brief description
With swedish keyboard layout there are duplicates of ¨, ^ and ~ when typing in bash.exe.

* Expected results
The keys should output a single character after the next keypress.

* Actual results (with terminal output if applicable)
The characters are inserted both from the direct keypress and before the character from the next keypress.

* Your Windows build number
`15014`

* Steps / All commands required to reproduce the error from a brand new installation 
1. Set keyboard layout to SWE
2. Press `AltGr + ~` and then space and you will have two ~ characters.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
