### ISSUE TITLE
IMAP / SMTP network within node app

### ISSUE THREAD

**Issue by thenitai** [Microsoft/WSL#1690]
* A brief description

Got a node app that connects to an IMAP server and for sending emails to a SMTP server. Both connections don't work within WSL.

* Your Windows build number

15031

**Comment by aseering** [comment]
Hi @thenitai -- hm...  WSL itself (as far as I know?) just provides TCP; IMAP and SMTP are built on top of that.

Is it possible that your Windows (or another third-party) firewall is blocking these connections?

**Comment by thenitai** [comment]
No firewall or anything else is interfering. For the record, running the same node app on the Windows side work without an issue.

**Comment by Plazmaz** [comment]
It might be related to the issue I just opened: #1697

**Comment by thenitai** [comment]
I don't get those errors you've report on #1697 but I read that there are some network issues that have yet to be resolved with the WSL

**Comment by sunilmut** [comment]
@thenitai - Thanks for your post. If this is related to #1697, then that is fixed in the insider build 15042. Please try you repro on that build. If the issue still persists, do provide detailed repro steps.

> but I read that there are some network issues that have yet to be resolved with the WSL

There shouldn't be any open network related issues impacting this other than AV, in the latest insider builds. If you feel otherwise, please provide the specific bug/issues, so that we can make progress.

**Comment by therealkenc** [comment]
Duping #1697 for lack of repro. If the problem persists, please reboot the issue following CONTIBUTING.md.
