### ISSUE TITLE
Inotify Watches Limit

### ISSUE THREAD

**Issue by UglyDuckling2k** [Microsoft/WSL#1705]
I'm trying to increase the Inotify watches limit. 
I have tried to set the config value fs.inotify.max_user_watches, but it does not seem to have any effect.

```
Edit the file /etc/sysctl.conf and add this line to the end of the file:
fs.inotify.max_user_watches=16384
```

**Comment by benhillis** [comment]
In our current inotify implementation we do not have a limit on the number of inotify watches a user can register.  Are you encountering any problems because of this behavior or just something you noticed?

**Comment by intdel** [comment]
@benhillis It is an issue for some applications. For example, JetBrain's fsnotifier stops working since the file does not exist.

./fsnotifier64 --selftest
fsnotifier[14172]  info: started (self-test mode) (v.20160218.1348)
fsnotifier[14172] debug: inotify fd: 3
fsnotifier[14172] error: can't open /proc/sys/fs/inotify/max_user_watches: No such file or directory
fsnotifier[14172]  info: finished (2)

**Comment by benhillis** [comment]
@intdel - Thanks! I have opened a task to get this implemented.

**Comment by czfhhh** [comment]
@benhillis I have problem which the same as intdel met. How it goes now?

**Comment by benhillis** [comment]
Thanks for the ping, I'll get these procfs files added.

**Comment by therealkenc** [comment]
If I buy pizzas can you get the rest of `/proc` that can be stubbed while you're there?

**Comment by czfhhh** [comment]
@intdel If you just want to use JetBrain's fsnotifier, you can refer https://github.com/int128/idea-fsnotifier-wsl

**Comment by intdel** [comment]
@czfhhh Very cool. Thanks!

**Comment by benhillis** [comment]
This should be fixed in 17093, please let me know if you continue to hit issues.

**Comment by reubenur-rahman** [comment]
> @intdel If you just want to use JetBrain's fsnotifier, you can refer https://github.com/int128/idea-fsnotifier-wsl

Thanks :)
