### ISSUE TITLE
Some deficiencies on user experience.

### ISSUE THREAD

**Issue by cjliux** [Microsoft/WSL#1714]
Currently I am using the linux subsystem on windows 10 pro. I found that the color scheme of the bash is something annoying, because on windows, blue characters are extremely difficult to identify in the command prompt. So every time I call bash in command prompt to browse my files using 'ls', where directories will be listed blue as default, it turns out I can't identify what directories are in the current path. Although I can disable this feature by using 'ls --color=no --classify', I don't like this sort of tricks. Even more than that, blue is used in vim, which make it difficult to edit text in bash. What can I do to change the color scheme?
Another problem is about 'sudo'. It seems that linux subsystem is not completely independent and is affected by the architecture of its host. When using 'sudo', it always prompt 'sudo: unable to resolve host \<your computer name\>', and that'is annoying. Any method that can help is appreciated.

**Comment by aseering** [comment]
Hi @cjliux -- thanks for posting!

Regarding sudo, that issue is discussed (and the fix is explained) on #1204 .

Regarding changing color schemes, that's up to the application.  WSL doesn't provide its own implementation of `ls`.  Instead, it downloads Ubuntu Linux and, by default, runs Ubuntu's native versions of `ls`, `vim`, etc.  So the default color scheme is as provided by Ubuntu Linux.  If you want to customize how a program behaves, you can do so within WSL the same way that you would in regular Linux.  For example:

* `ls`: http://linux-sxs.org/housekeeping/lscolors.html
* `vim`: https://www.linux.com/learn/weekend-project-take-control-vims-color-scheme

**Comment by cjliux** [comment]
That's great! Thanks.

**Comment by cjliux** [comment]
I noticed that bash on ubuntu on windows doesn't support scrolling and thus I can't review my command history or the output of my commands.

**Comment by aseering** [comment]
Hi @cjliux -- if you have a new issue, could you please open a new ticket?

Regarding scrolling, it definitely is supported and it works for me.  Perhaps you have configured your Windows console window to not have any scrollback buffer?  Or perhaps you're using a program such as screen or tmux, that manages scrollback internally so disables the Linux (and, therefore, Windows) scroll bar?

**Comment by cjliux** [comment]
I means, not calling from command prompt but clicking the corresponding entry on the start page. They are different cases. If I call bash in the command prompt, it works, but in the other case, it doesn't.

**Comment by aseering** [comment]
Hm, that's interesting.  Those two cases generally should behave the same.

In both cases, it should be using the same underlying Wiindows command-prompt program.  It's just launching the program in a different way.  I'm not personally an expert in the different configuration options for the console window, but I'd recommend that you look around there.

Also, if you'd like to get more help with this question, please open a new ticket, since it's a new question; the questions that you originally asked in this ticket have, I believe, been resolved?
