### ISSUE TITLE
copy paste from clipboard with multilines is causing errors in Ipython

### ISSUE THREAD

**Issue by jack-guo** [Microsoft/WSL#1717]
When you have code in a notepad, i.e. notepad++ and then copy paste via right click into the shell console with Ipython on, the result are that only the first line of code is properly pasted, while the rest of the code at the beginning of the line are being cut. please see screenshots that i've linked:

to be copied code:
http://imgur.com/a/sdCTk

copied into shell ipython:
http://imgur.com/a/GyagC

it would be nice if the copy-paste works properly. 

Regards,

Jack

p.s.

build:
http://imgur.com/a/GyagC

===============================================================
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
