### ISSUE TITLE
Something modified /etc/hosts and removed the top comment

### ISSUE THREAD

**Issue by DrPizza** [Microsoft/WSL#1722]
The manifestation was that each time I `sudo`, I get a non-fatal error `unable to resolve host AWKAWK`.

I check `/etc/hosts`, and it looks as in this: 
![image](https://cloud.githubusercontent.com/assets/961950/23286615/dffd7bfe-f9ed-11e6-9496-386fa5d51dbf.png)
Source: [Twitter](https://twitter.com/DrPizza/status/834883819593428992/photo/1)

Regeneration of the hosts file was being suppressed. But I don't know why; I never modified the file locally. Maybe a package changed it?

In the end, deleting `/etc/hosts` fixed things.

**Comment by bitcrazed** [comment]
Talking with @DrPizza about this on Twitter:

Cause of this MAY be caused if the user in-place upgrades 14.04 instance to 16.04 after upgrading to Insider build.

In which case, does WSL get notified of upgrade so that we can update the hosts file?

If not, the `/etc/hosts` file likely doesn't have the new comment blob:

    # This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.

And thus, never gets its contents updated in builds >= [14361](https://msdn.microsoft.com/commandline/wsl/release_notes#build-14361)

Interesting one for @sunilmut to investigate!

**Comment by crcrewso** [comment]
@bitcrazed I had this issue on WSL fresh 14.04 installs too. Though I just manually add my hostname at the top of the hostfile after every install. Since my installs require a bit of host file manipulation I didn't think too much about it.

**Comment by bitcrazed** [comment]
Thanks @crcrewso. In recent Insiders builds, and in the Creators Update which will be shipping soon, the Hosts file contains a comment line at the top:

    # This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.

If this line is not present, we don't write your hosts file for you and you're entirely responsible for its contents. If you add this line at the top of your hosts file, we will write your hosts file for you whenever your network connection state changes.

If you do need to manually modify your hosts beyond what WSL normally writes to your hosts file, you may want to file additional bugs here so that we understand your scenario better.

**Comment by DrPizza** [comment]
I think @bitcrazed may be correct about the sequence of events that caused my `hosts` to not be rebuilt with the comment.

**Comment by crcrewso** [comment]
@bitcrazed Well some versions of Torque require the hostfile have a specific order which is different from most distro's defaults. I fault Torque on this and don't see a need to fill this forum with those bugs. As SLURM gains popularity I can drop Torque testing entirely not have to worry.

**Comment by sunilmut** [comment]
@bitcrazed's analysis here is spot on. Unfortunately, for people migrating from `Anniversary Update` to `Creators Update`, this will be a problem i.e. automatic generation of `/etc/hosts` will stop working. Easy workaround is to delete the file, as you have already figured. We will try to cover this in our documentation. Any code change to support this in `Creators Update` seems to be a non-starter.

**Comment by benhillis** [comment]
We have added a wsl.conf option to not overwrite the hosts file.
