### ISSUE TITLE
How to repair failed setup?

### ISSUE THREAD

**Issue by OneOfMany07** [Microsoft/WSL#1750]
I had an issue during the first setup where it got "stuck" during the tarball extraction.  I don't have AVAST installed, but do have BitDefender installed.  Could that be an issue?

Either way, I closed the window after trying to hit enter to see if I'd get a username creation prompt like one thread I'd seen in here suggested.  I saw nothing new, nothing printed...so I closed the terminal.

I have an Ubuntu on Windows shortcut, but when I run it I get a root@<computer_name> prompt.  I assume more setup should have happened because my network doesn't seem to work.  I tried to "apt-get update" and it seemed to be stuck trying to access the network (stays at 0%).  I even tried that in an administrator run terminal.

I also don't know how to uninstall/reinstall or I'd have tried.  Any suggestions or URLs are appreciated.

**Comment by aseering** [comment]
Hi @OneOfMany07 -- well, that sounds frustrating.  Hopefully easy to fix, though:

Regarding BitDefender -- I would recommend that you read the "No Internet with 3rd party AV/Firewall" ticket ( #475 ).  It discusses problems and workarounds for many firewalls, including BitDefender.  Also, make sure you're using the latest version, as many security programs had to be updated when WSL was released in order to recognize and correctly handle Linux binaries and network requests.

My guess is that BitDefender is causing your network issues, and that your network issues are causing problems with the script that installs WSL.

For uninstalling/reinstalling, there is a command line tool for doing that:

https://msdn.microsoft.com/en-us/commandline/wsl/reference

**Comment by benhillis** [comment]
@oneofmany07 - Can you please clarify what build you're running?  If you'd like to create a non-root user you can use the below command:

`lxrun.exe /setdefaultuser`

I'd also recommend deleting your /etc/hosts file so WSL regenerates one.
