### ISSUE TITLE
Being able to edit, create httpdocs files with a windows app

### ISSUE THREAD

**Issue by erdemece** [Microsoft/WSL#1751]
Windows Build Number: 14393.693

My problem probably mentioned million times but just want to describe from an amateur web developer perspective. Also, there might be a solution for this that I don't know. I am not as good as you guys.

I have successfully installed lamp on WSL and works incredibly faster than vagrant which made me invest into this. I have been using vagrant for years just for being able to use my text editor to edit, create delete my php files within windows and keep www folder in my E:/Project/Server/www folder. also I use cmder to ssh into vagrant virtual server and do git commands and others.

What I tried was, I tried to created a virtual host with apache2 on WSL and point www folder to my /mnt/e/Projects/Server/www folder. but when I create a file from windows, linux doesn’t see those files.

How can I do this with WSL? If its not possible can you please implement this feature? thanks.

**Comment by aseering** [comment]
Hi @erdemece -- where (at what path) are these files that you're creating on Windows and not seeing on Linux?  You should be able to create files in C:\ (or D:\, E:\, etc -- any local NTFS-formatted partition) and see them immediately from Linux in /mnt/c, /mnt/d, /mnt/e, etc.

You can't edit files in the Linux paths /etc, /usr, /home, etc from Windows because (among other reasons) they are required to have Linux file permissions and attributes, and most Windows programs don't know how to correctly set Linux file attributes when the file is saved.  The general recommendation is to keep all files that you need to edit frequently, somewhere in C:\ (or E:\, in your case).  You can then symlink to that path from /etc, /home, etc as needed.

**Comment by erdemece** [comment]
@aseering thank you so much for taking time to answer. This is an awesome tool and I really want it to work with it.

To make sure we are on the same page let me explain; I have a folder called projects in my e drive. I also created a folder called Server in my projects folder. In the Server folder I want to create virtual host folder for apache. for example I create folder a called wordpress.dev and point the virtual server to /mnt/e/Projects/Server/wordpress.dev in apache config file for documentroot. I gave the necessary apache permissions but when I create, edit or move files in wordpress.dev linux doesn't see them. 

how can I achive this with symlink ?

Thanks again.

**Comment by erdemece** [comment]
Never mind. It was a bug I guess. I removed WSL and installed again now linux sees the files I created on windows folders.

Thanks.

**Comment by AjayWireTutor** [comment]
Did it delete all your packages when you reinstalled? Does it retain everything?

**Comment by therealkenc** [comment]
From [up above](https://github.com/Microsoft/WSL/issues/1751#issuecomment-284454951):

> I gave the necessary apache permissions but when I create, edit or move files in wordpress.dev linux doesn't see them.

With the [`-o metadata` feature](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) available in the April Update this `apache2` on `/mnt/c` scenario should now be supported. You don't need (and shouldn't use) a symlink unless you have a particular reason to do so. If it doesn't work, that should be investigated further under a different cover following the issue template.
