### ISSUE TITLE
Unable to use extended function keys (F13-F20) from WSL console

### ISSUE THREAD

**Issue by jarst** [Microsoft/WSL#1772]
* A brief description
By default extended function keys (F13-F20) are not accessible.
* Expected results
When user presses Shift+Fn, console should behave like extended Fn key was pressed. 
* Actual results (with terminal output if applicable)
Pressing Shift+Fn is equivalent to pressing bare Fn.
* Your Windows build number
Version 10.0.14393
* Steps / All commands required to reproduce the error from a brand new installation 
Simple way to verify:
1. sudo apt install mc
2. mc
3. F9 -> Options -> Learn keys
4. Try generating key stroke for F13-F20

**Comment by fpqc** [comment]
14393 is old and buggy. New version is releasing in about a month or a month and a half. Can you test on the insider builds?

**Comment by zadjii-msft** [comment]
Sometime after 14393 we added support for ctrl/shift + Fn keys, but I don't think we do anything particularly for keys higher than F12.

**Comment by zadjii-msft** [comment]
I made sure this is on our backlog, MSFT:11645810

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This is in our backlog and we'll consider for a future release.
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
