### ISSUE TITLE
Is there any way to use Sublime Text or any other visual editor "Rails"

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Microsoft/WSL#1791]
I have rails installed on Bash On Windows. Is there any way I can open that directory in windows sublime text editor?

**Comment by aurimus** [comment]
Yes, paste this into address bar `C:\Users\<yourUSERNAME>\AppData\Local\lxss\`

**Comment by AbhimanyuAryan** [comment]
Thanks

**Comment by fpqc** [comment]
DONT DO THIS

**Comment by fpqc** [comment]
@AbhimanyuAryan do not listen to this, it can lead to data loss. Sublime text doesn't understand the special attributes.

**Comment by crcrewso** [comment]
Is there a single windows side editor that successfully handles advanced attributes? I've been using vxsrv and medit until now

**Comment by jackchammons** [comment]
@AbhimanyuAryan We recommend using a directory located under /mnt/. This is where we automatically mount your fixed NTFS drives. Because of the way that WSL works, only changes made here by Windows applications will be immediately viewable by any Linux applications you are running. If you make changes to `C:\Users\<yourUSERNAME>\AppData\Local\lxss\*` using anything else but a WSL terminal you will be susceptible to data loss and syncing issues.

[Check out the blog that one of our developers wrote on the topic.](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/)

**Comment by aurimus** [comment]
@jackchammons is correct, I'm using this approach and it all works together with some git settings for line endings.

**Comment by Coridyn** [comment]
I have got Sublime Text 3 running in WSL by using Xming and the steps shown here: https://gist.github.com/MadLittleMods/0e38f03774fb16e8d698175e505f1f3e#using-sublime-text-through-wsl

Then with this alias (adjust install directory as necessary)

```
alias subl='DISPLAY=:0 ~/downloads/sublime_text_3/sublime_text'
```
it's super easy to edit files on the Linux side of things:

```bash
$ subl ~/.bash_profile

$ subl .
```

I am running Windows 10 (15063.332) and Sublime Text 3 (3126)

**Comment by EvyLynne** [comment]
I needed to get set up to code in Python using WSL and this information was perfect getting Sublime to run from inside the WSL!  Thank you!

**Comment by therealkenc** [comment]
This one was kind of a question which kind of has an answer, even if it isn't an officially supported scenario. Sublime has run since June 2016 #481 ([message](https://github.com/Microsoft/WSL/issues/481#issuecomment-224837581)). Closing out 'cause there isn't much more to discuss specifically about the ask. @EvyLynne happy it is working for you 👍.

**Comment by Spandan-Madan** [comment]
Here's one non ideal solution that I use. Though sublime text surely is awesome, this may be hard to set up. An easier solution is to just use jupyter notebook. From WSL when you launch a jupyter notebook it's going to open up in the browser, where you can edit the file. Not ideal, but at least something :)

**Comment by therealkenc** [comment]
There is also [theia](http://www.theia-ide.org/), [ALM](http://www.alm.tools/), and the like. Totally different ask from the OP though.
