### ISSUE TITLE
Name Resolution with custom Name Resolution Policy

### ISSUE THREAD

**Issue by dnabsuh** [microsoft/WSL#1815]
We have a situation where we need to use a custom name resolution policy to allow us to resolve a customer's internal domain queries.   (Under 'Local Computer Policy/Windows Settings/Name Resolution Policy')

When I run scripts under Bash on Windows, the server names on the customer site are not resolved.  All windows based applications are able to resolve the client names with no problems.  

Is there a way to have Bash use the name resolution policy, or can I have Bash use a custom /etc/resolv.conf to fix this?

**Comment by aseering** [comment]
Hi @dnabsuh -- yes, you can use a custom resolv.conf.  Just replace the existing file with a file that meets your requirements.

**Comment by sunilmut** [comment]
@aseering - Thanks for chiming in.

@dnabsuh - Yes, you can take ownership of `/etc/resolv.conf` (as @aseering also mentions) by removing the below text from the file. In the absence of that text, WSL will not regenerate the file on any updates. If you do so, do also note that any updates to your DNS servers will not get updated automatically by WSL.

`# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line`

Thanks for using WSL. Hope you are enjoying it!

If this satisfies your request, we would like to close the issue out.

**Comment by dnabsuh** [comment]
@sunilmut is it possible to have the BASH shell pick up from the DNS Redirector?   The situation is I have a DNS redirector pointing .internal to  10.1.1.1 DNS Server and .secondary pointing to 11.1.1.1 (example domains/server) this works great on windows and if I go to server.internal, or server.External I get the right ones.  

I should note in Windows 7; we used to use a loopback adapter with the 'Unbound' DNS server service running to do the same thing, which does still work with BASH. 

I may just need to learn more about resolv.conf - my first look at it didn't tell me how to point specific DNS domain server for a domain.

**Comment by sunilmut** [comment]
@dnabsuh - Let me make sure that I understand your question. You want a way for your Windows "Redirector" solution to work  correctly with "WSL Bash". Is that accurate?

> I may just need to learn more about resolv.conf - my first look at it didn't tell me how to point specific DNS domain server for a domain.

Yes, first I think you will have to figure out a way for DNS redirection to work on native Linux. If it is not supported there natively, then it will be difficult (but, not impossible) for us to support it. I am not very familiar with DNS redirection on Linux. I encourage you to learn more about that first.

> I should note in Windows 7; we used to use a loopback adapter with the 'Unbound' DNS server service running to do the same thing, which does still work with BASH.

I am not sure which "BASH" are you referring to here? Cygwin? "WSL" bash or Windows native bash is not supported on anything prior to Windows 10.

**Comment by dnabsuh** [comment]
Sorry for being unclear, I meant that I can still install a loopback adapter on the Windows 10 host, we use IP Address 192.168.90.1 for some random reason.
Once I have that loopback adapter running, I can run the Unbound service on 192.168.90.1 and then point resolv.conf to that.  
This is a work around, I was just hoping for a more 'elegant' solution using the policy.

**Comment by aseering** [comment]
@dnabsuh -- ooh, I've been meaning to build a tool like that; I didn't realize that one already existed.  Thanks for the pointer!

Could you bind Unbound to 127.0.0.1?  Do you need the extra loopback adapter?

@sunilmut -- WSL's support for Ubuntu's DNS implementation is actually relatively incomplete right now.  For starters, unlike Ubuntu, y'all actually try to write a valid `/etc/resolv.conf` :-)

More seriously:  On a stock Ubuntu Desktop system, `/etc/resolv.conf` simply points to localhost (actually `127.0.1.1`).  Network Manager (the graphical-and-sort-of-command-line tool used on Ubuntu for network configuration) starts an instance of `dnsmasq` early during system boot.  That daemon listens on `127.01.1` for DNS queries, and it handles them as required by the user's networking configuration, including any DNS redirection required by VPNs that are configured by Network Manager.  (VPNs can instead use NSS, and I think some do in which case they should work with WSL, but in my experience many don't.)

So, why not just do this in WSL?

* Network Manager is a graphical application.  (It does have a CLI, but it really feels like an afterthought as compared to the GUI.)
* `dnsmasq` is not launched at system boot.

While both of those can be worked around, neither is explicitly supported.  I'm frankly kinda sketched by depending on that much unsupportedness for something as fundamental to a modern environment as DNS resolution...

On the upside, @dnabsuh -- since Ubuntu itself just runs a proxy DNS server on localhost, your doing the same wouldn't be all that much worse than the status quo :-)

**Comment by sunilmut** [comment]
@aseering - Thanks for the write up. Yes, I have been looking at the network-manager service and other DNS issues (coming from VPN, such as #416). For one, the network-manager service is also the blocker for getting other network utilities to work such `nmap`, `traceroute` etc. because it provides some service over `localhost::53`. The network-manager service currently does not start successfully on WSL, as you also point out.
Going back to your bigger question of DNS resolution on WSL, yes, we understand that there are some gaps here and we are looking into it. It is a bit more convoluted that it appears on the surface, because WSL has to deal with network configuration on Windows (which are also altered by VPN solutions) and how to surface that (or bridge that) within WSL. Additionally, WSL users are also requesting support for [tun\tap](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17292841-support-mknod-dev-net-tun-in-wsl) native Linux VPN (such as OpenVPN #963). Any DNS solution that WSL supports should be extendable to that. There are multiple solutions possible here such as allowing Windows and WSL to both have their own network configuration (by also duplicating some information, and keeping them in sync) and/or redirecting all DNS requests from WSL to Windows. We are currently evaluating these approaches. And, listening to everything here as a feedback loop into that.

**Comment by aseering** [comment]
@sunilmut -- thanks for the detailed reply :-)  Sounds like you've already dug pretty deep into this stuff.  I'm glad to hear that you're working on it.

One nit:  I'm pretty sure it's technically not `localhost:53`; it's `127.0.1.1:53`.  (Note `.1.1` rather than `.0.1`.)  Presumably to avoid port conflicts for people who are already running their own local caching nameservers?

Also, another complicating factor is something like mDNS ( #384 ), which both Linux and Windows implement but they may implement differently.  (For example, I have seen Linux configurations that used `.home` rather than `.local` as the default mDNS domain.  I think that's uncommon these days, though.)

I for one would love to see a relatively loose coupling, with a fully-functional Ubuntu DNS stack (NSS + network-manager/dnsmasq) underneath, Windows DNS on top unless overridden in Linux, and integration over some local socket s.t. someone who doesn't want Windows integration can simply go into network-manager and point it at a different default DNS server.  That would handle all of the crazy DNS setups that I've personally encountered.  But that's just me :-)

**Comment by sunilmut** [comment]
> One nit: I'm pretty sure it's technically not localhost:53; it's 127.0.1.1:53. 

Correct, thanks for pointing that out :). It was an oversight from my side.

**Comment by dnabsuh** [comment]
@aseering - Yes I do run unbound on the local host port on the Windows host.  I have been running that on a Windows 7 machine for a while but had also to use the loopback adapter to get a different IP address because the VPN we use doesn't allow pointing back to 127.0.0.1  

Using unbound on 127.0.0.1 works pretty well, as long as I remember to edit /etc/resolv.conf  A few times it has changed on its own even with the comment line removed.

**Comment by krembuk** [comment]
Hi, I have a small issue with resolv.conf: windows seems to put VPN's DNS under the previously used DNS, which make it useless, since the previous DNS is always used. IMO, the logic should be: "if we connect to a VPN, we should prioritize the use of that VPN's DNS"

Can this behaviour be changed? It is a bit annoying to update resolv.conf everytime I reconnect VPN. Removing the first commented line does not work. resolv.conf still gets regenerated after I exit and rerun bash.

**Comment by sunilmut** [comment]
@krembuk - Thanks for your post. 
>if we connect to a VPN, we should prioritize the use of that VPN's DNS

Yes, that would be the right logic. But, often times WSL cannot programmatically determine which DNS entry belongs to the DNS.

> Removing the first commented line does not work. resolv.conf still gets regenerated after I exit and rerun bash.

Yes, we understand that is frustrating. We have a bug open at our end to fix the auto-regeneration.

Genearlly, we are looking for a more complete solution for the VPN. Until then, the manual update of resolv.conf will have to do. Apologies for the inconvenience.
