### ISSUE TITLE
Couldn't read /proc/net/snmp: No such file or directory

### ISSUE THREAD

**Issue by scriptkitz** [Microsoft/WSL#1817]
Couldn't read /proc/net/snmp: No such file or directory

**Comment by benhillis** [comment]
Hi @scriptkitz - thanks for posting.  When filing issues please try to follow our [contribution instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) as it helps us quickly triage issues.  ProcFs and SysFs files are added on as as-needed basis.  Is there a particular application that is failing to work because of missing /proc/net/snmp?

**Comment by therealkenc** [comment]
#1809
