### ISSUE TITLE
Rename the project to WindowsSubsystemforLinux.

### ISSUE THREAD

**Issue by rustyx** [Microsoft/WSL#1819]
Why is this repository called BashOnWindows?
It should be called WindowsSubsystemForLinux or something that resembles WSL more closely.

**Comment by dezza** [comment]
does anything really restrict it at this point to being bash only support?

**Comment by rustyx** [comment]
Well, bash is the only way to "enter" WSL, i.e. you can't execute arbitrary linux ELF programs from cmd (yet). But I feel that should not be a limiting factor, WSL is much more than bash.exe already.

**Comment by mateusmedeiros** [comment]
My two cents is that BashOnWindows really make it sound like a port, when we know it's something much more cool. :grin:

**Comment by dezza** [comment]
Well the whole Ubuntu thing I don't get. It basically has so little to do with ubuntu except userspace binaries and there's no reason why it couldn't run any other distro in its userspace. The wrong consensus that Ubuntu is the only sane Linux and Ubuntu is essentially === Linux in many peoples eyes is just wrong.. But Microsoft really appeal to that kind of people by branding with Ubuntu/Canonical

**Comment by iz0eyj** [comment]
Change the name to whatever you want, but change it! :)
My personal opinion is that you can simply call it WSL, sounds good,

**Comment by mindplay-dk** [comment]
Can anyone explain why it's called "Windows Subsystem for Linux" and not "Linux Subsystem for Windows"?

This is definitely "something for Windows" and not the other way around, isn't it?

I'm sure I'm missing something painfully obvious ;-)

**Comment by aseering** [comment]
Hi @mindplay-dk -- so, here's my understanding:

"Subsystem" in this context is a specific technical term defined in terms of Windows's [NT kernel architecture](https://en.wikipedia.org/wiki/Architecture_of_Windows_NT).  The Windows NT kernel supports (and, historically, has supported) a variety of different types of environments, called "Windows Subsystems".  The most well-known of these are probably the subsystems for running OS/2 binaries and POSIX applications (Windows's no-longer-supported "Services for UNIX" feature).  Though, as I understand it (and someone may correct me), the regular Windows userspace itself is composed of multiple subsystems these days:  Support for 32-bit applications on 64-bit Windows is implemented as a separate subsystem from the subsystem that runs 64-bit applications on 64-bit Windows.

Anyway, you've got all of these subsystems, and this new thing is a new Windows Subsystem for running Linux binaries.  Hence "Windows Subsystem for Linux".

**Comment by iz0eyj** [comment]
Symply it is a Windows Subsystem and not a Linux Subsytem, so Windows Subsystem for... and not Linux Subsystem for...

**Comment by mateusmedeiros** [comment]
@iz0eyj But it might also have been a `Linux Subsystem` because it is a subsystem that emulates the Linux system, and `for Windows` because it was made for Windows, it's on Windows.

So I guess it is both a `Windows Subsystem for Linux` and a `Linux Subsystem for Windows`, it just depends on the way you interpret the separate words and the connection between them.

If it was the second though, I guess it would have been better if it was `Linux Subsystem on Windows`.

**Comment by mindplay-dk** [comment]
> Anyway, you've got all of these subsystems, and this new thing is a new Windows Subsystem for running Linux binaries. Hence "Windows Subsystem for Linux".

@aseering nailed it, thank you :-)

**Comment by jstarks** [comment]
We've finally renamed this repo to WSL.

**Comment by therealkenc** [comment]
> it just depends on the way you interpret the separate words and the connection between them.

The preposition "for" has a specific meaning depending on whether it is followed by a noun or the present participle of a verb. In the two interpretations, WSL is either:

* [A] **W**indows **S**ubsystem [for running] **L**inux [applications]
* [A] **W**indows **S**ystem [for the] **L**inux [Operating System]

Standing alone, "Linux" is unambiguously a noun (second interpretation). There is nothing "for Linux" about "The Windows Subsystem for Linux". Amusingly, the person maintaining the WSL [installation instructions](https://docs.microsoft.com/en-us/windows/wsl/install-win10) probably studied English at some point and couldn't help themselves.
```
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta property="og:title" content="Install the Linux Subsystem on Windows 10" />
	<meta property="og:image" content="https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/images/microsoft-header.png" />

	<meta name="twitter:card" content="summary" />
	<meta name="twitter:site" content="@docsmsft" />
	<meta name="twitter:title" content="Install the Linux Subsystem on Windows 10" />
```

[I maintain this post meets contributing guidelines because it is technical. 😜]
