### ISSUE TITLE
Bash user file system and user integration is poor.

### ISSUE THREAD

**Issue by kraythen** [Microsoft/WSL#1841]
Although I am new to this windows subsystem it has some potential. To be clear I have never understood why windows doesn't rewrite their OS to be a UNIX variant with their own stuff on top of it and I think it would be amazing if they did so. They certainly have the manpower and talent and perhaps this project will allow me to use windows for professional development again!

Anyway to the issue, the fact that there is a separate user makes it difficult to navigate and understand the two systems. The two users don't have integrated permissions or even profiles. The paths are not integrated and That makes it confusing to know where you are. 

Suggestions: 

in the bash subsystem the home directory should be a symlink to the user's windows home directory so they don't have to maintain two home systems. Also the root of the lxss file system should not reside under AppData (which is a directory hidden by most MS tools, but rather at the root of the main drive (i.e. c:\lxss). This would make the subsystem significantly easier to relate between windows and subsystem files.

**Comment by aseering** [comment]
Hi @kraythen -- thanks for bringing this up!

I believe the gist of your first suggestion, having Linux and Windows share the same home directory, has been discussed before in this ticket tracker.  Though I'm failing to find a ticket reference; hopefully someone else will come across one.  There are advantages, but there are significant downsides to that approach that are specific to (as is the case with WSL) a system that aims to be 100% binary-compatible with Linux, and that would not apply to SFU-style POSIX compatibility:  This causes dotfiles written by Windows programs (those that write to your home directory rather than AppData, anyway) and dotfiles written by Linux programs to be shared.  Which means for example that your dotfiles cannot contain any absolute paths, because Windows binaries will reject Linux paths as invalid and vice versa.  Also, in many cases (as has been observed on several tickets here by NodeJS developers recently, for example), existing Windows script interpreters require that text files have Windows newlines, whereas the corresponding Linux binaries require Linux newlines.  You can't simply rely on Linux developers to open files in text mode because they may not `open()` files at all:  bash itself, for example, is well-known for `mmap()`ing script files such that you can (for better or for worse) edit the bytes of the file on disk and observe corresponding changes in the script's behavior.

The only generalizable way to make these two environments play nice with each other would be to modify the relevant binaries.  Microsoft (which, by the way, I don't work for; I just use WSL a lot) could of course do that for open-source projects.  But there are a lot of proprietary Linux binaries out there, and supporting them without modification is one of the motivations behind WSL.

Regarding placing the filesystem at `C:\lxss`, I personally really like that idea.  But you've skipped over the hard part :-)  Before the WSL devs could do that, they would need to address the following:

* WSL user accounts are currently per-Windows-user.  If you set file permissions in one Windows user's home directory, those permissions will not be meaningful to WSL in another user's Windows account.  So presumably you would also need tighter integration for user accounts.
* The current lxss directory is deliberately hidden, and is [very explicitly not supposed to be accessed from Windows](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) at all, because it uses NTFS features that many Windows programs don't understand.  As a result, if you attempt to modify stuff in that directory from Windows, more likely than not you will cause the files and directories that you modify from Windows to become unusable from Linux applications.  I think the WSL folks can and should make things much more compatible than they are today.  But at some level, the filesystem abstraction that existing Windows programs expect is different from the filesystem abstraction that existing Linux programs expect.  And the reason that I personally often use Windows with WSL, rather than my Mac, one of my Linux machines, my OpenBSD box, or one of my old SPARCStations, is because I have apps that are specific to Linux and apps that are specific to Windows, and I want to have them interact with each other.

**Comment by charlesmilette** [comment]
http://stackoverflow.com/questions/20797819/command-to-change-the-default-home-directory-of-a-user#26427748

You might want to try this command if you absolutely want to share homes between the two.

**Comment by kraythen** [comment]
Well frankly because of this and other things, the subsystem is just no usable by me at all, I will continue to run Ubuntu in a VM.  I have been programming 33 years and often wondered why windows just doesnt go full bore unix based. No idea but managing multiple home directories, one of which is in an application data directory hidden from use and obscure? I dont know what you guys are targeting here for a release but this isnt useful to me or any other dev i have run it by.
