### ISSUE TITLE
In Windows 10 build 16170 ,bash dosen't setting with Windows locale language

### ISSUE THREAD

**Issue by tony8077616** [microsoft/WSL#1867]
Hello

when i upgrate to 16170 and reinstall the bash(full uninstall then install)

bash doesn't setting with Windows locale(zh_TW),also it have ask this question.

but it still use with english

this problem doesn't have on 15063.14

and I setting lang Manually in bash to let it work

I reference this url:[https://www.shellhacks.com/linux-define-locale-language-settings/](https://www.shellhacks.com/linux-define-locale-language-settings/)

**Comment by aseering** [comment]
Hi @tony8077616 -- thanks for posting!

First, I'm curious where you got a build number 16170.  The latest public build is 15063, and the build numbers don't increase very quickly...  Could you type `ver` at a Windows command prompt and confirm what build number it says you have?

Second -- could you clarify -- are you saying that WSL asks you whether you want to use "zh_TW", and you tell it to use "zh_TW", but it then uses English instead?

I know there has been some discussion about whether WSL should automatically use the Windows locale or not.  The problem is, WSL is just using Ubuntu Linux's translations and its locale support, and in some scenarios Ubuntu's support for other languages is not as complete as Windows's.  So people may prefer WSL to be in some different language than Windows because WSL works better in that language.

**Comment by Sazpaimon** [comment]
@aseering 16170 was released 2 days ago: https://blogs.windows.com/windowsexperience/2017/04/07/announcing-windows-10-insider-preview-build-16170-pc/

**Comment by aseering** [comment]
@Sazpaimon -- ah, sorry, you are correct; I totally missed that!
