### ISSUE TITLE
Temporary file system filled up C drive

### ISSUE THREAD

**Issue by Entroper** [microsoft/WSL#1940]
I'm running with the Creators Update, and I had a Node process hang for a long time.  After killing it, I started getting disk space errors in Windows.  My %appdatalocal%/lxss/temp folder was full of large (> 20 GB) files.

I couldn't really use my computer at this point, so I deleted those files.  And predictably, this broke my WSL installation.  Nearly everything I do in WSL blows up with a "cannot create temp file, no such file or directory" error.  Is there a way to fix the temp folder so I can use WSL again, or do I pretty much need to start from scratch?  And if WSL fills up my C drive again, how can I reclaim the temporary space without breaking it?

**Comment by therealkenc** [comment]
I don't have any answer to your practical question; hope someone on the team does. See #1740 ([message](https://github.com/Microsoft/BashOnWindows/issues/1740#issuecomment-283772947)). But for the sake of someone else hitting this, can you share what Node package (particularly any potentially relevant native modules) you are using? When I hear "20 GB files", this makes me wild guess #1732 ([message](https://github.com/Microsoft/BashOnWindows/issues/1732#issuecomment-282937193)). Not necessarily Flow specifically, but there aren't many use cases for temp files with 20GB of "real" data. Maybe the files are sparse, which take up actual space on WSL but not Real Linux (in which case you'd never notice them in /temp unless you looked). Again, just a wild guess on a lazy Easter Monday though.

**Comment by Entroper** [comment]
Yeah, it was flow.  It sounds like you're right, flow uses sparse files and blows up the WSL filesystem.  Not cool on a 512 GB SSD.

**Comment by therealkenc** [comment]
Might be worth posting the issue over with the Flow guys. They ought to be cleaning up their temp turds, at least in non-abort paths. Ten such files isn't cool on a 512GB SSD, but one or two might be semi-tolerable. Not making any excuses for the lack of WSL sparse file support, mind. Just sayin'.

**Comment by therealkenc** [comment]
@Entroper - Wait... Per your edited second paragraph, I think you might have found a separate bug here; contrast, the lacking sparse file "feature". I believe the "real" sparse files you are looking for used to live in `/run/shm/`. But you won't find them there now, because they got `unlink()`ed right after creation. That directory you cleaned out, `.../lxss/temp`, doesn't have to do with WSL LxFS `/tmp`. [I did a double-take on your 'misspelling' when you posted, but didn't know what to make of it.] @SvenGroot explained in #966 ([message](https://github.com/Microsoft/BashOnWindows/issues/966#issuecomment-289106344)) that WSL implements open fs handles to unlinked files by quote "by renaming the file to a temporary directory". I bet that is `.../lxss/temp`. So it _**isn't**_ Flow failing to cleaning up after itself, as I naïvely went to in my head. It is WSL that is leaving dead soldiers behind. So don't bother the Flow people as I suggested. Their code is fine, and WSL is leaky.

**Comment by Entroper** [comment]
I don't think it was flow failing to clean up after itself or WSL, I think it was because flow had been running for about 3 minutes, and I killed it.  So it couldn't clean up anything.

**Comment by therealkenc** [comment]
That is precisely the leak. When the file handle closed on process death (by normal exit or by being shot in the head), the backing store for that unlinked file (with a refcount of 0) should have been released per *nix semantics.

**Comment by SvenGroot** [comment]
If a file is marked deleted, we do indeed move it to the temp directory, but we also mark it as delete on close. When there are no further references to the file (when you killed Flow), the files should have been deleted. The fact that that didn't happen would indicate a bug somewhere.

**Comment by therealkenc** [comment]
> Yeah, it was flow. It sounds like you're right, flow uses sparse files and blows up the WSL filesystem. Not cool on a 512 GB SSD.

This one was /dupe #1732 but never got marked as such.
