### ISSUE TITLE
apt-get build-dep does not work

### ISSUE THREAD

**Issue by ohhmm** [Microsoft/WSL#1957]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
apt-get build-dep <some package> - it says no source repositories in apt sources-list

* What's wrong / what should be happening instead:
dev packages with libraries needed to build the package should be installed (this is for developers, right?)

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
So, technically this is actually expected Ubuntu behavior.  Some distributions of Ubuntu, including the one that Microsoft is using, ship with source repositories disabled by default so that `apt update` runs (~2x) faster, and uses less disk space.  Many developers just need the `-dev` packages, or would choose to get the source directly from upstream rather than through `apt`.

If you want to use source packages (or any other repositories), you can enable them per the Ubuntu docs:
https://help.ubuntu.com/community/Repositories/CommandLine

That said, these defaults are used by Ubuntu in production server environments.  I believe Ubuntu Desktop has more repositories enabled by default (`universe`, I think?) as well as source packages.  I personally think that it would make a lot of sense for WSL's defaults to mirror Ubuntu Desktop's configuration in this respect.

(Note that I don't work on the WSL team myself.  Hopefully someone who does can comment?)

**Comment by benhillis** [comment]
@aseering - The image that we use comes directly from Canonical and as you've mentioned before it's their server cloud image.  I think there's a fine balance between providing a barebones image that's a smaller download / disk footprint versus an image with a lot of things many users may not need.  I think the current image is a good balance.

**Comment by aseering** [comment]
Hey @benhillis -- thanks; as always, your replies are much appreciated.  I do feel obliged to push back on one corner of this response, though:  I claim that WSL is not, primarily, aiming to be a headless server environment.  Therefore, Canonical's headless server image is probably not strictly optimal :-)  Does WSL really need to spend disk space and download cycles on things like Plymouth graphical boot?  Console fonts (stored in a Linux path that the Windows console doesn't currently use)?  LVM virtual-partition / RAID management?  (As I recall, the latter wasn't bundled with Ubuntu Desktop until relatively recently; just Server.)  And, per above, I can think of things that server admins would not want and developers would want.

Packaging is a big problem and a bigger time-sink; I'm not saying I think you should spend time on it now.  But I would like the plant the seed that y'all do have a different use case so there is room for tuning.

**Comment by benhillis** [comment]
@aseering - your points are valid.  I'll remind you that Microsoft does not own the usermode Linux bits.  We are using the image that Canonical decided to give us.  @dustinkirkland may have more justification on what is included in the tar.gz file they provided us.

**Comment by aseering** [comment]
@benhillis -- be careful, the beauty and the cost of open source is, you don't get to say "I don't own that" :-)

**Comment by iHateInventNames** [comment]
Maybe Canonical can provide a link to Launchpad to repository with the image builder?

**Comment by sunilmut** [comment]
@iHateInventNames - Thanks for your post. Appreciate the feedback. I agree with the general sentiment here that the image should be curated towards its audience and perhaps the current image is not the ideal one (as also pointed out by @aseering). But, you shouldn't be blocked on anything behind this image. I would also like to reflect on @benhillis post above that we partner with Canonical to deliver the experience here and they are responsible for the user image. So, if you have any access to @dustinkirkland, please drop him a note. We also talk to them and when appropriate, we can mention this as well. It's a bit early for that right now :) (as @aseering also notes).

**Comment by iHateInventNames** [comment]
Thank you @sunilmut

**Comment by dustinkirkland** [comment]
The WSL image is the *exact* same Ubuntu server/cloud image (package manifest) as Ubuntu in: AWS, Azure, Google, and elsewhere.  The goal is *consistency* across the entire Ubuntu experience.

As noted above, the source package lists are disabled in order to speed up apt-get updates, and reduce on disk footprint for the vast majority of users.  Devs who want the Ubuntu sources can simply uncomment those lines in /etc/apt/sources.list

**Comment by benhillis** [comment]
@dustinkirkland - [<3](https://www.youtube.com/watch?v=J789GId1kaY)

**Comment by dustinkirkland** [comment]
Van the man!


:-Dustin
@dustinkirkland

**Comment by sunilmut** [comment]
@dustinkirkland - That's reasonable. Thank you for your note.
