### ISSUE TITLE
npm postinstall script error - cannot run in wd

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/WSL#1960]
* Windows 1703 (creators')
* Update BashOnWindows
* Install NVM to ~/.nvm as usual
* Install node 6.10.12 LTS 
* Create this simple package.json
```json
{
  "scripts": {
    "postinstall": "node init"
  }
}
``` 
and this script init.js
```js
console.log("done")
```
* run npm install

* The result is
```bash
npm WARN lifecycle undefined~postinstall: cannot run in wd %s %s (wd=%s) undefined node init /mnt/c/projects/bugTest
```

```bash
npm run init
```

works just fine.

I'm guessing wd = working directory? But why is it failing to run?

OH BTW ```which nvm``` gives no output.

**Comment by SteveALee** [comment]
See original problem https://github.com/alexjoverm/typescript-library-starter/issues/37

**Comment by SteveALee** [comment]
After a little exploration I think this is as npm runs scripts setuid which fails due to the mounted windows fs config.

This works fine
```bash
npm install --unsafe-perm
```
However, this means a standard npm install fails and is a security anti pattern. Any ideas for a fix?

See https://docs.npmjs.com/misc/config#unsafe-perm

**Comment by yorickdowne** [comment]
ThIs isn't just npm. Building on /mnt/c fails for a lot of languages. At least you have a workaround with --unsafe-perm. 
It's been a few months but last I remembered this problem was considered intractible because of the way NTFS permissions work. Some things a *ix file system does just don't translate. Illegal characters in NTFS come to mind.
Excellent blog post on WSL and file systems: https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

Personally, I'm staying within ~, that side steps those issues. Syncs to git just as well as /mnt/c :).

**Comment by yorickdowne** [comment]
Postscriptum: you may want to follow https://github.com/Microsoft/BashOnWindows/issues/1799 and consider using openssh server and sshfs in the interim / as a way to access VolFS from Windows. https://igikorn.com/sshfs-windows-10/

I'd also check user voice to see whether there's a suggestion there for acl to permissions mapping in DrvFS and up vote if there is.

**Comment by tara-raj** [comment]
Please run this on a more recent Insiders Build and reopen if you're still running into this issue
