### ISSUE TITLE
No symlink from python to python3

### ISSUE THREAD

**Issue by derekbekoe** [Microsoft/WSL#1980]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

![screen shot 2017-04-21 at 4 54 34 pm](https://cloud.githubusercontent.com/assets/16448634/25299376/4172a638-26b3-11e7-8645-90e806b688da.png)

After the Creators update, there is no longer a symlink from python to either python2 or python3.

On other Ubuntu 16.04 systems this is the case but not in WSL so user has to run `sudo ln -s /usr/bin/python3 /usr/bin/python` manually.

See https://www.python.org/dev/peps/pep-0394/#recommendation

* What's wrong / what should be happening instead:

Expected `python` to be a symlink to `python3` and it is not so `python` command fils.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by yorickdowne** [comment]
Cannot reproduce here. Was this an in-place upgrade from 14.04? Maybe something went wrong in that process?

Try a remove/replace of Bash on Windows as described here: https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/

`
tbehrens@Meep:~$ which python
/usr/bin/python
tbehrens@Meep:~$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 9 Dec  9  2015 /usr/bin/python -> python2.7
`

**Comment by Boddlnagg** [comment]
I have the same issue here since Creators Update. I did not do an in-place upgrade, but rather
`lxrun /uninstall` followed by `lxrun /install` (Note: No `/uninstall /full`, since I followed some instructions where this was not included, and everything else seems to work.)
```

**Comment by derekbekoe** [comment]
@yorickdowne This was a fresh Windows VM with build 10.0.15063.
Only Python 3 is installed. Python 2 is not available.

<img width="827" alt="screen shot 2017-04-24 at 9 25 45 am" src="https://cloud.githubusercontent.com/assets/16448634/25347517/06133c14-28d0-11e7-89cc-0eab1e2f6a40.png">

**Comment by yorickdowne** [comment]
Interesting. The issue then is that Python 2.7 is missing, and with it the symlink.

What do you think is different from installations where this is happening, and installations where Python 2.7 comes in correctly?

**Comment by derekbekoe** [comment]
Has Python 2 been removed from Bash on Windows after the Creators update?

**Comment by aseering** [comment]
@derekbekoe -- it looks like Canonical has removed Python 2.7 from their [default cloud image](https://cloud-images.ubuntu.com/), which is what WSL uses, as of Ubuntu 16.04.  If you want it, you can get it by doing `sudo apt install python2.7`.

The reason that Python 3 is included by default is not because developers might use it.  It's included because some of Ubuntu's own core utilities require it.  The only included languages are ones that need to be there for the image to work.  (Python 2 was included in Ubuntu 14.04's cloud image, which is what Anniversary used, because some of Ubuntu's core tools still required it.)  I believe the idea is, you start off with a small initial download that's just enough to run `apt` and raw shell scripts; then you use `apt` to install whatever tools and languages you need.

**Comment by kaybee335** [comment]
@aseering - I see the point you are trying to make but I think the missing symlink MUST be created on the base install for those that have no intention of installing legacy python.  If you try 'sudo apt install python3' you get told that there is nothing to do (assuming your system is up to date).  So to actually get a configuration where only python3 is on the system you need to manually create this symlink.  Given the soon to be out of support status of legacy python (https://pythonclock.org/) I don't think that people doing a fresh install should have to know something as arcane as establishing the symlink before they can use python (or more pointedly be encouraged to install versions of python prior to version 3 unless there is a very good reason for it).

I am not going to try uninstalling python3 and re-installing it to see if that establishes the link as that will more than likely bork the subsystem given that so many Ubuntu and other tools rely on it (with my luck it would be apt-get).

I'm good now that I have created the symlink but I do think it should be there by default for the reasons above.

**Comment by kaybee335** [comment]
Just a quick follow-up on this.  The symlink alone will not give a fully usable python3 configuration.  It will be necessary to do 'sudo apt install python3-pip' before you can really get going.

I don't think that pip3 should be installed by default as it brings down another 200MB or so of packages (pretty much the whole g++ toolchain).  Once you realise it is not there, the remedy is pretty straightforward and follows standard python3 install practice for pip3.

**Comment by aseering** [comment]
@kaybee335 -- I see where you're coming from, but I think it's not so clear-cut:

According to Python's [PEP-394](http://legacy.python.org/dev/peps/pep-0394/), `python` should not refer to Python 3.  For now, it should only refer only to Python 2.  According to that PEP, unless I'm mis-reading it?, developers who need Python are expected to always explicitly refer to the Python binary as `python3`, even with new Linux distributions.  (The PEP does acknowledge that some Linux distributions, notably Arch, have nonstandard behavior here.)  This is definitely annoying for Python 3.  But, as discussed on the PEP, there's a feeling that it is necessary.

The [Ubuntu Python 3 Wiki page](https://wiki.ubuntu.com/Python/3) states that `python` will never refer to Python 3 by default as long as PEP-394 stands.

WSL's stated objective is not to provide you with your favorite Python dev environment.  It is to provide you with Ubuntu 16.04.  And it sounds to me like it's doing just that :-)

You can certainly continue to advocate here.  But my personal opinion (not that my personal opinion matters; I'm not a WSL engineer) is that WSL should follow upstream as much as possible; it should not diverge and set a whole new set of standards.  Here are some ways that you could get `python` to refer to Python 3 without forcing WSL to break with upstream:

* Bring up you concerns with the Python community.  Get them to decide that Python 3 is mature enough that they can update PEP-394 to permit having `python` refer to the Python 3 binary.  Then get Ubuntu to update their packages to reflect the new standard.  WSL will then automatically pick up Ubuntu's changes.
* Lobby WSL to add support for Arch Linux.  Arch Linux has chosen to break with PEP-394 and to expose Python 3 as `python`.  WSL initially only supported Ubuntu 16.04, but these days it also officially offers CentOS and a couple flavors of SuSE through the Windows Store.  Arch support would be tricky for technical reasons (because its rolling releases often start depending on brand-new kernel features before WSL has had a chance to implement them), but IMO it's a very reasonable ask.

**Comment by kaybee335** [comment]
@aseering - Nope, I did not realise that what I was suggesting was in violation of a PEP.  Now that I have been made aware of that I completely agree that the symlink should NOT be there. Using python3 works as it should. I am just getting used to working in environments where this mapping is automatically made (for example conda environments).

The good news is that my WSL is python3 only as I desired and functioning well enough that I could install anaconda using the linux install procedure.  Now I can set up python environments with whatever version of python I so desire while leaving the base WSL python at whatever is currently being distributed from the base repositories.

I have what I am looking for so I am a happy camper.  The support for USB-serial that was added as well means that I can do all my micropython development under WSL.  All tested and working, it's pretty amazing how good WSL is now.

**Comment by therealkenc** [comment]
> WSL's stated objective is not to provide any particular Python dev environment. It is to provide Ubuntu 16.04. And it sounds to me like it's doing just that :-)

This one got lost in the noise since last spring I guess. The kernel (WSL or Real Linux) doesn't know python3 from Perl.

**Comment by kaybee335** [comment]
> This one got lost in the noise since last spring I guess. The kernel (WSL or Real Linux) doesn't know python3 from Perl.

Let's not go there... Although I did spend a couple of years programming in APL which made moving to perl seem like nirvana!
