### ISSUE TITLE
 Trailing whitespaces added to text copy-pasted into WSL TTY largely per Window size

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#2006]
I use Win10 home, build 15063.138 and experience a problem related to copying files from Notepad++ to Nano. This seems to me to be associated with WSL in the context of the current Win10 cmd.exe/bash.exe terminal emulators.

### The current situation:

I wrote a `.sh` script in Notepad++ and made sure EOL is Unix (LF) and that all indents are tabulation based. I then pasted this script's content into a `nano script.sh` file in a remote Ubuntu 16.04 environment to which I SSH tunnel with WSL OpenSSH.

The pasted content was corrupted with **Trailing whitespaces** - The number of CR chars generally rise up in **direct correlation** with the TTY window size (see images in advance).

Tabulations contribute to having even more trailing whitespaces as they push text right towards the TTY's edge.

### The desired situation:

Pasting valid Bash scripts from Windows .sh files edited with Notepad++ into Nano in either WSL or WSL-based SSH tunnel, without any problem.

---

### What I tried to solve it:

In nano,  any Green box character is actually a trailing whitespace char (even though if you copy the file back to Notepad++ and doing `View > Show symbol > Show all characters` you will get LF+CR combos. Saving the file in Nano in Nix format (I.e, I made sure DOS format is toggled off), doesn't strip these.

dos2unix also doesn't strip these trailing whitespaces out of the saved Nano file.

### To reproduce in WSL:

1. Make sure to copy a script from Notepad++, which has Unix EOLs (LF), and includes only tabulation indents.
2. Make sure your nano script file ends with `.sh`, so you will have Bash highlighting. If you still don't have it, try to SSH tunnel into a remote Ubuntu server if you have one and create a script file there the same way and then you should surly have this behavior.
3. Either way make sure your Nano window is narrow (about 25-50 percent of the viewport) and that you paste a large portion of text).

### Notes:

1.the problem also happens [in a similar way](https://unix.stackexchange.com/questions/359910/heredocument-error-i-cant-understand-delimited-by-end-of-file/361064?noredirect=1#comment639743_361064) with heredocuments:

![362ec0e2-2954-11e7-8763-3bc340800877](https://cloud.githubusercontent.com/assets/13021900/25554455/8fffb876-2cd6-11e7-828a-c2ad20000d60.PNG)
![a](https://cloud.githubusercontent.com/assets/13021900/25360957/362c3fa2-2954-11e7-836a-7379d8c7fb7f.PNG)

**Comment by zadjii-msft** [comment]
@Benqzq I really haven't had time to investigate this at all yet, and I doubt that I'll have any time before //BUILD to investigate. I can try and get you an answer then. @miniksa may know off the top of his head, but I'm not really sure.

**Comment by fpqc** [comment]
Nano is extremely well known for mangling things because it has word-wrap on by default.

Have you tried pasting it into vim or nano -w script.sh?

**Comment by Benqzq** [comment]
I've yet to be acquainted with Vim but in `nano -w script.sh` isn't different from `nano script.sh` for that matter.

Also, given a similar phenomena happens with heredocuments and given that `cat > script.sh AND_THEN paste AND_THEN CTRL+D AND_THEN source script.sh` **works** for both scripts and heredocuments, I conclude this is a problem in the copy-paste mechanism of Windows10 (it's not necessariliy unique to Windows10, it might be an partiular design from much older versions).

A reinforecment to the claim the problem is Windows based is the fact that putting `unbind ^J main` in the end of `/etc/nanorc` didn't solve this and made my script to be pasted in one long row, see [my report](https://savannah.gnu.org/bugs/index.php?50879) in the Nano bug tracker.

Maybe @aseering could enrich us with his opinion?

**Comment by Benqzq** [comment]
Solved - Put the following code in the very end of /etc/nanorc:

`bind ^J enter main`

[Read more on this in the nano Bug tracker](https://savannah.gnu.org/bugs/index.php?50879).

**Comment by Benqzq** [comment]
I reopen given a similar problem happens with heredocuments (or it doesn't, it's hard to tell - [See answers here](https://unix.stackexchange.com/questions/359910/heredocument-error-i-cant-understand-delimited-by-end-of-file)).

**Comment by zadjii-msft** [comment]
I'll add it to my backlog of things to look at. MSFT:12048470

**Comment by zadjii-msft** [comment]
So after investigating this, this is definitely due to us pasting LF chars in the buffer which nano picks up as `^J` and automatically justifies the line. 

The simplest repro is just:
1. open a nano window
2. Paste a couple lines of text, where one is longer that the width of the buffer.

It only seems as though more whitespace is added on a smaller buffer because statistically more lines get justified on a smaller buffer width.

I hacked together a change that made all CR's or LF's into CR's when pasting in VT Input mode (read:bash.exe), and that did seem to fix this, but I highly doubt that's the right solution. I think there's more going on with the underlying TTY modes that we can't assume this would always work.

**Comment by DeeToTheVee** [comment]
I'm not sure if this is directly correlated with this issue but it looks similar.
An example of this I have is when you maybe cat out a file and want to pull two lines from in the middle into another file using copy & paste.

So in my scenario:
  1. I was ssh'd onto a Linux server using the bash for windows terminal.
  2. I'd cat or vim a file as there are 2-3 lines I need from the centre of the file.
  3. I then highlight and copy the lines I need and then when I paste it into a file (via vim or nano) it sticks it all onto one single line which I am then required to go through separating the lines onto their own lines rather than one massive long line.

This is obviously not expected behaviour and appears to have something to do with the fun that is Windows line endings though I can only speculate this based on what I've seen and how I do not see this behaviour happen on my native Linux system.

**Comment by zadjii-msft** [comment]
Sorry to necro an old thread, but apparently I never looped back on this one. It was evidently fixed at some point in the past, give the code at:

https://github.com/microsoft/terminal/blob/083be43700c01604983a9ff67e9fe6edab8ad0e5/src/interactivity/win32/Clipboard.cpp#L140-L183
