### ISSUE TITLE
posix sys/path returns with ENOMEM instead of ENAMETOOLONG on very long filename

### ISSUE THREAD

**Issue by w-klijn** [microsoft/WSL#2022]
* Windows build number:  Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  Running a c++ program that does a path operation for a way to long filename:

```
#include <sys/stat.h>
#include <string>
#include <iostream>
#include <cerrno>

int main()
{
    std::string way_too_long(1 << 20, 'z');

    struct stat st;
    int r = stat(way_too_long.c_str(), &st);

    std::cout << "error encountered:" << errno << std::endl; // ENOMEM
    std::cout << "error Expected:" << ENAMETOOLONG << std::endl;

    return 0;
}
```
* What's wrong / what should be happening instead:
The posix standard says it should return with ENAMETOOLONG on long file names:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html

* Problem occurs with both the standard g++.4.8.4 and 6.2.0
No issue on CentOS Linux release 7.2.1511 (Core)

**Comment by aseering** [comment]
Thanks @w-kiljn for reporting this!

I have to ask (just out of curiosity) -- do you have a non-test program that actually wants to generate paths of this length?  Or is this just a test case?

**Comment by therealkenc** [comment]
Since we're quibbling about the return value, I might as well quibble about the cause. It's `glibc`, not WSL. [Quoth](https://www.gnu.org/software/libc/manual/html_node/Limits-for-Files.html):
>Macro: int NAME_MAX
The uniform system limit (if any) for the length of a file name component, not including the terminating null character.
>
>Portability Note: On some systems, the GNU C Library defines NAME_MAX, but does not actually enforce this limit.

Technically this is not a WSL kernel thing, or even a Linux Kernel thing. It's a standard library thing (be it `glibc` or `musl` or whatever you are using). The maximum filename length is defined by the _filesystem_ (ext4, xfs, FAT32, UDF, Minix, FAT32, etc), not the kernel ABI contract. 

In fact on On Real Linux™ I am perfectly free to create a FUSE filesystem backed by say an sqlite database, and allow users to create million character filenames. If `glibc` enforced some arbitrary system-wide limit on the maximum number of characters, it would break my filesystem.

**Comment by halfflat** [comment]
Nonetheless, ENOMEM is not an expected failure.

**Comment by therealkenc** [comment]
Sure it is. From man7.org [stat(2)](http://man7.org/linux/man-pages/man2/stat.2.html):
```
       ENOMEM Out of memory (i.e., kernel memory).
```
So you are kind of in the unenviable position of either telling the glibc people their implementation is wrong (and they need to translate `ENOMEM` to something else), or telling Linus his implementation is wrong. Or the [TLDP](http://tldp.org/) people are wrong, although I can probably find the `ENOMEM` return value in the Linux source if I looked hard enough.

To be clear, I think the WSL guys should probably squash this and emulate Ext4 behavior on VolFS to every extent possible. But right now any Linux™ application program that doesn't handle the `ENOMEM` return value case from `stat()` is technically incorrect.

**Comment by w-klijn** [comment]
@aseering 
> I have to ask (just out of curiosity) -- do you have a non-test program that actually wants to generate > paths of this length? Or is this just a test case?

Not really?

I do have a use-case!:
I as a primary windows user want to have green lights in my unit test suite so my fellow Linux team mates stop making fun of me behind my back (I'm looking at you @halfflat) and stop calling it ToyOS™.

**Comment by bcumming** [comment]
@w-klijn, the unit test could be changed to test for `ENOMEM` or `ENAMETOOLONG`, because I think that @therealkenc's point is that either are acceptable.

**Comment by therealkenc** [comment]
Turns out the `ENOMEM` got squashed silently, coincidental the move to 9p circa 18917. That `ENOMEM`, while technically _"not wrong"_, wasn't the _expected_ return code on any Linux filesystem.

![image](https://user-images.githubusercontent.com/7049700/117194661-370afa80-ad99-11eb-8ec6-36ee6b0c55c5.png)
