### ISSUE TITLE
Bold doesn't work in Creator's Update Bash

### ISSUE THREAD

**Issue by agocke** [Microsoft/WSL#2027]
Repro: `echo -e "text \033[1mbold\033[0m text"`

This prints the following for me:

![image](https://cloud.githubusercontent.com/assets/515774/25506272/aa183300-2b5a-11e7-896d-4605911466f2.png)

`bold` should actually be bold, not just another color in the color palette. It also shouldn't change the foreground color.

Microsoft Windows [Version 10.0.15063]

**Comment by sunjoong** [comment]
@agocke - lt looks not bold but __bright__. Effect of code 1 is "Bold or increased intensity -- [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code)".

**Comment by zadjii-msft** [comment]
@agocke that's exactly right. We don't support proper bold at the moment, but the intensity works just fine for now. Like with all feature requests, it's already on the backlog :)

**Comment by agocke** [comment]
@zadjii-msft How do you decide what "intensity" means in this context? It seems to pick a different color from the palette, i.e. I can actually change the color that is printed by bold and it can be completely different from the normal color.

This is important because if I change the color scheme for my 16 foreground colors, what happens to my bold colors? It seems like sometimes nothing may happen, which means the bold colors show up as unreadable in my new color scheme.

**Comment by fpqc** [comment]
@agocke This is pretty standard for terminal emulators.  The 'bright' colors are the second row of 8 colors in programs that have a sane color picking interface =p.

**Comment by agocke** [comment]
Yeah, I think I screwed up the transcription from my .Xresources. Still, bold would be useful.

**Comment by dgilmour77** [comment]
This creates a bit of a trap for unwary users.  I like black text on dark grey background, and when I set it, it looked great.  Until I brought up a man page and it looked garbled and broken because I was unlucky that the bold color automatically chosen was the same as my background color - dark grey.  At a minimum, the logic for choosing a bold color should be based not just on the foreground color but the foreground/background combination.  Yeah, good luck with that ;-)

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#109
