### ISSUE TITLE
Running a powershell script changes the console to a raster font

### ISSUE THREAD

**Issue by agocke** [Microsoft/WSL#2050]
Create a simple powershell script, like the following:

```powershell
echo.ps1
---------
echo "test"
```

and then run from within WSL, `powershell.exe ./echo.ps1`. The script runs successfully, but the font is changed to a raster font.

Microsoft Windows [Version 10.0.15063]

**Comment by sunjoong** [comment]
@agocke - How did you run?
```
SUNJOONG-DESKTOP ~ # cd /mnt/c/Users/sunjoong/Desktop/
SUNJOONG-DESKTOP Desktop # ls
desktop.ini  echo.ps1
SUNJOONG-DESKTOP Desktop # cat echo.ps1
echo "test"
SUNJOONG-DESKTOP Desktop # /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe echo.ps1
echo.ps1 : The term 'echo.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. C
heck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ echo.ps1
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (echo.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

SUNJOONG-DESKTOP Desktop #
```

**Comment by agocke** [comment]
@sunjoong Sorry, typo. See edited (you have to use `./echo.ps1`)

**Comment by sunjoong** [comment]
@agocke - font not changed in my case
```
SUNJOONG-DESKTOP Desktop # /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe ./echo.ps1
test
SUNJOONG-DESKTOP Desktop #
```

**Comment by agocke** [comment]
Ah. It's particular to having opened the console through a shortcut pinned to the taskbar or start menu. Probably a write/permissions issue.

**Comment by sunjoong** [comment]
@agocke - Hmm... that could be. I'm using through bash shortcut in start menu and admin account in windows side and root in linux.

**Comment by agocke** [comment]
@sunjoong Try it from the taskbar.

**Comment by sunjoong** [comment]
@agocke - same as shortcut in start menu.

**Comment by agocke** [comment]
@sunjoong 🤷‍♂️ Sounds like it's on the WSL team to sort out :)

**Comment by sunjoong** [comment]
@agocke - Haha, no. If so am I, I should test with standard user account and normal linux account too. But, I'm doing something with this admin and root now.

**Comment by crashtua** [comment]
This affects me as well.

**Comment by jay-tuckey** [comment]
This seems to be specifically when you try to pipe the output of the powershell command. For me:
`~> powershell.exe -command 'write-host hi'` - This doesn't change the font
`~> powershell.exe -command 'write-host hi' | echo` - This will change the font to a raster font. It also throws an error:
```
~> powershell.exe -command 'write-host hi' | echo

write-host : The specified network name is no longer available.
At line:1 char:1
+ write-host hi
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Host], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.WriteHostCommand
```

**Comment by therealkenc** [comment]
Wasn't able to reproduce the 'raster font' behavior, which is kind of were this one has sat since May 2017. Maybe post a screencap just so there is clarity on what you are seeing. Also might be worth trying against [wsltty](https://github.com/mintty/wsltty) or [ttyd](https://github.com/tsl0922/ttyd) (or whatev) just to get a baseline versus the [Windows Console](https://github.com/microsoft/console).

As for the error, `/bin/echo` (or equivalent shell builtin) doesn't read from standard input so I can see how that might not work. Erroring out like that seems suboptimal though. Probably the input should be eaten silently, but oddly enough I've never even thought too hard about what consumes the characters if you do say a `/bin/echo hello | /bin/echo goodbye` in Linux. If you feel strongly about it spawn a new issue since this one is about the raster problem (such that it is).

**Comment by jay-tuckey** [comment]
Whoops, sorry @therealkenc , my mistake using echo instead of cat.

Here's some better detail:
*Windows Build*
```
PS C:\> Get-ComputerInfo -Property WindowsBuildLabEx

WindowsBuildLabEx
-----------------
17763.1.amd64fre.rs5_release.180914-1434
```
*Steps to reproduce error*
* Run ubuntu shell from start menu
* Settings before:
![image](https://user-images.githubusercontent.com/1253791/52244787-a11c6700-2926-11e9-9e92-5027724f4947.png)
* Execute `powershell.exe -command 'Write-output hi'` - no change to fonts etc.
```
jtuckey@jay-x1-carbon:~$ powershell.exe -command 'Write-output hi'
hi
```
* Execute `powershell.exe -command 'Write-output hi' | cat` - no error (now that I'm using `cat` 🙃), but fonts change to raster and console resizes. Settings after:
![image](https://user-images.githubusercontent.com/1253791/52244927-256eea00-2927-11e9-8a40-0bff531a1b22.png)

I'll give it a try now in mintty, and see if it works.

**Comment by therealkenc** [comment]
Okay got it. The variable between me (and others for two years) and you is that you started off on "Consolas". I started with "Luciida Console". I was able to reproduce starting with Consolas (whee). I'm on 18329, but the version isn't going to matter. Clearly the behavior has existed since the beginning of time.

_Whatever_ is causing the font setting change, this is squarely Windows Console territory. Re-file [over there](https://github.com/microsoft/console/issues) and cite this issue. It is _possible_ there is some cross-border problem and [interop](https://docs.microsoft.com/en-us/windows/wsl/interop) is pushing some weird data we can't see. But it works okay with `wsltty` (Consolas or otherwise), and WSL proper doesn't have any direct (or at least intended) way to cause the font to reset like that. Even if interop was subtly broken the terminal ought not do that. Bonne chance, and thank you for the persistence. This would have sat another two years without your repro.
