### ISSUE TITLE
Apache + wsgi results in maxed-out CPU cores

### ISSUE THREAD

**Issue by cricalix** [Microsoft/WSL#2055]
* Windows Build: 10.0.16184.1001
* Insider Preview Build: 16184.rs_prerelease.170424-2211

Core issue: Apache hogs 4 out of 4 CPU cores when trying to load a WSGI-backed Apache2 installation. Hogging occurs in both the www-data owned process, and the _graphite owned WSGI processes.

![2017-05-03 21_06_03-dhill bluefin_ _etc_carbon](https://cloud.githubusercontent.com/assets/1478917/25679210/617e695e-3044-11e7-9c11-a51c74589f1a.png)

I'm using the guide on Digital Ocean (https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server) as a rough guide to running some simple monitoring of my network connection from WSL.

The storage schema for graphite (for the two metrics I want to collect) is 1s:1d, 15s:7d. Shouldn't be too taxing.

After doing all of the installation steps in the guide, I did some quick data pushing into the service - a few hundred data points. Specifically, I'm using the pyping library to get some ping times, pushing one per second into the carbon service. However, once I hit this issue, I stopped pushing data so as to eliminate a contender for CPU time.

On a cold restart of Apache2, everything is fine. CPU usage for Apache2 is 0, or near enough. When I load http://localhost/ from the Windows host (Firefox), the www-data owned process spikes first on CPU usage, bouncing between about 130% and 200%. The _graphite owned processes then start to pick up, and will bounce between 30% and 100%, but generally sit at 50% each.

Closing the tab and re-opening it will cause more WSGI processes to spawn. There's nothing in any error logs that I can find.

Closing the tab and hoping the problem goes away doesn't work either - the processes in WSL are spinning around doing something, but whatever that something it, it doesn't rely on a listener at the other end of the HTTP request.

What's very strange here is that top reckons the www-data process is consuming 150% of available cores, but is in a sleeping state.

strace -fF -p <that www-data process> shows a lot of EAGAIN lines for fd's 13 and 15.  These are listed as unknown in /proc/56/fd.

```
strace: Process 56 attached with 27 threads
[pid    60] read(13,  <unfinished ...>
[pid    61] read(15,  <unfinished ...>
[pid    60] <... read resumed> 0x7f82fc1d0048, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid    61] <... read resumed> 0x7f82fc140048, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid    60] poll([{fd=13, events=POLLIN}], 1, 300000 <unfinished ...>
[pid    61] poll([{fd=15, events=POLLIN}], 1, 300000 <unfinished ...>
[pid    60] <... poll resumed> )        = 1 ([{fd=13, revents=POLLIN}])
[pid    60] read(13,  <unfinished ...>
[pid    61] <... poll resumed> )        = 1 ([{fd=15, revents=POLLIN}])
[pid    60] <... read resumed> 0x7f82fc1d0048, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid    61] read(15,  <unfinished ...>
[pid    60] poll([{fd=13, events=POLLIN}], 1, 300000 <unfinished ...>
[pid    61] <... read resumed> 0x7f82fc140048, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid    60] <... poll resumed> )        = 1 ([{fd=13, revents=POLLIN}])
[pid    61] poll([{fd=15, events=POLLIN}], 1, 300000 <unfinished ...>
[pid    60] read(13,  <unfinished ...>
```

The Windows host is definitely feeling the CPU pinch too - this isn't faked by WSL from what I can see.
![image](https://cloud.githubusercontent.com/assets/1478917/25679602/c82ab9e0-3045-11e7-9dec-2274f2a89276.png)

Disabling the apache2-graphite vhost, and re-enabling the default results in no CPU issues at all, so this appears to be something about the WSGI layer + graphite.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Would it be possible for you to take a sample profile trace of the scenario so we can take a closer look?

1.) Download and install the SDK form https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk
2.) Run this command from an admin command prompt to start the trace:
xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
3.) Run the scenario and wait 1-2 minutes
4.) Run this in an admin command prompt to stop the trace:
xperf.exe -d profile.etl
5.) Email profile.etl to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for stehuf and russalex.

**Comment by cricalix** [comment]
Sent.

**Comment by stehufntdev** [comment]
Thanks for sending over the xperf trace, really appreciate the help.  As you suspected, the application is calling poll and read like a banshee likely due to WSL reporting back incorrect state to poll.  From the strace, can you tell what type of file descriptors 13 and 15 are?  I saw above you mentioned proc lists them as unknown, and I didn't see a link to the strace.  From the xperf trace it looks like they might be sockets but the hit count is low for those stacks.

**Comment by cricalix** [comment]
Let me see what I can get strace/gdb/something to cough up about what those fds were pointing to.

**Comment by cricalix** [comment]
```
apache2  72 www-data   12u     sock    0,0                     231 can't identify protocol
apache2  72 www-data   13u     sock    0,0                     232 can't identify protocol
apache2  72 www-data   14u     sock    0,0                     239 can't identify protocol
apache2  72 www-data   15u     sock    0,0                     240 can't identify protocol
```
I suspect these might be sockets to the WSGI processes (output is from lsof). The implication from a bit of searching is that this means the sockets are half-closed (or half-open).

A bit more work with strace has got me this:

```
lstat("/usr/share/graphite-web/graphite.wsgi", {st_mode=S_IFREG|0644, st_size=609, ...}) = 0
gettimeofday({1493922343, 592617}, NULL) = 0
gettimeofday({1493922343, 592790}, NULL) = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 19
fcntl(19, F_GETFL)                      = 0x80002 (flags O_RDWR|O_CLOEXEC)
fcntl(19, F_SETFL, O_RDWR|O_NONBLOCK|O_CLOEXEC) = 0
connect(19, {sa_family=AF_LOCAL, sun_path="/var/run/apache2/wsgi.1200.0.1.sock"}, 38) = 0
write(19, "\21\6\0\0\0\0\0\0^\0\0\0\0\0\0\0GATEWAY_INTERFAC"..., 1561) = 1561
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c44a40000
read(19, 0x7f4c44a40048, 8000)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=19, events=POLLIN}], 1, 300000) = 1 ([{fd=19, revents=POLLIN}])
read(19, "Status: 200 Continue\r\n\r\n", 8000) = 24
shutdown(19, SHUT_WR)                   = 0
poll([{fd=19, events=POLLIN}], 1, 300000) = 1 ([{fd=19, revents=POLLIN}])
read(19, "Status: 200 OK\r\nVary: Cookie, Ac"..., 8000) = 1761
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c44a30000
read(19, 0x7f4c44a30048, 8000)          = -1 EAGAIN (Resource temporarily unavailable)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c44a20000
writev(12, [{"HTTP/1.1 200 OK\r\nDate: Thu, 04 M"..., 260}, {"\37\213\10\0(r\vY\2\377\255Wms\3328\20\376\356_\261\365
\315\25\247\0076\311\265I\216@"..., 1626}], 2) = 1886
read(19, 0x7f4c44a40048, 8000)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=19, events=POLLIN}], 1, 300000) = 1 ([{fd=19, revents=POLLIN}])
```

**Comment by stehufntdev** [comment]
Thanks for digging further, adding @sunilmut to get his opinion here.  From the strace above it looks like there's an issue with the epoll state for unix sockets not being updated correctly.

**Comment by dnebdal** [comment]
Since it's been about a year, I'd just like to add that this is still a problem (on windows 10.0.16299.431).

**Comment by DarthSpock** [comment]
@dnebdal Fixes for WSL aren't released via Windows Updates (unless related to BSODs or other heavy impacters). Upgrade to build 17134, the latest stable and see if your use case works now. There were changes with `epoll` that may light your scenario up. If not, an strace will be helpful.

**Comment by tst-rwildes** [comment]
I have build 17134 and this issue is still happening for too.  I have an strace but it just repeats the same lines over and over:
strace: Process 6098 attached with 258 threads
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6152] poll([{fd=10, events=POLLIN}], 1, 300000) = 1 ([{fd=10, revents=POLLIN}])
[pid  6152] read(10, 0x7f4fac004928, 8000) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by tst-rwildes** [comment]
@Brian-Perkins That might be it.  One thing I've observed is that if I stop the Apache server the client becomes unlocked and gets all of its results as expected.  This implies some kind of issue with detecting things are complete and lines up with the issue outlined in #2822.

**Comment by tst-rwildes** [comment]
@Brian-Perkins thanks for the tip!  I updated Windows to the latest insider version build 17760.1 and this issue no longer happens.
