### ISSUE TITLE
0x80070057 when calling bash -c from java (64bit).

### ISSUE THREAD

**Issue by andradebruno** [microsoft/WSL#2062]
When opening a bash process using java's  ProcessBuilder builder1 = new ProcessBuilder("bash.exe", "-c", "fastqc" ); I receive the error 0x80070057. This error doesn't happen in any other context.

**Comment by dbondarchuk** [comment]
+1 
I also have such problem. Any thoughts about this issue?

**Comment by darkverbito** [comment]
+1 invoking from bash over OpenSSH:

bobby {~/code/ssh} ➩ ssh -i sshkey bobby@40.116.167.230 "bash -c 'eval echo hi mom'"
Error: 0x80070057

**Comment by gravcat** [comment]
+1 also experiencing this when eval-ing into bash. Does not happen if bash is used interactively, or in any other context as @andradebruno suggested.

**Comment by therealkenc** [comment]
The OP doesn't have a repro, but taking the server to be `OpenSSH_for_Windows_8.1p1` that ships with windows, seems to take. 

![image](https://user-images.githubusercontent.com/7049700/92220852-6dcaf280-ee51-11ea-9de6-f050c07da5d4.png)

Call it as of 20H1 aka 19041, but there has been a lot of water under the bridge since 2017.

/fixed
