### ISSUE TITLE
as in bash,the shift+insert is does't work

### ISSUE THREAD

**Issue by zuohl** [Microsoft/WSL#2104]
* Your Windows build number: 150063
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots) when i update to 1703

**Comment by sunjoong** [comment]
@zuohl - `shift+insert` like mintty of cygwin or msys2? I think you want https://github.com/goreliu/wsl-terminal  like #2101.

**Comment by zuohl** [comment]
@sunjoong no,in cmd ,i can use shift+insert to paste ,but in bash it does't work

**Comment by sunjoong** [comment]
@zuohl - It looks like `shift+insert` does not work as paste key now ( and before ... #235 ). It could be better to use mintty, i.e., wsl-terminal or wsltty, if you want it.

**Comment by zadjii-msft** [comment]
@zuohl I believe this is technically "working as expected" - `bash.exe` sets the console to "Virtual Terminal Input Mode", where certain keystrokes, such as the arrow keys, the numpad and "Insert", etc, are translated into control sequences to be consumed by console applications. We do this instead of translating the keystrokes into shortcuts. This is also why Ctrl+V doesn't work to paste in bash either.

I believe this is originally tracked by #235.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#112
