### ISSUE TITLE
Use of the WSL as a docker backend? 

### ISSUE THREAD

**Issue by brad-x** [Microsoft/WSL#2114]
The Fall Creator's Update will allow a user to run multiple distinct Linux environments (Ubuntu, SUSE, Fedora) in separate filesystem roots and namespaces, which sounds eerily close to a containerized environment. 

With some effort, could the WSL not be used as a docker backend - docker could pull layers, deploy them to an lxss rootfs, and run the container as a WSL environment. 

The tricky bits would be docker's filesystem layering and its conception of networking. 

But this does look like a tantalizing "shoot for the moon" prospect. Even if it did have caveats, it feels like it could be useful.

**Comment by stehufntdev** [comment]
Requests for getting docker running have come up previously, check out the following posts for more details:

#85 
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker

Please give us feedback on the user voice so we can prioritize.

**Comment by brad-x** [comment]
Thanks for the links! This one differs - it suggests using WSL as a way to run Linux containers in Windows directly - the lxss rootfs generated from the layers pulled from docker hub, etc.

**Comment by stehufntdev** [comment]
Thanks for the clarification!  Yes, we've had various discussions on the different container type scenarios that could be enabled using the core WSL technology.  Marking this as a discussion for now, but feel free to open up a new user voice for tracking so we can prioritize that scenario appropriately.

**Comment by comodoro** [comment]
As you currently cannot run Docker on Windows without breaking other virtualization stuff, this would be a very useful feature

**Comment by matevarga** [comment]
@comodoro you can run Docker on Windows without breaking virtualization. What you probably mean is that Hyper-V cannot run together with e.g. Virtualbox -- this is expected because VT-X is not supposed to be used by multiple hypervisors at the same time. The solution is to use H-V for your other virtualization needs. (I know that H-V doesn't have accelerated graphics under Linux, that's a difficulty.)

**Comment by comodoro** [comment]
@matevarga Sorry, I did not include "for all practical purposes" because I thought it was implied. Even if Hyper-V had good support for all my OSes (I keep hearing the opposite about e.g. Linux, not just about graphics) I am not going to just throw away and replace all my virtual machines.

>

**Comment by yself** [comment]
Instead of relying on WSL isolation alone, it might be possible to install WSL into Windows Server Core docker image, and use WSL there as a target for the docker image. This would solve the networking and possibly other issues instead of relying on WSL isolation alone. 

Howewer my initial attemps just to install WSL into Windows Server Core docker image have been unsuccessful.

(Before I found this thread I have posted a topic at https://forums.docker.com/t/wsl-aware-docker-engine/40614 )

**Comment by shalupov** [comment]
@stehufntdev for some reason uservoice issue is now closed:
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker

**Comment by therealkenc** [comment]
> for some reason

That [cited](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker) User Voice above used to be "SORRY, NO PLANS!" with the comment (Oct 2016) "No plans at this time to support Docker engine atop WSL" before it got reinterpreted to mean the client.

Someone will suggest opening a new User Voice for Docker Engine under WSL. Cost nothing to post it, and it would give people a place to vent their me2s (for those inclined to engage in such activity). But bear in mind a new User Voice like that would just be duplicative of a bunch of already well documented surface WSL is missing (cgroups, much networking stuff, "make `systemd` work", etc). There is also a pretty fair question regarding "use case" since Windows Docker already gets you there equivalently. The whole point of a container is the _host_ doesn't matter.  YRMV.

**Comment by comodoro** [comment]
> Windows Docker already gets you there equivalently

So they replaced the Hyper-V technology? I have not heard about that. Or do you just mean people without virtual machines? Note that Hyper-V must be disabled AND system restarted in order to use other virtual machine solutions.

**Comment by therealkenc** [comment]
> Or do you just mean people without virtual machines?

What _mean_ is: (a) the old User Voice ticket was previously shuttered as "no plans" and then apparently interpreted to mean the client (b) you can always open a new User Voice if you feel inclined (c) docker is available in windows per the [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq) (you don't have to like it; which I can understand), and (d) the results of opening a new User Voice may vary. 

I don't work for MSFT. Who knows maybe you'll get lucky, the the WSL syscall surface is improving with every release.

> Note that Hyper-V must be disabled AND system restarted in order to use other virtual machine solutions.

+1 pro-tip.

**Comment by DrYak** [comment]
Regarding the layering :

 - older versions of Windows used to have a trick called "Volume Shadow Copy" that could keep older state of the file (e.g.: for backup)
 - Windows 10 introduced to "File History" as a different available strategy to keep older versions.

[source](https://en.wikipedia.org/wiki/Shadow_Copy)

I don't have much experience in Windows (mostly work with Linux as my daily driver), but perhaps a seasoned Windows dev could come up with a way to abuse the above "previous version" features to provide a poorman's layering ?

This could at least provide a way to run an image and a single container of it.
(But won't necessary work to deploy tons of containers : my limited googling of the subject yields that those "previous version" feature are read-only, you can't have multiple forking history/dependencies like on a real Docker on Linux running AUFS / BTRFS / etc.)
(At least, it could be acceptable enough to do a quick one-shot test of a single container:
untar image in LXSS rootfs, run container as a WSL session, then use "previous version" to roll back the rootfs to untared state / reset changes done by container).

**Comment by therealkenc** [comment]
Ran course. Landing zone for docker daemon ended up #2291.
