### ISSUE TITLE
Garbled interface in alsamixer.

### ISSUE THREAD

**Issue by Vaporeon** [Microsoft/WSL#2136]
I run Windows inside a virtual machine with KVM and PCI passthrough.
In order to change the volume for the host I ssh back into it and change the Line volume with `alsamixer`

Although the program works the text interface gets messed up.
![alsamixer](https://cloud.githubusercontent.com/assets/12814075/26283412/5750f552-3e6b-11e7-8b1e-dc045dc21078.PNG)

To reproduce ssh into any machine configured to use ALSA audio and run `alsamixer`.

Windows Version:
Microsoft Windows [Version 10.0.15063]

**Comment by zadjii-msft** [comment]
@Vaporeon What font are you using?

**Comment by Vaporeon** [comment]
The default which is Consolas 16 I believe. I am also using 150% DPI scaling.

**Comment by Vaporeon** [comment]
Changing the font does indeed fix it. It's too bad as Consolas is my favorite font among the stock ones and adding custom fonts to the Windows Console is not exactly fun. I tried TTF Terminus but it wouldn't take.

**Comment by zadjii-msft** [comment]
Uhg. That's unfortunate, Consolas is the font that usually always works. I'll take a closer work.

Most monospace fonts work automatically now, no need for dirty registry hacks like in the past. Just install the fonts on your system and go

**Comment by zadjii-msft** [comment]
I've been having some troubles getting this reproduced locally. @Vaporeon Could you try copying and pasting the "garbled" characters here, or in a txt file or something? 

If I had to guess, I'd say this is very likely going to be fixed by a change miniksa put in around the same time I fixed #1879. We're cropping certain characters a little differently now, so that graphical issues should be harder to come by.

I believe those characters are fixed now, so I'm going to remove the bug label from this.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#101
