### ISSUE TITLE
Unnecessary recompilation when building julia

### ISSUE THREAD

**Issue by mikewl** [microsoft/WSL#2162]
* Your Windows build number:  Version 10.0.16199.1000]

* What you're doing and what's happening:  Trying to build Julia in Bash on Windows

* What's wrong / what should be happening instead: gmp, mpfr and patchelf are requiring dependendices which should not be required.

Currently when building Julia in wsl the above mentioned dependencies seem to want to recompile things that have been provided already. It was mentioned by @vtjnash that this may be a filesystem bug relating to timestamps.

**Comment by therealkenc** [comment]
Are you doing the build in DrvFS (`/mnt/c/Users/you`) or in VolFS (`/home/you`)? Could be #1939.

**Comment by Mikewl** [comment]
probably a dupe of #1939

**Comment by tkelman** [comment]
definitely a duplicate of the originally reported issue in https://github.com/Microsoft/BashOnWindows/issues/544, if things work in /home/

**Comment by tkelman** [comment]
has more in common with https://github.com/Microsoft/BashOnWindows/issues/2025 since it's`tar` that Julia's build system is relying on to behave like unix with respect to time stamps (or rather we're extracting and building a number of autotools based projects, all of which are going to rely on time stamps), more than `cp`. but the file system deficiency is the root cause.
