### ISSUE TITLE
Feature: /etc/windows-release

### ISSUE THREAD

**Issue by mcandre** [Microsoft/WSL#2299]
As an aid to scripts attempting to determine the nature of the runtime environment with `cat /etc/*release*`, could bash on Ubuntu on Windows include a `/etc/windows-release` or similar file?

**Comment by sunjoong** [comment]
@mcandre - I have never heard that file yet.

**Comment by sunilmut** [comment]
@mcandre - Thanks for the suggestion. Interesting idea, but can also feels like a dangerous proposition for compatibility. We don't want to encourage any packages taking a dependency on this and introducing WSL specific behavior, that can also hide bugs in WSL.

**Comment by therealkenc** [comment]
It was brought up last year that it should be in `/proc/version`.  `Linux version 4.4.0-10.0.16237-Microsoft`. The version on my Android phone is for example `3.10.61-10942903`. Too lazy to dig up the issue#....

Sunil, people are going to take WSL dependencies in their software. Because there are WSL dependencies. Take for example this patch to Meteor [here](https://github.com/meteor/meteor/pull/8500/commits/d9c3f80dbf5f96566c5e61d04704e181c0c2cdac), which works around #1529 (an issue that did not even rate a "that's going to be really hard to fix" response from anyone). So people ~~hide~~ work around the bugs.

Anyway, from a `bash` script in WSL:
```
ken@HEADCRASH:~$ systeminfo.exe | sed -n 4p | awk '{print $3}'
10.0.16237
```

**Comment by benhillis** [comment]
I agree with @therealkenc.  Running systeminfo.exe or ver.exe via interop is probably the right way to go.

**Comment by Herst** [comment]
Another example of a WSL-specific fix: https://github.com/eventlet/eventlet/commit/09e166bfbd6ba6f52477a7ae1c421dcabd1f004c

On a side note, maybe they should be collected at some location for future in order to inform those developers when WSL oddities get fixed (e.g. in order to prevent workarounds causing problems once WSL follows the behavior of an original Linux™, we've been there with IE).

**Comment by therealkenc** [comment]
Even more amusing is [wsl-glibc](https://aur.archlinux.org/packages/glibc-wsl/), which works around #1878 by rolling back [this commit](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=4b4d4056bb154603f36c6f8845757c1012758158;hp=8d3bd947483f50b57aee7c35c07dc1927d6e8a27). That is, if one is willing to put "Cygwin for WSL" on the table, you can fix all kinds of stuff 😏.

**Comment by SRGOM** [comment]
`/proc/sys/kernel/osrelease` has Microsoft in it (since you only want the "nature" of the runtime env).

**Comment by zszszsz** [comment]
or otherwise a `uname -r` will do it.

**Comment by benhillis** [comment]
The Windows version is now part of /proc/version.
