### ISSUE TITLE
linux-headers-4.4.0-43-Microsoft for Nvidia Driver

### ISSUE THREAD

**Issue by andys0975** [Microsoft/WSL#2363]
As the screenshot below :
![image](https://user-images.githubusercontent.com/21152737/28501225-f75fcef4-7009-11e7-8f50-d7d21b24a8a6.png)

I tried to install Nvidia driver on my Ubuntu subsystem, however it request me "linux-headers-4.4.0-43-Microsoft" package. 
I use 
$ sudo apt install linux-headers-4.4.0-43-Microsoft
and the result said:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-4.4.0-43-Microsoft
E: Couldn't find any package by glob 'linux-headers-4.4.0-43-Microsoft'
E: Couldn't find any package by regex 'linux-headers-4.4.0-43-Microsoft'
```
So I wonder how I could install this package, or is it any other simple way to install Nvidia Driver?
Thank you!

**Comment by therealkenc** [comment]
> E: Unable to locate package linux-headers-4.4.0-43-Microsoft

Interesting. The package script is picking up `uname -r`. It can't locate the package because that name does not exist.

> or is it any other simple way to install Nvidia Driver?

No. If you are looking for OpenGL there are some instructions for llvmpipe [here](https://github.com/Microsoft/BashOnWindows/issues/648#issuecomment-299702548).

**Comment by chenhao1UMBC** [comment]
The same problem here when I tried the same thing...

**Comment by fpqc** [comment]
Of course you're hitting the same problem.  The graphics driver can't be compiled because there are no kernel headers for WSL's "kernel" (actually a Windows driver), and currently no way to send ioctls to the nvidia device in the first place.  

DKMS is actually interesting, and I hadn't thought about it much, but it could be the case that in the future, maybe DKMS and "kernel headers" could allow for the recompilation of some drivers to work with WSL.  DKMS was actually created in order to solve the problem of the lack of stability of the Linux Kernel ABI for proprietary drivers, and it might be flexible enough to allow Microsoft to provide their own headers for such drivers. 

But anyway, the NVidia drivers simply can't work for your primary graphics device even in theory, since it is controlled directly by the driver loaded by the Windows kernel.  It could be that in the future, you could delegate a secondary graphics card to a full WSL driver.

**Comment by therealkenc** [comment]
> A better way for this to happen is what was discussed elsewhere

That was #882.

**Comment by fpqc** [comment]
Yep!

**Comment by therealkenc** [comment]
Closing this out as by-design (the discussion has run its course). The OP related to NVIDIA drivers is n/a on WSL, because there is no Linux kernel in WSL.

This said, the by-design reality here has one dangling consequence. Doing a `uname` to figure out what kernel header package dependency to grab seems to be a common idiom some aptitude scripts (eg #2649). Those scripts don't "handle" the `-Microsoft` string appended to `/proc/version`, which the authors of those scripts would call a bug in our version string. We call it a feature per #423, and there is no turning back on that now.

It is mostly academic, I think, because I can't think of a case where whatever apt package being installed with such a dependency would have any hope of running on WSL. But **if** such a case exists (?), those scripts would have to be patched upstream to "strip trailing garbage", because the `-Microsoft` string is not going anywhere in the foreseeable future.
