### ISSUE TITLE
Windows `/mnt` files all marked as EXEC despite file ending settings in dircolors

### ISSUE THREAD

**Issue by erichiller** [microsoft/WSL#2421]
When in WSL/Bash and I run `ls` within and Windows `/mnt` all files are marked as EXEC despite file ending settings in dircolors. I know that all files within Windows have the executable permission and that is baked in, but shouldn't a configuration which is specific to a file extension override a configuration for a _general_ classification of `EXEC` in `dircolors` or `ex` in `LS_COLORS`?

My config:
```bash
LS_COLORS="rs=0:mh=00:di=01;36:fi=0:ln=35:pi=35:so=35:bd=35:cd=35:or=35:mi=35:ow=37:ex=34:*.env=32"; echo ${LS_COLORS} | tr \: \\n; ls -la;
rs=0
mh=00
di=01;36
fi=0
ln=35
pi=35
so=35
bd=35
cd=35
or=35
mi=35
ow=37
ex=34
*.env=32
```
![image](https://user-images.githubusercontent.com/5379325/29280416-fe26e246-80cf-11e7-9820-4b79b6917394.png)

Also, leaving `ex` unset just keeps the default settings, continuing to override the file ending specific one.
```bash
LS_COLORS="rs=0:mh=00:di=01;36:fi=0:ln=35:pi=35:so=35:bd=35:cd=35:or=35:mi=35:ow=37:*.env=31"; echo ${LS_COLORS} | tr \: \\n; ls -la;
rs=0
mh=00
di=01;36
fi=0
ln=35
pi=35
so=35
bd=35
cd=35
or=35
mi=35
ow=37
*.env=31
```

Yields:
![image](https://user-images.githubusercontent.com/5379325/29280208-2bd7fd5c-80cf-11e7-9e5e-fcb0f7ef2349.png)

In both of these, I would expect for `vars.env` to be colored differently (Green in the **top** image and **red** in the bottom one) from the other files.

This is on build `14393.1198`

**Comment by therealkenc** [comment]
> In both of these, I would expect for vars.env to be colored differently (Green in the top image and red in the bottom one) from the other files.

Blue on top and green on the bottom is the behaviour on Real Linux™ for a 0777 vars.env with your two configs.

**Comment by erichiller** [comment]
So file extensions will never override the 2 letter 'main' categories?

**Comment by therealkenc** [comment]
@erichiller - I wouldn't know. I just tried your scenario on the Ubuntu VM I had up and it behaves the same as WSL.

@benhillis (apologies for the ping). Something that's been nagging at the back of my head for some time is whether WSL could use the `GENERIC_EXECUTE` bit of [`ACCESS_MASK`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374892%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) on DrvFs to some advantage. The use-case here is literally that people don't like the color of their `ls` output. Literally. That's the problem. So maybe give them `0666` if `GENERIC_EXECUTE` is set and `0777` if is not. Forget the extended attributes in this context. 

Concretely: For `chmod(2)` calls on DrvFs files, if `S_IXUSR` is set, then set the `GENERIC_EXECUTE` bit, and report the mode as `0777`. Mask `S_IXGRP` and `S_IXOTH` entirely. If ``GENERIC_EXECUTE`` is not set, report the mode as `0666`. This is "incorrect" behaviour of course. But then doing a no-op on `chmod()` is not correct behaviour either.

I don't know if doing that would have other unintended consequences that I haven't considered, which is why I've kept the thought to myself. But you'd make a **lot** of people happy with the incremental change. Not me mind you. I just want to underline that when people say "I need the permission bits for development" what they _really mean_ is "I don't like the colors `ls` gives me". Possibly that can be addressed.

**Comment by benhillis** [comment]
@therealkenc - This is probably a better question for @SvenGroot but I think the problem is that virtually all files have the GENERIC_EXECUTE bit set.

**Comment by SvenGroot** [comment]
Drvfs already uses the execute permission to determine whether the execute bit is set in the permission it reports in WSL. The problem is, as @benhillis said, that pretty much all files in Windows have the execute permission.

Allowing chmod usage to remove the execute bit is not easily done. We would have to manipulate the ACL of the file, and it's not straight forward to just remove execute permissions. Which users are we removing it from? Everyone? What if the file has inherited permissions? Permissions on Windows aren't as simple as on Linux, so an approximation is the best we can do.

We do have plans to bring more Linux metadata support to Drvfs, which may at least partially alleviate this issue for some cases.

**Comment by therealkenc** [comment]
@SvenGroot 
> The problem is, as @benhillis said, that pretty much all files in Windows have the execute permission.

Yes that's most unfortunate. Maybe places the idea in the "not worth it" category. The theory here is that libraries like libuv's [`uv_fs_chmod`](http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_chmod) could, I think, follow suit. Meaning Windows VSCode would automatically follow suit. Ditto Cygwin/MSYS2, ie Windows Git. Needless to say, `NOTEPAD.EXE` is a write-off.

> Allowing chmod usage to remove the execute bit is not easily done.

That [I believe](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379588%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).

> Which users are we removing it from? Everyone?

No, the SID of the user running the lx session. If that user doesn't have an entry in the ACL for the file, do nothing. Which is no worse that what `chmod()` on WSL does now.

>  What if the file has inherited permissions?

Then you follow them (I don't think you have a choice, right). If you can't change the bit, do nothing. Just like now.

> We do have plans to bring more Linux metadata support to Drvfs

Awesomeness. But... Anything you do in that area would need the same kind support in libuv, Cygwin, or (for that matter) WRT _anyway_. If you bring more metadata to DrvFs, that work would supersede any improvement done with respect to allowing WSL `chmod()` to flip the `GENERIC_EXECUTE` bit. 

But you can fix the original poster's problem right now (I think?). You tell him to `chmod(1)` the files and his `ls` colors will look fine.

Allowing for the caveat: maybe not worth it, of course. Call it an idle thought.

**Comment by erichiller** [comment]
`chmod` has no effect on windows files though does it? (At least it did not on my machine)

**Comment by therealkenc** [comment]
> chmod has no effect on windows files though does it? (At least it did not on my machine)

Yep.

**Comment by SvenGroot** [comment]
Chmod has one effect: you can use it to toggle the read-only attribute. If you remove all writable bits, the read-only attribute will be turned on; if you add writable bits, it will be turned off. This is the same behavior that CIFS uses with a mounted SMB share on real Linux.

**Comment by matthewsimo** [comment]
My system sees all files as `EXEC`, and directories as either `STICKY_OTHER_WRITABLE`, `OTHER_WRITABLE`. It appears orphan symlinks are working too but I haven't had a chance to verify. For anyone else wrestling with getting a decently readable terminal that should get you limping along at least. 

The following settings get me 
![2017-11-30](https://user-images.githubusercontent.com/207644/33451182-d5238dd2-d5d3-11e7-96b8-252bb93d2eef.png)

```
STICKY_OTHER_WRITABLE 34
OTHER_WRITABLE 34
EXEC 37
```

It would be great to get full support of course, but I couldn't begin to understand the undertaking that might require.

**Comment by SGrosse-Holz** [comment]
This is an old thread, but I just stumbled across this with exactly the original question: on WSL, all files under `/mnt` are recognized as exectutable by default; this is fine, but can I tell `ls` to ignore this executable bit and just color by file ending?

Turns out, you can do exactly this (at least it worked for me): just set `ex=0`. Equivalently, if you're using `.dircolors` to generate `LS_COLORS`, set `EXEC 0`.

Stolen from here: https://unix.stackexchange.com/questions/458482/how-to-prevent-ls-colors-ex-from-overriding-extension-color-settings
