### ISSUE TITLE
Something weird on wsl.exe with a custom default shell

### ISSUE THREAD

**Issue by ShyPixie** [Microsoft/WSL#2510]
build number: 10.0.16291.0

I set fish shell as my default shell using chsh command, and the wsl is having a strange behavior since then:

```
C:\Users\eu>wsl
Welcome to fish, the friendly interactive shell
```

this doesn't give me the shell and stuck here... but if I use **_wsl fish_** instead:

```
C:\Users\eu>wsl fish
Welcome to fish, the friendly interactive shell
root@Amora /m/c/U/eu#
```

**Comment by therealkenc** [comment]
You said the same thing in February #1653 ([message](https://github.com/Microsoft/BashOnWindows/issues/1653#issuecomment-276704498)). This was the hang when I looked back then:
```
ioctl(1, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=47, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
getpgrp()                               = 225
ioctl(0, TIOCGPGRP, [225])              = 0
getpgrp()                               = 225
setpgid(228, 228)                       = 0
ioctl(0, TIOCSPGRP, [228])              = -1 EINTR (Interrupted system call)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
strace: Process 228 detached
<E> fish: Couldn't grab control of terminal
tcsetpgrp: Interrupted system call
```
Unless that was addressed, but the issue was never closed.

**Comment by ShyPixie** [comment]
My fish version is 2.6.0 and bash is 4.3.48

**Comment by therealkenc** [comment]
> My fish version is 2.6.0 

Yep that's the variable. Ben, repro (which never seems forthcoming from people who actually use `fish` in this or the original report)....
```
$ sudo apt-add-repository ppa:fish-shell/release-2
$ sudo apt update
$ sudo apt install fish
$ fish --version
fish, version 2.6.0
```
As I [mentioned](https://github.com/Microsoft/BashOnWindows/issues/1653#issuecomment-276870795) back in February, what changed in `fish` since 2.2 isn't clear with a ten-minute look-see, so I don't have a conclusive PR link that caused the fail to offer.

**Comment by CrshOverride** [comment]
I have the same issue locally. The only happens for the first instance of `WSL.exe` opened w/ `fish` as the default shell. Opening subsequent instances (with the first still open) succeed without issue.

Eventually I worked around the issue by using https://github.com/goreliu/wsl-terminal instead of `WSL.exe`.

**Comment by mqudsi** [comment]
> The only happens for the first instance of WSL.exe opened w/ fish as the default shell.

@CrshOverride that might be the key that would explain why I had such a hard time getting it to reproduce consistently.

Fish 3.0 works around this bug, you can build fish from git. That's not to say there isn't a bug on the WSL side of things, we just don't run into it any more.

**Comment by ShyPixie** [comment]
Now, with Windows 10.0.16299.15, fish exit with that message:

-fish: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.

**Comment by mqudsi** [comment]
@ShyPixie what version of fish?

**Comment by therealkenc** [comment]
> -fish: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.

That's #1878.
