### ISSUE TITLE
golang tests

### ISSUE THREAD

**Issue by forskning** [Microsoft/WSL#2526]
peterGo opened this issue

https://github.com/golang/go/issues/22020

Installing from source, several tests fail when running all.bash.

﻿Microsoft Windows [Version 10.0.15063]
2017-09 Cumulative Update for Windows 10 Version 1703 for x64-based Systems

**Comment by therealkenc** [comment]
Going to snipe this one since no response for a month+. The lack of response was **not** because no one cared (I remember when it was reported). The awkward difficultly is that while this issue# meets the "reproducible" requirement absolutely, it isn't actionable. It isn't a bug. It is `n` bugs (for some moving value `n`). WSL fails the golang tests. It also fails the libc tests and the [LTP tests](https://github.com/MicrosoftDocs/WSL/tree/live/LTP_Results). There is a testing related blog entry [here](https://blogs.msdn.microsoft.com/wsl/2017/04/11/testing-the-windows-subsystem-for-linux/) and an on unofficial side discussion in #2031 ([message](https://github.com/Microsoft/WSL/issues/2031#issuecomment-315395044)).

Constructively, what can be done per Golang#22020 is identify specific test case fails that are blocking any killer golang applications with widespread adoption. This is not an easy task mind, because you'll find the in most cases the problem will be a dupe. But _not always_, so please report anything you find following the template.
