### ISSUE TITLE
Unable to reboot windows with Bash On Windows

### ISSUE THREAD

**Issue by panda2k** [Microsoft/WSL#2533]
When using the reboot command in Bash On Windows I get the error `Failed to connect to bus: No such file or directory`

**Comment by ryanerwin** [comment]
Since I could be running multiple Linux terminals (say one copy of Fedora and one copy of Ubuntu) simultaneously, would it be desirable that `reboot` in Ubuntu would also stop my Fedora session and reboot my entire computer? 

This one doesn't make much sense to me, at least as WSL is now...

Once WSL supports an Init daemon and automatically bringing up a bunch of services, this would make a lot more sense... At least to use reboot to restart all processes related to that WSL instance.

Continuing to rely on `shutdown.exe` would probably make more sense for rebooting the entire system.

**Comment by benhillis** [comment]
@ryanerwin - Agreed.  If we eventually do support running system I would expect the reboot command to terminate just the current WSL distribution, not reboot the entire Windows machine.

**Comment by therealkenc** [comment]
Per Ben, rebooting _Windows_ from withing WSL with the [reboot(8)](http://man7.org/linux/man-pages/man8/shutdown.8.html) command per the issue title was declined by-design. For shutting down the instance (contrast rebooting Windows) see #3253. Workaround (put in your `.bashrc` or similar):
```
alias reboot='powershell.exe -command reboot-computer'
```
Or if you are a good person and haven't given yourself Windows Administrator privileges:
```
alias reboot='runas.exe /noprofile /user:Administrator "powershell.exe -command reboot-computer"'
```
