### ISSUE TITLE
Allow terminal color setting

### ISSUE THREAD

**Issue by bbulkow** [Microsoft/WSL#2550]
Windows version: Microsoft Windows [Version 10.0.15063]

Please just add the ability to change colors. Or change the "dark blue on black" to just about anything else, like light blue on black, or dark blue on grey.

If I SSH into another host, the color for directory is dark blue on black. Whoever chose this is a masochist. The default should be something more sensible than dark blue on black - ANYTHING - and the ability to change the color is necessary.

Steps to reproduce: ssh pi@[any host]
$ ls /

You will see that the directory names are unreadable - dark blue on black.

People are asking for mouse and network and all kinds of things. Nonsense. Just allow me to ssh into another host and do an LS and read the output. SSH is the one feature I use most. And please don't tell me to use a windows ssh client like putty. The point of WSL is to give me the workflow I'm used to - and I just ssh around to hosts.

To ask me to change the colors on every host I log into is non-sense.

**Comment by Line117** [comment]
https://www.youtube.com/watch?v=K7Vafhl7P0M

**Comment by zadjii-msft** [comment]
So, there are actually a lot of options available for changing your colors:

1. You can change your default colors to something more pleasing. You can use [colortool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) to change your defaults, and that should apply to your bash.exe/wsl.exe/ubuntu/suse/etc windows, assuming you haven't otherwise set any properties for them. This is the preferred method, because it's a lot easier to load entire color schemes with colortool than doing it manually.

For ex, `colortool -d solarized_dark` will give future console launches the "Solarized" color scheme.
![image](https://user-images.githubusercontent.com/18356694/31350934-eb3ff656-acdd-11e7-89e9-a2de39dd4e6b.png)

2. You can change the properties of your bash.exe window manually. 
 * right click ion the title bar of your console window, and click on properties:
![image](https://user-images.githubusercontent.com/18356694/31350492-4201da2e-acdc-11e7-8ab3-1539a4d3d824.png)
 * Use the "Colors" tab to change the values of the color table to something more pleasing.
![image](https://user-images.githubusercontent.com/18356694/31350510-52a9c062-acdc-11e7-849a-880cbef1d07a.png)
 * Hit okay to save and apply the changes.
Note that the Colors dialog is pretty much garbage and is really hard to use, hence colortool. 

Also note that unfortunately, colortool doesn't work with WSL and interop. It's a limitation of interop at the moment, but if anyone can find a way around that, [PR's are welcome :) ](https://github.com/Microsoft/console/tree/master/tools/ColorTool)

We've also [updated the default color scheme](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) as of the Fall Creator's Update, so if you choose to not change any properties at all right now, then when you get updated to FCU you'll get the new colors automatically.

**Comment by bbulkow** [comment]
Thanks for the quick response.

Can you answer the simple question of whether colortool and similar will apply to ssh sessions?

Lots of previous ideas ( like changing LS_COLORS ) doesn't work when you SSH to another machine.

**Comment by zadjii-msft** [comment]
Yes, it should. The actual colors that are displayed are controlled by the client terminal (in this case, conhost.exe), not the server (whatever's on the other end of ssh). So whenever an application on the server side writes text in "blue", it's up to the client to decide with which actual color "blue" is rendered in.

**Comment by PhMajerus** [comment]
Just in case you're feeling adventurous...
I think you could have the colors set on the server if you wanted to.
What you need is an utility between your SSH server and the shell and apps that parses the VT sequences and convert all palette-specific sequences (colors, bright, ...) to RGB (in \e[38;5;r;g;bm style) according to a locally set palette.
This would increase the network traffic a bit, but would enable you to set your colors on the server side, regardless of client.

You can test this out by running the following:
bash 1> >(lolcat)
Colors should be set randomly by lolcat. Server-side palette utility would work in a similar fashion but swapping colors sequences on the fly.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#81

**Comment by robcresswell** [comment]
@bitcrazed Why was this moved and closed? It's not resolved at all. colortool doesn't do anything for WSL.
