### ISSUE TITLE
Unnecessary packages in ubuntu base image

### ISSUE THREAD

**Issue by firewave** [Microsoft/WSL#2573]
I installed the Fall Creators Update and afterwards removed my existing WSL ubuntu installation and installed it clean from the store (also disabling the Developer Mode which was necessary in the past). After running "sudo apt-get update && sudo apt-get dist-upgrade" it reported the following:

```
The following package was automatically installed and is no longer required:
  libfreetype6
```

Installing and running "deborphan" revealed another unnecessary package:

ubuntu-core-launcher

I am aware that the first package can easily be removed using "sudo apt-get autoremove" and this is not an issue at all, but I thought it might be worth mentioning since the default package should be "clean" IMO.

**Comment by therealkenc** [comment]
This is normal Ubuntu upgrade behaviour (for some value of normal). See for example [this](https://askubuntu.com/questions/862547/ubuntu-core-launcher-was-automatically-installed-and-is-no-longer-required) regarding `ubuntu-core-launcher`. `libfreetype6` is harder to explain; who knows what caused that dependency, and I couldn't find a cite in a quick search. But I'd bet a gold star you'll get the same dangling dependency ref if you install a native stock 16.04 Ubuntu server image from Canonical on bare metal and do the same `apt-get dist-upgrade`. It isn't _likely_ Canonical accidentally dropped `libfreetype6` (but nothing else) into the Store tarball but not their stock image, because including it even accidentally would take active effort. And if it was there accidentally, that is what an `apt upgrade` is there to fix.

**Comment by firewave** [comment]
Just wanted to point it out - feel free to just close this issues.
