### ISSUE TITLE
Issues with Chroot in WSL

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/WSL#2575]
Latest, Creator's build

* Using external software to mount ext4 drives, I attempt to chroot into my linux partion, Chroot fails with no error messages.  
Expected: Chroot command completes and the external linux is loaded in root terminal.

**Comment by fpqc** [comment]
Windows-exotic filesystems are not supported at present, but if you are able to get the btrfs driver for Windows set up (I don't believe that the driver has a signature compatible with secureboot =\ ), you should be able to get things working in that case, since btrfs presents itself as ntfs to the kernel, if I remember correctly.

Full support would require probably a Microsoft ext4 driver to be built for the NT Kernel, which is sort of a problem unrelated to WSL.

**Comment by kenshen112** [comment]
so it wouldn't be possible to not have a Windows driver but instead let Linux mount them??

**Comment by fpqc** [comment]
Not right now.  Microsoft's support for LXFS (the rootfs and homefs for WSL) is a kind of virtual device driver built on top of a sort of internal VFS layer that emulates the full \*nix semantics, and DrvFS is another virtual device driver that implements partial \*nix semiantics for officially supported Windows filesystems (NTFS, Fat32, CDFS, Win32 network shares, etc).  True ext4 support needs both an underlying Windows driver as well as a special virtual driver for WSL to understand it.  This means you need both a filesystem driver for the NT Kernel as well as an additional driver to integrate that filesystem support into WSL.  

If there were an official ext4 driver, the WSL team could probably add support on their own (in particular, they could probably implement full \*nix semantics without emulation on top of it, since this is supported as part of the ext4 filesystem).  The problem is that they are unlikely to add support for a third-party filesystem driver.  

Another option is to wait for them to open up their internal device driver API for lxcore, but this is still closed at the moment since it is still under heavy development.

**Comment by therealkenc** [comment]
@kenshen112 - can you post your repro steps. What is your external ext4 software, what command did you use to mount that drive, what was the result of mounting the drive, can you see your chroot directory hierarchy. After than point we can get to `chroot` failing with no errors, and possibly look at an `strace`.

**Comment by DaJakerBoss** [comment]
I have written a script on my [own personal github](https://github.com/DaJakerBoss/ezchroot), and this issue is plaguing me. The steps as follow:

Mount the ext4 drive in a 3rd party program (The only one is Ext2Fsd.) in the drive "Z:"  
Mount the ext4 partition in WSL `mount -t drvfs Z: /mnt/z/`  
### An error is thrown: "WARNING: drive write protected, mounted read-only."  
### This is an error in the host program Ext2Fsd not being able to mount the drive properly  
Attempt the chroot `chroot /mnt/z/ /bin/bash/`  
Nothing happens. No errors thrown but no output at all. Chroot immediately fails.  

The issue is that the _only_ 3rd party program to mount ext4 partitions **cannot do it properly.**

**Comment by DaJakerBoss** [comment]
Here is the strace output of running `chroot /mnt/z/ /bin/bash` as listed above  
https://pastebin.com/CTS6gTdd

**Comment by DaJakerBoss** [comment]
I am further investigating the issue with the paid software Paragon - Linux Filesystems for Windows

**Comment by therealkenc** [comment]
> I am further investigating the issue with the paid software Paragon - Linux Filesystems for Windows

Right, the other only 3rd party Ext2 NT Windows filesystem driver. Ext2Fsd is #579. There are still no repro steps given for your `chroot` scenario. The error you are seeing is:
```
execve("/bin/bash", ["/bin/bash"], [/* 26 vars */]) = -1 ENOEXEC (Exec format error)
```

I can't tell you whether that is a problem with your `/bin/bash` or whether it is to do with chroot into drvfs in general, because you didn't say how you populated `/bin`. This is somewhat academic however. Whether `bash` fires up initially or not, the next thing it would try to do is access `/dev/tty`, which Ext2Fsd and Paragon do not support. The _very rough_ analogy here is you are trying to `chroot` into a ntfs-3g mount on Real Linux. Rather than jumping into `chroot` scenarios, start with basic file operations. 

Duping into #579 to keep the "enter ext4" scenarios in one place. At this point whether using Ext2Fsd or Paragon you are looking at the same fundamental issues. [If at some point support was added for Ext2Fsd but not Paragon, or visa versa, we can start differentiating the finer points.]
