### ISSUE TITLE
Cannot enumerate files on read-only disks

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2603]
Running build 16299.19; I'm unable to get bash to list the files on a volume that resides on a read-only local (physical) disk.

Can be replicated by creating a partition on a second local hard disk, then using `set-disk xx -IsReadOnly true` under powershell. The volume itself (let's presume the partition is mounted as drive `v:`) is listed under `/mnt/`, but `ls /mnt/v/` returns no files.

**Comment by SvenGroot** [comment]
What happens here is that we try to automount the volume as read-write during instance start, which fails because the disk is read-only. Since the volume isn't mounted, "ls" is showing the contents of the (empty) directory that would be used as the mount point, not the disk you're intending. You can verify this by running the "mount" command; the output will show you that V: (in your example) is not mounted.

As a work-around, you can manually mount it using the command `sudo mount -t drvfs V: /mnt/v -o ro` (actually, in this case it'll work even if you omit `-o ro` because the mount command automatically falls back to read-only if the attempt to mount read-write fails with EROFS).

To fix this, I will add similar fallback logic to mounting during instance start (fallback to read-only if the first attempt fails with EROFS).

**Comment by benhillis** [comment]
@mqudsi - FYI a better way to determine what's actually mounted is by looking at your /proc/mounts file.  We don't clean up the mountpoint directories (/mnt/c etc).

`cat /proc/mounts`

**Comment by Brian-Perkins** [comment]
This should be resolved as of Insiders Build [17101](https://github.com/MicrosoftDocs/WSL/releases/tag/17101).

**Comment by mqudsi** [comment]
Thank you kindly. I shall test it in short order and get back to you.
