### ISSUE TITLE
Permission issues with files on drvfs mounts to SharePoint Online network shares

### ISSUE THREAD

**Issue by hi2u** [microsoft/WSL#2611]
Using drvfs mounting inside the Linux subsystem, I can successfully mount shares that are on local servers, i.e.

```
mount -t drvfs -o ro '\\MyLocalServer\ShareName' /mnt/ShareName
```

When I run `ls -la` in the mountpoint all the files are owned by root:root and I can read their contents.  All good.

However, when I mount a SharePoint Online UNC path, such as:

```
mount -t drvfs '\\myorg.sharepoint.com@SSL\sites\a-team-site-name\Shared Documents' /mnt/sharepoint-site
```

- It does successfully mount
- I can navigate through all the folders and see all the filenames
- All the folders are owned by root:root, permissions are drwxrwxrwx (all good)
- All the files owned by ?:?, and the file permissions are -????????? - I can't read the contents of any files

i.e:

```
$ ls -la

drwxrwxrwx 0 root root 512 May 15 13:46 folderexample
-????????? ? ?    ?      ?            ? fileexample.txt
```

Is there a way to fix this permission issue so that it works the same way as it does for local servers?  

There's no problem reading/writing to the SharePoint share within Windows Explorer - so the issue is specific to the combination of SharePoint shares + mounting in Linux subsystem with drvfs.

Windows build number: Microsoft Windows [Version 10.0.16299.19]

**Comment by ntklotz** [comment]
Hello hi2u, just to get the obvious out there, have you tried using CIFS for uploading? Otherwise, I'd say it's an integration issue between SharePoint and WSL. You'll probably have to pipe it through to an NTFS directory in Windows and upload to SharePoint from there. Otherwise, there's the other obvious question: Did you configure the permissions in Linux to mirror Windows permissions? Remember, Linux and Windows have very different character strings that make it impossible to interpret. You'll always be able to read Windows files in real Linux but never the other way. Running WSL doesn't change that as it's part of the fundamental core of how Linux does everything. You can *try* to access the file from within WSL in SharePoint but SharePoint itself as well as your Win 10 OS will be unable to read the file. Hence, why I mention CIFS as it's supported by both Linux and Windows (part of the reason for it's existence).

**Comment by matteomancini984** [comment]
Dear all,
I have the same problem reported by hi2u in this thread. Was it solved?
I tried all the following commands for mounting. 

```
sudo mount -t drvfs '\\mysharepointserver.org@SSL\sites\info\restricted' /mnt/w
sudo mount -t drvfs '\\mysharepointserver.org@SSL\sites\info\restricted' /mnt/w -o metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11
sudo mount -t drvfs '\\mysharepointserver.org\sites\info\restricted' /mnt/w
sudo mount -t drvfs 'W:\' /mnt/w
```
(W: is the letter where I mapped the network drive in Windows 10)

In all cases mounting succeds and I can see directories and file names, but files cannot be read nor writed.
When I run `ls -l` in a directory in this is what I have:

```
ls: cannot access '/mnt/w/APPROFONDIMENTI/Benchmarking SSM 2021/Indicators.xlsx': Invalid argument
total 0
-????????? ? ?    ?      ?            ?  Indicators.xlsx
drwxrwxrwx 1 root root 512 Mar 25 09:11  Old
drwxrwxrwx 1 root root 512 Mar 23 19:21  db
```

Any suggestion?

Many thanks
