### ISSUE TITLE
Install any GNU/Linux distribution having rootfs tarball .tar.gz format

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#2618]
Here I only install Ubuntu 17.10 not the other distros. Steps that I follow:

**1.** Download Ubuntu from this article [Windows Server Installation Guide](https://msdn.microsoft.com/commandline/wsl/install-on-server). Open the downloaded .appx (or .zip extension) file with [7ZIP](http://www.7-zip.org/). Extract only the ubuntu.exe file.
**2.** Download latest Ubuntu SquashFs file from https://cloud-images.ubuntu.com/releases/17.10/release/ubuntu-17.10-server-cloudimg-amd64.squashfs and put that in same folder of Ubuntu.exe. Convert the .squashfs to .tar.gz with these commands below (see [this wiki](https://github.com/DDoSolitary/LxRunOffline/wiki/Guide-for-fetching-Ubuntu-pre-installed-images) from @DDoSolitary's LxRunOffline). <br>
```
mkdir tmp
unsquashfs -d tmp ubuntu-{version}-server-cloudimg-amd64.squashfs
cd tmp
tar czf ../install.tar.gz *
cd ..
rm -r tmp
```
✯Remember to make the name of the .tar.gz file as **install.tar.gz** because _Ubuntu.exe requires that name_. Ubuntu.exe finds the install.tar.gz file name in its current directory. See this IDA section below::

![install tar gz_filename](https://user-images.githubusercontent.com/31443074/32337824-0d58bdd8-c019-11e7-9e3c-39d74e546174.PNG)

**3.** Now just run Ubuntu.exe, wait till it completes to install it, create user & password.

![ubuntu_artful](https://user-images.githubusercontent.com/31443074/32190015-70b95f0c-bdd2-11e7-971b-14a4b2e70ce2.PNG)

**Comment by ntklotz** [comment]
Or you could just set Prompt=normal and execute a do-release-upgrade to get to the same point. Less work, same result, except probably less issues as you aren't modifying the installation file Ubuntu.exe is looking for. Also, why are you pulling the cloud image? Unless you are running Azure, AWS or something similar, your native host OS is local to the box you're using and has different dependencies than cloud, hence why there's a cloud image in the first place (speaking not just to this cloud image but generally about all cloud images).

**Comment by Biswa96** [comment]
@ntklotz I only show that latest Ubuntu in WSL can be installed from Cloud-Images, may be Microsoft provides cloud-images in Ubuntu.appx. I don't understand the last argument about the usage/dependencies of cloud-image, may you explain it?

**Comment by ntklotz** [comment]
@Biswa96 I'm speaking more about infrastructure dependencies. When running a system from the cloud, it's tied to specified resources that are allocated to the paying customer. That being said, those same resources are being utilized by other customers. It just goes back to what really is cloud? The most basic answer is a server farm that provides resources for multiple environments. Almost the same as virtualization, except everything is web driven and can be accessed through a browser. Or in the case of systems, it's basically thin/thick client that boots from the cloud (regardless of if you have a host OS you boot from first). Essentially what this boils down to is there are no dedicated resources for the coding involved. You can specify your specific hardware components and when your OS loads, it will read which hardware specs are specific to your machine. Since there are multiple servers that could potentially be utilized, you can't have that targeting such as with ARP. It could be that the service providing the OS install is in the cloud and the image itself isn't cloud-based but I was assuming based on your URL that it's a Cloud-driven image. Also the reason you won't find it in Ubuntu.appx or as readily on the Ubuntu site itself is because it isn't LTS. Only LTS versions are shipped through the Windows Store at this time as the officially supported from Canonical and now Microsoft with the release of FCU is only for LTS. Anything above 16.04 is considered in development and will eventually receive no updates or support of any sort after a designated amount of time. The next LTS that will be out is 18.04, which should come out sometime next year. Some users such as myself of WSL just feel we shouldn't be limited to using what is currently NOT the latest and greatest build out there for Ubuntu. I'm sure there are dev builds for OpenSuse and I know for fact Fedora has a dev build (though considering Fedora is an Agile driven project, it already is rather devvy since it's based on having the latest and greatest of everything and pushing it out to users asap (hence the huge demand for Fedora to go on the Windows Store.))

**Comment by Biswa96** [comment]
I'm curious about that there is no `init` file in **install.tar.gz** tarball of Ububtu. But when I install Ubuntu there is a `/init` file created automatically. How is that possible? Does lxcore.sys make it?

**Comment by Biswa96** [comment]
🌟🌟  It is easy to **install any distribution having .tar.gz** file format. This can be done easily with calling [**`WslRegisterDistribution`**](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826870(v=vs.85).aspx) function from **wslapi.dll**. See my GitHub repo for further details.

```
        [DllImport("wslapi.dll", CharSet = CharSet.Unicode)]
        public static extern uint WslRegisterDistribution(string distributionName, string tarGzFilename);
```

✨ Now Ubuntu 18.04 LTS is available as SquashFS in cloud-images. Download this file https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.squashfs and convert it to compressed tarball (.tar.gz) as shown above.

![ubuntu 18 04 bionic beaver](https://user-images.githubusercontent.com/31443074/32857099-cffa85da-ca6c-11e7-9c24-03fa54f939ae.PNG)

**Comment by DarthSpock** [comment]
Is 18.04 that I clearly see is still in development though obviously available, less buggy than 17.10? More to the point, have you tried upgrading from 17.10 to 18.04 using do-release-upgrade or just utilizing the method you described?

**Comment by Biswa96** [comment]
I did not try that. The cause is some childish and naive. Ubuntu takes time to upgrade in WSL. So to be faster, it is easy for me to download the tarball with IDM. I do focus on my first point.

**Comment by DarthSpock** [comment]
Does apt-get upgrade and dist-upgrade work? They are the only 2 apt commands that failed when upgraded with the other method. Note: for 16299 FCU, not the latest Insider.

**Comment by Biswa96** [comment]
In Ubuntu Xenial, `apt upgrade` and `apt dist-upgrade` shows same output that all are upgraded. But `do-release upgrade` shows 'No new release found' in Fall CU. But why are you focused on Ubuntu? Try others....

**Comment by Biswa96** [comment]
### Install BusyBox

Get BusyBox docker image from https://github.com/docker-library/busybox/blob/dist-amd64/glibc/busybox.tar.xz (~2 MB) and convert it to .tar.gz format. And install it in WSL using my repository [WSLInstall](https://github.com/Biswa96/WSLInstall.git) or [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline.git). 

![busybox_installed_wsl](https://user-images.githubusercontent.com/31443074/32984009-0e7831be-ccc4-11e7-9489-cfb8634611fd.PNG)

**Comment by ssfdre38** [comment]
I just tested with this setup and this one does work the best to get 18.04 using the Microsoft provided kernel. Right now im trying to setup a appx for it to install it better to the system

**Comment by DarthSpock** [comment]
@ssfdre38 If you want to generate an appx then your best bet is https://github.com/Microsoft/WSL-DistroLauncher as it provided step by step directions for creating an appx for any rootfs. Biswa is in the process of making a number of changes to his project.

**Comment by Biswa96** [comment]
@DarthSpock With this change or can add Drvfs metadata without using mount/umount command. The appx package in MS repository will be signed before use. There are some ways to do that without signing ;)

**Comment by DarthSpock** [comment]
So you'll basically provide a more simplified manner of performing the steps in launcher project? That sounds like something MS ought to be doing, maybe you could give them some pointers.

**Comment by Biswa96** [comment]
No that is not a secure way to package for Windows Store but is a **short insecure procedure** where user can control anything.

**Comment by DarthSpock** [comment]
Yes. I mean they should probably have a branch for MS Store deployment and another for everyone else. The everyone else can be unsigned if one chooses or choose the Store deployment branch for providing a more secure do it yourself method. It's all about choices.

**Comment by Biswa96** [comment]
Call @benhillis

**Comment by benhillis** [comment]
@Biswa96 - The distro launcher sample can be run as a classic Win32 application. It does not need to be packaged into an appx.

**Comment by Biswa96** [comment]
I know that. But I'm taking about using a unpacked application which can be installed with Powershell and AppxManifest.xml. see the procedure in github.com/mintty/mintty.appx

**Comment by Biswa96** [comment]
I know that. But I'm taking about using a unpacked application which can be installed with Powershell and AppxManifest.xml.

**Comment by Biswa96** [comment]
I know that. But I'm taking about using a unpacked application which can be installed with Powershell and AppxManifest.xml.
BTW, why there are two extra function WslLaunch() and WslLaunchInteractive()? They both use wsl.exe with std I/O handles.

**Comment by lewisdonofrio** [comment]
@Biswa96 What am I doing wrong ;(

1.) open Administrative Powershell prompt
2.) wsl to start ubuntu (18.04 image creator session attempt)
3.) donofrio@WSAL0131:/mnt/c/Users/donofrio/Downloads$ sudo su -
[sudo] password for donofrio:
4.) root@WSAL0131:~# cd /mnt/c/Users/donofrio/Downloads/
5.) root@WSAL0131:/mnt/c/Users/donofrio/Downloads# unsquashfs -d take-three bionic-server-cloudimg-amd64.squashfs

Parallel unsquashfs: Using 4 processors
32221 inodes (35048 blocks) to write
create_inode: failed to create character device take-three/dev/full, because Operation not permitted
create_inode: failed to create character device take-three/dev/null, because Operation not permitted
create_inode: failed to create character device take-three/dev/ptmx, because Operation not permitted
create_inode: failed to create character device take-three/dev/random, because Operation not permitted
create_inode: failed to create character device take-three/dev/tty, because Operation not permitted
create_inode: failed to create character device take-three/dev/urandom, because Operation not permitted
create_inode: failed to create character device take-three/dev/zero, because Operation not permitted
[=======-                                                                               ]  3143/35048   8%^C
root@WSAL0131:/mnt/c/Users/donofrio/Downloads#

Then on another host when I try to "install it" I now see:

PS C:\Users\donofrio\Downloads> .\ubuntu.exe
Installing, this may take a few minutes...
Installation successful!
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: donofrio
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Default UNIX user set to: donofrio
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
donofrio@LTAL0263:~$ sudo --version
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
donofrio@LTAL0263:~$ ls -lsart /usr/bin/sudo
148 -rwxr-xr-x 1 donofrio donofrio 149080 Jan 17 19:08 /usr/bin/sudo
donofrio@LTAL0263:~$

didn't seem like the same results as the first time I did this for 17.04 cloud image conversion?  Wondering what I did incorrectly? ;(

**Comment by Biswa96** [comment]
First copy that squashfs in Linux user home folder i.e. **~**. Then unsquashfs it.

**Comment by Biswa96** [comment]
First copy that squashfs in Linux user home folder i.e. **~**. Then got to home folder with `cd ~` command and unsquashfs it.

**Comment by lewisdonofrio** [comment]
I did, think of downloads as the homedir (I know I'm weird but wanted to stay out of the homedir root) in that I put the squish file into Downloads, because well that is where the browser puts downloads (yes I keep rootfs within downloads as well....paint me crazy) but I'll try your way and see if results are different; guessing not but you replied so I "gotta try."

**Comment by lewisdonofrio** [comment]
I see now....I was unsquishing into a windows homedir not the ~ un*x homedir....now it's unsquishing without error - tnx.... (someone note this so someone else doesn't fall into this trap)

**Comment by lewisdonofrio** [comment]
very good sign:

root@WSAL0131:/mnt/c/Users/donofrio/Downloads# mv bionic-server-cloudimg-amd64.squashfs ~
root@WSAL0131:/mnt/c/Users/donofrio/Downloads# cd ~
root@WSAL0131:~# ls -lsart
t77920 -rwxrwxrwx 1 root root 181485568 Jun 12 02:16 bionic-server-cloudimg-amd64.squashfs
     0 drwx------ 0 root root      4096 Jun 12 15:53 .
root@WSAL0131:~# unsquashfs -d take-three bionic-server-cloudimg-amd64.squashfs
Parallel unsquashfs: Using 4 processors
32221 inodes (35048 blocks) to write

[=======================================/] 35048/35048 100%

created 27527 files
created 3248 directories
created 4681 symlinks
created 7 devices
created 0 fifos
root@WSAL0131:~# 

:)

**Comment by lewisdonofrio** [comment]
how do I get rid of these "strikeout" lines.....lol

**Comment by Biswa96** [comment]
Sir, you are making many comments. If you succeed then don't reply with the output. Just say ok 😊
