### ISSUE TITLE
Installation of ARP/wARP 7.6 failed

### ISSUE THREAD

**Issue by TomRei87** [Microsoft/WSL#2621]
Hi,

I tried to setup the whole enviroment to use the CCP4 interface including SHELX, ARP_wARP and SHARP on my current build
`Microsoft Windows [Version 10.0.16299.19]`

CCP4, SHELX and SHARP I managed to get running, but ARP_wARP doesn't seem to work.

I downloaded the package and proceeded like distributor suggests.

```
tom@Tom:/usr/local$ tar xfvz /some/where/arp_warp_7.6.tar.gz
tom@Tom:/usr/local$ cd arp_warp_7.6
tom@Tom:/usr/local/arp_warp_7.6$ ./install.sh
Your login shell is: /bin/bash

tcsh located in /bin/tcsh will be used

Replacing /bin/csh with /bin/tcsh

ARP/wARP installer modified on Tue 08 Dec 2015

Checking permissions for /dev/null    - OK
Checking availability of sed command  - OK
Checking availability of tail command - OK
Checking availability of awk command  - OK
Checking decimal separator            - OK
Checking ARP/wARP directory path      - OK
Checking ARP/wARP directory structure - OK
Checking operating system name        - Linux
Checking processor type               - x86_64
ARP/wARP version 7.6 executables for this platform
are available in /usr/local/arp_warp_7.6/bin/bin-x86_64-Linux
*** ERROR ***
This machine cannot run ARP/wARP executables that
are statically linked to glibc.

    *** INSTALLATION OF ARP/wARP 7.6 FAILED ***
Modified version exit status 1
tom@Tom:/usr/local/arp_warp_7.6$
```

Does anyone has an idea how to get around this issue?

**Comment by therealkenc** [comment]
This is #1466 (CCP4), which is the same as #1462 (Softbank), which is the same as the one just above you in #2622 (Ioncube). What are the odds of that. 

The common denominator being these are all statically linked binaries. The notable difference here is that the `ARP/wARP` installer appears to be kind enough to say it isn't going to work up front, instead of waiting for the segfault. If you somehow managed to work around the `shelxd` crash in #1446 (here)(https://github.com/Microsoft/WSL/issues/1466#issuecomment-265583027), by whatever means, then it could be a false positive. Comment out the check in the install script and see what breaks next. Bonne chance.

**Comment by therealkenc** [comment]
No `strace` provided to confirm, but let's call this #1466 for now. If #1466 flips to fixed and the problem persists, add a comment to that effect over there and someone can take a closer look.
