### ISSUE TITLE
No clearly documented way to create an AppX bundle for a Linux distribution from scratch (custom distributions)

### ISSUE THREAD

**Issue by brad-x** [Microsoft/WSL#2635]
Try as I might I have yet to find documentation on how to construct an AppX that will allow a Linux distribution to be installed. 

I'm hoping I'm missing something terribly obvious and that this isn't a secret.

**Comment by Biswa96** [comment]
Microsoft provides the Appx files in this article [Windows Server Installation Guide](https://msdn.microsoft.com/en-us/commandline/wsl/install-on-server).
- Ubuntu: https://aka.ms/wsl-ubuntu-1604
- OpenSUSE: https://aka.ms/wsl-opensuse-42
- SLES: https://aka.ms/wsl-sles-12

**Comment by xenithorb** [comment]
Where's Fedora?

**Comment by Biswa96** [comment]
@xenithorb Fedora is not officially available now. But you may try this procedure. See this comment https://github.com/Microsoft/WSL/issues/8#issuecomment-212116902

**Comment by brad-x** [comment]
Good info here but what I'm actually looking for is a documented way to create the AppX bundle for a Linux distribution from scratch, in order to create a custom distribution that could be sideloaded or submitted to the Windows Store.

**Comment by Biswa96** [comment]
> "create the AppX bundle for a Linux distribution from scratch, in order to create a custom distribution"

@brad-x Add those words in your issue tittle.

I'm pleased that you want to create custom distribution, many user want other distros. But all of those are not available in Store till now. May be you create one using those **.tar.gz** files from distro's website. But those tarballs are different from the availability ones in Store. See #8

**Comment by sunilmut** [comment]
@tara-raj might be able to answer questions on official documentation for publishing your own distro.

**Comment by Biswa96** [comment]
@brad-x The two essential parts of Linux distro appx packages are 1. Open source userspace compressed tarballs (.tar.gz) 2. Close source installer executable (.exe). You can make packaged appx with visual studio.

Though you can get the tarball in any distro homepage, you can not get that installer executable.

**Comment by DarthSpock** [comment]
@Biswa96 I think Debian let loose the [secret]( https://salsa.debian.org/rhaist-guest/WSL) on creating a distro in the Windows Store. Probably also relevant to @DDoSolitary and @RoliSoft

**Comment by Biswa96** [comment]
@DarthSpock, According to @bitcrazed making a distro for WSL is not a rocket science. The distro launcher in those Windows Store Appx files are depends on `wslapi.dll`. 

For example, If you download Ubuntu Appx (i.e. `CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc.Appx`) from Windows Store and extract `ubuntu.exe`, then you get that it imports all WSL functions from `wslapi.dll`. I'm not amaze seeing this code. But I'm astonished that Debian released that code (C++). ❤️ Debian 

All distro launcher have same code except the commands to add user in Linux (depends on distro). I'm interested in `wsl.exe` or `bash.exe` and how the connect with `LxssManager.dll` with COM.

**Comment by Biswa96** [comment]
@DarthSpock Is it official report of original code for debian.exe? I doubt that because the repo owner name has `-guest` meaning he is not the debian developer.

**Comment by DarthSpock** [comment]
@Biswa96 It looked to me to be the same code they used for uploading to the Windows Store and creating the .appx file. I did get a partial spoiler for how they create  Kali has something similar with their [Kali-WSL-chroot](https://github.com/offensive-security/Kali-WSL-chroot) page but doesn't include the .appx info unfortunately. I know the repo owner is a Debian developer and took the credit on Twitter for getting this published. Indeed, if you look at the issues tracker, another Debian developer pointed out as much since the WSL image wasn't built the same way as other images Debian creates. I did notice about `cdebootstrap` but I'm guessing you're familiar with it as you already call the WSL API. 

I would recommend opening an issue there so he can walk you through how he used `wsl.exe` and/or `bash.exe`  to `LxssManager.dll`. I personally don't have enough know how to build and distribute a distro for WSL but since you've already gotten most of the process down, it would be great to see you releasing something a bit more official (and easier to use).

**Comment by Biswa96** [comment]
For the debian based distros (i.e. Debina, Ubuntu, Kali), I assume that the launcher executable will be same as they have same commands to add users. If you want to create that launcher just change this line with the distro name (in MyLinuxDistroLauncher.cpp):
`this->_myName= L"Debian";`

One can get the easy source code from @yuk7 repositories. See his works.

**Comment by DarthSpock** [comment]
So I was right and wrong about the link above. It's specific to Debian but I found another by another Debian developer and gives ALL the build steps you need to create a distro for WSL. https://salsa.debian.org/zobel/WSL

**Comment by Biswa96** [comment]
Good news, I've found that wslapi.dll does some COM mechanism with LsxxManagerProxy.dll to install .tar.gz. `WslRegisterDistribution()` calls CreateThread() first and then CoCreateInstance(). 

May be there is a way not using wslapi.dll and not the Wsl functions. @benhillis Am I right?

**Comment by Biswa96** [comment]
Good news, I've found that wslapi.dll does some COM mechanism with LxssManagerProxy.dll to install .tar.gz. `WslRegisterDistribution()` calls CreateThread() first and then CoCreateInstance().  The two parameters goes into CreateThread's lpParameter.

May be there is a way not using wslapi.dll and not the Wsl functions. @benhillis Am I right?

**Comment by benhillis** [comment]
@Biswa96 - The COM interface is not documented, the Wsl* functions are.

**Comment by bitcrazed** [comment]
@Biswa96 We recommend holding-on for a little longer: @tara-raj is currently driving the process to open-source the launcher project that distro partners have been forking & using to create the launcher for their distro packages.

The reference launcher implementation provides default implementation of the launching process, as well as some key functionality we'd like to see all launchers support consistently (e.g. `clean`).

The launcher uses the public Win32 API's which in turn call the internal WSL APIs and infrastructure. As always, avoid calling internal APIs since they may change without warning.

**Comment by benhillis** [comment]
@bitcrazed - Clean is a bad example, that has been removed from the new sample.  The supported way to clean is via app settings.  Right click tile -> More -> App settings -> Reset

**Comment by Biswa96** [comment]
I want to explore the COM programming and not to dependent on public WSL* functions. So I choose the COM mechanism and search (i.e. reverse) the procedure in wslapi.dll.

The WslRegisterDistrbution function include many extra functions like [`GetCurrentPackagePath()`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh446602(v=vs.85).aspx) which does not require in simple win32. And also it extracts tar.gz with [`QueryFullProcessImageName()`](https://msdn.microsoft.com/en-us/library/ms684919(v=vs.85).aspx) at execution path.

**Comment by bitcrazed** [comment]
@Biswa96 There are FAR better ways of exploring COM programming than trying to call non-public COM API's. Note that since the COM API is not public, it's liable to change at any time, which will likely break your code. 

It's MUCH safer to call the public & documented Win32 API's.

**Comment by DarthSpock** [comment]
The good news has finally arrived: https://github.com/Microsoft/WSL-DistroLauncher
See this blog post: https://blogs.msdn.microsoft.com/commandline/2018/03/26/wsl-distro-launcher/
