### ISSUE TITLE
Possible to move MYSQL data directory to different drive?

### ISSUE THREAD

**Issue by hyphen1370** [microsoft/WSL#2652]
Hello, 

I am experiencing the issue trying to move the mysql data directory to different drive to save space in C drive. Here is what I did:

1. Install mariadb with default settings
2. follow this guide to move data directory to /mnt/d/Database
https://www.digitalocean.com/community/tutorials/how-to-change-a-mysql-data-directory-to-a-new-location-using-a-symlink
3. restart the mysql 

I can restart the mysql and it works. However, it failed to create table with Errcode 5: Input/Output error. 

So, is that possible to do this?

**Comment by therealkenc** [comment]
This is #2644 #2593 et al.

**Comment by comsuoncha** [comment]
i have the same problem. any update here?

**Comment by comsuoncha** [comment]
Hi @therealkenc , can you take a look at this, thank you!

**Comment by comsuoncha** [comment]
up

**Comment by therealkenc** [comment]
This isn't on planet `ISSUE_TEMPLATE.md` so I took a pass. `EIO` is WSL's `EWTF` response when something "went wrong" with the filesystem. Who knows how the OP has their rig set up. Someone like Sven would need to take a look at the cause of the `EIO`, but the chances of one of the devs following a link on the Interwebs is nearzero. The only reason I didn't follow-up was (a) I repro the `EIO` and say "yep that's an EIO alright" followed by chirping crickets or (b) (worse) it works fine because I don't have the same `D:` drive setup as the OP.  The only reason it wasn't tagged need-repro and closed is because the EIO is almost certainly (kind of by definition) either a bug or a lack-of-feature, but who knows because academic.

**Comment by Vorta** [comment]
I have the same issue. However. If I have MySQL installed on Windows and create tables and the Linux-side MySQL directed to that dir it reads data normally. However, as soon as a larger insert is to be done, the same error occurs.
Windows version 1809.

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the `EIO`.
