### ISSUE TITLE
tmux pane borders are all garbled if used with Window Scaling enabled

### ISSUE THREAD

**Issue by 9a3eedi** [Microsoft/WSL#2701]
I've noticed that tmux acts strange on my laptop with cmd. My laptop has an almost 4k screen so I have scaling set to 150%. This is what happens with tmux if I open 3 panes, then move between them for a bit

![image](https://user-images.githubusercontent.com/8945202/33309102-6e8248f0-d436-11e7-9d39-ec3530432092.png)

However this issue doesn't occur when I have it set to 100% scaling.

![image](https://user-images.githubusercontent.com/8945202/33309161-95afa472-d436-11e7-95f3-8b9a51f81ea8.png)

As you can see, I've done the same thing with 100% scaling, and everything is displayed correctly.

I am not sure where the fault lies, is it a tmux bug? or a Windows console bug? or maybe it's the way that the WSL talks to tmux if the screen is scaled? 

I also can't seem to find this bug mentioned anywhere so maybe it's just my machine? But then again, maybe the kind of people who use tmux also aren't typical the kind who use Ubuntu for Windows on a hi-dpi screen :)

**Comment by zadjii-msft** [comment]
@9a3eedi What Windows build are you on? That is a known problem in pre-1709 builds.

**Comment by parkovski** [comment]
I'm on 1709 and can't repro this with tmux but I'm having a similar issue with vim with a recent patch that enables `termguicolors` on Windows.

My setup is a Surface Pro 4 with a standard DPI external monitor - the issue only happens when I start vim in an unmaximized console and then maximize it on the Surface (HiDPI) screen. The console spills over to the next screen and it seems like the buffer is shifted up by one line - `ggk` shows a white line at the top with no line number, and `Goj` makes inserted text appear on the line above where it's supposed to be.

After it's glitched out like this, unmaximizing the Window makes it even worse, kind of like @9a3eedi's tmux, and `Ctrl-L` to redraw the screen doesn't fix it.

I noticed a similar off-by-one bug while working on ANSI input for PSReadLine, but can't be sure if it's my bug or this one.

[Here is a copy of my patched vim.exe](https://1drv.ms/u/s!AtPZ-a4QMjWiivs0c4mfn2DimcOzRw) - hopefully this will help diagnose the problem. You may need these commands to make `tgc` work:
```vim
set t_Co=256
set t_8f="\e[38;2;%lu;%lu;%lum"
set t_8b="\e[48;2;%lu;%lu;%lum"
noremap! <Char-0x7F> <BS>
set tgc
```

**Comment by zadjii-msft** [comment]
@parkovski Can you file a separate issue for what you're seeing? I'd prefer keep the issues separated. Even if they seem related, it's usually safer to keep individual issues as isolated possible.

Also, a picture is worth a thousand words - screenshots would be super helpful. `Win+S` is useful for taking a snip to paste here.

**Comment by parkovski** [comment]
@zadjii-msft Done

**Comment by 9a3eedi** [comment]
@zadjii-msft You're right. I was at a pre-1709 build. I've recently updated and I no longer have this issue.

Thank you! and sorry for wasting anyone's time
