### ISSUE TITLE
File modification date wrong using DrvFs

### ISSUE THREAD

**Issue by ajkWare** [microsoft/WSL#2707]
1.	Microsoft Windows [Version 10.0.16299.64]
2.	I've been failing to compile Handbrake using Ubuntu.  The problem is that **the modification time for files created by expanding an archive using tar in mounted Windows filestore is incorrect.  The modification time is not the same as the file in the tar archive**. As a result, using make is confusing as often targets are rebuilt which shouldn't be or can't be. The latter occurs for example when building m4 within the HandBrake build sequence.
3.	The situation can be reproduced using the following sequence
 
•	Create a file in a directory
 ```mkdir d
echo "abc" > d/f
touch -t 197001010000.00 d/f
```
 •	Create an archive
   
`tar  cvf d.tar  d/`
 
•	Expand the archive into windows mounted filestore
 
`tar -C /mnt/c/temp  -xvf d.tar`
 
•	Compare the modification time for the file f
 ```
stat d/f
  File: 'd/f'
  Size: 4               Blocks: 0          IO Block: 4096   regular file
Device: 2h/2d   Inode: 12103423999474836  Links: 1
Access: (0666/-rw-rw-rw-)  Uid: ( 1000/    andy)   Gid: ( 1000/    andy)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 2017-11-29 01:32:41.093089400 +0000
 Birth: -
 
stat /mnt/c/temp/d/f
  File: '/mnt/c/temp/d/f'
  Size: 4               Blocks: 0          IO Block: 4096   regular file
Device: ch/12d  Inode: 10414574139210909  Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-11-29 01:34:23.630770700 +0000
Modify: 2017-11-29 01:34:23.630770700 +0000
Change: 2017-11-29 01:34:23.630770700 +0000
 Birth: -
```
Notes:
 
i.	If you expand the file in VoIfs, the timestamp is correct 
ii.	If you expand the file using a native Windows tar implementation and ntfs, the timestamp is correct
iii.	If you use a file with no content (i.e. omit the echo command above), the timestamp is correct.  This last result is rather puzzling - the system calls used by tar in the two cases are identical apart from the write to give the file content between creating it and setting the modification time.
iv.     You can correct the modification time in windows filestore using touch i.e. touch works as expected

**Comment by jstarks** [comment]
In Windows, file modification times are updated not when the write occurs, but at a time update point, which is usually at handle close. This can unfortunately override a time that was explicitly set via a different file handle.

And that’s what’s happening here. Tar is writing the data and then updating the modify time. But the update is happening in drvfs with a different handle from what we are using to do the write. So when the file descriptor is closed, drvfs closes the write handle, and this overwrites the original time.

This is all very unfortunate. We are working on a couple of possible fixes, and I hope to have something available in an insider build before too long.

**Comment by fkbreitl** [comment]
That's a serious problem for me too, that prevents me from using tar.

**Comment by tcsRTI** [comment]
I have Ubuntu for Windows 10 running in a Parallels VM on macOS Sierra. Because of issues with drvfs and Parallels shared folders, I'm attempting to export an SMB share from macOS, map it to a drive letter in Windows, and mount the resulting drive letter in Ubuntu with drvfs.


If I use 'touch' to create a file in that share natively from macOS, both Windows and Ubuntu see the correct timestamp on the file, i.e. "ls -l" shows me the correct date and time. If I touch a file from PowerShell, I see the correct timestamp in all three places. If I touch a new file from an Ubuntu bash shell, I see wildly incorrect timestamps. Specifically, Ubuntu is telling me Dec. 31 1969, Windows is reporting a blank timestamp in PowerShell and Windows Explorer Properties is reporting sensible Created and Accessed times but just says "Modified: 12:00:00 AM", and macOS is reporting May 28 of the year 60056. Yes, the year sixty thousand fifty six.

Is this a matter of configuration, or is there a bug somewhere?
