### ISSUE TITLE
Need a tool like tcping.exe on WSL

### ISSUE THREAD

**Issue by PtwHub** [Microsoft/WSL#2714]
As noted in other issues, there are severe limitations in WSL when using raw-socket network analysis tools. However, if I use WSL, I need some simple tools to figure out things like tcp routes and pings to analyse firewall and proxy connectivity. Where can I get a tool like https://www.elifulkerson.com/projects/tcping.php tcping.exe which works like a charm on windows 10. Thanks!

**Comment by therealkenc** [comment]
https://download.elifulkerson.com/files/tcping/0.37/x64/
https://www.elifulkerson.com/projects/tcproute.php
https://docs.microsoft.com/en-us/sysinternals/downloads/psping

**Comment by rodrymbo** [comment]
@PtwHub: A question for your question: have you tried interop? When I place tcping.exe on my Windows Path and invoke it with tcping.exe from within WSL, it runs and seems to be working properly, e.g. `tcping.exe example.com | grep success`. Interop also works with things like `NETSTAT.EXE -an` or `TRACERT.EXE`  (which are all caps on my machine for some reason...). Not exactly a linux result, but fairly close, and since WSL relies on Windows networking, you get results from the source, instead of something that has gone through a compatibility layer to try to get it to a linux app.

I suppose for consistency I should have used tcping64.exe but tcping.exe worked so I didn't go that far.

Thanks for the links, @therealkenc -- I learn stuff from your posts almost every day.

**Comment by PtwHub** [comment]
Thanks, yes, it appears to work at the moment with interop: calling the windows *.exe from WSL bash. I expect this is more of a workaround than the long-term desired approach, but it works, so case closed.
