### ISSUE TITLE
ZFS support (ideally Canonical's pre-built ZFS-on-Linux modules)

### ISSUE THREAD

**Issue by jim-collier** [Microsoft/WSL#2716]
First off, let me acknowledge that this feature request "should" go to [UserVoice](https://wpdev.uservoice.com/forums/266908). The problem being, UserVoice seems to be broken; searches don't finish, can't add new requests, etc. Furthermore, Git is a far more user-friendly platform and appears to be more active. (Though hard to be sure.)

That said, I was surprised to find that this request hasn't already been made here.

**Quick checklist of top ZFS benefits**

- Metadata-based integrity verification
- Copy-on-write
- Snapshots for free
- Clones for free
- Send and receive snapshots
- On-the-fly compression
- Sophisticated redundancy options, etc.
- Containers work best on ZFS

Even Btrfs has been unable to reliably crack this nut after years of development. Microsoft has been waffling on ReFS (e.g. pulled from 10 Pro) - and like Btrfs, has it's share of problems and even more compromises.

**Problems and challenges with supporting ZFS on WSL, that I'm currently aware of**

1. ZFS is a kernel module, which currently is not supported in WSL, may never be, and isn't currently the intended goal of WSL (whic is currently to provide user-space linux dev tooling).
2. ZFS requires direct block device access, which similarly isn't currently supported in WSL, and /dev/disk doesn't exist.
3. ZFS is released under CDDL, which is incompatible with GPL v3 (and lxss isn't even open source).
4. ZFS on Linux is itself a hybrid port/re-implementation of Solaris ZFS, and already has a number of kludgey workarounds and shims (such as the SPL translation layer).
5. ZFS on Linux uses memory and disk caching in a poorly integrated way, due to the fundamental architectural differences between Linux, and ZFS's original target OS.
6. There are already open-source efforts to bring ZFS to Windows natively. (E.g. [ZFSin](https://github.com/openzfsonwindows/ZFSin).) While this may solve a much-desired wish for many: ZFS self-contained on Windows - without having to run a VM and jump through hoops with vmdk passthrough and loopback samba sharing - it still comes with these drawbacks:
    1. It's not currently stable.
    2. It doesn't have the backing and engineering resources of the host OS's owning company behind it, or large teams like ZFS on Linux. (Yet, at least.)
    3. Other attempts to bring Linux filesystems to Windows have been fraught with stability and/or reliability issues for long-term, high-volume applications (e.g. FUSE modules on Dokan).

**There would be many open questions - such as**

- How would ZFS volumes be accessed?
    - Only via WSL? (Very limited - only access via local terminal, remote SSH, or remote SSHFS.)
    - Samba? This might be a great cross-platform option, but Samba does not appear to work on WSL currently. Also, there would be port conflicts with native CIFS to work out.
    - NFS? Not an ideal cross-platform solution, and being a kernel module, not currently supported by WSL. (Third-party user-space nfs-ganesha apparently might work though.)
    - A Windows CIFS pass-through feature? This could be ideal, could leverage performance improvements of Windows CIFS (such as direct memory mapping), and would solve other problems as well (e.g. accessing WSL filesystem from Windows since accessing the lxss folder directly is a no-no). Granted, it seems like it might be a significant technical hurdle.

**Some solution ideas to problems listed above**

1. No support for kernel modules in WSL: Lxss is itself a shim/translation layer that fakes a linux kernel to user space, so it should be possible to also fake a kernel module interface.
    1. This could even be extended to allow building against the kernel ala DKMS (which Ubuntu's ZFS no longer needs to do), which could further WSL's place as a useful dev tool.
    2. Would solve countless other kernel module -related requests, such as support for FUSE, NFS, eCryptFS, etc.
    3. The fact that WSL already works so well on Windows, has led to an explosion of end-user interest. For example, it is already trivially easy to get an Ubuntu desktop running on WSL (e.g. via VcXsrv). While that's not officially "supported" or even recommended, and things can get wonky, it's still cool - and (arguably) more promising than Wine on Linux which is (arguably) more wonky still, even after decades of development (given how closed, complicated, and rapidly moving Windows is). Allowing kernel module support would significantly expand the options and capabilities of running a Linux GUI on Windows. (And of course expand the number of potential problems.)
2. No block device access, no /dev/disk: This could also be supported, in theory - or at least Cygwin does (granted Cygwin is a very different thing and with different goals). Obviously some precautions would be needed, such as restricting access to devices already mounted by Windows, to read-write mode (if at all). Adding this level of support would again expand the horizons and capabilities of WSL. There would also be challenges in virtualizing and/or passing-through access to hardware registers, so that unmodified linux drivers could access them as they expect to - probably no small feat.
3. ZFS's CDDL license: The Linux world solves this by not including it in a distribution, but making it easily available. (Ubuntu even precompiles it and makes available through standard repositories.) Then it is a user choice and - arguably - nice and legal.
4. ZFS on Linux being a hybrid port/re-implementation of Solaris ZFS: As long as it works on Linux, and the above points are addressed, it should work. And again, the ZOL project is working on making ZFS on Linux more Linux native.
5. Memory and disk caching is poorly integrated into Linux model: The ZOL project is working on this.

Again, these are not modest challenges and the solutions wouldn't be cheap or easy. There may never be enough justification for Microsoft to throw engineers and money at such a challenge. It could remain a pipe dream forever. (Or until Microsoft abandons WSL, whichever happens first.) But you have to admit - that Microsoft is the one developing WSL in the first place, and that it is pretty robust so far- is pretty amazing! Just imagine how much more amazing it can or could get.

**Comment by kfix** [comment]
Windows has iscsi initiators, use those to talk to a storage appliance that supports ZFS. Export a zvol to windows, it can format as NTFS and manage the filesytem for WSL to use.

you can run the NAS as a VM and provide it a disk drive from the host. Perf would likely be lousy, but you get all the COW features that might acccelarate your workflow in spite of that - branching & snapshots are wonderful for build bots.

Not sure why you’d think that Windows supporting binary Linux kernel modules is even remotely possible — Linux doesn’t guarantee a stable ABI from version to version. Rebuilding external mods from source against some mythical compatibility layer is likely not possible either,  native Linux distributions rely on DKMS for this and that can easily be stymied.

**Comment by doublemeat** [comment]
@kfix thanks for the comment, but it was helpful, didn't add new information in context, was (probably unintentionally) misleading, and unnecessarily derisive.

That Linux doesn't guarantee kernel ABI stability is irrelevant, in context. The fundamental point of WSL _itself_ is to provide a substantial portion of a distro-specific kernel ABI, upon which corresponding native Linux userland dev tooling runs. (Then thunk those syscalls to Windows.)

It is in fact "remotely possible" to expand that thunking layer arbitrarily, including support for kernel modules, which are consumers of the kernel interface. (Whether easy and/or worth it to Microsoft, is debatable at best or doubtful at worst. But certainly not impossible.) If you still disagree, that's fine - but you should probably do the Wine project a favor, and inform them stat that they can't thunking low-level APIs is not remotely possible. And also Microsoft, so that they can stop wasting time on their x86:x86_64 WOW translation layer - which is also an ever-moving target. And MAME. And all the other native game console translators that not only target unstable ABIs, but undocumented ABIs. You may rightly argue that WSL, Wine, and MAME are different projects with different goals and legal justifications - which is true and great. But would miss the point about what is "remotely possible" with low-level ABI tunking against an impermanent and even undocumented interface. Countless examples of "likely not possible mythical compatibility layers", if you will.

As for iSCSI SAN, that is beyond the intended scope of this post. I tried to be clear that this was for single-host "enthusiast" use, not for enterprises, or for physical multi-host configurations. (And for the same price, a straightforward native ZFS NAS over CIFS would perform better than NTFS on ZFS over iSCSI SAN, be less brittle, and make more sense for typical home users.)

As for your "NAS in a VM" idea: 1) I already mentioned that as a viable alternative, and 2) given modern-enough consumer-grade hardware and virtio - and all else being equal including storage controllers and media - performs significantly better than gigabit NAS or SAN. (I'm using this setup as we speak. The only real challenges to the configuration is remapping the physical devices to raw VMDK attachments every time the VM starts, which can be [and is] scripted; and setting up a second virtual host-only adapter for sharing to host, for optimal performance. As an alternative to raw VMDK mapping, one could - and many do - configure virtualization I/O pass-through to one or more dedicated adapters, also all on the same host.)

So again, the point of this thread is to get the idea of (single-host) ZFS in WSL in writing, point out why and to whom it might be useful (not necessarily the current WSL target of developers), acknowledge the challenges so that it hopefully doesn't devolve into pedantry, solicit informed and technically accurate discussion/agreement/disagreement, and to do so on a user-friendly forum that Microsoft is hopefully reading but isn't their problematic UserVoice site.

(And so far, it appears there's either not much interest, it's not reaching enough eyes, and/or the idea wasn't presented concisely/well enough. That's a risk I knew I was taking.)

**Comment by jim-collier** [comment]
@kfix thanks for the comment, but it didn't add new information in context, was (probably unintentionally) misleading, and came off as unnecessarily derisive.

That Linux doesn't guarantee kernel ABI stability is irrelevant, in context. The fundamental point of WSL _itself_ is to provide a substantial portion of a distro-specific kernel ABI, upon which corresponding native Linux userland dev tooling runs. (Then thunk those syscalls to Windows.)

It is in fact "remotely possible" to expand that thunking layer arbitrarily, including support for kernel modules, which are consumers of the kernel interface. (Whether easy and/or worth it to Microsoft, is debatable at best or doubtful at worst. But certainly not impossible.) If you still disagree, that's fine - but you should probably do the Wine project a favor, and inform them stat that thunking low-level ABIs is not remotely possible. And also Microsoft, so that they can stop wasting time on their x86:x86_64 WOW thunking layer - which is also an ever-moving (and even often undocumented) target. And MAME. And all the other native game console translators that thunk the entire stack. You may rightly argue that WSL, Wine, and MAME are different projects with different goals and legal justifications - which is true and great. But would miss the point about what is "remotely possible" with low-level tunking against impermanent and even undocumented interfaces. All examples of "likely not possible mythical compatibility layers".

As for iSCSI SAN, that is beyond the intended scope of this post. I tried to be clear that this was for single-host "enthusiast" use, not for enterprises, or for physical multi-host configurations. (And either way, for the same price, a straightforward native ZFS NAS over CIFS would perform better than NTFS on ZFS over iSCSI SAN, be less brittle, and make more sense for typical home users.)

As for your "NAS in a VM" idea: 1) I already mentioned that as a viable alternative, and 2) given modern-enough consumer-grade hardware and virtio - and all else being equal including storage controllers and media - performs significantly better than gigabit NAS or SAN. (I'm using this setup as we speak. The only real challenges to the configuration is remapping the physical devices to raw VMDK attachments every time the VM starts, which can be [and is] scripted; and setting up a second virtual host-only adapter for sharing to host, for optimal performance. As an alternative to raw VMDK mapping, one could - and many do - configure virtualization I/O pass-through to one or more dedicated adapters, also all on the same host.)

So again, the point of this thread is to get the idea of (single-host) ZFS in WSL in writing, point out why and to whom it might be useful (not necessarily the current WSL target of developers), acknowledge the challenges so that it hopefully doesn't devolve into pedantry, solicit informed and technically accurate discussion/agreement/disagreement, and to do so on a user-friendly forum that Microsoft is hopefully reading but isn't their problematic UserVoice site.

(And so far, it appears there's either not much interest, it's not reaching enough eyes, and/or the idea wasn't presented concisely/well enough. That's a risk I knew I was taking.)

**Comment by therealkenc** [comment]
Discussion appears to have run it's course. Fundamentally dupe #1893, which actually has zfs as the use case cited. If or when [openzfsonwindows](https://github.com/openzfsonwindows) goes stable release, `mount -t drvfs` might be a well formed ask, much like #579.

**Comment by mailinglists35** [comment]
>If or when openzfsonwindows goes stable release

@therealkenc what is the most appropriate public place where Microsoft could discuss zfs on Windows? For example could they assign some people on the mentioned ZoW github project?

I mean I know it's a competitor to it's own proprietary ReFS, but still would be very interested to know their opinion (not just technical but legal also)!

So far everyone seems to fear Oracle except Canonical, and Canonical appear to be in warm relations with Microsoft...

**Comment by xrishox** [comment]
I've been building my own wsl kernel with zfs support for the last 6 months or so and it works well enough, but I'm a bit uneasy about keeping my own kernel up to date. I would much prefer to be on the microsoft native kernel, but without zfs support this is a no go for me. Please reconsider supporting zfs natively. Seeing as how canonical has found a way to do it without legal issues, I've got to imagine that it should be possible here too.

**Comment by jittygitty** [comment]
@mailinglists35 Microsoft's stance has greatly evolved with time (for the better!), perhaps partly because:
https://www.zdnet.com/article/microsoft-developer-reveals-linux-is-now-more-used-on-azure-than-windows-server/

For a history you can read links from this search result:
https://www.google.com/search?q=microsoft+holds+patents+against+linux+get+royalties

So, the about-face Microsoft did is great news for Linux and for ZFS as well. In fact, Microsoft is in much better position to use ZFS on Windows, even distributing binaries without any issue. Because as far as I know there is "zero" license issue with "distributing" ZFSonWindows "binaries", compared to the 'license technicality' that causes a gray area if "distributing" ZFS binaries within Linux. Therefore, Microsoft could literally make ZFS as an officially supported filesystem if it wanted to.

@jim-collier @kfix I do not think that the ZFSonWindows project tries to load Linux kernel modules and zfs modules meant for Linux kernel. I have not looked at any of the code, but it seems to be that it is a real "port" of zfs code to the Windows platform.

@xrishox Have you used the latest from https://github.com/openzfsonwindows/ZFSin and if so can report on stability etc?

**Comment by jim-collier** [comment]
This is fantastic to hear. I started watching releases on https://github.com/openzfsonwindows/openzfs.

Interestingly, with WSL2 it is also now actually possible to run the linux "version" of ZFS within WSL2 (at least the linux ZFS code compiled under WSL2). People have gotten it to work, apparently without too many kludges. I'm not saying I would personally trust important data with this approach (I still use the linux VM and disk passthrough with samba sharing approach to "use" ZFS on Windows). But it's still pretty fascinating:

https://wsl.dev/wsl2-kernel-zfs/

**Comment by jittygitty** [comment]
@jim-collier I'm not an expert on WSL2 but it seems its basically a lightweight "Virtual Machine" running on their "Hyper-V". In that sense, if zfsonlinux native is more stable than openzfsonwindows then I'd think ZFS via "WSL2" may be more stable as well.

I would be very curious of a "performance" test between openzfsonwindows versus ZFS via WSL2 versus ZFS inside a full VM like in Virtualbox/VMware or even full Hyper-V instance not wsl2.
