### ISSUE TITLE
apt-get (dpkg) stuck at unpacking

### ISSUE THREAD

**Issue by MiracleXYZ** [microsoft/WSL#2721]
I was trying to install the package `texlive-fonts-extra` in WSL (Ubuntu 16.04) using 
```
sudo apt-get install texlive-fonts-extra
```
However, when apt-get finished downloading, the task stuck at 'unpacking' and didn't move in an hour. Even `Ctrl-C` and `Ctrl-D` couldn't help me. I had to kill the terminal and restart it.
After I typed 
```
sudo dpkg --configure -a
```
and tried to re-install the package, the same issue happened.

I googled it and found that this issue had happened in an older version of Ubuntu when there is a "slow USB drive". It might be a bug in WSL too.

**Comment by Biswa96** [comment]
Console output shows

>The following packages will be upgraded:
  gcc-7-base libgcc1 libstdc++6
3 upgraded, 214 newly installed, 0 to remove and 5 not upgraded.
Need to get 1195 MB of archives.
After this operation, 2521 MB of additional disk space will be used.

May be size of 1GB is the main problem.

**Comment by MiracleXYZ** [comment]
Exactly. The size of the package `texlive-fonts-extra` (alone) is over 200MB. It seems that the problem only appears in relatively big packages.

**Comment by sunilmut** [comment]
@MiracleXYZ - I was able to `sudo apt-get install texlive-fonts-extra` fine on Insider build 17004, although it took a long time. Which build of Windows are you running? Can you share the output of the `ver` Windows CMD?

**Comment by MiracleXYZ** [comment]
@sunilmut I am running Insider build 16299.64. The output of the `ver` Windows CMD is the following:

```
Microsoft Windows [Version 10.0.16299.64]
```

**Comment by DaJakerBoss** [comment]
Shoot it takes a long time for dpkg to unpack files about 50mb in size unless you're using a top-of-the-line SSD. Let it run overnight and see if patience will take its course.

**Comment by abulhol** [comment]
Having this problem with installing Kibana on Microsoft Windows [Version 10.0.18362.418].

**Comment by Juksefantomet** [comment]
Hello, adding information to this issue as it was directly related to "stuck at unpacking"

using:

Microsoft Windows [Version 10.0.19042.804]

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

WSL 1
```

performed the elevated powershell commands:

`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

`wsl --set-default-version 2`

as i was planning on using wsl 2.

realized the WSL target was still 1 on current install and due to work related tasks and time was unable to reinstall a WSL 2 environment.

-

proceeded at a later point with:

`sudo apt update && sudo apt upgrade -y`

heroku package got stuck on endless unpacking and bricked my ubuntu to the point where i had to use:

`sudo dpkg --remove --force-remove-reinstreq heroku`

eventually i reverted the elevated powershell command:

`wsl --set-default-version 2` to `wsl --set-default-version 1`

and i was able to reinstall heroku within a 1 minute run.

so this is more of an FYI, targeting WSL 2 and using WSL 1 be a contributing factor to this issue.
