### ISSUE TITLE
Read/ Write Speed is insanely slow.

### ISSUE THREAD

**Issue by gulshanmudgal** [Microsoft/WSL#2759]
Windows build number : Microsoft Windows [Version 10.0.16299.64]

i have uninstalled the legacy wsl app and installed the Ubuntu app from Microsoft Store.
Now the read write speed is pathetic.

it took my more than an hour to copy a folder using bash.

any Solution?

**Comment by gulshanmudgal** [comment]
File Size : 410 MB

**Comment by Biswa96** [comment]
Copy from where to where?

**Comment by therealkenc** [comment]
Is this your first time using WSL, or are you experiencing a slowdown relative to a previous install? If the latter, what was the previous Windows version? Also what does `find . -type f | wc` in the root of the source folder return?

**Comment by Biswa96** [comment]
@therealkenc I even see this issue when I copy files around ~150MB from `/mnt/c/folder` to `/home/user`. Though the delay is not so to cause any inconveniences. May be that's my HDD is slow somehow.

**Comment by therealkenc** [comment]
@Biswa96 - You're on the latest and have been around for a while, so it is safe to assume just the unfortunately titled #981, or #2626, and many many friends. Trying to determine here whether this is just more of the same or something else going on, because an hour for 400MB on a spindle seems excessive even by WSL standards. But maybe not if it is enough tiny files.

**Comment by therealkenc** [comment]
@Biswa96 - You're on the latest and have been around for a while, so it is safe to assume you are just seeing the unfortunately titled #981, or #2626, and many many friends. Trying to determine here whether this is just more of the same or something else going on, because an hour for 400MB on a spindle seems excessive even by WSL standards. But maybe not if it is enough tiny files.

**Comment by gulshanmudgal** [comment]
i was installing hadoop and it happened, may be it has something to do with the file size being over 200 MB, and if it is Microsoft should acknowledge and provide a solution, and May be it is because of UWP, because before i installed this UWP Ubuntu app, since then only i started facing this issue. In my experience UWP are pathetic at accessing local files. UWP + Virtualization might be the cause for this plight.

**Comment by therealkenc** [comment]
> In my experience UWP are pathetic at accessing local files. UWP + Virtualization might be the cause for this plight.

No that's not it. Universal Windows Platform isn't doing anything when you install hadoop, and there is no virtualization (of the UWP variety or otherwise) involved with WSL. I suppose we should start with your repro steps exactly. This is starting to sound a lot like dupe #2721.

You can also try as a baseline:

```
cd ~
mkdir tmp && cd tmp
dd if=/dev/zero bs=1M count=200 | tr '\000' '\001' > file1.bin
time cp file1.bin file2.bin
```

That returns in `0m0.174s` real on my machine.

**Comment by gulshanmudgal** [comment]
real    0m0.500s
user    0m0.000s
sys     0m0.219s

**Comment by gulshanmudgal** [comment]
i got this

**Comment by gulshanmudgal** [comment]
what it means? need-repro?

**Comment by therealkenc** [comment]
It means a set of steps to reproduce your case. Your post says "it took my more than an hour to copy a folder" but you just copied 200MiB in half a second above. So:
```
$ # ...the steps
$ # ...to make
$ # ...some_commnd 
$ # ...run slowly
$ time come_command some_args
```

**Comment by therealkenc** [comment]
Calling this dupe #2721 or #981 (or take your pick) for lack of repro. Academic. If one or both of those flip to fixed and your scenario (whatever it might be) is still slow, do open a new entry following the [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md).
