### ISSUE TITLE
[Blender] unable to start process, 

### ISSUE THREAD

**Issue by cenit** [Microsoft/WSL#2764]
* Windows Build 16299.125
* Trying to launch blender (for debugging purposes on problems I am seeing on a real Ubuntu machine)
```
$ blender
connect failed: No such file or directory
could not get a list of mounted filesystemts
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
Aborted (core dumped)
```
* What's wrong: blender does not start
* Strace: no more informations given by strace for this problem

seems related to #1006

**Comment by therealkenc** [comment]
> ... failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock()

_Is_ #1006 #486. You can follow the instructions [here](https://github.com/Microsoft/WSL/issues/648#issuecomment-324562271) and see how blender fares. If you run into display issues after getting over the PulseAudio blocker, try running Blender remotely from a Real Linux VM using llvmpipe (as opposed to Intel/NVIDIA/AMD DRM drivers) to VcXsrv on Windows first, so you have a baseline. Also include your use-case for running blender on WSL as opposed to Windows will help. Bonne chance.

**Comment by therealkenc** [comment]
Amusingly, blender does work (for some value of working). No one would _do that_, mind. But does paint. This is on 17063, but I'm pretty sure FCU 16299 would be okay too. OpenGL stuff has been okay since someone tried [OpenRTC2](https://github.com/Microsoft/WSL/issues/1209#issuecomment-254025980) back in October 2016.

![wsl-blender](https://user-images.githubusercontent.com/7049700/34199132-8eeef70e-e521-11e7-997b-0a633de6628e.png)

**Comment by cenit** [comment]
since it was just for debugging purposes when a linux machine was not available, I will not proceed with your suggestion. Honestly I don't want to install the full ubuntu desktop on WSL just for this task.
Thanks anyway for your help
