### ISSUE TITLE
Possible regression: permissions on DrvFs

### ISSUE THREAD

**Issue by heldchen** [Microsoft/WSL#2770]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17063

* What you're doing and what's happening:
```
me@devbox:~$ sudo su - someuser
someuser@devbox:~$ touch /mnt/d/foo.bar
someuser@devbox:~$ chmod 777 /mnt/d/foo.bar
chmod: changing permissions of '/mnt/d/foo.bar': Operation not permitted
someuser@devbox:~$ ls -al /mnt/d/foo.bar
-r-xr-xr-x 1 me me 0 Dec 20 15:54 /mnt/d/foo.bar
```

* What's wrong / what should be happening instead:
I think on previous builds the chmod operation did not throw an error, and files created from a different user were still read & writable for them.

starting with 17063, this seems to have changed. some web frameworks (f.e. Magento) try to chmod files and folders and are now throwing warnings/exceptions, and are unable to "change" the metadata of previously created files.

on the Windows NTFS permission side, the file permissions for such files & folders are not getting the Write right.

I'm not using the new `-o metadata` mount option.

**Comment by DarthSpock** [comment]
Did you read the [Release Notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063)? There have been major changes with the permissions.

**Comment by heldchen** [comment]
that's why "regression" and "I'm not using the new -o metadata mount option." :-)

**Comment by DarthSpock** [comment]
Ah I see, I jumped the gun and didn't see that last part.

**Comment by jstarks** [comment]
Thanks for the prompt feedback, and I'm sorry we broke your setup! This was an intentional breaking change to better align drvfs with Linux filesystem behavior. In general, only the owner (or root) can change the mode on a file, and with the new drvfs code the default owner on your files is the same as your distro's default user.

For now, you can override this default user by unmounting and remounting the drvfs instances using the flags mentioned in the release notes. You can also try turning on the metadata option and chowning the files properly.

We will be documenting an easier way to configure this soon.

However, we don't currently have a way to go back to the old behavior. If the new options aren't sufficient for common scenarios, we can consider a mount option to provide the pre-17063 behavior. What do you think?

**Comment by smuuf** [comment]
I was looking all over the internet to find anything about exactly this *(after my setup was broken after installing 17063)*. I'm glad I found this thread, since now I know I'm not the only one having issues with permissions.

I couldn't find anything about this new thing anywhere else. I also *did* read the WSL release notes, but **no change in the default behaviour was apparent from the text**.

> DrvFs supports additional Linux metadata. [...] This is disabled by default.

At least not from what I understood. Did I get that wrong, or is this issue *not* what the citation refers to?

**Comment by sunilmut** [comment]
I will mark this as "discussion" unless a compelling reason comes back to support the old behavior.

**Comment by DarthSpock** [comment]
@smuuf, upgrade to 17074 based on this from the release notes: 

> Fixed storage format of DrvFs metadata [GH 2777] 

enable the `- o` and use `chown` to fix your setup.

**Comment by therealkenc** [comment]
Ran course, in the sense this is now (as of April Update) by-design.
