### ISSUE TITLE
WSL slow text buffer

### ISSUE THREAD

**Issue by jkroepke** [microsoft/WSL#2772]
Hi there,

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have a HiDPI Desktop Environment on UHD with 125% Scale.

If I', using a termial multiplexer like tmux and I run commands which give huge text output, like dmesg (dmesg | wc -l -> 3951), the output lags totally.

On client systems like mac os or cygwin (on same machine), the output buffering is working fine.

I got this behavior on all terminal windows sizes.

Video: https://streamable.com/4e2i3

* What's wrong / what should be happening instead:

No lags.

**Comment by NielsH** [comment]
I have the same issue, sometimes the delay in tmux with a lot of text causes it to totally freeze and take minutes to recover. Sometimes I just close the connection completely and re-attach to tmux which is faster.

Microsoft Windows [Version 10.0.16299.192]

Fwiw, I don't have a HiDPI setup, but instead the default settings.

**Comment by NZSmartie** [comment]
Same here using GNU Screen on Ubuntu 16.04.3 LTS, Windows 10 Pro 16299.192.

**Comment by jkroepke** [comment]
Maybe unrelated to WSL. I can verify this issue with update 1803 and native ssh.exe from windows.

**Comment by DarthSpock** [comment]
This is an issue that should be resolved in Skip-Ahead builds and should be filed under the [Console ](https://github.com/Microsoft/Console) tracker

**Comment by zadjii-msft** [comment]
@DarthSpock wait is it really already fixed in skip ahead? I don't think this is related to that other high-dpi font issue from a little bit back, considering the buffer updates w/o tmux at the normal speed, but tmux appears buffered.

(I'm not really suggesting that I have a solution to this problem, or have any idea what might be causing it. i just don't think it's Microsoft/console#143)

**Comment by DarthSpock** [comment]
I was thinking the pseudo console interop would have fixed this but I'm
unable to confirm

**Comment by mqudsi** [comment]
I'm pretty sure this isn't a bug with WSL but rather a timing issue that causes poor IO handling involving `select(2)` and similar to handle pending IO activity.

[We had a similar situation with fish](https://github.com/fish-shell/fish-shell/issues/4921), where commands outputting a wall of text would cause the terminal to basically freeze and ctrl-c events wouldn't be posted until already-started IO operations had come to a halt. However, [changing up how we handled IO readiness](https://github.com/fish-shell/fish-shell/pull/5219) and took care of the problem and then some, and now WSL really flies under fish (even faster than bash, subjectively speaking). (All tested exclusively under hi-dpi displays).

The problem here is piling on potentially buggy IO handling, one on top of the other. You have conemu's handling of IO itself (which should be straightforward with one or two fds to read from max), but then on top of that you have the terminal multiplexer, the shell within the multiplexer, the command being executed inside the shell, etc.

(SSH is the same problem)

**Comment by ryanmortier** [comment]
I have two screens, a 4k and a 1080 screen. When the console is on the 1080p monitor, output is fast. When  the console is on my 4k monitor, output is slow.

**Comment by ltltlt** [comment]
Same problem here, 2k screen, the output is too slow within tmux. Any updates?

**Comment by Scarecrow0** [comment]
Met the same issue, it makes the Windows Terminal also slow down.

**Comment by NielsH** [comment]
Intestingly to note for me is that when a large amount of text has to be shown by the terminal (i.e. i `cat /very/large/textfile` ) where it would take minutes to catch up, I can usually speed it up by making the windows terminal application window very small. Then after a few seconds I can maximize it again and continue. 

Another thing I have noticed, however not objectively measured so it might be a placebo affect of sorts... is that when someone else using a macbook (which may not be relevant) is connected to my tmux (that I am connected to on a server over SSH), I seem to have less issues with the slow text.
