### ISSUE TITLE
Installation of azure-cli 'hangs' on unpacking

### ISSUE THREAD

**Issue by stefanstranger** [Microsoft/WSL#2775]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.125]
* What you're doing and what's happening:  
When I try to update the azure-cli (2.0.22-1) to the latest version on Ubuntu WSL the unpacking part of the installation seems to hang. See screenshot [here.](https://t.co/A5XV0lpNdo)

I followed the steps to install azure-cli described [here.](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#install-on-windows)

In the end after retrying multiple times I used the [manual installation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#a-namelinuxinstall-on-linux-without-a-package-manager) of the azure-cli. 

* What's wrong / what should be happening instead: 
azure-cli should be installed.

**Comment by rajattrt** [comment]
I too encountered this issue. 
Windows build: 16299.98

**Comment by rajattrt** [comment]
applying following changes resolved the issues for me.
```
sudo apt-get update
sudo apt-get install -y libssl-dev libffi-dev
sudo apt-get install -y python-dev
```

**Comment by hemake** [comment]
This issue persist on lxss (Windows susb system for linux with Ubuntu 16.04.3) I think partly the issue is Ubuntu by default uses python3.5 there, and has limited initial packages installed, I resolved it installing it using the python3-pip installer.

I think regardless what package missing bigger issue is it should not hang at "unpacking line" but should fail explicitly if possible stating what package is missing.  Installation script needs proper error checking.

**Comment by bityob** [comment]
@rajattrt 

> applying following changes resolved the issues for me.

Thanks, it helped me too.

**Comment by erik-wramner** [comment]
I had the same problem and the workaround didn't help. I tried at least eight times and rebooted Windows as well, just in case. Finally I left the process for about an hour and the upgrade actually succeeded!

**Comment by cmeiklejohn** [comment]
I'm running into this problem as well, workaround did not resolve it for me.

```
$ sudo apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/41.6 MB of archives.
After this operation, 337 MB of additional disk space will be used.
Selecting previously unselected package azure-cli.
(Reading database ... 34339 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.0.43-1~xenial_all.deb ...
Unpacking azure-cli (2.0.43-1~xenial) ...
dpkg: error processing archive /var/cache/apt/archives/azure-cli_2.0.43-1~xenial_all.deb (--unpack):
 error setting timestamps of '/opt/az/lib/python3.6/site-packages/azure/mgmt/network/v2015_06_15/models/__pycache__/application_gateway_ssl_certificate_py3.cpython-36.pyc.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/azure-cli_2.0.43-1~xenial_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by hemake** [comment]
There are actually couple ways this gets resolved, tried on both Ubuntu 16.04 and 18.04 successfully.

Installing following dependencies will help:
`python-dev, build-essential, libffi-dev, libssl-dev`

Try installing azure-cli again as usual, sometimes waiting longer than usual at unpacking.... might treat you to a successful installation :)

If it does not help use following script:
`curl -L https://aka.ms/InstallAzureCli | bash`

This will use a complete az install and use a separate python environment that gets installed from this location: /home/{user}/lib/azure-cli/bin/python

**Comment by nickstenning** [comment]
I see that this issue has been closed, but the issue definitely persists:

```
~ $ sudo apt install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  azure-cli
1 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
1 not fully installed or removed.
Need to get 0 B/42.3 MB of archives.
After this operation, 353 MB of additional disk space will be used.
(Reading database ... 29853 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.0.45-1~bionic_all.deb ...
Unpacking azure-cli (2.0.45-1~bionic) over (2.0.45-1~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/azure-cli_2.0.45-1~bionic_all.deb (--unpack): unable to open '/opt/az/bin/2to3-3.6.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system
                                                                                         Errors were encountered while processing:
 /var/cache/apt/archives/azure-cli_2.0.45-1~bionic_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
command sudo apt install azure-cli  16.05s user 227.66s system 31% cpu 106M memory 13:05.90 total
```

The fact that it's an apparent I/O error that aborts installation would suggest to me that this isn't a problem with the `azure-cli` package per se, but I could well have misunderstood what's going on here.

Additional debugging data:

| | |
| - | - |
| `uname -a` | `Linux redacted 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux` |
| WSL version | Ubuntu, 1804.2018.817.0 |
| Windows version | Windows 10 Enterprise, build 17134.228 |

**Comment by sirredbeard** [comment]
I found this issue when $ sudo apt-get install azure-cli kept hanging on install at 16% on Debian. The workaround did not help. 

![capture](https://user-images.githubusercontent.com/33820650/45784840-3f3db800-bc38-11e8-9626-4bc166fa19b0.PNG)

**Comment by sirredbeard** [comment]
I take it back. I let it sit for a long time, came back, and it had finally worked.

I still opened an issue over at [azure-cli ](https://github.com/Azure/azure-cli/issues/7374) regarding the problem.

**Comment by cmeiklejohn** [comment]
Mine is also stuck at 16% -- any advice other than sitting and waiting?

**Comment by sirredbeard** [comment]
@cmeiklejohn 

No, not really.

The real "issue" here for most people is lack of an ability to check the install progress. It does work, it just takes a really long time after appearing stuck, I _think_ mostly because the .deb is just the install script wrapped in a .deb, not a true package. Plus the install script is download and installing it's own python 3.6 environment for azure in /opt/.

And then a couple other people who arrive here have an actual install problem and that points to a second issue: Poor error reporting.

Those are two separate issues.

Of course without these, it's hard to tell which problem anyone is having is which.

It occurred to me there may be a way to check the progress of the install, to see if it is still working or stalled, by monitoring the processes using ps, using a tool to monitor system load, or even peaking into the processes itself using something like Dtrace.

**Comment by hemake** [comment]
I think install script should be way more verbose like saying downloading and installing each sub package instead wrapping everything inside unpacking step. When I do various installs time to time in different machines I get bitten by this many times. 

As a workaround you can enable a progress under Ubuntu for "apt" command specifically but still it stays long time at 16% or 17% waiting for close to 1 hour, depending on your system of course.

@sirredbeard stated what happens if there is actually an error on the installation and you'll be sitting for several hours in dismay (has already happened couple times for me), onus should not be on the user to check the status going into depths like this.

I will request the azure-cli script to be updated as this process should be painless as possible to customers, generally is the one of the first steps required to enable azure-cli for Ubuntu/debian, also this is not an issue with WSL rather how the installation script is written.

**Comment by jomach** [comment]
Same issue. 
on my dockerfile I have:
RUN curl -L https://aka.ms/InstallAzureCLIDeb | sudo bash 

this hangs

**Comment by spyro2000** [comment]
Same problem on apt-get upgrade for me with azure-cli (2.13.0-1~bionic). Hangs for more than 2 hours now.

**Comment by Mon-ius** [comment]
Same problem on Codespace.  `Unpacking azure-cli (2.23.0-1~focal) over (2.22.1-1~focal) ...`

**Comment by thargy** [comment]
Same problem on Debian, eventually got (after leaving ages):
```bash
Unpacking azure-cli (2.26.1-1~buster) over (2.26.1-1~buster) ...
dpkg: error processing archive /var/cache/apt/archives/azure-cli_2.26.1-1~buster_all.deb (--unpack):
 unable to open '/etc/bash_completion.d/azure-cli.dpkg-new': No such file or directory
dpkg: unrecoverable fatal error, aborting:
 unable to install updated status of 'azure-cli': No such file or directory
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

when using
```bash
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

(after trying everything else)

**Comment by vzabawski** [comment]
I got this issue when started upgrading packages on Ubuntu 18.04. Azure-cli repo is enaled, so I got:
```
Unpacking azure-cli (2.30.0-1~bionic) over (2.28.0-1~bionic) ...
```
It hagds for more than 30 minutes, progress bar is stuck.

**Comment by Hazmi35** [comment]
It still happens on GitHub Codespaces too. I've been running into this problem since when Codespaces was out for Private Beta. It still happens on the default image to this day.

**Comment by bison92** [comment]
Hi @therealkenc this issue is still occurring, why is it closed? Is there any other place where this issue is tracked? 

- Run latest ubuntu image with `docker run -it --entrypoint /bin/bash ubuntu`
- `apt update`
- `apt install -y curl`
- `curl -sL https://aka.ms/InstallAzureCLIDeb | bash`

I don't understand how is this issue closed without being resolved, nor pointing to some other issue where this problem resolution is tracked. It's been 5 years since reported and here I am having the same problem on a fresh system. This makes no sense.

**Comment by vzabawski** [comment]
@bison92 it's kind of expected behavior due to low io performance of WSL 1. For me, installation took 50 minutes.

**Comment by bison92** [comment]
I get that but this is still an issue. No matter where it comes from, or which component is responsible for it.

**At the very minimum**  the installation process should state this is a known problem, tell the user to wait and apologize.

**Comment by bugs84** [comment]
For me - helped me wait for a looong time (not sure, but more than half an hour and less than an hour). And then it was successfully installed.  I still believe, that this is a bug, which should be fixed! Awful :(

**Comment by melezhik** [comment]
@spacecat why this is closed? it is still unresolved ...
