### ISSUE TITLE
Console Improvements

### ISSUE THREAD

**Issue by GuerrillaCoder** [Microsoft/WSL#279]
I remember seeing in the original release video some mention of improving the console window but mine looks pretty much the same it always has.  

Is there any way to improve it so it is more like working in putty/xterm?  By this I mean things like easy copy/paste and mapping mouse clicks to the terminal.

I was using cygwin before and that had a nicer console window.  Can I use that safely with win bash?

**Comment by Dimasdanz** [comment]
Try to use [ConEmu](https://conemu.github.io/) and use the following as startup
`%windir%\system32\bash.exe ~ -cur_console:p`
The `-cur_console:p` is important as stated on [this issue](https://github.com/Maximus5/ConEmu/issues/651)

**Comment by bitcrazed** [comment]
Mouse support is already on our backlog for considering in a future version.

Regarding copy/paste, in Bash, we pass the keystrokes straight through to `/bin/bash` or whatever app is currently running. How Bash and *NIX tools handle modern keyboard commands, including CTRL + V is a [topic of much conversation](http://superuser.com/questions/421463/why-does-ctrl-v-not-paste-in-bash-linux-shell). We'll consider in the future.

**Comment by GuerrillaCoder** [comment]
Thanks.  Will give ConEmu a go.

@bitcrazed I meant the actual console window.  In putty you can select text and it automatically copies.  In console you need to select "Mark" and then select and then hit enter which is a little awkward.  Also to paste you need to right click and go "paste" whereas putty is just a right click.

**Comment by benhillis** [comment]
@GuerrillaCoder Have you tried [quick edit mode](http://www.tekrevue.com/tip/boost-productivity-quickedit-mode-windows-command-prompt/) in cmd?

**Comment by GuerrillaCoder** [comment]
@benhillis I didn't know about that one, thanks!  Enabling it now.

**Comment by bitcrazed** [comment]
@GuerrillaCoder Did quick-edit mode work for you?

**Comment by navidR** [comment]
Instead of conemu which does have quite childish/ridiculous design I prefer to see this two feature in command line window(which overall does have simple and good design):

1. Hide scroll bar (which is quite waste of space)
2. Unlimited buffer

Both gnome-terminal, KDE's konsole dos have these.

**Comment by mintty** [comment]
How about a real terminal application which provides a rich xterm-like feature set?

To make mintty interoperable with Bash on Windows, I see a few issues missing.
From a cygwin-based mintty, I can run cmd.exe but bash won't run from there, probably because of pty handling incompatibility.
Likely, mintty should be compiled natively in Ubuntu on Windows for that purpose, but as it uses a combination of native Windows and POSIX APIs, that would need to be supported in UoW.

**Comment by bitcrazed** [comment]
We'll be publishing a blog post highlighting the many improvements we've made to the Windows Console once some of the latest fixes bubble up into the insider releases.

We hear you regarding improvements to the console's VT-100/ANSI/XTerm support and for additional console app features and will talk more about our plans to address many of your suggestions and requests in the future.

**Comment by DanielGGordon** [comment]
So it's not possible to run this in Mintty? I was hoping to install `Zsh` with Powerline and get some nice prompt colors, but it doesn't seem like that's possible - unless I'm missing something. 

I don't think Windows should underestimate the power of a pretty prompt. Imagine if the next blog post had a picture of the Windows command line looking like [this](https://camo.githubusercontent.com/46b2bffaa556787cd434ffc8930520b8c9922d6e/687474703a2f2f692e696d6775722e636f6d2f6876694d4154432e706e67) or something. That would really catch people's attention.

**Comment by yantis** [comment]
@DanielGGordon You might want to try ConsoleZ https://github.com/cbucher/console
ZSH with Powerline works great with build 14342

Here is a screenshot of it runing on Windows 10 Build 14342 
![consolez](https://cloud.githubusercontent.com/assets/4214239/15212556/4a7a0fb8-17f6-11e6-8d5c-81c79ee0f0e1.PNG)

**Comment by midurad** [comment]
Unfortunately neither ConEmu, Console2 nor ConsoleZ seem to work fully with Bash on Windows (or Cygwin for that matter). Ctrl+/, arrow keys and other key bindings are not passed to bash when running under these. For me, when running Windows 10 Bash under ConsoleZ, the arrow keys don't work either. ConEmu had the same problem (although in that case the problem was solvable). Windows terminal isn't any better in that respect either.

The lack of a unified terminal emulator under Windows, especially with Windows 10 Bash being out is a real bummer. Microsoft has done a great work thus far with bringing Linux to Windows and improving the existing terminal but as @DanielGGordon has already pointed out, the power of a familiar, modern terminal cannot be underestimated. 

Also, a question to the Microsoft team. How about Clink? It makes interaction with cmd so much more bearable. It is open source. Why not make integrate it into cmd?

**Comment by aseering** [comment]
@midurad -- you mentioned gnome-terminal, etc; have you considered running one of them directly?  I know that's one of @fpqc 's favorite topics :-)

This seems to be a common discussion topic; there are a bunch of tickets about it.  I suspect that, as far as bug-tracking purposes go, the WSL team gets the point :-)  For us users figuring out what to do, maybe it's worth starting a [forum thread](http://wsl-forum.qztc.io/viewforum.php?f=12)?

**Comment by fpqc** [comment]
@aseering lol sniped.

@midurad I have like 5000 posts on this github where I tell someone how to set up rxvt-unicode-256color with vcXsrv

**Comment by Perlence** [comment]
I've managed to run [st](http://st.suckless.org/) on my WSL, turned out to be very nice! Thanks @aseering for cue.

![st on Windows 10](http://i.imgur.com/gckXJwz.png)

**Comment by fpqc** [comment]
@perlence wow, cute!  gonna try st now!

**Comment by aseering** [comment]
Thanks @Perlence !  I'll have to give that a try

**Comment by fpqc** [comment]
@aseering to set the default geometry in st, it's at the verrrrry bottom of st.c, hardcoded at the top of 

```main(int argc, char *argv[])
{
        uint cols = 140, rows = 22;

[...]}```

**Comment by Perlence** [comment]
@aseering @fpqc You can also set geometry via `-g` command-line option.

**Comment by fpqc** [comment]
@perlence yeah I saw that, but it's nice to set defaults too.

**Comment by dswartzen** [comment]
It would be nice if the PGUP and PGDN keys worked for paging up and down in the terminal with bash, like they do in the powershell or in an Xterm.

Right now the only way to scroll (that I've found) is to use the mouse and the scrollbar, or right click and enter "scroll" mode and then the page keys work.  That's too tedious. The idea is to scroll without taking your hands off the keyboard.  CTRL-B, CTRL-F like in vim would also be acceptable.

The cut and paste with the mouse is clunky but works well enough for now.

**Comment by fpqc** [comment]
@dswartzen you can manually change your TERM= variable to one that is more correct (since the Windows console does not implement lots of xterm's features).  I think someone on this github repo has found a good terminfo setting that is included in the terminfo database and represents the true functionset of the Win10 console.  

Ideally, someone could throw a proper terminfo for bash.exe and the Windows console (both the wrapper and the Windows console impose their own limitations (for example, stripping of color codes and mouse escape sequences is done at the wrapper level, not the console level).

**Comment by dswartzen** [comment]
@fpqc I've tried most of the TERM variants in /lib/terminfo to try to get one where the page keys work, but I'm not having any luck.  Please post in here if you find out which TERM is the best to use in the windows console.

The only way I could get a full size block cursor in vim was to do a **set term=ansi** in .vimrc

**Comment by mintty** [comment]
Mintty as a terminal for WSL is now available with an installer: https://github.com/mintty/wsltty

**Comment by be5invis** [comment]
Please, implement the pty api in win32, so that we will no longer need to hook the programs.

**Comment by fpqc** [comment]
@be5invis this may be coming. Read all of #111

**Comment by wolf99** [comment]
Would be cool if there was some way of scrolling within the console without having to resort to the mouse. Ubuntu bash uses `Shift+PageUp/Down` AFAIK.

**Comment by shaunuk** [comment]
Found a work around :)

run cmd first then type bash....

**Comment by bonki** [comment]
@Perlence Can you give a hint on how to get st (/X) running?

**Comment by Perlence** [comment]
@bonki I built st from source, then I installed [VcXsrv](https://sourceforge.net/projects/vcxsrv/) and set `DISPLAY` environment variable in WSL to that of VcXsrv. Everything worked pretty smooth, I didn't have to do any workarounds.

**Comment by bonki** [comment]
@Perlence Thanks for the fast reply, works perfectly! I think I'll stick to `wsltty` though for the time being until I need X anyway.

**Comment by dman777** [comment]
Is there a way to enable quick edit mode?

**Comment by bitcrazed** [comment]
Closing this issue since:
1. We've delivered most of these asks over the last few Win10 releases, including 24-bit color support, improved Console color palette, mouse and Copy & Paste support in Linux Console instances, etc.
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by gitcnd** [comment]
For peeps struggling with keys not working (e.g. PgUp PgDn etc) - This totally fixed the problem for me (WSL on Windows 11 using Ubuntu):

https://sourceforge.net/projects/ultimate-bashrc/files/

(note that I attempted to copy a keymap first, /etc/default/us.map.gz, which didn't fix anything - not sure if this .bashrc fixed the problem, or, it caused my keymap fix to fix it)

Probably it will just fix it though.
