### ISSUE TITLE
Options to change console text cursor

### ISSUE THREAD

**Issue by musm** [Microsoft/WSL#280]
For some reason I strongly dislike the underline cursor. Adding other cursors like a straight line, blinking straight line, block would be of value. 

See e.g. the settings conemu has for this
![image](https://cloud.githubusercontent.com/assets/4319522/14851794/3b57679e-0c50-11e6-90a8-1b87a29d5fe8.png)

**Comment by bitcrazed** [comment]
Thanks for your suggestion. Added to the backlog. Will consider in the future.

**Comment by Erhie** [comment]
Norton AntiVirus don't let install Conemu (WS.Reputation.1)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This ask is now on our feature backlog and will be considered for a future release
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
