### ISSUE TITLE
bash.exe, wsl.exe & ubuntu.exe doesn't load/read ~/.bashrc

### ISSUE THREAD

**Issue by zmni** [Microsoft/WSL#2816]
1. **Version**: `Microsoft Windows [Version 10.0.16299.192]`

2. **Steps to reproduce**:
    1. From inside WSL
        1. Install [nvm](https://github.com/creationix/nvm/blob/master/README.md#installation) (or any programs/scripts source from `.bashrc`).
        2. Install node.
        3. Install global any node cli module.
        4. Make sure everything works.
    2. Open Cmd/Powershell
        1. Run `bash.exe -c 'which nvm'` or `bash.exe -c 'which anything-installed-via-nvm-or-npm-global'`.
        2. Same as above for `wsl.exe` and `ubuntu.exe run`.
3. **Terminal output**: Nothing.
4. **Expected output**: Should output binary path. Can be executed.
5. My also apply to other distros and shells.

Is this intentional? If not, is there any workaround to this problem? If anyone knows, please share. Thanks.

* [My .bashrc on gist](https://gist.github.com/zmni/3d0685a478aed5d3f79a3accbe5edbcf).

**Comment by therealkenc** [comment]
```
C:\>bash.exe -ic "which nvm"
/home/ken/.nvm
```

**Comment by therealkenc** [comment]
`which nvm` returns empty inside WSL and Real Linux, which I never noticed before. This is with a standard `nvm setup` natch. I've never looked into how `nvm` does it's thing. Curious.

It is linux-behaviour, but I'd need to look closer to find out why `which` behaves  that way. But in any case, if you want to load `.bashrc` you want:
```
bash -ic nvm    # or -ic <whatever>
```

**Comment by therealkenc** [comment]
[This](https://github.com/creationix/nvm/issues/540)

Safer to close now.

**Comment by zmni** [comment]
Oh, I see. This makes me actually read the manual of the linux shell behavior, so many years still doesn't know the basic. And now, I just hope that `wsl.exe` or `distro.exe run` can also execute command with `-i` or `-l`.

Thanks, closing this now.

**Comment by darthmall** [comment]
According to the [documentation](https://docs.microsoft.com/en-us/windows/wsl/interop) `bash.exe` is deprecated, but when I run `wsl -ic` I get an error from bash telling me that `-` is in an invalid option. As far as I can tell, `wsl` is not parsing `~/.bashrc` because I have modified my `PATH` to look for executables in `~/gems/bin` but they're not being found. If I run `bash -ic bundle` it works, but `wsl -ic bundle` does not.

**Comment by therealkenc** [comment]
> As far as I can tell, wsl is not parsing ~/.bashrc

Put an `echo hello` as the first line of your `.bashrc` and run `wsl.exe` with no parameters.

> ~/gems/bin

`/home/you/gems/bin`

**Comment by darthmall** [comment]
I added different echo statements to both `~/.bashrc` and `~/.bash_profile`. The results were:

- `bash.exe`: parsed bash_profile
- `wsl.exe`: parsed bash_profile
- `bash.exe -i`: parsed bashrc
- `wsl.exe -i`: gave me an error `/bin/bash: -c: option requires an argument`

So I moved the `GEM_HOME` and `PATH` configuration into `~/.bash_profile` and then tested `which bundle`, which should print `/home/evan/gems/bin/bundle`. None of these commands found `bundle` on my path: `bash which bundle`, `wsl which bundle`, `bash -i which bundle`. Because of the `echo` statements at the top of both `~/.bashrc` and `~/.bash_profile` I could see that `bash -i which bundle` was parsing `~/.bashrc`, which suggests to me that `wsl which bundle` and `bash which bundle` are parsing neither `~/.bashrc` nor `~/.bash_profile`.

The best solution I've found so far is to place the `GEM_HOME` and `PATH` definitions in `~/.bashrc` and to use `bash.exe -i` instead of `wsl.exe` when I need to run ruby scripts. Obviously with `bash.exe` being deprecated, this seems less than ideal.

**Comment by benhillis** [comment]
wsl.exe launches your distribuitons default shell, and if you pass any additional arguments they will show up like this:

wsl.exe ls /
$SHELL -c "ls /"

If you want to run /bin/bash -ic you can accomplish that by doing:
wsl.exe /bin/bash -ic

**Comment by darthmall** [comment]
So there's no way to get `wsl.exe` to parse the shell config files directly, I have to do `bash -c "bash -ic ..."` if I want the command to work with any modifications I've made to the environment?

**Comment by benhillis** [comment]
`wsl bash -ic ...` is sufficient.

**Comment by adamlwgriffiths** [comment]
Is this not the same as just running `bash -ic ...`, except worse?

**Comment by chrisdfrey** [comment]
Got tripped up by this; glad that `wsl bash -ic` works but it would be nice if there was an option for wsl to do something similar.

**Comment by therealkenc** [comment]
^--- Problematic because `bash` might not be your shell, and `bash` is not a `wsl.exe` thing. What `-ic` does, and even the existence of `-ic` as CLI parameters is up to `bash` or whatever shell is being spawned.

Powershell alias in your PS profile is probably what you want (or similar).

**Comment by praveenmak** [comment]
I might be asking a dumb question, but I am having this annoying this. 
I just want to find the wsl version I am running.

On Powershell. If I type .

wsl --version  
bash interprets it and throws this error.


`C:\WINDOWS\system32>wsl --version
/bin/bash: --: invalid option
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option`

**Comment by therealkenc** [comment]
> wsl --version
> bash interprets it and throws this error.

On your release (of Windows, whatever it is you don't say), `wsl.exe` just  tries to pass that string along to `/bin/bash` with tragic results. Try doing `/bin/bash -c --version` _inside_ WSL for fun. Same error.

A lack of `wsl.exe --version` was lamented [here](https://github.com/microsoft/WSL/issues/4045#issuecomment-493287990) too, in the context of more-recent Insiders.

**Comment by benhillis** [comment]
WSL is tied to your windows version. Adding a separate version option would not be helpful.
