### ISSUE TITLE
How can I change the resolution of the Generic pnp monitor?

### ISSUE THREAD

**Issue by zyong812** [Microsoft/WSL#2826]
I want to automate browser test on a windows, and the machine has no physical monitor. 

I use ssh to execute automation commands on this windows desktop remotely, and it uses the Generic pnp monitor by default.

The problem is the resolution of the Generic pnp monitor is too low, 1024x768, which is not enough to hold a browser for normal use, so many web elements are out of visible area and the tests can't run normally. We need at least 1920x1080 resolution to run tests correctly.

I have not find out how to change the resolution of Generic pnp monitor. Could you please help me?

Is there a way to change the resolution of Generic pnp monitor. to 1920x1080?

Or how can I solve my problem with windows in other ways?

**Comment by zyong812** [comment]
TightVNC can help a little, it can change the resolution to 1280x1024, but no larger

**Comment by therealkenc** [comment]
Closing since this was not a WSL question and there were no takers. If you are looking to automate browser tests you might want to check out [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) or [PhantomJS](http://phantomjs.org/), or ask in those communities what might best suit your scenario.
