### ISSUE TITLE
Stop breaking Virtualbox/other hypervisors

### ISSUE THREAD

**Issue by ow** [Microsoft/WSL#2850]
Windows Skip Ahead is silently breaking all hypervisors with confusing errors. I've tried getting attention on feedback hub, as have others, but this seems to be ignored. It's pretty frustrating, and I really hope this change is not rolled out. Here's the details:

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17074

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1.  Install Windows update RS4 (on skip ahead or fast branches with a TPM chip)
2.  Whoops, can't boot Virtualbox, Vagrant, VMWare or anything else anymore because "VT-x is disabled" somehow
3. Enable and disable VT-X doesn't fix it
4. Check system information, a partial version of Hyper-V has been enabled and is silently running. Hyper-V blocks all other hypervisors from booting. This is called "Windows Defender Credential Guard" or "Windows Defender Device Guard" — some sort of new feature in testing.
![ohnoes](https://user-images.githubusercontent.com/3075582/35045457-2de8b902-fb94-11e7-9a8d-e5eb05dd188c.jpg)
5. [Disable it using this set of instructions](https://docs.microsoft.com/en-us/windows/access-protection/credential-guard/credential-guard-manage) (requires multiple reboots) 
6.  Your VM should now boot (these steps took me about five hours of work to figure out, because there's no way to easily detect Hyper-V locking VT-x)

* What's wrong / what should be happening instead:

**What's wrong:** Should be able to consistently boot VMs without VT-x being locked, but Hyper-V being enabled silently creates confusing errors
**What should be happening:** VMs should boot.

**Comment by therealkenc** [comment]
The Windows Subsystem for Linux is not related to VMs or VT-x. Information about the Feedback Hub is [here](https://insider.windows.com/en-us/how-to-feedback/).

**Comment by ow** [comment]
I've tried it many times, and it's difficult to get attention for dev-based issues there, but hey, it was worth a shot.

**Comment by benhillis** [comment]
The WSL team is part of the larger group that owns the hypervisor and virtual machines.  @jstarks do you know anything about any current bugs in Insider builds that would be causing these issues?

**Comment by jstarks** [comment]
@ow, yeah, this is a painful situation. We are beginning to use the hypervisor for more and more security features in Windows, and the unfortunate result of this is that other hypervisors cannot run at the same time.

To partially mitigate this, we have released a [new API](https://docs.microsoft.com/en-us/virtualization/api/index) for using the Windows hypervisor to implement virtualization software. We are working directly to add support for this to qemu, and we are encouraging other hypervisor vendors to work on support for this as well.

In the meantime, it sounds like we could improve the diagnostics for this problem so that you don't have to waste 5 hours figuring out what's wrong. I'll forward your feedback along to the team.

**Comment by ow** [comment]
Ah, thanks @jstarks — I guess the problem is twofold (if my opinion can be useful here):

1. I didn't really opt for this feature, nor was I notified it was enabled! The latter might do the trick, but frankly, this is a pretty large change that flew under the radar? The documentation seems fairly limited on it, but I totally understand - just a thought.
2. As you say, it's difficult to find. This gets REALLY weird on Home builds because Hyper-V isn't supported, so it doesn't even show up as a thing you can remove in the settings. Even putting it there, with a warning about why it's ticked (or even greying it out) would be _so_ helpful to the end user. This was such a bizarre situation (I even installed Ubuntu to troubleshoot) because it's just not exposed _anywhere_ really.

Anyway, appreciate that it's on the radar! Thanks for chiming in.

**Comment by therealkenc** [comment]
That's informative about the teams being under the same umbrella; thanks for sharing. Makes the origin of that CUDA # 2422 survey post clearer. FWIW, last Spring I the made switch from running Windows as host and Linux as client to vice versa, because the Insiders VM breakage wasn't worth the trouble. [This was around the time I realised that's how a few of the VS Code guys roll.] If closing this was premature please re-open with no offence.

**Comment by jstarks** [comment]
Since this isn't really a WSL issue, I think we should keep it closed. But I'm happy to help direct any kind of kernel- or virtualization-related feedback to the right place.

**Comment by ow** [comment]
Hi again! This is a really frustrating thing that's making me consider switch to Ubuntu, and nobody is paying attention? It's broken the developer experience on WSL and I can't get anyone to listen to feedback; every update breaks the override I described at this point.

**Comment by jstarks** [comment]
@ow, I'm sorry this is so frustrating. It's tough to balance security and compatibility sometimes, and what's right for some users is not always right for others.

We've simplified the steps to turn this off, which should make this slightly less painful for you. There's a [blog entry](https://techcommunity.microsoft.com/t5/Windows-Insider-Program/Windows-Defender-System-Guard-Making-a-leap-forward-in-platform/td-p/167303) with instructions. Please give it a try and report back if you're still seeing problems. It should stick across OS upgrades, too.

You can also try using qemu, which now has upstream support for working with the in-box hypervisor.
