### ISSUE TITLE
DrvFs automount stopped working if "options={atime|noatime|relatime|strictatime|rw|ro}" present in wsl.conf

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#2927]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17093.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Enable metadata include default mount options.
``[automount]  ``
``enabled = true  ``
``options = "rw,noatime,uid=0,gid=0,metadata"  ``

Next launch, DrvFs will be not mounted.

* What's wrong / what should be happening instead:
DrvFs automount works fine.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
[lxcore.zip](https://github.com/Microsoft/WSL/files/1706004/lxcore.zip)

**Comment by SvenGroot** [comment]
Yes, that is the expected behavior. We pass the specified options directly to the fifth parameter of the `mount()` system call. This means that the options that the `mount` binary would normally parse into a flag are not supported.

If you want to explicitly specify those options, currently the only way to do so is to include every drive for which you want to do so in /etc/fstab.

**Comment by 0xbadfca11** [comment]
OK.
