### ISSUE TITLE
unshare failed: Invalid argument

### ISSUE THREAD

**Issue by tim241** [microsoft/WSL#2981]
* ```Microsoft Windows [Version 10.0.17107.1000]```

I'm trying to get `unshare -U` to work but whenever I try to execute that command I get:
```
tim@localhost:/$ unshare -U
unshare: unshare failed: Invalid argument
tim@localhost:/$
```
it seems like WSL doesn't have [User Namespaces](https://cateee.net/lkddb/web-lkddb/USER_NS.html) implemented(CONFIG_USER_NS)

[unshare.strace](https://gist.github.com/anonymous/3f8822b49d5ffa66db2db83c87666412)

**Comment by benhillis** [comment]
You are correct, we have not yet implemented user namespaces.

**Comment by therealkenc** [comment]
Ref `CLONE_NEWUSER` in #2242, which was closed (entirely reasonably) because Chrome's suid sandbox now works, but still needs `--disable-namespace-sandbox`.

@tim241 - if you've got another use case ("I'm trying to....") it is worth citing.

**Comment by tim241** [comment]
@therealkenc well, I replaced the chroot with Void linux(because I nwant to write [xbps package templates](https://github.com/voidlinux/void-packages/) and the [xbps-src](https://github.com/voidlinux/void-packages/blob/master/xbps-src) script needs [xbps-uunshare](https://github.com/voidlinux/xbps/tree/master/bin/xbps-uunshare) which is required for the way they build a package, so I /need/ the User Namespaces support. Here's an example of where it crashes:
```
> ~/void-packages ./xbps-src pkg linux
=> Using `/home/tim/void-packages/hostdir/binpkgs/wine-fixes' as local repository.
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
ERROR unshare (Invalid argument)
> ~/void-packages
```

**Comment by boypt** [comment]
`os.exec` in Go also calls `unshare(CLONE_NEWUSER)` , which also cause `Invalid argument` to all Go program calling subprocess.

hope user namespaces sooner got implimented .

**Comment by gusbemacbe** [comment]
@therealkenc, are you still working on it?

**Comment by therealkenc** [comment]
Wasn't the person "working on it". I take boypt at face value above, which would imply it was not implemented in WSL1. There is also #3282 which I suspect (but can't prove) is a side effect of chrome no longer supporting SUID sandbox (nor `--no-sandbox` last time I played with it, which was some time ago). 

`CLONE_ALLTHETHINGS` is fully functional in WSL2.

**Comment by gusbemacbe** [comment]
@therealkenc, strange, I used WSL2. My issue is similar to @tim241's.

**Comment by therealkenc** [comment]
Tim241 didn't have a repro so that post was glossed in January; this was before WSL2, and thus not too surprising a fail at the time. But as it happens I'm working on something in a space (almost) related Void Linux at the moment, so you've made me look on the lark. I was able to reproduce Tim's scenario on WSL2. There is an easier repro than the `./xbps-src` dance. Inside a Void chroot, just:

![image](https://user-images.githubusercontent.com/7049700/67841914-5cd58600-fab6-11e9-9c41-f7b87cc62d4a.png)

With the entirely predictable strace:
```
unshare(CLONE_NEWUSER)                  = -1 EPERM (Operation not permitted)
write(2, "unshare: ", 9unshare: )                = 9
write(2, "unshare failed", 14unshare failed)          = 14
write(2, ": Operation not permitted\n", 26: Operation not permitted
```

Which is nutty (at least in my somewhat sleep deprived state) because outside the chroot (back in plain 'ole Ubuntu):

![image](https://user-images.githubusercontent.com/7049700/67842430-657a8c00-fab7-11e9-9e79-dc8c7cad5ba7.png)

Which I already knew worked because I had done it before. At a loss right this moment to guess the variable. On first glance it is hard to finger-point WSL, because user namespaces is enabled in the kernel and, well, your know, works. But it is also near-impossible to finger-point Void userspace, because I can't think of anything that Void userspace could do to make the `unshare(2)` _fail_. It isn't performing the chroot proper (that makes no sense).

Reason will probably be obvious once it comes to me; if someone else doesn't beat me to it. Appreciate the submission.

**Comment by tim241** [comment]
@therealkenc 
I tested your repro on a native ubuntu 19.10 install (with a amd64 debian chroot)

![image](https://user-images.githubusercontent.com/18737914/67847065-84ead680-fb02-11e9-9397-1c1719d5ceef.png)

it seems like intended behavior :)
some more research led to this:
https://unix.stackexchange.com/questions/442996/what-rule-prevents-entering-a-user-namespace-from-inside-a-chroot

**Comment by gusbemacbe** [comment]
There is an article of void-packages repo, which suggests to modify chroot's permissions.

**Comment by therealkenc** [comment]
> it seems like intended behavior :)

I was afraid of that. Thanks.

**Comment by trajano** [comment]
This would be useful to automate https://github.com/microsoft/WSL/issues/5090#issuecomment-613945065 as per https://stackoverflow.com/questions/20553039/forcing-usermod-with-running-program/56338192#comment109450754_56338192
