### ISSUE TITLE
User questions - migrating from legacy WSL and interface with MOBAxterm

### ISSUE THREAD

**Issue by dorianps** [Microsoft/WSL#3022]
Hi all, and sorry if these are not strictly developer questions.

1. How can I migrate settings and files from the older WSL "Bash for Windows", and then delete completely the old distro to save space.

2. I use MOBAxterm to interface with WSL. This was very easy with the old WSL because "Bash for Windows" appears among the available shells. Nothing like that with the new WSL installed from Windows Store. Any idea how to get MOBAXterm to open the store-downloaded Ubuntu?

Thank you for any help.

**Comment by benhillis** [comment]
Copy whatever you want to save to one of your DrvFs volumes (/mnt/c etc).  Alternatively you could tar whatever you want to save.

Then run `wslconfig.exe /unregister Legacy` to remove the legacy distro.

**Comment by fpqc** [comment]
the old mobaxterm bash.exe support will work the same as soon as you set the new Windows Store distro as default with wslconfig.

**Comment by G-Rath** [comment]
@benhillis sorry for the necro, but I'm trying to get my WSL up to date (i.e getting off `bash.exe`/legacy), and the documentation seems a little sparse.

> Then run wslconfig.exe /unregister Legacy to remove the legacy distro.

So will that take care of "uninsalling" bash? I'm a little paranoid of "losing" disk space in the form of files relating to `Legacy` (i.e the command gets removed, w/o touching the actual "mnt", which I now can't access b/c `bash` is gone).

Are there any docs about removing & cleaning up Legacy, and switching to the "new WSL" (which I'm assuming is `wsl2`?) - I installed Bash for Windows back when it was... well Bash for Windows, and been using it like that ever since so I'm very much out of the loop :joy:

**Comment by jshields** [comment]
@G-Rath This sounds pretty hopeful, from the docs:
> To remove the legacy distro from your machine, run the following from a Command Line or PowerShell instance:
```
wsl --unregister Legacy
```
https://docs.microsoft.com/en-us/windows/wsl/install-legacy#uninstallingremoving-the-legacy-distro

Then if you are worried about the disk space:
> To forcefully delete your legacy WSL distro, delete the %localappdata%\lxss\ folder (and all it's sub-contents)
```
rm -Recurse $env:localappdata/lxss/
```
https://docs.microsoft.com/en-us/windows/wsl/install-legacy#manually-deleting-the-legacy-distro
