### ISSUE TITLE
17123: Zombie process survives killing init

### ISSUE THREAD

**Issue by heldchen** [Microsoft/WSL#3034]
**Your Windows build number:  (Type `ver` at a Windows Command Prompt)**
10.0.17123.1

**What you're doing and what's happening:**
for unknown reasons, the `redis-check-rdb` is hung and consumes an entire cpu core.
- killing in bash resulted the process turning into a zombie process assigned to pid 1 as parent
- survived killing its parent via bash
- killing via task manager does nothing
- survived init via task manager
- after killing init, the process now appears without parent in Process Explorer

![image](https://user-images.githubusercontent.com/299636/37555677-8887dce6-29eb-11e8-8f3e-e25a16b2a78f.png)

![image](https://user-images.githubusercontent.com/299636/37555707-047c21a4-29ec-11e8-991b-44e673566044.png)

**What's wrong / what should be happening instead:**
- the process should not survive killing init
- there should be a way to forcefully tear down / restart the wsl subsystem from within windows

**Strace of the failing command, if applicable:**

n/a (access denied)

**Comment by therealkenc** [comment]
> killing in bash resulted the process turning into a zombie process

No that process is quite alive. It is an orphan not a zombie.

> killing via task manager does nothing

That's the bug. For what it is worth, I get these too on a semi-regular basis basically since forever. I've never posted an issue because I don't have a repro. Unfortunately neither do you. Only way I've found out is a reboot.

> the process should not survive killing init

That much is correct, following [pid_namespace](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html) semantics:
> If the "init" process of a PID namespace terminates, the kernel
       terminates all of the processes in the namespace via a SIGKILL
       signal.  This behavior reflects the fact that the "init" process is
       essential for the correct operation of a PID namespace.

Which, I suspect WSL does admirably, but your process refuses to die so it has to go somewhere. The bug is it won't die.

> there should be a way to forcefully tear down / restart the wsl subsystem from within windows

I asked for that in (in 2016)[https://github.com/Microsoft/WSL/issues/1086#issuecomment-247525568]. At the time I had asked Russ for a `lxrun.exe /die-mf-die` switch offline in an email exchange. It was not forthcoming.

**Comment by benhillis** [comment]
Killing init via task manager will kill everything in the instance. There was a bug preventing it from working but it's fixed in current insider builds.

**Comment by heldchen** [comment]
this was on the latest fast insider build... are you referring to skipahead builds?

**Comment by therealkenc** [comment]
> Killing init via task manager will kill everything in the instance.

The problem is once in a while a WSL process will not respond to `SIGKILL`. If killing `init` via the task manager takes down its sub-processes "harder" than a `SIGKILL` (does it?), that is good news. But the question here isn't why `init` isn't taking down its children (even though it was framed that way). The question is why couldn't he kill the process in the first place. If he could kill the process, he wouldn't have resorted to trying to nuke `init` in the first place.

**Comment by heldchen** [comment]
> No that process is quite alive. It is an orphan not a zombie.

obviously, as it was draining an entire cpu core. yet it was marked as `z` in ps, therefore zombie :-)
as in your cases, only a reboot got rid of it. 

and I agree, not being able to kill the astray process is the problem. yet even under real linux this happens from time to time, yet I have never had a case where killing a parent wouldn't get rid of its zombified processes.

I mentioned init because in other issue discussion this was brought up as a way to "shut down wsl". a real shutdown option would really be useful now as background processes are allowed. even more so when some of them are unkillable...

**Comment by therealkenc** [comment]
> yet I have never had a case where killing a parent wouldn't get rid of its zombified processes.

That's a misinterpretation. A zombie process that becomes an orphan will get re-parented just like any other process on Real Linux. With the singular (one might say unusual) exception of PID 1 in a namespace. If your child zombie died, it died because the parent killed it; not because the parent died. The kernel takes no special action. Like [this](https://serverfault.com/questions/76263/how-to-kill-a-defunct-process-with-parent-1). They _normally_ they die of course, because a `SIGHUP` (contrast `SIGKILL`) trapped by the parent (say `bash`), which will turn around and euthanize the kids.

**Comment by benhillis** [comment]
Any other repro steps other than running "redis-check-rdb"? Seems like a deadlock to me.

**Comment by therealkenc** [comment]
> Any other repro steps other than running "redis-check-rdb"? 

All of the cases where it has happened to me have been seriously seriously ugly. Think: big unsupported packages running in gdb or strace, with kids and/or parents being killed, or dying violently on their own, or spinning, probably with a dozen system calls (some of them restartable some of them not) on the go. I've made quiet attempts in the past to come up with something tight you could actually use, but never succeeded. 😞

**Comment by therealkenc** [comment]
(only because it's the weekend) My question to Russ at the time was whether it is technically feasible to give WSL instances a big red button. So, say an hour or two from now I give you a nice tight repro extracted from `redis-check-rdp` that causes WSL to deadlock. You fix it, and there is 🎉 all around. But that doesn't address the next deadlock, which can't be fixed in the stable branch for another six months (even if we have a repro). The answer my question might well be: "no, a big red button is not really technically feasible" (with academically optional "because"). Wouldn't surprise me. But it is a reasonable question.

**Comment by heldchen** [comment]
> Any other repro steps other than running "redis-check-rdb"? 

unfortunately not - I wasn't even running this intentionally. it seems to be some kind of redis auto maintenance invoked by the default ubuntu `redis-server` package. running it manually does not trigger the issue.

**Comment by mqudsi** [comment]
Oh, I didn't know this was a bug. I can reproduce it at will with a combination of `RunInBash`, `fish`, and background jobs.

**Comment by heldchen** [comment]
> Any other repro steps other than running "redis-check-rdb"?

it took me some hours, but here's a fully contained, working repo for a zombie (process) apocalypse:

**prerequisites:**
```
apt-get install redis-server redis-tools
```

**environment**
```
root@devbox:/var/lib/redis# redis-server --version
Redis server v=4.0.1 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=6f05deda2aff122a
root@devbox:/var/lib/redis# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```
not sure if also reproducible on 16.04, to be honest, as xenial has version 3.0.6

**repo:**
```
# startup
sudo service redis-server start

# make redis autosave faster
redis-cli CONFIG SET SAVE "9 1 3 10 6 10000"

# fill in some large dummy data in a HSET
cat /init | gzip | redis-cli -x HSET 'ubuntu' 'wsl'

# watch Task Manager...

# stop service
sudo service redis-server stop

# remove persistence database to avoid garbage during next service start
sudo rm /var/lib/redis/dump.rdb

# optionally, rinse & repeat
```
here's the result after a few runs:
![image](https://user-images.githubusercontent.com/299636/37573938-2397c296-2b1d-11e8-86bb-d18aca762b28.png)

all those processes are unkillable from the get-go. only a reboot gets rid of them.

**Comment by heldchen** [comment]
the repo works with an unmodified Debian wsl out of the box.

@therealkenc can you remove the needs-repo tag? :)

**Comment by therealkenc** [comment]
Keep an eye on 3039.

**Comment by heldchen** [comment]
yeah I saw. and the issue is really with build 17123. went back to 17120 and everything runs smooth.

**Comment by dsolodow** [comment]
unfortunately still present in 17127.

**Comment by Brian-Perkins** [comment]
As Insider Builds continue to be released, it should be noted that the first build containing a fix for this internally is 17131, so until an Insider Build at or greater than that is released externally, this issue will continue to be present.

**Comment by dsolodow** [comment]
Thanks for the heads up. :) Hopefully the final for 1803 is that build or higher as it would **really** hurt to have a defect like this included in the release.

**Comment by heldchen** [comment]
thanks brian, looking forward to a future build

**Comment by vheathen** [comment]
Is there any known workaround for this exists? This bug makes impossible to use my laptop for development (I'm extensively using WSL and can't even start tests for my working project).

**Comment by mqudsi** [comment]
@vheathen roll back to 1720.

**Comment by dsolodow** [comment]
17133 just released; downloading and installing now to see if it fixes.

**Comment by DarthSpock** [comment]
Will there be Release Notes published for 17133?

**Comment by dsolodow** [comment]
Yes but it didn't mention this.

**Comment by heldchen** [comment]
this has been fixed in 17133

**Comment by sunilmut** [comment]
@DarthSpock - I have put the release notes for [17133](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17133-fast), but, at this time it is safe to assume that there won't be any WSL changes in the fast ring, until the fast ring merges with the skip ahead. That should happen anytime now.

**Comment by DarthSpock** [comment]
Just wanted to verify this issue was resolve before release of the stable version.

**Comment by mqudsi** [comment]
@sunilmt purely out of curiosity, what does MM stand for in this context?

**Comment by benhillis** [comment]
@mqudsi - Memory manager.

**Comment by dsolodow** [comment]
@DarthSpock - it's fixed in build 17133 which just hit the fast ring today. That makes it virtually certain that it will make it into the 1803 release of Windows 10.

**Comment by benhillis** [comment]
@dsolodow - There's no virtually, the fix is in 1803.

**Comment by dhedey** [comment]
Running 1809 (OS build 17763.134) I'm hitting an issue that appears very similar to this, it occurs at random a couple of times a day, and it is node which hangs and is unkillable in both WSL or Windows. A full computer (Windows) restart is required to remove this process.

In particular, in our use case node "mdc" spawns other node processes which spawn other processes, so it's quite a mess, but at some point, the root node process hangs or crashes (for as yet unclear reasons), and can then not be killed. The children become marked as <defunct> (zombies?) when using `ps -eaF`, and the hung process still continues to hold resources (such as open sockets).

An example hang
![image](https://user-images.githubusercontent.com/8008816/49463494-6eec6d00-f7f0-11e8-8f45-5f7cf240a1a4.png)

An example of the process tree (process with PID 214 is the node process which won't die):
![image](https://user-images.githubusercontent.com/8008816/49463519-8af00e80-f7f0-11e8-9490-813a664b5fd3.png)
_(This is after killing its original parent/s so that its PPID eventually changed to 1)_

Has any else seen this issue in versions post fix?

**Comment by karolyi** [comment]
I'm also getting these zombie processes with sublime text.

To me it seems that it has something to do with installing/removing files via any fast means (in my case, npm install), and sublime is trying to get a hold of those.

Just a hunch, this might be filesystem related. I've had other filesystem issues recently with WSL.
