### ISSUE TITLE
/etc/hosts file was overwritten by WSL at some point

### ISSUE THREAD

**Issue by ownmaster** [Microsoft/WSL#3043]
I had a hosts file with different content inside WSL for quite a long period of time (a few months at least, if not a year) and today I saw that it's content has been overwritten by `System32\drivers\etc\hosts`.
Now `/etc/hosts` starts with:
```
# This file is automatically generated by WSL based on the Windows hosts file:
# %WINDIR%\System32\drivers\etc\hosts. Modifications to this file will be overwritten.
```

I would like to understand:
1) Since I never added those lines manually, it must be added during some system update - if I remove these lines does it really mean, that the file inside WSL will not be overwritten?
2) Does WSL store a backup of this file somewhere, so I can restore it?
3) If I decide to enable automatic file generation, can I force this process somehow without system reboot?

Windows version: 10.0.16299.309

**Comment by benhillis** [comment]
The ability to disable automatic generation of the /etc/hosts file became available in build 17093  and is coming to stable builds of Windows in the next cumulative update which is due soon:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings

**Comment by ownmaster** [comment]
@benhillis so, I assume that the answer for 2 other questions is 'no': there is no backup by WSL and user can't trigger file update manually?

**Comment by benhillis** [comment]
No backup but the hosts file will be regenerated when a new instance is launched.

**Comment by ownmaster** [comment]
@benhillis seems that all existing WSL console sessions must be closed before new session can get an updated hosts file.

**Comment by benhillis** [comment]
@ownmaster - Correct, that is what I mean by a new instance.

**Comment by ajit555db** [comment]
Add the hosts as follows:

Open the following file in Notepad admin mode:
"C:\Windows\System32\drivers\etc\hosts"
# add your hosts this at the end of the file e.g. 

192.168.2.30 ubmaster
192.168.2.31 ubworker1
192.168.2.32 ubworker2
192.168.2.33 ubsrv

**Comment by CosmicCatnap** [comment]
> Add the hosts as follows:
> 
> Open the following file in Notepad admin mode:
> "C:\Windows\System32\drivers\etc\hosts"
> 
> # add your hosts this at the end of the file e.g.
> 192.168.2.30 ubmaster
> 192.168.2.31 ubworker1
> 192.168.2.32 ubworker2
> 192.168.2.33 ubsrv

The issue in question is not how to find a workaround, its why WSL thinks it should be responsible for a core linux feature and why it transparently erases changes in a way that is against virtually every use case for WSL I can think of.. You should be given a blank hosts file because this issue was self-inflicted.

**Comment by treysis** [comment]
Additionally to the windows hosts file, Ubuntu adds some own entries at the end of /etc/hosts. What is the basis for these lines? I want to add `::1 localhost` because for some reason Ubuntu's default decided that this would not be good. I disagree. It's the default on many systems, including Debian, Windows, and macOS.
