### ISSUE TITLE
Arrows keys (and more) do not work correctly in vi insert mode

### ISSUE THREAD

**Issue by eyalroth** [Microsoft/WSL#3076]
When I open `vi` on windows bash and go into insert mode, the arrows and the ins/del/home/end/pg up/down keys (and perhaps even more) seem to not work correctly. Many of them just cause a character to be typed, where others cause some weird deletion/cursor behavior.

![vimbash](https://user-images.githubusercontent.com/6641808/38244692-22e8f634-3744-11e8-950d-5fa317b0ffb3.png)

Note that these keys work fine with the default mode or with the visual mode.

**Windows build number:** 10.0.15063

I was unsure if this issue should be filed under the console issue tracker, and I ended up choosing the WSL since there was already a similar issue filed here before (#1154). The main difference between the issues is that I'm not using any kind of a custom console, but I'm running the native `bash` executable as is.

**Comment by DarthSpock** [comment]
You should file under the console issue tracker but since you're on 15063, the first thing you should always do is upgrade to the latest stable or Insiders. If that isn't possible, you can always try [WSLTTY](https://github.com/mintty/wsltty) which provides other work-arounds as well for current limitations with the console.

**Comment by eyalroth** [comment]
I actually just upgraded to 10.0.16299.125 and the problem persists. I guess I'll file the issue there.
