### ISSUE TITLE
WSL on Windows 8.1

### ISSUE THREAD

**Issue by nullpunkt5** [Microsoft/WSL#3115]
Windows 7 is now too old.  
Windows 10 has way too many `consumer` features that makes it highly undesirable for any technical user.
Also the new `control panel redesigns` are an absolute nightmare, the old ones are perfect.

Linux is a headache for home use, only work. 
Even if you spend hundreds of hours customizing your awesome-arch-setup, you still encounter problems upon problems. 
Home is not work.

Win8 has that bad reputation from that failed launch, but 8.1 fixes everything.

Windows 8.1 strikes the best balance on everything. 
Win 8.1 is the best OS I've ever used, period.  

The only thing missing from Win8.1 is, of course, WSL.

- How can WSL be ported to 8.1? What is required?
- Will this -ever- see the light of existence?

**Comment by sunilmut** [comment]
@nullpunkt5 - Thanks for the feedback. Unfortunately, the short answer to your question "WSL on Windows 8.1" is "no".  Windows 8.1 is not an active development branch. I wouldn't want to repeat things that are already available on the net, but, there are many reasons to be on Windows 10, beyond features, such as for security, as it is a fast moving target.

I can agree and understand some of your frustrations with the UI, but, the best way to address that is through the proper & right feedback channel.

I have marked the issue as "discussion" and left it open for the community to discuss away.

**Comment by v0idst4r** [comment]
If Linux is a headache for you why do you want WSL? I recently switched from SCU to Arch and I've never been happier. I don't know what problems your talking about, any problems are usually created by the unknowing user.

**Comment by ernierasta** [comment]
I second @v0idst4r comment. If you struggle with GNU/Linux, why you choose distribution for advanced users? Install Debian Testing, Ubuntu, Fedora, ... or stay with Win 8 and install Linux as VM in VirtualBox if you just need some specific functionality.

**Comment by benhillis** [comment]
Discussion has run it's course.

**Comment by lopugit** [comment]
damn bro if only 8.1 had WSL, SMB to OSX is completely broken on windows 10... smfh

**Comment by rolfen** [comment]
> If Linux is a headache for you why do you want WSL? I recently switched from SCU to Arch and I've never been happier. I don't know what problems your talking about, any problems are usually created by the unknowing user.

> I second @v0idst4r comment. If you struggle with GNU/Linux, why you choose distribution for advanced users? Install Debian Testing, Ubuntu, Fedora, ... or stay with Win 8 and install Linux as VM in VirtualBox if you just need some specific functionality.

Yes, I second these replies, the Linux system is very stable. It is perfect. In my 10+ years of using Linux, I have never encountered a single bug. The UI never froze, the system never crashed. I was never asked to reboot after an update. I have never had apt complain about obscure dependency problems.

I never had to waste time trying to find out why a part of the UI was frozen, why a panel had disappeared, why apt was refusing to install a package, why my machine needed 1 minute to boot, why X was suddenly refusing to start, why it was only detecting a single wifi networks, why my SD port was running at the lowest speed, for example.

Linux is perfect, obviously, but some fail to see this very obvious fact, they must be stupid.

**Comment by tiomno** [comment]
https://docs.microsoft.com/en-us/windows/wsl/faq#why-would-i-use-wsl-rather-than-linux-in-a-vm

**Why would I use WSL rather than Linux in a VM?**
WSL requires fewer resources (CPU, memory, and storage) than a full virtual machine. WSL also allows you to run Linux command-line tools and apps alongside your Windows command-line, desktop and store apps, and to access your Windows files from within Linux. This enables you to use Windows apps and Linux command-line tools on the same set of files if you wish.

**Comment by ZhenFTW** [comment]
Pleasee supportt itt. Upgrading to windows 10 makes my pc laggy. Buying a new one was impossible for me a student. Implementing it will be a great help for us developer. I know this might seem impossible but pleaseee

**Comment by ZhenFTW** [comment]
Please support it. I know microsoft is focus on windows 10. It makes sense since they care about the new customers. But care about the old customer that can't afford a new one. I really want to have this on my PC.

**Comment by mged** [comment]
windows 8.1 is not out of support if it come to timing, but even tho they ignore supporting windows 8.1 which is not END-OF-LIFE yet.

how scammy snarky company, I do really really really HATE microsoft so much!
im a windows 8.1 user and i cant use windows 10, my pc will be unuseable due to high cpu usage, ram usage. and disk usage. upgrading wont help i did maximise everything.

i dislike you so much! add WSL TO WINDOWS 8.1 or i will try to make one ( even if it cost me yeras! )

**Comment by akhilalekha** [comment]
I too am on Win 8.1 and I didn't upgrade when I had the chance. Now I'm looking for WSL for Win 8.1 :sob:

**Comment by palikacska** [comment]
> Windows 8.1 is not an active development branch.

That's why it's still mostly stable because it's not ruined with new poor, inexperienced-user-first redesigns that makes the life of every single power user much harder and harder with each update.
> there are many reasons to be on Windows 10

But there are much more, for a technical user, not to be on a feature branch of Windows 10. Especially stability, reliability and performance.
> beyond features, such as for security, as it is a fast moving target

Referring to security is a double edged sword here. When you add new features, you add new security holes as well. When you're only maintaining without adding features, you mostly add bug fixes and not security holes. So a maintenance version like Windows 8.1, Windows 10 LTSB and LTSC are much more stable & secure than any feature release of Windows 10. Those who use Windows for work don't want unnecessary changes and redesigns every half a year and we don't want to be free testers for Microsoft on the feature branch either.

> I can agree and understand some of your frustrations with the UI, but, the best way to address that is through the proper & right feedback channel.

On which the answers are mostly taken to idealist, non-techie product designers who tend to ignore them. Ruining Windows 10 user interface with dumbed down mobile-first design (while we're talking about a desktop OS) and crippled customizability and configurability haven't started now and didn't start in 2019, when this issue was created. It started much longer ago and it's not changing despite of many criticism and negative feedback of power users.

To @nullpunkt5, I recommend Windows 10 Enterprise 2019 LTSC. WSL can be installed on it [manually](https://4sysops.com/archives/install-subsystem-for-linux-in-windows-10-ltsc-and-server-2019/) and it's in maintenance state for 3 years so thus more stable than recent Windows 10 versions.

**Comment by JaservTECH** [comment]
i cant imagine when wsl on 8.1 , but end of support next january 23, so long win 8.1. i know 8.1 run perfectly , stable and does't use much more proc and ram, just like the old one win 7.

**Comment by NeoNomadVII** [comment]
I am a webmaster for 20 years now. I am not an expert on Linux, but I love it.Since I'm no Linux-pro, I use Ubuntu or Fedora. Usually I install Linux on my previous computer, like now with a dual-boot with Windows XP, which is for me, the best, most stable, with facilities for configuration version of windows. And I use currently windows 8.1 on my newest computer. I work like that for a long time, switching for one computer to another. 
I usually manage my network, my webserver on linux, but I'm used to write my code on windows. Because I don't like Emacs or Vim. 
Even if Linux is more and more easy to use, when I want to watch a movie or play a game, I prefer windows. Like many among you, I like win 8.1 (much better than vista or 7). Well once I managed to start on the desktop and not this useless diaporama, and with my "Start" button and the list of my apps.
Microsoft took a path that I hate. They try to make it more simple with win 10 and 11, but the result is not configurable, consumer-oriented. Why would I buy it? I will have to use windows 11 when I'll change my computer, and I have the feeling, that I will use linux a little more than today because that's what I do. 20 years ago, it was really hard for me to configure linux. the main reason was that I couldn't find the appropriate drivers. Some times I had no sound, sometimes samba didn't work well with windows (once again, I am not completly at ease on linux, but I improve each year). Today, there are no driver issues, no installation needed, and I love apt. So simple. So concrete and well thought. On the other side, we have windows with updates you don't know what's in it. And always, with windows you start with a nice computer, no app or service that is unnecessary or unwanted. And after 5 years, despite many re-installation supposed to be like your computer was all new...the starting process takes 5min instead of 1. And I find services that I don't know anything about, this is tedious. Checking all svchost.exe {args[]} to see what's what, if it's necessary or not. I am sure that one day I will finally make the leap and work only with linux.
If I had 3 screen exit, I am sure that I'll use one for a VM, the 2nd for my desktop, and the 3rd for my browser with a movie playing. I tried to install WSL and failed with error 0x8008060c. Eventually I found you, and wanted to tell you this.

**Comment by scottwozz333** [comment]
6 years on and this is still as true as the day you wrote it. WSL2 is the only reason I'm trapped on the pile of crap that is Win11. It is a mess in all other respects.
And yes I've tried running Ubuntu as main OS, it sucks. I tried it ten years ago, it sucked then. It still sucks. Total system crashes when my internet is disconnected or I plug in a second monitor is not 'user error', it's just a bad OS.
I hope some elite programmer out there finally ports WSL to Windows 8.1 and frees us all from this hell. It would be the perfect OS combination, period.
