### ISSUE TITLE
UNIX username

### ISSUE THREAD

**Issue by MatteStt** [Microsoft/WSL#3117]
Hey

Where can I get my own new UNIX username?

**Comment by bitcrazed** [comment]
Does this help?

https://docs.microsoft.com/en-us/windows/wsl/user-support

**Comment by rhmccullough** [comment]
https://docs.microsoft.com/en-us/windows/wsl/user-support
This document says
Because that elevated processes can change/damage system-wide settings and
data, and can access/modify protected files and folders, *AVOID* launching
elevated processes unless you absolutely have to - whether they're Windows
or Linux applications/tools/shells!

I don't consider this to be good advice.

Windows permissions often leave me with no control over files that I create.

I can only gain control over my own Windows files by multiple changes using
security tabs.

To avoid such problems, I always execute WSL/Ubuntu and Windows/Cygwin with
elevated privileges.


Richard H. McCullough
http://ContextKnowledgeSystems.org
What is your context?

**Comment by therealkenc** [comment]
> To avoid such problems, I always execute WSL/Ubuntu and Windows/Cygwin with
elevated privileges.

Free country; but for anyone else anyone landing here, do not do this. Seriously. There is no reason to run WSL elevated. There isn't even a justifiable reason reason to have Admin privileges attached to your Windows User account. Doing so defeats the purpose of privileges. The problems you are "avoiding" are likely circular. You run elevated, so files created aren't accessible as a normal user (possibly in locations like `C:\foo` where you need not be because it isn't 1998). So, you run elevated to avoid problems accessing them.

Looks like this is answered by Rich's link. Bonne chance.

**Comment by rhmccullough** [comment]
For anyone else reading this, I share files between users, between
partitions, between operating systems, between computers.
Windows always causes problems.

Richard H. McCullough
http://ContextKnowledgeSystems.org
What is your context?

**Comment by bitcrazed** [comment]
@rhmccullough: 

Launching an elevated process does not change the user account used to launch the process - it only adds admin privileges to your account's SID while launching the new process, after which the admin rights are stripped once more so any further (non-elevated) processes are not launched with admin rights.

As such, when you create a file within an elevated shell, that file's owner will be the account under which that file was created.

**Running every shell elevated is a very dangerous practice that we strongly recommend against.** Instead, we recommend running Cmd/PowerShell with non-elevated in general, and only running an elevated shell when you need to do something that requires elevation (e.g. modifying a system-wide setting or file) and then closing the elevated shell as soon as possible afterwards. This way, malicious or faulty code cannot easily access or corrupt sensitive system files and data.

If you share files between users, partitions, operating systems and computers, I think I now see why you appear to run into issues with file ownership: Different user account on different OS instances (even if they share the same name/email/etc.) are independent identities.

So a file "file.txt" created by "Rich" on one machine will be owned by a different identity to a file created by "Rich" on a different machine/OS instance/etc.

If you want to present a single identity across multiple machines/OS instances/etc., you'll need an AD (or compatible) LDAP Domain used by all machine/OS instances.

PS: I've RARELY had to do this, but I've deleted your latter comment which was inflammatory and unprofessional. Please keep discourse respectful in this repo.

**Comment by rhmccullough** [comment]
@bitcrazed:
<p>You seem to be saying a shell with administrative privileges does not have administrative privileges ???
<p>You recommend using Cmd/PowerShell, but I am using WSL/Ubuntu/bash or Windows/Cygwin/bash to build and execute programs. <p>My typical case: I create several users for different parts of a large project. I create files in another user's directory. I own the files, but Windows doesn't let me change the files that I own. Problems get worse with subdirectories. Elevated shells give me a convenient way to manage my programs without changing users.
<p>your PS: acknowledged

**Comment by bitcrazed** [comment]
## Re. Elevation:
Where do I say that?

The elevation rules apply to all Windows processes, but they're often something to pay more attention to with shells because shells are usually used to execute and launch other exe's.

A shell launched with elevated privileges runs with elevated privileges. And any app that elevated shell launches, also run with elevated privileges, which is why it's potentially dangerous to run all shells elevated.

If you run your Bash.exe/Wsl.exe elevated, the Linux processes they subsequently launch will also run with elevated privileges. Since you can install arbitrary apps which depend-upon and consume arbitrary packages, you'd better hope that none of them accidentally run `rm -rf /` or `diskpart.exe /s nuke_system_disk.txt` ;)

Note that `sudo` only governs Linux binaries' permissions within WSL: If the Linux shell (e.g. bash) is running without elevation, you won't be able to, for example, write to `/mnt/c/Program\ Files`. To do that, you'll need to run bash/wsl elevated … and hope nothing you run uses anything with a malicious/destructive payload.

## Re. Users:
If you create multiple local users on an OS instance (machine/dual-boot/VM/whatever), those users will be tied to that instance. If you want multiple users on several machines to access & share files/folders, it's HIGHLY recommended that they should all be domain users, and their machines, and the shared resources be housed on a domain-joined PC's/servers.

If you're creating & modifying Windows user accounts & permissions, you should be using PowerShell. [Here's an example](https://blogs.msdn.microsoft.com/johan/2008/10/01/powershell-editing-permissions-on-a-file-or-folder/) of how to 
1. Get the ACL's for a file/folder
2. Modify the permissions (e.g. granting rights to another user
3. Updating the file/folder's permissions)

This is all, however, completely beyond the scope of the originally posted issue. Happy to direct you to other resources if you'd like to send me email richturn at you know where .com.
