### ISSUE TITLE
Alt+Space doesn't prompt window menu

### ISSUE THREAD

**Issue by csholmq** [Microsoft/WSL#3128]
When in cmd.exe, or any other window, Alt+Space prompts the window menu which allows you to navigate settings and other alternatives without using the mouse. It also enables visual cues (what letter to type for each alternative). But upon entering the bash shell, Ctrl+Space this gets blocked. Just like Ctrl+A, Ctrl+F, etc.

Upon opening it by Alt+Space, the menu is browseable withy visible shortcuts present
![image](https://user-images.githubusercontent.com/1297882/39301538-aa3fdef0-494f-11e8-9a01-17110a4fe384.png)
Upon opening it by mouse click, the menu is still browseable but the visual cues are missing
![image](https://user-images.githubusercontent.com/1297882/39301503-90ebd788-494f-11e8-8a31-3c9fec692883.png)

Microsoft Windows [Version 10.0.16299.248]

**Comment by heldchen** [comment]
this is the default windows behavior and has nothing to do with WSL.

**Comment by csholmq** [comment]
Then why does it stop working as soon as you enter bash?

**Comment by heldchen** [comment]
because then you're in unix world - the keyboard keycodes alt+space might have a different meaning (as do quite a few other keycodes, btw)

**Comment by DarthSpock** [comment]
@csholmq This is an interop area of improvement for the Windows Console team. For future issues regarding the Windows Console, which WSL uses, file it here: https://github.com/Microsoft/Console

The Console team has done alot of work to improve this area but you'll find the best improvements in Skip-Ahead builds. Since you're on FCU, you'll need to wait until official release of SCU before being able to sign up for Skip-Ahead.

**Comment by csholmq** [comment]
Thank you for your answers. Makes sense.
