### ISSUE TITLE
Spring 2018 update: umask is always 0000 even after setting it to 22 in /etc/wsl.conf

### ISSUE THREAD

**Issue by nickjj** [Microsoft/WSL#3153]
* Your Windows build number:  Version 10.0.17134.1 (Windows 10 Pro, Spring 2018 edition)

* What you're doing and what's happening:

0. Edit `/etc/wsl.conf` to look like this:

```
[automount]
options = "metadata,umask=0022"
```

Sign out of Windows and sign back in (not Win+L but a full sign out).

1. `cd /mnt/c`
2. `mkdir foo`
3. `stat -c "%a %n" foo`
4. The above returns "777"
5. Running `umask` shows "0000"
6. Running `mount -l` shows `C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,metadata)`

* What's wrong / what should be happening instead:

I would expect newly created folders to have 755 permissions. I would also expect umask to be 0022 instead of 0000. For the record, setting umask=22 instead of umask=0022 produces the same issue.

Also files are created with 666 permissions even with fmask set to 0011 or 11.

* Workaround for now:

Setting the umask value in my `~/.bashrc` works but this feels dirty.

**Comment by therealkenc** [comment]
#352

**Comment by nickjj** [comment]
#352 is from 2 years ago well before DriveFS had umask options added to it through wsl.conf.

Microsoft released a few blog posts demonstrating wsl.conf and using this new umask feature, such as https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/. But since the feature doesn't work, it's really confusing.

**Comment by therealkenc** [comment]
Mount umask != process umask. You are experiencing the latter, and #352 is as unaddressed as it was two years ago. If on Real Linux™ you mount a filesystem with umask 0022 but have a bash process umask of 0000 it will behave the same as WSL.

Use `wsl.exe sudo /bin/login -f <user>` and your `mkdir` mode will behave as expected. It is only "confusing" because #352 is still broken, and is not related to the blog post you cited above.
