### ISSUE TITLE
Setting a custom root path to / inside of wsl.conf still winds up with an empty /mnt/c folder

### ISSUE THREAD

**Issue by nickjj** [Microsoft/WSL#3155]
* Your Windows build number:  Version 10.0.17134.1 (Windows 10 Pro, Spring 2018 edition)

* What you're doing and what's happening:

1. Edit `/etc/wsl.conf` to look like this:

```
[automount]
root = /
```

Sign out of Windows and sign back in (not Win+L but a full sign out) to ensure it takes effect.

1. `ls -la /mnt/c`

You'll notice that it's an empty folder.

* What's wrong / what should be happening instead:

I would expect that the `/mnt` folder would not exist, or at the very least `/mnt/c/` would not exist since the drive is mounted to `/c` now.

* Thoughts:

This may seem like a minor thing but in practice it could be potentially deadly. I almost blew up my primary SSD last night with an automated backup which backs up my files to `/mnt/f` (I forgot to update it using the new root mount path of `/f`).

Anyways, everything backed up to `/mnt/f` which is technically on my C drive now. I woke up to 1GB free. If that folder didn't exist (as expected) the backup would have failed to run.

**Comment by benhillis** [comment]
This is by-design.  The /mnt/c directory is the mount point.  Cleaning these up would be problematic because let's say you changed your DrvFs drives to mount at /win/* and started putting files under /mnt/c which is now just a real directory.  If we deleted these directories we could potentially be causing user data loss.  I suggest after changing the automount root directory, that you clean these up manually.

**Comment by nickjj** [comment]
Ok thanks, so they are safe to delete. There's a bunch of them for each drive that was previously mounted.
