### ISSUE TITLE
PHP chmod(): Operation not permitted 

### ISSUE THREAD

**Issue by mikevoid101** [Microsoft/WSL#3172]
Hello,

I am using ubuntu to work on projects that are written in PHP, I have a basic LAMP stack and everything worked well ever since I started using WSL until my last Windows update where PHP keeps getting hit by permission restrictions for things like chmod, creating cache folders and files etc.

My last feature update is version 1803 and my last quality update is KB4011253.

**Comment by DarthSpock** [comment]
If your permission issues are on Windows directories, did you enable the Linux metdata feature in `wsl.conf`? 
I suggest looking at https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/ and https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/ and see if these are useful to you. Also something you might want to consider: https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/

**Comment by mikevoid101** [comment]
@DarthSpock thank you for the links! I will try them out and see if the issues persist.

**Comment by boan2010** [comment]
Worked for me, thanks :-)
```
sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata
```

https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/

**Comment by zoiosilva** [comment]
Maybe related to this issue: https://drupal.stackexchange.com/questions/273287/phpunit-loadtest-fail-due-to-chmod-operation-not-permitted

**Comment by pixxelfactory** [comment]
Still does not work, what we did so far:
- install ubuntu
- install a lamp stack
- creating a virtualserver pointing to a windows-directory, wich resides on drive f (no, var/www or other wsl-directories are NOT an option, since we need to modify / create ecc files directly from windows)
- installed Joomla
- tried to install addons or other stuff
- get a delete not permitted error, found out that it is due to a chmod operation performed before unlinking files within the joomla-core
- mounted the f-drive wia drvfs with metadata enabled (mounted correctly, i've checked it)
- tried to install joomla inside the directory directly from wsl (downloaded and unzipped with wget / unzip from the command line)
- still does not work...
- tried to install it to var/www/subdir, from there it works, but we cannnot create files directly from windows, since they are invisible to wsl / ubuntu

**Comment by WSLUser** [comment]
> but we cannnot create files directly from windows

Addressed in Insiders with a Plan9 server embedded into `/init`. So next release of Windows will finally have the fix for that. See https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/

Otherwise, did you set metadata manually or via wsl.conf? The metadata won't persist without wsl.conf when you exit your wsl session.

**Comment by pixxelfactory** [comment]
So, if everything succeeds, already this April? That would be great, since we tried:
- setting / mounting it manually with metadata
- writing it to wsl.conf
on two separate machines, neither did work...

Best regards

**Comment by WSLUser** [comment]
Exact release date isn't out yet that I'm aware of. Only suggestion at this point would be to try out [PengWin](https://github.com/WhitewaterFoundry/Pengwin) and see if that fares any better than Ubuntu. Be sure to run through the setup script.

**Comment by pixxelfactory** [comment]
Coming back to this thread, i've updated to 1903 and now it seems to work without issues!!
Thats great news for all webdevs on win10!

**Comment by Faisal-nfl** [comment]
> sudo umount /mnt/c

it says "umount: /mnt/c: target is busy"

**Comment by tomasz-wiszkowski** [comment]
@Faisal-nfl you must ensure that no shell points to a location under /mnt/c, eg. close all WSL windows except current terminal, and then:

```
cd /
umount /mnt/c
mount -t drvfs -o metadata C: /mnt/c
```

if the above still fails for you, try
```
umount -l -f /mnt/c
```

just beware, this will make things a bit less pleasant (likely shell will start failing with `No such file or directory` upon every next action)

**Comment by therealkenc** [comment]
Avoid `umount -f`. It doesn't do what most people assume it does. If the target is busy even after closing all shells but one, you can find the process holing a handle with http://manpages.ubuntu.com/manpages/xenial/man8/lsof.8.html:
```
$ lsof +f -- /mnt/c
```
Exit (or kill with fire) whatever is open. Or, `wsl.exe --shutdown` (from powershell or cmd.exe natch) is a good big hammer go-to.
