### ISSUE TITLE
Writing USB key broken after April Update

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3187]
After April update I cannot copy files on USB key preserving their timestamps. 

Before the update, I had created the mount point:

`sudo mkdir -p /mnt/e/`

and could copy files preserving timestamps:

```
sudo mount -t drvfs e: /mnt/e
/bin/cp -p foo /mnt/e/
rsync -av bar /mnt/e/
```

I did and used this since Fall Creators Update.

Now, I get:

```
/bin/cp -p foo /mnt/e/
/bin/cp: preservati gli orari di '/mnt/e/foo': Operazione non permessa

/usr/bin/rsync -av foo /mnt/e/
sending incremental file list
foo
rsync: mkstemp "/mnt/e/.foo.lMsStT" failed: Operation not permitted (1)

sent 103 bytes  received 111 bytes  428.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

```
If you do not have a quick solution about this, what I described is a big regression of WSL April Update which has brought WSL back before Fall Update was released...

**Comment by 0xbadfca11** [comment]
Maybe #2770

**Comment by benhillis** [comment]
@SvenGroot - would you mind taking a look at this? Seems like this should work.

**Comment by angelog0** [comment]
Hi @benhillis, please explain what does it mean _Seems like this should work_. Here also this does not work anymore:

```
rsync -av foo.tmp/ /mnt/e/foo.tmp/
sending incremental file list
created directory /mnt/e/foo.tmp
rsync: chgrp "/mnt/e/foo.tmp/." failed: Operation not permitted (1)
rsync: chgrp "/mnt/e/foo.tmp/bar" failed: Operation not permitted (1)
./
bar -> foo.txt
foo.txt
rsync: mkstemp "/mnt/e/foo.tmp/.foo.txt.ZUiZwf" failed: Operation not permitted (1)

sent 169 bytes  received 312 bytes  962.00 bytes/sec
total size is 14  speedup is 0.03
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

```
and this does not work:

```
tar -xvof foo.tar.gz -C /mnt/e/
foo.tmp/
foo.tmp/bar
tar: foo.tmp/bar: funzione "utime" non riuscita: Operazione non permessa
foo.tmp/foo.txt
tar: foo.tmp/foo.txt: funzione "utime" non riuscita: Operazione non permessa
tar: foo.tmp: funzione "utime" non riuscita: Operazione non permessa
tar: foo.tmp: impossibile cambiare il modo a rwxr-xr-x: Operazione non permessa
tar: Uscita con stato di fallimento in base agli errori precedenti
```


That means all my scripts to save my WSL home are broken and I have to resume the old strategy I adopted when WSL knew only `C` fix drive, i.e. creating a tarball, moving it in Windows and then unpacking it on the USB key...

It is a very good result, congratulations to the developers...

**Comment by benhillis** [comment]
I'm saying it sounds like a bug that we should investigate.

**Comment by angelog0** [comment]
@benhillis wrote:

> Please keep your discourse professional and civil.

Now you should prove that you are civil restoring what I wrote... if you developers have created a mess, you should be happy that someone stress this...

In any case, for the sake of completeness, it seems that adding the option `metadata`,

`sudo mount -t drvfs e: /mnt/e -o metadata`

allows `cp - p`, `tar `and `rsync` to work as expected.

In the example you have put on the WEB, often `mount` is used without `sudo` but if I do not use `sudo` I get an error:

```
mount -t drvfs e: /mnt/e -o metadata
mount: only root can use "--options" option
```

```
mount -t drvfs e: /mnt/e
mount: only root can use "--types" option
```

Usually I use the same USB key both in Windows and WSL. Now, when I mount it adding `metadata` option, the Windows files are `root root` while those copied with WSL are `utente utente`. Maybe this has its logic but intuitively an user would expect `utente utente`...

Hi @benhillis, I hope you do not yet censor what I wrote, you would make you a bad figure...

**Comment by SvenGroot** [comment]
This is indeed a manifestation of #2770. When you mount your USB stick with default options, all the files will be owned by root, and your user doesn't have the permission to change the timestamps in that case. DrvFs used to bypass the owner check, but this is no longer the case since we added support for different owners with the "metadata" option.

Mounting with "metadata" works in this case because it allows the files you create to be owned by you, rather than root, however it's not the only option (and doesn't solve the problem for files already created by Windows, which don't have metadata and would therefore still be owned by root. For this reason, we added mount options to DrvFs that specify the owner uid and gid to use for files that don't have metadata.

The solution is to mount your USB drive using mount options setting the default uid/gid for files without metadata:
`sudo mount -t drvfs e: /mnt/e -o uid=1000,gid=1000`

You should use your actual uid/gid instead of 1000 (run `id` to determine your default account's uid/gid). Using the metadata option shouldn't be necessary unless you want to use non-default Linux permissions. If you do want to use this option, I recommend you use it together with the uid/gid options.

DrvFs mount options are described at the bottom of [this blog post](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/).

**Comment by Mornon** [comment]
I'm having a similar issue, but -o metadata doesn't solve it: if I try to run rsync on a USB stick I get errors like this:

**Comment by Zythyr** [comment]
> 
> 
> This is indeed a manifestation of #2770. When you mount your USB stick with default options, all the files will be owned by root, and your user doesn't have the permission to change the timestamps in that case. DrvFs used to bypass the owner check, but this is no longer the case since we added support for different owners with the "metadata" option.
> 
> Mounting with "metadata" works in this case because it allows the files you create to be owned by you, rather than root, however it's not the only option (and doesn't solve the problem for files already created by Windows, which don't have metadata and would therefore still be owned by root). For this reason, we added mount options to DrvFs that specify the owner uid and gid to use for files that don't have metadata.
> 
> The solution is to mount your USB drive using mount options setting the default uid/gid for files without metadata:
> `sudo mount -t drvfs e: /mnt/e -o uid=1000,gid=1000`
> 
> You should use your actual uid/gid instead of 1000 (run `id` to determine your default account's uid/gid). Using the metadata option shouldn't be necessary unless you want to use non-default Linux permissions. If you do want to use this option, I recommend you use it together with the uid/gid options.
> 
> DrvFs mount options are described at the bottom of [this blog post](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/).

I think some of the issues are coming from how and when WSL will automatically mount  a drive. Maybe you can provide some insight on my question below? 

**Issue:** I have noticed that WSL will sometimes automatically mount a drive. If it automatically mounts its the user/owner is set to the process that launched the bash.exe. If it does NOT automatically mount the drive, and I have to manually mount it using `sudo mount -t drvfs e: /mnt/e`, then the user/owner is set at `root`. 

The general trend I have noticed is as follows: 
If a USB drive is connected, then WSL will NOT automatically mount the drive
If an HDD is connected using SATA to USB cable, then WSL will automatically mount the drive 

Why is this happening? What command can one use to determine if it was automatically mounted?

**Comment by benhillis** [comment]
@Zythyr - When you run sudo, you effectively become root.  If you want to mount as a specific user, you will have to specify the uid and gid mount options:

For example:
sudo mount -t drvfs e: /mnt/e -o uid=1000,gid=1000

**Comment by Zythyr** [comment]
> 
> 
> @Zythyr - We only automatically mount fixed drives.
> 
> When you run sudo, you effectively become root. If you want to mount as a specific user, you will have to specify the uid and gid mount options:
> 
> For example:
> sudo mount -t drvfs e: /mnt/e -o uid=1000,gid=1000

Yes, I understand that, however my question was: **Why is it that WSL sometimes automatically mounts a drive and sometimes it doesn't?** My use case is for using rsync. Prior to me knowing that I have to use `sudo mount -t drvfs e: /mnt/e -o uid=1000,gid=1000`  instead of `sudo mount -t drvfs e: /mnt/e` I randomly had permission related issues. Now I realize it was because of how drive was originally mounted (automatically or manually). **Why is it that WSL automatically mounts external HDD but does NOT automatically mount USB flash drive?**

**Comment by benhillis** [comment]
@Zythyr - USB flash drives are not fixed.

**Comment by Zythyr** [comment]
> 
> 
> @Zythyr - USB flash drives are not fixed drives, they are removable.

Aren't external drives removable? I have a HDD connected to PC using SATA to USB cable. It act just like a USB flash drive, so why does WSL discriminate between the two? 

Independent of a drive is "removable" or not, why does WSL not automatically mount it? Isn't this a logical approach? For example, if I were using a Ubuntu OS, if I connect a USB flash drive, it would automatically mount the drive, it don't have to manually go in the Terminal to mount it... Shouldn't WSL mimic this same behavior?

**Comment by therealkenc** [comment]
> Why is it that WSL sometimes automatically mounts a drive and sometimes it doesn't?

Part of confusion derives from the choice of nomenclature.... (1) Drives aren't auto-mounted in WSL in the sense of the word commonly used in Linux. They're static mounted, at startup. Your SATA drive on a wire is treated as a fixed drive because that's what it looks like at startup. Your USB stick does not. (2) WSL doesn't actually have "drives" in the Linux sense either. There are no block devices in WSL that come and go, like in Real Linux.

> For example, if I were using a Ubuntu OS, and I connect a USB flash drive, it would automatically mount the drive, I don't have to manually go in the Terminal to mount it... Shouldn't WSL mimic this same behavior?

The landing zone for that is #560 ([message](https://github.com/Microsoft/WSL/issues/560#issuecomment-361450367)). Rhetoricals usually don't get much of a reply, so you can probably consider that part answered by yourself (affirmative or negative; whichever you prefer).

**Comment by angelog0** [comment]
With all due respect, from my POV this behavior of `WSL` respect to USB devices is of no usefulness and I renounced it. I prefer to use a Windows folder as a sort of "cloud" to exchange data between WSL and the USB device. Usually, in the time it would take to mount (and then to unmount) the device as suggested in this discussion I have already transferred the data (with the help of [MSYS2](http://www.msys2.org) in wich USB device are automounted).

Merry Christmas and Happy New Year.
