### ISSUE TITLE
Ubuntu 18.04 FISH shell hangs

### ISSUE THREAD

**Issue by csharpe** [Microsoft/WSL#3219]
After install Ubuntu 18.04 from the windows store I performed the following operations:

1. sudo apt-get update
2. sudo apt-get upgrade
3. sudo apt-get install fish
4. fish (to verify fish shell installed) - worked correctly
5. exited fish shell
6. chsh <username> -s /usr/bin/fish
7. Exited bash - closes Ubuntu 18.04 terminal window
8. Restarted ubuntu 18.04 from the windows start menu
9. Ubuntu hangs on restart....
I would expect Ubuntu to start up presenting a fish interactive login shell.  This does work on Ubuntu 16.04.3 by following the above steps.

Windows version is: Microsoft Windows [Version 10.0.16299.431]

![image](https://user-images.githubusercontent.com/229092/40282145-ef1ae174-5c27-11e8-8b0e-9fb9423c0694.png)

I can easily reproduce this with a fresh install of Ubuntu and even simply resetting the install from the add/remove programs advanced options settings.

**Comment by sirredbeard** [comment]
Windows 10.0.17134.81
20180426.2 build of Ubuntu 18.04

I have been using fish as my default shell on 18.04 for some time, so I was surprised by your report. I followed your exact steps on a fresh install and was unable to reproduce:

![capture5](https://user-images.githubusercontent.com/33820650/40580929-c67d34f6-6118-11e8-8053-abb318610e46.PNG)
![capture6](https://user-images.githubusercontent.com/33820650/40580930-ca255ab6-6118-11e8-82ff-3ed14ff1b999.PNG)
![capture7](https://user-images.githubusercontent.com/33820650/40580931-cc266594-6118-11e8-9a21-bcf6c6c19801.PNG)

Instead of uninstalling Ubuntu via removal of WSL in Windows Features I would recommend just right-clicking on Ubuntu in the Start Menu and selecting uninstall. Letting Microsoft Store handle the images works reasonably well now. Even using the old lxrun app can cause issues like the one you describe.

**Comment by csharpe** [comment]
Hi Sirredbeard
I tired your recommended uninstallation process.  No change.  On a hunch I tried another PC with a different video card, well actually quite different across the board.   I can reproduce the issue on it as well, so that makes two different PC's.

I noticed you are running a later build of Windows 10.  I am starting to feel that may be a factor.  I checked with Windows Update and no newer builds are available.  I must be on a different ring than you are.  I have hopes that a newer build will address the issue.

**Comment by csharpe** [comment]
I forgot to note that both machines are running the same build number of windows 10.

**Comment by sirredbeard** [comment]
@csharpe 

It could be a build issue.

Just so you know I am not running on an Insider or Developer ring. I am running factory Lenovo Windows 10 Pro with the May 2018 updates.

You might want to check to make sure you are getting updates properly, there are ways to manually force an update.

**Comment by mqudsi** [comment]
See also https://github.com/Microsoft/WSL/issues/2510#issuecomment-334017639 https://github.com/Microsoft/WSL/issues/2199, and https://github.com/Microsoft/WSL/issues/1653

**Comment by therealkenc** [comment]
> See also #2510 (comment) #2199, and #1653

Thanks @mqudsi. Call this #1653 because the OP is 16299. Fix in 1803 April Update aka 17134.
