### ISSUE TITLE
WSL crashes when going into full screen via Alt+Enter when vim has a statusline

### ISSUE THREAD

**Issue by noelbundick** [Microsoft/WSL#3245]
* Your Windows build number:  `Microsoft Windows [Version 10.0.17672.1000]`

Desktop message shows
```
Windows 10 Enterprise Insider Preview
Evaluation copy. Build 17672.rs_prerelease.180511-1445
```

* What you're doing and what's happening:

I am using vim (`version 8.0.1453`) inside the `Ubuntu 18.04` downloaded from the store to open a file. When I press `Alt+Enter`, I get a flash of Win7-ish chrome with Sets buttons and no min/max/close buttons around my terminal atop a black screen. Sometimes it's a legit blue gradient Win7 frame, sometimes it's just a flat box. It hangs there for 5-10 seconds, and then my WSL environment crashes completely, clearing both the black background and the now-unresponsive terminal

This also occurs in the legacy bash.exe environment that I still have around, so it doesn't seem to be anything specific to 18.04. It also repros across `/bin/bash` and `/bin/zsh` as my login shell

![image](https://user-images.githubusercontent.com/1970162/40566340-0c4184d2-6025-11e8-8f73-fbc030c0ab49.png)

Oddly, it only happens when I have specific values in my `.vimrc`. The minimal configuration to reproduce the error is the following:

Bad .vimrc
```
set laststatus=2
```

Good .vimrc
```
set laststatus=0
```

It also only occurs when I am in vim prior to `Alt+Enter`. If I am in fullscreen mode, then open vim, all is fine. If I then reenter fullscreen mode, I get the crash again.

* What's wrong / what should be happening instead: I should be allowed to maximize a WSL terminal without errors

* Strace of the failing command, if applicable: 
https://gist.github.com/noelbundick/5d395d1f5e67017585cbb6896a2c28cd

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by noelbundick** [comment]
Update: this does not happen with an identical config on my 1803 machine with version: `Microsoft Windows [Version 10.0.17134.48]`

**Comment by therealkenc** [comment]
So it doesn't work in 17672 but is okay in 17134. That's definitely helpful and interesting. You _might_ try your luck over in the Windows Console issue [tracker](https://github.com/microsoft/console), if only because quoth: "I get a flash of Win7-ish chrome with Sets buttons and no min/max/close buttons around my terminal". That doesn't seem like a WSL syscall surface kind of thing. But your `strace` log (appreciated) blocks on a `select()` so I can't rule out a cross-border problem either. You're right it (nearly certaintly) isn't going to be a Xenial vs Bionic thing.

You can confirm by trying your scenario with another terminal emulator ([wsltty](https://github.com/mintty/wsltty) or [PuTTY](https://www.putty.org/) or `xterm` with [VcXsrv](https://sourceforge.net/projects/vcxsrv/), or pick your poison) and see how it fares. If it works, you'll probably get better service over in the other tracker.

**Comment by noelbundick** [comment]
Thanks, @therealkenc - I've verified that wsltty is working fine, so I'll close this here

Looks like https://github.com/Microsoft/console/issues/175 is likely the same issue and has a fix landing in an upcoming Insiders build (if not already fixed in 17677)

**Comment by gentig** [comment]
I have the same issue too. When resizing terminal window while vim is open it "crashes". Weird gray color appears in the bottom and right side of the terminal window.
