### ISSUE TITLE
WSL 18.04 apt upgrade failure

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/WSL#3274]
I recently downloaded **Ubuntu 18.04**  App from Microsoft App Store.
Subsequently, I update app packages through `sudo apt-get update` and then, `sudo apt-get upgrade`
then I the following message  came up with errors (just fresh WSL system nothing has been installed),

![upgrade](https://user-images.githubusercontent.com/3683121/40872024-739c5a7c-6664-11e8-94c5-12c41f675ece.PNG)

and, there are after I installed GCC, clang, gdb, and python3 also it's getting same upgrading error saying - 

> Error: insufficient privileges to access the ebtables rulesets.

> Errors were encountered while processing:
 /var/cache/apt/archives/ebtables_2.0.10.4-3.5ubuntu2.18.04.1_amd64.deb

Please help me to resolve this issue.
Thank you.

**Comment by Biswa96** [comment]
Try to login with `sudo -s`.

**Comment by shoffmeister** [comment]
https://bugs.launchpad.net/ubuntu/+source/ebtables/+bug/1774120

**Comment by Line117** [comment]
https://github.com/Microsoft/WSL/issues/1761#issuecomment-392575807

**Comment by therealkenc** [comment]
> #1761 (comment)

Which in turn is ref #767

**Comment by macxfadz** [comment]
@therealkenc  Do we have an exact fix for this issue? or do we have to wait for next Ubuntu release?

**Comment by sirredbeard** [comment]
@macxfadz A temporary workaround is here: https://github.com/Microsoft/WSL/issues/1761#issuecomment-392575807

**Comment by therealkenc** [comment]
Or  maybe someone can confirm whether just purging the thing is a viable solution (I haven't looked).

**Comment by sirredbeard** [comment]
@therealkenc Preliminary testing shows that simply purging doesn't work, but it was worth a shot.

> Unpacking libcurl4:amd64 (7.58.0-2ubuntu3.1) over (7.58.0-2ubuntu3) ...
> Preparing to unpack .../16-ebtables_2.0.10.4-3.5ubuntu2.18.04.1_amd64.deb ...
> invoke-rc.d: could not determine current runlevel
>  * Error: insufficient privileges to access the ebtables rulesets.
> invoke-rc.d: initscript ebtables, action "stop" failed.
> dpkg: warning: old ebtables package pre-removal script subprocess returned error exit status 1
> dpkg: trying script from the new package instead ...
> invoke-rc.d: could not determine current runlevel
>  * Error: insufficient privileges to access the ebtables rulesets.
> invoke-rc.d: initscript ebtables, action "stop" failed.
> dpkg: error processing archive /tmp/apt-dpkg-install-sFNodb/16-ebtables_2.0.10.4-3.5ubuntu2.18.04.1_amd64.deb (--unpack):
>  new ebtables package pre-removal script subprocess returned error exit status 1
> dmesg: read kernel buffer failed: Function not implemented
>                                                           update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
> invoke-rc.d: could not determine current runlevel
> Preparing to unpack .../17-libcurl3-gnutls_7.58.0-2ubuntu3.1_amd64.deb ...
> Unpacking libcurl3-gnutls:amd64 (7.58.0-2ubuntu3.1) over (7.58.0-2ubuntu3) ...
> Preparing to unpack .../18-software-properties-common_0.96.24.32.3_all.deb ...
> Unpacking software-properties-common (0.96.24.32.3) over (0.96.24.32.1) ...
> Preparing to unpack .../19-python3-software-properties_0.96.24.32.3_all.deb ...
> Unpacking python3-software-properties (0.96.24.32.3) over (0.96.24.32.1) ...
> Preparing to unpack .../20-snapd_2.32.9+18.04_amd64.deb ...
> Unpacking snapd (2.32.9+18.04) over (2.32.5+18.04) ...
> Preparing to unpack .../21-cloud-init_18.2-27-g6ef92c98-0ubuntu1~18.04.1_all.deb ...
> Unpacking cloud-init (18.2-27-g6ef92c98-0ubuntu1~18.04.1) over (18.2-14-g6d48d265-0ubuntu1) ...
> Preparing to unpack .../22-ssh-import-id_5.7-0ubuntu1.1_all.deb ...
> Unpacking ssh-import-id (5.7-0ubuntu1.1) over (5.7-0ubuntu1) ...
> Errors were encountered while processing:
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> hayden@t470s:~$ echo "export DISPLAY=:0" >> .bashrc
> hayden@t470s:~$ echo "export LIBGL_ALWAYS_INDIRECT=1" >> .bashrc
> hayden@t470s:~$ sudo apt-get remove ebtables --purge
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following package was automatically installed and is no longer required:
>   libfreetype6
> Use 'sudo apt autoremove' to remove it.
> The following packages will be REMOVED:
>   ebtables* lxd*
> 0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
> 22 not fully installed or removed.
> After this operation, 20.2 MB disk space will be freed.
> Do you want to continue? [Y/n] Y
> (Reading database ... 28478 files and directories currently installed.)
> Removing lxd (3.0.0-0ubuntu4) ...
> invoke-rc.d: could not determine current runlevel
> Stopping Container hypervisor based on LXC: (not running).
> invoke-rc.d: could not determine current runlevel
> Removing lxd dnsmasq configuration
> Removing ebtables (2.0.10.4-3.5ubuntu2) ...
> invoke-rc.d: could not determine current runlevel
>  * Error: insufficient privileges to access the ebtables rulesets.
> invoke-rc.d: initscript ebtables, action "stop" failed.
> dpkg: error processing package ebtables (--remove):
>  installed ebtables package pre-removal script subprocess returned error exit status 1
> Errors were encountered while processing:
>  ebtables
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> hayden@t470s:~$

**Comment by macxfadz** [comment]
`sudo -s` also not working :(  what cause this privelledge issue ?
![capture](https://user-images.githubusercontent.com/3683121/40899257-9b16402e-67e3-11e8-9848-bd87bcb210a0.PNG)

**Comment by sirredbeard** [comment]
@macxfadz 

When the ebtables upgrade script invokes the ebtables stop init script ebtables tries to open a socket and fails. Either because ebtables is [at fault](https://lists.ubuntu.com/archives/ubuntu-devel-discuss/2018-May/018072.html) for misinterpreting or because WSL hasn't fully implemented iptables, it fails is not entirely clear. Either way it ends up throwing a permissions error. It doesn't matter what you run as, or what runlevel.

**Comment by therealkenc** [comment]
> why it fails is not entirely clear

No, why it fails is _entirely_ clear. WSL does not implement all Linux ABI surface. Doesn't even pretend to, per the FAQ. Aspires to, hopefully. 

#1451 is `PF_NETLINK`. Which is not `AF_UNIX`. Which is not `AF_PACKET`. And, is not `AF_INET` per #767.

**Comment by sirredbeard** [comment]
@therealkenc 

You may be correct. Could you please explain why [this](https://lists.ubuntu.com/archives/ubuntu-devel-discuss/2018-May/018072.html) is wrong or misplaced though?

**Comment by therealkenc** [comment]
> Could you please explain why this is wrong or misplaced though?

Well, anything I could say would be speaking for Balint, which I don't. All I think he is trying to say is that etables could deal better with the error returned by WSL, which makes etables technically more correct, and thus addresses the hard fail. `EPROTONOSUPPORT` depends entirely on the _`PROTO`_ in question. Some are _`SUPPORT`_. Some are _`NOSUPPORT`_. 

> And why EPROTONOSUPPORT appears to have been added here, the syscalls in question?

In the #1451 OP, `nmap` never even made it to a `EPROTONOTSUPPORT` return from `socket(AF_INET, ...)` to begin with. It was dying with `EOPNOTSUPP` on `sndmsg()` on an `AF_NETLINK` socket. The latter was addressed (narrowly, because not all `NETLINK_ROUTE` messages are implemented in WSL either). The former is not (or, at least not enough to make etables happy).

**Comment by sirredbeard** [comment]
I see. Thank you for clearing that up.

**Comment by macxfadz** [comment]
@therealkenc   @sirredbeard - guys any elegant fix for this issue please ? :|

**Comment by sirredbeard** [comment]
@macxfadz 

I mentioned a workaround [above](https://github.com/Microsoft/WSL/issues/3274#issuecomment-394168479).

You can also simply hold ebtables using apt: 

> sudo apt-mark hold ebtables

**Comment by akshaybabloo** [comment]
by holding/disabling `ebtables` will it cause any problem with the network bridge between Windows and Linux? Looking at their website (http://ebtables.netfilter.org/), `ebtables` does a lot of stuff

**Comment by macxfadz** [comment]
@akshaybabloo  sounds like we have to next release of WSL ? is n't it ?

**Comment by akshaybabloo** [comment]
@macxfadz yep. Looks like that. Or even a patch would be enough

**Comment by sirredbeard** [comment]
@akshaybabloo 

ebtables is old software that few actually use any more. It is maintained as legacy software by the developers that inherited it who only provide the most basic security patches and updates.

ebtables is also not compatible with WSL yet because the WSL layer hasn't fully implemented all the advanced networking calls that ebtables and it's parent software iptables uses. So no one is really using ebtables on WSL.

@macxfadz 

This bug, in the upgrade script on Ubuntu 18.04, only affects Ubuntu 18.04 images. So Ubuntu 16.04, OpenSUSE, SEL, and Kali users are unaffected. The fix is for the upgrade script in Ubuntu 18.04 to ignore the error when ebtables tries something not yet supported by WSL as part of the upgrade process. The second post on this thread contains a link to the Ubuntu bug report. If you look you will see a patch in Ubuntu has been generated, pushed to Cosmic, which is 18.10 in progress, for testing, and will filter down to Bionic, 18.04, in due time.

Windows or WSL itself will not need a patch, although it's possible eventually WSL will support the network calls ebtables is flunking out on during the upgrade.

**Comment by macxfadz** [comment]
@sirredbeard  Thanks for the info ...if we holding/disabling ebtables in ubuntu 18.04 if you don't mind , can you please tell me what are the side effects we can expect? and one thing though , why it's working with 16.04 fine? as you mentioned here 

> This bug, in the upgrade script on Ubuntu 18.04, only affects Ubuntu 18.04 images. So Ubuntu 16.04, OpenSUSE, SEL, and Kali users are unaffected

due to 18.04 upgrade script update?

**Comment by sirredbeard** [comment]
@macxfadz 

>  can you please tell me what are the side effects we can expect?

Very little actually relies on ebtables these days, it's just there for legacy support on some servers.

Given that ebtables doesn't work on WSL at this time, holding ebtables upgrades in WSL will have no real effect. 

Holding it means it simply won't get any updates via apt-get -upgrade.

WSL is rolling out support for iptables which it means it's possible ebtables could, by extension, be supported too, there's no real demand for it though.

Ebtables is legacy software in maintenance mode, there are modern more secure tools for performing it's functionality. Ubuntu is even working on a layer to wrangle iptables.

I imagine eventually upstream distros like Debian will deprecate ebtables in time.

>  why is it working with 16.04 fine

The issue occurs when the ebtables upgrade script calls ebtables to stop it and ebtables fails.

The issue only occurs when ebtables is upgraded via apt.

It is working fine in 16.04 because 16.04 does not ever upgrade ebtables, there's really no need to.

**Comment by macxfadz** [comment]
@sirredbeard  Thank you for the explanation really helpful.

**Comment by Voskrese** [comment]
@sirredbeard  как вариант удалить послу установочный скрипт

 ls /var/lib/dpkg/info/qemu-user-static* 
` ls /var/lib/dpkg/info/ebtables*`

`rm /var/lib/dpkg/info/ebtables.postinst`

http://kde5.blogspot.com/2017/03/linux-apt-get-force.html

**Comment by macxfadz** [comment]
This solved the issue temporarily I guess. 💃 
[Microsoft Link](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/errors-in-ubuntu-1804-on-windows-10/fe349f3d-3d58-4d90-9f8f-c14d7c12af8b)

**Comment by Hypnoes** [comment]
![capture](https://user-images.githubusercontent.com/13956546/42291441-3416ddec-7ffe-11e8-9ac7-a274832c185e.PNG)

Still not fix at this time....

**Comment by macxfadz** [comment]
@Hypnoes but mine fix for the time... that's why I mentioned "temporarily" ...sorry

**Comment by tralston** [comment]
Interesting. Updated ebtables today (via aptitude ui) and it didn't error out.

**Comment by macxfadz** [comment]
@tralston Couldn't get you, can you mentioned what do you mean by "aptitude ui"? and what modification have you carried out in order to error wipe away?

**Comment by Voskrese** [comment]
@macxfadz
`sudo aptitude`
`Ctrl + T `

**Comment by onomatopellan** [comment]
The ebtables problem has been fixed. No need to hold the package anymore. 
https://launchpad.net/ubuntu/+source/ebtables/2.0.10.4-3.5ubuntu2.18.04.3

**Comment by therealkenc** [comment]
Good to know. Closing external. [Contrast #767 and friends.]
