### ISSUE TITLE
Ubuntu 18.04 gpg dirmngr IPC connect call failed

### ISSUE THREAD

**Issue by sirredbeard** [Microsoft/WSL#3286]
* Your Windows build number:  10.0.17134.81

* What you're doing and what's happening: 

Building MonoDevelop for Windows looks like a [real hassle](http://www.monodevelop.com/developers/building-monodevelop/#windows) and there are no binaries available.

I decided to give MonoDevelop for Ubuntu binaries a try on WSL.

I installed a clean Ubuntu 18.04 from the Microsoft Store.

To get it all caught up I executed:

```
sudo apt-mark hold ebtables # for the current upgrade bug
sudo apt-get update
sudo apt-get upgrade -y
```

and then I picked up with the [MonoDevelop IDE instructions](http://www.monodevelop.com/download/#fndtn-download-lin):

```
sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
```

Then I run into an issue.

I receive the following error message:

```
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
[sudo] password for hayden:
Executing: /tmp/apt-key-gpghome.BG01sRSmD5/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.BG01sRSmD5/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
```

* What's wrong / what should be happening instead:

gpg isn't able to call dirmngr

What I have attempted:

1. Running dirmngr in another bash instance
2. Making sure gpg-agent is running in the background
3. This. https://stackoverflow.com/questions/49496667/gpg-key-generation-canceled and https://stackoverflow.com/questions/46673717/gpg-cant-connect-to-the-agent-ipc-connect-call-failed 

* [Strace of the failing command.](https://gist.github.com/sirredbeard/41ced701945eeb66e2cbfca0a44025a3)

Note: I have also tried building MonoDevelop from source on Ubuntu in WSL, but ran into [this issue](https://github.com/mono/monodevelop/issues/5022).

**Comment by shoffmeister** [comment]
3424  bind(3, {sa_family=AF_UNIX, sun_path="/tmp/apt-key-gpghome.wZVVfa2T2R/S.dirmngr"}, 43) = -1 ENOENT (No such file or directory)

**Comment by shoffmeister** [comment]
The process you strace keeps looking for "/tmp/apt-key-gpghome.wZVVfa2T2R/S.dirmngr" - and does not find it.
That this then ends up as
```
3424  socket(AF_UNIX, SOCK_STREAM, 0)   = 3
3424  stat("/tmp/apt-key-gpghome.wZVVfa2T2R/S.dirmngr", 0x7fffe2242bd0) = -1 ENOENT (No such file or directory)
3424  bind(3, {sa_family=AF_UNIX, sun_path="/tmp/apt-key-gpghome.wZVVfa2T2R/S.dirmngr"}, 43) = -1 ENOENT (No such file or directory)
```
does not seem to be overly surprising.

This begs the question: What do you actually see in `sudo ls -la /tmp/apt-key-gpghome*` at the time of failure?

**Comment by Alternate-Egoist** [comment]
It's Bugging Since The First Bionics in wsl. But the temporary to pass this problems is using apt-key add instead adv options through wget or curl :
curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF" | sudo apt-key add

**Comment by sirredbeard** [comment]
This workaround works. Thank you. I had a completely block when I was trying to think of other ways to install the key.

I created an example script here. https://github.com/sirredbeard/monodeveloponwsl/edit/master/install_via_apt.sh

I also reported to mono develop that they should list installing on WSL as an option for installing MonoDevelop on Windows here.
https://github.com/mono/md-website/issues/84

**Comment by therealkenc** [comment]
I hate to look a 'closed' gift horse in the mouth, but this one merits some further attention because it will keep coming up until we have a work-around on the books for the `dirmngr` fail proper. The problem is unrelated to Mono or MonoDevelop, natch. [MariaDB](https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-16-04) (key `0xF1656F24C74CD1D8`) fails the same, as will every `apt-key` howto anyone has ever posted on the Interwebs.

The problem that `dirmngr` (`sudo apt install dirnmgr`) isn't running (or isn't autolaunched?) and thus there is nothing on the other end for `apt-key` via `gpg` to talk to. After around half an hour of investigation, like @sirredbeard, I wasn't able to make `dirmngr` at home on WSL manually. Maybe someone else will have better luck or suggestions.

**Comment by sirredbeard** [comment]
I support re-opening for the wider issue with dirmgr.

I think I was able to import the key by curling it in and piping it to apt-key.

Is this only on Ubuntu and only 18.04? If so, should we file a bug report upstream with Canonical?

**Comment by therealkenc** [comment]
> I think I was able to import the key by curling it in and piping it to apt-key.

Yes that's effectively the work-around until the base cause and a solution to the root problem is articulated.

> Is this only on Ubuntu and only 18.04?

That is part of what merits investigation. It wasn't a problem on 16.04 (but you already knew that). Whether it wasn't a problem in 16.04 because (a) an operable `dirmngr` wasn't previously a requirement or (b) `dirmng` was working fine and nobody thought anything of it or (c) something changed with `gpg` or `apt-key` or `dirmngr` or something in between that now causes the sequence to fail, I can't tell you. Or at least, not with any authority after looking at it for a short bit.

**Comment by Alternate-Egoist** [comment]
but sometimes in metapackages with ubuntu-desktop when i was want to install Crystal Language by importing their gpg and it's works through the adv options

**Comment by DarthSpock** [comment]
I'd like to report that any debian based distro (possibly any distro) utilizing an updated dirmngr before 18.04 was officially released as LTS was recieving this error. The issue was resolved just in time for 18.04 release. So this may be a regression or something Ubuntu did to screw with it.

When I had experienced this error utilizing Debian Buster, I simply reinstalled Debian from the Store after 18.04 was released and the updated package containing the fix was imported when upgrading from Stretch to Buster. As of yesterday evening, I have yet to see this issue re-occur. 

The work-around mentioned above failed at the time and did prevent any package (including stock) from successfully upgrading. Even `apt update` failed.

I would recommend others test a different distro other than Ubuntu 18.04 that uses the same version of dirmngr (or upgrade to it if not part of the base) and see if it still has an issue.

For completeness, I'm running build 17134 with the latest patch.

**Comment by sirredbeard** [comment]
@Alternate-Egoist 

I wanted to do the same but could not duplicate your success.

![capture32432](https://user-images.githubusercontent.com/33820650/41491546-aed75e9e-70c7-11e8-88a5-281d6855087a.PNG)

**Comment by filjoseph1989** [comment]
I tried following the guide here https://downloads.mariadb.org/mariadb/repositories/#mirror=utm&distro=Ubuntu&distro_release=bionic--ubuntu_bionic&version=10.3

while running this, sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8, i got 
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.cROhJELJ0N/S.dirmngr' failed: IPC connect call failed message too

**Comment by therealkenc** [comment]
> I tried following the guide here ... apt-key etc etc etc ..../mariadb/.... etc etc etc ...  0xF1656F24C74CD1D8 .... I got .... etc etc .... IPC connect call failed

Well, yes. Because [_Quoth_](https://github.com/Microsoft/WSL/issues/3286#issuecomment-396653804):

The problem is unrelated to Mono or MonoDevelop, natch. MariaDB (key 0xF1656F24C74CD1D8) fails the same, as will every apt-key howto anyone has ever posted on the Interwebs.

**Comment by jibin2706** [comment]
same error while install mongodb

**Comment by sav-valerio** [comment]
Same problem here with MariaDB, if you really need the repository you could "avoid" the key authentication using _sudo apt-get --allow-insecure-repositories update_
Still it is not a proper solution, not to mention the potential security issues that could arise.

**Comment by foxliu** [comment]
Can try this: 
1. use `sudo apt update ` then will get something like `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5523BAEEB01FA116`
2. Got the pubkey `5523BAEEB01FA116`
3. Use `curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5523BAEEB01FA116" | sudo apt-key add` Replace 0x5523BAEEB01FA116 with 0x<your pubkey in 2step>
4. complete, you can run `sudo apt udpate` no error

**Comment by sav-valerio** [comment]
@foxliu solution seems to work just fine. 
But still I wasn't able to download the public key using curl, so I copied manually the key from the Ubuntu Keyserver link,to a new file in WSL, then loaded it with sudo apt-key add.

For future reference, this is the MariaDB Package Signing Key: 
http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF1656F24C74CD1D8

**Comment by amehrshad** [comment]
i have the same error while installing mongodb

**Comment by luisarriojas** [comment]
For future reference, manual solution is this:
$ curl -sL "https://www.mongodb.org/static/pgp/server-4.0.asc?_ga=2.264892495.1953852568.1531143056-750073170.1531143056" | sudo apt-key add

**Comment by benhillis** [comment]
I took a look at this today and have determined that this is a timing-related issue that is exposed because of a difference in how Windows and Linux handles connection attempts to localhost sockets.  On Linux an attempt to connect to a localhost tcp socket on a port that is not active will return a failure immediately.  On Windows there appears to be a 1 second timeout.  This causes the following sequence to occur.

1. gpg spawns dirmngr
2. dirmngr attempt to connect to localhost port 9050 (this is attempted twice).
3. gpg attempts to connect to a unix socket that dirmngr creates after the localhost socket connection fails.

This one second timeout in step 2 is enough to cause gpg to think that dirmngr is not responding.  There appears to be a retry loop in gpg, but it is not waiting long enough to account for the 1 second connect timeout (the connect is actually attempted twice).

I've reached out to some Windows networking experts to determine if there is a way that this timeout can be avoided.

**Comment by therealkenc** [comment]
That's awesome Ben. Thank-you for digging; by total chance I was going to dive this one myself this evening. Motivation being, this is blocking LXC, which uses gpg to fetch keys for the images in the same manner as `apt-key` 😉. 

Being ahead of me, if you've got a suggestion a temporary work-around in the gpg or dirmngr source to make them collectively happy (avoid the timeout) that would be helpful. Even if not, at least I know where to look now, which is very appreciated. If this is going to be a long lead time thing (won't make fall release) maybe I can push a PPA to launchpad.

**Comment by benhillis** [comment]
I haven't looked through the gpg source but it seems to be after it has launched dirmngr and is trying to connect to a unix socket it expects dirmngr to create. There is a retry loop that goes for about 20 iterations.

**Comment by benhillis** [comment]
I took another look this morning and found the bug in gpg.  Their retry loop waiting for dirmngr to come up is passing an invalid argument to the nanosleep system call.  From the nanosleep [man page](http://man7.org/linux/man-pages/man2/nanosleep.2.html):

The value of the nanoseconds field must be in the range 0 to 999999999.

The retry loop starts with a relatively small sleep and doubles the duration, eventually capping out at one second.  However they pass 1 second as 1000000000 nanoseconds, which returns EINVAL immediately.

This was actually already fixed by this commit: https://github.com/gpg/gnupg/commit/0cfdd3b57d592fb6baa7dafe8fde124e8a6c7798#diff-01af2aa0c9e9ef29097d81dfcf608938

**Comment by benhillis** [comment]
I received a suggestion from the Windows networking team to set a socket option for localhost sockets to disable TCP retry.  With this change the apt-key command succeeds.  @Brian-Perkins has a change in code review now.

**Comment by therealkenc** [comment]
Well that turned out well. Might even address some other outlying fails. It was only by chance that `dirmngr` regressed and exposed this.

I also managed to learn something. 48 hours ago I would have bet a buck that it was glibc that checks for the the billion nanosecond overflow, returning `EINVAL` to satisfy some posix definition; and the Linux kernel would eat it and just normalise the timespec (a saner behaviour). It doesn't. The kernel checks. Who knew.

**Comment by benhillis** [comment]
@therealkenc - Yeah I suspect this might speed up some random things that are attempting to connect to things things on localhost.

**Comment by sirredbeard** [comment]
Thank you to @therealkenc and @benhillis.

Has a bug report been opened with GPG re: regression?

**Comment by sirredbeard** [comment]
@benhillis Ah, I thought it was an upstream regression in gpg, my mistake.

**Comment by et304383** [comment]
So is there ultimately no fix for this?  Do we have to compile gpg from source to upgrade?

**Comment by hermanomark** [comment]
I think I'm having the same issue. I'm trying to install MongoDB and nothing happens when running sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

**Comment by hermanomark** [comment]
@foxliu hey I tried your steps

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

converted to:

curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9DA31620334BD75D9DCB49F368818C72E52529D4" | sudo apt-key add

did I did this right?? it returned
Ok. then I just proceeded to install MongoDB works just fine.

**Comment by foxliu** [comment]
@hermanomark    OK means the key has been added, you can install the one you need

**Comment by PpiERo** [comment]
I'm trying to install MongoDB.  I looked it up all morning.
`sudo curl -LO https://www.mongodb.org/static/pgp/server-4.0.asc`
`sudo apt-key add server-4.0.asc `

**Comment by buddha314** [comment]
This same error occurs trying to install ROS via [these instructions](https://janbernloehr.de/2017/06/10/ros-windows) and I have not been able to figure out how to use `curl` in this instance.

**Comment by gavanderhoorn** [comment]
@buddha314: there is a Q&A on ROS Answers about this ([this one](https://answers.ros.org/question/307024)).

**Comment by IanKemp** [comment]
@benhillis For those of us *not* on an insider build (corporate network), is there any way to get this fix?

**Comment by jefraroce** [comment]
Hello, I arrived to this thread for a similar problem installing **MongoDB**, but maybe this steps are useful for you too:

_(Were ran in Ubuntu 18.04 installed like a subsystem of windows 10)_

### First download the key manually (This key is for mongodb-org repository)
`wget https://www.mongodb.org/static/pgp/server-4.0.asc`

### Add key manually
`sudo apt-key add server-4.0.asc`

### Remove it
`rm server-4.0.asc`

### Update package list
`sudo apt-get update`

### Install MongoDB-org
`sudo apt-get install -y mongodb-org`

That's it, I hope to have helped to anyone.

Cheers!

**Comment by ppumkin** [comment]
If you need to install something from Microsoft, say like Azure CLI

> wget https://packages.microsoft.com/keys/microsoft.asc

Following the guide by @jefraroce helped me

**Comment by ppumkin** [comment]
> > If you need to install something from Microsoft, say like Azure CLI
> > > wget https://packages.microsoft.com/keys/microsoft.asc
> > 
> > 
> > Following the guide by @jefraroce helped me
> 
> Where is the guide @ppumkin ?
> I am stuck on this now - thx!

Use what @jefraroce  has written up just aboive my previous comment. In particular 

> wget https://www.mongodb.org/static/pgp/server-4.0.asc

would be 

> wget https://packages.microsoft.com/keys/microsoft.asc

**Comment by JohnFlowerful** [comment]
Add `no-use-tor` to dirmngr.conf.

**Comment by MajidJafari** [comment]
Hi guys. I had problem installing mongodb on wsl like you. Then I just downloaded "TGZ" package from [https://www.mongodb.com/download-center/community?jmp=docs](url) and followed the installation steps from [ https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-linux/](url) and everything works for me.

Hope this could help you.

**Comment by Choco0914** [comment]
> 안녕 얘들 아. 나는 당신처럼 wsl에 mongodb를 설치하는 데 문제가있었습니다. 그럼 난 그냥에서 "TGZ"패키지를 다운로드 [https://www.mongodb.com/download-center/community?jmp=docs](url) 에서 설치 단계 및 다음 [https://docs.mongodb.com/v3.2/tutorial/ install-mongodb-on-linux /](url) 모든 것이 저에게 효과적입니다.
> 
> 희망이 당신을 도울 수 있습니다.



> Hi guys. I had problem installing mongodb on wsl like you. Then I just downloaded "TGZ" package from [https://www.mongodb.com/download-center/community?jmp=docs](url) and followed the installation steps from [ https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-linux/](url) and everything works for me.
> 
> Hope this could help you.

I can not see the results for that link

**Comment by MajidJafari** [comment]
@Choco0914 copy and paste the link in the new tab. Seems Gitlab doesn't allow for direct linking

**Comment by ScottRBK** [comment]
Anyone having any the same issue when trying to install Mono for Ubuntu 18.04 (https://www.mono-project.com/download/stable/#download-lin) in WSL?

I've tried the suggested work around but I'm not able to find the key (3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF) that is required for Mono on the Ubunutu key server site (http://keyserver.ubuntu.com/) and not surprisingly it's not worked when using curl.

**Comment by xsqian** [comment]
I have a similar problem while installing azure-cli.

sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
>      --keyserver packages.microsoft.com \
>      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.nTgRqyZ9R8/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.nTgRqyZ9R8/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

**Comment by lukerogers** [comment]
@xsqian I had the same problem with Azure CLI, so I stole the command from the SQL Server Linux install (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017) and got it to work:

`curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -`

**Comment by xsqian** [comment]
@lukerogers Yes, thank you so much for sharing the solution, love it!

**Comment by Coolguy3289** [comment]
@therealkenc This is still an issue. Following any instructions that instruct you to run apt-key adv still fail for the same error. Got the error following instructions from https://docs.pritunl.com/docs/ssh-client under the Ubuntu Bionic section.

**Comment by therealkenc** [comment]
> this

No, [_this_](https://github.com/microsoft/WSL/issues/3286#issue-330854159) was resolved in [17723]().

![image](https://user-images.githubusercontent.com/7049700/58300018-e65d8b00-7d95-11e9-907a-e862d08d57ff.png)

**Comment by filjoseph1989** [comment]
> curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF" | sudo apt-key add

I tried following this https://downloads.mariadb.org/mariadb/repositories/#mirror=rise&distro=Ubuntu&distro_release=bionic--ubuntu_bionic&version=10.4 and I have similar problem.

Solution:

replace this `0xA6A19B38D3D831EF` with key found on mariadb page. in my case `0xF1656F24C74CD1D8`

curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=`0xA6A19B38D3D831EF`" | sudo apt-key add

**Comment by tsilefy** [comment]
For those still with the same problem (I had it with MySQL 8 on a fresh Ubuntu 18.04), [this](https://linuxer.eu/apt-key-gpg-keyserver-receive-failed/) solved my problem. In this case, it's Spotify but it works with any other repository.

> `$ wget -q "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA87FF9DF48BF1C90" -O- | gpg --dearmor > spotify-A87FF9DF48BF1C90.gpg
$ sudo mv spotify-A87FF9DF48BF1C90.gpg /etc/apt/trusted.gpg.d/`

1- download the key
2- pass it to gpg to turn the ASCII into binary (unwrapping)
3- move the new file to apt's keyring.

After that, I was able to do apt update and to install.

**Comment by ip11** [comment]
Follow the https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

sudo service mongod start (Will not work with WSL)

Step1 : sudo mkdir -p /data/db

Step2 : sudo mongo --dbpath /data/db 

This will start the mongod server in WSL without any additional start

Step3 : mongo 👍

**Comment by veloscillator** [comment]
This issue still exists in 20.04. The original workaround (calling `apt-key add -` manually) no longer works. @tsilefy's workaround above _does_ work. Is there any change of getting this resolved for good?

**Comment by onomatopellan** [comment]
@veloscillator which Windows build? in 20.04 libc6 is broken in WSL1 and shows a very similar error message. You can try  https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931 workaraound.

**Comment by aikoofujimotoo** [comment]
![image](https://user-images.githubusercontent.com/35658068/80303123-34baab80-87e9-11ea-8518-f5a32ad30a42.png)

Both didn't work.

**Comment by aikoofujimotoo** [comment]
![image](https://user-images.githubusercontent.com/35658068/80303157-603d9600-87e9-11ea-99aa-d192c54e44a9.png)

Both didn't work though.

**Comment by veloscillator** [comment]
> 
> 
> @veloscillator which Windows build? in Ubuntu 20.04 libc6 is broken in WSL1 and shows a very similar error message. You can try [#5125 (comment)](https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931) as workaraound.

This resolved my issue, thank you (I'm on 2004 19041.208).

**Comment by MaxPowerWasTaken** [comment]
I ran into this issue trying to install postgres on WSL(1).

with:

```
MYURL=https://www.postgresql.org/media/keys/ACCC4CF8.asc
```

both
```
wget --quiet -O - $MYURL | sudo apt-key add -
``` 
and 
```
curl -sL "$MYURL" | sudo apt-key add -
```
yield the following error:
```
gpg: can't connect to the agent: IPC connect call failed.
```

I can probably hold off on installing postgres on this machine for a month until WSL2 is available in a non-Insider build (corporate network). 

Can I expect this to be fixed in WSL2 (for ubuntu 20.04)? Thanks for all the work you all have done on this.

**Comment by fluffynuts** [comment]
I can't even use `apt-key add` because it also bombs out. So here's a super-manual way to get this done:
```
curl https://download.mono-project.com/repo/xamarin.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/mono.gpg
```

Putting this here in case I'm not the only person for whom this is a mission :/

**Comment by neozeed** [comment]
I have a Pi4 running Linux version 4.4.0-19041-Microsoft

root@DESKTOP-BBF5IEP:~# curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5523BAEEB01FA116" | sudo apt-key add
Illegal instruction (core dumped)

I can't even apt-get update on either Ubuntu 18 or 20.  At best the dirmngr crashes or trying to add keys results in an Illegal instruction.  Is there anything about running on Cortex-A72's?   This is feeling like PowerPC all over again...

**Comment by cesarau04** [comment]
> 
> 
> For those still with the same problem (I had it with MySQL 8 on a fresh Ubuntu 18.04), [this](https://linuxer.eu/apt-key-gpg-keyserver-receive-failed/) solved my problem. In this case, it's Spotify but it works with any other repository.
> 
> > `$ wget -q "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA87FF9DF48BF1C90" -O- | gpg --dearmor > spotify-A87FF9DF48BF1C90.gpg $ sudo mv spotify-A87FF9DF48BF1C90.gpg /etc/apt/trusted.gpg.d/`
> 
> 1- download the key
> 2- pass it to gpg to turn the ASCII into binary (unwrapping)
> 3- move the new file to apt's keyring.
> 
> After that, I was able to do apt update and to install.

This worked for me in the lastest WSL ty

**Comment by brunoschmidt** [comment]
Just for reference.
The bug affecting dirmngr is with WSL support for nanosleep.
There is a workaround available here:
https://github.com/microsoft/WSL/issues/4898#issuecomment-680915619

It works for me.

**Comment by onomatopellan** [comment]
Finally latest Windows update brings nanosleep support in Ubuntu 20.04 WSL1.

[KB4571756 (OS Build 19041.508)](https://support.microsoft.com/en-us/help/4571756)
