### ISSUE TITLE
Cannot access a specific location using explorer.exe

### ISSUE THREAD

**Issue by Zeraflut** [Microsoft/WSL#3342]
Hello,
When I'm running the Windows File Explorer using the command `explorer.exe`, a window to the quick access appears without any issue. 
But when I try to add a path to the command line, it always leads to the native "Documents" folder, even if I use random characters (e.g. `explorer.exe hkhnds`). 
The only exception is when I try to access the current location (`explorer.exe .`). It leads to the System32 folder where bash.exe is located in this case, even though it's not supposed to open there either.
I just can't understand this behaviour. Have someone an idea?

Windows build number: version 1803 (build 17134.112)

**Comment by shoffmeister** [comment]
Try, for instance, `explorer.exe 'C:\Users\youruser\Pictures'` - i.e. use single ticks to quote the argument. The backslash is the Linux escape character.

Alternatively, escape the escape, `explorer.exe C:\\Users\\youruser\\Pictures`

**Comment by Zeraflut** [comment]
That works indeed, thanks^^ 
I guess the path needs to be written using the Windows' language... 
But that doesn't explain the issue with the dot.
So, how to access the current location with the dot that isn't working?

**Comment by therealkenc** [comment]
> when I try to access the current location

You didn't specify your "current location", but I assume you mean #2004. `explorer.exe .` works okay here assuming your CWD is in `/mnt/c/Users/you/Pictures`.

**Comment by Zeraflut** [comment]
When I'm in the home directory of WSL (`/home/username`) for example, and I use the command line `explorer.exe .`, the File Explorer opens in the System32 folder where `bash.exe` is located, even though the home directory's Windows path looks more like `C:\Users\username\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home` for me.

@therealkenc In the thread you linked, to access its location, they use the path `%localappdata%\lxss\home`, but that's much shorter than in my case... So much more convenient to use as it is.

The only solution I found for my case is to set a variable in my `.bashrc` to my Windows home directory path but to be honest, I hoped for a better solution...

Well, that being said, thank you for your time and help^^

**Comment by shoffmeister** [comment]
> I guess the path needs to be written using the Windows' language...

No. The path just needs to be specified in a way that 
a) it "makes sense"
b) explorer.exe is able to do something useful with it

Having single backslashes in the argument will make the shell (bash) assume escape, so C:\Users is what _you_ see, not what the shell sends (it sends C:<escaped \U>sers). Send nonsense to explorer.exe - explorer.exe ignores the nonsense.

Your "." is the current working directory. Bash shell expansion should resolve that to something and the launch explorer with that. Given
```
cd ~
explorer.exe .
```
I _could_ expect my Linux home directory to pop up in Windows Explorer. Microsoft do not support this yet.

An alternative expectation could be C:´\Users\myuser\Documents - because explorer.exe is (for now) not supposed to get access to the Linux file system, so explorer.exe would not get a valid path and this default to the Documents folder.

But System32, I do not reasonably expect.

Do note that the following
```
cd /mnt/c/Users/myuser/Pictures
explorer.exe .
```
meets (my) expectations.

All this probably makes a whole lot of more sense once you are (more) familiar with the Linux shell (most often bash).

**Comment by Zeraflut** [comment]
@shoffmeister I'm quite familiar with Bash^^

But actually not that much with Windows... If the Windows File Explorer can understand the path behind the dot when it's something like:
`/mnt/c/Users/myuser/Pictures` which equals `C:\Users\youruser\Pictures`
I don't understand why it can't when it's:
`/home/user` which equals `C:\Users\youruser\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home`

I think it wouldn't have been too difficult to make the root location equal to this `C:\Users\youruser\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\` for the File Explorer

But I suppose I just have to admit that it's not working like that...

**Comment by therealkenc** [comment]
> I don't understand why it can't when it's:
/home/user which equals C:\Users\youruser\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgs\LocalState\rootfs\home
> ...
> I think it wouldn't have been too difficult to make the root location equal to

No, that [is difficult](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/). You will not find the path you cited anywhere in the MSFT documentation on WSL. If it were simple it would work.
