### ISSUE TITLE
Use of OpenSSH Control-Master on drvfs freezes process on poll()

### ISSUE THREAD

**Issue by blami** [microsoft/WSL#3370]
* Your Windows build number: Microsoft Windows [Version 10.0.17134.137]

* What you're doing and what's happening: 
After updating to 1803 I moved my ~ to my ``%HOME%/wsl`` for convenience. Everything works well so far except using Control-Master channels for multiplexing SSH connections. Running ``ssh user@host.domain -N -M -S ~/test`` succesfully creates socket and establishes connection for master channel. However, when I am trying to leverage multiplexed connection by running ``ssh user@host.domain -tt -S ~/test`` client process gets stuck on ``debug2: fd 3 setting O_NONBLOCK``. When putting my socket to root filesystem it works well.

My drvfs is mounted with all necessary metadata:
```
C: on /mnt/c type drvfs (rw,noatime,uid=XXX,gid=XXX,umask=2,fmask=1,metadata)
```

* What's wrong / what should be happening instead:
Client should not get stuck, instead it should set fd 3 to O_NONBLOCK and continue attaching to master session as it does when run with socket on root filesystem. 

* Strace of the failing command, if applicable:  
```
write(2, "debug1: auto-mux: Trying existin"..., 42debug1: auto-mux: Trying existing master
) = 42
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path="/mnt/c/Users/Foo/wsl/test"}, 110) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
write(2, "debug2: fd 3 setting O_NONBLOCK\r"..., 33debug2: fd 3 setting O_NONBLOCK
) = 33
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
write(3, "\0\0\0\10\0\0\0\1\0\0\0\4", 12) = 12
read(3, 0x7fffdbb74a30, 4)              = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}], 1, -1^C)    = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
```

* Workaround:
Configure ``openssh`` client to put sockets to root filesystem.

Please note that I can't upgrade to Insider build as this is enterprise managed machine not allowing me to do so by company policy.

**Comment by therealkenc** [comment]
> Please note that I can't upgrade to Insider build

Probably not necessary anyway. No news of fixes in this area since 17134 (that I'm aware of).

The `fcntl(3, ...|O_NONBLOCK` actually "succeeds". And interestingly enough, the `read()` doesn't block. It returns `EAGAIN`, correctly, without holding up right there. It is the `poll()` that sits there forever. Anyway, broken, obv, however you look at it.

I'm not real clear on the status of `AF_UNIX` on DrvFS, but I'd love to hear news. I tried to make use of it in a recent [experiment ](https://github.com/Microsoft/WSL/issues/1349#issuecomment-400936919) but failed miserably and had to fall back on tried and true `AF_INET`. This blog from [December 2017](https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/) (!) says "stay tuned":

> And, if you are wondering, there is already support for unix socket within Windows Subsystem for Linux (WSL), how does that work with the Windows unix socket implementation? Well, currently, it doesn’t, but stay tuned! 

So the "it doesn't" is a red flag. Your `poll()` might be blocking because there simply isn't anything to `read()`. But I really can't say, 'cause I'm still tuned. It would be nice to see this for the Fall release while we still have runway left. Good post.

**Comment by DarthSpock** [comment]
> Well, currently, it doesn’t, but stay tuned!

I thought they were referring to [this blog](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/)

That said, still plenty left to do per the [UserVoice](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/33247168-add-sock-seqpacket-and-sock-dgram-to-af-unix) for it. Agree we need news of where it currently stands.

**Comment by blami** [comment]
@therealkenc Thanks for great explanation!

**Comment by therealkenc** [comment]
> It is the poll() that sits there forever. 

There were some `poll(2)` fixes since 17134. Please try `1904[23]`, which might be better (or it might not). 

> [me] I'm not real clear on the status of AF_UNIX on DrvFS

The status of AF_UNIX on WSL2 9p is still sort of open. That probably deserves a new ticket for anyone interested.
