### ISSUE TITLE
Create a UNIX socket with filename containing colon on DrvFs will be create Alternate Data Stream.

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#3371]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17711.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```bash
$ mkdir -p /mnt/c/temp
$ python3 -c "import socket; socket.socket(socket.AF_UNIX).bind('/mnt/c/temp/:abcd');"
$ cmd.exe /c dir 'C:\temp' /r
2018/07/11  00:00    <DIR>          .
                                  0 .:abcd:$DATA
2018/07/11  00:00    <DIR>          ..
$ rmdir /mnt/c/temp
```
That path can not ``connect()`` from either linux or windows.

* What's wrong / what should be happening instead:
I think it should be create as "/mnt/c/temp/\uF03Aabcd" or cause an error.

**Comment by benhillis** [comment]
Thanks for reporting, I'll take a look at this.  I think this should probably use the same DrvFs filename escaping rules as regular files.

**Comment by benhillis** [comment]
Fixed in [17728](https://github.com/MicrosoftDocs/WSL/releases/tag/17728).

**Comment by therealkenc** [comment]
Was the verboten character the only problem? The [release notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17728-fast) state an ominous "Fix a number of AF_UNIX related issues" but there's only one here. 

Also (since I'm here) do all the 17xxx changes end up automagically in the _next_ 18xxx Skip Ahead release? That's kind of a rhetorical question, but the last time around (RS 4) it was getting confusing what was fixed in what release.
