### ISSUE TITLE
WSL Bash hangs on launch

### ISSUE THREAD

**Issue by moe2566** [microsoft/WSL#3392]
#### System Info
    Windows build number:  Microsoft Windows [Version 10.0.17713.1000]
    Distribution: Ubuntu 16.04.4 LTS
    Kernel: 4.4.0-17713-Microsoft

#### What I'm doing
    Running bash.exe

 #### What's happening
    When I run bash.exe the program opens, but hangs indefinitely.
    I need to start up 5/6 instances to get one that's working as expected.

Here are the .etl log files. `(had to change the extension to .txt in order to load it here)`

[lxcore_adss.txt](https://github.com/Microsoft/WSL/files/2210324/lxcore_adss.txt)
[lxcore_kernel.txt](https://github.com/Microsoft/WSL/files/2210325/lxcore_kernel.txt)
[lxcore_service.txt](https://github.com/Microsoft/WSL/files/2210326/lxcore_service.txt)

**Comment by benhillis** [comment]
Thanks for sending the traces.  It looks like either zsh is running into some kind of issue.  Would it be possible to try switching to bash to see if things still hang?

**Comment by moe2566** [comment]
Still hanging after switching to bash

**Comment by glenstarchman** [comment]
I had the same issue and narrowed it down to initializing nvm in my `.zshrc`.  In fact, I was unable to get nvm to function manually even from bash. In my case simply not using nvm and installing node globally made everything work fine.

**Comment by aaronpowell** [comment]
I'm experiencing the same issue as described by @glenstarchman, initialising [`nvm`](https://github.com/creationix/nvm) in my `.zshrc` file will cause really slow startup of `zsh` (and `bash` I think, but I don't use `bash` as my default shell 😝).

**Comment by arcanis** [comment]
Might be related to https://github.com/creationix/nvm/issues/1868

**Comment by tstackhouse** [comment]
Highly likely that @arcanis is correct.  I am experiencing the same issue.

**Comment by tomasaschan** [comment]
I'm seeing this too, and it's likely that nvm is the culprit here too (it is, if not the last, then one of the last things i changed about my startup scripts). Now my WSL Ubuntu starts so slowly that it in practice never reaches the prompt (the longest I've waited is a couple of hours).

I've tried uninstalling, resetting to factory settings etc, but can't make the behavior go away. What's my best course of action?

**Comment by eyalroth** [comment]
Did you check out #849?

**Comment by tstackhouse** [comment]
@eyalroth I'll look at that issue and see if there is any overlap, this was a while ago, and I believe I sidestepped the issue by switching from using `nvm` to manage node version on my WSL to using [`n`](https://github.com/tj/n), which works without issue. I was hesitant at first because I use `nvm` for windows, but that is an entirely separate project from `nvm` on *nix/OS X.

**Comment by kghost** [comment]
If you find an zombie after a hang, this is probably related to #3741
