### ISSUE TITLE
Why gNewSense4 was not included in Linux Distribution of Choice

### ISSUE THREAD

**Issue by BoQsc** [Microsoft/WSL#3396]
> Free as in freedom...
> gNewSense is a fully free software GNU/Linux distribution.
> Free software is software that respects your freedom. You can use it without restrictive licenses, make copies for your friends, school or business. To use free software is to make a political and ethical choice asserting your rights to learn and to share what you learn with others.
> 
> It is built by people across the globe who work together as a community and sponsored by the FSF (Free software foundation). We are open and anyone is welcome to join. Read more...
[http://www.gnewsense.org/Main/HomePage](url)

**Comment by therealkenc** [comment]
Distributions are submitted to the Microsoft Store by distribution maintainers. Answer to your question could be that the gNewSense4 maintainers:  (a) Aren't interested in submitting their distribution to the Store for reasons, (b) Are interested in submitting their distro to the Store but haven't gotten to it due to other priorities. More information can be found [here](https://blogs.msdn.microsoft.com/commandline/2018/03/26/wsl-distro-launcher/).
