### ISSUE TITLE
Question: how to create a windows shortcut for a Graphic linux app?

### ISSUE THREAD

**Issue by viebel** [Microsoft/WSL#3404]
I'd like to use the `konsole` terminal on WSL.
I was able to install it and run it by executing  `export DISPLAY=:0; konsole&` on WSL.

Is there  way to create a windows shortcut for being able to launch `konsole` from the Windows start menu?

**Comment by therealkenc** [comment]
#637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-239470325)).

**Comment by viebel** [comment]
@therealkenc thanks for the pointer.
I ended up creating a desktop shortcut with the following target `C:\Windows\System32\bash.exe -c "DISPLAY=:0 konsole"`

The only problem I have is now two windows: the `bash` window and the `konsole` window.
Is there a way to automatically close the `bash` window while keeping the `konsole` window open?

**Comment by goost** [comment]
This is what I use to start emacs without a window:
```vbs
Set oShell = CreateObject ("Wscript.Shell") 
Dim strArgs
strArgs = "wsl zsh -c 'DISPLAY=localhost:0 emacs'"
oShell.Run strArgs, 0, false
```
Saved as file `emacs.vbs`.
Source  
https://superuser.com/questions/140047/how-to-run-a-batch-file-without-launching-a-command-window

**Comment by viebel** [comment]
Thanks @goost it wirks fine.
I put the `.vbs` on my desktop.
Do you know a way to customize the icon?
Currently I have the default vbs icon and I find it a bit ugly.
![image](https://user-images.githubusercontent.com/955710/43359413-d8a635c4-92aa-11e8-8fa3-01d3ccbf425a.png)

**Comment by willbush** [comment]
Just wanted to point out, since this issue comes up in google searches, there's a utility called [wslusc](https://github.com/wslutilities/wslu/wiki/wslusc) that makes making links easy.

```bash
wslusc -g emacs -e "export GDK_SCALE=2;"
```
creates a normal desktop link whose target is `C:\Windows\System32\wscript.exe C:\\Users\\Will\wslu\runHidden.vbs bash.exe -c "cd ~; export DISPLAY=:0; export GDK_SCALE=2; emacs"`

**Comment by karlwilcox** [comment]
> Thanks @goost it wirks fine.
> I put the `.vbs` on my desktop.
> Do you know a way to customize the icon?
> Currently I have the default vbs icon and I find it a bit ugly.
> ![image](https://user-images.githubusercontent.com/955710/43359413-d8a635c4-92aa-11e8-8fa3-01d3ccbf425a.png)

If you do want to take the .vbs route to launching UI apps then put the vbs file elsewhere, right click on it in File Explorer and chose "create a shortcut". If you move that new shortcut on to the desktop then you can change its icon, again through a right click. I auto-start vcxserv and have various shortcuts on my desktop, e.g. terminator instead of the default terminal.

**Comment by ouweiya** [comment]
Use wslg.exe on Windows 11.
Create a shortcut and fill in the execution path.

`C:\Windows\System32\wslg.exe gedit`
