### ISSUE TITLE
export BROWSER='/mnt/c/path/to/ms_edge_binary'

### ISSUE THREAD

**Issue by snobu** [Microsoft/WSL#3405]
All WSL distros should export `BROWSER='/mnt/c/path/to/ms_edge_binary'` by default, so something like

```bash
$ python -m webbrowser -t "http://www.python.org"
```
can pop up a browser.

Also, this part (`/mnt/c/path/to/ms_edge_binary`) isn't trivial, you can't just launch the .exe since there's no .exe, there are just some shims, instead you need to do horrible things like

```
export BROWSER='/mnt/c/Windows/System32/cmd.exe /c start shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge'
```

which doesn't really work.

If you export `BROWSER='/mnt/c/path/to/chrome.exe'` it all works nicely, so that's what WSL should strive for with Edge.

I believe an extra shim, e.g. `WSLEdgeShim.exe` would be a good enough solution, as long as it's exported by default.

**Comment by benhillis** [comment]
@snobu - You can make it a bit less horrible:
`cmd.exe /c start microsoft-edge:`

**Comment by snobu** [comment]
That doesn't work. Actually my horrible example doesn't work either, i just tried to mock up a launch command.

```
Microsoft Windows [Version 10.0.17134.165]
```

**Comment by benhillis** [comment]
@snobu - Works on my box:
`ben@BENHILL-STUDIO:/mnt/c/Users/benhill$ cmd.exe /c start microsoft-edge:`

**Comment by therealkenc** [comment]
Ran course. If the ask here is "Chrome & IE good, Edge bad" there is the [Feedback Hub](https://support.microsoft.com/en-ca/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) and an Edge [Microsoft Edge platform feedback](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer) site.

**Comment by PAGuardado** [comment]
Hey! this is closed but i can't find the solution yet! 
is there any at all?
I want WSL to call for 'edge' whenever it needs a internet browser

**Comment by Biswa96** [comment]
You could try the new Edge+Chromium thing.

**Comment by PAGuardado** [comment]
I guess it could work, but I can't find how to even try it!
can you explain us how please?

**Comment by snobu** [comment]
Is runnong Windows binaries still a thing in WSL2?

**Comment by Biswa96** [comment]
Windows binary (PE) can be executed in WSL2 as same as in WSL1, like before. Just enter the executable name. For example, my Firefox is here `D:\Firefox\firefox.exe` then enter `/mnt/d/Firefox/firefox.exe`.

**Comment by therealkenc** [comment]
> I want WSL to call for 'edge' whenever it needs a internet browser

That "whenever" is the rub. It isn't straightforward to coax [`xdg-open(1)`](http://manpages.ubuntu.com/manpages/xenial/man1/xdg-open.1.html) into calling a windows browser using WSL interop, but it is possible. Long story short Ben's [answer](https://github.com/microsoft/WSL/issues/3405#issuecomment-407807031) from July 2018. Ref #3832 et al. You'll need to set the `$BROWSER` environment variable in your `.bashrc` yourself.

> You could try the new Edge+Chromium thing.

The original motivation for the ask in the OP [was](https://github.com/microsoft/WSL/issues/3405#issue-344251279) "you can't just launch the `.exe` since there's no `.exe`". Haven't looked but I doubt that changed new NewEdge. It's Chromium under the hood, but that is unrelated to the launch mechanism. 

> For example, my Firefox is here `D:\Firefox\firefox.exe`

Needless to say, `firefox.exe` isn't a problem because existence `.exe`.
