### ISSUE TITLE
What flags is glibc configured with, if glibc is being used?

### ISSUE THREAD

**Issue by ameisen** [Microsoft/WSL#3418]
The best I can tell, glibc is still being used as the libc for Ubuntu-WSL (as opposed to musl or a custom solution).

When I tried building glibc myself with what I considered to be sane configuration options... the system segfaults basically _immediately_ when using it. There's also the issue that I don't have any usable Linux kernel headers as NT is not Linux, so building it is... difficult.

I am doing systems-level development on WSL - I have a custom build environment/OS that can run atop Linux, and I want to make sure it runs atop Windows using WSL. It can somewhat work with Cygwin, but it functions far better on WSL. However, I need to be able to rebuild libc. I just don't know what configuration to use for it, since so far the configurations I've tried have failed relatively miserably.

**Comment by shoffmeister** [comment]
Microsoft supplies the kernel.

The rest comes from whatever distribution you are using - including the system's C library. Or, in other words, the complete userland is not from Microsoft ;)

**Comment by therealkenc** [comment]
> The rest comes from whatever distribution you are using 

He's rolling his own. Which is alight.

> There's also the issue that I don't have any usable Linux kernel headers as NT is not Linux, so building it is... difficult.

You can use the standard Linux kernel headers, say for Linux 4.4.0. WSL has no Linux kernel, but is (to a first order) Linux kernel ABI compliant. The specific kernel version for your headers isn't important because glibc doesn't care that much (because the ABI doesn't change for glibc's purposes that much). 

As for the configuration Ubuntu uses, you can grab that conveniently with `apt source glibc`. But the configuration Ubuntu uses isn't specific to WSL and this isn't a WSL question.
