### ISSUE TITLE
Problem creating kernel threads

### ISSUE THREAD

**Issue by diegoxfx** [microsoft/WSL#3465]
In my operative system class, we were creating some user and kernel threads in linux. Of course I was in Windows Bash, and when i tried to run the kernel thread, it failed. Here's the code

[ed: testcase -KC]
```
#include <iostream>
#include <sched.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>

using namespace std;

int k = 0;

int
hiloExec(void *arg) {
    int *p = (int *) arg;

    for (int i = 0; i < *p; ++i) {
        cout << "Hola: " << i << " k: " << k << endl;
        k++;
    }

    return 11;
}

int
main() {

    char *stackHilo;

    stackHilo = new char[1024];

    pid_t hilo;

    int *pVeces = new int;

    *pVeces = 1000;

    int flags = CLONE_SIGHAND | CLONE_VM | CLONE_FILES | CLONE_FS | CLONE_PARENT;
#if 0
    // failpath on WSL 18241
    flags |= CLONE_IO;
    hilo = clone(hiloExec, stackHilo +1024, flags, 
        pVeces, NULL, NULL);
#else
    flags |= CLONE_THREAD;
    hilo = clone(hiloExec, stackHilo +1024, flags, pVeces);
#endif

    if (hilo < 0) {
        cerr << "Error creando hilo: " << hilo << endl;
        exit(1);
    }

    for (int j = 0; j < 1000; ++j) {
        cout << "Otro hilo: " << k << endl;
        k += 4;
    }
    int status;

    cerr << "Hilo: " << hilo << endl;

    waitpid(hilo, &status, 0);

    cout << "Hilo termino con estado: " << status;

    return 0;
}
```
Later i tried to run it in Ubuntu, and it worked well.

**Comment by therealkenc** [comment]
Haven't run it by try dropping the `CLONE_IO`. It isn't supported right now AFAIK. If that's the case it would be nice if it were stubbed as a no-op....

**Comment by therealkenc** [comment]
This one turned out (mildly) more interesting than on first glance. Yeah, `CLONE_IO` causes an `EINVAL` alright. 

What was unexpected is even without the `CLONE_IO` WSL _still_ yields `EINVAL`. Turns out this is because the OP test case (semantically same as inside the `#if 0`) was "missing" `CLONE_THREAD`. Scary quotes because, oddly enough, you don't (it appears) have to specify `CLONE_THREAD` (_or_ `CLONE_VFORK`). A strict enough interpretation of the the LDP [`clone(2)`](http://man7.org/linux/man-pages/man2/clone.2.html) page doesn't actually imply you do, but it has never come up before. _"Who knew"_.

So there is _two_ parts to this one.
* stubbing `CLONE_IO`
* tolerating absence of `CLONE_THREAD`

`strace` log too pedantic to post because it's just `EINVAL` on the unsupported combos.

**Comment by Brian-Perkins** [comment]
Specifically WSL is not handling CLONE_SIGHAND in the absence of CLONE_THREAD, so two issues here:
    1) CLONE_IO can be ignored per man page
    2) CLONE_SIGHAND is independent of CLONE_THREAD
