### ISSUE TITLE
How to build u-boot with gcc-linaro-arm-linux-gnueabihf-4.9(32bit) in WSL?

### ISSUE THREAD

**Issue by xjfjian** [Microsoft/WSL#3472]
I want to build u-boot with gcc-linaro-arm-linux-gnueabihf-4.9(32bit) in WSL(ubuntu18.04)。
after install qemu and binfmt,I can run gcc-linaro-arm-linux-gnueabihf-4.9(32bit) in WSL。
but When run Build.sh,there are some errors:
Error:
root@XJFJIAN:/media/u-boot-imx# ./build.sh
Configuring for mx6qsabresd - Board: mx6sabresd, Options: IMX_CONFIG=board/freescale/imx/ddr/mx6q_4x_mt41j128.cfg,MX6Q,DEFAULT_FDT_FILE="imx6q-sabresd.dtb",DDR_MB=1024,SYS_BOOT_EMMC
  GEN     include/autoconf.mk.dep
cc1: error: /opt/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.2/include: Value too large for defined data type
cc1: error: include: Value too large for defined data type
cc1: error: /media/u-boot-imx/arch/arm/include: Value too large for defined data type
...........................

Build.sh content:
make mx6qsabresd_config ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

try to mount disk add -o nounix,noserverino
WSL not support this options
Error:
mount -t drvfs F: /mnt/f -o nounix,noserverino
mount: /mnt/f: wrong fs type, bad option, bad superblock on F:, missing codepage or helper program, or other error

**Comment by zjd1988** [comment]
Hi @xjfjian  how did you solve this problem?I run with the same porblem.

**Comment by xjfjian** [comment]
NO
I found a x86_64_arm-linux-gnueabihf version.But I'm not sure if there are any hidden problems in different versions of the compiler

**Comment by zjd1988** [comment]
ok ，thank you for your reply。
![image](https://user-images.githubusercontent.com/7134030/51887435-c2cd9980-23ce-11e9-8cb9-75224bc15530.png)

besides， “need-repro” meanning that WSL develper will fix problem？

**Comment by zjd1988** [comment]
Hi @therealkenc，  thanks for your explanation，I will open a new issue with template。

**Comment by therealkenc** [comment]
Thanks. Note that `make` isn't much of a reproducer though, because [`make(1)`](http://man7.org/linux/man-pages/man1/make.1.html) works fine. Your problem lies elsewhere, and tracking it down to the point of generating a tight repro -- meaning the minimum CLI command(s) needed to demonstrate a diverge from Real Linux -- is not going to be a straightforward exercise for you. I suspect the instant problem relates to the build requiring `cifs`, and WSL does not have `cifs`. Which means getting it working is probably going to require changes upstream to whatever it is a `u-boot-imx` entails. That's all speculation of course based on the information presented.
