### ISSUE TITLE
File permissions keeps changing from none to 777

### ISSUE THREAD

**Issue by terrywh** [Microsoft/WSL#3484]
I found this problem using git when pulling from server:
![image](https://user-images.githubusercontent.com/968222/44331306-ca8e2700-a49b-11e8-8086-09bf687c25ea.png)

then i discover:
![image](https://user-images.githubusercontent.com/968222/44331389-f0b3c700-a49b-11e8-9812-543a39a3e201.png)

that file permissions keeps changing: after the "ll" everything goes all right, but when I close all the consoles, and reopen the problem reappreared (maybe with another file....)

I'm on Windows 17741.rs5_release.180814-1430

Update:
I think this has to do something with that I access/update some of the files with a Dual boot Ubuntu 18.04 OS.

**Comment by DarthSpock** [comment]
Do you utilize the metadata option that you can configure in `wsl.conf`?

**Comment by DarthSpock** [comment]
You'll need to create it yourself. See https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/

**Comment by DarthSpock** [comment]
Also worth noting: If you're using a Windows IDE other than VS-Code and/or if you're running VS-Code but not the Insiders released last night, the metadata will be stripped so permissions will go back to the default. So that's another thing to account for.

**Comment by benhillis** [comment]
sudo bash -c "echo $'[automount]\noptions=metadata' > /etc/wsl.conf"

**Comment by terrywh** [comment]
metadata is no use in solving this problem ... :
![image](https://user-images.githubusercontent.com/968222/44442883-57092880-a607-11e8-9672-82ae679cfab4.png)

**Comment by onomatopellan** [comment]
> I think this has to do something with that I access/update some of the files with a Dual boot Ubuntu 18.04 OS.

That scenario is not supported. WSL file metadata is different than real Linux file metadata. If you use real Linux to manipulate WSL files you will lose the WSL file metadata. In later builds WSL tries to recover files without WSL metadata and that's why they end having 777 as file permissions.

**Comment by therealkenc** [comment]
> That scenario is not supported. 
> WSL file metadata is different than real Linux file metadata.

If that's _actually_ the scenario being described (I had dismissed "Update: think this has to do something with...Dual boot Ubuntu" as too unusual) then it isn't just _different_. If the OP is touching those files with `nfts-3g` in Real Linux, then the metadata is _nonexistent_. Because, before relatively recently, `NTFS` had never heard of them (in a user-facing way outside way outside WSL, anyway). And, by extension, neither does `ntfs-3g`. 

Which begs the obvious question: Could you update ntfs-3g to support them? And the answer is, ya, you could. That's actually an almost-interesting project idea.

@terrywh - If you are modifying those files in Real Linux (dual boot Ubuntu), how, precisely, are you accessing those files on a Real Linux boot? The directory was `/data/...` (not `/mnt/?/somthing`) on WSL. What directory, exactly, are you mounting and accessing on Real Linux? Because if it is `/media/you/.../Users/You/AppData/Local/Packages/.../rootfs/data`, well, that _probably_ would have been something worth mentioning. And is... "unusual".

**Comment by boan2010** [comment]
In WSL we do a checkout from the git repository to the WSL mount. When we edit files in our IDE running in Windows environment, it changes the permissions from 666 to 777. How can we prevent this?

**Comment by terrywh** [comment]
@therealkenc OK, I get where these problems accur. And I eager to see if ntfs-3g and WSL can work together. (FYI, I am accessing/writing these file from a Real Ubuntu OS (Dual boot from the same machine, And is mounting NTFS Partitions Directory `D:/data` to `/data`).
