### ISSUE TITLE
Typing ubuntu in explorer address bar does not give correct pwd

### ISSUE THREAD

**Issue by wolf99** [Microsoft/WSL#3513]
Build number Microsoft Windows [Version 10.0.16299.611] (1709)

Open Windows File Explorer to some directory, Type "wsl" or "bash" into the address bar and WSL opens with the same working directory as previously browsed to. Trying the same with "ubuntu" results in a working directory of ~.

I expected typing "ubuntu" to act the same as typing "wsl" or "bash" with respect to the working directory in the resulting terminal.

There is no output created for these scenarios when logging is enabled per [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by wolf99** [comment]
Thanks, this explains that it happens; but doesn't explain any reasoning...

Is running "wsl" otherwise just the same as running "ubuntu"?
- Does it source all .bashrc, .profile, etc upon launching all the same?
- How does it work in the case that I have multiple distros installed and *want* to open, for eg, SUSE with a particular working directory?

**Comment by therealkenc** [comment]
`wsl.exe ~ --distribution Ubuntu-18.04` will put you in your home directory of the Ubuntu-18.04 on [17666](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17666) or better. Ditto any other distro returned by `wslconfig.exe /l`.

[As an aside `wsl.exe --distribution Ubuntu-18.04 ~` errors out. Which gets a sad face.]

**Comment by wolf99** [comment]
@therealkenc This is actually the opposite of what I expected - I want to run ubuntu (or SUSE, etc) and have it launch with the directory open in Explorer (i.e. *not* `~`)

**Comment by therealkenc** [comment]
> 10.0.16299.611
> I actually meant "easily from Explorer without having to copy-pasta the location"

That was added in [17666](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17666)

**Comment by rodrymbo** [comment]
I'm probably wrong, but I keep thinking of the "current directory" versus "home directory" result as an attempt to match what you see under the heading `INVOCATION` in `man bash` – which also has an explanation of what startup files (`.bashrc`, `.bash_profile`, etc) are executed under the various options. 

I'm also thinking this will remain frustratingly inconsistent until #3246 and cousins are fixed -- neither `wslpath -u` nor the various "run bash in the current directory" options work properly for certain non-fixed but otherwise properly mapped and mounted drives, e.g. Veracrypt, even with NTFS filesystems and all the other bells and whistles.

**Comment by wolf99** [comment]
> > 10.0.16299.611
> > I actually meant "easily from Explorer without having to copy-pasta the location"
> 
> That was added in 17666

I look forward to seeing it in Redstone 5 release then 🙌
