### ISSUE TITLE
MyDistribution name is listed on wslconfig instead of Kali

### ISSUE THREAD

**Issue by kiazhi** [Microsoft/WSL#3526]
Downloaded the Kali package and manually install the Kali appx. But when I using the `wslconfig /l` command in command prompt to list the distro, I found that the distro name from the list is showing `MyDistribution` generic name.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.492]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
![kali - mydistribution name issue in wslconfig list](https://user-images.githubusercontent.com/13409063/45133712-db080680-b1ea-11e8-957e-4c86d92cfde0.PNG)

* What's wrong / what should be happening instead:
It should not be displaying `MyDistribution`, I'm more expecting it to display `Kali` instead.

Not sure if the issue should be reported to Kali because it may be how the appx is built.

**Comment by Biswa96** [comment]
Kali Linux developers may forget to change distribution name in WSL-DistroLauncher project solution file. This is not a bug, just a copy/paste issue.

**Comment by tara-raj** [comment]
Thanks for pointing this out. We'll reach out to the Kali developers and get this changed

**Comment by kiazhi** [comment]
Thank you, @tara-raj.

**Comment by n8v8R** [comment]
W10 Pro x_64 v1903 b18362.267
____
@tara-raj could you please share a link through which KL devel been contracted or some response from the KL devel?

Because this has not been remedied when KL (DistroLauncher-Appx_1.1.4.0_x64.appx) is being downloaded from https://docs.microsoft.com/en-us/windows/wsl/install-manual it still comes up as `MyDistribution` and thus cannot be deployed that way. 

There is nothing in the documentation about potentially renaming the distro. If it were clear where the `MyDistribution` naming convention is located I could perhaps patch it.

**Comment by Biswa96** [comment]
@n8v8R You can use IRC to contact them. Link https://docs.kali.org/community/kali-linux-irc-channel. Or tweet them, link https://www.kali.org/about-us/.

**Comment by n8v8R** [comment]
I am about to head to IRC but since the matter been brought up here previously and mentioned that the KL devel would be contacted I have been wondering what has come of that initiative?

**Comment by n8v8R** [comment]
cross ref https://gitlab.com/kalilinux/build-scripts/kali-wsl-distrolauncher/issues/58

**Comment by mscraigloewen** [comment]
I've fixed the appx on the documentation page: https://docs.microsoft.com/en-us/windows/wsl/install-manual 

Your distro should install normally now.

**Comment by n8v8R** [comment]
@mscraigloewen Thank you, works now as expected
