### ISSUE TITLE
[Question] Can System32/bash.exe do X11 forward from a local Linux vm?

### ISSUE THREAD

**Issue by tuyenpm9** [Microsoft/WSL#3531]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
This is a question so, all version should be counted.
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:
I have an linux vm, and GUI with X-windows installed on it, I'd like to use `bash.exe` as remote GUI to that vm by using X forwarding.

   Maybe this is silly question but I don't have experience with this, just predict that can be happened.

**Comment by therealkenc** [comment]
If the question is: Can I run X clients on WSL and use Real Linux VM as the X server, answer is yes. Whether you are using a Xorg Sever on a Real Linux box or XQuartz or Xming or VcXSrv is the same from WSL's perspective. You are writing bytes down a socket. Details on how to configure various X servers can be directed to their proprietors. #637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799)).

**Comment by tuyenpm9** [comment]
@therealkenc : I still not have clear vision here, can you make more clear that in-case we have a vm that running x-server and I'd like to use `system32/bash.exe` as x-client, is that possible?

If not and I have to use another program like `VcXSrv` then is it possible to run x-server in a vm and the using `VcXSrv` as x-client?

**Comment by therealkenc** [comment]
> can you make more clear that in-case we have a vm that running x-server

The Linux X server commonly running in your VM is Xorg or Xwayland.

> and I'd like to use system32/bash.exe as x-client, is that possible? I'd like to use system32/bash.exe as x-client, is that possible?

`system32/bash.exe` is not an X client. [`xeyes`](https://www.x.org/releases/X11R7.5/doc/man/man1/xeyes.1.html) (for example) running on WSL **or** on your VM (either way) is an X client.

> is it possible to run x-server in a vm and the using VcXSrv as x-client?

VcXSrv is not an X client. VcXSrv is an **X** **S**er**v**e**r** (compiled with Microsoft **V**isual **c**). The hint is in the name.

_Yes_ it is possible to run `xeyes` in WSL using the Xorg/Xwayland server on your Linux VM for display. It is possible to use just about _any_ X Server (including VcXsrv).

Details on how to configure various X servers (be it Xorg or Xwayland or VcXsrv) can be directed to their proprietors.

**Comment by tuyenpm9** [comment]
@therealkenc : Thanks but please give me more. So `VcXSrv` is X-server for WSL because WSL just only provide/expose shell itself to users (via an terminal emulator `System32/bash.exe`) - So I can understand `VcXSrv` as a wrapper to provide X-server feature to WSL.

If I did have X window running inside my linux vm on local windows10 host, So I just need only an X-client that installed on windows10 host to connect to X windows inside my linux vm?

**Comment by therealkenc** [comment]
> Thanks but please give me more.

Only because it's late.

> So VcXSrv is X-server for WSL...So I can understand VcXSrv as a wrapper to provide X-server feature to WSL

Sort of, in the sense that folks _do use_ VcXSrv as an X Server for WSL. But VcXSrv is not a "wrapper" and is not "for WSL". VcXSrv is "for" any any X11 client application running on any operating that wishes to connect to it.

> So I just need only an X-client that installed on windows10 host to connect to X windows inside my linux vm?

I am not really sure how to answer that. If you want to run `xeyes` (or any X client app) then yes you would need to install it. To run `xeyes` you need two things. (1) You need `xeyes`. (2) You need an X Server (any X server) running somewhere.

Let's sum up so we can put to rest. "Yes" to all of the below:
* You can run `xeyes` in your Linux VM connected to the local X Server running in your Linux VM (obviously).
* You can run `xeyes` in WSL connected to the X Server in your Linux VM (less obviously).
* You can run `xeyes` in your Linux VM connected to VcXSrv instead of the local Linux X Server (common if you never installed an X Server in your Linux VM).
* You can run `xeyes` in WSL connected to VcXSrv (common but not special).
* You can run `xeyes` in WSL connected to a MacOS VM running the [XQuartz](https://www.xquartz.org/) X Server (let's call this one "not common").
* You can run `xeyes` in a MacOS VM connected to VcXSrv (because you lost a bet).

"No" to:
* You cannot run an X Server (that draws pixels) locally on WSL because WSL cannot draw pixels. So you'll need to use another X Server (any X Server).

**Comment by tuyenpm9** [comment]
I'd say I would need X server in linux vm expose its GUI app to windows10 host. I don't use GUI app of bash wsl.
