### ISSUE TITLE
memfd_create() is not available

### ISSUE THREAD

**Issue by josephapg** [microsoft/WSL#3542]
Windows build number: 10.0.17134.285
Distro: Ubuntu 18.04.1 LTS

I want to use [NGINX Unit](https://unit.nginx.org) but it fails with the following error:
```
{
    "error": "Memory allocation failed."
}
```

Here's the content of `/var/log/unit.log`:
```
[info] 7148#7148 discovery started
[notice] 7148#7148 module: python 3.6.5 "/usr/lib/unit/modules/python3.6.unit.so"
[info] 7150#7150 controller started
[notice] 7146#7146 process 7148 exited with code 0
[info] 7151#7151 router started
[alert] 7150#7150 *3 memfd_create(/unit.7150.7fd46a63) failed (38: Function not implemented)
[alert] 7150#7150 *4 memfd_create(/unit.7150.aca6c7) failed (38: Function not implemented)
```

This happened when I tried to configure it using
`curl -X PUT -d @/path/to/configuration.json --unix-socket /run/control.unit.sock http://localhost/config/applications/app_name`

**Comment by therealkenc** [comment]
Ref #1209 for sport. I had forgotten it was left open as a landing zone for memfd and then closed it because the use case was satisfied.

**Comment by therealkenc** [comment]
Query for the devs: How "doable" is `memfd_create()` given the plumbing WSL has on hand? Normal "if it were easy it would exist" rules apply, natch. But I'm curious if it is in the realm of reasonably possible, or a bridge too far for the foreseeable future. Put another way, is lack thereof due mostly because it is fundamentally going to be hard (colloquially, "impossible") to map the behavior onto what you got, or because there is not a lot of demand (fairly demonstrably, given the large swaths of Linux-land that don't need it). I have some time-sink code that could use memfd, but upon thinking about it for a minute and hypothesizing on WSL internals I'm starting to wonder if this is an "straightforward to ask but hard to do" kind of thing.

**Comment by Brian-Perkins** [comment]
We have thus far avoided implementing memory-backed files (memfd, tmpfs, et al.), instead relying on the system drive for temporary storage (aka really slow memory). We could do something similar here, in which case it would just be a little bit of infrastructure to handle the lifetimes of "anonymous" files. A better solution would require plumbing in some real tmpfs concepts, and that will be quite a bit more work, though I am not aware of any technical blockers.

**Comment by therealkenc** [comment]
Appreciate the reply Brian. My headspace when I wrote the query was in what you called "real tmpfs concepts" (which I know WSL doesn't have), but of course you can do anything `memfd_create()` can do with a real temp file (which is otherwise ignored) and a `mmap()`. Mild duh to self, thanks. Points to (rather obvious) approach for the time-sink code too. I just wasn't thinking about it straight, because my head was stuck in anonymous memory.

**Comment by incube8r** [comment]
Adding reference to NGINX Unit issue:
https://github.com/nginx/unit/issues/256

**Comment by linkmauve** [comment]
`memfd_create()`’s main benefit is to be able to place seals on the fd, so that other processes receiving this fd can know for sure it won’t e.g. shrink under their feet, this isn’t possible on Linux with other filesystems so far, including tmpfs.

**Comment by yecril71pl** [comment]
Firefox crashes on openSUSE 15.1.
