### ISSUE TITLE
WSL-Debian doesn't measure the network traffic

### ISSUE THREAD

**Issue by shunanya** [Microsoft/WSL#3544]
I have installed WSL-Debian on my W10 (Win 10 Pro 64 bit, v 10.0.17134).
Seems, all is OK so far. 
But when I have tried to measure network traffic by reading '/proc/net/dev' file I seen only zeros for all interfaces. Please note that any Linux network commands like wget, ping and others are working properly.
Note also that repeating of reading '/proc/net/dev' file gives the same result (only zeros).
What is problem? How can I measure the network traffic in such environment?
![capture](https://user-images.githubusercontent.com/853199/45593984-95de9400-b9a3-11e8-8809-dab15cb5cdc0.PNG)

**Comment by therealkenc** [comment]
> What is problem?

The problem is the values are stubbed in WSL.

> How can I measure the network traffic in such environment?

With Windows. From the WSL bash prompt, something like:
```
$ powershell.exe -Command "Get-NetAdapterStatistics"
```

**Comment by shunanya** [comment]
Thank you so much for concrete answer. Seems, it's old issue and MS want not to fix it at all.
Thus, probably, to be not loss a time I have to change my measuring bash script by calling powershell.

**Comment by therealkenc** [comment]
> it's old issue and MS want not to fix it at all

Interestingly enough no specific duplicate request I could find though. I don't think it is a case that MSFT doesn't "want" to fix it but rather it is a matter of priorities thing. There are lots of blocking scenarios that need work, and this scenario has a viable work-around with interop. There is also nonblocking scenarios that thousands of devs want enabled.

Your mentioning a script matters though, so thanks for that. If you have a _development use case_ for `/proc/net/dev` it helps prioritize. Uses cases sounds something like: "My bash script measure packet stats in order to [reason] and without those numbers I can't [something]". It doesn't sound like the use case here is "...in order to look at the pretty numbers". If that's the case who knows maybe you'll get lucky. It just hadn't been requested before (AFAICT). 

You can hold it open if you want (there are lesser requests open) which is why I didn't just tag this question asked/answered. Leaving it closed is okay too. It isn't like the MSFT devs don't _know_ it is stubbed. Either way, legit enough ask.

**Comment by zyfyy** [comment]
is there another way in wsl to count net speed?

**Comment by zyfyy** [comment]
> > What is problem?
> 
> The problem is the values are stubbed in WSL ref #602.
> 
> > How can I measure the network traffic in such environment?
> 
> With Windows. From the WSL bash prompt, something like:
> 
> ```
> $ powershell.exe -Command "Get-NetAdapterStatistics"
> ```
high cpu load when used on wsl.
