### ISSUE TITLE
X windows not on screen boundaries

### ISSUE THREAD

**Issue by Clovel** [Microsoft/WSL#3551]
* Build :  Microsoft Windows [version 10.0.17134.254]

* What is happening : Two screens, unplug one. WSL X windows that were on the other screens do not pop back to the remaining screen. 

* What should be happening instead : The windows should be moved to the remaining screens. 

Using vcXsrv v1.20.1.2 (31/09/2018), Ubuntu 18.04 distrib for WSL.

**Comment by therealkenc** [comment]
This behavior is determined by VcXsrv and/or your X window manager (if you are running one). You'll get better service on the question from the purveyors of those products. Tag linux-bevavior because you will (surely) see the same thing running a Real Linux VM with identical client-side setup. Ref #637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799)).
