### ISSUE TITLE
DBus machine ID not initialised

### ISSUE THREAD

**Issue by mdh34** [Microsoft/WSL#3552]
* Your Windows build number: 10.0.17134.285 & Ubuntu 18.04.

* What you're doing and what's happening:  Attempting to run `dbus-launch` fails.

* What's wrong / what should be happening instead: The DBus machine-id isn't initialised and is left empty, meaning that `dbus-launch` and associated tools fail with `machine ID '' looks like it's the wrong length, should be 32 hex digits`.

This can be fixed by running `sudo systemd-machine-id-setup` but should ideally be set on installation.

**Comment by therealkenc** [comment]
> should ideally be set on installation.

Sadly that ask (as phrased) is tag 'external' because MSFT/WSL does not control Ubuntu userspace or the Store App or the launcher. Alternatively WSL would need to support `systemd` per #994, which I think (?) might set up the machine id on startup if it is missing (if it doesn't, it could). Or WSL `init` could do more `systemd` things per #2530.

**Comment by therealkenc** [comment]
Closing since there isn't a WSL actionable. You could _try_ asking Canonical to update their [launcher](https://github.com/Microsoft/WSL-DistroLauncher) and make `systemd-machine-id-setup` part of install process. More practically, run the command yourself as suggested and grumble under your breath a little when you hit the enter key.
