### ISSUE TITLE
Enable/Install WSL within a Docker Windows container

### ISSUE THREAD

**Issue by Natone16** [Microsoft/WSL#3555]
Hi everyone,

I am wanting to enable and install the Windows Subsystem for Linux (WSL) feature from within a Docker windowsservrecore container.
However, due to the fact that Docker containers are more like full-environment-processes than VMs,
and because WSL feature installation requires a 'system reboot'; this has proven troublesome.

I have seen solutions that other people have figured out for installing features that normally 'require reboot' in a Docker windows container.
- e.g. Active Directory support: https://blogs.msdn.microsoft.com/containerstuff/2017/01/30/create-a-container-with-active-directory-support/
- e.g. Server Media Foundation: https://forums.docker.com/t/installing-server-media-foundation-in-a-docker-container/23587

So I was wondering if anyone had any thoughts or has managed something similar for getting WSL to install in a Docker windows container?

Thanks in advance.

**Comment by chuckatkins** [comment]
@therealkenc this was closed a year ago but there's no reference or followup pointing to a resolution.  Is this possible?  Does installing wsl into a servercore container work now?  How is it done?

**Comment by therealkenc** [comment]
There were no takers on your question is all. Generally if an issue submission can be turned into something along the lines of "WSL is failing with this syscall, which differs from Real Linux" it'll get a look in this bug tracker. This one was of the "I was wondering if anyone had any thoughts" variety, and long-short no one did. How can "it" be done? Dunno. Broadly speaking the precept "install WSL in a Docker container" isn't very well formed; WSL1 is a kernel driver that gets install (loaded into) the NT kernel, which isn't on planet Docker. If you are looking to install _Ubuntu_ in a Docker container, that's well formed, but doesn't appear to be the ask, whatever the ask may be. You'll usually get more eyeballs in a discussion forum rather than this WSL bug tracker.

**Comment by chuckatkins** [comment]
Fair enough.  I only asked here because it's the only place I saw someone else, @Natone16, trying to articulate what I was trying to do and also failing at it.  I'll follow up in another venue to try to get more information.

**Comment by JasonDictos** [comment]
I think it should be possible to install wsl1, as it does not use the hypervisor, something like:
```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```
However you'll have to mount the .wim from the installation media as the windows containers don't come with those present

**Comment by robertoandrade** [comment]
I'm actually trying to do the same on a Windows Server 2022 container and am facing issues with DISM not being able to enable the WSL feature (although Virtual Machine Platform does get enabled ok when trying to enable WSL1 using: `wsl --install --enable-wsl1 --no-distribution` for testing). Same happens when trying to enable it directly with DISM, issue being primarily with the "sources" not found, but even after mounting the .wim from the Evaluation installation media into the container and although `Dism.exe /Online /Cleanup-Image /restoreHealth /source:C:\sources` succeeds trying to enable the WSL feature right after fails the same way with the same error code:

```
The source files could not be found.
Use the "Source" option to specify the location of the files that are required to restore the feature. For more information on specifying a source location, see https://go.microsoft.com/fwlink/?LinkId=243077.
```

Since it's been a few years since this has been asked I was wondering if anyone else had any new pointers?

**Comment by robertoandrade** [comment]
Ok, after trying a few paths I was able to mount the Windows Server 2022 Host `c:\windows\winsxs` folder into the container and run `dism.exe /online /enable-feature:Microsoft-Windows-Subsystem-Linux /all /source:c:\sources` (where `c:\sources` is the mount point of the host folder) and got it to be successfully enabled, although it does ask for "rebooting" the machine, so proceeding now with the `wsl install` command to see if I'm able to get WSL1 running in the container 🙏

**Comment by robertoandrade** [comment]
Funny enough when finishing the installation I get an expected error like:

```
The package could not be installed because the Windows Firewall service is not running. Enable the Windows Firewall service and try again.
```

🤷
