### ISSUE TITLE
I/O error when writing non-UTF8 bytes to the console

### ISSUE THREAD

**Issue by Random832** [microsoft/WSL#3563]
When writing a string that contains invalid UTF-8 bytes to the console, write(2) returns an error status [EIO].

Results are inconsistent. When I tried to create "realistic" test cases like 'Hello, \x93world\x94!', it stripped out the offending bytes instead of returning the error. Writing a string containing only invalid UTF-8 bytes and control characters (e.g. echo $'\x80') seems like the most reliable way to produce the error.

The typical behavior on a real Linux terminal emulator would be to replace all offending bytes with the replacement character, rather than stripping them out. There is no part of the tty system that would allow an error to be returned.

**Comment by mpa7** [comment]
Your Windows build number: (Type ver at a Windows Command Prompt)

10.0.17134.286 (also 10.0.17763.1)

What you're doing and what's happening: (Copy&paste specific commands and their output, or include screen shots)

I was using curl and neglected to redirect binary output.  Similar to below but this forces terminal output via -o:

curl -o - https://www.kernel.org/theme/images/logos/tux.png

What's wrong / what should be happening instead:

curl reports: 'curl: (23) Failed writing body (218 != 8657)'

On Linux no error is raised and the binary output is displayed as expected. While binary output is not generally useful in the terminal, it shouldn't cause syscalls to fail.

Strace of the failing command, if applicable: (If some_command is failing, then run strace -o some_command.strace -f some_command some_args, and link the contents of some_command.strace in a gist here).

Failing write:

78    clock_gettime(CLOCK_MONOTONIC, {3101, 467273000}) = 0
78    fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
78    ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
78    write(1, "\211PNG\r\n\32\n\0\0\0\rIHDR\0\0\0h\0\0\0x\10\6\0\0\0\36\312\267"..., 8192) = 218
78    write(1, "\333\262-kiu\253\367\252;\177Tu\253\273\325-\265\244\226\3249'\337s\356i\251\273\352\326\357"..., 7974) = -1 EIO (Input/output error)
78    clock_gettime(CLOCK_MONOTONIC, {3101, 494699000}) = 0
78    time([1537966647])                = 1537966647


For WSL launch issues, please collect detailed logs.

**Comment by therealkenc** [comment]
This is dupe #636 ([message](https://github.com/Microsoft/WSL/issues/636#issuecomment-391892207)). You've got a good repro, so maybe head on over to the [console tracker](https://github.com/microsoft/console) and try your luck. It still fails in Windows Console with build 18290, but is okay in [`wsltty`](https://github.com/mintty/wsltty) (aka `mintty`) per screecap.

Note `wsltty` operates on a `pty` (`/dev/pts/?`) and Windows Console operates on a `tty` (`/dev/tty?`). The `EIO` in your `strace(1)` log on the `write(2)` syscall suggests a WSL problem. It might be the Console folks end up booting you right back here. If that happens feel free to open up a new tracker. Whichever team, the problem has been outstanding since the summer of 2016.

![image](https://user-images.githubusercontent.com/7049700/49624512-8b221280-f986-11e8-8023-48557f106c0d.png)

**Comment by doggy8088** [comment]
@therealkenc this issue will hang my terminal window forever if I SSH another machine can try to write unsupported characters on the console.

I just tried [wsltty](https://github.com/mintty/wsltty).  It works perfectly. 👍
