### ISSUE TITLE
bring back alt+space hotkey to launch universal window menu to bash terminal emulator (conhost)

### ISSUE THREAD

**Issue by faridcher** [Microsoft/WSL#3578]
the title is self-explanatory, I think.

![image](https://user-images.githubusercontent.com/9982519/46247024-65bada80-c412-11e8-9f41-d42488d9d13b.png)

thanks

**Comment by DHowett** [comment]
@biswa96 what makes you say that?

**Comment by therealkenc** [comment]
Not a WSL actionable. The issue title isn't self-explanatory because that isn't a "bash terminal emulator" (there is no such) but that is beside. You could try the [console tracker](https://github.com/microsoft/console) but I hate to punt you there because I'm not sure this is in their wheelhouse either. Could try [Windows 10 feedback hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) failing else. Bonne chance.

**Comment by faridcher** [comment]
@therealkenc I hope the new title isn't wrong. thanks for the directions.
