### ISSUE TITLE
Error: 0x800704d5 after installing Docker for Windows

### ISSUE THREAD

**Issue by lwblackledge** [Microsoft/WSL#3595]
I have been using WSL for a couple of days and was adding some additional tools like `yarn` and `nvm` with no problems. 
I got to the point where I installed Docker for Windows (Version 18.06.1-ce-win73 (19507)).
After this install, and a reboot to enable Hyper-V, `wsl` no longer starts.

---

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.666]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1. Open 'powershell'
2. \> wsl
Error: 0x800704d5

* What's wrong / what should be happening instead:
WSL should start.
I have tried removing the distros via wslconfig, and also disabled/re-enabled WSL via Windows Features, to no avail.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
[logs.zip](https://github.com/Microsoft/WSL/files/2448295/logs.zip)

---

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by lwblackledge** [comment]
I still have had no luck resolving this issue and am not certain how to proceed short of a complete system wipe (which i cannot do).

Any assistance or suggestions would be appreciated.

**Comment by lwblackledge** [comment]
This appears to be related to my company's proxy / firewall settings blocking some communication. I'll close this issue.

**Comment by XoroshiroNOT** [comment]
Unlike the OP suggestion, proxy/firewall is not the issue for me.

Microsoft Windows [Version 10.0.16299.665] right now after update, but this issue occurred a few weeks ago and Windows was updated 1 month ago also. Since issue has not repeated, no logs captured.

[Moved here from a different thread]
I've been running WSL for about 6 months without issue and had opened 100s of bash shells manually, but just recently start launching bash multiple times from a single BAT file, which I've done about 10 times without issue (and 5 time subsequent to the error). This time got 'Error: 0x800704d5' for ONLY the first 2 out of 12 bash windows launched by this BAT:

TIMEOUT /T 16500 /NOBREAK
del testxoroshironot
copy testxoroshironot*.log resultsA*.*
start bash -c "./bigcrushallparallel1.sh" 'this one errored
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel2.sh" 'this one errored
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel3.sh" 'this and the rest were fine
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel4.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel5.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel6.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel7.sh"
TIMEOUT /T 350 /NOBREAK
start bash -c "./bigcrushallparallel8.sh"
TIMEOUT /T 350 /NOBREAK
start bash -c "./bigcrushallparallel9.sh"
TIMEOUT /T 400 /NOBREAK
start bash -c "./bigcrushallparallel10.sh"
TIMEOUT /T 400 /NOBREAK
start bash -c "./bigcrushallparallel11.sh"
TIMEOUT /T 450 /NOBREAK
start bash -c "./bigcrushallparallel12.sh"
pause

Perhaps knowing that, in at least my case, the issue is rare and apparently self-correcting within a 10 minute time frame, will help future efforts with similar errors.
