### ISSUE TITLE
[Question] Howto change cursor's speed

### ISSUE THREAD

**Issue by tuyenpm9** [Microsoft/WSL#3616]
**Please fill out the below information:**
Windows 10 version 1803 build 17134.112

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I feel slow when moving cursor around, I need to increase cursor's speed to improve workflow.
Use case: I install `archlinux` on vmware box and then open `wsl` (actual fallback to `bash.exe` of Ubuntu) then `ssh` to `archlinux` box, doing vim and other stuffs, the problem that I couldn't increase cursor's speed, I changed console and xorg cursor's speed but both didn't work.

* What's wrong / what should be happening instead:
As mentioned above, I expect a way to increase cursor's speed of `wsl`, howto?

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
No takers on the question. Generally speaking, you can `ssh` into remote Linux box (VM or otherwise) and use `vim` without any particular "slowness" (if that wasn't the case there'd be screeching to the contrary). If you are experiencing unusual slowness there isn't any knob to tweak to make it faster. Nothing is made _artificially_ slow. There is not enough to go on here regarding the nature of the ask for any concrete answer. Bonne chance.

**Comment by tuyenpm9** [comment]
Idk but we have these to increase speed of curosr on console: https://wiki.archlinux.org/index.php/Linux_console/Keyboard_configuration#Adjusting_typematic_delay_and_rate

and on X: https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration#Adjusting_typematic_delay_and_rate

I tried both but `bash.exe` terminal seem didn't recognize, so probably it lacks of support.

**Comment by therealkenc** [comment]
If you wanted to change the keyboard _typematic delay_ that is unrelated to "then ssh to archlinux box, doing vim and other stuffs". It is related to your keyboard settings. You want [this](https://bltt.org/adjust-windows-keyboard-repeat-rate/).

**Comment by tuyenpm9** [comment]
Exactly what I need but even with `short` of `Repeat delay` still feel in slow motion, but thanks, problem partial solved.

**Comment by therealkenc** [comment]
> but even with short of Repeat delay still feel in slow motion

I think I should probably clarify. What I meant was "**if** you wanted to change the typematic delay" that is how you do it, but I do not think that is _actually_ what you want. 

Changing your keyboard settings will change the behavior (user experience) of `notepad.exe` in Windows, as well. But you aren't complaining that `notepad.exe` feels like slow motion. You are complaining that `ssh` from WSL into a Linux VM feels like slow motion. I can't tell you why that is the case, because there is not enough to go on here regarding the nature of the ask for any concrete answer. I can tell you that, generally speaking, you can `ssh` into remote Linux box (VM or otherwise) and use `vim` without any particular "slowness" (if that wasn't the case there'd be screeching to the contrary). Which was the original answer given.

**Comment by tuyenpm9** [comment]
I don't think so, with two above links that I mentioned to change speed rate of cursor, I tested on native archlinux and result cursor's speed changed.

But the same configs, same os, everything is the same except that this time archlinux is on vm on windows10 host, two above setups didn't affect the cursor's speed.

Changing `keyboard typematic delay` of windows10 host does change cursor's speed in general and affect all windows10's applications, `base.exe` is also included.

Windows10 applied/forced `speed rate` of cursor on all its applications OR `bash.exe` terminal didn't respect/simulate archlinux's settings.

I expect `bash.exe` terminal has it own implementation to change cursor's speed. This is not a complaint but sound alike.

**Comment by therealkenc** [comment]
> I expect bash.exe terminal has it own implementation to change cursor's speed. This is not a complaint but sound alike.

Appreciate the follow up. If you meant "I expect WSL [to have] it own implementation to change cursor's speed" then you could have reported the absence of [`/dev/port`](http://man7.org/linux/man-pages/man4/mem.4.html) in the OP. Which is self explanatory and I took that you understood that for granted. Instead you said "still feel in slow motion" after changing your keyboard repeat rate and I made the (regrettable) mistake of attempting to clarify.
