### ISSUE TITLE
vim somtimes stops working after leaving bash opened for a long time

### ISSUE THREAD

**Issue by paladox** [Microsoft/WSL#368]
Leaving bash open for a long time can cause vim to sometimes not work. By not working I mean when you do vim some file it starts the editor but scrolling you can see that it is all jumbled around and you carn't edit properly. The only solution is to close bash and reopen it.

**Comment by JokerQyou** [comment]
I experienced this too. I left bash open for one night (~11 hours), vim and nano then both have this problem. Restarting bash did fix this temporarily for vim, but not for nano.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and has likely been fixed since it was opened. If not, please post a new issue in the [Console GitHub Repo](https://github.com/Microsoft/console)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
