### ISSUE TITLE
Installing intellij - error Startup Error: Unable to detect graphics environment

### ISSUE THREAD

**Issue by CORRET** [Microsoft/WSL#3684]
When I start Intellij

_sudo /usr/intellij/idea-IU-183.4284.148/bin/idea.sh

Startup Error: Unable to detect graphics environment_

**What is the problem ?**

**Comment by nyanhacker** [comment]
You better using in Native Windows instead Linux. Since WSL a few support of GUI

**Comment by therealkenc** [comment]
> What is the problem ?

The problem is Intetellij  unable to detect a graphics environment. See [this](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799). [Noting that you won't want compiz or unity or pretty much anything that thread has to say in order to run Intellij.]

> WSL only a few support of Graphical Programs

That isn't correct; WSL doesn't draw pixels and whatever syscall emulation gaps WSL does have isn't related to drawing them. That said, it is correct to say graphic applications aren't supported with WSL in the sense that it is exceeding difficult to identify syscall emulation problems with graphic apps because they tend to be large and unwieldy. See also [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq#can-i-run-all-linux-apps-in-wsl).

**Comment by RyanQuey** [comment]
For those who find this on Google like myself: 

WSL 2 does have support for intellij and can run it just fine, see here for instructions

https://github.com/lackovic/notes/tree/master/Windows/Windows%20Subsystem%20for%20Linux#run-linux-gui-applications

**Comment by shvo123** [comment]
nice https://github.com/lackovic/notes/tree/master/Windows/Windows%20Subsystem%20for%20Linux#run-linux-gui-applications
does not work for me 
 export DISPLAY=${DISPLAY:-$(grep -Po '(?<=nameserver ).*' /etc/resolv.conf):0}
Bad : modifier in $ (-).
