### ISSUE TITLE
Cannot run command with distribution whose name contains space

### ISSUE THREAD

**Issue by Martin1994** [Microsoft/WSL#3751]
* Your Windows build number:  10.0.17763.195

* What you're doing and what's happening:
1. Install a linux distribution using LXRunOffline. The name of the installed distribution contains space (e.g. `"a b"`).
2. Try to invoke with this distribution by `wsl.exe -d "a b"`. It reports `Error: There is no distribution with the supplied name.`
3. However I can switch the default distribution to `"a b"` using `wslconfig.exe /s "a b"`.
4. This problem does not exist in 17134.

* What's wrong / what should be happening instead:

`wsl.exe -d "a b"` should launch the distribution `"a b"`.

* For WSL launch issues, please collect detailed logs: [lxcore_etl.zip](https://github.com/Microsoft/WSL/files/2722362/lxcore_etl.zip)

**Comment by benhillis** [comment]
Distribution names cannot have spaces in them, their name must match the below regular expression:

^[a-zA-Z0-9._-]+$

What is the output of wslconfig.exe /list

**Comment by benhillis** [comment]
Distributions names cannot contain spaces.  Could you include in your trace the registration of the distribution via LXRunOffline?

**Comment by therealkenc** [comment]
I'm confused as well, since the first sentence is self-explanatory and the ask for a trace (_whatever_ trace) wouldn't shed any new light. The call is going to be "`WslRegisterDistribution("foo bar", "foobar.tgz")`". If that scenario isn't allowed yet [`WslRegisterDistribution()`](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslregisterdistribution) returns `S_OK` regardless, then that's a bug (although, not a particularly serious bug that requires any critical attention). If if it isn't allowed, it doesn't need a repro. It's a bog straightforward by-design tag. There isn't any question here that the distribution name contains a space.

**Comment by DDoSolitary** [comment]
@therealkenc I generally agree with you. But LxRunOffline doesn't use `WslRegisterDistribution` at all (though some of the previous versions do). It simply writes extract the tar file creates appropriate registry keys.

**Comment by therealkenc** [comment]
> doesn't use WslRegisterDistribution

Yes I assumed; I was giving benefit of the doubt for the case where the API _was_ being used. You can't stop people using admin privileges from corrupting their registry directly as is the case here. That much was supposed to be implied (because obvious: I can make my MS Office stop working too if I corrupt the registry).
