### ISSUE TITLE
IPFS cause LXcore.sys crashes (BSOD)

### ISSUE THREAD

**Issue by Po-wei** [Microsoft/WSL#3762]
**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows 1803 [Version 10.0.17134.472]
WSL ubuntu 18.04

* What you're doing and what's happening: 
Use amd64 version of go-ipfs for linux on Unbuntu 18.04
then I do
$ ipfs init
$ ipfs add [file]
$ ipfs daemon

keep ipfs daemon running about 10~20 minutes
Windows crashes with BSOD
SYSTEM_SERVICE_EXCEPTION
LXcore.sys

I run three time and they all crashe.

The dump file was sent to secure@microsoft.com

**Comment by Biswa96** [comment]
I can reproduce your issue in Windows 10 Pro insider build 18305. Though I am not getting BSOD/GSOD, after approximately 10 minutes `wsl.exe` process crashes, many Windows program become so crazy that I have to reboot my PC. Yes, the issue lies in the LxCore driver. Here are some Event logs from `Microsoft.Windows.Subsystem.LxCore`:


```js
ExecutablePath:ipfs Function:LxpSocketInetSetSocketLevelOption Line:3725 Message:AF_INET: (stub) Ignoring Socket option:15
ExecutablePath:ipfs Function:LxpSysDispatch Line:6133 Message:[0xffffff8d] Syscall 42 failed with unexpected error -115!
ExecutablePath:ipfs Function:LxpSysDispatch Line:6133 Message:[0xfffffffe] Syscall 262 failed with unexpected error -2!
ExecutablePath:ipfs Function:LxpSysDispatch Line:6133 Message:[0xfffffdfc] Syscall 202 failed with unexpected error -516!
```
These four lines repeats nearly 2000 times. I have also tried with disabling Windows Firewall, same error. Investigating...

**Comment by benhillis** [comment]
> Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues
