### ISSUE TITLE
Ubuntu on WSL hangs after launching windows applications from terminal

### ISSUE THREAD

**Issue by Ptheguy** [Microsoft/WSL#3769]
**Your Windows build number:**  Windows Version 10.0.17763.253
**What you're doing and what's happening:** I have `Atom` text editor installed on my Surface Pro 3. There is a path directory set up such that when I am in Ubuntu terminal, I can open the editor by typing `atom` and hit enter. Immediately after this, the line with my username and directory is returned, as expected. Recently, I updated Windows and I think there's a bug now. When I type `atom` and hit enter, the editor does open normally, however, my terminal hangs up--that is, the line with my username and directory is not returned and to restore functionality I have to either close and re-open the terminal or close the editor. In a sense, the terminal hangs up during time which editor is open. This was NOT an issue before, and it is really annoying as I need to be editing and compiling at the same time.  

**What's wrong / what should be happening instead:** Terminal hangs up after launching a Windows application and does not return to normal functionality until application is closed. This was never an issue before.

**Comment by CherryDT** [comment]
This is as it should be. The problem is running in foreground, hence blocking your shell. It's the same if you run any Linux GUI program. (I would consider it a bug that this didn't happen before.) If you want to run Atom in the background, use `&`:

```
atom &
```

(In case you don't see this _always_: I would guess that second, third, etc. instances of Atom may reuse the first instance, in that case the second instance would immediately terminate.)

**Comment by therealkenc** [comment]
>  (I would consider it a bug that this didn't happen before.)

I can't reproduce this here on 18312, and don't have a 17763 handy. Atom returns to the prompt and runs in the background (which is Windows Atom behavior). Impossible to tell whether there have been changes to interop since 17763 because release notes. "Recently, I updated Windows" isn't enough to go on, and it seems doubtful anyone is going to bisect this. Using `notepad.exe` rather than Atom as the interop case would be a start as well. Worth noting Electron does nontrivial things with the pty, and #3734 is flapping in the wind. Chalking this need-repro absent further information.

**Comment by francisli** [comment]
Doesn't sound like there's going to be a fix for this in WSL, but for the record, I can reproduce this behavior, and can confirm that this is different behavior after installing October 2018 update (17763). Unfortunately, after the terminal hangs with atom in the foreground, it does not respond to CTRL-Z. Also, adding & to the command causes atom to crash before launching. I'll search for and file a bug with the Atom project...

I never used notepad.exe from WSL before, but testing it now, it also exhibits this foreground behavior, but in this case, I can stop it with CTRL-Z and background it, or launch notepad.exe with &.

**Comment by francisli** [comment]
For anyone else landing here from search, activity probably related to this in the Atom project: https://github.com/atom/atom/issues/18702

**Comment by JacobDB** [comment]
I found a reasonable workaround for this; running the command as a background process works pretty much as you'd expect it to. Here's an alias I'm using for VS Code:

```sh
# Alias for opening files and folders in VS Code
code() {
    target_path=$(wslpath -a -w $(readlink -f $1)) # resolve the path
    (/mnt/c/Windows/System32/cmd.exe /C "Code $target_path" &) # open the path
}
```

It resolves a Linux path to a Windows path, then opens VS Code as a background process, and suppresses the output PID.

**Comment by felipecassiors** [comment]
To work around it, I'm using:

```bash
powershell.exe 'Start "C:\Program Files\Docker\Docker\Docker Desktop.exe"'
```

The question is: why this Issue is closed? I'm running the most recent version Windows and WSL and it's still having this weird behavior.
