### ISSUE TITLE
Powershell get-vm list Ubuntu as "state off" even if is running

### ISSUE THREAD

**Issue by pldg** [Microsoft/WSL#3772]
* **Your Windows build number:**  Microsoft Windows [Version 10.0.17763.253]

* **What you're doing and what's happening:**  Run `get-vm` from powershell to list all WSL instances, Ubuntu is actually running but is listed as `State Off`

* **What's wrong / what should be happening instead:** If a WSL distro is running, `get-vm` should return that distro istance as `State Running`

See the screenshot below

![image](https://user-images.githubusercontent.com/24630716/51107521-53ad4e00-17ef-11e9-835f-85c0a1c8a6a4.png)

**Comment by benhillis** [comment]
WSL is not a virtual machine, so not showing up via that powershell cmdlet is by design.

**Comment by pldg** [comment]
In [this talk by Sarah Cooley](https://youtu.be/Zi0eofqAkXU?t=391) it seems like she is had installed two distributions of WSL (Ubuntu 16.04 and Ubuntu 18.04). When she execute `get-vm` you can see `ubuntu` has **`State Running`** and `Ubuntu 18.04 LTS` has `State Off`

![image](https://user-images.githubusercontent.com/24630716/51134002-a65e2880-1836-11e9-8afd-40c05c354819.png)

**Comment by pldg** [comment]
Why if I run `get-vm` on my system it print out `Ubuntu 18.04.1 LTS` which is *not* a virtual machine but WSL?

**Comment by pldg** [comment]
My bad, I didn't remember I've installed Ubuntu 18.04.1 LTS also in Hyper-V, now it make sense, thanks :)

**Comment by therealkenc** [comment]
Yeah I can repro this here, oddly.
```
PS C:\Users\there> get-vm

Name               State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----               ----- ----------- ----------------- ------   ------             -------
Ubuntu 18.04.1 LTS Off   0           0                 00:00:00 Operating normally 9.0
```

Odd, because I run my Windows 10 inside a VM (Linux host) and it isn't even possible to nest virtual machines. [Side note I've been meaning to mention for about a year but didn't have an opportunity worth raising it... Doing network interfaces or CUDA with VM tricks isn't a viable solution if you got your Windows 10 in a VM. Raison d'être for WSL (if there is one) is to _not_ be a VM, but to improve Windows by native means. We already have virtual machine solutions out the yazoo.]

**Comment by therealkenc** [comment]
Deleted a comment myself. I probably had a (failed) Ubuntu VM from the middle of last year on my box too. Easy to double-take since the nomenclature is identical.
