### ISSUE TITLE
Documentation/information on what metadata is stored by WSL

### ISSUE THREAD

**Issue by ameisen** [Microsoft/WSL#3776]
Hello again,

I'm curious if there is any information/documentation related to what information (and by what mechanism) is being stored by the LXSS subsystem for files within its purview which are what get corrupted by Windows-native editors. I presume that they're volatile and subject to change.

I would like to modify a few text editors (mainly Notepad++, though if I have enough time I may consider making a Visual Studio extension?) to be able to save directly to LXSS. However, I don't have any information about what the data that needs to be restored is. I'd like to avoid reverse engineering it if possible. I've found it a bit difficult to find information about this since the variety of details about how LXSS/WSL actually work is scattered amongst various blog posts in different places, and I'm not even entirely sure how many of them are still up-to-date.

As an aside, I've noted that Visual Studio Code seems to have some limited awareness of WSL - is it aware of meteadata and thus capable of altering LXSS-owned files?

**Comment by Biswa96** [comment]
Only one man actually showed how WSL works with in-depth view.

**Comment by therealkenc** [comment]
Reverse engineering will not help you with `lxfs` because the action happens in the WSL driver, and you can't get at that driver from the Windows side even if you had every line of source code let alone documentation on how it worked. Think about it for a second. Do you think there is some conspiracy at Microsoft to corrupt those files on `lxfs` with Windows editors, but if only you knew some secret about how it `lxfs` internals worked, you could fix it with a patch to Notepad++? If you could access the `lxfs` driver from Windows seamlessly there wouldn't be an `lxss`. There would be `drvfs` full stop. 

Which it appears the devs are at least asymptotically getting [closer to](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18305), because you can use the new `wsl.exe --export` and `wsl.exe --import` to host the distribution entirely in a Windows location of your choosing.

You can add WSL metadata support to an Windows applications (like Notepad++) if you want, which is then accessible by both sides via `drvfs`. That is [documented](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_stat_lx_information) AFAICT. Doesn't even look particularly difficult.

Not really the place for the question however. You want to hang out in a place like [OSR](https://www.osr.com/) or similar. Now that metadata is part of the Windows API it isn't even really a WSL question, strictly speaking. Best I can tell you could call/use those APIs even if WSL wasn't installed, or if you never heard of WSL. They're just Windows APIs like all the rest.

**Comment by ameisen** [comment]
@therealkenc 

I'm a little put off by the tone of your post.

> And you can't get at that driver from the Windows side even if you had every line of source code let alone documentation on how it worked

I mean, full source code would make it pretty obvious via what mechanisms (ADS, *etc*) that metadata is being stored, which would make handling it far easier. Reverse engineering, or at least tracing, is just another mechanism to determine that.

> Do you think there is some conspiracy at Microsoft to corrupt those files on lxfs with Windows editors, but if only you knew some secret about how it lxfs internals worked, you could fix it with a patch to Notepad++?

Why would I think that? I'm unfamiliar with any APIs to deal with WSL metadata. My assumption has been that it uses ADS in NTFS, but I wanted to validate that that was the only place/way data was being stored, as if it is being stored in some other fashion that is non-trivial or non-obvious, I would still be corruption file metadata, even if I handled the alternate data streams. This would be why I asked if there was any information that I wasn't able to find about how WSL is storing the relevant data. I have to know how the data is being stored in order to handle it, after all.

> That is documented AFAICT. Doesn't even look particularly difficult.

I'm curious how you found that. I've been looking through MSDN/Docs for some time trying to fine information about `lxfs`. If `FILE_STAT_LX_INFORMATION` represents the *only* data that WSL is actually storing but normal windows Applications do not handle, then that should suffice. The problem is that I don't know if that's the *only* relevant data. Is making sure that `FileStatLxInformation` and `FileCaseSensitiveInformation` are properly restored/updated via `NtQueryInformationFile`/`NtSetInformationFile` all that is needed?

**Comment by therealkenc** [comment]
> [me:] That is documented AFAICT. Doesn't even look particularly difficult.

I should probably clarify that. Writing the metadata doesn't look particularly difficult. What to write there (starting with which `uid`/`gid` right out of the gate) is another matter. For that you are going to need to teach Notepad++ about WSL instances, and the WSL users inside those instances (and, in extremis, users in namespaces inside those instances). Doable. Calling that a small project would be a pretty bad mischaracterization tho, and that deserved correction. But I mean, go crazy....

> I have to know how the data is being stored in order to handle it, after all.

What but not how. I couldn't tell you how Real Linux get its `uid`/`gid` onto an `ext4` filesystem let alone they get onto NTFS. Easy enough to look with `ext4` because we've got the source code, but the answer is academic to calling `chown(2)`.

> I'm curious how you found that.

It's been in the WDK since [last spring](https://github.com/Microsoft/WSL/issues/2954#issuecomment-379745602). I found it in the WDK by looking when Biswapriyo asked.

> The problem is that I don't know if that's the only relevant data. Is making sure that FileStatLxInformation and FileCaseSensitiveInformation are properly restored/updated via NtQueryInformationFile/NtSetInformationFile all that is needed?

Short undisciplined answer would be "yep". But I can't give you definitive up/down answer to that, having not written a PoC I can link you to on github (call this an abundance of caution). The question is sort of analogous to asking "I know about `chmod(2)`, but is there other relevant stuff I need to know about?" There is no straight answer to that.  Constructive thing to do is set `FileStatLxInformation` and go from there, since even if it doesn't satisfy the sufficiency condition it absolutely positively satisfies necessity condition.

> I'm a little put off by the tone of your post.

Sorry, it isn't you. It is an accumulation of three years of posts regarding writing to `lxfs`. Also the niggling fact that this is a bug tracker with a template that says "Issues with missing or incomplete issue templates will be closed" which is hard to miss.

As an aside, and hesitantly, it is looking more-and-more to me like `lxfs` and `drvfs` are pretty interchangeable. ISTM `wsl.exe --import` wouldn't exist if it were a problem. I'm thinking heads would start exploding when folks started mashing their newly imported distro and it corrupted everything. Haven't confirmed that tho. One way to find out. Bonne chance.

**Comment by Biswa96** [comment]
I would suggest not to change any code in important porgrams like Notepad++ or VSCode etc. because internals of WSL is changing way faster. It may break those program. Another thing, only application of NTFS extended attributes can not solve the issue. Once Rich warned me about that (I forgot which thread).

**Comment by therealkenc** [comment]
> [deleted speculation from previous post] it is looking more-and-more to me like `lxfs` and `drvfs` are pretty interchangeable.... One way to find out.

Made me look. Nope. They are now allowing us to play fast and loose with the distro location, but convergence (if any) between `lxfs` and `drvfs` is still a ways off -- it appears after a quick look-see, anyway. If that ever changes I'm sure we'll hear an announcement including trumpets. [Chalk it up to wishful thinking on my part. I was pretty surprised to see the `--import` feature appear and read way too much into it.]

**Comment by therealkenc** [comment]
> I would suggest not to change any code in important porgrams like Notepad++ or VSCode etc. because internals of WSL is changing way faster.

Meh. You could fork. No harm there. I doubt `FileStatLxInformation` is going to move much because its published API. [I say this entirely in the hypothetical, mind, because _effort_. But I wouldn't deign to discourage anyone from trying.]

> another thing, ... application of NTFS extended attributes can not solve the issue.

Correct, with "can not" being operative. You cannot add `chmod` to Notepad++ with extended attributes (even if you wanted to know the details) anymore than you can add `chmod` to a Linux userspace application with knowledge of the `ext4` file layout.

Calling this a wrap since there isn't much to add and there is no WSL actionable.

**Comment by 0xbadfca11** [comment]
Unfortunately FileStatLxInformation/FILE_STAT_LX_INFORMATION is helpless for you.
This only can query, can't set or update.
NtSetInformationFile(..., FileStatLxInformation) always return STATUS_INVALID_INFO_CLASS.
At least, it is impossible to set metadata or copy from an existing file without knowing where metadata is stored.
No guaranteed way.

**Comment by therealkenc** [comment]
That's most unfortunate. Be interesting what the folks over at OSR have to say on why `NtSetInformationFile` doesn't work. It is possible you have to have a lot of specific ducks in line before making the call to `NtSetInformationFile`. Or it only works using `ZwSetInformationFile` from inside a driver. Or.... it just isn't settable by design, and WSL is diddling the EA from within `lxcore.sys` directly. Great info, thanks. But you've made me a little sad.

**Comment by Biswa96** [comment]
Is FileStatLxInformation==70 ?

**Comment by therealkenc** [comment]
> Is FileStatLxInformation==70 ?

Yes, but you are better off asking in a group that is knowledgeable about (and cares about) that sort of thing -- because you will get better answers. 

I never did a PoC last spring because it is probably a fools errand. Probably the right approach (given the present WSL model) is to marshal everything. Which is how devs look to be headed over in Microsoft/vscode/issues/ # 63155 and # 29194. You need intimate knowledge of the distribution to add a "log into WSL" button to Notepad++ anyway. Saving and restoring metadata _existing_ files serves marginal purpose, and you hard block on creating _new_ files without information about WSL users.
