### ISSUE TITLE
WslLaunch username support

### ISSUE THREAD

**Issue by dmex** [Microsoft/WSL#3786]
* Windows build number:
18312

* What you're doing and what's happening:
The wslapi header includes the WslLaunch and WslLaunchInteractive functions for launching WSL processes but it still hasn't been updated with support for specifying the user similar to the 'wsl.exe -u username' command from the command line.

* What's wrong / what should be happening instead:
Please include support for specifying the user when calling WslLaunch and WslLaunchInteractive.

**Comment by dmex** [comment]
@therealkenc 

This was a feature request not a question 😄

You can use commands like this with WslLaunch:
`L"su dmex -c \"wslpath 'C:\\Projects\\lxsstool.out' | bash\" "`

1) Switch user 'dmex'
2) Run command wslpath and convert the win32 path to wsl path (/mnt/c/projects/lxsstool.out).
3) pipe result from step 2 into bash and execute.

This works but correctly escaping the commands with the su command requires lots of trial and error which is time consuming and painful since wsl.exe supports the username parameter already.

**Comment by therealkenc** [comment]
(ftfy) Why is username not supported in the `WslLaunch()` api?

Beats being banished to User Voice. Held yours open because it's not a bad question.

If I had to guess, there has been no response because (a) not exactly a stampede of likes for your ask (b) the devs never noticed you posted (c) Contemplating the API changes would open glaring questions about why the first param is a distro name instead of pathname, and why `envp` is missing.

Work around would be to spawn `wsl.exe` with `CreateProcess()`. Maybe all that all answers the question. 😉

**Comment by therealkenc** [comment]
Going to close this on stale. Chances of a breaking API change to `WslLaunch()` seems small. For now this basically falls into by-design territory (the API is what it is). You can work around with `su` or `sudo login -f`. Might even call doing it that way a feature ([ref](https://github.com/Microsoft/WSL/issues/352#issuecomment-376021319)).
