### ISSUE TITLE
[Feature Request] Updates on getting OpenCL and CUDA GPU support?

### ISSUE THREAD

**Issue by chenchen2015** [Microsoft/WSL#3789]
Gratings WSL team,

I just want to again bring up the good old "OpenCL and CUDA GPU support" topic that has been discussed many times.

Numerous previous discussions (e.g. #829 #1788 #327 ) have directed people like me to [this highly voted feature request on User Voice forum](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support). As a matter of fact, it is the [HIGHEST voted feature request on the forum](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/filters/top) (which has more than 2 times the votes than the second requested feature, as of 1/20/2019). I saw a survey (#2422 ) done on August 2017, presumably to collect some early user preferences for initial project targeting. The last update on the User Voice forum was on April 2018 which was 10 months ago.

If possible, could you guys please let us know the status of this feature request and ideally, what's the estimated time frame of this project? Will we see an update in the next few months, or by the end of this year?

**Comment by lefnire** [comment]
Closed. Silence. Love it

**Comment by neil-119** [comment]
Guys, this is what our developers are mainly going to use WSL for (other than some types of IoT development). Would love to hear some update for this.

**Comment by chenchen2015** [comment]
Not trying to blame the team or anything, my guess is that this is one of those features that is too complicated for the team to address given the current support they are getting from MS and other factors internally and externally (third-party drivers, etc.).

Given the current feedback from everywhere, I would guess GPU support is not going to come in the near future. I have switched to dual boot native Ubuntu for that reason though it's not the ideal solution (definitely less convenient than WSL + GPU support).

**Comment by lefnire** [comment]
@chenchen2015 agreed. It's a shame VirtualBox / Docker can't (or too hard) to get GPU support either, dual-boot is only option at present

**Comment by therealkenc** [comment]
> my guess is that this is one of those features that is too complicated for the team to address

That doesn't appear to be the case. The devs have held two questionnaires on CUDA [here](https://github.com/Microsoft/WSL/issues/2422) and [here](https://twitter.com/tara_msft/status/1065327178215231489). If this was in the "yeah, never going to happen because impossible" category (like say, probably, `insmod native-linux-kernel-module`) then one wouldn't go to the trouble to conduct a survey.

The entirely-not-silent response the question posed in this duplicate issue submission [was](https://github.com/Microsoft/WSL/issues/829#issuecomment-342270608):

> We are quite aware of the demand of this feature and are working to see how best we can support it..... The challenge here is not just technical but also logistical and other. Because there are multiple players involved here, and not everything is in direct control. But, we are exploring all possibilities here.

Separately,

> what's the estimated time frame of this project?

Imagine, just for a moment, if opening a duplicate issue on a github bug tracker was actually an effective way to get an answer to that. Say, more effective than adding a me2 or +1 to an existing issue (also ineffective).

If there was an estimated time frame for CUDA on WSL it goes without saying that the UserVoice status would have flipped from "on the backlog" to "working on it" and you'd have got an email notification answering the rhetorical. The as-of-this-instant the answer being... _no_... there is no estimated time frame for this project. Which is a altogether different answer than there is no timeframe and never will be because impossible.

> It's a shame VirtualBox / Docker can't (or too hard) to get GPU support either

Indeed. This is a good-as-any reason to hold out optimism. Unlike say the ever-popular `nmap` ask there isn't a good (or at least, particularly ideal) CUDA story on Windows for the out-of-box Linux-first tooling people are asking for.

**Comment by erogol** [comment]
Here is how I got it working with a little bit of hacking http://www.erogol.com/using-windows-wsl-for-deep-learning-development/ 

Hope it helps!!

**Comment by chenchen2015** [comment]
GPU support seems to be on WSL 2 feature backlog as well (with high priority) according to [Microsoft Docs on WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2-are-there-plans-to-increase-hardware-support)

> **Can I access the GPU in WSL 2? Are there plans to increase hardware support?**
>
> In initial releases of WSL 2 hardware access support will be limited, e.g: you will be unable to access the GPU, serial or USBs . However, adding better device support is high on our backlog, as this opens many more use cases for developers that wish to interact with these devices. In the meantime, you can always use WSL 1 which has serial port and USB access. Please stay tuned to this blog and WSL team members on Twitter to stay informed about the latest features coming to insider builds and reach out to give us feedback on what devices you’d like to interact with!

Thanks, WSL team! Looking forward to see how this goes...

**Comment by therealkenc** [comment]
> WSL 1 which has serial port **and USB access**. 

That line has been nagging me a mildly, because it conflates USB device support with RS232 devices support that _happens_ to be implemented on a Universal Serial Bus. That confuses rather than informs the answer to the FAQ question "Can I access the GPU in WSL 2". There is no USB _device_ access in WSL1, which is #2195 #3745 and a dozen dupes with informal landing zone #412. 

[Funny thing, in the context of the question: you can do compute [over a USB interface](https://software.intel.com/en-us/movidius-ncs) -- if we had USB support.]

Which is **not** a complaint that USB device support is missing in either WSL2 or WSL1 (I have no horse in that race). Just that the whole "in the meantime" clause above will lead to people to believe they need to be on WSL1 for USB device support; which does not exist.

**Comment by petesherick** [comment]
At this point, you are better off spinning up a nix VM in the cloud

**Comment by turowicz** [comment]
> At this point, you are better off spinning up a nix VM in the cloud

But then you can't justify buying large GPUs for your engineers so they can play games in spare time.

**Comment by XenorPLxx** [comment]
This is one of the first Google results for "WSL Cuda". I guess it's worth mentioning that it's going to finally happen soon https://developer.nvidia.com/cuda/wsl.

**Comment by CrazedCoding** [comment]
@XenorPLxx Nice find.

Has anyone found any concrete examples or tutorials on WSL 2 and CUDA, yet??

**Comment by XenorPLxx** [comment]
There's a little bit of info [here](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gpu) and [there](https://news.developer.nvidia.com/microsoft-and-nvidia-announce-june-preview-for-gpu-acceleration-support-for-wsl/), but the timeframe states 'in few months', so I guess it's not coming to us that "soon".

**Comment by Erik-Sovereign** [comment]
It is stated here that a public preview will start in June https://news.developer.nvidia.com/microsoft-and-nvidia-announce-june-preview-for-gpu-acceleration-support-for-wsl/

(It seems you need to be in the Windows Insider Fast Ring and apply for the Nvidia Developer Program, both is free and easy to do)

**Comment by CrazedCoding** [comment]
Thank you for the swift replies, and useful links @XenorPLxx and @Erik-Sovereign 

I am perplexed. I am a member of both the Windows Insider Fast Ring, as well as the Nvidia Developer Program, but there still seems to be no support, or even documentation at this point...

I have been searching all day. I even attempted to see if it worked out-of-the-box as claimed, but WSL2 doesn't seem to come with Dxgkrnl, d3d12, or anything.

**Comment by CrazedCoding** [comment]
@everyone

https://blogs.windows.com/windowsdeveloper/2020/06/17/gpu-accelerated-ml-training-inside-the-windows-subsystem-for-linux/

Looks like it might be part of a a recent patch: Windows 10 Insider Preview 20150.1000 (rs_prerelease)

**Comment by ablankenship10** [comment]
Has anyone successfully gotten this to work? I am able to run a CUDA sample application, however having issue installing OpenCL afterwards (followed this: https://gist.github.com/Brainiarc7/dc80b023af5b4e0d02b33923de7ba1ed). `clinfo` shows `Number of platforms: 0`

Trying to get OpenCV for python3 working with GPU acceleration

**Comment by xxxzsx** [comment]
I need OpenCL to run olcvanitygen!

**Comment by turowicz** [comment]
It works although Triton workflows are not yet there.

**Comment by turowicz** [comment]
All frameworks and applications such as OpenCL and Triton need to adjust their code for WSL as the CUDA driver is not exposed in the same way as barebone driver. It is possible that in the next release of the driver Nvidia will modify it so it looks the same, but the current situation is different.

cc @deadeyegoodwin

**Comment by jeanmonet** [comment]
I couldn't find this information. Is there (or will there be) GPU/CUDA support in WSL 1?

**Comment by jeanmonet** [comment]
> Ohhhhh, hmmmmm, Maybe you just need WSL 2.

Went for WSL 2, works like a charm.

**Comment by nelsonjchen** [comment]
The CUDA GPU support is obviously out but if anybody is interested in OpenCL, it might be worth paying attention to this issue: 

https://github.com/microsoft/WSL/issues/6951
