### ISSUE TITLE
Introduction of a Windws Variable WSLHOME

### ISSUE THREAD

**Issue by tabedzki** [Microsoft/WSL#3801]
Hi, 
Is there a way to have WSL automatically include a variable in Windows called WSLHOME or something of that nature that would point to the Ubuntu location on the computer (something like `C:\Users\tabedzki\AppData\Local\lxss\root`)? I understand I can create these variables myself, just curious if it could be implemented natively.

**Comment by therealkenc** [comment]
No, for two reasons. (a) `...\Local\lxss\root` does not exist on the Windows side for your purposes unless or until the status of #1524 changes. (b) There is no single rootfs because you can have multiple distros installed.

You could [muck](https://github.com/therealkenc/EnumWSL/blob/master/EnumWSL/Program.cs) with the registry to find the relevant paths to the distros but you'd be on your own with that.

**Comment by tabedzki** [comment]
Ok, cheers.
Just curious, what do you mean that `...\Local\lxss\root` does not exist on the Windows Side for my purposes? That is the actual path that leads to my WSL configuration

**Comment by therealkenc** [comment]
> That is the actual path that leads to my WSL configuration

It does not. It leads to a bunch of files that look like they probably have something to do with WSL, that for your purposes don't exist. [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-use-a-windows-file-with-a-linux-app)
