### ISSUE TITLE
easy to fix kali linux wslregisterdistribution failed 

### ISSUE THREAD

**Issue by sambhavsurana** [Microsoft/WSL#3820]
Microsoft Windows [Version 10.0.17134.523]
So, i wanted to start kali on WSL and got this issue:
`WslRegisterDistribution failed with error:
0<random numbers>  : the parameters are incorrect `
`press any key to continue`
and when i pressed it just closed the window. 
to solve this i used the command
`services Lxssmanager start`
and it fixed it .i dunno how it happened but whatever

**Comment by mscraigloewen** [comment]
Hi @sambhavsurana , thanks for filing the feedback!

Do you remember what the `<random numbers>` happened to be? If so we can point you to what the problem was. If not, that's fine it appears to have been an issue related to the installation since the service wasn't running. I'm glad that you got it resolved!

I'm going to mark this issue as closed, since it has been resolved, but feel free to comment if you have any follow ups.

**Comment by sambhavsurana** [comment]
@mscraigloewen Lxssmanager was not started when i started my laptop

**Comment by mscraigloewen** [comment]
Thanks for the clarification :)

**Comment by sambhavsurana** [comment]
Also `<random numbers>` were 0*800703fa
