### ISSUE TITLE
explorer.exe cannot open URLs with arguments in them

### ISSUE THREAD

**Issue by cheshrkat** [Microsoft/WSL#3832]
Microsoft Windows [Version 10.0.17763.253] 
using WSL Ubuntu 16.04.5 LTS

Background: I have a release script which does a bunch of automated things, then guides the user through a couple of manual actions where they have to go to a URL. In other shells the script opens the URL for them to make things easier, but I discovered `explorer.exe` via WSL cannot open *URLs with arguments*. It can open URLs without arguments, so this seems like a bug. Albeit not the end of the world, still a bug :)

STEPS TO REPRODUCE...

These do work as expected (that is, the URL opens in the system default browser):
```
$ explorer.exe http://example.com
$ /mnt/c/Windows/explorer.exe http://example.com
```

These do not work as expected:
```
$ explorer.exe https://example.com?foo=bar
$ explorer.exe "https://example.com\?foo=bar"
$ explorer.exe 'https://example.com?foo=bar'
$ explorer.exe 'http://example.com?foo=bar'
$ explorer.exe "https://example.com\?foo\=bar"
$ explorer.exe 'https://example.com\?foo\=bar'
$ explorer.exe http%3A%2F%2Fexample.com%3Ffoo%3Dbar
$ explorer.exe 'http%3A%2F%2Fexample.com%3Ffoo%3Dbar'
$ /mnt/c/Windows/explorer.exe 'http://example.com?foo=bar'
```

Expected result:
URL opens in browser

Actual result:
Generic file explorer window opens

I did find this workaround:
```
$ cmd.exe /c start http://example.com?foo=bar
```

...although I've not yet tested it in my release script (it's something I can't test at home on a weekend :)). 

Raising a ticket anyway because it seems like a bug that some URLs will open with `explorer.exe` and others won't. If it's not considered a bug, this issue should at least tip others off to the workaround.

**Comment by therealkenc** [comment]
This is continuation #2835 formerly #1625 ([message](https://github.com/Microsoft/WSL/issues/1625#issuecomment-357015320)), others. Those talk about spaces a lot, but the problem is the escaping. You need to punch a quote through to the Windows side, otherwise that `?` is problematic. The quotes in all the variations you tried are being eaten by `/bin/bash`. [Trying to http escape the `?` was well, meaning but won't work in `cmd.exe` either for reasons unrelated to WSL.] 

You _might_ expect the following to work:
```
$ echo \"http://example.com\?foo-bar\"
"http://example.com?foo-bar"        <-- same string as you'd want use from a cmd prompt
$ explorer.exe \"http://example.com\?foo=bar\"
```
But it doesn't. It isn't clear to me whether that is by design or otherwise. Standard operating procedure seems to be to bounce it off `cmd.exe` or `powershell.exe` explicitly.

**Comment by cheshrkat** [comment]
Thanks for the info. Seems like the other ticket covers it; I'll run with the `cmd.exe` workaround in the meantime.

**Comment by pascal-t** [comment]
The `cmd.exe` workaround did not work for me. It opened the browser but the arguments were gone. 
Instead this worked: `rundll32.exe url.dll,FileProtocolHandler "https://url.com/path/index.php?arg1=foo&arg2=$bash_var"`
From https://stackoverflow.com/a/49115945

**Comment by ianisl** [comment]
In case someone needs this: the `cmd.exe` workaround works, but you need to escape `&` characters like so: `^&`. 

```sh
# Doesn't work
cmd.exe /c start '' 'C:\Program Files\Mozilla Firefox\firefox.exe' 'https://example.com?foo=bar&baz=bar'
# Works
cmd.exe /c start '' 'C:\Program Files\Mozilla Firefox\firefox.exe' 'https://example.com?foo=bar^&baz=bar'
```

The reason is that the URL argument contains no spaces, so WSL passes it to `cmd.exe` unquoted (see <https://github.com/microsoft/WSL/issues/2835#issuecomment-364475668>), which means the `&` character will be understood as a `cmd.exe` command separator, not a literal `&`.
