### ISSUE TITLE
New Explorer integration edge cases - /mnt/

### ISSUE THREAD

**Issue by refack** [Microsoft/WSL#3853]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  `10.0.18836.1000`

* What you're doing and what's happening:  
  1. Open Windows Explorer
  2. Browse to one the WSL distros
  3. Browse to `/mnt/`
  4. Click on any mount point

* What's wrong / what should be happening instead:
  * Network Error `0x80070035`

![image](https://user-images.githubusercontent.com/96947/52882576-24fbfd80-3136-11e9-872f-513e628c2ca8.png)

---

BTW browsing to the regular storage location shows the mount points empty, but working:
![image](https://user-images.githubusercontent.com/96947/52882627-4f4dbb00-3136-11e9-80bc-42ffd66f3318.png)

**Comment by Biswa96** [comment]
Looks like I'm not the only one digging WSL. It is related with WSL path translation. Waiting for future Insider builds.

**Comment by Biswa96** [comment]
It is related with WSL path translation. Wait for future Insider builds.

**Comment by SvenGroot** [comment]
This is by design. We don't let you navigate into DrvFs mount points through \\wsl$, for several reasons:

- Access would use the security context of the WSL init process, not the security context of the process accessing the file.
- In some cases, we found recursive file system access could lead to hangs or long delays.
- There is no benefit to doing this, since the files are available in Windows anyway so all this does is provide you with a much slower way of accessing those files.

Going directly through rootfs is showing you the mount point directories, but the actual mounts only exist in WSL so of course they're not visible there.

**Comment by refack** [comment]
> Going directly through rootfs is showing you the mount point directories, but the actual mounts only exist in WSL so of course they're not visible there.

That's what I'd expect as well (empty folder). An exception IMHO is a no no ¯\\_(ツ)_/¯

**Comment by therealkenc** [comment]
> * There is no benefit to doing this, since the files are available in Windows anyway so all this does is provide you with a much slower way of accessing those files.

That's semantically equivalent to saying there is no benefit to `mount --bind` in Linux because the files are there anyway.

But beggars can't be choosers and you get 100 points for the integration anyway. Nice work Sven. 💯

**Comment by SvenGroot** [comment]
@therealkenc However, `mount --bind` does not make you go through a communications protocol and an extra layer of abstraction (the WSL VFS layer), using potentially the wrong security context, and removing a bunch of features of the underlying file system (since not everything NTFS does is supported through WSL or the \\\\wsl$ view). ;)

**Comment by therealkenc** [comment]
Yeah. I "get it". So.... counting commas... is that three new User Voice entries or would just the one do? [don't answer that] 🐱‍👤

Again nice work.

**Comment by Biswa96** [comment]
SO why Plan9, not SMB? There are multiple layers in P9: LxssManager.dll --> p9np.dll --> p9rdr.sys --> rdbss.sys, any I/O performance issue for that?

**Comment by Biswa96** [comment]
SO why Plan9, not SMB? There are multiple layers in this P9 implementation: LxssManager.dll --> p9np.dll --> p9rdr.sys --> rdbss.sys, any I/O performance issue for that?
