### ISSUE TITLE
I don't Update

### ISSUE THREAD

**Issue by 0977906063** [Microsoft/WSL#3875]
OS build: 17736.316
I am a new user. I only use Linux distro and I want to update it. When I enter:
`sudo apt update && sudo apt upgrade`
and there were warnings:
`dpkg: warning: 'ldconfig' not found in PATH or not executable
E: Sub-process /usr/bin/dpkg returned an error code (2)`
I hope to help everyone, I thank you very much!

**Comment by mscraigloewen** [comment]
Hi @0977906063 , is this a fresh install? 
If you don't have anything in the distribution have you tried reinstalling?

**Comment by 0977906063** [comment]
I deleted all and reinstalled. And now it has another message: `E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
I run the command: `apt --fix-broken install`. It reports a new installation. When I agree to install, there is an error:
`dpkg: error processing archive /var/cache/apt/archives/libtk8.6_8.6.8-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/tcltk/x86_64-linux-gnu/tk8.6/pkgIndex.tcl', which is also in package fonts-dejavu 2.37-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libtk8.6_8.6.8-4_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`
I don't know what to do anymore.

**Comment by mscraigloewen** [comment]
I'll put the exact steps to setup your distro, could you follow them and let me know if you run into any errors?

---
Install [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab) from the Microsoft Store

Run the Ubuntu app from the start menu

Run these commands in the shell:
`sudo apt update`
`sudo apt upgrade`

---

After that you should be set up, and I'd be quite surprised if you encounter any errors since that is an incredibly common use case. Good luck! :)

**Comment by therealkenc** [comment]
> I deleted all and reinstalled. 
> [...]
> /var/cache/apt/archives/libtk8.6_8.6.8-4_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)`
> I don't know what to do anymore.

Re-categorizing need-repro. It wasn't clear in the OP this was off a clean install, and it looked like a question about vanilla apt/dpk borkage.

There isn't enough to go on here to offer any kind of constructive suggestions. That "deleted all and reinstalled" is carrying a lot of weight. If the repro here is do a `sudo apt update` as the first command off a fresh install of 18.04 from the Store, that obviously "works". There is another unknown variable.

Hail mary pass before this one dies, make sure you are on a clean install (again) and then as the first commands do:

```
$ sudo su
# export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# apt update
# apt upgrade
```

If either of those have the same warnings, then a `strace(1) log` per the deleted issue [template](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) might save this. If the problem is `apt upgrade` (OP doesn't say, but it looks like) then along the lines of:
```
# strace -f -o apt-update.strace apt update
```

**Comment by kcris** [comment]
Hi,

got the same problem after upgrading from 19.10 to 20.04
sudo do-release-upgrade -d
and after that, installation is borked

apt --fix-broken install
fails with ldconfig missing

and installing ldconfig fails because apt is in a wrong state

Thanks
