### ISSUE TITLE
curl causes ubuntu failure

### ISSUE THREAD

**Issue by HeroicMastodon** [Microsoft/WSL#3899]
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
restart to use nvm
nvm install stable
hangs after checksums

ctrl-c does not end the process.  Closing the window breaks ubuntu. (reopen ubuntu and nothing appears in the console) until restart.  Upon restart ubuntu works but nvm installation remains impossible.
rm -rf ~/.nvm 
sudo apt-get install nodejs
sudo apt-get install npm 
hangs on "setting up python 2.7"

upon uninstalling/reinstalling ubuntu apt no longer works and all "curl"s fail causing ubuntu to hang indefinitely.

**Comment by mscraigloewen** [comment]
Hi @HeroicMastodon !
What version of Windows are you using? (If you open up CMD and type in `ver` what does it say?)

I wasn't able to reproduce your issue running Debian and on a recent build. This is good news since the problem may already be fixed!

Are you looking to use nvm specifically, or just nodejs?

**Comment by HeroicMastodon** [comment]
UPDATE 
I had not yet upgraded to the October update in windows 10 yet.  This may have been what ultimately fixed the issue however it may have also been an issue with my antivirus containing the subsystem.  Either way it seems to have been fixed now.

**Comment by mscraigloewen** [comment]
Glad to hear it! :) Thanks for filing the issue, and if you run into anything else please feel free to post again.
