### ISSUE TITLE
Web servers can't work for some large files 

### ISSUE THREAD

**Issue by ChaosPivot** [microsoft/WSL#3908]
* My Windows build number:
 10.0.17763.348

* What you're doing and what's happening:  
1. Install the WSL.
2. Install nginx.
`sudo apt-get install nginx`
3. Create a nginx configure file.
`sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/my-website.conf`
4.Edit my-website.conf
`Server{
server_name website.my
root /var/www/html;
index index.html;
......
}`
5. Start the nginx server and edit my host file.
6. Then I can visit http://website.my 

* What's wrong / what should be happening instead:
When I copy a file to the web root directory like test.rar,if this file‘s size is bigger than 1Mb, When I vistit http://website.my/test.rar , then there is no response from the browser,and there is no error log in /var/log/nginx/error.log.
If the file's size is smaller then 1Mb, for example ,like 1Kb , I When I visit http://website.my/test.rar , the server works , and I can get this file.

I have also tried apache 2 , and this error still exists. But if I use python and php http server module just like `python -m http.server` Or 'php -s localhost:80` , this error disappears and I can get the bigger file.

**Comment by whitwhoa** [comment]
@ChaosPivot Were you able to find a resolution for this? I have also run into what I believe to be the same issue with nginx installed in wsl. I have one environment trying to serve an 18mb image which fails after client has downloaded about 10% of it, same with a 19mb .pdf file. 

I also have another environment that's serving many smaller files ~100, 50 of those being .bmp images that are between 300kb and 600kb. The majority of these files will load, however a handful (4-5) will only download partially, then once the client timeout is reached the browser shows the broken image icon.

For each instance, server returns an http 200 status code, and nginx does not log anything within the error.log file.

My first instinct was that I had botched (or forgotten to set something) in the nginx configuration, but so far I cannot seem to find anything that sticks out as being able to cause such an issue. I've installed nginx on many different linux boxes in the past and this is the first time I've run into this issue, which leads me to believe it may be wsl related.

**Comment by dizzam** [comment]
I'm not sure it is related to your issue but I met a similar problem that nginx will occupied nearly the same size of memory as the file size when I request for some large files (~1G). And this will cause the web server not responding to the request in some cases.

I solve this problem by adding `sendfile_max_chunk 512k` to the config file of nginx after `sendfile on`. It is a really weird behavior because nginx will automatically chunk the file for sending in linux system but not in WSL. I guess it may related to some "kernel" setting differences between WSL and Linux. And I am still examining on it.
