### ISSUE TITLE
DNS resolution delay when on VPN

### ISSUE THREAD

**Issue by elijahgagne** [Microsoft/WSL#3917]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.316]

* What you're doing and what's happening:  I am seeing, intermittently, a 5-second delay on DNS resolution when I am using the Palo Alto GlobalProtect VPN client.

* What's wrong / what should be happening instead: DNS resolution should always be fast.

* Strace of the failing command:  https://gist.github.com/elijahgagne/10ead1d8f2655a55716142cad432eefb

Here's an example of the hang I see
```
[:~] $ ssh -vvv -T git@github.com
OpenSSH_7.6p1 Ubuntu-4ubuntu0.1, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "github.com" port 22

### Sits here for about 5 seconds

debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to github.com [192.30.253.113] port 22.
```

But I don't always see the hang. Here's a loop getting timings for 10 of these.
```
for i in `seq 1 10`; do { time ssh -T git@github.com >/dev/null; } |& grep real; done
real    0m5.421s
real    0m0.402s
real    0m5.465s
real    0m0.469s
real    0m5.424s
real    0m0.469s
real    0m0.403s
real    0m5.410s
real    0m0.419s
real    0m0.380s
```

Here's my resolv.conf
```
cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
nameserver 129.170.17.4
nameserver 129.170.17.4
nameserver fec0:0:0:ffff::1
search dartmouth.edu
```

I only have this problem in WSL while on GlobalProtect VPN. I do not have this problem:
- When on GlobalProtect VPN but using native Windows (e.g. PowerShell, Putty)
- When I use a different VPN and I'm in WSL

I have opened a ticket with Palo Alto. We did some network traces and reviews of the firewall logs. It looks like the delay is happening inside WSL because all soon as our DNS servers get the request they send a reply back. There are no delays through the firewalls. 

I have found that I can edit resolv.conf and comment out the two "nameserver 129.170.17.4" lines. Then DNS resolution for internal things is fast, but I cannot access things on the Internet.

```
$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
#nameserver 129.170.17.4
#nameserver 129.170.17.4
nameserver fec0:0:0:ffff::1
search dartmouth.edu
$ ping github.com
ping: github.com: Temporary failure in name resolution
$ PASSWORD=$(gcred)
$ for i in `seq 1 10`; do { time sshpass -p $PASSWORD ssh op7@onprem.server.com -q -o StrictHostKeyChecking=no echo >/dev/null; } |& grep real; done
real    0m0.045s
real    0m0.043s
real    0m0.045s
real    0m0.045s
real    0m0.046s
real    0m0.049s
real    0m0.046s
real    0m0.050s
real    0m0.045s
real    0m0.049s
```

I have also tried changing my DNS server to Google's 8.8.8.8, but that doesn't help
```
$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
#nameserver 129.170.17.4
#nameserver 129.170.17.4
nameserver 8.8.8.8
nameserver fec0:0:0:ffff::1
search dartmouth.edu
$ ping github.com
ping: github.com: Name or service not known
```

**Comment by therealkenc** [comment]
Thanks for the `strace` log. Better to use [`nslookup(1)`](https://linux.die.net/man/1/nslookup) as the command, because the problem isn't directly related to `ssh` or `ping`. Add a `-t` or `-tt` on the `strace(1)` which will make where the pause is happening clearer. Fair warning this one is going to be a tough repro. The timing data will help identify where `nslookup` is pausing, but probably won't help identify "what went wrong".

You are on the right track trying to debug the problem. Drop that IPv6 nameserver line from `/etc/resolve.conf` (you'll feel better). If you can `ping 8.8.8.8` but can't `nslookup github.com` then we can start diving the reason that's happening. If you _can't_ `ping 8.8.8.8`, that's a whole different can.

Ref #1663, which was closed as a dupe (it isn't, #2477 is a different problem). I never tracked my own similar symptoms because (per above) it is a tough repro situation. In my case the problem seemed to be IPv6 related, but looking at your `strace` that's not your problem. Link just makes my next search easier.

**Comment by elijahgagne** [comment]
Thanks. What's interesting is that nslookup is always fast. Ping sometimes hangs before it start pinging. I notice this the most connecting to things via SSH, LDAP, curl, or database connections.

```
# Before any changes
for i in `seq 1 10`; do { time nslookup github.com >/dev/null; } |& grep real; done
real    0m0.076s
real    0m0.047s
real    0m0.050s
real    0m0.048s
real    0m0.046s
real    0m0.051s
real    0m0.052s
real    0m0.051s
real    0m0.044s
real    0m0.054s

# Updated /etc/resolv.conf
$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
nameserver 129.170.17.4
#nameserver fec0:0:0:ffff::1
search dartmouth.edu

# Ping is working fine
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=13.7 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 13.778/13.937/14.172/0.174 ms
$ ping github.com
PING github.com (192.30.253.112) 56(84) bytes of data.
64 bytes from lb-192-30-253-112-iad.github.com (192.30.253.112): icmp_seq=1 ttl=51 time=19.4 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 19.387/20.776/23.643/1.725 ms
```

**Comment by therealkenc** [comment]
Repeating: You _were_ on the right track trying to debug the problem. If (with ns `8.8.8.8`) you can ping `8.8.8.8` but can't `nslookup github.com` then we can start diving the reason that's happening. If (with ns `8.8.8.8`) you can `nslookup github.com` but can't `ping github.com`, we can start looking at differences between the two with an `strace -f -tt -o` of both.

No one has ns `129.170.17.4` except you, so this issue# is right now on track to die an unfortunate need-repro/dupe death analogous to #2082 #1350 #2884 and so many others. No one likely to respond here has a "Palo Alto GlobalProtect VPN". Not because there is a problem with that software (odds are there isn't, I use a VPN all day) but because there is no way to know what is going on without a `strace -t` to look at and make semi-educated guesses.

Needless to say I can both `ping github.com` and `nslookup github.com` using ns `8.8.8.8`. So can most everyone (or heads would explode). So at least there is _something_ to explore with your `ping: github.com: Name or service not known` fail.

**Comment by elijahgagne** [comment]
Thanks, I really appreciate the responses. With ns 8.8.8.8, I can ping, but not nslookup. 
```
$ sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
$ cat /etc/resolv.conf
nameserver 8.8.8.8
$ ping 8.8.8.8 -c 1
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=27.4 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 27.441/27.441/27.441/0.000 ms
$ nslookup github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find github.com: NXDOMAIN
```

I then created gists of each operation
```
# Note sure why I need to use sudo for the ping strace, but got an error if I did not
sudo strace -o ping.strace -tt -f ping 8.8.8.8 -c 1
strace -o nslookup.strace -tt -f nslookup github.com
```

The gists are available at:
- [nslookup.strace](https://gist.github.com/elijahgagne/16031bae4c96cbd78d0dab2891749e80)
- [ping.strace](https://gist.github.com/elijahgagne/3bdcbaab217ab9c2fba67d1d99e4b78a)

**Comment by therealkenc** [comment]
Thanks, follow up much appreciated. `ping -V` (or ping --version) just so we have a chance of being on the same page. I'm in and out this weekend but I'll look when I get a chance (usually some late nite).

**Comment by elijahgagne** [comment]
```
$ ping -V
ping utility, iputils-s20161105
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by mpa7** [comment]
I notice you said you don't have a problem from Windows but when connected to the problematic VPN what output do you get from the Windows nslookup utility (when run from cmd.exe or Powershell) when querying the 8.8.8.8 DNS server? As below:

nslookup github.com 8.8.8.8

**Comment by elijahgagne** [comment]
Interesting. When on VPN, testing with PowerShell
```
C:\Users\egagn> nslookup github.com 8.8.8.8
Server:  UnKnown
Address:  8.8.8.8

*** UnKnown can't find github.com: Non-existent domain
```
And for comparison, when NOT on VPN in PowerShell:
```
C:\Users\egagn> nslookup github.com 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    github.com
Addresses:  192.30.253.112
          192.30.253.113
```
I will update my ticket with Palo Alto about this.

**Comment by mpa7** [comment]
Yeah, that's exactly what I was expecting. The fact that both nslookup utilities got an NXDOMAIN response tells us that at DNS server _somewhere_ is responding to the query, but it certainly isn't 8.8.8.8. I suspect that on the VPN any packets for port 53 are being redirected to an internal DNS server - probably for security reasons. The other possibility is interception within your machine by the VPN client.

Running `route print` from PowerShell when on and off the VPN will allow comparison of routing table but I suspect all traffic goes via VPN when you're connected.

**Comment by elijahgagne** [comment]
Thanks
- [route-vpn.txt](https://gist.github.com/elijahgagne/54f545ae21a86a6528eab519258946f1)
- [route-no-vpn.txt](https://gist.github.com/elijahgagne/501af695750cf5a017eb5c65db624188)

Here's what's in the route-vpn.txt, but not in route-no-vpn.txt
```
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
...
          0.0.0.0          0.0.0.0         On-link       10.230.35.8      1
...
      10.230.35.8  255.255.255.255         On-link       10.230.35.8    256
...
     129.170.9.29  255.255.255.255      10.134.48.1    10.134.63.199     35
     129.170.17.4  255.255.255.255         On-link       10.230.35.8      1
```

**Comment by mpa7** [comment]
This line overrides the default route so that all traffic that doesn't have a more specific route in the table will go over the VPN. The lower metric value means this entry take priority over the existing default route. 10.230.35.8 is the IP allocated to your machine by the VPN appliance:

`          0.0.0.0          0.0.0.0         On-link       10.230.35.8      1`

A reverse DNS lookup `dig -x 129.170.9.29` suggests that 129.170.9.29 is the external IP of the VPN appliance. This line states that traffic to 129.170.9.29 should not traverse the VPN and instead go via the original default route:

`     129.170.9.29  255.255.255.255      10.134.48.1    10.134.63.199     35`

You can see the above was derived from the original default route line:

`          0.0.0.0          0.0.0.0      10.134.48.1    10.134.63.199     35`

Finally, traffic to 129.170.17.4 (the DNS server from the OP) is directed across the VPN:

`     129.170.17.4  255.255.255.255         On-link       10.230.35.8      1`

Based on the above, traffic for 8.8.8.8 would go over the VPN. From an elevated PowerShell you could _try_ the below to force the 8.8.8.8 traffic to bypass the VPN:

`route add 8.8.8.8 mask 255.255.255.255 10.134.48.1 metric 35`

Maybe run the nslookup commands again. You can clean the rule up with:

`route delete 8.8.8.8`

**Comment by elijahgagne** [comment]
You're right on the money. 
```
C:\Users\egagn> nslookup github.com 8.8.8.8
Server:  UnKnown
Address:  8.8.8.8

*** UnKnown can't find github.com: Non-existent domain
C:\Users\egagn> route add 8.8.8.8 mask 255.255.255.255 10.134.48.1 metric 35
 OK!
C:\Users\egagn> nslookup github.com 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    github.com
Addresses:  192.30.253.113
          192.30.253.112

C:\Users\egagn> route delete 8.8.8.8
 OK!
```
Does this suggest a workaround for me in WSL? Some additional information is that I use my organization's VPN when I'm onsite and also at home. I need to be on VPN, even when onsite, in order to get access through the firewall to servers. 

Alternatively, do you think there is more I need to ask on my ticket with Palo Alto?

**Comment by mpa7** [comment]
Yes, if using 8.8.8.8 sidesteps the random delays you are seeing you could use this as a workaround. The disadvantage is you'll need to run a different `route add` command depending on whether you are onsite or at home. <gateway> will need to be set to the default gateway address which at home will be the IP of your router:

`route add 8.8.8.8 mask 255.255.255.255 <gateway> metric 35`

You can use `route print` to find what you need.

Unfortunately, none of this helps us discover the cause of those delays when you use 129.170.17.4...

**Comment by elijahgagne** [comment]
Thanks. Yeah, and using 8.8.8.8 doesn't do much to help me. 99% of why I use WSL is to make use of command line tools to interact with servers and apps that I need 129.170.17.4 to resolve the DNS for me because they have private IPs behind my organization's firewall.

**Comment by therealkenc** [comment]
Nameserver `8.8.8.8` isn't much use to you, but you are seeing delays on a name (`github.com`) that your `129*` server can't (doesn't) resolve quickly right away when it asks upstream. All WSL (the kernel) does is write/read some bytes out port `53` because glibc tells it to (WSL doesn't even know it is doing a name lookup).

Left unexplained is why your `129*` server is taking five seconds to reply sometimes, but (unstated but taken as a given) never takes five seconds in Windows. Unfortunately that (probably) is not WSL actionable. And even if it is (always possible) there isn't going to be a repro anyone in Redmond can try. You can keep poking your ticket, but that usually ends badly because the intersection of "Palo Alto GlobalProtect VPN" and "WSL users" is small in the relative sense.

You can try this, which given what we know so far from above, should cut down your time to 1 second.
```
# /etc/resolv.conf
options timeout:1
nameserver 129.170.17.4
nameserver 8.8.8.8
```

I should a state quick-fix solution as well. If the local (`dartmouth.edu`?) names you use are in practice far and few between, you can just stuff those names in `/etc/hosts` and then use `8.8.8.8` exclusively in your `resolv.conf` for everything else.

**Comment by elijahgagne** [comment]
That resolv.conf does indeed seem to cut my delay down to 1 second. This is a really good workaround in my opinion. I'm happy to close this with that. If I get a better solution down the road I'll be sure to report back on it here. 

I really appreciate all the help!

**Comment by bewing** [comment]
Is there any followup to this issue?  I also use GlobalProtect VPN and am running into this issue on Windows 10 1809 update.  Before upgrading, on 1709, I did not have this issue.

**Comment by bewing** [comment]
As a follow up of my own, I was able to pin this down in *MY* case to the A/AAAA interaction of the DNS servers inside my VPN.  Setting `options: single-request-reopen` in `/run/resolvconf/resolv.conf` after every reboot resolves this issue.  

Is it possible to set options to persist, without having a static `resolv.conf`?  I still want it to update based on added/removed DNS servers when I connect to my VPN.

**Comment by DDuarte** [comment]
2022 and GlobalProtect VPN still has issues with WLS 2

The solution in this thread worked: https://live.paloaltonetworks.com/t5/globalprotect-discussions/globalprotect-blocks-the-network-traffic-of-wsl2/m-p/424989/highlight/true#M1603

```
e.g. during our test when
- the WSL host had an IP of 172.25.175.245
- netstat showed interface #20  "Hyper-V Virtual Ethernet Adapter #2"  held our WSL network
- GlobalProtect's tunnel host route had a metric of 256 (though I imagine any value greater than 1 will do)

we got it working by adding
- route add 172.25.175.245 mask 255.255.255.255 172.25.175.245 metric 256 if 20
```
