### ISSUE TITLE
Filter driver development for DrvFS

### ISSUE THREAD

**Issue by crossmeta** [Microsoft/WSL#3944]
Is there such a thing as filter driver for DrvFS to intercept just the VFS calls coming from LXCORE . This can speedup the WSL linux apps tremendously when used with [crossmeta](/crossmeta/sys) without any further translation as it is already providing a POSIX file system XFS, EXT4 etc.

This is already done in Crossmeta [Testing](/crossmeta/sys/blob/master/TESTING.md) as it provides direct path using DeviceControl (ioctl) mechanism to its own programs and NTDLL api path for other programs.

**Comment by therealkenc** [comment]
This question isn't really well formed (or rhetorical), so I'm not even sure what a constructive answer would be here. DrvFS is calls down to the underlying filesystem, and any filter driver on that filesystem can watch the operations fly by or intercept them as it sees fit. But you already know that, so that isn't the answer you are looking for.

**_If_** you mean, is there a way to intercept **WSL's** Linux-alike VFS calls.... well, "no". That wouldn't be **NT** filter driver naturally (wrong API). You know that already too. One could hypothesize an alternate-universe where there was either a WDK for WSL that provided hooks into the WSL's VFS function pointers. Or, somewhat equivalently, provide some kind of loadable kernel module API from the WSL side, which is more-or-less a rerun of #1893 ([message](https://github.com/Microsoft/WSL/issues/1893#issuecomment-293640920)). Which got an "likely never happen" ... "though it would be pretty cool" ... "[closing] this out for now" from the devs.

In the interest of heading off more of these, #3865 remains a pretty valid question/ask. It remains open. Separately, up-voting the FUSE [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) is probably a good place to start, since it doesn't take a Sherlock Holmes degree of deductive reasoning to assume FUSE will come sometime before "expose internal WSL VFS API with WDK" arrives.
