### ISSUE TITLE
^W does not clear input during `cat` (anything else that's not interactive)

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/WSL#3949]
**Please fill out the below information:**
* Your Windows build number: 10.0.17763.379

* What you're doing and what's happening: 
```
me@mywsl:~$ cat
hello world^W^W
```

* What's wrong / what should be happening instead:
When doing the same on a native linux system, the `hello world` gets erased when I press ^W twice

---

On both the Windows and Linux system `stty -a` contains `werase = ^W`. The `cat` example might be a bit stupid, but another case where it happens if i'm f-tailing some file and accidentally enter stuff. This just looks ugly, but on Linux I can get rid of this again using ^W if there was no new line since I typed it.

The issue happens regardless of how I connect - it happens via SSH and the normal windows terminal, and regardless of shell (tried zsh and bash). However, it might be worth nothing that it also happens in the normal input prompt of `sh` (I guess it doesn't use readline or a similarly fancy input editor).

**Comment by therealkenc** [comment]
I can reproduce this here. Nice eliminations, thanks. 

> However, it might be worth nothing that it also happens in the normal input prompt of sh (I guess it doesn't use readline or a similarly fancy input editor).

Good data point. Your readline guess is probably right, but oddly `dash` is okay on my Real Linux. Academic since your `cat` test is a better repro anyway.

The problem can't be the [console](https://github.com/microsoft/console). I think you eliminated interop with by trying `ssh`. Stumped why going through `stdin` (in your repro, `cat`) would make a difference. Not a dupe that I can see, which is kind of interesting in itself. Thanks for the submission.
