### ISSUE TITLE
Is it possible to access one WSL's app filesystem from another?

### ISSUE THREAD

**Issue by ANogin** [Microsoft/WSL#3954]
I have both Ubuntu 18.04 and 16.04 apps installed, and wondering whether accessing the filesystem belonging to one of them from the processes running in the other is supported. I tried going to `/mnt/c/Users/anogin/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs` from the 16.04 app, but got the wrong permissions, which suggests to me that this is probably not a good idea in the same way as accessing Linux files from Windows applications is not a good idea. Is there some better way?

I am running Windows 10 Enterprise Version 1803 OS Build 17134.648

**Comment by ANogin** [comment]
P.S. Ideally, it would be particularly great if it was possible to share /home between different Linux versions.

**Comment by therealkenc** [comment]
> which suggests to me that this is probably not a good idea

It isn't.

> Is there some better way?

Install the app somewhere on `/mnt/c`, in the same way you might on `/usr/local`. You will need to make sure everything the app depends on lives there as well. Meaning, for example, the app can't poke `/etc` (which, of course it can't because you've got two two of them).

> P.S. Ideally, it would be particularly great if it was possible to share /home between different Linux versions.

Different question, but roughly the same answer. Mount bind your `/home` to somewhere on `/mnt/c`. Make sure you've got metadata enabled.

Also, you probably don't want to do that.
