### ISSUE TITLE
WSLENV /p ignores spaces in path

### ISSUE THREAD

**Issue by JiroDan** [Microsoft/WSL#4000]
WSLENV /p ignores spaces in path

Microsoft Windows [Version 10.0.17134.706]

Create an environment variable containing a path with a space in it 
	MY_ENV=C:\Users\Joe User\utility
Add this variable to WSLENV translating for path 
	WSLENV=MY_ENV/p
bring up WSL 
	C:\ubuntu
attempt to use the translated variable 
	$cd $MY_ENV

Result is:
-bash: cd: too many arguments

Expected Result:
		expected the current path to change to /mnt/c/Users/Joe\ User/utility

**Comment by benhillis** [comment]
This should work if you wrap the variable in quotes:
`cd "$MY_ENV"`

**Comment by hermanmak** [comment]
Having the same issue while building reach native on a Windows 10 pc using WSL Ubuntu.

I think this issue should be reopened because many applications would be affected if your windows path contains spaces. In order to maintain a seamless experience WSLENV/p should consider spaces and include a escape before spaces.

**Comment by therealkenc** [comment]
> WSLENV/p should consider spaces and include a escape before spaces.

rerun #3713

**Comment by hermanmak** [comment]
how was the original issue resolved?

**Comment by therealkenc** [comment]
> how was the original issue resolved?

It isn't original just analogous. It was resolved with the conclusion (if that is the word) that escaping the output of `wslpath` is incorrect. Just like this one. [At least the other one had the redeeming quality that escaping the paths would be useful for copy-and-paste scenarios.]

>  In order to maintain a seamless experience WSLENV/p should consider spaces and include a escape before spaces.

No.

```
$ mkdir hello\ world
$ FOO="hello\ world"
$ echo $FOO
hello\ world
$ cd $FOO
bash: cd: too many arguments
```

Which was explained over in #3713 ([message](https://github.com/Microsoft/WSL/issues/3713#issuecomment-447208877)). n.b. None of this has to do with path translation or Windows. It is because: You have to quote an environment variable when you use it, or bash won't parse the expanded string the way you probably want. Blame Stephen Bourne.

**Comment by viveleroi** [comment]
Is there a way to solve this when I have no control over how the env variable is used in wsl? For example `JAVA_HOME`. 

I used WSLENV to share my JAVA_HOME but when run in wsl, gradle throws an errors:

```
[gradle] ERROR: JAVA_HOME is set to an invalid directory: /mnt/c/Program Files/Eclipse Adoptium/jdk-11.0.15.10-hotspot
```

I can `cd` to the directory when **I** use quotes around it.
