### ISSUE TITLE
Clear-screen bug after updating to Ubuntu 19.04

### ISSUE THREAD

**Issue by PHR16384** [Microsoft/WSL#4015]
(Windows Version:  10.0.17763.437)

After updating WSL to Ubuntu 19.04, though the "clear" command now erases the scrollback, it also places the viewport several lines down, proportional to the number of lines that were erased from scrollback.
![Screenshot 2019-05-03 16 18 56](https://user-images.githubusercontent.com/3525718/57163670-d1f22800-6dbf-11e9-9992-6dd39abe5d28.png)
In the screenshot above, the selection cursor is where the top-left corner of the viewport ends up, giving me a blank screen.  The viewport continually resets to this blank position until terminal output has more lines than were previously cleared.

I double-checked on another machine with a largely vanilla Win10 installation — added the Ubuntu app, immediately updated to 19.04, same result when entering "clear".

Workaround:  use "clear -x" instead of "clear" for the old screen-clearing behaviour (i.e. previous terminal output not erased, but hidden from view).

**Comment by therealkenc** [comment]
[Console tracker](https://github.com/microsoft/console) until/until some indication there is a WSL diverge to the contrary. Also no repro. In principle you could post CLI steps to compile `clear` (or a subset thereof with ncurses(3x) maybe) and include an `strace(1)` log indicating what is being written to the tty per the [template](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md).

**Comment by radium-v** [comment]
I'm having the exact same issue after upgrading to Ubuntu 19.04. I did create a ticket at microsoft/Terminal#728 but now that I look further, neither @PHR16384 or I are using the new Windows 1903 Terminal, so I don't know if that ticket is as relevant there as it is here.

* Your Windows build number:  10.0.17763.475

* What you're doing and what's happening:
1. Open Ubuntu 19.04 with a terminal window:
![2019-05-12 (0)](https://user-images.githubusercontent.com/863023/57591182-20a96b80-74fe-11e9-8858-a9253cffdc14.png)

2. Type `clear` and hit enter
![2019-05-12 (1)](https://user-images.githubusercontent.com/863023/57591187-2901a680-74fe-11e9-8761-cc183d566933.png)
![2019-05-12 (2)](https://user-images.githubusercontent.com/863023/57591189-2bfc9700-74fe-11e9-9229-21fc9f4cf8b9.png)

3. The screen scrolls too far and the prompt is too far up
![2019-05-12 (3)](https://user-images.githubusercontent.com/863023/57591198-3454d200-74fe-11e9-94da-af3e0efcefdc.png)

4. Typing in the prompt even after scrolling up resets to the borked scroll positon:
![2019-05-12 (4)](https://user-images.githubusercontent.com/863023/57591210-4fbfdd00-74fe-11e9-8208-2f53cab47b3b.png)

5. Resizing the window fixes the re-jumping but *only* if you scroll the prompt back into view first:
![2019-05-12 (5)](https://user-images.githubusercontent.com/863023/57591245-69f9bb00-74fe-11e9-924d-79b3c6e50c00.png)


This started happening after upgrading to Ubuntu 19.04 and wasn't an issue before. I'm noticing some other weird stuff too:
* As described in the original issue comment, the amount of lines the scrolling is off by is equal to the amount of lines that were present when the `clear` was called.
* Manually scrolling the window to the top with the mouse brings the prompt back into view, though typing in the prompt resets the scroll position offscreen (by the entire incorrect offset).
* If I scroll to the top, then *resize the window*, the scroll position is fixed. This *only* works if I haven't already started typing a new command
* This is happening in both Windows Terminal as well as Visual Studio Code (1.33.1 system setup).
* This happens when I run `wsl.exe`, `ubuntu.exe`, open the Ubuntu app shortcut, or open a terminal in Visual Studio Code.
* The `cls` command in `cmd` works as expected.
* Using `clear -x` does scroll into position as expected, but doesn't remove previous lines. Ctrl+L also works as expected.
* `infocmp -l` returns `clear=\E[H\E[2J`, which is expected.

**Comment by radium-v** [comment]
stacktrace: https://gist.github.com/radium-v/c551d0fd8cf29ed93d6ff2d0d7463c33

**Comment by X3Gamma** [comment]
This issue applies to WSL Kali Linux as well.
Issuing a clear command will cause viewport to move out of the screen.
Using `CLT-L` can be used to restore the screen.

Clear Stacktrace:
`execve("/usr/bin/clear", ["clear"], 0x7fffe6237400 /* 15 vars */) = 0
brk(NULL)                               = 0x7fffc143c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=83195, ...}) = 0
mmap(NULL, 83195, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f31047ab000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libtinfo.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\351\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=183528, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f31047f0000
mmap(NULL, 186752, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3104770000
mmap(0x7f310477e000, 57344, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7f310477e000
mmap(0x7f310478c000, 53248, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c000) = 0x7f310478c000
mmap(0x7f3104799000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f3104799000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260A\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1824496, ...}) = 0
mmap(NULL, 1837056, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f31045a0000
mprotect(0x7f31045c2000, 1658880, PROT_NONE) = 0
mmap(0x7f31045c2000, 1343488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f31045c2000
mmap(0x7f310470a000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16a000) = 0x7f310470a000
mmap(0x7f3104757000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b6000) = 0x7f3104757000
mmap(0x7f310475d000, 14336, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f310475d000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f31047a0000
arch_prctl(ARCH_SET_FS, 0x7f31047a0740) = 0
mprotect(0x7f3104757000, 16384, PROT_READ) = 0
mprotect(0x7f3104799000, 16384, PROT_READ) = 0
mprotect(0x7f31047f7000, 4096, PROT_READ) = 0
mprotect(0x7f31047e7000, 4096, PROT_READ) = 0
munmap(0x7f31047ab000, 83195)           = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
brk(NULL)                               = 0x7fffc143c000
brk(0x7fffc145d000)                     = 0x7fffc145d000
stat("/home/x3gamma/.terminfo", 0x7fffc143c480) = -1 ENOENT (No such file or directory)
stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=512, ...}) = 0
stat("/lib/terminfo", {st_mode=S_IFDIR|0755, st_size=512, ...}) = 0
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=512, ...}) = 0
time(NULL)                              = 1558437142 (2019-05-21T19:12:22+0800)
access("/etc/terminfo/x/xterm-256color", R_OK) = -1 ENOENT (No such file or directory)
access("/lib/terminfo/x/xterm-256color", R_OK) = 0
openat(AT_FDCWD, "/lib/terminfo/x/xterm-256color", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=3555, ...}) = 0
read(3, "\36\2%\0&\0\17\0\235\1\2\6xterm-256color|xterm"..., 32768) = 3555
read(3, "", 29184)                      = 0
close(3)                                = 0
time(NULL)                              = 1558437142 (2019-05-21T19:12:22+0800)
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TIOCGWINSZ, {ws_row=30, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
fstat(1, {st_mode=S_IFREG|0666, st_size=0, ...}) = 0
write(1, "\33[H\33[2J\33[3J", 11)       = 11
exit_group(0)                           = ?
+++ exited with 0 +++`

Windows Version: 10.0.17763.503

**Comment by PHR16384** [comment]
The issue seems to be fixed for me, at least since this week.  Either something relevant got fixed with powershell/cmd in Windows build 1903, or the culprit was among the Linux packages installed - I noticed some "core" packages among the apt-get updates this month ("bash", "console-setup", etc.).

**Comment by bwasim** [comment]
I'm facing the same issue with Win10 (10.0.17763 Build 17763).. WSL info is as follows with `lsb_release`.. 
```
bwasim@desktop:/mnt/c/busybox-1.31.1$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

Anyone else seeing this as well ?

**Comment by macsunmood** [comment]
Exactly same issue here, as @bwasim has. 
Win10 Win10 (10.0.17763), Ubuntu 20.04 LTS

Any solutions?

**Comment by bwasim** [comment]
@macsunmood , I updated my Windows installation (which indirectly updated WSL) and the problem went away.. I would recommend that you try the same..

**Comment by macsunmood** [comment]
@bwasim I'll try it, thank you, sir!

**Comment by thezaff** [comment]
I have the same issue. It appears on all terminal clients (cmd, powershell, VS Code), except the VS Code terminal in WSL-Remote mode. In this case for whatever reason it works perfect.

**Comment by gauravjain14** [comment]
For those who are still struggling, try `clear -x`. That did the trick for me and I have tried it on ubuntu versions 19.04 and above.
