### ISSUE TITLE
Can the Linux subsystem under Windows play games???

### ISSUE THREAD

**Issue by cm19940306** [microsoft/WSL#4021]
Can the Linux subsystem under Windows play games???

**Comment by Biswa96** [comment]
Mention a small tiny game. I'll try.

**Comment by therealkenc** [comment]
>Can the Linux subsystem under Windows play games???

OpenRTC2 since #1209 in 2016. [Steam](https://store.steampowered.com/linux) is problematic because 32-bit support last I looked, but could probably be force fed with effort. Short answer graphics apps aren't supported, at least until the [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq#can-i-run-all-linux-apps-in-wsl), changes, so you are technically on your own.

But yes. The WSL can play games fine 😉. 

![image](https://user-images.githubusercontent.com/7049700/57325384-bee0a000-70be-11e9-9827-f4591a7094d5.png)
