### ISSUE TITLE
Cannot access Composer / PHP installed in Windows from WSL - Ubuntu

### ISSUE THREAD

**Issue by joshuadabejero** [microsoft/WSL#4042]
Microsoft Windows [Version 10.0.17134.706]

I was trying to access composer installed on Windows 10 using WSL - Ubuntu.
![wsl-composer-php-error](https://user-images.githubusercontent.com/29270980/57759458-8c711b80-772c-11e9-8335-eb869d288ec5.PNG)

Should be showing,
```
C:\Users\Jojero>composer --version
Composer version 1.8.5 2019-04-09 17:46:47
```
Strace result:
```
jojero@xmarkdspai-pc:/mnt/c/Programs/xampp/php$ strace -o"composer --version".strace -f "composer --version"
strace: Can't stat 'composer --version': No such file or directory
```
Please help, thanks!

**Comment by therealkenc** [comment]
You've got composer in your Windows `%PATH%`. Do:
```
$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ composer
```
If composer isn't installed in your WSL distribution, install it.

**Comment by joshuadabejero** [comment]
Can't I use the composer installed in Windows 10 from Ubuntu command lines?

**Comment by therealkenc** [comment]
> Can't I use the composer installed in Windows 10 from Ubuntu command lines?

That might be possible, to the extent doing so makes sense. Shorter answer would be 'no', given that you got an error when you tried.

Once you've typed `composer` at the Ubuntu `/bin/bash` commandline prompt, WSL has handed over execution to the Windows `composer` app. That ran. But Windows `composer` isn't happy (apparently) because it can't find Windows `php`. WSL has no idea why Windows `composer` can't find Windows `php`. _WSL_ doesn't even know Windows `composer` is _looking for_ Windows `php`.

Someone in a Composer forum might be able to tell you how to coerce Windows Composer into finding Windows PHP in the scenario. Might be as simple as setting up a Windows system (global) path or environment variable. It might not be as simple.

But that is _probably_ not the route you want. Absent knowing what you are trying to achieve inside _Linux_ Ubuntu, you _probably_ want a _Windows_ implementation of `bash`, to go with your Windows version of Composer and your Windows version of PHP.

**Comment by joshuadabejero** [comment]
I found a solution, I added an alias for composer then it points like this php.exe [composer file bin location]. It works but the problem is the PATH in Windows 10 blocking the composer alias so I change the reg key of wsl flags to 5. And now it won't import all of the PATH on windows then I create a .bash_paths imported in my .bashrc which I can add paths one by one the way I want it to be. The problem is I don't know how to use the export [...].

**Comment by joshuadabejero** [comment]
Hi! I manage to make it work now! Thank you so much also about the export through command line, I got run problem where I can't use cat, vim, ls.

```
jojero@xmarkdspai-pc:~$ php.exe --version
PHP 7.3.4 (cli) (built: Apr  2 2019 21:56:52) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
jojero@xmarkdspai-pc:~$ composer --version
Composer version 1.8.5 2019-04-09 17:46:47
```

**Comment by therealkenc** [comment]
Glad you got it working and appreciate the follow up. Makes a good search target. You can tell WSL to not import Windows paths with `appendWindowsPath=false` in `wsl.conf` on Win10 1809 aka 17763 or better (I think it was 1809). You might want to add back some Windows paths judiciously to your `.bash_paths` so you don't lose stuff like the path to `cmd.exe`. But only if you want.

**Comment by joshuadabejero** [comment]
Yes I added some paths too I was so happy I don't have to use docker / vagrant or even move to Linux. Now I can even change php.exe to php just by using alias. But I will make it just like that I just need composer by now.

I added the following paths in .bash_paths,
export PATH="$PATH:/mnt/c/Windows"
export PATH="$PATH:/mnt/c/Windows/System32"
export PATH="$PATH:/mnt/c/Windows/System32/wbem"
export PATH="$PATH:/mnt/c/Programs/Microsoft VS Code/bin"

VS Code has it's on cli.js for that so I can use `code` inside the WSL anytime I want.

**Comment by joshuadabejero** [comment]
Hi! @therealkenc, I found out about WSL2, will I able to run it on Windows 10 Home?

**Comment by benhillis** [comment]
@joshuadabejero - yes

**Comment by joshuadabejero** [comment]
Even I have no Hyper v? It will work?

**Comment by joshuadabejero** [comment]
@therealkenc I'm planing to create a GUI Application which create an extension for .bash_paths and .bash_aliases inside windows so the  change for the path is in easiest way.

**Comment by therealkenc** [comment]
> inside windows so the change for the path is in easiest way

You could, but it wouldn't be an approach I'd recommend personally, _absent_ an explanation for the root cause of the "`php: not found`". It isn't clear (to me, atm) why pruning your path works around the problem; just that it does. It is institutionalization of a work around. But to be clear I could be easily be convinced otherwise given an explanation for why `php` isn't being found by Windows composer (an "ah, I see" moment), and absent a _better_ solution than diddling the paths manually (easily or otherwise). But since I don't have this particular itch to scratch I haven't looked into why you got the original error.

Not to imply discouragement. If folks find your GUI useful, even better.

Since I'm here....

> Even I have no Hyper v?

Yes. You actually already have most of the Windows virtualization infrastructure on your Windows Home right now. You just don't have a MSFT branded UX (Windows Hyper-V Manager) to do anything visible with it on Home Edition.
