### ISSUE TITLE
c++ regex_match native Ubuntu vs WSL

### ISSUE THREAD

**Issue by T4lus** [microsoft/WSL#4046]
I have some strange behavior while using both Ubuntu and Ubuntu on Win 10 (WSL). Both versions are 18.04 and GCC, and I'm compiling with these flags: `-std=c++11 -g`.

My problem is that I have this regular expression: `^[\\t ]*(?:([.A-Za-z0-9_]+[:]))?(?:[\\t ]*([A-Za-z]{2,4})(?:[\\t ]+(@[A-Za-z0-9_]+(?:(?:\\+|-)[0-9]+)?|\".+?\"|\'.+?\'|[.A-Za-z0-9_]+)(?:[\\t ]*[,][\\t ]*(@[A-Za-z0-9_]+(?:(?:\\+|-)[0-9]+)?|\".+?\"|\'.+?\'|[.A-Za-z0-9_]+))?(?:[\\t ]*[,][\\t ]*(@[A-Za-z0-9_]+(?:(?:\\+|-)[0-9]+)?|\".+?\"|\'.+?\'|[.A-Za-z0-9_]+))?)?)?`

for matching some assembler-like string (yeah, I know it's long).

I'm using it like this : 

```
    std::ifstream infile(this->inFile.c_str());
	while (std::getline(infile, line)) {
		lineNumber++;
		line = line.substr(0, line.find("#"));
		if (line == "")
			continue;
		line = reduce(line);

		if (regex_match(line, m, op_reg)) {
			std::vector<std::string> ops;
			ops.push_back(std::to_string(lineNumber));
		    for (int i = 1; i < m.size(); i++) {
		    	if (m[i] != "") {
		    		ops.push_back(m[i]);
		    	}
		    }
		    this->maps.opMap.push_back(ops);
		}
	}
```

This piece of code is working well on my native Ubuntu installation, but on the WSL version of Ubuntu `regex_match` always returns false.

Have some of you already encountered this? And if so, how have you managed it ?

**Comment by T4lus** [comment]
I found the issue is that even in WSL we have \r\n line ending style

**Comment by therealkenc** [comment]
> I found the issue is that even in WSL we have \r\n line ending style

Neither WSL/RealLinux kernel nor the Windows kernel "have \r\n" line ending style. Your input file has a line ending style. This snippet will behave the same Real Linux and WSL given the same input.

You'll need more code to handle files with differing eol conventions, if that's a design goal. Bonus points for handling all the charset eol conventions, a common one on Windows being [UTF16](https://en.wikipedia.org/wiki/UTF-16). [Which is needed if your program is going to consume assembler like strings containing characters other than 'merican.]

> how have you managed it?

Short answer is strip the `\r` chars from the `ifstream` before handing off to `std::getline(ins, line, '\n')`. Pull the whole file into a `std::stringstream` is a big hammer way to do that. [Boost iostreams](https://www.boost.org/doc/libs/1_70_0/libs/iostreams/doc/index.html) are another way to go.

Long answer is use a library like [libicu](http://site.icu-project.org/) because you can't even assume a `[.A-Za-z0-9_]` regex has much meaning let alone the eol convention. [Shorter long answer: you don't want the long answer.]
