### ISSUE TITLE
WSL API does not work in PowerShell

### ISSUE THREAD

**Issue by GigabyteProductions** [microsoft/WSL#4058]
On Windows 10 Enterprise 10.0.17763.0.

Where I expect [WslRegisterDistribution](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslregisterdistribution) to not function due to #4057, even [WslIsDistributionRegistered](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslisdistributionregistered) indicates that existing distributions do not exist.

For example, having Ubuntu installed, the following C# .NET code prints `1` as a standalone application:
```
using System.Runtime.InteropServices;

public class wslutil
{
	[DllImport("wslapi.dll", CharSet = CharSet.Unicode)]
	static extern uint WslIsDistributionRegistered([In, MarshalAs(UnmanagedType.LPWStr)] string distributionName);

	static void Main(string[] args)
	{
		System.Console.WriteLine(WslIsDistributionRegistered("Ubuntu"));
		System.Console.ReadLine();
	}
}
```

while PowerShell-ifying it prints `0`:
```
Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;

public class wslutil
{
	[DllImport("wslapi.dll", CharSet = CharSet.Unicode)]
	public static extern uint WslIsDistributionRegistered([In, MarshalAs(UnmanagedType.LPWStr)] string distributionName);

	public static void Main(string[] args)
	{
		System.Console.WriteLine(WslIsDistributionRegistered("Ubuntu"));
	}
}
'@
[wslutil]::Main({})
```

Similarly, an attempt to use [WslUnregisterDistribution](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslunregisterdistribution) returns `2147942405` (`0x80070005`, or `E_ACCESSDENIED` per https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/705fb797-2175-4a90-b5a3-3918024b10b8):
```
Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;

public class wslutil
{
	[DllImport("wslapi.dll", CharSet = CharSet.Unicode)]
	public static extern uint WslUnregisterDistribution([In, MarshalAs(UnmanagedType.LPWStr)] string distributionName);
}
'@
[wslutil]::WslUnregisterDistribution("Ubuntu")
```

Perhaps I am unaware of some type of sandboxing in calling native code from PowerShell?

**Comment by Biswa96** [comment]
Ironically, I and many others are waiting for the same thing [since it's beginning](https://stackoverflow.com/q/47250994/892848).

**Comment by benhillis** [comment]
Interesting, first I've seen this. I'd suggest using wsl.exe --import instead of the store API because it is more flexible.

**Comment by GigabyteProductions** [comment]
Haven't seen `wsl --import`. Looks like it isn't in the the organization-oriented editions' update channels, yet...

Is there a given KB that provides the new option?

**Comment by GigabyteProductions** [comment]
Hmmm... even today's updates installed onto Home edition from Win10_1809Oct_v2_English_x64.iso does not provide the option. Is it a Windows Insider Program update?

**Comment by GigabyteProductions** [comment]
1903 now visible on https://www.microsoft.com/en-us/software-download/windows10ISO
`wsl --import` now functioning on Windows 10 Enterprise 10.0.18362.30.

**Comment by Thell** [comment]
Why was this  closed when the topic "WSL API does not work in PowerShell" still seems to be the case?
Granted we can use wsl.exe as well as a wsl-launcher based solution and then call out to that from powershell, but the point still remains... _should_ loading the wsl api and using the dll functions work?

I wanted to give it shot too...

**Comment by rkttu** [comment]
Maybe this is not an optimal solution (because it involves another process creation inevitably); however, I'm posting here because I think it's worth mentioning.

I created an out-of-process style WSL API wrapper for addressing this issue. If you have interested in this code, please look out for the sample code. Any kind of contribution is welcome.

Recently, I recovered an out-of-process COM server sample code from the All-in-one Code framework in the codeplex.com archive. (which was ancient open-source storage managed by Microsoft)

Then I thought the sample code could help resolve the CoInitializeSecurity issue because the process is apart from the client process. API client gets a stub of the actual COM server, so the CoInitializeSecurity will not bother. Also, when the COM server is called the first time, the server launches automatically, and the server calculates the reference count. If it reaches zero, the process will automatically close.

https://github.com/wslhub/wsl-sdk-com
