### ISSUE TITLE
Windows 10 1903 Update Deleted WSL Installation

### ISSUE THREAD

**Issue by XerTheSquirrel** [microsoft/WSL#4063]
* Your Windows build number:  `Microsoft Windows [Version 10.0.18362.116]`
* What you're doing and what's happening:  I was trying to launch WSL after updating Windows to 1903 but it fails to start because it says there are no distrubutions. The Debian installation directory is gone as well.
* What's wrong / what should be happening instead: WSL fails to start and the Debian installation was deleted/cleared out.

**Comment by benhillis** [comment]
@XerTheSquirrel - Uggh, the store folks assured me this bug was fixed. Did you happen to launch Debian very shortly after the update?

**Comment by XerTheSquirrel** [comment]
> 
> 
> @XerTheSquirrel - Uggh, the store folks assured me this bug was fixed. Did you happen to launch Debian very shortly after the update?

I did yes...

**Comment by benhillis** [comment]
Thanks. The issue is that Windows is doing some work on it's repository of installed packages in the background, and while that is happening WSL queries the package repository and it says Debian is not installed.

I am very sorry about this, I will follow up with the store team to see if they are aware this race still exists.

**Comment by XerTheSquirrel** [comment]
> 
> 
> Thanks. The issue is that Windows is doing some work on it's repository of installed packages in the background, and while that is happening WSL queries the package repository and it says Debian is not installed.
> 
> I am very sorry about this, I will follow up with the store team to see if they are aware this race still exists.

It is what it is, just going to be reinstalling Debian now.

**Comment by XerTheSquirrel** [comment]
I will note that I have an automated task which is set to run when the computer is started, it just runs `/etc/rc.local` since I need a few services active as soon as possible. Note that this was active before, during, and after the installation of the update. I will note that "All Tasks History" was disabled, so I do not know the exact times when the tasks have started.

This is the exported task:
[Linux RCLocal.zip](https://github.com/microsoft/WSL/files/3208583/Linux.RCLocal.zip)

**Comment by haakoo** [comment]
I also had WSL disappear after installing 1903. I had Ubuntu installed, which was gone after upgrading to 1903.

I did not try to start Ubuntu shortly after the upgrade, it was not there. Not too bad, since it's a _new_ computer and I hadn't installed too much yet, but a bit annoying.

**Comment by Biswa96** [comment]
Didn't Windows preserv the old installation in Windows.Old folder (or something similar)?

**Comment by haakoo** [comment]
Yes, the upgrade created a `Windows.Old` folder, but I did expect Ubuntu to still be installed and available after the upgrade, like the other _Microsoft Store_ apps.

**Comment by Biswa96** [comment]
So, it may be possible to recover deleted distribution from that folder in current WSL system.

**Comment by XerTheSquirrel** [comment]
I had looked in `Windows.Old` however it seemed to have only kept configuration data. It was really small in size and had no root filesystem in it at all.

**Comment by Trass3r** [comment]
The file system is in `%LOCALAPPDATA%` packages. Shows up in JDiskReport 😅

**Comment by fergalmoran** [comment]
Just happened to me updating to 18980.1
Has put me right off WSL I'm afraid.

**Comment by Biswa96** [comment]
If possible move the WSL distribution to other partition or drive and backup the lxss registry after doing it.

**Comment by jdhao** [comment]
I have met the same issue here. Suddenly I can not use WSL. I thought it was an issue with wsltty I am using. 

But it seems that Ubuntu on Windows is erased somehow after a Windows update. I have to reinstall Ubuntu on Windows to start the Ubuntu terminal successfully.

**Comment by reavertm** [comment]
I got my WSL Debian "deleted" in 1809 and not after update from 1709, but just today. This is corpo-managed Windows installation and the only windows update installed between yesterday and today is some Microsoft Office 365 stuff, so completely WSL unrelated.
Some files are still in %user%\AppData\Packages\Debian*\LocalState\rootfs, but ProgramData\Packages\Debian\ is almost empty but Debian store app (it was installed from Store) is shown to be installed.

**Comment by LongLiveCHIEF** [comment]
I didn't get my full distro deleted, but it reverted the distro back to it's pristine "just installed from store" state.

Any of my files or packages I had on the distro that weren't specifically mounted to one of my physical disk drives are gone.

**Comment by KaiSD** [comment]
The same thing happened to me. My Ubuntu 18.04 WSL installation just reverted to its "factory" status.

**Comment by blackakula** [comment]
Hi all,
I've faced this problem today. I found my files in `C:\Users\<username>\AppData\Local\lxss\`. Unfortunately, because is Windows filesystem, all permissions on the files are lost. But at least, not the files itself.

**Comment by KaiSD** [comment]
It seems like I'm not so lucky.

**Comment by saolaolsson** [comment]
WSL installation gone today on 18362.476 while experimenting with getting Task Scheduler to start an ssh server on WSL during Windows start up/log on. Replaced by a new installation. Home directory seemingly lost.

**Comment by slikts** [comment]
I'm using Windows 10 Pro version 1903 and found WSL to be disabled after installing an update yesterday.

**Comment by microngust** [comment]
Windows Update applied KB4534132 to my Windows 10 laptop this morning and then prompted me to reboot. After rebooting, my Ubuntu 18.04 distro is no longer available under WSL. It does still shows up under Add/Remove programs but there are no files available under C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs or C:\Users\0017919\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState.

This is extremely disappointing as I had everything set up to do development within WSL and now it appears that Windows Update wiped everything out and I'll need to start over. This is completely unacceptable and it's making me consider switching back to Linux as my primary OS.

**Comment by telmer6** [comment]
Adding another irritated voice, my Ubuntu distro seemingly deleted itself with no warning, leading to a bunch of failing scripts and lost configuration.

**Comment by jimmed** [comment]
+1 to angry voices. This just happened to me. My local development environment depends on having Ubuntu within WSL.

**Comment by channeladam** [comment]
+1 to angry and frustrated people.

I hadn't used my Ubuntu instance for a couple of months, and just started it from the pinned item on my task bar.

It then went through an installation process:
> Installing, this may take a few minutes...
> Please create a default UNIX user account. The username does not need to match your Windows username.
> ...
> Welcome to Ubuntu 20.04 LTS (GNU/Linux 4.4.0-18362-Microsoft x86_64)

All my files and installed apps have disappeared.
Data Loss has occurred and a lot of time wasted setting up that environment.
This is really unacceptable.
I'll have to go back to a VM as this cannot be trusted.


**Windows update history:**
Windows 10 1909 installed on 28/12/2019.
Last time I used Ubuntu was likely 8 February, 2020.
KB4528760 - installed 13/2/2020
KB4532938 - installed 13/2/2020
Security Update for Adobe Flash Player: February 11, 2020 - installed 12/3/2020
KB4532693 - installed 15/3/2020
KB4551762 - installed 18/4/2020
KB4537572 - installed 18/4/2020

**Comment by tete1030** [comment]
+1. My wsl Ubuntu has gone missing in `wsl --list`. And the wsl directory is left only with `temp` folder and `fsserver` file, without the `rootfs` folder.

- After viewing all comments here, I found two people have mentioned that they were using **Task Scheduler to execute startup tasks in wsl**, which I have also being using. 

- Another probable reason is https://github.com/DDoSolitary/LxRunOffline which I have used to move wsl to other partition. After checking its code, I believe the method LxRunOffline is using to move wsl is just changing Registry value in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\${name}\BasePath`.

- Using a NTFS file recovering tool, I found files in rootfs was deleted at 16:49:02. It was non-immediately after a post-power-loss boot. I'll list a detailed timeline later.

- I have checked the whole Event Viewer at the time 16:49, Nothing WSL or unusual.

- No system update in Event Viewer. No Ubuntu update happened in Windows Store.

Timeline before deletion:
1. 15:30 an accidental **power loss**
2. 16:00 power restored, system boot
3. 16:22 - 16:30 two manual reboots
4. 16:49 another manual reboot, the deletion happened during this startup

Given that wsl has survived three system startups after power loss, I think the power loss might be irrelevant.

===
Windows version: 1909 , 18363.836

**Comment by petrosca** [comment]
The same happened to me. After a Windows system update my Ubuntu distro on WSL was deleted. When I re-installed Ubuntu from Microsoft Store the new installation overwrote the old one in:

`...\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc`

All my files are lost and no clue on how to recover them.

**Comment by KristanPushologies** [comment]
+1 for losing a WSL install on 1903. Note I can't update to 2004 as it's still "coming" for my PC...

I had a windows update pending this morning, so rebooted. KB4565351 and KB4569751 are showing in my update history.

Happily been working all day, then needed to drop into WSL via VSCode to do some work, only to be informed there's no WSL installations.

I have a `CanonicalGroupLimited` folder still in my `AppData` folder, with a few folders inside that, but apart from `settings` they're all empty.

So I've lost half a day I spend setting up WSL with everything I needed for my dev environment. Fortunately all the work itself is safely pushed up to my repos elsewhere, but had this not been the case I'd be mighty annoyed.

I also run wsl on my laptop for working while travelling, and am now totally paranoid that's going to magically vanish one day.

I see a previous commenter has used `LxRunOffline` and I'm in that camp too. I had to move my wsl install temporarily to another disk as I was out of space on my root drive, but I have since moved it back to it's original location. I can't see anything obvious in the event logs...

Is the cause of this known, or is it worth a bit of digging on my part?

**Comment by gordynorth** [comment]
+1 for losing my WSL installation on 1903. 
A windows update updated something and my WSL was gone. The files are still available because I had moved them to a non SSD drive. 
Most times I used right click open Linux shell here, which seemed to work until I need the Ubuntu shell, so I ran the Ubuntu entry on my desktop. Then I get a message that the installation will take some time, with that my previous installation was gone. 

Now I have to move it again to a non SSD drive! My laptop is not ready for 2004 yet. 

I also have a CanonicalGroupLimited  folder in AppData under Local. 
What can I do?

CanonicalGroupLimited

**Comment by GNorris913** [comment]
I also lost my entire WSL directory after 1903 update. Deleted everything that was in there. Was unable to recover the files, updates, programs etc stored on the subsystem. Reinstalled from ms store. Didn't see anything WSL related in event viewer, just the update. Computer is on UPS power so I know a power outage isn't to blame. Very frustrating.

**Comment by vladdu** [comment]
Perhaps better to add here the info from #6173: 
I have 10.0.19042.0 and probably after the installing KB4579311, the vhdx file for my default ubuntu distribution disappeared.

**Comment by thenger** [comment]
Same problem on version 10.0.19041.1

(`Get-ComputerInfo | % OsHardwareAbstractionLayer`)

I also noted that all folders in `C:\Users\%USER%\AppData\Local\Packages\` were modified at the date the update took place.

**Comment by balexandre** [comment]
I got the exact same behavior on 10.0.19041.488 update

Ubuntu opens but there's no cursor whatsoever

![image](https://user-images.githubusercontent.com/45473/109130054-97563e00-7751-11eb-80be-143b708d7585.png)

**Comment by d4rkd** [comment]
+1 to depressed and frustrated people.
all data on my wsl lost after 19041.1 update

![image](https://user-images.githubusercontent.com/28192869/112297203-92dd6080-8cd0-11eb-9b4b-fc5c398c50fc.png)

**Comment by mexchip** [comment]
I have WSL Ubuntu installed, I have been working with it for some months now, I worked with it just yesterday.
Today, I launched Windows Terminal and Ubuntu was gone from the launch menu, ran wsl and got "Server execution error":
![imagen](https://user-images.githubusercontent.com/2236848/112722591-2a5cd200-8ed0-11eb-8993-320f0cfd7b98.png)

Tried running Ubuntu from the Start menu:
![imagen](https://user-images.githubusercontent.com/2236848/112722610-3a74b180-8ed0-11eb-8a00-3f0b16187010.png)

Tried opening a WSL project from VSCode, it stays in "Opening Remote..."
![imagen](https://user-images.githubusercontent.com/2236848/112722678-8b84a580-8ed0-11eb-8b1f-fbd254eb047a.png)

Guess I lost all my files :(

**Comment by aj-cruz** [comment]
Did a number of updates on 4/20 (KB4589212, KB4601554, KB5001330). My CentOS 8 WSL install is gone.
I've been too depressed to log into GitHub and look, hopefully I committed my latest changes in all my projects :(

**Comment by Clement-Lelievre** [comment]
Same problem on version 10.0.19041.1
Did an update yesterday and after 7 months without trouble with my WSL (Ubuntu + zsh in the shell), I seem to have lost everything.
After a closer look, I could see here _C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState_ that there's a 62gB ext4 (Linux partition) saved.

Hopefully I'll be able to read it and retrieve 6 months of work, of which only about 10% are stored on repos...

**Comment by swifferwarrior** [comment]
I came across it after KB5003173 update. I checked my AppData and my partition with Ubuntu+zsh is still there for me as well. Ubuntu UWP was still installed but was acting like a fresh install and asked if I wanted to proceed with installing. I have a sneaking suspicion that doing so would have created a new partition and it would be harder to access my old files.   It looks like VM Platform and WSL were disabled in Windows Features. I checked the boxes again and rebooted. The first time I opened up my terminal it was a little ornery but the second time around everything was back to normal.

**Comment by Septias** [comment]
I updated overnight to the 21390.co_release.210521-1658 evaluation build just to find out that I can't start Ubuntu anymore. 
Ubuntu is still there:
```ps
PS C:\Users\score> wsl -l
Windows-Subsystem für Linux-Distributionen:
Ubuntu (Standard)
```
and the Packages-folder `CanonicalGroupLimited.UbuntuonWindows...`  has content in it (~20gb). 
It is just that the wsl won't start properly:
```
PS C:\Users\score> wsl
Beim Vorgang ist eine Zeitüberschreitung aufgetreten, da von dem virtuellen Computer oder Container keine Antwort empfangen wurde.
```
which translates to `The process timed oute because there was no answer from the virtual computer/container.`
Do I have to reinstall Ubuntu, or can I make it work another way? Because It looks more like a configuration problem than anything wrong with Ubuntu.

**Comment by Septias** [comment]
Update:
Luckily, for me running `wsl --update` updated the kernel and made it run again 💪

**Comment by natan-fernandes** [comment]
Had the same issue, I fixed it running `wsl` and suddenly it appeared again on the new tab

**Comment by Pramuspl** [comment]
Same happened here... Docker Desktop fails to start, it turns out that the settings.json was full of NULLs. When I managed to get it up, it turned out that the WSL instance is gone and reinstalling from MS Store apparently overwrote my files because the home directory is empty.

This is unacceptable...

**Comment by smabit** [comment]
I have had the same problem with a WSL1 installation suddenly disappearing on Server 2019 with all data however still available in the Packages directory of the user profile.

Adding a new distribution under the Lxss registry key did not help. It will show the system in the list but no way to start it. What has helped was to rename the Canonical.... folder. Then install same Linux version again. Stop the Lxss service. Delete (or rename) the new installation and use the same folder name for the installation to be recovered. Start Lxss service. All back working.

**Comment by benbenbenbenbenben** [comment]
This happened to me. I've got to say deleting a vhdx has got to be up there with the worst possible side effects. I'm a massive champion of WSL in enterprise and for this to be open after **two years** is honestly incredible.

**Comment by ronvoluted** [comment]
Sadly the same for Win 10 21H2 (19044.1503 / KB4023057) still; had a Debian based installation (Pengwin) disappear.

Found a `%UserProfile%\AppData\Local\Packages\WhitewaterFoundryLtd.Co.xxx_xxx` directory but it only had factory files in it like others have mentioned.

**Comment by aaronelliotross** [comment]
OMG. NO WORDS.

**Comment by havran** [comment]
In my case seems like some update remove registry information about installed Ubuntu distribution. Because I have all files related with WSL Ubuntu installation extracted in one directory, I know where is vxhd file created. 

Long story short:

1. I try create export tar file, but I wrongly assume I should pack whole directory with all files, (vxhd, 38Gb big, included).
2. I import created file as new distribution `wsl --import Ubuntu [target_dir] file.tar`
3. command `wsl` do nothing - but when I look at mounted `\\wsl$\Ubuntu`,  I see all files which I pack amd I realize, I should use only vxhd file.
4. I rename created wxhd file from [target_dir], where was created, and copy my old vxhd file.
5. Voila, I have my all old distribution back.

Final note. When I open wsl, my default user is not used and I was logged as root. This can be fixed by create/or/add file `/etc/wsl.conf` with:

```
[user]
default=yourusername
```

Then shutdown wsl and start distro again. Now seems all works ok.

**Comment by SeeYaaa** [comment]
WslRegisterDistribution failed with error: 0x8007019e

**Comment by ashleyghooper** [comment]
I've just experienced this incredibly disastrous issue. My Ubuntu 22.04 vhdx disappeared completely.

I'm on build 19044.2604.

Our company is in the process of switching to logging in with UPNs (`first.last@domain.com`) rather than the old `DOMAIN\username`, and I logged in with UPN for the first time yesterday. Everything was fine yesterday but when I logged in again this morning, I got a vanilla desktop and a Windows error dialog stating that I couldn't be logged in. After a reboot I was able to log in okay.

**Comment by bigjosh** [comment]
Just happened to me. Was using the WSL distribution. Clean shutdown. Rebooted computer. Tried to start up WSL again and got that the VHDX was now missing...

```
C:\Users\passp>wsl --distribution Ubuntu-20.04
Failed to attach disk 'C:\Users\passp\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04LTS_79rhkp1fndgsc\LocalState\ext4.vhdx' to WSL2: The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/MountDisk/HCS/ERROR_FILE_NOT_FOUND
```

File is completely gone. Tried to find it with Windows deleted file finder and nothing. :(

This seems like a very very bad failure mode, especially to be still happening after all these years. 

```
C:\Users\passp>ver

Microsoft Windows [Version 10.0.26100.4351]
```

**Comment by jamesbomb** [comment]
> Just happened to me. Was using the WSL distribution. Clean shutdown. Rebooted computer. Tried to start up WSL again and got that the VHDX was now missing...
> 
> ```
> C:\Users\passp>wsl --distribution Ubuntu-20.04
> Failed to attach disk 'C:\Users\passp\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04LTS_79rhkp1fndgsc\LocalState\ext4.vhdx' to WSL2: The system cannot find the file specified.
> Error code: Wsl/Service/CreateInstance/MountDisk/HCS/ERROR_FILE_NOT_FOUND
> ```
> 
> File is completely gone. Tried to find it with Windows deleted file finder and nothing. :(
> 
> This seems like a very very bad failure mode, especially to be still happening after all these years.
> 
> ```
> C:\Users\passp>ver
> 
> Microsoft Windows [Version 10.0.26100.4351]
> ```

just happened to me too. all my work stuff is gone. no vhdx file. any idea about how to recover it?
the funny thing is that while doing some web dev on wsl, the system suddenly crashed. the computer rebooted, did an automatic check disk and when i was in the system I was no able to connect to wsl or open the folder on explorer. i'm crying. literally.

**Comment by hitbuyi** [comment]
just happen to me, my ext4.vhdx of 100G is completely removed, any solution to solve this problem?
