### ISSUE TITLE
QUESTION: Is it possible to mount arbitrarily 9p servers now (19H1)?

### ISSUE THREAD

**Issue by marcosdiez** [microsoft/WSL#4070]
I am a happy user of the release Version 10.0.18362.116 (19H1).

Since it can now talk 9p with WSL, can it also talk to any other random server (like my other VMs, my phone, etc ?)

I know this may not be the right place to ask this question, but this is the only way I can think of of asking it to the right people.

**Comment by mscraigloewen** [comment]
Hi @marcosdiez , in general no you won't be able to mount arbitrary 9P servers to WSL. The communication channel we've created is specific to WSL. 

We are releasing a deep dive into the 9P architecture soon, which will hopefully give you some more clarity on how and why this works. 

I'm going to mark this issue as closed since I've answered your initial question, but I'm also happy to follow up if you'd like to.

**Comment by marcosdiez** [comment]
First of all I must say that I am delighted to receive an answer from Mr. @mscraigloewen himself.

I believe I kind of understood the whole P9 thing. 

I am just thinking the consequences of Windows to be able to mount arbitrary P9 servers. It might be a good thing. Even better if one could mount arbitrary ports.

Trivial application would be for me to mount anything typing 9p://IP_OF_A_SERVER:ABITRARY_PORT/blah

A nice usage would be to implement an P9 server on `	Your Phone Companion` to allow one to have a better access to the phone's file system.

**Comment by mscraigloewen** [comment]
Yes I agree, there are a lot of interesting and useful use cases for being able to access a 9P server onto Windows! Of course there are also many challenges on doing so, and as of right now our team is focused on great features to WSL, so adding the ability to mount any 9P server isn't currently on our backlog. When the deep dive into the architecture video comes out I'm hoping it will make it a lot clearer on why this is the case!

**Comment by marzhall** [comment]
Hi @craigloewen-msft! I'm currently looking at the option of implementing a virtual filesystem for a data storage service at work, and it'd be great if I could use 9p, since the service needs to be windows- and linux-compatible. Since it's been three years since the last post here and it's a top result for the query, I figured I'd ask if there's been any updates on allowing the use of 9p outside of the WSL - or if there were any other options for a VFS you might suggest. My apologies if I've missed a recent post elsewhere. Thanks!

**Comment by craigloewen-msft** [comment]
Hi @marzhall there haven't been any updates here. The 9P file server is just for use in WSL right now, and there isn't a publicly usable implementation of it. Thank you for the interest though!

**Comment by marzhall** [comment]
Ah, bummer. Thanks for the quick response!

**Comment by vonj** [comment]
Publicly usable, or publicly endorsed?
