### ISSUE TITLE
Configure rxvt cutchars

### ISSUE THREAD

**Issue by andb0t** [microsoft/WSL#4087]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.765]

* What you're doing and what's happening:
I have the problem described in this [stack exchance thread](https://superuser.com/questions/692988/is-there-a-way-to-set-margins-paddings-in-tmux): I use tmux as terminal multiplexer. It has vertical bars `|` as window separators, which appear in the WSL ubuntu 18.04 shell as normal `|` characters. When I want to copy&paste a word by double clicking, which touches the border, i.e. the `|` char, the `|` char is also selected. I would like to exclude `|` from double-click selections and make them a cutchar. This can be done on linux like this in some rxvt config file (which one?):

   ```
   URxvt*.cutchars: "()*,;<>[]{}|`\"'#│"'`"
   ```
   How do I configure this in WSL?

* Reproduction:
Simply type a string including `|` (e.g. `left|right`) and double click it. It will highlight the entire string instead of just the left or right side of the `|` where you were clicking. In your browser, most likely, double clicking the string will work as I would like to have it in the WSL as well.

* What's wrong / what should be happening instead:
I would like it to only highlight one side of the `|` on click.

**Comment by mscraigloewen** [comment]
Hi @andb0t! The actual process of highlighting and copying text is actually handled by the Windows Console (AKA the Terminal Window that you're interacting with) and not WSL itself. So the WSL team won't be able to put in a fix for you, but the Windows Console team will certainly help you out! 

Could you please open an issue on [their Github page](https://github.com/microsoft/terminal) describing your problem?

I'm going to close this issue since ultimately the issue will be handled by the Console team. Please feel free to ping this thread if you have any further questions!
