### ISSUE TITLE
Windows 10 1903 Update Breaks GDK_SCALE

### ISSUE THREAD

**Issue by peidaqi** [microsoft/WSL#4097]
**Please fill out the below information:**
* Your Windows build number: 1903

* What you're doing and what's happening: 
Running Terminator terminal emulator with VcxSrv on HiDPI screen.
Prior to 1903 update, I can add an environment variable in ~/.profile :
export GDK_SCALE=2
And this would get a 2x scale for GDK applications.

* What's wrong / what should be happening instead:
The previous breaks with 1903 update.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
This submission is not WSL actionable. WSL writes bytes out socket localhost:6000 and does not know the semantics of `GDK_SCALE`. The place to direct the question would in forums related to those products (GTK and VcXsrv). You'll probably get better answers there by replicating your scenario under a VM like VitrualBox rather than WSL. Ref #637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799)). Tag somewhere between external and linux-behavior.
