### ISSUE TITLE
Black screen in legacy mode

### ISSUE THREAD

**Issue by eElor** [microsoft/WSL#4117]
Today Ubuntu (WSL) opened just a black window.

I re-installed it and tried different things to get it to work properly again. I noticed that using the legacy mode caused that black/blank window. However, by turning it off, all the other windows consoles (cmd, powershell) became black as well. 

Re-installing Ubuntu and using it seems to require the legacy mode to be off, but cmd and powershell on... That wasn't the case not long ago.

**Comment by mscraigloewen** [comment]
@eElor are you still using the legacy version of WSL? An easy solution might be to upgrade, is there any reason you aren't able to?

**Comment by eElor** [comment]
Hi @mscraigloewen 

my WSL was always up to date. I wrote this issue after it completely stopped working. I still do not know the reason. But after playing around, I discovered the issue with the legacy mode. I just tried it again: I updated and upgraded WSL and turned on legacy mode (was off before, since WSL won’t work otherwise).

WSL stopped working altogether. It won’t even start... However, CMD and Powershell are working now (were before only black windows). And they only do in legacy mode ( `right click on any console > properties > Options >Use legacy console (requires relaunch...)` ). As soon as I turn legacy mode off in cmd/powershell, WSL starts working again, but the other two appear just as black windows.

**Comment by mscraigloewen** [comment]
This seems to be a Windows Console related bug if WSL can be working or not working depending on whether you have legacy mode enabled. Could you please open this issue on the [Terminal repo's](https://github.com/microsoft/terminal) page?

I'll close out this issue on this repo since I don't believe we can do anything that would help fix your problem. Feel free to reopen it if you are still running into WSL specific issues! Thank you :)
