### ISSUE TITLE
I want to try to mount VirtFS in WIn10 (guest os).

### ISSUE THREAD

**Issue by daiaji** [microsoft/WSL#4154]
What should I do?

**Comment by stephen45ss** [comment]
I assume you are attempting to create some shell environment that is secure for some reason. hosting? Please consider the fact that WSL 2 is in development and this is a place to address issues not a how to guide. That in mind probably there isn't full support for this yet or it may not work at all. One of the devs on the project might know if this is possible but this as i said before isn't really the place to ask how to do  something. Try stackoverflow or another similar site.

**Comment by daiaji** [comment]
@stephen45ss Thank you. I thought it might not be possible at all.
But since WSL2 is not yet developed, I don't want to re-evaluate WSL. (I've used WSL1, and to be honest, it's terrible.)
Actually WIn10 is my guest os, my host os is opensuse. I try to use VirtFS to exchange files.

**Comment by stephen45ss** [comment]
I'm actually still installing the windows update to get WSL 2 up and running been a ultra slow process taking hours. But windows 10 is my host OS with kali linux in wsl 1 currently. Unfortunately I discovered WSL 2 doesn't support nmap or other networking tools because limitations in networking but I'm still gonna see what it can do as far as I/O speed and install times and the like. I honestly would love to see full networking ability in the future for WSL 2. WSL 2 will give security experts and developers a good way to interact with linux while keeping a windows host OS. I love tools on linux and let's face it some tools on linux are better but for gaming hands down windows does it best and i love gaming and linux will never be my choice OS for gaming. And if any devs do read this keep up the good work and bring us more features ;)

**Comment by daiaji** [comment]
@stephen45ss https://www.kali.org/news/wsl2-and-kali/
Kali's blog post claims that Nmap is available on WSL2. :D
@benhillis So the VirtFS provided by WSL2 only works for Win10 under guest os? Not working for Win10 under guest os? Is there a relevant development plan?
