### ISSUE TITLE
[WSL2] Issues with running LXD (system containers)

### ISSUE THREAD

**Issue by simos** [microsoft/WSL#4158]
* Your Windows build number:  Windows 10 build 18917 (Fast ring)

* What you're doing and what's happening:  

I am using WSL2 with the default Ubuntu 18.04.2 image. 
I want to setup LXD (system containers, unprivileged) to work in WSL2. 

I run the following to start the service, then `sudo lxd init` to initialize LXD. I accept all the defaults. 
```
sudo service lxd start
sudo lxd init
```

* What's wrong / what should be happening instead:

The initialization fails with a networking error,
```
Error: Failed to create network 'lxdbr0': Failed to run: iptables -w -t filter -I INPUT -i lxdbr0 -p udp --dport 67 -j ACCEPT -m comment --comment generated for LXD network lxdbr0: iptables: No chain/target/match by that name.
```

* Further errors
You can setup LXD without networking, by responding _no_ to the networking questions when you run `sudo lxd init`. By doing so, `sudo lxd init` manages to complete. But when you actually try to start a new container, you can the following errors: 

```
lxc mycontainer 20190614081018.500 ERROR    utils - utils.c:safe_mount:1179 - Operation not permitted - Failed to mount "sysfs" onto "/usr/lib/x86_64-linux-gnu/lxc/sys"
lxc mycontainer 20190614081018.500 ERROR    conf - conf.c:lxc_mount_auto_mounts:724 - Operation not permitted - Failed to mount "sysfs" on "/usr/lib/x86_64-linux-gnu/lxc/sys" with flags 0
lxc mycontainer 20190614081018.500 ERROR    conf - conf.c:lxc_setup:3539 - Failed to setup first automatic mounts
lxc mycontainer 20190614081018.500 ERROR    start - start.c:do_start:1263 - Failed to setup container "mycontainer"
lxc mycontainer 20190614081018.500 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc mycontainer 20190614081018.500 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 7
lxc mycontainer 20190614081018.500 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc mycontainer 20190614081018.501 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "mycontainer"
lxc 20190614081018.506 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"
```

## Tips
1. To start over, you can `sudo apt remove --purge lxd`, then install LXD again with `sudo apt install lxd`. 

## References
1. [Status of LXD in WSL2](https://discuss.linuxcontainers.org/t/status-of-lxd-on-wsl2/5018/1)

**Comment by onomatopellan** [comment]
It seems someone made it work.
https://twitter.com/10_Chrisi/status/1139619146935820288

**Comment by simos** [comment]
I wrote a post on running LXD in WSL2. 
Specifically, I could not get networking to work, so I used proxy devices.
The result is to get Internet Explorer to view the website from a LXD container.
https://blog.simos.info/how-to-run-lxd-containers-in-wsl2/

**Comment by therealkenc** [comment]
^--- Thanks for that 👍.

As you point out, at base, the WSL2 has some missing KCONFIGs ref #4165. Others have hit the OP fail [here](https://github.com/lxc/lxd/issues/3686) and [here](https://bugs.gentoo.org/628346#c4), and this Gentoo peeps appear to have worked-around with this [patch](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=7f091e8001253dfcd84e81d263d7db319b63aabf).

Since you bring it up in your blog post, you can get `systemd` up on WSL2 if you are feeling risqué ref #994. Now that we're playing with the big boys, a lot of the Linux ecosystem was previously out of bounds in WSL1 because of _"bigger problems"_ would really rather be living in a warm `systemd` home, especially if those package binaries were built on a distro that assumes `systemd` exists (because their local build scripts find `systemd`). That's not to say these packages _won't_ run _without_ `systemd` (they generally can), but the devs that _actually maintain_ those packages more often than not have `systemd` on their rigs (typically Red Hat or Ubuntu) so it isn't too surprising there are going to be rough edges for us on WSL2. It isn't too hard to find these rough edges on the Interwebs, because you'll get Google hits from the Gentoo/Alpine/Void people.

**Comment by horseinthesky** [comment]
I'm able to `lxd init` but containers silently stop.

My default profile
```
lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/c2
```

My lxdbr0
```
lxc network show lxdbr0
config:
  ipv4.address: 10.198.196.1/24
  ipv4.nat: "true"
  ipv6.address: none
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/c2
managed: true
status: Created
locations:
- none
```

When I do `lxc start c2` my container stays STOPPED
```
lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| c2   | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
```

Container logs say:
```
lxc info c2 --show-log
Name: c2
Remote: unix://
Architecture: x86_64
Created: 2020/06/03 19:52 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc c2 20200606083559.215 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance
lxc c2 20200606083559.407 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 17
```

**Comment by benhillis** [comment]
If you have a compatible CPU, nested virtualization is now enabled by default in recent Insider Dev builds.
