### ISSUE TITLE
wget under wsl is not using windows defender to check the file against vulnerabilities 

### ISSUE THREAD

**Issue by kkreja** [microsoft/WSL#4163]
am not sure if that is a bug or a feature. 

When I download

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_windows_hotspot_11.0.3_7.msi

via browser it is checked by "Antimalware Service Executable" when I download it via wsl and wget it's not

**Comment by karuboniru** [comment]
You download the file to where? To Linux filesystem or devfs of windows?

**Comment by therealkenc** [comment]
> am not sure if that is a bug or a feature.

Benefit of the doubt you're not sure. Some information on "A quick explanation of the architectural changes in WSL 2 " available [here](https://devblogs.microsoft.com/commandline/announcing-wsl-2/).

> Where did you download the file to?

This is a rhetorical question. Waiting for "I downloaded it to ext4" is not necessary.

Files on drvfs will be examined by Defender. Those in the container will not, just like Hyper-V, by design.

**Comment by kkreja** [comment]
Yeah when downloading to windows filesystem Defender is activated and the file lands on the disk after that is done. But when downloaded to ext4 and copied to windows file system then it is available right away.
