### ISSUE TITLE
Arrow keys for command recall don't work correctly ssh'ed on remote hosts running bash

### ISSUE THREAD

**Issue by tastle73** [Microsoft/WSL#418]
To reproduce:

ssh to another host running bash. try to up arrow through your command history and it will either immediately print the escape characters like "[A" for up arrow or it will work initially and then start doing that later or intermittently. 

Terminfo/termcap is correct for xterm on these systems.

**Comment by tastle73** [comment]
ash and ksh are problematic too

**Comment by zadjii-msft** [comment]
@tastle73 Which build are you on? (press Windows Key + R, type “winver” into the Run dialog, and press Enter.) There have been a bunch of fixes for some issues involving the arrow keys, but I (and @richturn) want to double check to see if they're in your build yet or if they're an unrelated issue.

**Comment by tastle73** [comment]
1511 14342.001

**Comment by timriker** [comment]
seems to work here for history, though not in some other apps.
1511 14342.1001
see #425

**Comment by tastle73** [comment]
FWIW It works fine on the local session. If I ssh to another system, it sporadically works and other times I just get the escape code on the command line.  I wonder if it's related to the tset/tput issue with vi?

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and has likely been fixed since it was opened. If not, please post a new issue in the [Console GitHub Repo](https://github.com/Microsoft/console)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by timriker** [comment]
I think the fix for #425 fixed this issue as well.

**Comment by RichTurn** [comment]
Hey guys,


I have no clue what you all are talking about. You are using the wrong
email address.

Regards,

Richard Turner
