### ISSUE TITLE
drvfs: metadata (chmod\chown) possible for mounted SMB drives?

### ISSUE THREAD

**Issue by holmesb** [microsoft/WSL#4200]
Anyone got metadata working when mounting SMB (samba) mapped drives?  

The only mounts that I've managed to get "metadata" successfully showing in their options when I do a `mount -l`  are local NTFS drives.  In fstab I'm using:

` V: /mnt/tmp drvfs metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11 0 0 `

where V: is a mapped samba drive in Windows 10 (1903).  `mount -l` shows this is mounted without metadata: 

`V: on /mnt/tmp type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,case=off)` 

Hence I cannot use chmod nor chown.  I've also tried drives mapped to NFS shares using Microsoft Client for NFS to no avail.  Can someone confirm whether its possible to use metadata with network drives?

My /etc/wsl.conf correctly includes the metadata option:
```[automount]
enabled = true
options = "metadata,uid=1000,gid=1000,umask=22,fmask=11,case=off"
mountFsTab = true

[network]
generateHosts = true
generateResolvConf = true

**Comment by therealkenc** [comment]
> Can someone confirm whether its possible to use metadata with network drives?

It isn't. The ask implied here is to support WSL metadata in the Windows SMB filesystem and Windows NFS filesystem. In principle that's possible (anything is _possible_) but right now that metadata (say the `UID:GID` userspec) for all practical purposes is not accessible on the _Windows_ side, by design. The fact you're trying to _then_ mount those _Windows_ (sic) filesystems in WSL is related but orthogonal to the ask. Those Windows filesystems don't support metadata, so `drvfs` (`wslfs`, `9p`) isn't gonna see the metadata either.

I should for the sake of completeness acknowledge that Windows NFS does have [identity mapping](https://techcommunity.microsoft.com/t5/Storage-at-Microsoft/NFS-Identity-Mapping-in-Windows-Server-2012/ba-p/424602) capabilities, but that is (getting into the weeds) a different kettle of fish. The Windows NFS client doesn't expose the `UID:GID` as WSL metadata.

In the Q&A portion of the [WSL2 launch](https://www.youtube.com/watch?v=lwhMThePdIo) (at around 54:00) someone asked about merging permission models. It got basically a hard-no for now.

In WSL2 you are able to mount both SMB and NFS remotes inside the container. Which is almost certainly going to be SOP for the foreseeable future.
