### ISSUE TITLE
Can offer some 32-bit distrubution for choose?

### ISSUE THREAD

**Issue by XQDD** [microsoft/WSL#4215]
I found that run or compile the 32-bit project under the 64-bit system is a very troublesome event there are lots of compatibility errors. So can we simply use a 32-bit Linux distribution under 64-bit win10?

Why we need it? The reason is some arm CPU is 32-bit and only can run 32-bit ELF, so we need cross compile under WLS.

Why can't we just compile under Qemu, VMware, VirtualBox or a real Linux environment?  Because WSL  is very handy and faster than all of the virtual tool above.

**Comment by benhillis** [comment]
I was curious so I tried importing http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/x86/alpine-minirootfs-3.10.0-x86.tar.gz on WSL2 and it works like a charm.

**Comment by therealkenc** [comment]
Calling this ran course. It wasn't actually clear from the OP whether he/she wanted a x86 32-bit Linux distribution or a 32-bit Arm Linux distribution.

The latter being entirely [doable](https://wiki.qemu.org/Documentation/Platforms/ARM) under QEMU, and I suppose common for ARM-type people. For example, Arch still [humors](https://archlinuxarm.org/) soft float ARMv5te. 

The former, which Ben tried, gets an easy "yes of course works". But conflates the second paragraph of the OP stating "some arm CPU is 32-bit", which doesn't have a lot to do with 32-bit **x86**. Except, to the extent, some Arm cross compilation tooling (read: [yocto](https://github.com/microsoft/WSL/issues/3154)) is I gather built 32-bit x86 for reasons. But that use case is already covered well by the fact that Ubuntu x64 multiarch [works](https://github.com/microsoft/WSL/issues/2468#issuecomment-502402213) fine out of the box on WSL2. There is no need to spin a 32-bit Alpine (and a few good reasons not to) in order to run Yocto.

[That is all notwithstanding this week's [brouhaha](https://www.engadget.com/2019/06/24/canonical-ubuntu-linux-32-bit-support/) about Canonical dropping x86 support. That would make those Arm people's heads explode, nevermind #1644 Steam or [#2258](https://github.com/microsoft/WSL/issues/2258#issuecomment-311435352) Wine. ]
