### ISSUE TITLE
wsl2: vpn on host machine

### ISSUE THREAD

**Issue by dimarusyy** [microsoft/WSL#4252]
Hello,

Recently with wsl1 all network interfaces were replicated from windows machine.
With wsl2 because of hyper-v being used, the NAT interface is used and wsl2 doesn't see any vpn interfaces from host machine.

My question : Is there any way to replicate tunnel vpn interface in wsl2 ?
Also, so far wsl2 doesn't provide UI support for now, using vpn clients in wsl2 is not always possible because sometimes 2FA requires UI interaction with user.

**version**:
> C:\Users\ddr>ver
> Microsoft Windows [Version 10.0.18922.1000]

**ipconfig** on windows host, 10.10.177.21 is vpn address: 

>C:\Users\ddr>ipconfig
>Windows IP Configuration
> 
> Ethernet adapter Local Area Connection* 2:
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . : fe80::8424:b1a5:7586:8508%3
>    IPv4 Address. . . . . . . . . . . : 10.10.177.21
>    Subnet Mask . . . . . . . . . . . : 255.255.255.255
>    Default Gateway . . . . . . . . . : 0.0.0.0
> 
> Ethernet adapter Ethernet:
> 
>    Media State . . . . . . . . . . . : Media disconnected
>    Connection-specific DNS Suffix  . :
> 
> Ethernet adapter Ethernet 2:
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . : fe80::d470:2271:9f37:cf27%16
>    IPv4 Address. . . . . . . . . . . : 192.168.0.194
>    Subnet Mask . . . . . . . . . . . : 255.255.255.0
>    Default Gateway . . . . . . . . . : 192.168.0.1

Thanks

**Comment by therealkenc** [comment]
> My question : Is there any way to replicate tunnel vpn interface in wsl2 ?

Would have to be way more specific on "tunnel vpn" because the specifics on the answer to "is there any way" is going to be very sensitive to the nature of the VPN. Answer is almost always going to be "yes" (2FA or not), but you'll get way better answers if you ask in a forum with people familiar with the VPN in question.

That said, I get the feeling there is something else going on here, as yet unexplained. The [quoth](https://github.com/microsoft/WSL/issues/4201#issuecomment-504380389) "I tried connect to a VPN in Windows a few time in them past, but every time I failed" over in #4201 has been nagging at me. It is certainly a true enough statement, but leaves unexplained the fail part. Your statement "the NAT interface is used and wsl2 doesn't see any vpn interfaces from host machine" in your OP leaves explanation as well. The fact WSL has it's own IP segment isn't notable (or special) in the context. Which is not on you; I don't know why your bytes aren't being routed into WSL2 either. _My_ Windows VPN works fine (my provider happens to use [OpenVPN](https://openvpn.net/) +  [TAP](https://github.com/OpenVPN/tap-windows6)) but that doesn't help you because you aren't using my provider, areya).

Which is just to say, attacking this from the WSL2 side can almost certainly be made to work, with effort. But it _probably_ isn't the right approach. If I had to guess (and I do), there is some (maybe simple) answer here for a certain class of VPNs that we're all missing. Otherwise every Hyper-V user would be screeching for the last decade.

**Comment by dimarusyy** [comment]
@therealkenc , thanks for answering but unfortunately I didn't fully get it.
#4201 is about unsupported API and is not related to my question.

Let me briefly describe the  real question I'm faced now :
1. I use **pulsesecure** vpn client on Ubuntu VM to connect to VPN. It requires 2FA and requires UI support as asks for 2FA passphrase.
2. I can successfully connect to VPN both from windows host or from Ubuntu VM running in Hyper-V.
3. I can't connect to vpn from wsl2 because of UI being unsupported or via using host(windows) VPN/tunnel interface on wsl2 (or maybe I don't know the way how to configure that).

When wsl2 starts, it's eth0 is 172.x.x.x as it's behind the NAT. That's why I don't think any configuring of routing either on windows or wsl2 is applicable (as being answered in some issues here) to workaround my issue.

To say more, if you were watching wsl2 demo on ms-connect conference, the guys from MS were mentioning about replicating host network interfaces in wsl2. But looks like only default NAT is available for now.

**Comment by therealkenc** [comment]
> and is not related to my question.

Yeah I get that a lot.

Hopefully someone from the community will  offer an answer more to your liking, and which you believe is more related to your question.

**Comment by wangqr** [comment]
Just for your information, running GUI application on both WSL1 and WSL2 is possible. You need a Xserver on Windows host (either VcXsrv or cygwin/X will work), then `export DISPLAY=<windows ip>:0`. Detailed guides also available with some Googling.

**Comment by dimarusyy** [comment]
@wangqr , thank you for comment. Yes, you are right and I was able to deal with NAT issue and tried wsl2 with xming. 
I was able to start pulseUi from pulse vpn client. But unfortunately it emits an error while trying to connect to vpn :
> ip6tables-restore: line 5 failed
I failed to find something reasonable about this error and it looks like this is an issue in pulse client.
That's why for now I postponed with this approach and switched back to virtual box.

**Comment by ahazu** [comment]
I'm having this exact same issue. Converting back to WSL 1 is not really an option as that breaks other network functionality. Back to VMs I guess....

**Comment by ronaldwillems74** [comment]
I solved this for my situation by establishing the VPN connection not from the windows host, but from within the WSL2 VM using openconnect. Obviously I cannot use the vpn connection on the Windows side, but that's ok for me. I'm also using X forwarding with XMing to be able to use a browser over de vpn connection

**Comment by carlolars** [comment]
Similar problem here, started two-three weeks ago for me so something somewhere must have changed...

I've been running Ubuntu 20.04 in WSL2 since April, connecting to work using the Pulse Secure Win10 app and accessing the servers at work from both Windows and from within WSL2. I've had no problems with `git fetch` or `git push` until now, where fetching/pushing works for very small changes (10+ objects) but not for larger changes (~100+ objects) where push/fetch just hangs.

If i connect to work using the `OpenConnect VPN client` from inside WSL2 then it works fine. OpenConnect can be run in cli-only so it is an ok workaround for me.  
I just have to convince the IT-department to allow more than one active VPN connection, right now I must choose between pushing from WSL2 or browsing the intranet from Windows 😄

**Comment by dimarusyy** [comment]
The point is that my VPN server requires 2FA and only pulsesecure vpn UI client allows to connect.
Unfortunately OpenConnect cli doesn't work properly with 2FA.

**Comment by tanukus** [comment]
@carlolars I'm unable to connect to my work VPN (Pulse secure) from WSL2 on Window 10 (1909). How did you manage that?
