### ISSUE TITLE
WSL2 opens in home directory instead of directory corresponding to Windows working directory

### ISSUE THREAD

**Issue by aeschli** [microsoft/WSL#4270]
No reproducible steps, but wanted to create an issue to make sure this is logged:
I've heard from various users that WSL2 sometimes doesn't come up in current working dir  (corresponding to the folder where started in Windows), but starts in the home directory instead.

Rebooting the VM seems to fix the issue.

https://stackoverflow.com/questions/56609858/vscode-remote-release-and-wsl-2
https://github.com/microsoft/vscode-remote-release/issues/21#issuecomment-506321702
https://github.com/microsoft/vscode-remote-release/issues/883

I'l probably make a fix to VSCode Remote WSL to no longer rely that the cwd is mapped to unblock users.

**Comment by benhillis** [comment]
Thanks @aeschli - Not much to go on here, and I'm unable to reproduce this myself.  Please keep me updated if you find out any more information.

**Comment by arthow4n** [comment]
@benhillis I ran into this issue when I turned Windows Sandbox feature on, then I turned it off and the issue is gone. I tried to reproduce by turning Windows Sandbox on again, but the issue wasn't reproduced this time. Not sure if this helps because I failed consistently reproducing it, my OS build version is 18930.1000.

**Comment by goldnetonline** [comment]
You're a lifesaver bro.

Thanks
