### ISSUE TITLE
Error: 0xc03a001a while installing wsl2 distribution

### ISSUE THREAD

**Issue by bbhopesh** [microsoft/WSL#4299]
I get following error when I try to install a wsl2 distribution.
```
WslRegisterDistribution failed with error: 0xc03a001a
Error: 0xc03a001a The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.
```

My windows version is: Microsoft Windows [Version 10.0.18936.1000]

I am attaching log files with the issue.

[logs.zip](https://github.com/microsoft/WSL/files/3387789/logs.zip)

**Comment by Biswa96** [comment]
Duplicate https://github.com/microsoft/WSL/issues/4103.

**Comment by bbhopesh** [comment]
Thanks for pointing this out.

**Comment by impleotv** [comment]
This is what helped me - https://utf9k.net/blog/wsl2-vhd-issue/

**Comment by marcus-crane** [comment]
@impleotv Glad you found use out of my post 🙂

**Comment by ayelai** [comment]
> 
> 
> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages
> and right click the folder, check advanced options and disable compression. Run the launch again.
> 
>     * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> 
>     * Debian is under "TheDebianProject" so that will appear under "T"

Thank you @runner-ed! This worked for me as well.

**Comment by SiddharthSingi** [comment]
> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages
> and right click the folder, check advanced options and disable compression. Run the launch again.
> 
> * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> * Debian is under "TheDebianProject" so that will appear under "T"

Thank you @runner-ed . Have been looking for a way out for this for a long time. This solution worked for me as well!

**Comment by kl3sk** [comment]
Thanks this fix my problem Too !!

**Comment by namedgraph** [comment]
And nobody felt it's important to mention this in the installation guide?..

**Comment by RnebDG** [comment]
> 
> 
> This is what helped me - https://utf9k.net/blog/wsl2-vhd-issue/

Thanks, Solved my issue as well!

**Comment by cuj** [comment]
> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages
> and right click the folder, check advanced options and disable compression. Run the launch again.
> 
> * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> * Debian is under "TheDebianProject" so that will appear under "T"

for those of you who has an error saying that "C:\Users<your user name>\AppData\Local\Package" doesn't exist:

in run you can do
`cmd /c  %SystemRoot%\explorer.exe %APPDATA%\..\Local\Packages`

**Comment by tonyspunei** [comment]
This approach also helped me. 
1. Find the Locatio - in my case it was the "KaliLinux.54290C8133FEE_ey8k8hqnwqnmg" folder.
2. Right click on it -> go to advanced Settings and disable comprime data.
3. DONE!

**Comment by jacob-kymustang** [comment]
> This is what helped me - https://utf9k.net/blog/wsl2-vhd-issue/

This worked for me as well, thank you.

Mine was under the folder: "CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc"

**Comment by aleleonian** [comment]
> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages
> and right click the folder, check advanced options and disable compression. Run the launch again.
> 
> * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> * Debian is under "TheDebianProject" so that will appear under "T"



> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages
> and right click the folder, check advanced options and disable compression. Run the launch again.
> 
> * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> * Debian is under "TheDebianProject" so that will appear under "T"

IT WORKED!

Thanks so much.

**Comment by thevictorian** [comment]
The solution is referred to in this Microsoft tutorial
https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

**The requested operation could not be completed due to a virtual disk system limitation. Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.**

Deselect “Compress contents” (as well as “Encrypt contents” if that’s checked) by opening the profile folder for your Linux distribution. It should be located in a folder on your Windows file system, something like: USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited...
In this Linux distro profile, there should be a LocalState folder. Right-click this folder to display a menu of options. Select Properties > Advanced and then ensure that the “Compress contents to save disk space” and “Encrypt contents to secure data” checkboxes are unselected (not checked). If you are asked whether to apply this to just to the current folder or to all subfolders and files, select “just this folder” because you are only clearing the compress flag. After this, the wsl --set-version command should work.

**Comment by Erasemus** [comment]
I may have a new variant of this issue: Background: Installed wsl-2 then attempted to install Ubuntu: The command window reported that Ubuntu was already installed and would launch it . In the new window that appears I see:Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xc03a001a
Error: 0xc03a001a The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.
No mention of decompression. I found two distribution profile folders of the form mentioned in the  earlier posts. I changed the compression setting on the one that had it set. No joy.

**Comment by simomill** [comment]
So, I have the same problem. But the "compress contents" option is already unticked.

**Comment by noor-ridha** [comment]
> This also solved my issue as well. Essentially... find the package under C:\Users<your user name>\AppData\Local\Packages and right click the folder, check advanced options and disable compression. Run the launch again.
> 
> * Of course ubuntu is listed under "CanonicalGroupLimited.Ubuntu" so if you sort alphabetically it will appear under "C"
> * Debian is under "TheDebianProject" so that will appear under "T"

thank youuuuu, problem solved
