### ISSUE TITLE
Android Studio and possibly other applications can't access WSL filesytem

### ISSUE THREAD

**Issue by bbhopesh** [microsoft/WSL#4307]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18936.1000]

* What you're doing and what's happening: 
I used git for Linux to check out a repo on Linux filesystem. If I run `explorer.exe .` in this directory, Windows file explorer opens fine and I can access files from explorer. However, when I try to create project in Android Studio, it can't access this path. Even when I give exact path using `\\wsl$\Ubuntu\home\user\path\to\repo`, Android Studio doesn't recognize it. Interestingly, Ubuntu doesn't show up under Network in file explorer, so, everytime I have to open explorer from command line.

* What's wrong / what should be happening instead:
`\\wsl$\...` path should work in any Windows program including Android Studio. Explorer should also display distributions under Network resources.

**Comment by Biswa96** [comment]
Try to mount/map that network drive (e.g. `Z:\`).

**Comment by bbhopesh** [comment]
That doesn't work. Get network name cannot be found error.
![image](https://user-images.githubusercontent.com/8807496/61313551-82f94380-a7af-11e9-8ed6-0637d2840017.png)

**Comment by bbhopesh** [comment]
Oh that worked. Thanks a lot. 
However, `\\wsl$` is a valid path. Do you know just using this path doesn't work?

**Comment by Biswa96** [comment]
Do you have any simple program instead of Android Studio?

**Comment by bbhopesh** [comment]
No I haven't tried anything else yet. I just assumed that any program which has it's own file explorer would face this issue. I tried Visual Studio but that uses Windows file explorer so it didn't have the same problem.

Do WSL distros show up for you under Network in explorer by default?

**Comment by Biswa96** [comment]
> Do WSL distros show up for you under Network in explorer by default?

I do not allow Windows to do that hence I made a Shell Link (.lnk) to automate that.

**Comment by therealkenc** [comment]
> Interestingly, Ubuntu doesn't show up under Network in file explorer

There wasn't enough to go on here to determine why Ubuntu isn't showing up under Network in file explorer. 

If I had to guess either (a) The problem is related to that path not appearing in the Network Neighborhood, or, (b) Android Studio itself isn't happy with `\\wsl$\Ubuntu\home\user\path\to\repo` paths due to some gap in their code. The `Z:\` work-around would suggest it's the latter, but that's a WAG. Either way, ran course because not actionable. 

Appreciate the submission though. Maybe some me2s will appear on the mysteriously missing 'Ubuntu' in the net hood.
