### ISSUE TITLE
WSL fails to return tty screen size given correct VT sequence

### ISSUE THREAD

**Issue by therealkenc** [microsoft/WSL#4327]
[regrouping]

**Comment by DHowett-MSFT** [comment]
Just a note: I'm having trouble with this repro.

`echo -e '\e[18t' > $(tty) | xxd` redirects the output directly to the tty, rendering the additional redirect into `xxd` useless.

`echo -e '\e[18t' | xxd` redirects the output directly into `xxd`, which is why `xxd` then prints the raw bytes `1B 5B 31 38 74`. This is not what you're expecting (it dumps the value of `CSI 18 t` instead of the response `CSI 8`).

Regardless, that's not the correct way to reproduce this. You want `echo -en '\e[18t'; xxd`, at which point the terminal emulator will respond with `CSI 8 ; <h> ; <w> t`. You'll have to press <kbd>Ctrl+D</kbd> to get xxd to recognize the end of the stream, as there's no delineation in the input stream between terminal reports and user input.

That just turns this into a feature request that we support `CSI 18 t`. I'll rename and categorize this bug appropriately.

**Comment by DHowett-MSFT** [comment]
Oh, I can't, as I forgot this wasn't the terminal repo. This is just a feature request for conhost.

**Comment by therealkenc** [comment]
Sh*t sorry Dustin. That was my bad cut and paste. I'll delete both in two min and regroup.

**Comment by therealkenc** [comment]
Don't have the power to delete; closed is the best I can do. I'd have to take harder run at a `wsl.exe`-as-child (eg [rawpty.cpp](https://github.com/Biswa96/wslbridge2/blob/master/rawpty/RawPty.cpp)) and post if (iff only if) . This is more challenging than the half hour exercise I was hoping for last weekend because `wsl.exe` is a black box and `ssh.exe` is [not using](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/win32_pty.c#L98) ConPTY. Which is not on you. If it _can_ be done in-scope `xterm-256color` `wsl.exe` scenario by whatever means then this is by-design ConPTY, and feature request `wsl.exe -t` "Force pseudo-terminal allocation" option WSL.
