### ISSUE TITLE
Running wsl.exe -d with a custom-built distro fails silently

### ISSUE THREAD

**Issue by Difegue** [microsoft/WSL#4361]
* Your Windows build number:  Microsoft Windows [version 10.0.18362.267]

* What you're doing and what's happening:  

~~~~
wsl.exe --import customDistro $env:APPDATA\CustomDistro .\package.tar
wsl.exe -l
wsl.exe -d customDistro
~~~~

* What's wrong / what should be happening instead:  

The distro is properly listed when doing `wsl.exe -l`.  
However, the `wsl.exe -d` call fails silently instead of starting a Linux shell.  

This only happens with some clients and I am unable to reproduce it.

* Detailed WSL launch logs from a client:  

[lxcore.zip](https://github.com/microsoft/WSL/files/3454069/lxcore.zip)

* The failing custom distro (please excuse the OneDrive link):    
https://1drv.ms/u/s!AtJBOSoSCRPJgYsP1Ao9aJqymoH8Cg

**Comment by Biswa96** [comment]
It works in latest Windows 10 insider build 18945 with both WSL1 and WSL2 mode.

**Comment by therealkenc** [comment]
Taking Biswa96's word for it, for lack.

**Comment by Difegue** [comment]
Thanks for testing on the latest insider builds, I hadn't done it myself.  

I was hoping that you'd see a clue in the lxcore files that'd pinpoint the issue those specific machines are having, but I guess there's nothing in 'em. Oh well 🤷‍♂️

**Comment by onomatopellan** [comment]
Those logs are from Windows 10 build 17134. An upgrade would be the best.

**Comment by therealkenc** [comment]
Okay now I'd be remiss in silence. [Thanks Biswa96+Onomatopellan, your valuable input is very helpful and appreciated.]

> I was hoping that you'd see a clue in the lxcore files

...

> An upgrade would be the best.

Being on the latest helps. Meets necessity condition if not sufficiency condition. 

But in this case it isn't about the logs. The probability of finding someone in the community willing and competent enough to dive a (paraphrasing) "my rando tarball doesn't work" is, let's call it, small -- on an issue submission statistical basis, historically speaking, anyway. With the caveat, sure, I suppose it could happen. 

Further, the probability of this issue submission exposing a novel gap in WSL2 is near zero, because WSL2 is Real Linux. Realistically, the only reason this one didn't go full chirping-crickets is that Biswa96 looked, and said it works. It would still be sitting open otherwise. Hence, "for lack".

Whether anything was fixed between 17134 and 18362, I can't say. I'd say dubious, since it is equally likely Bis only managed (quoth) "I am unable to reproduce it" from the OP. But I don't know... because, see, I am pretty sure no one even looked at the logs. Certainly not me. Because "my tarball doesn't work" is not actionable. I have a hard drive full of half-finished projects that _don't_ work. The likelihood of anyone deep diving mine are "small" too.

I don't work for or speak for MSFT yadda yadda. Don't shoot the messenger.

**Comment by Difegue** [comment]
Oh yeah, I wasn't expecting this issue to unravel a massive bug or for people to actually try out the tarball; It was just there for a complete reproduction example.  
I was sure the user was running latest, but since it's apparently not the case I can simply tell him to upgrade now. :)

Please don't see my previous message as spitting on your work or anything; It was certainly not meant so. 😅
