### ISSUE TITLE
WSL2 does not pass through kubectl port-forwards transparently like WSL1

### ISSUE THREAD

**Issue by andrewgill-draysontechnologies** [microsoft/WSL#4406]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18956.1000]

* What you're doing and what's happening:  
kubectl port-forward does not allow windows applications to connect as expected over the specified localhost ports on WS2. This behaviour is a change from WSL1.

I am attempting to connect to a dev kubenetes cluster hosted on gcloud. My WSL2 is setup and able to run kubectl commands as expected. e.g. `kubectl -n dev get po ` returns all of the PODs in the namespace as expected. 

However, port-forwarding does not allow windows based applications to connect through localhost as expected.

I run the following command:
`kubectl -dev port-forward postgresdb 5432`

It responds with:
Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432

However, when windows attempts to connect over 127.0.0.1:5432 the connection fails to work. Running the same command in a powershell console allows the port-forward to work as expected.

* What's wrong / what should be happening instead:
I expect the network traffic to pass through to the kubectl cluster as it did in WSL1.

**Comment by therealkenc** [comment]
#4199

**Comment by yousafsyed-bg** [comment]
Since I haven't been able to find a simple solution to this problem, I tricked wsl2 with a docker container inside of my distro.

`docker run --rm --name kubectl --user root -v ~/.kube/config:/.kube/config -p 8080:8080 bitnami/kubectl:latest port-forward --address 0.0.0.0 --namespace containerNameSpace containerName 8080:7111`


To simplify this more this command can be wrapped into a simple bash script named /usr/bin/kubectl that can forward all the kubectl commands to the docker container.

I hope this can help someone.

**Comment by yousafsyed** [comment]
Since I haven't been able to find a simple solution to this problem, I tricked wsl2 with a docker container inside of my distro.

`docker run --rm --name kubectl --user root -v ~/.kube/config:/.kube/config -p 8080:8080 bitnami/kubectl:latest port-forward --address 0.0.0.0 --namespace containerNameSpace containerName 8080:7111`

To simplify this more this command can be wrapped into a simple bash script named /usr/bin/kubectl that can forward all the kubectl commands to the docker container.

I hope this can help someone.
