### ISSUE TITLE
Start WSL2 on Boot

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/WSL#4477]
**Please fill out the below information:**
* Your Windows build number:  `Microsoft Windows [Version 10.0.18975.1000]`

* What you're doing and what's happening:  Starting up my machine, I get a message saying my WSL2 share can't be mounted.

![image](https://user-images.githubusercontent.com/115199/64475529-8d99de80-d149-11e9-83df-ce50717f7963.png)

* What's wrong / what should be happening instead: To preserve a seamless experience between my Windows and Linux spaces, I would like an option to ensure that this share is available at system boot.

**Comment by jpsenior** [comment]
To share a temporary workaround that has been working well for me, I have created an `/etc/rc.local` containing the service definitions I want to run on boot (like docker).  I have also created a scheduled task that runs as my user account during login that issues wsl.exe /etc/rc.local - this seems to have been pretty great for me so far.

I do however agree this needs to be a first class option, where WSL boots simultaneously with windows with a more supported option.

**Comment by therealkenc** [comment]
> I do however agree this needs to be a first class option,

If you submit a [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l), be sure to detail what the 'first class option' might look like in terms of the UX. WSL isn't going to begin at _Boot_ because the Windows _User_ hasn't logged in yet. 

I suspect this is going to be a "use standard methods" kind of thing rather than a WSL thing. Add wsl.exe -d <distro> /etc/rc.local/something` to startup, where `something` is a init script launches any daemon(s) that will keep the WSL instance alive. It'll flash a `cmd.exe` window but that's pretty standard fare.

**Comment by atrauzzi** [comment]
I'm not sure I agree. I definitely don't want terminals flashing when my system starts or when I log in and I'm not sure what precedent exists to say that it's "standard fare".

Moreover, isn't it a massive design oversight to constrain WSL* to being something that can only happen at "user-time"?  What design decision prompted WSL* to require a user be logged on?

**Comment by benhillis** [comment]
@atrauzzi - the fact that distributions are per-user.

**Comment by atrauzzi** [comment]
That's just repeating the problem though. It's a serious question.

**Comment by blacklightpy** [comment]
> That's just repeating the problem though. It's a serious question.

No, it is totally okay that WSL instances are per-user because it may not be required for other users, or they may have other configurations set up. Just like any other VMs. Both possible implementations make sense and they just chose one over the other. Maybe they should've given an option to install WSL system wide vs user only.

But I support that running WSL at startup should be a native feature than a user-implementation with flashing terminals because there's been many instances where I wanted to access a file from the distro without launching a terminal and typing wsl just so the P9 server would start up in Explorer.
