### ISSUE TITLE
Why there is no 'rename' exec in WSL2 that every other Linux distribution has?

### ISSUE THREAD

**Issue by BandageWorm** [microsoft/WSL#4481]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sirredbeard** [comment]
If your distro of choice on WSL doesn't come with rename you can easily add it. For example, `$ sudo apt-get install rename`.

The distro builds provided for WSL tend to have a smaller base set of packages than a full desktop installation.

I actually use `mv` for renaming, it's shorter to type.

**Comment by BandageWorm** [comment]
> 
> 
> If your distro of choice on WSL doesn't come with rename you can easily add it. For example, `$ sudo apt-get install rename`.
> 
> The distro builds provided for WSL tend to have a smaller base set of packages than a full desktop installation.
> 
> I actually use `mv` for renaming, it's shorter to type.

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rename

Of course I tried, it just doesn't work. I use Ubuntu.

**Comment by therealkenc** [comment]
- `rename`is not a [Unix](https://en.wikipedia.org/wiki/Unix) command; or if you prefer, not a [POSIX utility](https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html). [`mv`](http://man7.org/linux/man-pages/man1/mv.1.html) is.
- The command you _might_ be looking for is called `rename.ul` [from](https://packages.ubuntu.com/bionic/amd64/util-linux/filelist) the `util-linux` [package](https://packages.ubuntu.com/bionic/util-linux), which ships by default with Ubuntu from the MSTF Store.
- Ubuntu's `rename` [package](https://packages.ubuntu.com/bionic/rename) is _apparently_ some `perl` thing [who knew] you _probably_ don't want. It does not ship by default on any stock Ubuntu build, full desktop or otherwise.
- Why you can't install the goofy `perl` thing (aka `file-rename` [upstream](https://metacpan.org/release/File-Rename)), assuming doing that was desirable, is not WSL actionable. You'll get better answers regarding "unable to locate package" in a [Ubuntu forum](https://ubuntuforums.org/) or at [superuser.com](https://superuser.com/). Clearly the package [exists](https://packages.ubuntu.com/bionic/rename).
- Likewise instant query "Why there is no 'rename' exec in ~WSL2~ Ubuntu that every other Linux distribution has?" would be a question to ask in a Ubuntu forum. [n.b. No comment either way on premise, because I wouldn't know what every other Linux distribution ships or doesn't ship.]

On Ubuntu, you can point `/usr/bin/rename` at `/usr/bin/rename.ul` with a [symlink](http://man7.org/linux/man-pages/man1/ln.1.html), or use [update-alternatives](http://man7.org/linux/man-pages/man1/update-alternatives.1.html).

Bonne chance.
