### ISSUE TITLE
cannot enumerate external usb devices using android tools fastboot

### ISSUE THREAD

**Issue by hufubin** [microsoft/WSL#4483]
When I using fastboot to enumerate external phone, it cannot find any devices, even android device can be find in device manage list.

Furthermore, if I want to use another tool 'adb', it need run service in windows first, and then it can work in bash on ubuntu.

**Comment by therealkenc** [comment]
#2195

**Comment by hufubin** [comment]
Not like adb, using TCP port to communicate with server, can be workaround by start server in windows environment and then using adb in bash. fastboot has no similar server, it need WSL to access serial port...
It's not the same issue, cannot dup to adb issues.

**Comment by therealkenc** [comment]
> WSL to access serial port...

I read your "not like adb" and re-tagged this too fast. I never actually made it to the ask, which is still USB device support. The landing zone for USB device support remains (among others) #2195. You can use `adb` over TCP, but the reason #2195 is open is because _there is no USB device support_ WSL (1 or 2). User Voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/31920928-add-libusb-support-to-wsl).

**Comment by jdorsay-xenu** [comment]
The User Voice forum in your link gets "Command Prompt / Console / Windows Subsystem for Linux (WSL) [Closed]" Has it been migrated to a new location?

**Comment by therealkenc** [comment]
Best I can tell (and only from the text there) it has been shuttered since my post two weeks ago, in favor of the tag-feature issues in this repository. So up-voting #2195 (interestingly, it has none) would be the thing to do.
