### ISSUE TITLE
WSL2 no internet access inside wsl, when connected to Wi-Fi with captive portal

### ISSUE THREAD

**Issue by archilkarchava** [microsoft/WSL#4502]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
  Microsoft Windows [Version 10.0.18980.1]
  Ubuntu WSL2 from the Store.
* What you're doing and what's happening:
  Connecting to my university's Wi-Fi network and authenticating on the captive portal page.
* What's wrong / what should be happening instead:
  Don't have internet access inside WSL2 terminal, except for the captive portal Wi-Fi login page.
  Should have internet access after authenticating in the browser.

**Comment by therealkenc** [comment]
Heh. I like this one. Ask is HTTP proxy interop with Windows, as well as a house brand `systemd-resolved`. Has nothing to do with WiFi, strictly speaking; imagine if Starbucks had wired ports at their tables).

For now you'd have to go off road, and doing that probably won't be entirely trivial. Gold Star to anyone who posts a working solution. I don't have it in me to spend a day at Starbucks working one up. Running native Firefox or Chrome in WSL to VcXsrv will also _probably_ work, assuming you've got a whole `systemd` parade running. Bonne chance.

**Comment by archilkarchava** [comment]
One workaround I found is to use a VPN in windows and a custom resolv.conf in wsl.

**Comment by qiansen1386** [comment]
I am connecting to my home wifi, and get exactly the same problem. What should I do to further diagnose the issue? It used to be fine, until last update.
![image](https://user-images.githubusercontent.com/1759658/85427915-c1060680-b5bf-11ea-8621-c49398dd39de.png)

Windows Version: 10.0.19041.329
WSL 2 with Ubuntu 18.04 LTS

**Comment by therealkenc** [comment]
Your home router will be different than a captive portal (proxy) scenario. Search 'DNS' or 'VPN' or 'resolv.conf' and you'll find lots of hits.

Regarding the OP, if authenticating with a Windows browser and pointing `/etc/resolv.conf` in the right direction works, that is pretty much standard operating procedure until/unless WSL learns how to handle the DNS server changing better. Closing only because if updating `/etc/resolv.conf` works then any forthcoming improvements will apply to your scenario as well. Thank-you for the submission though it was a good one.
