### ISSUE TITLE
vscode can open and modify source.list through GUI but can't save

### ISSUE THREAD

**Issue by wgm096350** [microsoft/WSL#4508]
I know that /etc/apt/source.list is a file that should not be modified freely, but sometime i need to modify the package to speed up download speed so it has to be changed. One way to do that is through VIM. VIM is a headache for me (a deep-rooted windows user). I can open /etc/apt/source.list in VSCODE as the following picture below, but after modifing it, saving it is a another headache because I don't have root 's rights. "Permission Denied". Any workaroud?
![QQ截图20190915220819](https://user-images.githubusercontent.com/24369346/64922797-d9ade880-d805-11e9-8410-c63a71432073.png)
![QQ截图20190915220836](https://user-images.githubusercontent.com/24369346/64922798-d9ade880-d805-11e9-9df0-f8e77bc093fe.png)

**Comment by therealkenc** [comment]
This is a dupe but I can't find it. Ref [microsoft/vscode-remote-release/286](https://github.com/microsoft/vscode-remote-release/issues/286).

> Any workaroud?

It _might_ take if you (re)start WSL as root (`wsl.exe` -u root). Haven't tried (wouldn't try). Humble guidance would be to use [`nano`](https://en.wikipedia.org/wiki/GNU_nano).

**Comment by therealkenc** [comment]
... or SOP would be to copy the `/etc/apt/sources.list` to `$HOME`, edit it in VS Code, and copy it back to with `sudo(1)`.

Closing rather than let it chirp crickets indefinitely. Right now, by-design, WSL interop leans heavily on the "default user" paradigm. For the unprivileged multi-user use case (user `steve` or `jane`), follow the vscode-remote-release tracker cited above. Maybe something will come of it.
