### ISSUE TITLE
g++-8 internal compiler error under WSL (Debian Buster, Ubuntu Bionic)

### ISSUE THREAD

**Issue by Nekto89** [microsoft/WSL#4510]
* Your Windows build number:  10.0.18362.356

* What you're doing and what's happening:
`x86_64-linux-gnu-g++-8 -O1 -c ice_gcc.cpp`
Result: `x86_64-linux-gnu-g++-8: internal compiler error: Segmentation fault signal terminated program cc1plus`
https://gist.github.com/Nekto89/f17bc6dac4dfcf969e54709185aa5c2c

* What's wrong / what should be happening instead:
Expected: no internal compiler error
There is no internal compiler error using Docker with same version of g++

Debian:
```
FROM debian:buster-20190910-slim
RUN apt-get update && apt-get -y --no-install-recommends install g++-8=8.3.0-6  && rm -rf /var/lib/apt/lists/*
COPY ice_gcc.cpp /usr/src/ice/ice_gcc.cpp
WORKDIR /usr/src/ice
RUN x86_64-linux-gnu-g++-8 -v 
RUN x86_64-linux-gnu-g++-8 -O1 -c ice_gcc.cpp
```
Ubuntu:
```
FROM ubuntu:bionic-20190807
RUN apt-get update && apt-get -y --no-install-recommends install g++-8=8.3.0-6ubuntu1~18.04.1  && rm -rf /var/lib/apt/lists/*
COPY ice_gcc.cpp /usr/src/ice/ice_gcc.cpp
WORKDIR /usr/src/ice
RUN x86_64-linux-gnu-g++-8 -v 
RUN x86_64-linux-gnu-g++-8 -O1 -c ice_gcc.cpp
```

* Strace of the failing command, if applicable:
Debian: https://gist.github.com/Nekto89/ce11e8fc22329ef94682579bbc2dbffa

**Comment by therealkenc** [comment]
```
133   --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7fffc6823fbc} ---
133   +++ killed by SIGSEGV (core dumped) +++
132   <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV && WCOREDUMP(s)}], 0, NULL) = 133
```

Thanks so much for the well formed submission including the strace logs. It really helps. Hence effort to expended to look.

That address (`0x7fffc6823fbc`) sure doesn't look mapped alright. Nothing mapped up past the `0x74..........`-ish range. So it looks like WSL1 is doing what it is told, and faulting as ordered.

Unfortunately (?) I can't seem to reproduce on WSL1 (sic) and 18980. It compiles fine; here's [y strace](https://gist.github.com/therealkenc/88a6bcb52cdddf7ea90f629866ef90c3). Pretty much the same deal up to line 949, but no illegal access. `g++-8` continues along. 

![image](https://user-images.githubusercontent.com/7049700/65085814-5d7de700-d964-11e9-9527-767877f08bd8.png)

I don't have a 18362 handy, but there is _almost no way_ the version Win10 version is going to make a difference here. That segv is all userspace. You could try insiders on a lark. Stranger things have happened.

My WAG is that there is something very subtly different between your Docker userspace and your WSL1 userspace that is causing `gcc++-8` to choke. It _almost_ has to be, because with `g++`, despite it being enormous, doesn't actually hit much interesting syscall surface to actually fail [with weasel-word 'much' acknoledged.] In short, "an ICE is an ICE". If I could reproduce it here we'd have a thread to tug, but it works, so we don't.

Debugging `g++-8` with `gdb` and finding out why it is actually faulting is pretty much out of the question unless you've got a week to burn. Practical guidance would be install `gcc++-9` and see if it still fails. That will at least vary g++'s the userspace environment. If that doesn't work, try Insiders. 

If _that_ doesn't work, I suppose you _could_ duplicate your Docker environment verbatim in a WSL1 chroot and see if it _still_ fails. But by that point we'd be grasping big time. If it still failed with an _identical_ userspace, finding out why it works for me but not you would amount to some too-subtle-to-look difference between my rig and yours (CPU, amount of RAM, whoknows). By then solution would be pull anchor and try WSL2. Or keep using Docker. Bonne chance.
