### ISSUE TITLE
how to solve the question that sudo:must be setuid root?

### ISSUE THREAD

**Issue by qiuziyuchenxi** [microsoft/WSL#4513]
Modify the owner of the /usr using the sudo chmod-R 777/usr command,Cause sudo:must be setuid root problem, that is sudo command can not be used. I want to into the Linux recovery mode, when the Ubuntu app star and I press the SHIFT key,.But I can not into the recovery mode.I want to know how to solve the problem that sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set? and how go into the recovery mode?

**Comment by 0xbadfca11** [comment]
``ubuntu.exe config --default-user root``
or
``wsl.exe --user root``

**Comment by therealkenc** [comment]
Thanks 0xbadfca11. I have a suspicion this is a different or perhaps unrelated question; because the "SHIFT key" reference is curious. And `sudo` works out of the box on Ubuntu, without having to resort to logging in as root to diddle suid bits. But that's the answer to how to get in as root and mess with `/usr/bin/sudo`, if one wanted or needed to do that.

More information on sudo and sudoers [here](https://www.sudo.ws/).

**Comment by qiuziyuchenxi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you very much.
        I already have solved that problem as you described.
    
        
            
        
    
    
        
        

        
    

    On 9/17/2019 12:05，0xbadfca11<notifications@github.com> wrote： 


ubuntu.exe config --default-user root
or
wsl.exe --user root
