### ISSUE TITLE
[WSL2]Git repo isn't recognized by VS Code if in linux root folder

### ISSUE THREAD

**Issue by AndreasGalster** [microsoft/WSL#4559]
**Your Windows build number:**
18985.vb_release.190913-1426

**What you're doing and what's happening:**
I have a git repo open in VS Code, when I have the folder somewhere on my device (e. g. `mnt/c/folder`) the git repo in VS code is properly recognized, if I place the folder within my linux root folder, the git repo is not being recognized.

** What's wrong / what should be happening instead:**
VS Code should show the Git icon and recognize the Git repo, including highlighting files that have changed, there they've changed, etc.

**Comment by therealkenc** [comment]
It would take a lot of doing for a `.git` directory on Linux `/ ` (ie, literally, a `/.git/` directory) to be well formed. Your root folder would need to be writable as your default WSL user. Ref #4508. There are no repro steps provided to tell. This is likely tag by-design like the other. Please confirm concise CLI repro steps for your scenario.

**Comment by HeyITGuyFixIt** [comment]
I think I understand what you are trying to do, but I cannot reproduce this issue. I am assuming you are cloning a repo to `/mnt/c/folder/` (with `folder` being an example, and not necessarily being the actual folder) and you move the repo folder to your home directory, `~/`. When you open that repo folder in VS Code it doesn't show the Git icon.

Now for me, my Windows build `18999.vb_release.191004-1432`, and my VS Code version is 1.39.1, and am using WSL2 with Ubuntu 18.04.3 LTS. And the kernel is `4.19.72-microsoft-standard`. I cloned  a git repo off of Gitlab and copied the folder to my home directory and was able to open it in VS Code without any issues. The Git icon showed up and reported any and all changes made to the repo.

Make sure you are up to date, and that you are trying to open the repo folder, not the home directory or the .git directory. Also try disabling all of your extensions, except the Remote - WSL extension. If it works after disabling your extensions, start to add them back until you figure out which one may be causing the issue, if that is the issue here. If you still can replicate the issue after trying my advice, please show us what you are doing.

**Comment by AndreasGalster** [comment]
> I think I understand what you are trying to do, but I cannot reproduce this issue. I am assuming you are cloning a repo to `/mnt/c/folder/` (with `folder` being an example, and not necessarily being the actual folder) and you move the repo folder to your home directory, `~/`. When you open that repo folder in VS Code it doesn't show the Git icon.
> 
> Now for me, my Windows build `18999.vb_release.191004-1432`, and my VS Code version is 1.39.1, and am using WSL2 with Ubuntu 18.04.3 LTS. And the kernel is `4.19.72-microsoft-standard`. I cloned a git repo off of Gitlab and copied the folder to my home directory and was able to open it in VS Code without any issues. The Git icon showed up and reported any and all changes made to the repo.
> 
> Make sure you are up to date, and that you are trying to open the repo folder, not the home directory or the .git directory. Also try disabling all of your extensions, except the Remote - WSL extension. If it works after disabling your extensions, start to add them back until you figure out which one may be causing the issue, if that is the issue here. If you still can replicate the issue after trying my advice, please show us what you are doing.

Yes, this is exactly what I am doing. What are the things that should be up-to-date? Windows build, VS code, terminal app, what else?

**Comment by HeyITGuyFixIt** [comment]
@AndreasGalster The things you mentioned are good to have up-to-date, and if you are still having issues, continue with the other troubleshooting advice I gave:

> ... and that you are trying to open the repo folder, not the home directory or the .git directory. Also try disabling all of your extensions, except the Remote - WSL extension. If it works after disabling your extensions, start to add them back until you figure out which one may be causing the issue, if that is the issue here.

**Comment by JonathanAspeling** [comment]
I came across this thread and wanted to leave my resolution. 

I installed Remote - WSL extension for my VS Code. 
![image](https://user-images.githubusercontent.com/42679894/170841170-f15728e6-41b8-4f72-970f-3f4a02cf0dc0.png)

I then navigated to the folder via cli on WSL. Typed Code . in the directory I wanted to launch and presto.
