### ISSUE TITLE
Can't connect to Windows host using localhost from Linux

### ISSUE THREAD

**Issue by throwable-one** [microsoft/WSL#4582]
It used to work in WSL1.
Try ``$ telnet 127.0.0.1 445``.

Interesting, that it works the opposite way (you can connect to Linux using localhost from Windows), but not vice versa.

WinVer ``18995.1``

**Comment by craigloewen-msft** [comment]
This is by design, we are working on improving that experience. We prioritized connecting from Windows to a Linux server as that's the most common use case.

For more info please check out our [WSL 2 UX differences docs page](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-network-applications). Thanks! :)

**Comment by throwable-one** [comment]
@craigloewen-msft thank you.
