### ISSUE TITLE
WSL2 and Vagrant

### ISSUE THREAD

**Issue by Salmondx** [microsoft/WSL#4599]
Do you have plans to make WSL2 and vagrant work together? Currently its not possible because vagrant can't mount network (UCN) files.

Also IMHO it's worth mentioning this fact somewhere in a blogpost :)

**Comment by craigloewen-msft** [comment]
What workflow did you have in mind with Vagrant? Would you mind describing it in a bit more detail for us? 

Did you want to use the Windows version of Vagrant to target WSL2 instances? Or did you want to run Vagrant inside of WSL2? Or something completely different?

Thank you!

**Comment by Salmondx** [comment]
Sorry for not describing it in details in my first message.
So I usually use vagrant with VirtualBox provider. As I understand wsl 2 is going to be based on Hyper-V and VirtualBox can not be instantiated while Hyper-V is enabled.

Are you going to support VirtualBox/Vagrant pair in WSL 2? Currently in WSL 1 I just run vagrant/virtualbox installed on my windows and it works without any issues (in WSL 1 we can run exe files from linux distro).

**Comment by craigloewen-msft** [comment]
Gotcha! We have talked about this in [a blog post](https://devblogs.microsoft.com/commandline/wsl-2-post-build-faq/) before, as well as on the docs in our [WSL 2 FAQ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox). 

So VirtualBox 6.0.0 does have a Hyper-V fallback, but the performance seems limited as of right now. As of right now there isn't any update beyond the answers in those posts. 

Does that help answer your question?

**Comment by Salmondx** [comment]
Oh, I see. So as I can see the only solution is to update to a new virtualbox with limited performance.
It seems that I will stick with WSL 1 for a time :)

Thanks for your answers.

**Comment by craigloewen-msft** [comment]
I'm glad I can help, and we would like the WSL2 and VB story to improve in the future, and I'll post any updates on the [Command line blog](https://aka.ms/cliblog) or on Twitter as they become available.

Since we have some other discussion threads going over this same topic I'll close this out to reduce our clutter on the team but feel free to reopen/comment more if you have any other questions.

**Comment by akarasulu** [comment]
There are multiple approaches to WSL2 integration:

1. A vagrant provider for WSL2, with vagrant running on the host, which launches and manages WSL2 instances (integration needed with Virtual Machine Platform (VMP), not Hyper-V) -- I'm sure Hashicorp is thinking about this as we speak with WSL2's launch with the 2004 update.

2. Vagrant running inside WSL2 instances to launch and manage nested virtual machines inside WSL2, via other hypervisors (i.e. KVM, VirtualBox, or VMWare), but I have no idea if VMP supports nested virtualization since it is so nascent and intended to grow with the needs of WSL.

Another approach might be to have vagrant in WSL2 instances launch other sibling instances on the host but this is a stretch. It would have to talk to vagrant installed on the host. Not sure how beneficial this would be to end-users though besides having the same vagrant interface through a clean Linux command line rather than cmd/ps.

If there are new approaches or updates please share ... always interested in integrating vagrant with WSL2. Microsoft has done a great job with WSL2. Very exciting times.
