### ISSUE TITLE
WSL network problems, while using  Hamachi (even offline)

### ISSUE THREAD

**Issue by EdOverride** [microsoft/WSL#4611]
I personally don't have the time (or skill) to search this more, right now, but I thought, maybe I can help someone else, by posting this.

Windows 10, when hamachi (https://www.vpn.net/) is installed, WSL has some network connection problems, like `bundle/gem` commands don't work.

For example, commands, like `gem install <gem>`, `bundle update`, `bundle install`, commands all get error:
`Could not fetch specs from https://rubygems.org`

Even though `wget`, `curl`, `ping` commands can access `https://rubygems.org`.

This happens even if Hamachi network adapters are disabled and if it's set to `offline` mode.

I also tested, that this is the problem, by uninstalling, testing, above mentioned, commands (and they worked), and installing Hamachi again, after which same error came back.

If you need any extra info, tell me, and I'll happily add it here.

**Comment by datwaft** [comment]
Same problem, but disabling the adapter seems to make it work.

**Comment by EdOverride** [comment]
@datwaft not rly a solution..

**Comment by datwaft** [comment]
> 
> 
> @datwaft not rly a solution..

Obviously.  
As an additional, it seems that Hamachi also makes `pip install` slower.

**Comment by EdOverride** [comment]
@therealkenc May I ask, why this issue got closed if it's still a problem?

**Comment by therealkenc** [comment]
There were no takers from the community of Hamachi users given the information provided in the OP since October, other than the answer given (disable the adapter). To the extent the problem relates in some undefined way to Hamachi, the behavior of that product is not under the control of WSL. There is no actionable; and no way to repro without a Hamachi account. The purveyors of that product could in the hypothetical diagnose the problem, and if there was some actionable change to be made to WSL (or Hyper-V) that could in principle be turned into a well defined ask.

Found a nugget of information [here](https://thegeneralistit.com/blog/2016/02/20/setting-up-logmein-hamachi-gateway-as-vm-guest-on-2012r2-hyper-v-server/) in a quick google search. Can't vouch for it's accuracy (or relevance), but it would suggest that Himache is not supported with Hyper-V absent some rain-dance steps (legacy network, mac spoofing). MAC spoofing has come up in other submissions; but isn't the ask here. Legacy Network Adapter support probably falls under the "unlikely" column; with the caveat that anything can, in the hypothetical be turned into a feature request. All speculation by necessity that Legacy Network Adapter support were the solution, natch.
