### ISSUE TITLE
UserVoice redirects here

### ISSUE THREAD

**Issue by parsley72** [microsoft/WSL#4612]
The text you see when you open an issue says:
> If you have a feature request, please post to [the UserVoice]> (https://wpdev.uservoice.com/forums/266908).

But https://wpdev.uservoice.com/forums/266908 shows the message:
> To better meet evolving user feedback needs in Windows, we will retire this forum as of October 28th, 2019. Please use the links below to continue to engage and provide your feedback to us.
> WSL: https://github.com/microsoft/wsl

So where do feature requests go now, and where have all the ones that were raised previously gone?

**Comment by therealkenc** [comment]
> where have all the ones that were raised previously gone

There's a mirror issue# for every feature request of note that was ever opened in UserVoice, because there was always at least one submitter that didn't read the template. Notable entries for example CUDA #1788 or USB #2195 or graphics #230 #938. Back in the day circa 2016-2017 they were closed here, but for a long time they've been de-facto left open. A search on the [feature tag](https://github.com/microsoft/WSL/issues?q=is%3Aissue+label%3Afeature) shows the list. If there are some low-vote outliers that don't have an issue here I suppose it is now fair game to submit them. This is going to be a bit in flux until 20H1 because a number of feature requests have been addressed in WSL2.

**Comment by amazingant** [comment]
Because I got a notification for #230 being reopened, just want to mention that back in 2016, there was no issue template for users to read, and Microsoft employees were happily promoting this repository on twitter as a good place to submit bugs. The "correct" way to report things has of course changed since then, and some issues that were originally opened here assuming something was broken (like #230) have since been given the "feature" label instead.

**Comment by therealkenc** [comment]
Tue the template came later; however UserVoice was [always](https://github.com/microsoft/WSL/tree/74ace89445c79c6f609ce5eb6765e9df9542b690) the "correct" place to submit feature requests, and feature submissions were actively being closed at the time (poster child #131). Bug versus feature distinction being up for interpretation, mind, so there was always going to some built-in ambiguity. Never hurt to try.

#230 was a seriously oddball case. I think that's the only example in the now 4600+ odd submissions to date where nominally existing WSL functionality got killed. Your submission was _totally_ fair game. I suppose it could have been give a one-of-a-kind a "nothing-to-see-here" tag.

**Comment by craigloewen-msft** [comment]
I'll look into where to find the old Uservoice content and how to merge the content onto Github. When I have updates I'll post them here!

**Comment by therealkenc** [comment]
^---- In the hypothetical the old Uservoice content (we'll use the word lightly) got merged, there probably won't be a need for an update here. That flood would be hard to miss.

> So where do feature requests go now,

Here on github.

> where have all the ones that were raised previously gone?

There's a mirror issue# on this github for every feature request of note that was ever opened in UserVoice. Some of those github submissions were closed; most are still open. The ones that are closed could in principle have their status changed back to feature-open on request in the issue.

Let's call this one question->answered. To the extent it was a documentation issue, the [feature template](https://github.com/microsoft/WSL/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) is live and the [README.md](https://github.com/microsoft/WSL/blob/master/README.md) was updated. The old UserVoice links don't redirect here anymore. They're 404.
