### ISSUE TITLE
Issue with tmux when I custom my bashrc

### ISSUE THREAD

**Issue by dovankhai** [microsoft/WSL#4683]
* Before I not use tmux
![image](https://user-images.githubusercontent.com/24471733/68940041-b3400580-07d4-11ea-85ba-c3126ccb4b9e.png)

* After I use tmux
![image](https://user-images.githubusercontent.com/24471733/68940073-c9e65c80-07d4-11ea-94e9-aa97c3ee917c.png)

**Comment by craigloewen-msft** [comment]
Hi @dovankhai , what build of Windows are you running? Are you using WSL 1 or WSL 2?

For something like this, it's quite possible that it could be related to the actual Linux binaries themselves, since tmux handles drawing characters on the screen. Are you able to try your scenario on a Linux machine and see if you have the same problem there?

**Comment by dovankhai** [comment]
Hi @craigloewen-msft  
* My build of Windown is 18363.476
* I use WSL 1
* I checked my scenario on a Linux machine and everything is ok.

**Comment by dovankhai** [comment]
Hi @craigloewen-msft 
* I install the latest Windows Terminal Preview release and use Zsh. I use this them 
ZSH_THEME="agnoster"
![image](https://user-images.githubusercontent.com/24471733/69775752-5711b400-11cc-11ea-9836-b75e717da535.png)

* When I use tmux, it is not very good.
![image](https://user-images.githubusercontent.com/24471733/69775731-45c8a780-11cc-11ea-9af4-87e8777e5d32.png)
