### ISSUE TITLE
Integration guidance

### ISSUE THREAD

**Issue by PeterWone** [microsoft/WSL#4695]
I wrote an extension that adds printing to vscode. Apparently people not only use it on Windows, Linux and Apple, they even use it on WSL.

Someone posted this issue concerning browser launch https://github.com/PeterWone/vsc-print/issues/51 and the problem is well outside my experience. 

By way of context, the extension works by launching the default browser and loading the URL of an embedded webserver that renders the print job using HTML. Under WSL there's some sort of problem with the launching-browser stage, but I didn't really understand enough to troubleshoot.

This is an appeal for guidance, or suggested reading, or possibly contributors if someone cares about the problem and knows how to tackle it.

**Comment by Biswa96** [comment]
Some thoughts. The extension can use a shell script to execute Windows programs. The script can detect if it is running under WSL, for example, `uname -a | grep -i microsoft`. Then it launches Windows program, for example, `cmd.exe "start $1"`, where `$1` is the first parameter (a URL) given to shell script by the vscode extension. Here are [other ways][1] to start default browser using command line.

[1]: https://stackoverflow.com/q/3739327/8928481

**Comment by therealkenc** [comment]
Using the interop path seems to take on a quick look (somewhat surprisingly actually). This is on Insiders 19018 and WSL 2.

![image](https://user-images.githubusercontent.com/7049700/69124070-d1696800-0a57-11ea-9558-8b86c16dd0d8.png)

![image](https://user-images.githubusercontent.com/7049700/69124227-2f964b00-0a58-11ea-9de7-39c848432eee.png)

That `/home/ken/hello.txt` above is a WSL path.

The OP over on the other thread might be onto something though. That [link](https://code.visualstudio.com/docs/remote/wsl#_advanced-forcing-an-extension-to-run-locally-remotely) which talks about running the extension locally (contrast remotely) sounds plausibly what you want. From the looks, your extension (embedded webserver et al) could probably all happen local-side. I couldn't tell you how to go about the (their words) "if an extension supports it" part, mind.

The best way to test and explore remote versus local scenarios _without_ WSL would be to try your extension with the "[Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)" extension installed. You can use a remote server or VM of choice that has `sshd` live on the other side. To a first order, that is the same thing as "they even use it on WSL". Really that means "they even use it remotely", with the "WSL" distinction being not overly relevant in the context.

[Running VS Code with your extension **in a VM** is a different case entirely, because that is "all local" in the first place. Ditto running native Linux VS Code and a native browser in WSL with an X11 Server. But that's not the ask.]

**Comment by sburlappp** [comment]
The problem is that you really want this extension to run on the local Windows side, see here for a solution:

https://github.com/PeterWone/vsc-print/issues/51#issuecomment-571625618
