### ISSUE TITLE
[wsl2] Import failed with: The operation timed out because a response was not received from the virtual machine or container.

### ISSUE THREAD

**Issue by simonferquel** [microsoft/WSL#4726]
**Please fill out the below information:**
* Your Windows build number:  19018

* What you're doing and what's happening:  
Sometimes (very rarely, but it happens) registering a distro with `wsl --import <...> --version=2` fails with `The operation timed out because a response was not received from the virtual machine or container.`.
After that, wsl seem totally unusable (`wsl -l -v` hangs).
I can confirm that the machine on which I last saw the error has no file encryption/compression enabled.

* What's wrong / what should be happening instead:
wsl --import should work reliably, and errors should not put wsl in an unstable state.

* For WSL launch issues, please [collect detailed logs]:
The issue happened on a CI machine and it happens randomly and rarely, so I am unable to get detailed logs for that.

**Comment by simonferquel** [comment]
wsl --shutdown also fails after encountering this issue with `server execution failed`

**Comment by Biswa96** [comment]
> 19018

It's 19033 now.

**Comment by simonferquel** [comment]
According to https://github.com/docker/for-win/issues/5256#issuecomment-561147987, this also happens on 19033

**Comment by simonferquel** [comment]
However, out user does not see "server execution failed" on following wsl commands. Might be an unrelated problem

**Comment by benhillis** [comment]
@simonferquel - could you take a trace please?

**Comment by simonferquel** [comment]
It is difficult to trace as it is difficult to reproduce consistently.
The user reporting the issue on 19033 seemed to have the compressed file attribute. I wonder if on some conditions, windows would automatically compress ~/AppData. I'll try to explicitly unset it and see if I can reproduce

**Comment by simonferquel** [comment]
@benhillis after automatically uncompressing / unencrypting the folder we had much less occurrences of this bug.

However, we still see it happening on Windows Home 19041. Problem is, we have no way to connect to those machines in RDP to play with the machine once the problem is triggered :/.
Do you think systematically enabling the traces on all our tests would have an impact on WSL behavior ? (so that in case of failure, we can easily send them here)

**Comment by benhillis** [comment]
Enabling the traces during your tests would be a good idea and should not impact functionality.

**Comment by simonferquel** [comment]
We just updated our jenkinsfiles to do just that. Brace for a lot of log parsing :D

**Comment by simonferquel** [comment]
(also don't hesitate to ping me if you think other traces could be interesting - for hns maybe ?

**Comment by simonferquel** [comment]
[lxcorelogs.zip](https://github.com/microsoft/WSL/files/4054639/lxcorelogs.zip)
Hi @benhillis, got a repro today with logs recorded:
In our logs we have an error on deploying a distro - this is part of the first start logic:
```
[14:37:33.300][WslEngine         ][Error  ] Failed to deploy distro docker-desktop-data to C:\Users\docker\AppData\Local\Docker\wsl\data: exit code: -1
stdout unicode: The operation timed out because a response was not received from the virtual machine or container.
```
After that error, we do a second try. This time it is failing when terminating the lingering docker-desktop distro:
```
[14:37:46.897][WslEngine         ][Error  ] Failed to terminate distro: exit code: -1
stdout unicode: The remote procedure call failed.
```
Hope the logs can help!

**Comment by benhillis** [comment]
Thanks @simonferquel, do you happen to have any memory dumps for the lxssmanager service?  They would be either WER or Watson crashes, you should be able to find them in eventvwr.

Thanks!

**Comment by simonferquel** [comment]
Unfortunately these are ephemeral Azure agents, without RDP on it (and the particular instance on which this happen got scrapped out already). Would you have a powershell script at hand to automate collecting this ?

**Comment by benhillis** [comment]
@simonferquel, no I'm not aware of any automated way to collect these dumps.

**Comment by simonferquel** [comment]
Ok, let me ping @StefanScherer so that we find a way to enable at least a remote powershell to those machines and we'll monitor those kind of errors, and try to get dumps if we see this happen in the coming days

**Comment by simonferquel** [comment]
[traces and wer file.zip](https://github.com/microsoft/WSL/files/4063684/traces.and.wer.file.zip)
We managed to get a .wer file alongside the etl traces on our latest repro. I suppose the wer file is enough for you to get a dump from Microsoft diagnostics server ?

Build is 19041

**Comment by benhillis** [comment]
@simonferquel - Thanks, I was able to confirm this is an issue we have fixed and are working on backporting to 19041.

**Comment by simonferquel** [comment]
Awesome! That is actually the most frequent issue in our CI nowadays, glad to hear a fix is coming :)

**Comment by aykborstelmann** [comment]
> @simonferquel - Thanks, I was able to confirm this is an issue we have fixed and are working on backporting to 19041.

How is the state of the issue now? I have a similar issue and I'm currently on 19041 ...

**Comment by simonferquel** [comment]
Another report, with slightly different wsl.exe output (zip contains wsl.exe output + etl traces):
[report206790.zip](https://github.com/microsoft/WSL/files/4359895/report206790.zip)

**Comment by briangreenery** [comment]
This happens to be reliably every time I try to start Ubuntu that I got from the Microsoft Store.

I followed the steps here: https://docs.microsoft.com/en-us/windows/wsl/install-win10

And the very first time I started the Ubuntu container, it prompted me for the root password, then displayed:

> The operation timed out because a response was not received from the virtual machine or container.

Now every time I try to start the container, it hangs for a while then prints that message. This is easily reproducible for me since it happens every time.

I'm running Windows 10 19042.630. Is there any debugging information that I can collect or any steps that I can take to get WSL2 working?

**Comment by pranithan-kang** [comment]
> wsl --shutdown also fails after encountering this issue with `server execution failed`

Thanks for this clue, I tried this command and the problem solved.

**Comment by Dale-NUC** [comment]
Since this issue is still open I would like to add that today, I experienced WSL problem failing to import and thereafter hanging. I've run the import on the same system and a couple others without fail until now.
- System is Win10Home, 20H2, build 19042.985.

More details:
- The failed import did not complete, the .vhdx was not created.
  - I was left with a folder structures with a lot of different files. I tried to manually delete the files created during the failed import, now I have a folder which cannot be deleted since there is a folder in the tree named "apache.". The "remove-item" with "-force" option is not able to remove the folder either.
  - Removing the folder from explorer returns an error: "Could not find this item".

I've since disabled and enable WSL on the system, which seemingly fixed the WSL problem (WSL doesn't hang anymore and the Import completed on the second attempt). However. I still cannot delete the target folder created for the failed import.

**Comment by OMIDBIDBID** [comment]
i was working for git connection to wsl that i found this error too...ouuuuch......
The operation timed out because a response was not received from the virtual machine or container and i cant use  wsl --user root ........i want only ubuntu desktop ...why windoes dont let me for it by wsl......lool
