### ISSUE TITLE
bash -c "command" opens bash instead of running the command

### ISSUE THREAD

**Issue by akabhirav** [microsoft/WSL#4741]
* Your Windows build number:  Microsoft Windows [Version 10.0.19035.1000]

* What you're doing and what's happening: When I run bash -c "command" it opens up bash instead of running the command and printing the output

* What's wrong / what should be happening instead: It should run the said command and print the output

* Strace of the failing command, if applicable:  NA

**Comment by akainth015** [comment]
Can you show us a screenshot / video of how you are running `bash`?

**Comment by akabhirav** [comment]
[Video](https://youtu.be/z21Jfwzcfts) of me reproducing the error. I don't know what logs I can include with this, so please ask me to run commands and I'll give you the output

**Comment by akainth015** [comment]
As a wild guess, you have another program with a `bash.exe` in your PATH. What is the output of `where bash`?

**Comment by therealkenc** [comment]
Can't repro this here. No guesses as to how you've got your rig set up. `bash.exe` has long been depreciated in favor of `wsl.exe`. That's not the problem, but the constructive suggestion would be to run `wsl.exe`, which will at least eliminate akainth015's guess.

![image](https://user-images.githubusercontent.com/7049700/70380871-b5d6dc00-18f6-11ea-99f2-7366334d3acb.png)

**Comment by akainth015** [comment]
To add on to what @therealkenc said, you would just run it as `wsl ls -l` instead of `bash -c "ls -l"`.

**Comment by akabhirav** [comment]
@akainth015 - `where bash` returns nothing. I tried running `wsl ls -l` and that seems to be working properly. It also looks like `WSLENV` is dependent on `BASH_ENV` as it's value is `BASH_ENV/u`.

@therealkenc is there any info that I can give that'll help you figure out my configuration. There is also this problem where whenever I log-in to bash, it always logs me in as root. Could these problems be related. It seems that you were right about the deprecation

**Comment by therealkenc** [comment]
> @akainth015 - where bash returns nothing. 

That's not good out of the gate. Depreciated or not, `bash.exe` should turn up in  `C:\Windows\System32\`. n.b. In powershell [it apears](https://devblogs.microsoft.com/scripting/weekend-scripter-where-exethe-what-why-and-how/) you need to call `where.exe` explicitly contrast `where` which I guess is some cmdlet.

> It also looks like `WSLENV` is dependent on `BASH_ENV` as it's value is `BASH_ENV/u`

Neither `WSLENV` nor `BASH_ENV` get set by `wsl.exe` nor Ubuntu. What is setting them in your instance I can't guess, and speculating would probably be bad in this instance. Check your Windows environment and make sure nothing has set [`WSLENV`](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/). If so, unset it with Control Panel.

Also try moving your `.bashrc` and `.profile` out of the way so they aren't invoked when your shell starts. Since you've got unexplained default user behavior below, best to rename those two files in `/root` and `/user/you` directories, where `you` is the user you picked when you installed your distro.

> whenever I log-in to bash, it always logs me in as root

You can start your shell as a specific user with `wsl.exe -u <username>`. You can (re)set the default user with:
```
C:\> ubuntu1804.exe config --default-user ken
```
...assuming Ubuntu-18.04 was your distro. That doesn't explain how your user got set to `root` in the first place tho. Some alternative information on setting the default user in #3974.

But this is starting to smack of _effort_ for your part. The fast path here is probably to uninstall your distro and then re-install it from the Store.

**Comment by akainth015** [comment]
I believe it is still worth your time to run `where bash`. I know that works in CMD, and as @therealkenc said, it should be `where.exe bash` in PowerShell.

If that sounds like too much of a hassle, and you elect to nuke your WSL install, I recommend disabling, restarting, then re-enabling the WSL feature before reinstalling the distro to ensure that the executables in the System folder are the correct ones.

Also to note, your Windows version is higher than mine. Are you on an Insider build? If so, @therealkenc, are you aware of any related changes there?

**Comment by therealkenc** [comment]
> I believe it is still worth your time to run where bash

It is for curiosity and sport, but based on the video, it looks pretty certain he got WSL `bash.exe`, and made it to his distro's `/bin/bash`. The pause is telltale. The lack of output from `where` is explained by the Powershell quirk.

[n.b. `wsl.exe` and `bash.exe` do behave in subtly different ways by-design, but they aren't worth getting into because `bash.exe` is toast. Point was to move on from `bash.exe`, making `where.exe bash` altogether academic.]

> If so, @therealkenc, are you aware of any related changes there?

I'm on 19037, per my [first post](https://github.com/microsoft/WSL/issues/4741#issuecomment-562889012). Yes that's Insiders, as is 19035 in the OP. Actually the main reason I looked at all was the off possibility that `bash.exe` _did_ stop working as expected for some reason on recent releases, with no one noticing because (nearly) no one runs `bash.exe` anymore. `bash.exe` _did_ work on Insiders as expected, so answer no; there are no relevant changes there.
