### ISSUE TITLE
Running bash via SSH doesn't honor PS1

### ISSUE THREAD

**Issue by mkpankov** [microsoft/WSL#4748]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.476]

* What you're doing and what's happening: 
  * Install native Windows OpenSSH Server component
  * Run OpenSSH Server service
  * Connect to this machine from Linux using this command line:
```
[vagrant@adm ~]$ /usr/bin/ssh  _@10.0.2.2 -p 22 -o PubkeyAuthentication=no -t 'bash -c "PS1=\[EXPECT\]#\  bash --noprofile --norc"'
_@10.0.2.2's password:
mkpankov@DESKTOP-FNQG3V0:/mnt/c/Users/_$ exit
```

* What's wrong / what should be happening instead:

The prompt is incorrect - it doesn't account for value of `PS1` variable.

What should be happening: I get logged in and the prompt is `[EXPECT]# `.

**Comment by therealkenc** [comment]
Attempting to translate this, do you have a Cygwin/MSYS2 or similar on your win32 side, unmentioned in "what you're doing and what's happening". Is that correct?

If so, there is no reason that inner Bash's environment to make it to the outer one. A repro with actual steps, and fully qualified paths to the two `bash`es including `.exe` extension where applicable that you are intending to run there (windows paths, WSL paths) as opposed to just a naked `bash` (depending on your unmentioned `%PATH%`) might help eludicate what is going on here.

**Comment by therealkenc** [comment]
I _think_ I have what you _might_ be shooting for below.

![image](https://user-images.githubusercontent.com/7049700/70472799-98d01380-1a84-11ea-8336-1ff0ba937a1e.png)

The run was with WSL2 on 19037 Insiders, because that's what I have handy. Shouldn't technically be different on 18362 and WSL1, because there aren't any changes there that affect `$PS1` (that I'm aware of, anyway). WSL proper doesn't actually have clue-one about a `$PS1` variable. Neither does OpenSSH. But I since haven't done the run on 18362 WSL1 per your OP, the version difference bears mentioning. Bonne chance.

**Comment by mkpankov** [comment]
I've been trying your command and apparently, somehow, swapping `'` and `"` makes it fail or work!

So this works
```
[vagrant@adm ~]$ /usr/bin/ssh  _@10.0.2.2 -p 22 -o PubkeyAuthentication=no -t "wsl.exe /bin/bash -c 'PS1=foo\$\  /bin/bash --noprofile --norc'"
_@10.0.2.2's password:
foo$ exit
```

and this doesn't

```
[vagrant@adm ~]$ /usr/bin/ssh  _@10.0.2.2 -p 22 -o PubkeyAuthentication=no -t 'wsl.exe /bin/bash -c "PS1=foo\$\  /bin/bash --noprofile --norc"'
_@10.0.2.2's password:
mkpankov@DESKTOP-FNQG3V0:/mnt/c/Users/_$ exit
```

I can't see why this is the case, but the issue itself can be closed.
