### ISSUE TITLE
No internet with 3rd party AV/Firewall

### ISSUE THREAD

**Issue by russalex** [microsoft/WSL#475]
Providing a place where people can report issues running 3rd party firewalls.  For this, please report:

1) Confirm your /etc/resolv.conf nameserver matches the DNS server in ipconfig /all.
2) What AV/Firewall you're currently running (Bitdefender / Kaspersky / etc...).
3) Steps you've tried to resolve the issue (i.e. turn off the firewall, set the network adapter as trusted, etc...)

We do know from thread #5 that many people with Bitdefender have discovered turning off their firewall and / or setting their network adapter as Trusted (which basically turns off the firewall for that adapter) allows for network connectivity.

Goal of this thread is to help inform us which configurations have issues and help us document any potential workarounds as well as find any bugs / fixes we may need to address.

**Comment by StfBauer** [comment]
I'm running on Norton 360 and everything seems to work so far. Was able to install and download stuff inside of Bash on Windows.

The only problems I have are more related to the overall network implementation on Bash on Windows. Things such as ifconfig doesn't work or at least display the current IP address. Many NodeJS thing try to be dynamic and try to read the current IP Adress configuration.
This currently fails. Not sure if it is related to Firewall Issue or a general one. I think it is an general problem right now.
I think it would help if you can talk directly to the network configuration or at least have a service that fake or mirror the network adapters.

**Comment by mikeguidry** [comment]
Im using windows firewall and am trying to figure out where this new subsystem relates to configuring it.  I hope we figure it out.. I might play around and try some things..

**Comment by paladox** [comment]
Using Norton security works but using Microsoft firewall (Microsoft Defender) stops all internet access in bash I carn't access apache2 or anything with Microsoft firewall.

**Comment by cornem** [comment]
I have BitDefender Endpoint Security (which apparently I cannot turn off) and it does not work. `/etc/resolv.conf` looks OK:

    nameserver 8.8.4.4
    nameserver 8.8.8.8
    nameserver fec0:0:0:ffff::1

**Comment by cfeilen** [comment]
Running AVG Internet Security (16.81.7640), and I am unable to get any network connectivity. 
If I disable AVG's Firewall, I can use nslookup, and get a good response for microsoft.com.  If I enable the firewall, nslookup fails with: socket.c:1915: internal_send: 75.75.75.75#53: Invalid argument
I can see in my firewall logs that the application is blocking the exe's outbound connection.  I tried explicitly adding the executable under %appdata%\..\Local\lxss\rootfs\usr\bin\nslookup, but that didn't work.

**Comment by cdmackie** [comment]
1) /etc/resolv.conf is fine
2) Windows Firewall Control, which is just a friendly wrapper for the standard Windows Firewall.
3) Disabling (in my case) outgoing blocking lets Bash work fine

I run my system where all outgoing connections are blocked until they are explicitly allowed, and a firewall rule is created,

However, can't seem to find a way to allow pico processes through Windows Firewall as an exception when everything else is blocked.

**Comment by cacophobe** [comment]
Faced a boat-load of problems installing and updating Lxss with Kaspersky Total Security (KTS) installed. Tried a lot of workarounds, including unblocking networks, ports, files and folders in KTS and installing and reinstalling the whole Subsystem about five times. Uninstalling KTS solved many of the network issues. I could finally install and update using `apt-get` and `lxrun /update`.

#640 #5

**Comment by cmgibbs** [comment]
I'm using AVG Internet security and even if I'm in the trusted network and I've disabled every option on AVG ("turn off firewall until next reboot", etc.) I can't get commands such as apt-get to connect to the internet, I just get a general permission denied error. Nslookup seems to work when I disable the firewall, but nothing else - however - if I _uninstall_ AVG then everything works as it should. I can apt-get and the like without any issue; so it's some sort of issue with the AVG interaction. Any suggestions?

**Comment by ramonwirsch** [comment]
Avast Internet Security blocks internet as well. All connections seem to just hang forever. Avast's logs show no blocked traffic, deactivating the Firewall resolves this.

**Comment by azsde** [comment]
Kaspersky also blocks most of outgoing connections, especially when using apt-get update / upgrade.

Uninstalling kaspersky works great, disabling it isn't enough.

**Comment by pnegry** [comment]
+1 for broken with windows firewall. No way to create an outbound rule to allow. Disabling the firewall is not a solution.

**Comment by allquixotic** [comment]
Setting the adapter to Trusted in Bitdefender "works", but this *can't* be the long-term solution being proposed by Microsoft. There has to be some way to work with these vendors so that we can get WSL processes whitelisted by the firewall products so we don't have to disable a critical security feature to use basic networking in WSL.

**Comment by benhillis** [comment]
@allquixotic You're right, this definitely isn't a long-term solution.  Essentially the problem is that WSL we've introduced a new type of process that these firewalls don't know how to handle.  I've reached out to people at Kaspersky and will do the same for the Bitdefender folks so we can help them make the changes they'll need to enlighten their firewalls to our new type of process.

**Comment by ZatsuneNoMokou** [comment]
I am using Avast Internet Security, the logs show that it is blocking "System" because no rules found

![8d1d2f306fa7e2a6c975511e35c4aaa02](https://cloud.githubusercontent.com/assets/7016954/17374467/05a67afe-59ad-11e6-8653-5cf61ac1f9fe.png)

Could it be a problem of a unsigned file? (That's what that red message mean)

**Comment by cdmackie** [comment]
@benhillis What is, or will there. the right way to identify these processes in Windows Firewall?

**Comment by allanortiz** [comment]
I disable kaspersky firewall and windows firewall, and errors persists (No ping, apt-get with err connections, etc..). I need to remove Kaspersky?? :/

**Comment by mikeguidry** [comment]
Ben,

Is there a way to transform the data into "process information" that those third party firewalls could understand natively?  It might be counter productive to ask them to add an entirely new type.  I could be wrong long term as Linux processes, and Windows obviously could
Be treated very different...

Lol.. Windows defender is just as good as these firewalls these days.  Most use Microsoft detours as their hooks as well.. Maybe not the major but the lower 90%... Oh well.

I think it could be relatively possibly to either in real time translate a connection to requesting attention from prior WSL firewalls either in real time or a linked list being updated?  I'm not too sit considering it's closed source and I'm just observing from the outside in.  I haven't had a chance to put pico processes under IDA pro.

Have a great week.
Mike

**Comment by mikeguidry** [comment]
Technically it is an unsigned file ;) never before has there been a system polling both file types, and applications together like this.. So it's viewing ELF files (even if somehow getting a hash) as unsigned...

**Comment by degoya** [comment]
@allanortiz : did you closed or just disabled Kaspersky? 
you need to fully close Kaspersky to make it work. Shutting down the Protection for limited Time doesn't work. Also turning of all the firewall services inside of kaspersky won't help.
close Kaspersky and apt should work. no need to fully uninstall it

**Comment by allanortiz** [comment]
@degoya just disabled.  Can't I work with bash shell having kaspersky activated?

**Comment by ZatsuneNoMokou** [comment]
@mikeguidry So, there's nothing to do with Avast to allow it? Or there's a rule to make it work?

**Comment by ramonwirsch** [comment]
For me, even global rules in Avast were not applied to WSL processes. But disabling the firewall sufficed for getting connections to work.

**Comment by ZatsuneNoMokou** [comment]
@ramonwirsch But keeping firewall disabled... xD

**Comment by ramonwirsch** [comment]
I know, i know... But I use it mainly to compile stuff and only need connectivity for updates or git pulls, so for me it is not too big of a Problem....

**Comment by ZatsuneNoMokou** [comment]
But I haven't tried yet, does ssh work with this issue?

**Comment by degoya** [comment]
i think the only thing we could do is wait until all the 3rd party firewalls will update. 
For Kaspersky there is already something in the works.

[https://forum.kaspersky.com/index.php?s=662d01d349ad8497a83c6ea81871f05e&showtopic=354919 ](url)

**Comment by ZatsuneNoMokou** [comment]
@degoya And you know is there's anything for Avast?

**Comment by degoya** [comment]
@ZatsuneNoMokou : sorry, no idea if there is anything for avast in the works.

**Comment by ZatsuneNoMokou** [comment]
Sorry for asking it here, but what ip to use in Windows part to connect to wls ssh?

**Comment by pnegry** [comment]
This issue is not constrained to just 3rd party firewalls, it also affects Windows Firewall as well. Simply put, there's no way to create a rule to permit outbound connections from the WSL, for *any* firewall, and the workaround of disabling firewalling altogether is unacceptable.

**Comment by benhillis** [comment]
@pnegry If you're interested I'd suggest you read our blog on "pico processes" which is how Linux processes are implemented.  https://blogs.msdn.microsoft.com/wsl/2016/05/23/pico-process-overview/

This was not an architectural decision "let's break people's firewalls" but we don't have control over what third party code does.  I suspect what the issue is for the firewalls they are expecting some state (for example the PEB which does not exist for NT processes) to be present, that is not for pico processes (by design).

Also - Windows Firewall does allow you to create generic "allow port X" rules are respected for pico processes.

**Comment by degoya** [comment]
without the firewall the bash is really useless for me because nowadays you won't go without firewall. so i will stay in my VM with Debian until 3rd party fixed the problem :D

**Comment by pnegry** [comment]
@benhillis 'port X rules' are not respected if the outbound firewall is enabled. You cannot even create a socket. Here's a test:
 - firewall in "Outbound connections that do not match a rule are blocked" ("Block" mode in the gui)
 - Outbound Rules -> New Rule  -> Port-> TCP, Specific remote ports: 22 -> Allow the connection -> Apply to all profiles -> Name: Permit 22

in bash:
pnegry@XXXX:~$ telnet 192.168.23.10 22
Trying 192.168.23.10...
telnet: Unable to connect to remote host: Permission denied

Can someone provide a working windows firewall ruleset, in BLOCK mode, where pico is permitted outbound? I can only get it to work with 'Allow'.

**Comment by aseering** [comment]
@degoya -- for what it's worth, I haven't bothered configuring firewalls on my machine in years; I always just go with stock settings, and I've never been hacked, caught a virus, etc.  The stock Windows firewall's defaults work with WSL; they just mostly restrict inbound connections, not outbound.

(Well, not never.  Once, in recent memory.  But that was a Linux machine, not Windows, and a long story.)

That said, my usage patterns are weird :-)  Firewalls do help people; I agree that this is an important use case to get working ASAP.

**Comment by THPubs** [comment]
Just installed the new update just to get Bash and now it's not working :-( I also have the same issue and I run Kaspersky.

**Comment by degoya** [comment]
without the firewall the bash is really useless for me because nowadays you won't go without firewall. so i will stay in my VM with Debian until 3rd party fixed the problem :D

**Comment by foxx1337** [comment]
I'm using the builtin Windows Firewall with "Outbound connections: Block" and I don't understand what I should whitelist in order to have connectivity from lxss.

When I set the firewall to "Outbound connections: Allow" connectivity returns to lxss processes.

**Comment by pnegry** [comment]
@foxx1337 this is not clear at all, also the title of this issue is misleading because its not just third party products that are affected, which i think leads the dev team to deprioritise the issue

@russalex would you please consider renaming the issue to "No internet connectivity through host-based outbound firewalls" and edit the initial comment accordingly.

Also please note that configuring blanket exceptions for ports, especially 80/443, is not an acceptable fix. Most malware uses these ports for C&C so adding these exceptions compromises the utility of an outbound firewall.

**Comment by ATouhou** [comment]
Avast also breaks internet connection, even though it does not prompt, and settings are set to prompt

**Comment by zbtlxjxi** [comment]
**AVG Firewall (AVG 2016) supports pico processes, but special settings have to be applied.** (The last checkbox in screnshot.)
![wsl_eng](https://cloud.githubusercontent.com/assets/20947168/17551203/01ef0204-5ef9-11e6-9a9d-2df45cd8feda.png)

Open AVG UI, press F7 (Firewall settings), click Expert mode button, select Advanced Settings and check the last checkbox. OK.
If there is no WSL checkbox, you have older AVG version or your OS does not support WSL.

**Comment by degoya** [comment]
has there been any updates lately?
i just tried again and now when i do a apt-get with kaspersky then Kaspersky will be disabled automaticaly and after apt-get is finished it will enable the firewall/AV again.

**Comment by THPubs** [comment]
Still not working for me under Kaspersky :-(

**Comment by Tekki** [comment]
With Kaspersky Internet Security 17.0.0.611(b) both "apt-get update" and "apt-get upgrade" work.

**Comment by THPubs** [comment]
Yeap Kaspersky just fixed the issue :-)

**Comment by ascjones** [comment]
This is also an issue with Symantec Endpoint Protection 12.1. 

Works when firewall disabled.

**Comment by bottemav** [comment]
Just upgraded my Bitdefender Internet Security to version 2017 (21.0.18.898) and now I can perform a "apt-get update" and "apt-get upgrade".

**Comment by dev169** [comment]
@benhillis If you are willing to work with third party vendors to fix this issue, I believe there should be an analogous initiative for the Windows built-in firewall, because using WSL appears to be impossible when outbound connections are blocked by default (which is the only secure configuration), and it appears there is no way to whitelist Pico processes (yet?). Is this recognized as a defect? If so, if there is any progress on that front, it would be great if it could be shared. 

As an aside, I've seen @aseering [mentioning](https://github.com/Microsoft/BashOnWindows/issues/1488#issuecomment-268269088) that the Windows firewall works without being explicit regarding how it is configured (see my ref. above regarding outbound connections). I think it would be great if some further details would be added here, since this issue# captures many of the related but scattered reports and could serve as a good reference point for future readers.

**Comment by benhillis** [comment]
@dev169 - We are absolutely willing to work with third party AV and firewall vendors. In fact we've published a [blog post](https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/) and a document about how to update their software to use the new PS notification infrastructure we have added since Anniversary Update.

**Comment by dev169** [comment]
@benhillis But the Windows built-in firewall doesn't work with Pico processes either. That was my point above. And to reiterate my question, taking into account the blog post you linked, is that being worked on for the Creators Update?

**Comment by russalex** [comment]
@dev169 We have been in contact with the AV / Firewall teams within Windows.  I do not know their timelines so I can not speak for what will be released in the Creators Update, but I can say that we have an open line of communication with them.

**Comment by dev169** [comment]
@russalex Thank you for the extra information.

**Comment by sological** [comment]
Anyone got this to work on the Windows built-in firewall? I didn't. And I am using creators update.

**Comment by aseering** [comment]
Are you using the stock configuration of Windows Firewall / you haven't locked things down further?  That configuration works fine for me.

Though, a bunch of people have recently reported problems with any configuration, even the Windows firewall disabled and all other firewalls completely uninstalled.  I don't think the cause of those failures is fully understood yet?

**Comment by sological** [comment]
@aseering  Not stock, I'm using "Windows Firewall Control" set at medium which blocks connections with unmatched outgoing rules.
Letting it add pico as an allow rule doesn't work.

**Comment by aseering** [comment]
@sological -- yeah, that's a known limitation.  The WSL team has said elsewhere that, as of Creators, WSL exposes an API that allows firewall developers (including the Windows Firewall) to firewall WSL processes correctly.  So now it's up to those teams to implement that functionality.

**Comment by mageta** [comment]
Since this is now out of Beta, may I ask how to use any WSL 'container' with just the simple Windows Defender Firewall (this is the firewall that is bundled with windows itself)? No other 3. party tool is used! I did set my Domain/Private/Public Profile to:

 * Firewall state: On (recommended)
   * Inbound connections: Block (default)
   * Outbound connections: Block
 * Every network is protected.

Then I enter rules for all the stuff I want to make outbound/inbound connections. But I can not figure out how to enable any of the linux tools (like zypper, or apt-get). Usually - for all the other normal application - this works just fine.

I do not want to disable any of my general profile settings, nor do I want to make blanked rules that allow all http traffic.. that would render the whole firewall pointless IMHO.

I saw this article here https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/ mentioned in the context. But I am not sure how this is gonna help me. I think this is the hint as to how to implement this in a 3. party product.

**Comment by techexo** [comment]
Indeed, I can only add my voice to the one of @mageta! How can we configure Windows Firewall (or close-related softwares like TinyWall) to be an actual firewall **and** having network connectivity inside WSL?

I do not understand how such a major security component could have been overlooked while developing WSL. Is there any real documentation available for firewall developers to support Pico processes?

Regards

**Comment by CottonEaster** [comment]
> I do not understand how such a major security component could have been overlooked while developing WSL.

I agree.

> Is there any real documentation available for firewall developers to support Pico processes?

That seems like a good question.

**Comment by sunilmut** [comment]
@techexo - We understand the frustration, but, this is work in progress. We have made available all the necessary document to the AV vendors to play nicely with WSL (or pico) processes. They have to do the work on their end. Community push like [this](https://forum.kaspersky.com/index.php?/topic/354919-bash-shell-for-win-10-linux-subsystem-for-windows/) helps.

We are also looking at ways to improve integration of Windows defender with WSL processes.

**Comment by techexo** [comment]
@sunilmut Why this documentation is not available online? I cannot find it.

It is really frustrating because WSL was particularly advertised when it was released as a super cool new functionality, finally allowing developers to have the best of both environments, but it is not even compatible with Windows's own firewall! I find strange that companies have updated their softwares under pressure of the community, but Microsoft is not able to do that with one of its own product.

**Comment by therealkenc** [comment]
It is inaccurate to describe WSL as incompatible with Windows Firewall. WSL is as compatible with Windows Firewall as Docker.

The blog post on pico processes and antivirus/firewall software is [here](https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/). Which is kind of beside the point unless you work for a 3rd party antivirus or firewall company, who know how to reach Microsoft and ask.

**Comment by vith** [comment]
> WSL is as compatible with Windows Firewall as Docker.

I don't think that's quite accurate either.

I just installed Docker on Windows and I was able to get network access in a container. I could use that. (If it didn't use Hyper-V or if Hyper-V being enabled didn't stop Virtualbox or VMWare from working).

In WSL I cannot get any network access. I can't use that.

**Comment by sunilmut** [comment]
@techexo - All we are trying to say is that WSL is work in-progress. We never advertised it as "done". As for WSL integration with Windows firewall, as mentioned previously, we are trying to **improve** integration. They are not fully incompatible. Windows firewall will not by default block WSL processes, unless there are some very-restrictive firewall group policies. The place where the integration is lacking is the inability to specifically exclude a WSL process in the firewall. We are looking into improving this experience.

**Comment by therealkenc** [comment]
It seems, from here anyway, that folks are conflating giving WSL it's own network alias (`ifconfig eth0 192.168.0.123 up`), and the perceived requirement to whitelist `/usr/bin/wget` in Windows Firewall. The latter makes basically no kind of sense, because `/usr/bin/wget` isn't signed (by Windows) and can be replaced at will with normal user privileges. Or, if you insist, makes perfect sense (for reasons), but is not the reason you can get out to the Interwebs from a Docker container.

**Comment by vith** [comment]
I just meant that the end result for a user with a default block rule in Windows Firewall is that Docker is possible to use and WSL is not. If it is, please let me know!

I would be perfectly fine with just bridging WSL to my network adapter and letting it bypass Windows Firewall altogether, as is the case with the desktop oriented hypervisors I've used.

I'm actually not personally interested in whitelisting individual linux binaries inside WSL, though I would go that route if it were available and necessary.

I'm sure there's 1000 different ways for a truly malicious application to bypass Windows Firewall, as you alude to. I have no expectation that it's a secure solution. And yet Windows Firewall allows path based rules, and many people use them. For stronger security I would use a virtual machine with no networking (and there be subject to VM escapes anyway).

**Comment by therealkenc** [comment]
> default block rule in Windows Firewall is that Docker is possible to use and WSL is not. If it is, please let me know!

It is not, AFAIK, because `ifconfig eth0` and friends is not supported in WSL. Closest User Voice I could find is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/15592293-iproute2). Maybe there is a better one.

**Comment by techexo** [comment]
> They are not fully incompatible. Windows defender does not block WSL processes. The place where the integration of WSL with Windows firewall is lacking is the inability to specifically exclude a WSL process in the firewall.

So it seems that maybe I skipped a step somewhere? Because with quite a classical configuration for a firewall (i.e. block everything going out and going in if it has not been explicitely whitelisted), I understood that WSL as a whole was not exclude-able. Am I wrong? Or "a WSL process" is what you call the entire subsystem running?

I am more in the situation described by @vith and have no interest of whitelisting individual binaries, just having a way to bypass Windows Firewall for WSL, without deactivating the firewall it for the whole system.

**Comment by sunilmut** [comment]
There seems to be a general interest towards an "allow all" WSL processes. I am curious to know where there is coming from. Is it because of DNS queries?

**Comment by therealkenc** [comment]
Yep they want 53 open. And 80. And 443. Like [this](https://github.com/Microsoft/WSL/issues/1852#issuecomment-358847525). Or pick your port poison.

The ask is because people have spent years in Docker and Cygwin. With Docker you can write firewall rules for Docker's IP address _in Linux_. With Cygwin you can whitelist `wget` because it is just a Windows binary. With WSL you cannot.

**Comment by therealkenc** [comment]
> Given the option of letting WSL completely bypass Windows Firewall I would do that and use it for a few things that I use VMs for now.

That is equivalent to option (1). Because WSL _is Windows_ and anyone who has user privileges that allow them to call call `socket()` in a win32 executable (the thing you are presumably trying to prevent with your _outgoing_ firewall rules) can call `bash.exe -c thing_that_calls_socket` instead.

That said, I have no doubt adding a "allow all pico processes" checkbox in Windows Firewall will make people happy anyway. So sure, why not. Though I would like to be room with the Windows Firewall team when the task ticket is submitted just to hear the "Really?"

**Comment by techexo** [comment]
@therealkenc , good remark indeed. And I suppose there is no way of using iptables with WSL like you would on a classical UNIX system?

**Comment by therealkenc** [comment]
Yeah no iptables. Yet.

**Comment by aimlessadam** [comment]
Back towards the end of 2016, @russalex posted that the internal Windows Firewall team was being looped in; Have they recognized the problem with the native Windows Firewall and outbound whitelisting?

thanks!

**Comment by yonailo** [comment]
+1 to fix this issues for Kaspersky, does anyone know a page for making requests to Karspersky team ?

**Comment by Tekki** [comment]
@yonailo I wonder what exactly doesn't work in your case. I've Kaspesky Internet Security installed and use WSL daily to fetch code from GitHub and to connect to my local and external servers without any problems.

**Comment by bbday** [comment]
At the moment to work with Kaspersky AV you must go on settings > advanced > network > monitor port and disables 80/443

**Comment by Jacq** [comment]
> Kaspersky also blocks most of outgoing connections, especially when using apt-get update / upgrade.
> 
> Uninstalling kaspersky works great, disabling it isn't enough.

Disabling works for me but it is not unblocked immediately, usually there is a delay of some seconds (less than a minute for sure).

**Comment by WillyShum** [comment]
I've got Avast Internet Security and I've tried disabling firewall and included a rule to allow WSL' ping directory full access. But I still cannot ping any thing on wsl ubuntu for windows 10

**Comment by dreadnautxbuddha** [comment]
I was having issues with my Vagrant on WSL wherein accessing an external API doesn't seem to finish. Checking the logs of the server where the API resides isn't showing anything since I really was not able to connect. Found out that BitDefender was the culprit. For now, I added my API's domain name in the exclusions and everything works fine now.

**Comment by Mizumaky** [comment]
Had first a problem failing all connections, then only some but still couldnt install gcc.
Finally solved by trying editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4." while also completely turning off Kaspersky Free anitivirus, and kinda trying apt-get update and somehow i got apt-get install gcc to download the rest and work. Also i looked at the port behind ip adresses of failed connections and tried disabling protection for the specified port in the antivirus settings - that helped me to get at least some connections working, yet even some on that port still didnt go through idk why.

**Comment by Trass3r** [comment]
> 
> 
> Back towards the end of 2016, @russalex posted that the internal Windows Firewall team was being looped in; Have they recognized the problem with the native Windows Firewall and outbound whitelisting?

Yeah any updates?

**Comment by Tekki** [comment]
An update for Kaspersky: Getting worse with newer versions. Individual processes from WSL like apt-get or git appear in the program list, but even if they are trusted the connection is blocked. Disable controlling of port 80 and 443 (Settings--Additional--Network) solves most of the problems, but of course reduces the security of the system.

**Comment by Hameem1** [comment]
I'm trying to get a Flask app running via WSL and I can't open it from the browser via 127.0.0.1:5000. I have an Avast antivirus. I tried setting the adapters to private (trusted) and adding rules to allow for wsl.exe and bash.exe. I also added them to the exclusions list just to be sure, but it doesn't work. However, disabling the Avast firewall works but that isn't a real solution. Is there any fix to this by now? It's 2019!

**Comment by Tekki** [comment]
It's a misunderstanding to think the processes run inside WSL; they run directly on the Windows kernel. If you type for example
```
perl -E'for (1..60) { say $_; sleep 1 }'
```
into WSL and open the Windows Task Manager, you will see 'perl' for one minute on the list. This means not WSL or bash, but Perl, Python or whatever process you start needs to be trusted by the firewall. This is probably what the AV developers don't understand.
Of course it's shame that in 2019 these companies still take our money for their security products and are still not able to handle such a Windows feature.

**Comment by tingjhenjiang** [comment]
Now I'm using WSL 2 and avast internet security and the network connection are blocked by avast firewall. If I turn off avast firewall network connection works well. When firewall is on, even after I add 
"C:\Windows\System32\lxss\wslhost.exe"
"C:\Windows\System32\bash.exe"
"C:\Windows\System32\wsl.exe"
"C:\Windows\System32\conhost.exe"
to new application rule(all allowed), network connections are still blocked.

**Comment by uniibu** [comment]
@tingjhenjiang all you have to do is go to Settings -> Protection -> Firewall -> Check the **Internet Connection Sharing Mode**. You can now access the internet on WSL2 without disabling Avast Firewall. 
![image](https://i.gyazo.com/65a57de0b46e07865d8ea012f075ffac.png)

**Comment by tingjhenjiang** [comment]
> 
> 
> @tingjhenjiang all you have to do is go to Settings -> Protection -> Firewall -> Check the **Internet Connection Sharing Mode**. You can now access the internet on WSL2 without disabling Avast Firewall.
> ![image](https://camo.githubusercontent.com/d39ec37b7106802f13e656decce249c8b010ac34/68747470733a2f2f692e6779617a6f2e636f6d2f31353265663434663362353461633335373332646561626661323262333561632e706e67)

Hello uniibu,
I found out that the solution you provide does not work for me.

It is still worth noting that if I switch the option "For programs with no defined rules(i.e. programs not listed on the Application Rules page), do the following" from either "auto-decide" or "ask" to "allow", the connection works well, though it is not what I'm expecting.

**Comment by denniswed** [comment]
I know this thread is a little old, but is still very relevant, especially with WSLv2. Symantec Endpoint Protection, specifically the "Network and Host Exploit Mitigation" is blocking traffic coming back from our proxy. It sees the target IP address as unknown because that IP address is internal to the workstation and being NAT'd through the virtual interface WSLv2 appears to use. If I convert my instance to WSLv1, I don't have any network problems. Interestingly, Docker Desktop containers, installed and running with WSLv2, do NOT have the same problem. They work just fine.

**Comment by dadeke** [comment]
Avast Real Site is causing this issue here.

Disable Real Site and all DNS resolutions working in WSLv2 .

![Avast_Real_Site](https://user-images.githubusercontent.com/6050573/165384231-7bc5fdbc-5951-430c-abc6-06b6f751ecc5.png)

[How do I set an exclusion for Real Site?](https://support.avast.com/en-eu/article/188/#idt_070)

I added `dns://*.github.com*` but not working. 🤔
