### ISSUE TITLE
improper result for date command.

### ISSUE THREAD

**Issue by soudai** [microsoft/WSL#4783]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.19041.1]`

* What you're doing and what's happening:  (Copy&paste the full set of_specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```sh
$ date --iso-8601=ns
2019-12-24T19:00:27,357428100+09:00
$ date --iso-8601=ns
2019-12-24T19:00:29,109509200+09:00
$ date --iso-8601=ns
2019-12-24T19:00:29,806925600+09:00
$ date --iso-8601=ns
2019-12-24T19:00:30,290930200+09:00
$ date --iso-8601=ns
2019-12-24T19:00:30,679012400+09:00
$ date --iso-8601=ns
2019-12-24T19:00:31,184642700+09:00
```

* What's wrong / what should be happening instead:

Make sure the last two digits of nanosecond are `00`.
It works only when php is WSL in the following cases.

> But "u" can only parse microseconds up to 6 digits, but some language (like Go) return more than 6 digits for the microseconds, e.g.: "2017-07-25T15:50:42.456430712+02:00" (when turning time.Time to JSON with json.Marshal()). Currently there is no other solution than using a separate parsing library to get correct dates.

golang truncates when trailing 0.

https://www.php.net/manual/en/datetime.formats.php

**Comment by therealkenc** [comment]
> Make sure the last two digits of nanosecond are 00.

Can you clarify the ask on this one a bit? WSL 2 (what I checked) does appear to always (sic) end the ns clock as '00', whereas Native Linux on metal returns rando two-digits (with a one in a hundred chance of '00'). That's a resolution thing, and probably the case on Hyper-V too.

But either way, your repro command always returns nine digits (as it must, because billions).

**Comment by soudai** [comment]
> Can you clarify the ask on this one a bit?

Thanks for the reply.

> WSL 2 (what I checked) does appear to always (sic) end the ns clock as '00',

That's exactly right.

I want to behave like Native Linux.
But it turned out to be difficult, thanks to you.

PHP applications developed with WSL may not work on Native Linux.

I will be careful about that.

**Comment by therealkenc** [comment]
> PHP applications developed with WSL may not work on Native Linux.

Thanks for the follow-up. Either you've identified a bug in your PHP stack where your scenario (whatever it is) would fail 1/100 calls. This is possible but unlikely. Or there is something wrong with your scenario (the code) itself.

It sounds like you're unblocked by "being careful" (careful by whatever means), so that's good news. You might want to try a PHP group ([stack overflow](https://stackoverflow.com/questions/tagged/php) maybe), post a minimal script exhibiting the behavior, and get feedback on what went wrong and/or the best approach. _Minimal_ is going to be critical to getting a good reply. 

One could hypothetically contort this into a timer resolution ask, but that doesn't appear to be what is going on here. [You are going to come up zeros on Real Linux eventually too.]
