### ISSUE TITLE
uptime output is not correct

### ISSUE THREAD

**Issue by gpakosz** [microsoft/WSL#4791]
![image](https://user-images.githubusercontent.com/553208/71622953-85bee800-2bd9-11ea-8a83-61ba14f095d6.png)

In the screenshot above, you can see:
  - on the left Ubuntu 10.84 running in WSL 1
  - in the center, Cygwin
  - on the right, Windows Task Manager

While Cygwin's `uptime` command agrees with Task Manager, Ubuntu's `uptime` command reports an uptime shifted by ~3 days 🤷‍♂️

 I'm running Windows 10 Version 1903 (OS Build 18362.418).

**Comment by tkharris** [comment]
WSL seems to blur the lines between a container (a la docker) and an alternate toolchain (a la Cygwin), but I tend to think of it more like a container, in which you would want uptime to reflect the container time, and not the host system time. Could you have started (or restarted) wsl 3 days after boot?

```
PS C:\Users\tharris> wsl --shutdown
PS C:\Users\tharris> bash
tk@DML2015W:/mnt/c/Users/tharris$ uptime
 11:50:50 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
tk@DML2015W:/mnt/c/Users/tharris$ uptime
 11:51:47 up 1 min,  0 users,  load average: 0.00, 0.00, 0.00
```

**Comment by gpakosz** [comment]
I don't recall interacting with `wsl` from the command line

**Comment by therealkenc** [comment]
One WSL `/proc/uptime` counts from when the WSL instance begins. Treads by-design.

![image](https://user-images.githubusercontent.com/7049700/71638647-2b924700-2c1a-11ea-90f2-c4ad193e15de.png)

**Comment by therealkenc** [comment]
Calling this by-design. The implied ask here is possible (because anything _possible_), but you'd be looking at some kind of upstream Linux kernel change to the `/proc/uptime` plumbing such that it reported the uptime of the OS running the host VM (be it hyper-v,  qemu, virtbox, vmware). Maybe someone has even thought about doing this before; didn't look. Trouble imagining the use-case.
