### ISSUE TITLE
Port 53 bug?

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/WSL#4818]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.21]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Trying to boot Kali in WSL 2 with something else (https://github.com/DNSCrypt/dnscrypt-proxy) listening on port 53 ... seems like that is incompatible atm? O.o

* What's wrong / what should be happening instead:

Both programs should work together ...

**Comment by privacyguy123** [comment]
Repro = have another program listening on port 53 then try to launch Kali.exe from Windows terminal

**Comment by privacyguy123** [comment]
Sorry - this is a WSL 2 specific bug. I wil repost over there, feel free to close. :)

**Comment by privacyguy123** [comment]
Bump?

**Comment by therealkenc** [comment]
> Trying to Kali 

Not a verb.

> have another program listening on port 53 then 

Not a full set of _specific_ command-line steps necessary to reproduce the behavior (text which is still on the screen).

> with something else (https://github.com/DNSCrypt/dnscrypt-proxy)

Probability of that link being followed was... small. Probability of someone investing time in reading `dnsscript-proxy` documentation to see if there is something to the problem. Smaller. Partly because running `kali.exe` starts `/bin/bash`, which is unrelated to ports being open.

But despite probabilities, made me look. Cannot repro here, even having tried. At least AFAICT with the scenario assumed.

```
$ wget https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.36/dnscrypt-proxy-linux_x86_64-2.0.36.tar.gz
$ tar xf dnscrypt-proxy-linux_x86_64-2.0.36.tar.gz
$ cd linux-x86_64
$ sudo ./dnscrypt-proxy -config example-dnscrypt-proxy.toml
```

![image](https://user-images.githubusercontent.com/7049700/73185644-49e14a80-40d3-11ea-9dd6-d221bd9a6626.png)


This was on 19951 WSL2. Version difference might matter vs OP 19041. Probably not.

**Comment by privacyguy123** [comment]
The problem only exists if something is listening on Port 53 on the Windows host side, perhaps I should have clarified that.

**Comment by therealkenc** [comment]
> The problem only exists if something is listening on Port 53 on the Windows host side

There is "something" listening on port 53 on the Windows host side. Because Windows has a DNS service. If it didn't, nothing would be answering the phone when libc's resolver looked up the address in WSL's `/etc/resolv.conf`, and tried to resolve a name.

This cap is with WSL shutdown entirely:

![image](https://user-images.githubusercontent.com/7049700/73209893-02bc7f00-40fe-11ea-82ed-a8ba23e57b78.png)

> The problem only exists 

To be clear, "the problem" hasn't been stated. "What's wrong" (also at the [top](https://github.com/microsoft/WSL/issues/4818#issue-551031459)) was not answered. [Starting `kali.exe` from a second Windows command prompt hangs and never gets to the `/bin/bash` prompt I'm assuming. But that's only a guess, by necessity.]

**Comment by craigloewen-msft** [comment]
@privacyguy123 can you upgrade your build to 19541 or later and then try your repro steps and see if you hit the same problem?

We put in a fix and want to make sure it addresses the problem. See this comment: https://github.com/microsoft/WSL/issues/4364#issuecomment-575743453 for more details.

**Comment by privacyguy123** [comment]
Thanks for the clarification!

**Comment by alpe89** [comment]
I resolved my issue updating docker desktop, I don't know why but dockerd.exe was listening on port 53. That was blocking wsl to start.
