### ISSUE TITLE
Is it possible to hook up some more /sys/class locations

### ISSUE THREAD

**Issue by sfoxover** [microsoft/WSL#4826]
I wanted to use WSL 2 for developing in C++ on Windows 10. But I have found its not working like a full Linux Distro. I have upgraded to Ubuntu 19.10 server on WSL 2 but found it missing /sys/class folders.

I would like to be able to test and use "/sys/class/thermal/thermal_zone0/temp" to read the CPU temperature. I assumed WSL 2 would work exactly the same as Ubuntu 19.10. 

Unfortunately it means I will need to use a real Linux box.

**Comment by andreujuanc** [comment]
Hi @sfoxover  
Did you find a way to do this?

**Comment by Victormeriqui** [comment]
This has not been fixed in WSL2, I am running Ubuntu 22.04 on WSL2 and do not have `thermal_zone` folders in `/sys/class/thermal`:

![image](https://user-images.githubusercontent.com/1396008/218535936-c4b3b406-3615-4e52-a866-740c54480fa0.png)
![image](https://user-images.githubusercontent.com/1396008/218535646-392941ee-2b12-418c-935f-13165afeefb6.png)

**Comment by eddiemMenefee** [comment]
I'm running Debian (bullseye) on WSL2 and also do not have `thermal_zone` folders in `sys/class/thermal` :

![screenshot-wsl2-thermal-list](https://github.com/microsoft/WSL/assets/116319343/1d21efb8-c897-44e6-94ea-212f830c692a)

![screenshot-wsl2-running-state](https://github.com/microsoft/WSL/assets/116319343/0d3eda99-6fb7-4e41-bdf9-4c1067256998)
