### ISSUE TITLE
WSL with NVIDIA Optimus laptops

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/WSL#4846]
I suspect there's something going on with these type of laptops that  have a Intel UHD 630 integrated/NVIDIA GTX 10xx hybrid ("Optimus") setup as I can't get WSL to recognise I have an NVIDIA card installed at all - is there any workaround/hack/fix for this?

**Comment by craigloewen-msft** [comment]
WSL doesn't gives access to the graphics card on your device. This is a (very popular) feature request and one that we are investigating! If you'd like any updates please follow this Github issue: https://github.com/microsoft/WSL/issues/829 and we'll be sure to post there when we have updates. 

I'll close this issue out for bookkeeping since I believe I've answered your question, feel free to comment more if I may have missed something or you have more questions.
