### ISSUE TITLE
git instaweb fails with "500 - Internal Server Error"

### ISSUE THREAD

**Issue by rpici** [microsoft/WSL#4871]
### 1)  Issue Title:
git instaweb fails with "500 - Internal Server Error"

### 2) Your Windows build number:
Microsoft Windows [Version 10.0.18363.628]

### 3) Steps required to reproduce
1. Download and install Ubuntu for WSL from the Microsoft Store, then open the Ubuntu WSL terminal.

2. sudo-apt-get update; sudo apt-get install -y git lighttpd w3m

3. mkdir test && cd test

4. git init

5. sudo git instaweb
(You will see a 500 internal server error message here in addition to below)

6. From the host Windows machine, open a browser and go to:
    localhost:1234

After step 6, a "500 internal server error" message will be displayed in the browser.

### 4) What should be happening instead:
The browser should display a web interface to view the current git repo.

**Comment by therealkenc** [comment]
Confirmed here, although the fail is slightly different with my particular rig.

![image](https://user-images.githubusercontent.com/7049700/73697332-25690d80-4693-11ea-916d-33c2e1155713.png)

Put up the strace [log](https://gist.github.com/therealkenc/0b88ef488090afe91c517d21deeeeae6) for the pedantry. End-game below. Looks to be suicide by `tgkill`, for reasons that would need digging in the source. The error occurs in `/usr/bin/w3m` which does get some [google hits](https://www.google.com/search?rlz=1C1CHBF_enCA874CA874&sxsrf=ACYBGNRcTBMSPJQg6OO8SvZqzjlQqojatQ%3A1580770530808&ei=4qQ4XvT6MNiz0PEPivyEgAo&q=w3m+wrong+__data_start&oq=w3m+wrong+__data_start&gs_l=psy-ab.3..33i160.3822.14177..14276...0.1..0.383.2444.17j2j2j1......0....1..gws-wiz.......0i71j35i39j0i273j0i131j0j0i67j0i10i67j0i10j0i20i263j0i22i30j33i10.EZPZk0aQXmE&ved=0ahUKEwj089aPvbbnAhXYGTQIHQo-AaAQ4dUDCAs&uact=5).

Practical suggestion would be to try WSL 2 and see if it fares better.

```
1505  munmap(0x7ffee2600000, 43527)     = 0
1505  set_tid_address(0x7ffee1bf1510)   = 1505
1505  set_robust_list(0x7ffee1bf1520, 24) = 0
1505  rt_sigaction(SIGRTMIN, {sa_handler=0x7ffee1c14c50, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7ffee1c22540}, NULL, 8) = 0
1505  rt_sigaction(SIGRT_1, {sa_handler=0x7ffee1c14cf0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7ffee1c22540}, NULL, 8) = 0
1505  rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
1505  prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
1505  write(2, "Wrong __data_start/_end pair", 28) = 28
1505  write(2, "\n", 1)                 = 1
1505  rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
1505  rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
1505  getpid()                          = 1505
1505  gettid()                          = 1505
1505  tgkill(1505, 1505, SIGABRT)       = 0
1505  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
1505  --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=1505, si_uid=0} ---
1505  +++ killed by SIGABRT (core dumped) +++
1490  <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGABRT && WCOREDUMP(s)}], 0, NULL) = 1505
1490  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=1505, si_uid=0, si_status=SIGABRT, si_utime=0, si_stime=0} ---
1490  rt_sigreturn({mask=[]})           = 1505
1490  write(2, "Aborted (core dumped)\n", 22) = 22
1490  read(10, "", 8192)                = 0
1490  exit_group(134)                   = ?
1490  +++ exited with 134 +++
```

**Comment by therealkenc** [comment]
> Practical suggestion would be to try WSL 2 and see if it fares better.

WSL 2 does not appear to fare better (which is mildly surprising). Data point to save you going Insiders to look.

**Comment by therealkenc** [comment]
The Internal Server Error is due to missing `libcgi-pm-perl` and (possibly) `gamin`.
```
$ sudo apt install libcgi-pm-perl gamin
```

On WSL 1 I am still getting the deep-in-glibc, which I think is a really bad fail path trying (?) to launch a local browser. That's a guess. There is _probably_ some kind of (entirely academic) diverge in WSL 1, that we will almost certainly never know. That much tag fixedinwsl2. It doesn't matter because the `lighthttpd` lights up anyway. 

Don't read much into Insider build 19555. Nothing has changed in WSL1 since 18363 that would be relevant. The root cause of the Internal Error was the missing package(s), which would be tag linux-behavior or tag external (ie not WSL's wheelhouse).

![image](https://user-images.githubusercontent.com/7049700/73713091-fbc6db00-46c0-11ea-8790-5450918ad928.png)

**Comment by rpici** [comment]
Amazing, that fixed it for me.  I'm not sure what's causing the error you're still getting, but on my rig, your fix gets git instaweb working perfectly.

How did you figure out that those missing packages would do the trick?

Thank you!

**Comment by therealkenc** [comment]
> How did you figure out that those missing packages would do the trick?

I ran it on Real Linux (Ubuntu on metal) to see why it wasn't working on WSL 2 (which to a first order "can't happen" because WSL 2 is Real Linux). It failed out of the gate on a missing dynamic library load, because missing `gamin`. 

After installing `gamin` it failed with the same with the same Internal Error. I dumped an [`strace(1)`](http://man7.org/linux/man-pages/man1/strace.1.html) and it was pretty easy to see it looking for, and failing to find, `/usr/share/perl5/CGI.pm`. Which, even without me really speaka the Perl, seemed kind of important for a Perl CGI script to have. Installed it on Real Linux and it lit up. Installed it on WSL 2 and it lit up. Installed it on WSL 1 and it lit up with the `__data_start` caveat.

I'm content to ignore the `__data_start` thing. There's a lot of moving parts to `git instaweb`, and one can't ever really ensure every moving part is the same on all the runs without considerable _effort_. Others have hit that error in not-WSL `w3m` scenarios. It is probably a userspace thing if it is working for you, not actually a fixed-in-wsl2 thing. Not curious enough to look. Glad it is working for you.

**Comment by rpici** [comment]
If you don't mind, can you explain what you mean exactly by Ubuntu on metal?  Because I just tried to reproduce the error on a fresh VM with Ubuntu 16.04.6 (desktop AMD-64 version), and if I follow the steps to reproduce given in my original post, it doesn't fail with the `gamin` error.  git instaweb runs fine on the fresh VM.  What am I missing?

**Comment by therealkenc** [comment]
> Ubuntu on metal

Ubuntu running on a machine made of mostly metallic and semi-metallic parts (plus some plastic).

> it doesn't fail with the gamin error

That's probably because it is already installed. Or.... the Ubuntu 16.04.6 ships with a w3m, or lighthttpd, or whatever it is the perl cgi script uses doesn't depend on `gamin`. Or..... other.

Without gamin, `lighttpd` croaks on lack of symbol `FamErrList` from [`libfam0`](https://packages.ubuntu.com/eoan/libfam0).

![image](https://user-images.githubusercontent.com/7049700/73785453-27db6e00-474c-11ea-89f6-5e7790093473.png)

**Comment by rpici** [comment]
To try to reproduce the helpful error message that you got, I tried recreating the issue on two Ubuntu 19.10 VMs, one for the [Desktop edition](https://ubuntu.com/download/desktop/thank-you?version=19.10&architecture=amd64) and the other for the [Server edition](https://ubuntu.com/download/server/thank-you?version=19.10&architecture=amd64).

Both editions have the same /proc/version as yours:
`vm@ubuntu:~/test$ cat /proc/version`
`Linux version 5.3.0-29-generic (buildd@lcy01-amd64-024) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020`

The desktop edition already had `gamin` pre-installed, but the server edition did not.

Neither edition had `libcgi-pm-perl` pre-installed.

In both editions, following the "Steps required to reproduce" from the OP, I can reproduce the 500 Internal Server Error, but in neither edition do I the get the error output that clued you in to the solution;  git instaweb just fails silently, as it did on WSL.

The closest I can get to your output is by running git instaweb twice:
`vm@vm:~/test$ git instaweb`
`vm@vm:~/test$ git instaweb`
`Instance already running. Restarting...`
`vm@vm:~/test$`

...but I never get the "symbol lookup error" that you got.

Interesting...

**Comment by therealkenc** [comment]
> ...but I never get the "symbol lookup error" that you got.

That is because, [quoth](https://github.com/microsoft/WSL/issues/4871#issuecomment-582032548):

> There's a lot of moving parts to git instaweb, and one can't ever really ensure every moving part is the same on all the runs without considerable effort. 

Your moving parts are different.

**Comment by aashutoshrathi** [comment]
Facing this even on WSL2 😕 

@therealkenc's solution 
> sudo apt install libcgi-pm-perl gamin

worked for me.

**Comment by adampl** [comment]
FYI: `gamin` is not required

**Comment by untalsanders** [comment]
I am using Arch Linux and in my case I just need to install the [`perl-cgi`](https://archlinux.org/packages/extra/any/perl-cgi/) and [`lighttpd`](https://archlinux.org/packages/extra/x86_64/lighttpd/) packages to make it work.
