### ISSUE TITLE
mmap fails with EINVAL, Firefox reliably crashes

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/WSL#4873]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18363.592

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
`{ firefox; }`
See [1605665 &mdash; operator `delete []` crashes on `MemoryTextureHost`](https://bugzilla.mozilla.org/show_bug.cgi?id=1605665)!
**TL;DR:** Compositor thread receives a previously mapped block via IPC and tries to re-map it.  Since the block has been allocated in a different thread, `mmap` returns `MAP_FAILED` because `EINVAL`, which triggers a controlled crash in Mozilla memory management unit.

* What's wrong / what should be happening instead:
I guess the call should return the block; that happens when you step through the code under `gdb`.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
See [downstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1605665)!

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
While I'm not 100% convinced `memfd_create()` is the cause, since this was brought up [before](https://github.com/microsoft/WSL/issues/3542#issuecomment-560179373) in /dupe #3542 that can act as the landing zone. Someone highly motivated to find the diverge and suggest an upstream work-around could dive it, in principle. Alternative tag fixed-in-wsl2.

**Comment by yecril71pl** [comment]
> While I'm not 100% convinced memfd_create() is the cause, since this was brought up before in /dupe #3542 that can act as the landing zone. Someone highly motivated to find the diverge and suggest an upstream work-around could dive it, in principle. Alternative tag fixed-in-wsl2.

WSL has no upstream.  An argument against the dependency on `memfd_create` would be that it does not crash when run step by step under `gdb`.  But what do I know? 🤔

**Comment by therealkenc** [comment]
> WSL has no upstream. 

Upstream Firefox, naturally.

>  An argument against the dependency on memfd_create would be that it does not crash when run step by step under gdb

Another strong(ish) argument would be I wasn't able to find a relevant `memfd_create()` in the firefox source, in a quick search when you posted in December, anyway.

> `mmap(0x7fd280a00000, 4194304, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 EINVAL (Invalid argument)`

That would suggest #3939 or variation thereof. Someone highly motivated to find the diverge and suggest an upstream work-around in firefox, in principle. Assuming the nature of the `mmap` diverge wasn't already addressed. On first glance it appears to be. Best I can tell #3939 shipped [in 18890](https://github.com/microsoft/WSL/issues/3939#issuecomment-488429593) > 18363.

Firefox 72.0.2 light up (paints) WSL 1 Win10 build 19951, but appears suffer other (unrelated) [problems](https://www.google.com/search?sxsrf=ACYBGNS6OGfZAApvczl1786HwqUGCEW4FQ%3A1580954647796&ei=F3Q7XsKWMJP4-gT_h7GQCw&q=firefox+%22exiting+due+to+channel+error%22&oq=firefox+%22exiting+due+to+channel+error%22&gs_l=psy-ab.3..0l2j0i22i30l3.11777.12599..13008...0.2..0.69.136.2......0....1..gws-wiz.......0i71j35i39j0i7i30j0i5i30.oLmHtA-tpCg&ved=0ahUKEwiC_r-B67vnAhUTvJ4KHf9DDLIQ4dUDCAs&uact=5) on WSL1. Firefox 68.0.1, the version cited in Bug [1605665](https://bugzilla.mozilla.org/show_bug.cgi?id=1605665) seems alright. Bonnie chance.

![image](https://user-images.githubusercontent.com/7049700/73900019-3c4e6200-4843-11ea-9997-ed2306b0b085.png)

**Comment by yecril71pl** [comment]
>> An argument against the dependency on memfd_create would be that it does not crash when run step by step under gdb
> 
> Another strong(ish) argument would be I wasn't able to find a relevant memfd_create() in the firefox source, in a quick search when you posted in December, anyway.

The case against `memfd` was dismissed by downstream.

>> mmap(0x7fd280a00000, 4194304, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 EINVAL (Invalid argument)
>
> That would suggest #3939 or variation thereof. Someone highly motivated could dive the nature of the diverge and suggest an upstream work-around in firefox, in principle. Assuming the nature of the mmap diverge wasn't already addressed. On first glance it appears to be. Best I can tell #3939 shipped in 18890 > 18363.

No need for diving, that one *resizes* a mapping onto a *file*, so the common part is only in the result: `mmap` reports `EINVAL`.

> Firefox 72.0.2 light up (paints) WSL 1 Win10 build 19951, but appears suffer other (unrelated) problems on WSL1. Firefox 68.0.1, the version cited in Bug 1605665 seems alright. Bonnie chance.

Currently both Chromium and Firefox fail under WSL, which is kind of sad because nobody knows any other browser.  I use qute but the initial shock you get from that interface is epic.

**Comment by therealkenc** [comment]
> No need for diving, [#3939] resizes a mapping onto a file, so the common part is only in the result: mmap reports EINVAL.

The probability that firefox 68 demonstrably works on WSL1 >18890, but exhibits an `mmap EINVAL` on 18363, while, at the same time, the `EINVAL` was addressed by a heretofore undiscovered and unannounced improvement in WSL1 `mmap` behavioral semantics _other than_ #3939 or variation thereof, is admittedly nonzero. It would take a pathological amount of motivation to eliminate the academic epsilon. [...it's 3939]

> Currently both Chromium and Firefox fail under WSL, which is kind of sad because nobody knows any other browser.

They do. It would appear that the population of WSL1 users motivated dive the diverges and find upstream work-arounds is smaller than it [once was](https://github.com/microsoft/WSL/issues/648#issuecomment-258305615). Probably because existence WSL2. Is that sad? Tough to judge.

**Comment by gcp** [comment]
>Another strong(ish) argument would be I wasn't able to find a relevant memfd_create() in the firefox source,

We don't use memfd_create() in Firefox, although we likely will in the future, see https://bugzilla.mozilla.org/show_bug.cgi?id=1440203

This doesn't seem to have to do anything with that though. We mmap(MAP_FIXED, PROT_NONE) a region we previously allocated because all the heap allocations belonging to that region have been freed, as a hint to the kernel the memory is now available again.

Somehow, on WSL, this call fails.

**Comment by therealkenc** [comment]
> Somehow, on WSL1, this call fails.

The `mmap` [does not](https://github.com/microsoft/WSL/issues/4873#issuecomment-582704093) fail with `EINVAL`, as of WSL1 18890 or thereabouts. [To the extent was explored, anyway.]

**Comment by gcp** [comment]
Good, then I assume the crash volume will drop as soon as 18890 ships to users...
