### ISSUE TITLE
Binary versions are showing wrong in neovim :checkhealth for providers

### ISSUE THREAD

**Issue by tteke** [microsoft/WSL#4882]
Version 10.0.19559.1000
Running :checkhealth on neovim causes the issue
Binary version numbers have "^[[H^[[J" characters in front of them. I tried using both packages from repository (for the binaries and neovim) and a version manager (like asdf). It should report the correct version number (e.g. v10.19.0). For nodejs I think the code that queries the version uses the command like this
https://github.com/neovim/neovim/blob/master/runtime/autoload/health/provider.vim#L625

**Comment by therealkenc** [comment]
That line of code isn't going to work if `node` emits is CRLF. Which is how win32 `node` behaves by design.

![image](https://user-images.githubusercontent.com/7049700/74174124-41673480-4be8-11ea-86cf-e79ee408a054.png)

Educated guess you don't have `node` installed in WSL.

**Comment by tteke** [comment]
I tried both nodejs from the repositories and with asdf version manager. Same result. I know node is installed on wsl because I am currently using it.

**Comment by therealkenc** [comment]
Can't repro here (made me look). I assume the output is supposed to look like this.

If your version numbers have `"^[[H^[[J"` characters in front of them, it is because those are the characters `write()` syscall was given. Whatever the reason it is almost certainly going to be a userspace thing. Termcap related possibly.

![image](https://user-images.githubusercontent.com/7049700/74178650-c5bdb580-4bf0-11ea-9616-1c4d1fd2c272.png)

**Comment by tteke** [comment]
Can you try after installing npm neovim package with 'npm install -g neovim' ? Because the main version issue is with node version, python seems ok.

**Comment by therealkenc** [comment]
No effect. It wouldn't. That `ESC H ESC J` is a cursor positioning sequence. Try `export TERM=vt220` for the sport of it. Or `export TERM=linux`, which is roughly the same thing. Going to make a wild guess (maybe incorrect) you are not running an Ubuntu install from the Store, is that about right?

**Comment by tteke** [comment]
Yes, I'm using Ubuntu from the store now it became "^[[3^[[H^[[J". And I realized, anything I echo in neovim command like ":!echo $PATH" has "^[[3^[[H^[[J" in front of it.

**Comment by therealkenc** [comment]
A simpler repro than `nvim(1)` might be:
```
$ printf "\033[H\033[Jhello\n"
```
Which should print hello in the upper left corner of your screen. [For you, probably, it won't.]

What was the result (if anything) of setting `TERM=vt220` before running `nvim(1)` or the above `printf(1)`.

> Yes, I'm using Ubuntu from the store now 

Thanks; that's a useful data point. Now it is down to guessing your diverge versus a clean install. You could try moving your `.bashrc` out of the way (`mv ~/.bashrc ~/bashrc.bak`, start another shell) to see if the culprit is in there. It might not, but it is a good usual suspect. That or the problem is somehow on the terminal emulator (read: [console](https://github.com/microsoft/terminal)) side, although absent externalities the Windows Console will interpret those escape sequences fine.

**Comment by tteke** [comment]
printf worked as normally (hello on the upper corner). After you said to start a clean shell I realized I was using tmux. I suspected it might be the problem so running without tmux the problem was solved. I was using someone else's tmux config(https://github.com/gpakosz/.tmux) on a clean tmux there is also no problem. So somewhere in that guys conf there is a line that breaks it for wsl. That tmux conf is not so important for me so for now I can say the problem is solved. Thanks

**Comment by tteke** [comment]
Trying to figure out what was wrong with the conf. I realized that in my config.fish file (i am using fish as default shell) I have these lines so that the session always start with tmux 
```fish
if status is-interactive  
and not set -q TMUX  
    exec tmux
end
clear  
```
if i comment those lines, even if I use the previous tmux conf everything is fine. Those lines were the culprit.

**Comment by therealkenc** [comment]
>  always start with tmux

Heh; I had guessed you failed to mention `tmux` earlier, but it worked under clean `tmux` for me too, so I assumed that wasn't it. Couldn't account for a tmux config tho.

> So somewhere in that guys conf there is a line that breaks it for wsl. 

It isn't a "for WSL" thing. Neither WSL nor a Real Linux kernel has any idea what those escape sequences mean, or why `tmux` or `fish` (or anything else) writes what it writes down a pty.

It _might_ be the terminal emulator, possibly (maybe,hypothetically,in theory). You could experiment with other emulators. MSFT has a new [Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab). I use [`ttyd`](https://github.com/tsl0922/ttyd) (based on xterm.js) sometimes.

Allowing for possibility "something else".

> so for now I can say the problem is solved. Thanks

Glad you're solved!

**Comment by tteke** [comment]
It is weird that when I start tmux myself it works but with those lines it doesnt. Anyways its not a big deal to write 4 characters everytime I start the emulator. After that next tabs/panes start with tmux anyways. 
I am already using Microsoft Terminal btw. I'll try other emulators as well.
