### ISSUE TITLE
WSL2Bug No response in 19559

### ISSUE THREAD

**Issue by quank123wip** [microsoft/WSL#4887]
**Please fill out the below information:**
* Your Windows build number:  10.0.19559.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead: When I run "wsl" in the powershell,it's just stopped and no output was given.

**Comment by erikbye** [comment]
Build number: 19559.1000

Attempting to start WSL2, Debian, converted from WSL1 with `wsl -d debian` results in:

wsl -d Debian
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.wsl

**Comment by knubey** [comment]
I am receiving the same errors on Ubuntu, Ubuntu 18.04, and docker-desktop.
![image](https://user-images.githubusercontent.com/5951125/74341725-cd569900-4d6d-11ea-9d08-46be50c86c73.png)
