### ISSUE TITLE
Upgraded distribution to WSL 2 and it has stopped opening on command

### ISSUE THREAD

**Issue by haydenrou** [microsoft/WSL#4892]
Hi there,

I recently realised I had WSL 2 installed, but my distro was using WSL 1. To upgrade, I used `wsl --set-version <distro> 2`. After doing this, whenever I run WSL from powershell, it turns on the machine but does not take me to the command line.

Here is what happens:

`
PS C:\Users\hayde> wsl -l -v
`
`NAME      STATE           VERSION`                                                                                                                                                                                      `* ubuntu    Stopped         2`
`PS C:\Users\hayde> wsl`
`PS C:\Users\hayde> wsl -l -v`
`NAME      STATE           VERSION`
`* ubuntu    Running         2
`

What I've tried:
- exporting & importing again, having unregistered and terminated the distro
- rebooting
- upgrading windows

My setup:
- OS Name: Microsoft Windows 10 Home Insider Preview
- Version: 10.0.19564 Build 19564

Please advise how I can debug this?

Thank you,
Hayden

**Comment by kidonng** [comment]
Windows version 19564.1005. WSL 1 works flawlessly, but WSL 2 gives no response. 

![image](https://user-images.githubusercontent.com/44045911/74672177-aa057100-51e7-11ea-9a6f-fe0d88ed1baf.png)

(Using [ArchWSL](https://github.com/yuk7/ArchWSL) which may be unsupported, but I don't think it's the cause since it worked well on last version)

**Comment by haydenrou** [comment]
When I set my ubuntu WSL version back to 1, it still fails now.

**Comment by kidonng** [comment]
@haydenrou https://github.com/microsoft/WSL/issues/4899#issuecomment-588172634 worked for me.

**Comment by haydenrou** [comment]
@kidonng unfortunately this does not fix the above.

**Comment by haydenrou** [comment]
Just as an update on this, if I download Ubuntu-18.04 from the app store, I can run a 'new' distribution from the command line, however my old one that I imported and upgraded per the above still does not work.

For the meantime I'll use my new distribution but it would still be nice to know why my other one wouldn't work, so I'll leave the issue open.

**Comment by dzar-aker** [comment]
I'm having a similar issue and I'm running the "official" distribution from Windows update on build 2004 (Windows Pro). 

For me, I convert to WSL 2 (Ubuntu 18.04) and when I run, it simply does:

The Windows Subsystem for Linux instance has terminated.

That's it. No prompt or other messages. Are there any logs anywhere? I suspect this is due to some tools installed that are causing a conflict. I have a very complex setup (and I did start removing a few things - like Docker - that I thought might be a problem but they are not fixing this). And with the long conversion time ("minutes" should not mean hours... ) I'm done iterating. We need a way to debug these things!

Anyone know if there are useful logs? Please... there has to be (right?).

**Comment by haydenrou** [comment]
This is what I was trying to ask @dzar-aker . With no luck, I started over. All I can suggest at this point is to export and re-import the subsystem, but really that's just pulling ideas out of a hat.

I think what's being done here is great but I'm going to leave it until it's more fleshed out, I can't risk losing everything with a random update I'm _forced_ to do.
