### ISSUE TITLE
map network drive with non-root permissions via \\wsl$\distro\folder

### ISSUE THREAD

**Issue by uzokis** [microsoft/WSL#4910]
**Is your feature request related to a problem? Please describe.**
I would like to create files in windows via \\wsl$\distro\folder as a non-root user.
I'm using a (custom) eclipse to do programming work in windows, but would like to use a lightweight linux as the actual building sandbox. This means when creating files in windows, they will be created as root and makes it inconvenient to use the tooling inside the wsl2 instance (everything works but I have to constantly chown the working directories to a non-root user)
Microsoft Windows version: Version 10.0.19041.84

**Describe the solution you'd like**
Have some kind of way to map the \\wsl$ network drive AND somehow specify the user which will control the permissions inside the wsl instance. (maybe via a config file, path parameter, ...)

**Describe alternatives you've considered**
I found some unofficial info online suggesting setting the default user via wsl would also have influence on this but it doesn't seem to be the case.
I also tried login in as the actual user when mapping the network drive, but that also doesn't seem to do anything.

**Additional context**
-

**Comment by therealkenc** [comment]
> Have some kind of way to map the \wsl$ network drive AND somehow specify the user which will control the permissions inside the wsl instance.

The WSL 9p service on the WSL side takes the identity of the distro's default user. [I think; it might be the user that first invokes the distro instance, say with `wsl.exe -u`. I never investigated the behavior in detail because I don't invoke WSL as root, ever.]

Either way, if those files are being created as user `root`, try setting your default user in `/etc/wslconf` like so:
```
[user]
default=<username>
```

Then do a `wsl.exe --shutdown`, and then launch a shell again. Files created in `\\wsl$\distro\home\username` should be created as `username` (not `root`).

Related #3990 and still-open #3966.

**Comment by uzokis** [comment]
Thanks, that did the trick!
