### ISSUE TITLE
WSL cannot open chromedriver.exe in /mnt/c

### ISSUE THREAD

**Issue by YiRuChenbilibili** [microsoft/WSL#4932]
I just updated my wsl to wsl2. In wsl I can easily use my chromedriver by set (chrome_driver = "/mnt/c/Program Files (x86)/Google/Chrome/Application/chromedriver.exe")then driver = webdriver.Chrome(chrome_driver)
But after I  started to use WSL2.It raises the problems like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/chen/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /mnt/c/Program Files (x86)/Google/Chrome/Application/chromedriver.exe
what should I do?Or it's just not support？

**Comment by therealkenc** [comment]
There is no repro here, but if your scenario was working in WSL1 and not WSL2 that _usually_ is because of loss of `localhost` transparency in WSL2. Since `chromedriver.exe` is presumably listening on the Windows side, this is very probably dupe #4199. It is almost certainly possible to get your scenario working using the real IP address of the service (think: `chromeserver.exe` on another machine). There is not nearly enough to go on here to tell you how to go about that (or even speculate); though a forum familiar with python and selenium might.

**Comment by dfanica** [comment]
@YiRuChenbilibili I want to use `chomedriver.exe` from WSL (I have version 1) but I keep getting `org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.`

Initially I thought that you can't call `chromedriver.exe` (since it's listening on Windows side) from WSL (which is on Ubuntu 18.04 side) but then I saw you post here and I was wondering if this is possible and I'm missing something?

I have Chrome Version 80.0.3987.149 (Official Build) (64-bit), on Windows 10, and I'm using ChromeDriver 80.0.3987.106 and I'm calling it via WSL with `webdriver.chrome.driver = /mnt/c/chromedriver.exe`

Since I can't get this to work I'm looking now to set this up running Maven from Windows rather than WSL. Any help appreciated. Thanks.

**Comment by YiRuChenbilibili** [comment]
I simply try this in WSL(version 1):
from selenium import webdriver

driver = webdriver.Chrome(executable_path="/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/Scripts/chromedriver.exe")

driver.get("http://www.baidu.com")

print(driver.page_source)

driver.quit()

And it can work.

**Comment by mangelozzi** [comment]
> There is no repro here, but if your scenario was working in WSL1 and not WSL2 that _usually_ is because of loss of `localhost` transparency in WSL2. Since `chromedriver.exe` is presumably listening on the Windows side, this is very probably dupe #4199. It is almost certainly possible to get your scenario working using the real IP address of the service (think: `chromeserver.exe` on another machine). There is not nearly enough to go on here to tell you how to go about that (or even speculate); though a forum familiar with python and selenium might.

The only issue with this, is that `chromedriver` only allows one to connect to local host for security reasons.
