### ISSUE TITLE
The operation could not be started because a required feature is not installed

### ISSUE THREAD

**Issue by simeruk** [microsoft/WSL#4951]
* Windows build number: **19569.rs_prerelease.200214-1419** [Version 10.0.19569.1000]
* Issue manifesting itself as below, while trying to start up my only distribution:
```
C:\Users\name>bash
The operation could not be started because a required feature is not installed.

```
* Expected behaviour, that usually worked:
```
C:\Users\name>bash
name@DESKTOP:/mnt/c/Users/user$
```

* Workaround link provided by @pedrodaniel10 for slightly different [issue ](https://github.com/microsoft/WSL/issues/4939) did work and removed the issue in my case as well, which in a nutshell is as follows: 

1. navigate to "Start" button, 
2. type in "**Exploit protection**" and run it as administrator,
3. once in, nawigate to: "**Program settings**" \ "**Add program to customise**", adding the two 
below separatelly, in each case, disabling by unticking: “**Code flow guard (CFG)**":
```
    C:\WINDOWS\System32\vmwp.exe
    C:\WINDOWS\System32\vmcompute.exe
```

Not sure if [detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) are required since solution pointing to issue resolution has been indicated.

**Comment by fennemaj** [comment]
I've been struggling with this issue all day today and this solved it for me.  I was getting this error:

Error: 0x80370114 The operation could not be started because a required feature is not installed

And trying a ton of different things, none of which would allow me to complete the Ubuntu install.  Doing the above is the only thing which fixed this for me.  Thanks for finding this and sharing it!

**Comment by alikrc** [comment]
June-2021 - unticking Code flow guard (CFG) solved my issue, thanks a lot.

**Comment by arsalannaseer** [comment]
> 
> 
> June-2021 - unticking Code flow guard (CFG) solved my issue, thanks a lot.

Worked for me as well. Thanks!

**Comment by manueldeprada** [comment]
december 2021 - this fixed my error under WSL2 Windows 11:
Error 0x80370102 The Virtual machine could not be started because a required feature is not installed

It also fixes the HyperV error: Failed to start the virtual machine 'x' because one of the Hyper-V components is not running.
thank you so much!!

**Comment by 8xu** [comment]
Fixed it by activating HyperV from Windows features tab

**Comment by liudonghua123** [comment]
Why `Hyper-V` is required? According to the docs on https://answers.microsoft.com/en-us/windows/forum/all/the-virtual-machine-could-not-be-started-because-a/9ef9cc67-489e-448d-928f-e8e3b826ae34?auth=1, only `Hypervisor platform` and `Virtual machine platform` is required.

And `Hyper-V` may be conflict with other 3rd party hypervisors such as VMware or VirtualBox.
