### ISSUE TITLE
Cannot run Firefox

### ISSUE THREAD

**Issue by saschanaz** [microsoft/WSL#4964]
* Your Windows build number:  19041

* What you're doing and what's happening: 

I'm using vcxsrv and trying to run Firefox on it, on WSL1 Ubuntu.

```
$ DISPLAY=:0 firefox
Exiting due to channel error.

###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0059,name=PBrowser::Msg_UpdateEffects) Channel error: cannot send/recv

[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
[Parent 13504, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-CTCO4D/firefox-73.0.1+build1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 23
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

* What's wrong / what should be happening instead: It runs Firefox but only with errors. Restart never helps.

![image](https://user-images.githubusercontent.com/3396686/76416764-fb92bd00-639b-11ea-853c-2290d9bb496f.png)

**Comment by saschanaz** [comment]
Switched to WSL 2 and it works now.

**Comment by tshirtman** [comment]
Damn, i’ve been fighting on that since yesterday, and couldn’t find much anything about it, sadly i don’t think i’ll be able to switch to WSL2 on this machine, as i’m not admin on it, came pretty close to having an acceptable setup in WSL with it, but the only browser i could get to work as of yet is w3m, which is a bit limited, and i can run firefox in a docker with x11vnc and a client to have something somehowe integrated in my i3 setup, but that’s not great, having firefox working natively would be great, i have the *exact* same symptoms, a lot of these messages in the logs, (channel error cannot send/recv, and file_descriptor_set_posix.cc), and the same "sorry. We just need to do one smal thing to keep going", that never go away.

Chrome fails with different errors

`Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Permission denied`. 
(SIGTRAP).

Electron apps close with the same message, not sure if the cause is the same as with firefox.

w3m works without issue, and about everything else network is fine.

**Comment by saschanaz** [comment]
I could run Firefox normally on WSL1 in 2019, maybe something changed on Firefox side 🤔

**Comment by tshirtman** [comment]
Any idea of the timeframe you had that working, i guess i’ll check with a version from early 2019 and try to bisect the version if that works.

**Comment by saschanaz** [comment]
>edit: wonderful, firefox 67 works!

That's fairly old, but 👍

**Comment by tshirtman** [comment]
yeah, i’ll try more recent ones, it seems this one is not liked at all by the systems, i just got two reboots :| we’ll see 🤞

**Comment by tshirtman** [comment]
So it’s apparently self updating, whatever version i’m on, and breaking itself (and doing something windows doesn’t like at all) in the process, one  pretty blunt workaround i found is to make the extracted folder read only (`chmod -R ugo-w firefox`) before even running it, and i then go to about:config to stop it from even trying to update, doing that, it seems firefox 69.0 is the last version i can make work (70 and 71 start but have weird issues, like the viewport apparently not updating, while the rest of the UI working almost correctly). The downside of my workaround is that i can’t apparently install addons, as they are stuck in "installing" state forever.

Oh well, at least that’s progress, and hopefully these bits will help someone else if they happen to be in the same situation.

**Comment by mdirshadlearning** [comment]
How can i install firefox old version using WSL1

**Comment by DesktopECHO** [comment]
When I was working on [xWSL](https://github.com/DesktopECHO/xWSL) the only decent browser I could get to work reliably was Mozilla Seamonkey:

```
cat <<EOF | sudo tee /etc/apt/sources.list.d/mozilla.list
deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main
EOF

sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C
sudo apt-get update
sudo apt-get install seamonkey-mozilla-build
```

**Comment by tshirtman** [comment]
i had more issues with it, so i looked for alternatives, and basilik seems to be the closest to firefox, and seems to run flawlessly.

**Comment by Dulatr** [comment]
Just wanted to say that this issue thread saved me so much headache with getting firefox working. I would like to add that apparently they stopped with the ability to turn off multiprocessing after version 68, after moving the autostart tab settings to remote.force and gutting the disabling. So maybe that's why you're having so much difficulty with the newer versions. 

For anyone else stumbling across or interested in this thread here's a [post](https://www.ghacks.net/2019/05/17/going-forward-multi-process-cant-be-turned-off-anymore-in-firefox/) about the change.

Works for me right now (seems stable so far) on: 

* Firefox 67.0

* Subsystem: WSL 1 / Ubuntu 16.04

* OS Build: 18363

**Comment by kousu** [comment]
Firefox also didn't work very well for me on ubuntu1804.exe with vcxsrv. It ran but kept crashing with the screens shown above.

However, Palemoon did work!

I used it to run [Windows 2000](https://bellard.org/jslinux/vm.html?url=win2k.cfg&mem=192&graphic=1&w=1024&h=768) inside of Linux inside of WSL inside of QEMU inside of Linux:

![2021-03-20-190437_1364x766_scrot](https://user-images.githubusercontent.com/987487/111888312-bbecb100-89b1-11eb-9ee8-744329d29bb3.png)

It worked! Even minesweeper :)

**Comment by DesktopECHO** [comment]
An update to my findings from two years ago -- If you're looking for something Chromium-based, QtWebEngine is the way to go.  

Any browser based on it (like Falkon, below) works great in WSL1.  More stable than Seamonkey - not quite as good at playing fullscreen video, but very stable.  Be sure to add the following flag for WSL1:

``export QTWEBENGINE_CHROMIUM_FLAGS="--single-process"``  

Here's a screenshot of Falkon on KDE Neon in WSL1 over xRDP:

![image](https://user-images.githubusercontent.com/33142753/185795992-1118caea-f5f9-4d1e-bf2e-a73586bb236f.png)
