### ISSUE TITLE
[WSL2][Ubuntu18.04] Unable to run the command if searched using "reverse-i-search"

### ISSUE THREAD

**Issue by prayagsingh** [microsoft/WSL#4966]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.113] 

* What you're doing and what's happening: 
 1. I'm trying to run the command using `reverse-i-search (ctrl R)`. Search is working fine but if I'm using `Tab` key while searching to complete the command in `reverse-i-search` then the `cursor` freezes in the beginning of the command and  when I'm trying to execute it by pressing `enter` key then it is not happening. It stuck. 
2. Even `ctrl C` is not working. Only way is to close the terminal.

* What's wrong / what should be happening instead:
 1. If pressed `Tab` key to complete the command in `reverse-i-search` then it shouldn't freeze the `cursor` in the beginning of the command. 

**Steps to Reproduce:**
1. press `ctrl R` in `Ubuntu 18.04` terminal to search the command and press `Tab` key to complete the command.
eg:  In my case, i was searching for `docker-compose -f docker-compose.yaml up -d` command

**ScreenShots**
![Screenshot (124)](https://user-images.githubusercontent.com/8455114/76608280-5ca4c700-653b-11ea-9ab8-c813b02f2d31.png)
![Screenshot (125)](https://user-images.githubusercontent.com/8455114/76608283-5d3d5d80-653b-11ea-9e2e-1badf349be7e.png)
![Screenshot (126)](https://user-images.githubusercontent.com/8455114/76608285-5e6e8a80-653b-11ea-9f1f-0d8779fad08a.png)

**Comment by sirredbeard** [comment]
Can you reproduce this issue in the classic Terminal?

If not, we may need to transfer this issue to the new Terminal project.

**Comment by prayagsingh** [comment]
Hello, I'm not sure what's classic terminal is but if your are talking about the terminal that we got after installing Ubuntu18.04 then yes, it is happening in that terminal too. Please find attached screenshots.
![Screenshot (135)](https://user-images.githubusercontent.com/8455114/77849509-b8cd4380-71e9-11ea-8216-fa50d47cdf09.png) 

![Screenshot (133)](https://user-images.githubusercontent.com/8455114/77849506-b7038000-71e9-11ea-8555-e087ec48145f.png)
![Screenshot (134)](https://user-images.githubusercontent.com/8455114/77849507-b834ad00-71e9-11ea-875b-ee240f09d68d.png)

**Comment by Diastro** [comment]
I'm hitting the same issue. Any update on this?

**Comment by prayagsingh** [comment]
@sirredbeard Could you please transfer it to Windows Terminal project because this bug is still present and its really annoying.

**Comment by onomatopellan** [comment]
I finally reproduced the issue and found the culprit. When it happens you can open another tab and run `htop`. You will see a bash process that uses too much CPU, click on it and press "S" key. Click on "AutoScroll" to see running syscalls in real time.
In my case the bash process was accessing every single file found in PATH and with /mnt/ being that slow in WSL2 that means a hang of lots of seconds. After waiting for a while the process ends and you can finally continue what you were doing.
 
![2020-06-07 (1)](https://user-images.githubusercontent.com/599142/83956713-3902cb80-a861-11ea-866c-bfa7d25739f5.png)

To test if that's the problem, from bash run this:
```
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
and after that try again using reverse-i-search. Now there shouldn't be any hangs.

**Comment by powzer** [comment]
I'm experiencing the same problem in WSL2 running Ubuntu 19.10.

The above PATH workaround resolves the problem.  I've added back "/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code/bin" to PATH and it's still not hanging on reverse-i-search.  Haven't tested adding any more to see where it's starts hanging though.

**Comment by prayagsingh** [comment]
@powzer Using above solution broke couple of commands like `code .` and `explorer.exe .`.

**Comment by onomatopellan** [comment]
The best for now, as @powzer said, is adding paths manually.

First avoid loading the Windows paths. Just create or edit file `/etc/wsl.conf` with this content:
```ini
[interop]
appendWindowsPath=false
```
After that add the path you need to your `.profile`. For example, if you want `code .` then add it like this:

`echo 'export PATH=$PATH:"/mnt/c/Users/onoma/AppData/Local/Programs/Microsoft VS Code/bin"' >> ~
/.profile`

Instead of `explorer.exe .` I recommend `wslview .` which comes in every Ubuntu distro.

**Comment by ajinkya-k** [comment]
I have the same issue. Terminal freezes on using ssh, same happens with classic termnial

**Comment by thtong** [comment]
@onomatopellan solution worked for me. But I had to run `wsl --shutdown` in command prompt for the config to take effect.

**Comment by SquidPony** [comment]
This didn't work for me. Until recently WSL2 only locked up occasionally when using VS Code, especially if running a Go test while VS Code was open. Today WSL2 locks up every five minutes and I can't get any work done :(

I'm guessing that either gopls got way more aggressive suddenly and is messing things up or WSL is playing less nice. Basically leaving this comment here just to say the issue isn't always resolvable with the above suggestion

**Comment by therealkenc** [comment]
This submission (`searching to complete the command in reverse-i-search then the cursor freezes`) could not be reproduced locally. Based on the work-around suggestion (thanks ono), this is effectively /dupe #4197.

I did look at the report back when it was submitted Spring of last year, and the curious (read: missing) piece is that a unadulterated Ubuntu distro install _will not_ cause `/bin/bash` to spam all over `$PATH`, be it the slow Windows paths or otherwise. I mean, why would it. And if it did, there would be much more widespread screeching. There is some externality or missing repro step (likely many moons prior to the `ctrl-r` step in the OP) that is causing `/bin/bash` to aggressively `stat(2)` all over `$PATH`. What that externality is I can't guess. What it might be would be a good [discussion](https://github.com/microsoft/WSL/discussions).
