### ISSUE TITLE
mc in tmux with glitches

### ISSUE THREAD

**Issue by klonuo** [Microsoft/WSL#499]
Very happy to see tmux working :)

This is small issue - running mc in tmux displays random glitches like this:

![clipboard01](https://cloud.githubusercontent.com/assets/361447/15934905/932f3988-2e65-11e6-8132-0593e015efae.png)

If mc is not run in tmux, this does not happen.

**Comment by zadjii-msft** [comment]
Hmm. I was able to get this to happen myself, but now it's gone and I can't seem to repro it at all. 

If you could get me more reliable repro steps, I should be able to get a better look at it. 

In your SS, it looks like it might have to do with the console rendering a double-wide garbage character (questionmark-box) instead of the unicode vertical line, but I'm not sure why that is...

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and has likely been fixed since it was opened. If not, please post a new issue in the [Console GitHub Repo](https://github.com/Microsoft/console)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
