### ISSUE TITLE
Import/Export breaks native Docker (Ubuntu)

### ISSUE THREAD

**Issue by Sellorio** [microsoft/WSL#5012]
**Your Windows build number**

Microsoft Windows [Version 10.0.19041.153]

**Steps taken to reproduce**

1. Created a VM with Windows 10
2. Enabled Windows Insider Program
3. All window updates applied
5. Enabled features as per https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
6. Restart
7. Installed WSL 2 update as per https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel (as of 2020-03-20)
8. Restart (just in case)
9. Installed Ubuntu 18.04 LTS as per https://docs.microsoft.com/en-us/windows/wsl/install-on-server as Administrator
10. Setup Ubuntu with username DockerHost
11. Installed latest Docker CE as per https://docs.docker.com/install/linux/docker-ce/ubuntu
12. Executed command `sudo service docker start` in WSL
13. Executed command `docker start hello-world` in WSL. **this completes successfully**
14. Exported Distro using `wsl --export Ubuntu-18.04 DockerHost.tar`
15. Rolledback VM to step 3 (All windows updates applied)
16. Enabled features again
17. Restarted
18. Installed update again
19. Restarted
20. Imported Distro using `wsl --import DockerHost C:\WSL\DockerHost DockerHost.tar --version 2`
21. Executed command `sudo service docker start` in WSL
22. Executed command `docker start hello-world` in WSL. **fails with error below**

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.
ERRO[0001] error waiting for container: context canceled
```

Expecting hello-world to execute successfully as it did before export-import.

**Comment by captain328** [comment]
I am facing the same issue.

**Comment by vininja** [comment]
same

**Comment by FelixA1996** [comment]
same

**Comment by therealkenc** [comment]
> docker: Error response from daemon: OCI runtime create failed

This one went chirping crickets because the answer is... long. That error is from userspace. There is probably something to this, but the probability that three people followed the 21 step repro (quoth: "same") is, let's call it, unlikely. I'll tag this distro-mgmt, but that is a bit disingenuous. To get any kind of traction, a repro would need to look something like:

(1) wsl.exe --export [... distro A]
(2) wsl.exe --import  [... distro A into B]
(3) "look, path `/path/to/some/file` is different on A versus B, and here is how it is different"

The "Rolledback VM" steps in the OP are a red herring. Ubuntu userspace isn't aware you reinstalled WSL2 nor that it is running in a VM. Getting to hypothetical step (3) above using `docker` as a vehicle is theoretically possible, but largely impractical. Someone highly motivated could in principle track down the root cause of that userspace `Error response from daemon` and find the diverge between 'A' and 'B'. In principle. Theoretically.

In the mean time, the work-around would be reinstall `docker` on 'B'. 

Or better still, `tar` up your docker containers from inside 'A', install a fresh 'B' (rather than `--import` from A), and then untar your containers inside 'B'.

**Comment by jlcummings** [comment]
Restarting Docker (not necessarily the desktop app, but the services) works around whatever the underlying issue that results from the wsl export.
