### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by lopatnov** [microsoft/WSL#5032]
Dear WSL team,

I have an issue with /bin/bash because there are a lot of scripts with /r/n line endings. The bash tool recognizes \r\n line ending as unknown command of \r symbol. This symbol users even can't see in normal bash code editors. This might be a bug, because  DOS uses carriage return and line feed ("\r\n") as a line ending, which Unix uses just line feed ("\n").

Please, add a feature to recognize line endings for bash tool of WSL.

**Comment by therealkenc** [comment]
GNU `bash` is not a "tool of WSL", and this behavior is by-design `bash`. /dupe #2365 et al. It would still be interesting to see if someone motivated could get `set -o igncr` upstreamed ([message](https://github.com/microsoft/WSL/issues/2365#issuecomment-317526788)), or failing that, create a Launchpad PPA.

**Comment by lopatnov** [comment]
Ok, and when bash will support Windows line endings?

**Comment by therealkenc** [comment]
> Ok, and when bash will support Windows line endings?

GNU `bash`? Wrong place to ask; no one here would know the answer to a "when" question regarding an independent software project. 

Guessing (and I do have to guess) short answer is probably (to a first order) "never". Reasoning being: (a) It is [valid](https://github.com/microsoft/WSL/issues/2365#issuecomment-317526788) to have '`\r`' in a `bash` script by design, (b) Cygwin has been around for a quarter century and the [patch](https://github.com/msys2/MSYS2-packages/blob/master/bash/0001-bash-4.4-cygwin.patch#L132) was never upstreamed, (c) It has been two years since #2318 was posted, and no one has wanted it bad enough to ask the `bash` maintainers if they would be amenable to accepting the feature upstream, and, (d) There is a straightforward solution (use *nix line-endings) that transcends WSL becoming a thing.

An alternate "when" answer would be: Moments after anyone motivated creates a [Launchpad PPA](https://launchpad.net/) with the `set -o igncr` patch applied. Even sooner if you compile `bash` with the patch applied yourself. Bonne chance.

**Comment by andrew-aladev** [comment]
> Ok, and when `bash` will support Windows line endings?

Cygwin developers doesn't really care about users, please use `msys2` and `mingw` where possible instead.

**Comment by therealkenc** [comment]
> cygwin will never implement this feature.

The `igncr` extension is a cygwin [patch](https://github.com/cygwinports/bash/blob/master/4.1-cygwin.patch#L138) since the olden tymes (circa 1990s).

**Comment by andrew-aladev** [comment]
> The `igncr` extension is a cygwin [patch](https://github.com/cygwinports/bash/blob/master/4.1-cygwin.patch#L138) since the olden tymes (circa 1990s).

`SHELLOPTS` usually includes bash script business logic, shell opts can be specified locally and won't be inherited by subscript, shell opts is readonly variable inside script. `igncr` like `ignbrk` is just input mode, it shouldn't be a part of `SHELLOPTS`. But nobody cares, `igncr` become a part of shell opts.

`set -o igncr` inside script is just absurd: you are declaring locally, than your script may use cr, but you don't care about any subscript. Any subscript will receive `SHELLOPTS` without `igncr` and will fail. Why? Shell opts was designed for business logic, this is not a place for input mode.

`msys` developers knows everything about this issue and maintains proper `igncr` patch. Please review [igncr patch](https://github.com/msys2/MSYS2-packages/blob/master/bash/0001-bash-4.4-cygwin.patch), specially comments section. This patch is the proper way of implementing input modes like `igncr`. `msys` `igncr` is not a part of shell opts. That's why I am talking about `msys` and `mingw` developers cares about user.

`cygwin` developers uses `SHELLOPTS` as scrapyard, they just added `igncr` inside and don't care about users. User have to use `env SHELLOPTS=igncr` before launching its script.

**Comment by andrew-aladev** [comment]
_I've removed previous comment, because provided wrong patch, sorry._

> The `igncr` extension is a cygwin [patch](https://github.com/cygwinports/bash/blob/master/4.1-cygwin.patch#L138) since the olden tymes (circa 1990s).

This patch is wrong from design perspective. `igncr`, `ignbrk`, etc are just **input modes**. `SHELLOPTS` includes options for shell script **business logic** only, input mode should not be a part of shell opts. Shell opts are readonly for current local script, user can setup local shell options that won't be passed by default to siblings, user can manually pass shell opts for scripts subtree.

For example you want to ignore cr, you are using the following command: `cygwin\bin\bash -o igncr script.sh`. Your local `myscript.sh` is the following:

```bash
#!/bin/bash
./subscript.sh
```

`subscript.sh` is the following:
```bash
#!/bin/bash
./script.sh
```

`script.sh` is the following:
```bash
#!/bin/bash
echo "fit"
```

`myscript.sh` will fail because `subscript.sh` will fail: `-o igncr` is local option for `myscript.sh` only and won't be passed to `subscript.sh` or `script.sh`. `-o igncr` as command line bash parameter or `set -o igncr` is just absurd: you are declaring that your local script may use cr, but not care about sibling scripts. That's why people are **poisoning all** its **scripts** with:

```bash
(set -o igncr) 2>/dev/null && set -o igncr
```

This line is awful, but today it is used inside millions of bash scripts. Bash `>= 3.2` added ability to pass `env SHELLOPTS=igncr` globally before script execution and `igncr` will be passed to any subscript, but ... `igncr` is not default option and **won't be used in cygwin by default**!

![igncr in cygwin not default](https://i.imgur.com/FqqzD1W.jpg)

That's why I am talking about `cygwin` developers don't care about **users**, they are care only about its **standards**. What does it mean standards in `cygwin`? They made a mistake, placed input mode inside shell options and they will carry this mistake with heads held high through the centuries. They will torture users as long as possible, they will never made **default windows input mode actually as default input mode for bash**.

So please use `msys2` and `mingw` where possible, its developers cares about users, they maintain [proper patch for bash](https://github.com/msys2/MSYS2-packages/blob/master/bash/0005-bash-4.3-msys2-fix-lineendings.patch). This patch just removes carriage return and it is simple and stable, your bash script just works as expected in `msys2` on windows.
