### ISSUE TITLE
WSL2 security issues 

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#5034]
Hi

I am wondering if the expolit which is described in page 7 in the document below still exist in the upcoming GA version:

https://img.en25.com/Web/FSecure/%7B87c32f0e-962d-4454-b244-1bb8908968d4%7D_WSL-2-RESEARCH.pdf

**Comment by DHowett-MSFT** [comment]
The “exploit” explained in the document appears to require the user to run it as an administrator (because it uses Enable-OptionalFeature to toggle feature state in the windows feature repository.)

The “exploit” appears to be a scheduled task that runs WSL. That scheduled task could run _anything._ How is WSL germane to the operation of the “exploit”?

If the user is going to grant administrative privileges to a process, there is an infinite number of scheduled tasks that can be added that don’t involve WSL.

The “exploit” amounts to “running a command as Administrator allows it to have privileges to reconfigure the entire system.”

**Comment by gpotter2** [comment]
The "exploit" breaks WSL install (while having administrative powers) to make it run as root by default, then creates a task to exploit that.

It's a laughable paper. I fail to see what their point was.
