### ISSUE TITLE
Composer is soooo slow on WSL 2?

### ISSUE THREAD

**Issue by marbuser** [microsoft/WSL#5079]
So this issue only started recently. Previously my speeds were fine but now I have no clue why this is happening.

I use composer to manage dependencies on my web projects, and it's always been pretty slow, but my recent usage of it on WSL set's a new record. I'm not sure whether something changed in a recent Insider update but here is basically what happened.

Previously: `composer update` or `composer require` would maybe take around 30 to 60 seconds to complete. This is pretty average for composer.

Now: `composer update` or `composer require` takes upwards of 60 minutes, but usually 30. No I'm not joking. I enabled verbose with `-vvv` and I've found that no matter what, it "redownloads" the json manifest for each of my dependencies, and writes it into the cache. The problem is, it does this every time which sorta defeats the point of a cache I guess. Also, each operation of `Download + Write to Cache` takes around 1-2 minutes EACH.

Considering most modern web projects have quite a number of dependencies, it make it pretty much unusable.

I've read plenty of posts/issues saying that File I/O in WSL isn't great, but what I don't understand is this was working fine like a week or two ago, and now it's randomly just started playing up.

In comparison, if I clone exactly the same git project on a native linux server and use composer, it finishes downloading them from scratch and putting all of them in cache in around 30-45 seconds (as said initially this is expected/usual)

So can someone provide anymore update on this? It's kinda annoying that I want to get some work done but instead I have to sit here for upwards of 1 hour before I can even do anything. Oh and the worst part is if I run `composer update` and wait an hour for it to finish, if I then decide to install a new dependency with `composer require`, I literally have to sit here for 1 hour AGAIN to install 1 dependency that might only be 10kb.

It's incredibly frustrating so I hope someone can help me out.

Thanks.

**Comment by simonferquel** [comment]
Where do you put your source files ? On the windows filesystem or within your wsl2 distro?

**Comment by ad-on-is** [comment]
I'm on WSL2, have composer installed (with Docker), my PHP project files reside inside WSL and the speed is amazingly fast. Installing TYPO3 for example took about 40s in total.

**Comment by thekonz** [comment]
Composer 1 takes quite a lot of time indeed, when having the files in /mnt/c, which I need for PHPStorm docker integration to work.

There are two solutions right now:
- move your files from /mnt/c into the linux root filesystem and lose docker integration in your IDE
- use [hirak/prestissimo](https://github.com/hirak/prestissimo) or composer 2 (run `composer self-update --snapshot` or use my [docker image](https://hub.docker.com/r/thekonz/composer2)) to speed up things

Let's hope WSL2 will improve speeds in the future.

**Comment by simonferquel** [comment]
You can probably tell phpstorm to hope your project using the Linux file share at \\wsl$\Ubuntu\home... This way the files are stored locally on the Linux side and your ide access the files using the remote share.

**Comment by thekonz** [comment]
No actually, you can not do that, it will say something like "UNC paths are not supported".

I also tried mapping wsl$\Ubuntu as a drive with its own letter (`net use`) and a windows symlink (`mklink` on cmd or  `new-item -itemtype symboliclink` on powershell). That gives you the ability to open the files in PHPStorm, but it will kill the docker integration, because for some reason, docker for windows only allows paths on C: to be mounted.

I tried fixing that in the docker for windows settings, but the menu of the current version does not contain anything about file shares.

**Comment by DevBodin** [comment]
I've had similar issues. I'm brand new to Linux and WSL (more or less), coming from a Laravel Homestead setup, and I've noticed at least initial composer interactions are quite heavily delayed, to the point I question if anything is happening.

Thing is, I ended up reinstalling Ubuntu a couple times, and I think the worst case I saw might've been running composer from Windows instead of WSL. I'm wondering if that's actually possible now, but something wasn't right any time I ran a composer command.

Now, with my full Apache2 setup *mostly* worked out and much, much faster. The exception seems to be that composer takes a very long time to respond after running `composer update` .  Like 20-30 full seconds of nothing.

As far as the updating, I can't confirm this at the moment, but I feel like the individual package download speeds are possibly faster, but there's a split-second of delay between each slowing the process as a whole down. I'm tempted to call it a wash, but it's hard to say. (If anyone actually cares, let me know and I can do some time tests.)

On the bright side though, once things have already been downloaded and composer is pulling from cached packages, the difference is mind-blowing. I literally laughed at how beautiful it was.

**Comment by nessunluogo** [comment]
Answering my case after 3+ years, just to help anyone landing here.

I had this issue on all my PHP projects under WSL2 (Windows 11 Pro) using Docker containers via DDEV.
After some investigation it was a networking problem.

I tryed using  `--prefer-dist`, `--no-dev` and `--ignore-platform-reqs` options and setting a bigger `process-timeout` value but nothing worked.

I tried shutting down my Ubuntu WSL (via `wsl --shutdown`) but nothing changed.

After some hours **I restarted Windows** and composer was fast as before.

**Comment by xtrcode** [comment]
I was using Symfony CLI, which uses Composer in the background. After enabling verbose output with the `--debug` flag, I saw warnings from Composer requesting new login credentials for GitHub. After entering the new token, everything worked quickly and flawlessly.
