### ISSUE TITLE
rsync fails with non-writable targets on mounted ntfs filesystems

### ISSUE THREAD

**Issue by kristjanvalur** [microsoft/WSL#5087]
* Your Windows build number:   [Version 10.0.18363.752]

* What you're doing and what's happening:
In a NTFS file system:
```
echo foo > a
echo bar > b
chmod -w a b
rsync a b
```
rsync fails with this error:
` rsync a b
rsync: rename "/mnt/f/BuildAgent/work/c5cd3d8bcff982f1/.b.Ikmoer" -> "b": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]`
Note that the chmod command effectively sets the NTFS "read-only" attribute.

* What's wrong / what should be happening instead:
In a regular unix file system, this works.  rsync temporarily overrides the targets attributes to allow overwriting from the source.  Under WSL, somehow that doesn't happen.
the that the chmod above results in the windows file attributes to become read-only.

* I'm using rsync in a build pipeline to perform cleanup by doing smart comparisons of a source and target.  Build pipeline is running natively, but I'm executing a WSL step using rsync because of its awesome power.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/79290609-6f375680-7e81-11ea-8910-3aa185876938.png)

[gist](https://gist.github.com/therealkenc/7cab66eda791501097d81ee191c6956a)

Maybe (probably?) at least in part #5019

**Comment by kristjanvalur** [comment]
Since #5019 mentions a "killer app":  Running TeamCity builds on a windows box to build a game in UnrealEngine4.  To streamline development deployment I am using a checksum copy with rsync to restore original timestamps on files that don't change for each build.  rsync is more powerful than robocopy in this respect.  Pretty sure this used to work, maybe a recent update just broke this.

**Comment by therealkenc** [comment]
> Pretty sure this used to work, maybe a recent update just broke this.

 Thanks for use case follow up it is genuinely helpful.

On best evidence it is looking like a regress at the very least between 17763 ->18363 but that's a very wide spread. I don't have a 17763 handy to confirm personally. When it broke remains a mild mystery, because everything in 18363 has been in Insiders for a full year or more, but the problem was not reported until recently. There are a lot (!) of Insider users. Makes me speculate that something external (like TeamCity) moved, or the flood would have happened last year. That theory could be wrong. Valid issue regardless.

**Comment by kristjanvalur** [comment]
Ah, TeamCity at least is a red herring, my use case is very much a custom thing, it doesn't natively support running WSL commands.  This is how I invoke rsync from a regular .cmd file: 
`%%SystemRoot%%\Sysnative\bash.exe -c " rsync -a --delete --checksum --no-times \"%refclean_src%/\" \"%refclean_work%\" "` 
I suspect that rsync is just not being that widely used in WSL.

**Comment by diablodale** [comment]
I have a guess to the cause of the errant behavior.

I've pushed TBs of data using rsync on WSL1. Yet, I can repo the OP on...
Win10 18363.778
WSL1
Ubuntu 18.04.4 LTS with 4.4.0-18362-Microsoft

However, those same steps don't have error (a and b have same content) on...
Native host...
Ubuntu 18.04.4 LTS with 5.3.0-46-generic

Interestingly, I've never encountered this error in the 2+ years pushing GBs of data nightly using `rsync` from that same WSL1 system. It pushes to that native Ubuntu on a LAN. And to a Linux server on the Internet. Both using the rsync remote over ssh method.

Contrast the same OP steps but use `cp a b` instead. This will fail with a similar `permission denied`. Why? Because b is read-only...and `cp` protects us...it doesn't do invisible extra work like rsync. Rsync does extra work...it will manipulate files/metadata to force its work...so it will manipulate the destination file/folders metadata to match the goal (since goals are both file content and metadata).

It is expected behavior when all write bits are removed in WSL that Windows native file bit is marked read-only. https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/ see caveat 2.

Since this `chmod -w` behavior triggers caveat 2 and leads to the Windows native file bit read-only...and since the Windows native file bits supersede and can't be overridden by WSL...that means that when rsync does its "extra work" that it can't. The linux api calls that rsync makes in WSL can't override the Windows native read-only file bit.

That's my guess.

As a workaround...if your setup allows, can you use rsync remote? Even if the rsync is remote to the same machine? Or don't do a `chmod -w` and instead a subset like `chmod go-w' 🤔

**Comment by AlexeiScherbakov** [comment]
Rsync on Cygwin is correctly works with readonly flag on ntfs drive, why rsync on WLS2 cannot?

**Comment by jaa101** [comment]
A word-around is to use --inplace which avoids the creation of temporary files.  Read the manual to see the downside of this option.
