### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349

### ISSUE THREAD

**Issue by ML6634** [microsoft/WSL#5100]
@craigloewen-msft

I work on Ubuntu Subsystem on Windows 10 Enterprise Evaluation. hello-world programs etc work on the old version of Docker CE 18.03.1, on Ubuntu WSL, but not on the current version of Docker CE.

Then, I followed the article:

https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

and did all steps there.

Unfortunately, for

~$ sudo docker run hello-world

I still get an error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.

although the docker is running.

Any ideas to fix it? Thank you!

**Comment by craigloewen-msft** [comment]
Are you using WSL 2? (Install instructions [here](http://aka.ms/wsl2-install) and instructions on how to check)

What build of Windows are you on?

**Comment by ML6634** [comment]
It is Windows 10 Version 1909 (OS Build 18363.778). It sounds that WSL2 cannot be installed. My laptop is brand new (bought a few months ago). I have installed "Microsoft Visual Studio Enterprise Trial" since Windows which comes with the computer does not support Docker. So, any possible ways for me to still run Docker? Or, installing Ubuntu alongside with Windows 10, instead of WSL, might be a choice? Thank you!

**Comment by ifreedoms** [comment]
Unfortunately,i also face the same probleam:Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.ERRO[0003] error waiting for container: context canceled
after i install docker-ce(19.03.8~3-0~ubuntu-bionic_amd64) on wsl(subsystem ubuntu 18.04 TLS) of windows server 2019 and service docker start , i try to run one image , e.g. hello-world with command "docker run hello-world" , i shows the above error.

**Comment by craigloewen-msft** [comment]
You are on a version of WSL that does not directly support docker.

[WSL 2]() supports docker (since it has 100% system call compatibility). You can find install instructions [here](http://aka.ms/wsl2-install) which will require you to be on Insider builds. It is set to release soon in Windows 10 version 2004, so you could always wait for that as well.

In the meantime, there are ways to run Docker with WSL 1 and Docker Desktop. Here's a [sample article](https://medium.com/@callback.insanity/using-docker-with-windows-subsystem-for-linux-wsl-on-windows-10-d2deacad491f) on how to do that that I found. Thank you 'Callback insanity' for the article! :)

I'll mark this as closed since I believe this is resolved, if you still have questions please reopen it and tag me to let me know!

**Comment by rishi360** [comment]
I have resolved this issue by changing the selinux policy to permissive mode.

**Comment by richardlgit** [comment]
@rishi360 , is that on Windows or Linux ?

**Comment by richardlgit** [comment]
@craigloewen-msft, went thru all the steps from you last comment but still running into the same issue. Updated to latest 2004 version (Build 19041 ) to no vail. Anything you can suggest?

**Comment by alvaromon** [comment]
I am facing the same issue as the error message reported but i am on a CentOS VM
