### ISSUE TITLE
wsl -t is not processing a System.String in powershell

### ISSUE THREAD

**Issue by alanlivio** [microsoft/WSL#5102]
* Your Windows build number:  
Microsoft Windows [Version 10.0.18363.778]

* What you're doing and what's happening:  
wsl -t is not processing a System.String in powershell.
I get running instance by the following command:
```
PS$ ((wsl --list --running -split [System.Environment]::NewLine)[3]).split(' ')[0]
Ubuntu-18.04
```
Then try to terminate it but a only receive the wsl command usage.
```
PS$ wsl -t ((wsl --list --running -split [System.Environment]::NewLine)[3]).split(' ')[0]
<WSL-USAGE>
```

**Comment by alanlivio** [comment]
hi @adrastogi. Any news?

**Comment by adrastogi** [comment]
Hi @alanlivio, it looks like you're trying to get a specific running distro name so that you can terminate it. If I remember correctly, WSL outputs UTF-16, so you could tweak the encoding as described in [this comment](https://github.com/microsoft/WSL/issues/4607#issuecomment-717876058) from #4607 .

**Comment by alanlivio** [comment]
Thanks @adrastogi. The following worked for me:
````
[System.Text.Encoding]::Unicode.GetString([System.Text.Encoding]::UTF8.GetBytes((wsl --list --running))) -split '\s\s+' 
```
