### ISSUE TITLE
Ping not working in wsl2 debian.

### ISSUE THREAD

**Issue by pnunn** [microsoft/WSL#5109]
* Your Windows build number:  10.0.19041.207

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
ping 8.8.8.8

* What's wrong / what should be happening instead:
ping: socket: Operation not permitted

Is it possible that something is blocking icmp packets? 
ssh works fine, so tcp seems to be OK.

Ta
Peter

**Comment by therealkenc** [comment]
Short answer, mortals don't have `CAP_NET_RAW` by default.

![image](https://user-images.githubusercontent.com/7049700/79715763-81523400-8289-11ea-9c55-9676bec9c7d6.png)

Dunno why `SUID` isn't set on Debian. Might be that they are using `security.capabilities` and those aren't getting picked up by WSL's `tar` on install, but that's speculation.

You can make the binary `SUID` like Ubuntu with `chmod u+s`, or newspeak is add the capability with setcap:
```
$ sudo setcap cap_net_raw+p /bin/ping
```

![image](https://user-images.githubusercontent.com/7049700/79716446-8dd78c00-828b-11ea-9e6c-c2598fcfba16.png)

Borders tag linux-behavior, because WSL2 is doing what it's told. But the `tar` (distro install) hypothesis could be tested by putting together a small busybox tarball together with a `security.capabilities` file, do a `wsl.exe --import`, and see what happens. Maybe that could be bent into an actionable under a different cover depending on the outcome.

**Comment by pnunn** [comment]
Thanks @therealkenc  that is awsome.
setcap did the trick and all now seems to be working. I'll try and migrate my ubuntu wsl1 machine now and see what happens there.

Thanks again.
P.

**Comment by therealkenc** [comment]
Great. Alright let's call this linux-behavior. If someone wants to dive whether the `security.capabilities` xattr hypothesis is correct or otherwise that is a different enough ask that would have a different repro.

**Comment by balexiev** [comment]
It's worth noting that Debian doesn't use SETUID by default, not only in WSL. So we have to use the capabilities option.

**Standalone Debian installation**
$ v /bin/ping
-rwxr-xr-x 1 root root 68076 Nov 10  2016 /bin/ping

user root capabilities:
\# getcap /bin/ping
/bin/ping = cap_net_raw+ep

**Debian WSL2**
\# getcap /bin/ping
/bin/ping cap_net_raw=p

$ getcap /bin/ping
$
(we see an empty response)

So what we need to get ping working is to run the following command (assuming the path is /bin/ping):
_setcap 'cap_net_raw+p' /bin/ping_

But if we run it as a normal user, we will get an error:
$ setcap 'cap_net_raw+p' /bin/ping
unable to set CAP_SETFCAP effective capability: Invalid argument

So, we use sudo:
$ sudo setcap 'cap_net_raw+p' /bin/ping
$ getcap /bin/ping
/bin/ping cap_net_raw=p
$
$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=60 time=1.86 ms

Reference: [https://blog.container-solutions.com/linux-capabilities-in-practice](https://blog.container-solutions.com/linux-capabilities-in-practice)

**Comment by NotTheDr01ds** [comment]
> It's worth noting ...

Apologies, but as far as I can tell *all* of what you wrote is covered above, mainly in [therealkenc's comment](https://github.com/microsoft/WSL/issues/5109#issuecomment-616320311) and my confirmation of the capabilities hypothesis on Debian.

**Comment by aentwist** [comment]
For IPv6 see https://github.com/microsoft/WSL/issues/4518

**Comment by odtmusisi19** [comment]
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.

im stuck

**Comment by thekeyboardworrier** [comment]
I'm stuck too.

**Comment by accnetdev** [comment]
Me too, it does not fix the issue. No connectivity here using WSL2 and Debian distro.

**Comment by sascha-wi** [comment]
bump

**Comment by Vinfall** [comment]
If you don't like settings caps yourself, it's also possible to use inetutils-ping from GNU (instead of the default iputils-ping) which seems to work fine on trixie/sid aarch64.

```sh
sudo apt install inetutils-ping
```

**Comment by TurnOffNOD** [comment]
> Short answer, mortals don't have `CAP_NET_RAW` by default.
> 
> ![image](https://user-images.githubusercontent.com/7049700/79715763-81523400-8289-11ea-9c55-9676bec9c7d6.png)
> 
> Dunno why `SUID` isn't set on Debian. Might be that they are using `security.capabilities` and those aren't getting picked up by WSL's `tar` on install, but that's speculation.
> 
> You can make the binary `SUID` like Ubuntu with `chmod u+s`, or newspeak is add the capability with setcap:
> 
> ```
> $ sudo setcap cap_net_raw+p /bin/ping
> ```
> 
> ![image](https://user-images.githubusercontent.com/7049700/79716446-8dd78c00-828b-11ea-9e6c-c2598fcfba16.png)
> 
> Borders tag linux-behavior, because WSL2 is doing what it's told. But the `tar` (distro install) hypothesis could be tested by putting a small busybox tarball together with a `security.capabilities` file, do a `wsl.exe --import`, and see what happens. Maybe that could be bent into an actionable under a different cover depending on the outcome.

This method solves the problem, but it will be reset by apt upgrade and the problem occurs again.

**Comment by Vinfall** [comment]
So use inetutils-ping instead, just like I said in https://github.com/microsoft/WSL/issues/5109#issuecomment-2769055870.

**Comment by jeremyj563** [comment]
For me this resolved it (no idea why):
```sh
$ sudo apt remove -y iputils-ping && sudo apt install -y iputils-ping
```

**Comment by pujfei** [comment]
I get a native Debian 13 installed on a thinkbook, and use 'getcap' to list capabilities of both /bin/ping and /usr/bin/ping, which shows no difference from that of WSL, strange thing is, turns out ping works like charm on the native Debian env, there must be something wrong on WSL Debian.

native Debian 13

<img width="1866" height="316" alt="Image" src="https://github.com/user-attachments/assets/d4af67c4-b223-400f-b6ad-33e88f650a4e" />

WSL Debian 13

<img width="1887" height="439" alt="Image" src="https://github.com/user-attachments/assets/664e21a1-c5aa-44ea-8020-c18fdd9a4837" />

**Comment by Vinfall** [comment]
> which shows no difference from that of WSL

See `5.1.15. Ping no longer runs with elevated privileges` in [Debian release note](https://www.debian.org/releases/trixie/release-notes/issues.html#ping-no-longer-runs-with-elevated-privileges) and [Debian Package Tracker](https://tracker.debian.org/pkg/iputils), it simply means your WSL Debian 13 ships older iputils.

> there must be something wrong on WSL Debian

Set permissive sysctl in .wslconfig, or install GNU `inetutils-ping`.

**Comment by pujfei** [comment]
@Vinfall that's very kind of you, many thanks
