### ISSUE TITLE
WSL2 - cannot create initial account

### ISSUE THREAD

**Issue by pdcxs** [microsoft/WSL#5112]
My windows version is windows 10 professional Insider Preview, Build 19582.rs prerelease 200306-1640

I try to install ubuntu 18.04 via WSL2, but after downloading from the windows store, ubuntu asks for UNIX user name, when I enter a name, It asks for it again and again and doesn't ask for password. Then I close the installing windows, and cannot start bash/ubuntu1804 anymore. I've tried ubuntu, too. Same problem.

**Comment by ngluva** [comment]
I'm here because of the same issue.  It's been going on for years but no one has seen fit to stop wasting peoples time.
The answer though you wouldn't know it from the error message is to use only lowercase names
The --force-badname doesn't work either.
See this thread. 
https://github.com/Microsoft/WSL/issues/3273

**Comment by pdcxs** [comment]
However, my user name is in lowercase.  Moreover, I have tried install ubuntu, same issue. I try [Arch Linux](https://github.com/yuk7/ArchWSL), too. The Arch Linux even cannot run. This is maybe caused the arch linux now only support wsl, but not wsl2. But still, I think it's a problem of WSL2.

**Comment by therealkenc** [comment]
There was no repro here but almost certainly /dupe #3273 or #5245.
