### ISSUE TITLE
IIS cannot access the WSL 2 file system in 20H1

### ISSUE THREAD

**Issue by ubbc** [microsoft/WSL#5116]
* Windows build number:  Microsoft Windows [Version 10.0.19041.207]

* What you're doing and what's happening: 
Attempting to serve WSL 2 filesystem content through a Windows 10 build 2004 IIS virtual directory with UNC path fails.

* What's wrong / what should be happening instead:
e.g. \\\\wsl$\Ubuntu\Websites\TestWeb
where  \\Websites\\TestWeb on WSL 2 host has been granted unrestricted access 777 (read/write/executable access for user/group/all) 
Testing the connection within IIS reports:
   * Pass through authentication succeeds.
   * Authorization fails ( but reports "The application pool identity is valid." )

Exploring the UNC path shows the files but browsing to content reports:

| Detailed Error Information | |
|--|--|
| Module | IIS Web Core|
|Notification | BeginRequest |
|Handler | Not yet determined|
|Error Code| 0x80070043|
|Config Error | Cannot read configuration file|
|Config File | \\?\UNC\wsl$\Ubuntu\Websites\TestWeb\web.config|

This fails using the built in account or supplying credentials for a local account with access to the path.

**Comment by ubbc** [comment]
This issue persists in build 19041.208

**Comment by stevium** [comment]
I also have this issue.

And I think it happens because IIS by default uses the `ApplicationPoolIdentity` built-in account for running the application pool worker process. and since WSL distro is only available per-user and not shared between other accounts, there is no way that the built-in account would work.

So I've tried the  `Connet As` option with my local username and password, and instead got this Authorization error:

`The path does not exist or environment variables in the path could not be expanded to verify whether it exists.`

Since the `Test Settings` takes some time to verify the path, it seems like it does recognize the `\\wsl$\` part as a network location, but it has no access rights... But that's just an assumption, and I have no idea why this is happening.

Did you maybe have any progress on this so far? 

I think It is really an essential thing and makes `WSL` useless for any kind of .NET web development...

**Comment by elwynelwyn** [comment]
I have the same issue on build 19041.329.

I worked through the same steps as @stevium and get the same results after changing the AppPool to use my local admin user.

**Comment by ubbc** [comment]
I think (?) this may potentially be fixed in build 20175. 

According to the release notes at [https://docs.microsoft.com/en-us/windows/wsl/release-notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes) 
> * Change \\wsl$ prefix to \\wsl to support URI parsing. The old \\wsl$ path is still supported.

This may allow the UNC path resolve correctly. I've not installed the preview version yet to try it as it is a bleeding edge build.

**Comment by johans** [comment]
Anyone got this working?

**Comment by paynecodes** [comment]
I'm trying to get this working as well. No dice.

Each of these `applicationhost.config` blocks result in the error below:

applicationhost.config
```xml
<virtualDirectory path="/somepath" physicalPath="\\wsl$\Ubuntu-20.04\home\myuser\myproject\somepath" />
```

applicationhost.config
```xml
<virtualDirectory path="/somepath" physicalPath="\\wsl.localhost\Ubuntu-20.04\home\myuser\myproject\somepath" />
```

### Error
> **HTTP Error 500.19 - Internal Server Error**
> The requested page cannot be accessed because the related configuration data for the page is invalid.

**Comment by tschamp31** [comment]
This is a broad work-around and doesn't work for all scenarios. This may be obvious to some but in-case anyone was racking their brains against this you can always do:
`<UseGlobalApplicationHostFile>true</UseGlobalApplicationHostFile>`

**Comment by johans** [comment]
`<UseGlobalApplicationHostFile>true</UseGlobalApplicationHostFile>` or mapping to a network drive doesn't seem to work
