### ISSUE TITLE
The tail -f command doesn't show the file's contents realtime

### ISSUE THREAD

**Issue by ywsswy** [microsoft/WSL#5168]
* Windows build number: 
C:\Users\23889>ver

Microsoft Windows [版本 10.0.18362.778]

C:\Users\23889>wsl --list
Ubuntu-20.04 (default)

* What you're doing and what's happening:
![image](https://user-images.githubusercontent.com/25153243/80911133-026bf980-8d67-11ea-86df-77bae646b8ae.png)

There is python script which print every second.
```
#!/usr/bin/env python3

import time
while True:
    print('hello, {}'.format(time.time()), flush=True)
    time.sleep(1)
```
i run it and redirect the output to file log.log, then use tail -f log.log to see what's happening.
```
python3 -u output.py >>log.log
tail -f log.log
```

* What's wrong / what should be happening instead:
The tail -f command doesn't show the file's contents realtime.

**Comment by onomatopellan** [comment]
First of all if you want to use Ubuntu 20.04 in WSL1 you need to do this workaraound.
https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931

After that call your script from a /home folder and not a /mnt/* one.

**Comment by ywsswy** [comment]
SUCC!

tail -f valid except /mnt/* folder

**Comment by therealkenc** [comment]
I was able to repro this on 19628 WSL1 on /mnt/c. It's a solid repro (thanks). In the screencap below `tail -f` does not update as the shell redirect writes (ie, a motion gif would be no better).

![image](https://user-images.githubusercontent.com/7049700/82298592-351e1080-9969-11ea-9465-04c56695bd43.png)

My mount line, because it can matter:

![image](https://user-images.githubusercontent.com/7049700/82298865-9219c680-9969-11ea-98d5-ffd350bf97ea.png)

Now the damndest thing is a similar `bash` loop does cause `tail -f` to work as expected.
```
while true; do echo $(date) >> log.log; sleep 1; done
```

Which is all very odd, because the file notifications ought work alright with drvfs. Would take a pretty deep dive to glean what is going on there. What is writing to `stdout` shouldn't make a whit of difference.
