### ISSUE TITLE
SDE64 cmd fails

### ISSUE THREAD

**Issue by UnPocoCocoLoco** [microsoft/WSL#5212]
* Your Windows build number:  [Version 10.0.17763.1158]

* Linux Ubuntu 18.04

* What you're doing and what's happening:  sde64 -skx -ptr-check -null-check -align-checker assert -align-checker-stderr

* What's wrong: E: Fork for injector launcher failed: Bad address

* Strace of the failing command: clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=NULL) = -1 EFAULT (Bad address)

**Comment by therealkenc** [comment]
> 17763

Try WSL2 on Win10 2004 aka 20H1 aka 19041. I quit at:

![image](https://user-images.githubusercontent.com/7049700/82273891-89a69900-9933-11ea-8319-83bde75fedea.png)

**Comment by cepera** [comment]
Actually the issue seems to still exist.
From intel side it probably won't be fixed: [same bug at community.intel.com](https://community.intel.com/t5/Intel-ISA-Extensions/SDE-on-Windows-Subsystem-for-Linux-WSL-fails/td-p/1184656?profile.language=ru)

The above command line is just not full. Some app to run just supposed to be added like this:

works (on real linux):
```
$ cat hi.c
#include <stdio.h>

int main(void)
{
    if (__builtin_cpu_supports ("avx512vl"))
        printf("yay!\n");
    else
        printf("ops!\n");
    return 0;
}
# no sde
$ g++ hi.c && ./a.out
ops!
# sde without avx512
$ g++ hi.c && sde64 -hsw -- ./a.out
ops!
# sde with avx512
$ g++ hi.c && sde64 -skx -- ./a.out
yay!
```
wsl2 (same piece of code):

```
$ g++ hello.c && sde64 -skx -- ./a.out
E: Fork for injector launcher failed: Bad address
```
