### ISSUE TITLE
WSL2 extremely slow opening file with VIM

### ISSUE THREAD

**Issue by mainegra** [microsoft/WSL#5223]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
  `Microsoft Windows [Version 10.0.19628.1]`

* What you're doing and what's happening:  
  Opening **_any_** text file with `vim` on `wsl2` takes extremely long, for instance `.bashrc`:
  `vim .bashrc`
   This is observed with any text file, not just `.bashrc`!
* What's wrong / what should be happening instead:
  Opening the file takes over 30 s on `wsl2` at any time. While with `wsl` it takes 4 s the first time 
  after starting `wsl` and after that it is instantaneous. I have timed it with a stopwatch and also 
  using `time`. **This makes it impossible to do any work!!!**

* Further information:
  - I have also noted such a slow performance running `rsync`. But I could post another issue with 
    the specifics!
  - `wsl` is running Ubuntu 16.04.5 LTS
  - `wsl2` is running Ubuntu 18.04.4 LTS

**Comment by onomatopellan** [comment]
30 seconds is too much. I have a seen a similar problem recently and surprisingly the user solved it with a simple `sudo apt remove xsel`. Using htop was key to discover what was locking the process:

https://www.reddit.com/r/bashonubuntuonwindows/comments/fuip7x/vimneovim_hangs_10_seconds_when_opening_netrw_or/fnjzb7h/

**Comment by mainegra** [comment]
@onomatopellan thanks for commenting on this issue! 
I do not have `xsel` installed:
`Package 'xsel' is not installed, so not removed`
And the delay also happens by simply invoking vim without a file!

**Comment by onomatopellan** [comment]
Ok let's see which plugin is taking that time. Do this:
```
wget https://raw.githubusercontent.com/hyiltiz/vim-plugins-profile/master/vim-plugins-profile.sh
chmod 777 vim-plugins-profile.sh
./vim-plugins-profile.sh
```
and post here the content of vim.log

**Comment by clementnuss** [comment]
Hello! I know the issue is closed but I have the exact same issue, and here I provide the vim.log file generated by vim-plugins-profile.
[vim.log](https://github.com/microsoft/WSL/files/4856906/vim.log)

There seems to be an issue with the Clipboard loading. This gave me the idea of `unset`ting the `DISPLAY` env variable, which solves the issue!
(I had it set to `export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0` for X11 forwarding).

I guess the problem here is that `vim` tries to access the clipboard, which appears to be reaching out to the X server running (or not) on Windows because of the `DISPLAY` environment variable.

If the variable is set and an X11 server is running on Windows and reachable, then `vim` starts correctly.
If the variable is set and the X11 server is not reachable, then it times out after 30sec and the startup is therefore slow.
If the variable is not set, `vim` starts correctly.

Maybe this will help someone else !

**Comment by mainegra** [comment]
I can confirm the behavior reported by @clementnuss ! I had set the DISPLAY variable for use with XMing or VcXsrv to be able to launch X Windows GUIs. If one of these servers is running then there is no delay. Thanks @clementnuss for sharing your findings!

**Comment by TheGrandmother** [comment]
Unsetting `DISPLAY` worked for me

**Comment by felixhorger** [comment]
Thanks @clementnuss!

I found a related issue, where selecting text in vim is very slow (no syntax highlighting or plugins, plain vim and standard textfile).
If I unset DISPLAY, the speed is decent as expected, however then the system clipboards are not accessible anymore.
If you want to be able to use the registers `"*` and `"+`, which apparently require connection to the x-server which provides the system clipboard, you have to remove `autoselect` from the  `:set clipboard`  option. This does the trick for me without unsetting DISPLAY, hope that helps!

**Comment by forrep** [comment]
Disabling connection to x-server `set clipboard+=exclude:.*` worked for me.
`vim -X` arguments also solves this problem.

**Comment by sg552** [comment]
my case is that: running `vim` is quite fast, but running `sudo vim` is quite slow, and it gives error message: 'unknow host xx...'.

so the solution is: don't change your hostname.

**Comment by LaplacianSpell** [comment]
@clementnuss Thank you very much! I've got the same issue when I'm trying to open `vimtutor` on my WSL2. It takes me about 2mins to open it !!!! You solution inspire me to check my X11 server. And I've found that it just didnt run on my Windows.

so I open my X11 server and it run fast immediately! Thanks!
