### ISSUE TITLE
Access to multiple network cards in WSL2

### ISSUE THREAD

**Issue by pav-rez** [microsoft/WSL#5246]
We have a PC with two network cards, one used for ordinary internet access, second to communicate with external hardware. In WSL2, we can see only one virtual card. Is there any way to access the 2nd network card to communicate with the external HW in WSL?

Thanks for your help.

**Comment by pav-rez** [comment]
Seeing the issue was closed with "need-repro" flag, is there any way we can help in reproducing the behavior for you?

**Comment by therealkenc** [comment]
A specific set of commandline steps of what you are trying to do and what is happening, in a new issue submission, in principle. In your case that will probably include as many details as possible about how your second network adapter was set up on the windows side. 

To the extent this was a question you will probably get better eyeballs in a more general Linux forum. Routing packets to two destination addresses is not related to there being one virtual adapter inside the VM. [Notwithstanding layer 2 things which probably don't apply here.] To the extent it is a bug or feature gap (it might well be), better than evens you are looking at a dupe. Bonne chance.

**Comment by peterkodys** [comment]
Hi experts, this problem was observe on work with readout of NEXYS video digilent card, details are on page: [Linux_ITKDAQ](http://ipnp.cz/kodys/works/daq_programs/Linux_ITKDAQ/index.html)
details related to WSL1 and WSL2 are on subpage:
[LinuxWSLInstallation](http://ipnp.cz/kodys/works/daq_programs/Linux_ITKDAQ/LinuxWSLInstallation.html).
Summary: in windows we see both Ethernet cards (ipconfig /all), on linux under WSL2 using ifconfig is only one net card connected to internet, second one unconnected or connected to digilent (non internet device) card (board) is invisible there, so we cannot continue on mapping and installing of it.
If you see description about how to work on VMB on other [VB subpages](http://ipnp.cz/kodys/works/daq_programs/Linux_ITKDAQ/LinuxOracleVirtualBox.html), there is mechanism hot to map other Ethernet card to VM, similar is missing on WSL2. Is this description enough for more details of problem?
Peter

**Comment by tbarbette** [comment]
Please reopen this issue :)

This is important to enable multipath technologies such as MPTCP or QUIC :)

Reproducibility steps:
1) Have a computer with 2 connections
2) If you're using WiFi and Ethernet, allow to keep both connections following this procedure 
```
1. Open Registry Editor.

2. Go to HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\WcmSvc\Local.

3. Create/change the fMinimizeConnections registry DWORD to 0.

4. Close Registry Editor and reboot.
```

3) ifconfig -a shows only eth0
