### ISSUE TITLE
npm and node don't work in wsl if  launched in a single command

### ISSUE THREAD

**Issue by robross0606** [microsoft/WSL#5251]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18363.836]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

From Windows cmd prompt, type one of the following:

- `wsl.exe npm --version`
- `wsl.exe node --version`
- `wsl.exe --exec npm --version`
- `wsl.exe --exec node --version`
- `wsl.exe -- npm --version`
- `wsl.exe -- node --version`

* What's wrong / what should be happening instead:

All will result in an error like this:
```
: not foundram Files/nodejs/npm: 3:
: not foundram Files/nodejs/npm: 5:
/mnt/c/Program Files/nodejs/npm: 6: Syntax error: word unexpected (expecting "in")
```
This appears to be trying to launch the Windows native version of the tools instead of launching inside the context of WSL.

[detailed_logs.zip](https://github.com/microsoft/WSL/files/4669923/detailed_logs.zip)

**Comment by rescenic** [comment]
Remove NodeJS from Windows system environment first. From what I experienced, Ubuntu WSL read windows system path too (If I read the error in WSL 2 - Failed to translate system path).

**Comment by robross0606** [comment]
That's not a viable solution for me. I need node in both environments.

**Comment by therealkenc** [comment]
/dupe #3882, #1512 ([message](https://github.com/microsoft/WSL/issues/1512#issuecomment-373300810)) variation #2365 ([message](https://github.com/Microsoft/WSL/issues/2365#issuecomment-317526788)), others. You don't have `npm` installed in your distro, it is installed but lives in a `$PATH` component added by your `.bashrc` (which is not evoked when you run `wsl.exe npm`).

**Comment by robross0606** [comment]
> /dupe #3882, #1512 ([message](https://github.com/microsoft/WSL/issues/1512#issuecomment-373300810)) variation #2365 ([message](https://github.com/Microsoft/WSL/issues/2365#issuecomment-317526788)), others. You don't have `npm` installed in your distro, it is installed but lives in a `$PATH` component added by your `.bashrc` (which is not evoked when you run `wsl.exe npm`).

Asking is not the same as telling.  I _DO_ have npm installed in my Ubuntu distro.  Installed using apt.  Feel free to ask questions, but telling me what I have is just plain arrogant .

**Comment by ralemangzz** [comment]
Hi

Can you resolve the problem? I have the same issues, Can you help me?

**Comment by therealkenc** [comment]
It appears what is going on here (and [elsewhere](https://github.com/microsoft/WSL/issues/5801)) is that folks are following the NodeJS on WSL guidance in [the docs](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2), which advises using [`nvm`](https://github.com/nvm-sh/nvm). If you go that route (contrast `sudo apt install nodejs npm`), then the `$PATH` component for `node` and `npm` is set up via your `.bashrc`. That means in order to run WSL node _from the Windows console_ with `wsl.exe` per the [OP](https://github.com/microsoft/WSL/issues/5251#issue-623426742), you'll need an interactive shell.
```
$ wsl.exe -d <distroname> /bin/bash -ic "node <node things>"
```

**Comment by dharm1k987** [comment]
If you **don't** want to install `nodejs` on `WSL`, and instead want to run the Windows counterpart, then these steps worked for me:

First of all note that since the Windows 10 Creators Update (build 1703, **April 2017**), we can natively run `.exe` files through `WSL`.

You can try this by typing `ipconfig.exe`, or `cmd.exe`, and see both of them execute fine (given that you didn't remove the Windows path that is automatically prepended) .

If you have `nodejs` installed on Windows, you can even run `node.exe`, and it should work fine.

The problem is that all of these are `.exe` files. `npm` is an exception, as are all global node modules. If you go to `/mnt/c/Program Files/nodejs`, you will notice that `npm` is written as `npm.cmd`. You **cannot** run `.cmd` files from `WSL` as per my knowledge.

The way I go around this is by running:

`cmd.exe /c npm.cmd` in the current location. You should see output then. So one entry I added in my `~/.bashrc` was:

`alias npm='cmd.exe /c npm'` (you don't need to put the full path of `npm` since `WSL` knows it from path)

You will notice that with your `global` node modules, you will not be able to call them from `WSL` either. Again, this is because they are `.cmd` instead of `.exe`.

If you go to `/mnt/c/Users/<USERNAME>/AppData/Roaming/npm` and do an `ls`, you can see that none of them are `.exe`. We must create alias for these again if you want to use them through `WSL`. You can actually do this easily programmatically in your `~/.bashrc` file:

```
alias npm='cmd.exe /c npm'

for file in `ls /mnt/c/Users/<USERNAME>/AppData/Roaming/npm/[a-z]*.cmd`; do
        cmdFile=$(basename -- "$file")
        filename="${cmdFile%.*}"
        alias "$filename"="cmd.exe /c ${cmdFile}"
done
```

After restarting your terminal, you should be able to run `npm` and global commands like `ng` easily.
