### ISSUE TITLE
nslookup `raw.githubusercontent.com` return 0.0.0.0

### ISSUE THREAD

**Issue by nodew** [microsoft/WSL#5255]
I could't fetch content from `raw.githubusercontent.com`, after my investigation, the nslookup returned `0.0.0.0`, which is weird.
```shell
$ nslookup raw.githubusercontent.com
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
Name:   raw.githubusercontent.com
Address: 0.0.0.0
Name:   raw.githubusercontent.com
Address: ::
```
meanwhile, nslookup `github.map.fastly.net` works fine.
```
$ nslookup github.map.fastly.net
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
Name:   github.map.fastly.net
Address: 151.101.76.133
```

**Comment by karuboniru** [comment]
If you are in mainland China(seems to be true from the Chinese characters in your bio), that is totally normal, blame [GFW](https://en.wikipedia.org/wiki/Great_Firewall) instead.

And doing `nslookup raw.githubusercontent.com` in the windows side should return the same ip. This also suggests that the problem is from the network/DNS itself but not WSL.

Use a proxy to solve this.

For sure you can make `raw.githubusercontent.com` accessible by a `hosts` file or a clean DNS, but that will be incredibly slow.

**Comment by nodew** [comment]
`nslookup` in windows side work well for me, since I'm already connected to an vpn.

**Comment by karuboniru** [comment]
> `nslookup` in windows side work well for me, since I'm already connected to an vpn.

Ok, your problem is that WSL will not access the network through VPN which is set for windows, and it not easy to make a WSL program to use Windows's VPN (I mean IPSec or P2TP..)

Maybe what you need is proxy software like `shadowsocks` or `V2ray` and make them listen on certain local port. Then you can tell Linux programs to use the proxy.

**Comment by nodew** [comment]
Ok, it looks like a DNS cache issue. After reset the instance, it works now.
