### ISSUE TITLE
WSL 2 is not running on windows 10 home (build 2004)

### ISSUE THREAD

**Issue by jehyunlee** [microsoft/WSL#5297]
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.264]
* What you're doing and what's happening:  WSL 2 conversion error

I've been following official instructions on [https://docs.microsoft.com/en-us/windows/wsl/install-win10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

After running "wsl --set-default-version 2", new prompt comes out. 
However, the linux installation raises an error
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800705b4
Error: 0x800705b4 ?? ??? ??? ??? ???????.

Press any key to continue...
```

This error is not raised when Linux is installed on <b>WSL 1</b>, but again, it raises another error when I tried to convert i to <b>WSL 2</b> with the following command 
```
wsl --set-version Ubuntu-18.04 2
```

Error message is : in short translation, "the task has returned due to time out"
```
변환이 진행 중입니다. 몇 분 정도 걸릴 수 있습니다...
WSL 2와의 주요 차이점에 대한 자세한 내용은 https://aka.ms/wsl2를 참조하세요
만료 기간이 지나서 작업이 반환되었습니다.
```

I suppose that 'Hyper-V' is not working on windows 10 home, still.

**Comment by chewi** [comment]
Certainly not because it's Windows 10 Home. I literally just tried WSL1 and WSL2 on there myself and they both worked.

**Comment by Theodore-Robinson** [comment]
It works perfectly fine for me 🤔
I updated my windows 10 home just some hours ago

**Comment by onomatopellan** [comment]
Are you using any AV solution different from Windows Security?

**Comment by jehyunlee** [comment]
Including a case of my friend, I have to admit that windows home does not matter at all. Anyway it is true that did not work on my case. Maybe another programs such as Oracle VirtualBox I have been used for docker (or some other) program might have caused the error. Thank you for case reports. ;)

**Comment by Vishnu05** [comment]
> Lots of Windows Home users are already enjoying WSL2 without problem. Are you using any AV solution different from Windows Security?

how to work on windows 10 home, I'm facing issues unable to enable the virtualization, need some solution

**Comment by onomatopellan** [comment]
@Vishnu05 open cmd.exe and post the output of `ver`

**Comment by nithinbandaru1** [comment]
It looks like the latest versions of Windows 10 Home support Hyper-V.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq

I feel that only a few tools or features come with the latest version of Windows 10 Home because I am not able to find management tools for Hyper-V.

I think they have allowed Hyper-V in Windows 10 Home version to grab a lot of developers because all are looking to develop cross platform-apps, mainly containers support. Docker is a big thing now, probably one of the reasons. We can also run Linux distributions as apps on Windows 10 which will bring all platform users to Windows.

I see ML, Node, Python, Java, IoT developers probably choose windows now because they are getting a full-blown Linux system in windows.

This is an amazing move by Microsoft. 

Probably I am wrong in a few points, open to get corrected.

**Comment by cam-rod** [comment]
Windows 10 Home still doesn't include Hyper-V, at least in its full form. Instead, WSL 2 uses a subset of the Hyper-V commands to start up and run (which are the ones available in Windows features under _Virtual Machine Platform_).
