### ISSUE TITLE
WslRegisterDistribution failed with error: 0x800706d9

### ISSUE THREAD

**Issue by evilzhou** [microsoft/WSL#5331]
after updated to wsl2:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 ??????????????????

Press any key to continue...

**Comment by 1379** [comment]
I encountered the same problem
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 ??????????????????

Press any key to continue...
```

Windows version: windows10 2004  19041.264
I have enabled the "Windows Subsystem for Linux" optional feature.
I hava enabled the 'Virtual Machine Platform' optional component
I have installed the wsl kernel
I have set WSL 2 as my default version
I tried Ubuntu20.04 and debain, and then both encountered the same problem
I tried restarting and reinstalling, but the problem is still not solved

**Comment by rescenic** [comment]
cmd as admin:
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns

Windows Search > Network Reset

CCleaner > Remove all temporary data

Restart Windows

**Comment by evilzhou** [comment]
new clue for 0x800706d9: 
#5329 
i'll try this tomorrow：
https://github.com/microsoft/WSL/issues/5329#issuecomment-641779771

**Comment by rescenic** [comment]
Yeah, it's around network issues. Firewall blocking port and corrupted network adapter. Just like Docker.

**Comment by evilzhou** [comment]
> new clue for 0x800706d9:
> [#5329 (comment)](https://github.com/microsoft/WSL/issues/5329#issuecomment-639135623)
> i'll try this tomorrow：
> [#5329 (comment)](https://github.com/microsoft/WSL/issues/5329#issuecomment-641779771)

unsolved

**Comment by wwboyer** [comment]
I'm having the same issue and I'm just about at my wit's end trying to figure out how to solve it. It doesn't help that the actual message associated with the error code seems to be completely useless. (Googling "There are no more endpoints available from the endpoint mapper." just gives a bunch of results regarding printers and I don't have a printer connected to my network at all, never mind that I'm not trying to use one)

I've tried:
- @rescenic 's suggestions (ran all of the commands and reset my network)
- Completely turning off Windows Defender Firewall
- Allowing all traffic from port 52
- Multiple reboots

The only thing I haven't tried yet is completely reinstalling Windows, which I am not willing to do for a myriad reasons. WSL 1 continues to work without issue, but I am unable to upgrade my current distros to WSL 2, nor can I create any new WSL 2 distros. I do not have Docker Desktop for Windows installed on my system. This feature was the sole reason I updated to 2004 and I'm very disappointed that it isn't working for what seems to be an incredibly cryptic reason that I just can't fix on my own. I've attached some ETL files that I made according to [these instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs), but given how much they compressed when zipped I don't know if they actually have anything useful in them.
[WSL_LOGS.zip](https://github.com/microsoft/WSL/files/4775633/WSL_LOGS.zip)

**Comment by evilzhou** [comment]
solved.
just start service ICS（Internet Connection Sharing (ICS）

**Comment by therobyouknow** [comment]
> just start service ICS（Internet Connection Sharing）

What are the steps to do this? Please advise on command line commands and anything else.

Thank you.

**Comment by Landokane** [comment]
ICS didnt work for me

**Comment by shutupandshave** [comment]
Or me

**Comment by OneTuskedMario** [comment]
I can't seem to start ICS, error message: "Access is denied"

**Comment by SkippityPaps** [comment]
> solved. just start service ICS（Internet Connection Sharing）

Not solved. This does absolutely nothing.

**Comment by rmorraye** [comment]
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 The endpoint mapper has no more endpoints available.

All the solutions tested did not work. And other internet solutions didn't work either.
I couldn't install any Ubuntu, from v18.04 to v22.04.
I tried install with "wsl --install Ubuntu --web-download", and got same error.

I'll try back to W10.

> configs: 
- Windows: 11 v23H2 (S.O. compilation 22631.2792)
- WSL: 2.0.9.0
- kernel: 5.15.133.1-1
- WSLg: 1.0.59
- MSRDC: 1.2.4677
- Direct3D: 1.611.1-81528511
- DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
- Windows: 10.0.22631.2792

**Comment by imby7** [comment]
can u help me with the same thing happen to me

**Comment by rmorraye** [comment]
> WslRegisterDistribution failed with error: 0x800706d9 Error: 0x800706d9 The endpoint mapper has no more endpoints available.
> 
> All the solutions tested did not work. And other internet solutions didn't work either. I couldn't install any Ubuntu, from v18.04 to v22.04. I tried install with "wsl --install Ubuntu --web-download", and got same error.
> 
> I'll try back to W10.
> 
> > configs:
> 
> * Windows: 11 v23H2 (S.O. compilation 22631.2792)
> * WSL: 2.0.9.0
> * kernel: 5.15.133.1-1
> * WSLg: 1.0.59
> * MSRDC: 1.2.4677
> * Direct3D: 1.611.1-81528511
> * DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> * Windows: 10.0.22631.2792

I installed W11 from scratch on my machine, and wsl worked normally after that.  The old installation was actually a clone of an old HD to this new one.

**Comment by qiziqiang** [comment]
I have also encountered and resolved this issue when I install Docker Desktop. In addition to the Hyper-V and WSL that everyone is talking about, you also need to check the following issues:
- Start Shared Access and Storage Service
- Ensure that your WSL/Ubuntu/Debian/etc. is installed on the system drive (usually C:, check it in Settings ->System ->Storage ->Change the save location for new content -> New Apps)

**Comment by Faribasaa** [comment]
> cmd as admin:
> 
> ```
> netsh winsock reset
> netsh int ip reset all
> netsh winhttp reset proxy
> ipconfig /flushdns
> ```
> 
> Windows Search > Network Reset
> 
> CCleaner > Remove all temporary data
> 
> Restart Windows

solved!

**Comment by Hbowe** [comment]
Im here to share what worked for me, read this more as a general retelling of events rather than a guide, because this is one of the first places folks land while googling but I do want to preface that this should be the last thing you try short of a hard OS reinstall as its very messy, imprecise, and reckless, you WILL break some systems files along the way so be prepared for it.

First, if you havnt already, do all the normal procedures people recommend for uninstalling any and all WSL programs including Distros. [BCU](https://github.com/Klocman/Bulk-Crap-Uninstaller) has been a favorite of mine for cleaning up programming messes left in my wake during experimentation binges. I wish I had done this first before the next steps, but it may also be wise to disable WSL and Platform Virtualization features in the Windows Feature menu.

More than likely if youve read this far youve already done different versions of the above and its still not working after reinstalls and reenables, so now we move on to the scorched earth method. Purge any and all mentions of WSL, WindowsSubsystemForLinux, any mentions of Linux that appear related to WSL, and any leftover data related to Distros youve installed from your filesystem. Yes, including from inside of WinSxS, which is dangerous and why you need to be sure you are only deleting WSL components. I personally found that I had WSL data dating as far back as 18 months ago tied up in WinSxS/Temp/InFlight 

Decent odds that you may run into permission errors from either SYSTEM or TrustedInstaller while deleting WSL folders, so I did the following: enabled the built-in Administrators account and logged in -> navigated to WinSxS in the file explorer -> right clicked into folder Properties -> Security -> Advanced -> Change Owner up at the top -> input Administrators into the object name field -> Apply -> OK -> close out of the windows related to properties -> re-open properties of WinSxS -> Edit Permissions -> grant Administrators full control -> should be able to delete folders/files in WinSxS. If still denied, might try enabling Inheritance temporarily if your Admin group settings are iffy. The above steps should work for other file directories if WSL is cached in random places. Swap back to your normal user account once completed.

After youve successfully expunged WSL data from your OS, you will find that trying to run the typical WSL --Install commands in PowerShell no longer work, as Windows wont even recognize WSL as a CMD command of any kind. I stumbled around running various dism and sfc repair commands with reboots inbetween but what I THINK is the winning order is to grab the Linux Kernel WSL manual updater from [Microsoft](https://learn.microsoft.com/en-us/windows/wsl/install-manual) at step 4 of their guide, run the updater, and then start running in an elevated PS terminal: 

> 
`sfc /scannow` 

`Dism /Online /Cleanup-Image /ScanHealth` 

`Dism /Online /Cleanup-Image /CheckHealth` 

`Dism /Online /Cleanup-Image /RestoreHealth` 

`Get-AppXPackage -allusers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`  
> 
My theory is that by running the WSL Linux Kernel updater first and having the files present in WinSxS the repair utilities will pickup on the fact that WSL has been only partially installed and proceed to repair the directories we nuked earlier on. For good measure its probably worth running `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart` and `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart` at the end here, followed by a system restart.

At this point I was able to successfully install stock Debian via the usual `WSL --Install -d` method. To reiterate one more time, this really should be a desperation attempt at fixing WSL after youve tried the other choices, breaking a bunch of stuff and banking on repair utilities to undo your collateral damage is uh not exactly following best practices but its less of hassle than a full re-install at the very least. 

For whatever reason, Windows seems to cache WSL config/settings data in multiple hard to reach locations that survive typical uninstallation methods and it eventually turns into a mess if you swap distros, docker configs, and similar VM+Container experimentations often enough. If a more knowledgeable dev or Windows admin would like to chime in on an easier and safer way to do a deep WSL cleanse I certainly would welcome it, just sharing what my sysadmin-school-of-jank teachings led me into doing.

**Comment by juandavidguerra** [comment]
in my case Windows 11:
win + R -> services.msc
Host Network Service -> Automatic and Start

![Screenshot 2024-07-25 142526](https://github.com/user-attachments/assets/00c88e38-5349-44d2-b98f-638e10f63bd9)

**Comment by carlhaynes** [comment]
Thank you! This worked for me

**Comment by carlhaynes** [comment]
Thank You, Turning on the Host Network Service worked for me

**Comment by fantomcheg** [comment]
https://programmersought.com/article/80963680547/ This helped me
