### ISSUE TITLE
WSL2: Folder-mounted NTFS partitions not accessible.

### ISSUE THREAD

**Issue by MaineTim** [microsoft/WSL#5356]
# Environment

```
Microsoft Windows NT 10.0.19041.0
Ubuntu 20.04
WSL 2
```

# Steps to reproduce

Mount an NTFS partition on a folder mount point using Disk Manager, then attempt to access it under WSL2.

#  Expected behavior

Normal access to the mounted partition.

# Actual behavior

C:\Data is a healthy NTFS partition. When access via /mnt/c is attempted:
```
$ ls /mnt/c/Data
ls: cannot access '/mnt/c/Data': Input/output error
```

When a drive letter is assigned, this works correctly:
```
$ ls /mnt/d/
'$RECYCLE.BIN'   Documents
```
Access via the folder mount works correctly in WSL1.

**Comment by WSLUser** [comment]
I get permission denied for `/mnt/c`.

**Comment by benhillis** [comment]
Any logs in kmesg?

**Comment by SvenGroot** [comment]
@MaineTim In both WSL1 and WSL2, folder-mounted volumes are not automatically mounted in WSL, but can be manually mounted using e.g. `mount -t drvfs C:\\Data /mnt/data`.

Once it is mounted, in WSL1 the folder mount point (/mnt/c/Data in your case) gets treated as a symlink to its actual mount point. If a volume is mounted on a folder and also has a drive letter assigned, this happens automatically, since the volume gets automounted using the letter and the folder becomes a symlink to that (e.g. /mnt/c/Data is a symlink to /mnt/d).

Unfortunately, translating folder mount points into symlinks is not currently supported in WSL2, and it's currently unclear if/how it could be supported.

The reason for this is a bit complicated. Technically, folder mount points are what's known as junctions in Windows. WSL always treats junctions as symlinks. The target path of a junction can take two forms: an NT path using a drive letter, e.g. `\??\D:`, which is the case for junctions created with `mklink -j`, or a volume GUID path `\??\Volume{c545f859-2df9-471f-9849-e546e7c77a51}`, which is the form used for folder mounts.

In WSL1, when we translate a junction, we check the mount table for the current process and see which drvfs instance has a volume GUID matching the junction target, and use that mount point as the prefix for the translated symlink target. This works regardless of where the drive is mounted.

In WSL2, translation is done by the 9p server process in Windows, which doesn't have access to the mount table, or any of the Linux kernel internals. It just knows your default automount prefix, so it guesses that `\??\D:` would be mounted on `/mnt/d`. We can make that guess for drive letter targets, but with a target that uses a volume GUID we have no idea where it might be mounted inside WSL, so we can't translate it.

That means that until we can find a solution for this, the only way to access folder-mounted volumes is to mount them manually (as mentioned above) and access them through that mount point. You unfortunately can't access them through the original folder mount.

**Comment by MaineTim** [comment]
@SvenGroot Thanks for the excellent explanation. I'll put an entry in fstab and call it good. If it's not already in the WSL documentation, perhaps your explanation should be added.
