### ISSUE TITLE
How do you stop WSL from starting as you boot up Windows?

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/WSL#5399]
So every time I fire up my PC it seems WSL automatically starts running in the background (and I have to run wsl --terminate Ubuntu)

Is there like any setting for having it not start as I turn on my system?

**Comment by therealkenc** [comment]
Did you install Docker for Windows?

**Comment by ItsCubeTime** [comment]
> Did you install Docker for Windows?

Well no, I dont tend to use softwares with subscriptions

**Comment by therealkenc** [comment]
> Is there like any setting for having it not start as I turn on my system?

There is no such setting that I am aware of.

**Comment by ItsCubeTime** [comment]
Why would you close it? My question remains unanswered.

No software should start by itself out of the users control, and you certainly shouldnt need to setup a sandbox environment just to prevent something like that

**Comment by lbenz** [comment]
> Why would you close it? My question remains unanswered.
> 
> No software should start by itself out of the users control, and you certainly shouldnt need to setup a sandbox environment just to prevent something like that

As you probably already know, `vmmem` proc take lot of memory, so it could be nice to manually start `wsl2` ourself in case we don't immediately need it, so we can save memory .

**Comment by onomatopellan** [comment]
Use `wsl.exe --shutdown` and restart Windows. After restarting open cmd an post the output of `wsl.exe -l -v`

**Comment by vedant11** [comment]
Well, I think this issue should be addressed. Really hits the battery life. 
Thanks.

**Comment by Biswa96** [comment]
WSL does not automatically start after Windows boots, unless you set up that manually.

**Comment by Kein** [comment]
So why is this question closed?

**Comment by therealkenc** [comment]
The question posed was asked and answered (there is no setting). Biswa96 elaborated: WSL does not start absent some externality. It does not take much for WSL to start. Docker desktop with the WSL backend will do it. Breathing on the Linux folder in Explorer will do it. Possibly other scenarios I haven't thought of.

Moving to discussion. If there is some actionable (read: unidentified issue causing WSL to start that requires resolution) comes of the discussion a new issue can be spun up. The OP submission didn't make it far out of the deleted template.

![image](https://user-images.githubusercontent.com/7049700/103592848-fd88b800-4ea8-11eb-960f-47e725737164.png)

**Comment by amirasyraf** [comment]
WSL2 will start on its own if have pinned any VM directory to anywhere in Explorer, such as in Quick Access, your Desktop, or if any file/folder is visible in 'Recent files'.  This how you're able to instantly access your VM directory despite not explicitly starting them.

You should be able to test this out by removing any reference to any VM files and rebooting, vmmem should no longer start on boot.

However, pinning or putting shortcut in Start does not seem to automatically start WSL2. I have tested this out myself.

**Comment by prajjwal27** [comment]
Explorer in windows 11 by default pins the location of installed WSL instances to the side panel. Any idea how to remove it?

**Comment by Eldair** [comment]
> WSL2 will start on its own if you have pinned any WSL2 directory to anywhere in Explorer, such as in Quick Access, your Desktop, or if any file/folder is visible in 'Recent files'. This how you're able to instantly access your VM directory despite not explicitly starting them.
> 
> You should be able to test this out by removing any reference to VM files/directory and rebooting, vmmem should no longer start on boot.
> 
> However, pinning or putting shortcut in Start does not seem to automatically start WSL2. I have tested this out myself.
> 
> Edit: I've found that if you've manually shutdown WSL2, i.e. `wsl --shutdown`, it will not start again automatically. Trying to access the file/directory will return "not accessible" error. Not sure if this is intentional or not. It doesn't seem like a consistent behaviour.

This is no longer the case, if there is "linux" directory in file explorer it will start wsl when file explorer is opened but will shutdown again soon after that if wsl dir is not accessed.

**Comment by achintya-7** [comment]
I believe if you have Docker desktop installed. It will start on bootup and thus activates wsl. I am quite sure that there will be a option to prevent Docker desktop to start on boot up.

**Comment by Eldair** [comment]
@achintya-7 There is already an option not to start docker on boot up - it never starts for me unless I open it.

**Comment by hyoretsu** [comment]
> The question posed was asked and answered (there is no setting). Biswa96 elaborated: WSL does not start absent some externality. It does not take much for WSL to start. Docker desktop with the WSL backend will do it. Breathing on the Linux folder in Explorer will do it. Possibly other scenarios I haven't thought of.

For anyone coming here in Windows 11: collapse the "Linux" section in Explorer, otherwise WSL will start itself every time you open it.

**Comment by sveken** [comment]
For me there was a single file in the Recent files list in explorer,  thankfully you can right click it and go remove.

**Comment by stevenb123** [comment]
use services.msc (if on windows), stop the WSLService, set the startup type to disabled, create a batch file that has a net start WSLService command for starting, and one with net stop WSLService for stopping it.  Simples...

**Comment by Adrodoc** [comment]
I had this issue too. It was especially bad for me, because whenever WSL started it stole the keyboard focus of the current application and this happened every few minutes, making it a nightmare to work with my computer.
I had to remove all references to files and folders in WSL from quick access, and disable recent files (just removing all recent files from Windows explorer was not enough).

To disable recent files I had to:
1. Open Settings.
2. Click on Personalization.
3. Click on Start.
4. Turn off the **Show recently opened items in Jump Lists on Start or the taskbar and in File Explorer Quick Access** toggle switch.

This fixed the issue for me.

**Comment by xavierfoucrier** [comment]
I can confirm on my side it's **due to the mapped network drive from WSL**.

If you shutdown WSL with `wsl --shutdown`, the `VmmemWSL` process will stop immediately, but trying to access the WSL mapped network drive will start it again 😉 

> If you ask Windows to automatically try to map all network drives at startup, it will boot up WSL to let you access the drive.

**Comment by juliancorrea** [comment]
Isn't that what we're talking about?
![image](https://user-images.githubusercontent.com/5554854/229120225-2a5a3b11-2ba2-4f6d-81fd-8ae003680690.png)

**Comment by CyberIQ-ai-LLC** [comment]
I mapped a drive letter to \\WSL$ and that causes it to start. I deleted the drive letter (net use b: /delete) and now the vmmemWSL process no longer runs on startup. So, if you don't have a drive letter mapped to that, check to make sure that you don't have any other app or link or anything that touches that share.

**Comment by jorismak** [comment]
No recent items...
Nothing in my quick access list (anymore, had one).

Yet, the moment I open file explorer, it still auto-starts WSL.
It tends to auto start directly again after shutdown like 1 in 5 times as well. 
(type in `wsl --shutdown`, then directly enter `wsl --list --running` and the command stalls for a few seconds, then shows WSL running (again)).

I wish the on-demand startup could just be disabled, because this is horrible and lagging.

**Comment by niclasmattsson** [comment]
Same for me. No recent file lists ("Show recently opened items" in Settings was disabled), I had not pinned anything to Quick Access, no applications running except Chrome and I had not mounted any drives or made any other shortcuts to \\wsl$. Still my WSL would spontaneously restart itself within 10 minutes after `wsl --shutdown`.

**Turns out I missed something. \*I\* had not mounted any drives but apparently installing Ubuntu using the Store "helpfully" maps a network drive to U:. Deleting that mapping finally ended the restarts (fingers crossed).**

Time for a rant. Funny how every single computer problem I've had for the last few years is a new problem directly created by Microsoft's misguided attempts at being "helpful" or "friendly". Hiding "unfriendly" items in the Explorer context menu behind "Show more options", Word and Excel saving to OneDrive by default instead of my local drive, simplifying Settings menus by outright removing anything complex and forcing me to use the registry, etc etc.

Just today an email I sent bounced back to me. Instead of showing me the error, Microsoft inserted a banner with the Office 365 logo and text in a large font: "WHEN OFFICE 365 TRIED TO SEND YOUR MESSAGE, THE RECEIVING EMAIL SERVER OUTSIDE OFFICE 365 REPORTED AN ERROR." Then there was a visualization of how my email was blocked, ending in a **RED** bar with "ACTION REQUIRED - POLICY VIOLATION OR SYSTEM ERROR". Then there were two paragraphs of text explaining how the email failed without saying what the problem was. Then a line "Was this helpful? [Send feedback to Microsoft](https://go.microsoft.com/fwlink/p/?LinkID=717199)" (no it wasn't). Then a heading "More Info for Email Admins" with **SIX** more paragraphs of useless text entirely lacking technical info. Finally, then finally: *Error Details - Error: [550 5.0.350] One or more of the attachments in your email is of a file type that is NOT allowed by the recipient's organization.* That's all I wanted to know. Why not just put **that** at the top and call it a day?

**Dear Microsoft, please stop being friendly. You suck at it. We want the nasty messy Microsoft we know and love.
Sincerely, Everyone.**

**Comment by jorismak** [comment]
> Same for me. No recent file lists ("Show recently opened items" in Settings was disabled), I had not pinned anything to Quick Access, no applications running except Chrome and I had not mounted any drives or made any other shortcuts to \wsl$. Still my WSL would spontaneously restart itself within 10 minutes after `wsl --shutdown`.
> 
> **Turns out I missed something. *I* had not mounted any drives but apparently installing Ubuntu using the Store "helpfully" maps a network drive to U:. Deleting that mapping finally ended the restarts (fingers crossed).**

Full of hope, I looked... but `net use` shows nothing. Just trying to use `u:` gives Location unavailable.
So that's not it....

**Comment by jorismak** [comment]
I think I have found my cause.

Someone on SO came with the idea to use Procmon.exe and then filter on path containing \\wsl. You then see processes which are accessing paths that way.

In my case, msedge came up with very old downloads or other types of access.

But my Asus (laptop) system software Armory Crate came up, which was accessing a file I once downloaded (for a virtual audio driver) that I downloaded to my WSL homedir by mistake.

No clue why Armory Crate wanted that file. But removing it and searching through my registry for other places accessing \\wsl.localhost seems to have cleared it out (after rebooting again).

That Amory Crate 'user session service' is known for accessing mapped network drives out of the blue, at random as well. It's some plugin that can be disabled that scans for certain things, apparently.

More stuff to disable, more stuff to clean up. But WSL2 says shutdown now (so far).

**Comment by umlx5h** [comment]
In my case, it seemed to be activated by windows app Everything.
I've added the WSL directory to the index of Everything.

**Comment by strconv** [comment]
When I work, `wsl auto runs when open explorer` does not affect me.
When I was off duty and playing games, whenever I turned on the explorer, wsl would automatically turn on and eat up my 1 to 2G of memory. It makes me feel very repugnant(中文称作膈应).
So I have a bat script locally, and whenever I finish using the explorer, I will run this script (right-click-administrator mode execution)

> wsl_fuckoff.bat
```bat
powershell -Command "Get-Process -Name 'wslservice' | Stop-Process -Force"
powershell -Command "Get-Process -Name 'wslhost' | Stop-Process -Force"
```

It is strongly requested that Microsoft can give wsl an option so that Linux folder in the explorer will not be turned on automatically and will only be displayed when wsl is turned on manually.

**Comment by jorismak** [comment]
Its already been stated , if wsl starts the moment you open an explorer
window, you have a link to the wsl distro somewhere in your recent items,
your quick access, etc...

Otherwise does not autostart.

In my case it was Asus Armory Crate that had a service looking at downloads
or something , and one of those was a path to my wsl distro.

Use the tricks like procmon/procexp to look for processes accessing \\wsl$
to find out which process it is causing wsl to autostart.

Looking through your registry for things named \\wsl$ might also be a good
idea to find the recent items / MRU links that might cause explorer to
autostart wsl.

**Comment by iamexe** [comment]
Actual Solution:

1. Create a .bat file "WSL Choice.bat" in notepad.

2. Input this:


@echo off
net session >nul 2>&1
if %errorLevel% == 0 (
powershell -Command "Add-Type -AssemblyName PresentationFramework; if((gsv wslservice).StartType -eq "Automatic") { $choice = [System.Windows.MessageBox]::Show('Disable WSL and Restart?', 'Version Choice', 'OKCancel', 'Information', 'Cancel');if ($choice -eq 'OK') {Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\WslService -Name Start -Value 0x00000004; Restart-Computer}} else { $choice = [System.Windows.MessageBox]::Show('Enable WSL and Restart?', 'Version Choice', 'OKCancel', 'Information', 'Cancel');if ($choice -eq 'OK') {Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\WslService -Name Start -Value 0x00000002; Restart-Computer}};"
) else (
  echo "Right-Click Bat File And Run As Administrator."
)

pause

:: 0x00000000 = Boot
:: 0x00000001 = System
:: 0x00000002 = Automatic
:: 0x00000003 = Manual
:: 0x00000004 = Disabled

3. Save the file to your Desktop.

4. Right-Click, Run, Read, Choose, Restart, Enjoy.

**Comment by zhexyez** [comment]
Just adding to the heap.<br/>In the first photo, I recorded no actions between shutting down and it automatically starting by itself. However, after rerunning the test, I first just sat waiting in the console window clicking nothing outside. But then I've clicked on the Microsoft Edge window, scrolled this page a little, came back to console window, and distro shows running.<br/>[<i>Yes, my system has software from ASUS installed.</i>]
![image](https://github.com/microsoft/WSL/assets/35332515/7979f7ee-8859-46eb-b34e-eafe2b2fd388)
![image](https://github.com/microsoft/WSL/assets/35332515/79ca8d3e-adb6-4d30-97eb-ce54a871617e)

**Comment by jorismak** [comment]
It has been known that most cases of wsl auto starting always boil down
back to a filename or link that points to the \\wsl$ area.
Arnoury crate has a plugin that scans recently used files, it has been a
file in my download history in edge , or a shortcut in the quick access
folder... Searching the registry for \\wsl$ has always proven to be a
solution when encountering this on a machine.

**Comment by iamexe** [comment]
Just write a bat file that flips the registry to either on or off, restart.

Double click the bat, if on, ask to turn off and restart, if off, ask to
turn on and restart.

**Comment by zhexyez** [comment]
> It has been known that most cases of wsl auto starting always boil down back to a filename or link that points to the \\wsl$ area. Arnoury crate has a plugin that scans recently used files, it has been a file in my download history in edge , or a shortcut in the quick access folder... Searching the registry for \\wsl$ has always proven to be a solution when encountering this on a machine.

Okay, I've searched registry for \\\wsl$ and found 1 entry under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\IdListAliasTranslations\WSLLegacy`. It has Source with value \\\wsl$ and a Target that looks like `::{some hex numbers}`. I thought about deleting ASUS software, but I don't think whether it impacts stability of a motherboard or not (fans in particular), so hesitate on this one.

**Comment by iamexe** [comment]
You have to find the generic way to set a service status via registry.

Once you know how to set any service state apply it to the wsl service.

So you want to find "how to set service status via registry"

**Comment by iamexe** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\<SERVICE NAME>.

To disable set Start registry DWORD to 4

Not on my pc or else I would post my bat script :)

**Comment by zhexyez** [comment]
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\<SERVICE NAME>. To disable set Start registry DWORD to 4 Not on my pc or else I would post my bat script :)
I see. Yes, I've found that entry. Can you elaborate on possible values of Start DWORD? Or could you point me towards docs? Thanks!

**Comment by zhexyez** [comment]
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\<SERVICE NAME>. To disable set Start registry DWORD to 4 Not on my pc or else I would post my bat script :)

Okay, I've found that entry. Could you elaborate on possible values of Start DWORD or point me towards some docs? Thanks!

**Comment by iamexe** [comment]
*Value: Start*
*Type: REG_DWORD*
*Data:*
*0x00000000 = Boot*
*0x00000001 = System*
*0x00000002 = Automatic*
*0x00000003 = Manual*
*0x00000004 = Disabled*


*if you need a source copy paste it into presearch or your fav search
engine*

**Comment by iamexe** [comment]
or use chat gpt / antropic claude / ollama's local gpt option with model of
your choice

**Comment by zhexyez** [comment]
> *Value: Start* *Type: REG_DWORD* *Data:* *0x00000000 = Boot* *0x00000001 = System* *0x00000002 = Automatic* *0x00000003 = Manual* *0x00000004 = Disabled* *if you need a source copy paste it into presearch or your fav search engine*

I see, thanks!

**Comment by jorismak** [comment]
Services can also be managed by 'services.msc' right ?
Anyway, the whole idea of WSL starting on demand is nice. Setting the
service to disabled means you need to go through hoops to get it running.
Would be a deal breaker for me.

Used it on two asus laptops, a Thinkpad and my own desktop at home without
it auto starting.
So whatever works for you.
That one wsl$ entry you found in the registry didn't look like it should
affect things and looks like it needs to be there.
If you find out t happens with edge running, it's something in there. If it
also happens without edge running , it might be the plugin of armoury
crate. *Shrugging* . Good luck.

**Comment by iamexe** [comment]
You can manage services through services.msc, through set-service
PowerShell, through sc.exe and to some extent through task manager or
server manager.

The problem is that the wsl service cannot be disabled "on the go" on
Windows 10 because the status option is greyed out... so you are left with
registry hacks...

Would it be better if Microsoft made it easier? Sure! Will they today? Nope.

I would love it if MS before this issue would make /etc/environment work
properly too.

So yeah, we agree :)
