### ISSUE TITLE
How to backup the wsl2 ubuntu files

### ISSUE THREAD

**Issue by QThans** [microsoft/WSL#5418]
Recently, my windows os has crash.I had reinstall my os.
Now, I need to khnow  how can i to backups my wsl2 files.It's not like wsl, I can't access Linux files directly. I'm worried that if is has crash, I won't get it back.
Thansk.

**Comment by lightmelodies** [comment]
You can backup the ext4.vhdx. For recovery just install the same distro then replace the ext4.vhdx with the old one.

**Comment by QThans** [comment]
Thans,It's so convenient.

**Comment by QThans** [comment]
Does it affect if the version is upgraded?

**Comment by benhillis** [comment]
Use wsl.exe —export to backup.

**Comment by QThans** [comment]
@benhillis It's is so slow.
and now I'm going to use both methods at the same time.
Thanks.

**Comment by viltiki813196** [comment]
@QThans @lightmelodies  Can you confirm that it did work to copy the previous ext4.vhdx onto the fresh wsl / ubuntu install ??
My WSL recently broke after a Windows insiders build update, so I am unable to to use any of the wsl.exe cmd commands such as --export --import, and I seem to be unable to reinstall WSL. I think it may be easiest to do a fresh Win10 install to be able to use WSL2 again, rather than trying to repair any disk or image areas which takes a very long time on my machine.
And then I will just replace the ext4.vhdx after I reinstall the Ubuntu distro.
I hope it works???
Otherwise I have lost about a weeks worth of work since my last git commit!!!

**Comment by nagarajcruze** [comment]
@viltiki813196 did you tried? is that worked for you?

**Comment by viltiki813196** [comment]
Hi @nagarajcruze yes, I backed up a copy of the original ext4.vhdx (Ubuntut 18.04) onto my external harddrive.
I didn't have to reinstall win10. Instead I updated to the latest windows insder build, then I had to manually fix a problem with the lxss manager. Then I installed a fresh copy of the Ubuntu 18.04 onto wsl2
Then I replaced the newly installed ext4.vhdx with my original ext4.vhdx, and everything worked fine again as before.

**Comment by nagarajcruze** [comment]
@viltiki813196  Thanks...

**Comment by viltiki813196** [comment]
@nagarajcruze I also found this helpful to reinstall wsl and distros https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281

**Comment by nagarajcruze** [comment]
@viltiki813196 i think they refer to updating...

**Comment by SharakPL** [comment]
One important thing is missing from this story 😉 

    C:\Users\<your_user_name>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx

... if you're using Ubuntu distro
