### ISSUE TITLE
sudo does not work

### ISSUE THREAD

**Issue by michael-angelozzi** [microsoft/WSL#5435]
# Environment

```
Microsoft Windows [Version 10.0.19041.329]
(Ubuntu) Release:        20.04
```

# Steps to reproduce
1. Log in as root
2. `cd /usr/local/bin`
3. `sudo curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage > nvim.appimage`

#  Expected behavior

To let me change the system instead of blocking me, thats why I am trying WSL2 cause getting blocked in windows.

# Actual behavior

`-bash: nvim.appimage: Permission denied`

Windows blocks the action even via linux.

**Comment by therealkenc** [comment]
Can't grok what you mean by step (1), or the expected behavior, or where you are getting a "`-bash: nvim.appimage: Permission denied`" error from given none of the repro steps invoke `bash`. But in any event cannot reproduce here. [n.b. the `sudo` on `curl` is superfluous below since we're already root per imagined step (1).]

![image](https://user-images.githubusercontent.com/7049700/85065124-7de00980-b161-11ea-83a9-d4c60c2929cd.png)

**Comment by DHowett** [comment]
`sudo ... > file` will not have permission to overwrite `file`, because the `>` operator is being handled by the shell, _not by `sudo`_.

**Comment by therealkenc** [comment]
Let's call it that, simply because it matches the outcome, and is the correct interpretation of the error. [It does mean disregarding "step (1)" like it was never there, tho.]

Maybe want:
```
$ cd /usr/local/bin
$ sudo bash -c "curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage > nvim.appimage"
```

Or somesuch.
