### ISSUE TITLE
'ss -l -f unix' shows unix sockets open in other WSL2 containers

### ISSUE THREAD

**Issue by tycho** [microsoft/WSL#5467]
# Environment

WSL2 kernel version:
```none
$ cat /proc/version
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

Host OS version:
```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

Ubuntu container:
```none
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

Arch Linux container:
```none
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

# Steps to reproduce

1. `wsl --shutdown`, to ensure a clean environment to start with.
1. Open a shell to a WSL2 container, and install `socat`.
2. Run `socat STDIO UNIX-LISTEN:$HOME/test.sock` in WSL2 container and leave that running.
3. Start a 2nd WSL2 container (i.e. another distro).
4. Run `ss -l -f unix | grep test.sock`.

#  Expected behavior

The UNIX socket open inside the first container should not be visible in the second container.

# Actual behavior

The UNIX socket open in the first container is visible to the 2nd container, despite being inaccessible at the path it indicates (since that path is local to the 1st container):

```none
$ ss -l -f unix | grep test.sock
u_str LISTEN 0      5                       /home/steven/test.sock 20500               * 0
```

# Further Details

I'm using `socat` to create UNIX sockets inside WSL2 containers, which connect via npiperelay to gpg-agent on the Windows host environment, e.g.:

```none
$ ps aux | grep socat
steven      72  0.0  0.0   7416  2020 ?        Ss   23:43   0:00 socat UNIX-LISTEN:/home/steven/.gnupg/S.dirmngr,fork EXEC:/mnt/c/binnt/x64/npiperelay.exe -ep -ei -s -a 'c:/users/steven/appdata/roaming/gnupg/S.dirmngr'
...
```

This allows me to use a Windows-native version of `gpg-agent` running on the host, while WSL2 can access the services provided by that agent from within the guest environment. In particular, this allows for me to have my YubiKey usable in the guest for e.g. SSH other OpenPGP functionality.

As part of setting these sockets up, I was using a simple test (`ss -l -f unix | grep /home/steven/.gnupg/S.dirmngr`) to determine if the socket was already open and if `socat` needed to be run. In normal circumstances, if the socket appears in `ss -l -f unix` then it should be open and accessible at the path indicated -- and thus no new `socat` needs to be spawned to handle it.

The problem is, `ss -l -f unix` isn't scoped properly (or more accurately, `AF_NETLINK`'s response to `SOCK_DIAG_BY_FAMILY` for `AF_UNIX` is scoped incorrectly) . It shows open UNIX sockets in other WSL2 environments, so any environment started after the first believes that the socket is open and accessible to it. Thus my setup for `socat` would be skipped on any environment started after the first one.

To work around this problem, I've changed my test to do `socat OPEN:/dev/null UNIX-CONNECT:$SOCKETPATH` and use the exit code of that to determine whether the socket is actually accessible. While this does solve the problem, it seems wrong for `ss -l -f unix` to show open UNIX sockets in other WSL2 containers.

**Comment by tycho** [comment]
Just tested against the latest WSL2 kernel available in the Windows Update Catalog:
```
$ uname -a
Linux Arioch 4.19.121-microsoft-standard #1 SMP Fri Jun 19 21:06:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

This still happens there. I didn't expect that would fix it, but wanted to clarify that this isn't merely an issue of using an older WSL2 kernel build.

**Comment by benhillis** [comment]
@tycho - Thanks for posting.  This is because each distro runs in the same network namespace.
https://www.man7.org/linux/man-pages/man7/network_namespaces.7.html

I'll look into this a bit more...

**Comment by tycho** [comment]
@therealkenc Was there a resolution?

**Comment by benhillis** [comment]
By design / Linux behavior.

**Comment by therealkenc** [comment]
The behavior you described is by-design. Or put another way, WSL2 has one kernel and one network namespace by choice. That goes for `AF_INET`, and (in this instance) `AF_NETLINK`. Whether that is good, bad, or otherwise I (personally) take no position in the context. One could imagine a world where each WSL2 distro had its own network namespace, but they don't. It is not possible to decouple the behavior of `AF_INET` from `AF_NETLINK`, because Linux does not offer that fidelity.

Ref #5177, if the `AF_UNIX` socket inodes _were_ accessible, you could access sockets from different paths, and this is the case _even if_ each distro had its own network namespace (since olden-tymes [circa 2010](https://patchwork.ozlabs.org/project/netdev/patch/m11vcbgimj.fsf@fess.ebiederm.org/), anyway). An awfully good case could be made that the inodes returned by the `AF_NETLINK` query ought be confined to (filtered by) the mount namespace where those inodes live. But for good or bad, it doesn't work like that.

Tangentially, an `AF_UNIX` inode can have no accessible path at all, because the dentry may have been `unlink(2)ed`. Likewise if the socket is `rename(2)d`, the path returned by `ss -l -f unix` won't be correct. You can even have two open `AF_UNIX` socket inodes on the same path in the same mount namespace. The path returned by `ss -l -f unix` makes no guarantees about _accessibility_, even within a given network namespace or mount namespace.

Long-short, the solution you arrived at was correct. The idiomatic way to tell whether an `AF_UNIX` socket on a given path in a given mount namespace is open is to... open it.

Do thank you for the concise report though. Consider the behavior being non-obvious if by-design acknowledged. It isn't obvious.

**Comment by tycho** [comment]
I assumed there was going to be investigation around moving from one netns to multiple, but okay. Sounds fine.
