### ISSUE TITLE
Arrow keys automatically repeated if pressed once with wsl and an X server

### ISSUE THREAD

**Issue by realasking** [microsoft/WSL#5468]
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

# Steps to reproduce

problem 1
1. install VcXsrv, start it 
2. open a file using emacs from wsl
3. press any of the arrow keys once
4. the cursor might automatically move until reached the end or the head of the file, like the arrow keys were automatically repeated
This problem is randomly appears.

problem 2
1. uninstall VcXsrv, change to MobaXterm
2. open a file using emacs from wsl
3. press any of the arrow keys once
4. there are something like 111111111111111111111, 222222222222222222, 444444444444444444 would appear on the software
This problem is also randomly appears 

#  Expected behavior

arrow keys should move the cursor correctly

# Actual behavior

arrow keys repeated automatically

**Comment by therealkenc** [comment]
The behavior of the keyboard and cursor in any of those products (VcXsrv, emacs, many things beside) is not under the control of WSL. Can't repro here, but even if I could there wouldn't be an actionable. [Because WSL doesn't have a keyboard.]

If you explore your scenario further in a forum related to those products, recommend framing the question in terms of a VM or cloud scenario using VcXsrv or Moba as the server.

![emacs-cur](https://user-images.githubusercontent.com/7049700/85493400-b03b9d80-b58b-11ea-884d-6c282b18fb66.gif)

**Comment by schelian** [comment]
Here's the discussion Vcxsrv https://sourceforge.net/p/vcxsrv/bugs/59/

**Comment by TAUnionOtto** [comment]
https://sourceforge.net/p/vcxsrv/bugs/59/#5b37

> I changed the IME with shift+ctrl to default IME, then it works. But this is very strange.

It works for me! @schelian thanks

**Comment by snowman** [comment]
try to turn off IME

**Comment by dptr** [comment]
> https://sourceforge.net/p/vcxsrv/bugs/59/#5b37
> 
> > I changed the IME with shift+ctrl to default IME, then it works. But this is very strange.
> 
> It works for me! @schelian thanks

hi, I have the same issue, would you tell me what kind of IME do you use ? I tried fcitx but not work.
