### ISSUE TITLE
My bash.exe don't execute my WSL installation

### ISSUE THREAD

**Issue by danieldias2016** [microsoft/WSL#5474]
Hey Guys,

I having some issue with the 2004 build windows 10, i'm using hyper terminal and trying to execute my ubuntu installation by setting the default file C:\Windows\System32\bash.exe.

But the bash load in a strange path (/mnt/host/c/Users/Daniel) and ubuntu commands doesn't working.

Example:
![image](https://user-images.githubusercontent.com/21282527/85485603-72e10b00-b59f-11ea-92e9-d504bd82f058.png)

I've already tried to open normal cmd and type bash or execute bash.exe manually but the same things happen, the only way that i found is execute ubuntu terminal:

![image](https://user-images.githubusercontent.com/21282527/85485857-f3a00700-b59f-11ea-8942-b1750c015c7b.png)

Can someone help me with this?

Appreciate!

**Comment by therealkenc** [comment]
Need all the necessary commandline repro steps leading to the first screenshot. But whatever they are, you should treat `System32/bash.exe` deprecated (read: doesn't exist). That it is deprecated won't matter, mind. The error `sudo: command not found` will be, almost by definition, either because it isn't in your `$PATH` or it simply isn't there. But whatever it is you are doing with `bash.exe`, better to not.

**Comment by therealkenc** [comment]
I've gleaned your scenario. You probably want something like this. Replace 'focal2' with your distribution name of choice (from `wsl.exe -l -v`).

![image](https://user-images.githubusercontent.com/7049700/85488521-4ae3ae80-b583-11ea-9ccb-fec84341ce18.png)

![image](https://user-images.githubusercontent.com/7049700/85489100-5c798600-b584-11ea-9ad5-9359430b5e03.png)

**Comment by danieldias2016** [comment]
Solved!

Just put this parameters in hyper.js

shell: 'C:\\Windows\\System32\\wsl.exe',
shellArgs: ['-d', 'Ubuntu-18.04'], 

To see how distro was enable:

![image](https://user-images.githubusercontent.com/21282527/85604864-0d852c80-b628-11ea-99e8-972dd6fe1abf.png)

Thanksss!
