### ISSUE TITLE
When will WSL2 support Tesla GPU?

### ISSUE THREAD

**Issue by mszhanyi** [microsoft/WSL#5546]
**Is your feature request related to a problem? Please describe.**
More and more people are using Azure machine to do AI development and test. So far, only Tesla GPUs (M50, k80, P100, V100) are supported in Azure.
From https://developer.nvidia.com/cuda/wsl/download, Nvidia only provides Geforce and Quardro driver for WSL.
It means we couldn't do any GPU-related job with WSL in Azure.

**Describe the solution you'd like**
Support Telsa driver for WSL.

**Comment by luiset83** [comment]
The Quadro driver installs on the supported insider build with a Tesla GPU, however presumably because there is no WDDM driver active on a Tesla card, WSL2 does not support running CUDA apps -- there is no /dev/dxg device exposed since Tesla cards use the TCC driver.

A better title should be support TCC (Tesla Compute Cluster) driver for CUDA applications on Tesla GPUs. I see no other hits on Google regarding this, so it's possible it was not an entirely popular use-case :(

**Comment by Hassanfarooq92** [comment]
Found a work around.
Download quadro drivers for wsl2, extract them by running installer but don't quit the installer.
Go to device manager, right click and select update the driver, check have disk and un-tick show compatible models only.
Now you have to select the similar quadro model which have the same chipset as ur tcc. For my case m40 is same as quadro m6000. Update the driver and now device manager should show it as quadro gpu (this means we were able to load the required driver for wsl2).
Now go to cmd/terminal, use nvidia smi to change the driver mode to wddm by using the command (Google it), after changing the mode from 1 to 0, it will appear as TCC* instead of TCC. You're good to go now.

**Comment by littleyeson** [comment]
> Found a work around. Download quadro drivers for wsl2, extract them by running installer but don't quit the installer. Go to device manager, right click and select update the driver, check have disk and un-tick show compatible models only. Now you have to select the similar quadro model which have the same chipset as ur tcc. For my case m40 is same as quadro m6000. Update the driver and now device manager should show it as quadro gpu (this means we were able to load the required driver for wsl2). Now go to cmd/terminal, use nvidia smi to change the driver mode to wddm by using the command (Google it), after changing the mode from 1 to 0, it will appear as TCC* instead of TCC. You're good to go now.

Is Tesla V100  use this way to work into WSL2?
