### ISSUE TITLE
network hangs in Windows with WSL enabled

### ISSUE THREAD

**Issue by swebs** [microsoft/WSL#5553]
When I reboot my computer, and before I connect to my corporate VPN, if I try to connect to one of my corporate network drives, e.g., in Explorer, it hangs, rather than giving a "couldn't connect" error immediately or timing out in a reasonable period. Similarly, if I try to open PowerShell (PS App), or a WSL instance in Terminal, it just sits there and does not display a prompt. Usually a prompt eventually appears after about 10 minutes. If I connect to my VPN during this period then the problem immediately resolves itself. Internet access is available, just not the connection to my corporate network.

So far this would appear to not have much to do with WSL, however after doing some testing with other computers it appear that this issue starts occurring after WSL is enabled (either featurename:Microsoft-Windows-Subsystem-Linux or featurename:VirtualMachinePlatform).

Generally it seems that with WSL enabled various Windows processes that try to access unavailable network resources hang or take a very long time rather than "realizing" that the resources are not accessible. Not sure if this is actually a WSL problem, and I realize this bug report is probably more vague than ideal, but maybe this makes sense to someone...

```none
Windows build number: 10.0.19041.329
```

**Comment by swebs** [comment]
I am not sure if the need-repro tag means that this needs instructions to reproduce, or just needs someone to be able to reproduce it, but I will try to provide a more explicit set of instructions. I am not sure which parts are entirely necessary.

Computer setup:
* WSL and Virtual Machine Platform enabled
* Network drives mapped which are inaccessible on reboot, e.g., because not connected to corporate VPN
* Computer connects to internet automatically on reboot (but not VPN)

Steps to reproduce:
* reboot
* log in immediately after reboot
* open Explorer and try to connect to inaccessible network drives
* open PowerShell
* repeat the previous two steps several times for a minute or two after logging in as the problem does not seem to necessarily start immediately

Expected behaviour:
* Trying to connect to network drives should cause "Restoring Network Connections" error dialog
* PowerShell should open fully with an interactive prompt available

What actually happens:
* Explorer hangs, with green progress bar very slowly progressing across address bar
* PowerShell window opens and displays some text like "Windows PowerShell", "Try the new cross-platform PowerShell ..." but the actual prompt does not appear

**Comment by therealkenc** [comment]
The practical path forward is to contact your corporate VPN provider and see if the problem is something that can be traced back to the Virtual Machine Platform or something vEthernet related. Even if there were some me2s on this submission, it would be impossible to know if the problem was the same as yours (or even remotely related). You _might_ try your luck in the hyper-v technet [forum](https://social.technet.microsoft.com/Forums/en-US/home?forum=winserverhyperv) on the off chance someone over there recognizes the fail pattern. But likely, a reader is going to need a repro too... some recipe of steps from a clean Windows install that gets a machine into a state where "it just sits there and does not display a prompt". And as soon as you enumerate the "my corporate VPN" step to get there, well you get the idea.
