### ISSUE TITLE
be able to print through WSL

### ISSUE THREAD

**Issue by ngfchristian** [microsoft/WSL#5621]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.330][run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019.
```

# Steps to reproduce

I am trying to install the driver of my printer, but it doesn't complete successfully.
below is the error i am getting.
[https://i.stack.imgur.com/UyhZ2.jpg](url)
i am running ./hplip-3.20.3.run

#  Expected behavior
the installation is supposed to go through without having an error.

# Actual behavior
 it says python3-pyqt5 is missing, however when trying to install that one, it says it's already installed.

I cannot install the driver, therefore my application cannot work properly.

Thanks.

**Comment by therealkenc** [comment]
"Trying to install the driver of my printer" is not a repro, and that jpg hyperlink doesn't resolve to an image. But lets call this spiritually equivalent #2195 if it is a USB printer, and a lengthy [serverfault](https://serverfault.com/) question if it is a network printer. For the latter it is often better to frame the question something like "how do I install a printer on a headless Linux container" over there rather than WSL.
