### ISSUE TITLE
wsl_update_x64.msi comes from unknown publisher

### ISSUE THREAD

**Issue by yegle** [microsoft/WSL#5628]
# Environment

```
PS C:\Users\yegle> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

# Steps to reproduce

1. Following https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2, run `wsl --set-default-version 2` to set WSL 2 as default version.
2. Prompt to go to https://aka.ms/wsl2kernel and download the Linux kernel update `wsl_update_x64.msi`
3. Run this installer

#  Expected behavior

Expect this installer to be from Microsoft.

# Actual behavior

Yellow UAC warning suggesting the installer is from Unknown publisher.

**Comment by therealkenc** [comment]
Thank-you for the submission. That is odd indeed. I can't reproduce here (no yello UAC). If others are seeing this give a thumbs up on the OP. Below is the SHA256 of the `.msi` of this writing (just downloaded). If yours matches, pretty safe to proceed despite the warning.

![image](https://user-images.githubusercontent.com/7049700/88186872-a9379780-cbea-11ea-8f6e-c622eaddac24.png)

**Comment by licanhua** [comment]
I can't repro it either, can you post a screenshot of the error?

**Comment by yegle** [comment]
The hash of my downloaded file matches the one in https://github.com/microsoft/WSL/issues/5628#issuecomment-662477378. It looks like this has something to do with my local system setup.

I'll close this bug for now and investigate further. FWIW below is the screenshot of the UAC warning (captured on my phone as UAC does not allow win10's built-in screenshot feature):

![image](https://user-images.githubusercontent.com/146133/88243994-1a0c9d00-cc47-11ea-9b9e-40c9759396a5.png)

**Comment by yegle** [comment]
Still puzzled by this issue but at least I can verify the installer is indeed signed by Microsoft on my end:

![image](https://user-images.githubusercontent.com/146133/88244253-1cbbc200-cc48-11ea-871a-e295d4389b75.png)

**Comment by yegle** [comment]
For some reason, if I run `msiexec /a wsl_update_x64.msi` then I can successfully start the installer without any UAC warning. But if I run `msiexec /i wsl_update_x64.msi` I get the same UAC warning.

**Comment by ruant** [comment]
@yegle For what it's worth, I get the same UAC warning.
Hash of the file matches the hash @therealkenc posted.

**Comment by yotauber** [comment]
I still get the same UAC warning (unknown publisher).

**Comment by jeremyn** [comment]
I had this problem and believe I fixed it by:

1) turning off the "Windows Subsystem for Linux" feature
2) uninstalling a lingering "Windows Subsystem for Linux Update" item in Apps & Features (this uninstaller itself raised the yellow unknown publisher warning even though it reported itself as from Microsoft Corporation)
3) restarting the WSL install process from the beginning as in [the docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

Probably best to reboot after each step even if you're not prompted to do it. When I started from scratch, the MSI was recognized as signed. 

Side note, when I ran the MSI successfully, I saw a box with the Tux penguin and a prompt, and only after a click or two did I get the valid blue UAC prompt. When it was failing, I got the yellow UAC prompt immediately after running the MSI. If this was actually a signature/certificate problem, I'd expect the blue and yellow prompts to appear at the same point in the install sequence. Since they appear at different points, I think it's actually a WSL install problem.
