### ISSUE TITLE
WSL2 can't connect local mysql server

### ISSUE THREAD

**Issue by Ashubel** [microsoft/WSL#5681]
Oops! My WSL2 with Kali, but can't connect to mysql, the error like this:
![image](https://user-images.githubusercontent.com/23721338/88872881-dd93ff00-d24d-11ea-8b93-a8ad1c3d7197.png)

**Comment by therealkenc** [comment]
The install isn't clean partly because #573 and possibly elsewise absence `systemd`. 

![image](https://user-images.githubusercontent.com/7049700/88876669-a8999500-d1d8-11ea-962e-59909560d053.png)

That's not causing `service mariadb start` to fail though. There is no `/etc/init.d/mariadb` and that `unrecognized service` is expected behavior (unrecognized 'cause not there). I took a look at my 20.04 Ubuntu Real Linux box and it doesn't have `/etc/init.d/mariadb` either. So this is probably going to be the situation for all modern-ish Debian derived distros. There is analogous `mongodb` case from a while back [here](https://github.com/microsoft/WSL/issues/796#issuecomment-392995415) and [here](https://askubuntu.com/questions/767134/mongodb-3-2-6-init-script-is-missing).

Starting `mariadb` with `systemctl` is #1579. Some docker folks use a `systemctl` facsimile mentioned [here](https://github.com/microsoft/WSL/issues/1579#issuecomment-481085323). Or start it manually (how I'd roll). Or find (or write) an `/etc/init.d` script to start it slightly less manually. Or big hammer fire up `systemd` à la #994 and various blogs on the web.
