### ISSUE TITLE
`wsl` does not respect Windows-side symlinks

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/WSL#5701]
# Environment

Windows build number: 10.0.20180.0
Your Distribution version: Ubuntu 18.04
WSL version: WSL 2

# Steps to reproduce

Use CMD to create a synlink to somewhere inside the WSL FS, in my case:

    mklink /d c:\eli \\wsl\Ubuntu-18.04\home\eli

Then cd into it, and use the `wsl` command -- it always starts with the root `/` as its working directory.  For example:

    C:\eli>wsl pwd
    /

#  Expected behavior

Expected to resolve the windows-side link before resorting to using `/`.

# Actual behavior

Uses `/`.

# Use case

Just to clarify my use case: I use both Linux & Windows heavily, so I want to have an easy short path to my home directory on the WSL side.  (In WSL1, my home directory was actually at `c:\eli`, with the WSL1 `/home/eli` being a symlink to it, and I now decided to try the switch to WSL2.)  Using `mklink` as above works nicely (with a minor caveat that it doesn't exist until I start WSL), but using `wsl` itself to start stuff from windows doesn't get the correct directory.  For example, I'd expect to just run `wsl` and get a linux shell at my directory, but if I'm in the symlink, it starts at `/`.

**Comment by therealkenc** [comment]
/dupe #5118 (with a tangential side order of #4868)

**Comment by elibarzilay** [comment]
@therealkenc, I have seen #5118 before posting this, and I also read through #4868 now -- it looks to me like both of these are about making WSL-side symlinks work on the windows side, but this is not what I'm talking about here.  This one is about the Windows-side `wsl` command not respecting a symlinked directory if you're in one (ie, I'm talking about a symlink that was created in `CMD` using `mklink`).

**Comment by razamatan** [comment]
i'm hitting this bug, but at a file level.

i currently have my windows terminal settings.json file (`%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`) linked to my dotfiles in wsl (dir output: `<SYMLINK> settings.json [\\wsl$\Ubuntu\home\razamatan\.dotfiles\settings.json]`).

since wsl2 switched to vhd's, if i try to open terminal w/o starting wsl to load the vhd, i get the "Encountered errors while loading user settings" error dialog. i have to remember to always start wsl to allow wt to be able to read from this (and any other) symlink to \\wsl$ files.

it would be great to automatically load wsl if trying to access any symlink that points to wsl paths.

**Comment by elibarzilay** [comment]
@razamatan, this is a separate issue (which I originally mentioned originally as a caveat).

BTW, I have a startup script (made in the Task Scheduler) that starts WSL when windows starts -- that would be an easy way to ensure that WSL starts automatically.

**Comment by razamatan** [comment]
ok.. i'll create a new issue.

**Comment by razamatan** [comment]
yeah.. but wsl stops if not accessing things regularly.
________________________________
