### ISSUE TITLE
Windows ssh Server conflict with tmux in WSL2

### ISSUE THREAD

**Issue by hzhangxyz** [microsoft/WSL#5703]
# Environment

windows 10 build 19041.388
WSL2

# Steps to reproduce

- Enable windows 10's ssh server
- Run `tmux` in WSL2
- Ssh from another machine into this windows 10's sshd and get cmd shell
- Run `wsl` from cmd in ssh environment
- Try to `tmux attach` in `wsl` in cmd in ssh, and fail

#  Expected behavior

expect get tmux session attached

# Actual behavior

Show no session
Although I can see tmux in `htop` and even socket in `/tmp/tmux-0`, But I cannot still connect to tmux server

**Comment by therealkenc** [comment]
Was not able to reproduce here.

![image](https://user-images.githubusercontent.com/7049700/89151911-d05d6580-d516-11ea-9be7-ed4a4bda9856.png)

Tagging need-repro, but it isn't WSL actionable. If `tmux` returns "`no sessions`" that is because there aren't any. WAG you aren't `UID 0` (`root`) in both places, based on hint `/tmp/tmux-0`. [Setting aside that nothing good comes from running `tmux` as root.]

**Comment by hzhangxyz** [comment]
@therealkenc 

Sorry, I try again, install a fresh wsl(https://github.com/yuk7/ArchWSL)

And I find it works, I got what was wrong is I mount tmpfs to /tmp

Then I try to mount tmpfs to /tmp again, and reproduce it successfully
