### ISSUE TITLE
curl connection timeout on port 8443

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#5707]
Hi, 
I am trying WSL 2 with Ubuntu 20.04 for development instead of the virtual machine with Ubuntu and I found one issue.

From Windows PowerShell, I run this command "curl https://mysite:8443/grafana/api/dashboards/uid/myid" successfully. Same on my virtual machine with ubuntu. When I try the same command in WSL I got:
```
*   Trying <mysiteip>:8443...
* TCP_NODELAY set
* connect to <mysiteip> port 8443 failed: Connection timed out
* Failed to connect to idot.system4u.biz port 8443: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to <mysite> port 8443: Connection timed out
```
Any suggestion?

Edit: If I try another port on the same site "curl https://mysite:443" it work well.

**Comment by therealkenc** [comment]
Please your windows build number. 

Disable firewall temporarily just to eliminate that variable. It isn't obvious that will help because it is an outgoing connection. But it is the usual subject and worth a shot. The exercise here is determining what is different about port 443 and 8443. WSL proper doesn't care about the difference, so whatever is going on, we're looking for something outside WSL. There is no repro here so not a lot to go on, even from the community.

**Comment by prochotor** [comment]
I have Version 2004 (OS Build 19041.338).

I tried to turn off the firewall but no effect.

I think the problem is in WSL because when I run the same command in PowerShell It works well. Same on my virtual machine with ubuntu
