### ISSUE TITLE
After importing/exporting WSL instance, no longer can execute `cmd.exe`, Permission denied

### ISSUE THREAD

**Issue by corykim** [microsoft/WSL#5710]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020)
```

# Steps to reproduce

The reason I'm doing this is to move the WSL files from my C: drive to my D: drive.

```
wsl --export Ubuntu-18.04 Ubuntu-18.04.tar
wsl --import Ubuntu-18.04 d:\virtual-machines\wsl Ubuntu-18.04.tar
```

When I run `wsl`, I notice that the user is `root`. So I set the default user:

```
ubuntu1804 config --default-user <username>
```

Then try to execute `cmd.exe` from a command line.

#  Expected behavior

I should see the command line prompt:
```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\my-name>
```

# Actual behavior

I get an error message:
```
-bash: /mnt/c/WINDOWS/system32/cmd.exe: Permission denied
```

If I check the command using:
```
ls -l /mnt/c/Windows/System32/cmd.exe
```
I see that the permissions are:
```
-r-xr--r-- 2 root root 289792 Dec  7  2019 /mnt/c/Windows/System32/cmd.exe
```

So if I run 
```
sudo /mnt/c/Windows/System32/cmd.exe
```

I get the Windows command prompt. But I shouldn't have to `sudo` to get that.

**Comment by therealkenc** [comment]
It is nonobvious behavior. Once you've done an `--import` then the (scare quote) "old" way of setting the default user via `distro.exe config --default-user` is not applicable. 

Set up a default user in [wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user). Ref #3974 ([message](https://github.com/microsoft/WSL/issues/3974#issuecomment-576782860)). Make sure to `wsl.exe --shutdown` for it to take. 

Also do not import to the same distribution name; there lies a lot of heartache. That a duplicate distro name was allowed by `wsl.exe --import` instead of erroring out is.... unfortunate. 

Should look like this, but you already surmised as much.

![image](https://user-images.githubusercontent.com/7049700/89229657-b19eb380-d596-11ea-833e-a48c0f478ed1.png)

**Comment by corykim** [comment]
Thank you @therealkenc, that did the job!
