### ISSUE TITLE
ubuntu.exe returns to cmd prompt without starting WSL

### ISSUE THREAD

**Issue by abdallaegt** [microsoft/WSL#5711]
#5709 Environment

```none
Windows build number: [Version 10.0.18363.959]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc 
version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce
C:\Users\hp>ubuntu

C:\Users\hp>bash

C:\Users\hp>

![bandicam 2020-08-03 22-28-29-561](https://user-images.githubusercontent.com/67766127/89224458-d0be3500-d5d8-11ea-9537-60628eb43e4e.jpg)

#  Expected behavior

# Actual behavior

**Comment by therealkenc** [comment]
> Windows build number: [Version 10.0.18363.959]

As an initial attempt, try installing Ubuntu-18.04 from the [Store](https://www.microsoft.com/en-ca/p/ubuntu-1804-lts/9n9tngvndl3q?activetab=pivot:overviewtab). In your submission you state Ubuntu-20.04 as your distribution version, but `ubuntu.exe` as the launcher, which is somewhat incongruous. After installing 18.04, start it with `wsl.exe -d Ubuntu-18.04`. The `bash.exe` application has been deprecated.

If that doesn't work, try updating to Windows 2004 aka 19041 to eliminate anything that may have been addressed since 18363. _Don't_ upgrade the distro to WSL2 until you've got WSL1 solved. If that still does not help, please post [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) via the feedback hub.

**Comment by Roseidon** [comment]
I had a similar issue today (wsl not starting), but I was prompted to update my wsl2-kernel (see https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel). Maybe this helps you!

**Comment by abdallaegt** [comment]
The problem was solved [here](https://stackoverflow.com/a/52574881/13079083)
Essentially, navigate to `Control Pane`l > `System `> `Advanced System Settings `> `Advanced `> `Settings `> `Advanced `> `Virtual memory`, Change ..., and set a Custom size for the paging file size: `800 `min and `1024 `max. Restarted, and the command prompt came back.

**Comment by therealkenc** [comment]
Thank-you for the follow up! Fascinating. The working theory being, this is dupe #849.
