### ISSUE TITLE
Japanese charactors not rendering correctly

### ISSUE THREAD

**Issue by louist103** [microsoft/WSL#5713]
# Environment
```none
Windows build number: [10.0.19041.388]
Your Distribution version: [ Ubuntu 20.04]
Whether the issue is on WSL 2 and/or WSL 1: [WSL1 and 2]
```

# Steps to reproduce

Doing anything to have Japanese (or likely any non ascii characters) display on the terminal .
In my case I am using Project64 and attaching a debugging tool through telnet to see Console output from debug roms.

#  Expected behavior
Expected to see characters like this :女神リフト CT

# Actual behavior
What actually happens is garbage is displayed instead. (screenshot attached)

**Comment by louist103** [comment]
![Capture](https://user-images.githubusercontent.com/35883445/89255249-40d7b580-d5ef-11ea-8fef-7213c7daca62.PNG)

**Comment by licanhua** [comment]
I guess it's codepage problem.
To verify that, you can install 'Windows Terminal' from Windows Store, and try it again from Windows Terminal. 'Windows Terminal' has better localization support.

If 'Windows Terminal' works fine, you may try:
1. set Windows display language to Japanese
2. change system locale to Japanese in Region Settings

**Comment by therealkenc** [comment]
> Doing anything to have Japanese (or likely any non ascii characters) display on the terminal .

You'll have to be a little more specific than "anything".

![image](https://user-images.githubusercontent.com/7049700/89255739-49bc8d00-d5d7-11ea-8295-0731f4e2fbfe.png)

First thing you can try is start `wsl.exe` from the new Windows [terminal](https://www.microsoft.com/en-ca/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab). That might or might not help your particular scenario out of the box but it is a good place to start. Sometimes the output needs to be piped though [`iconv(1)`](https://man7.org/linux/man-pages/man1/iconv.1.html) or similar depending on the encoding.

If none of that helps, open an issue over in the [terminal github](https://github.com/microsoft/terminal). WSL doesn't actually render the glyphs (Japanese or otherwise). They'll want a repro, and "....using Project64 and attaching a debugging tool..." _probably_ isn't going to get a lot of uptake. Redirecting some of the output to a file and posting a [gist](https://gist.github.com/) may shed some light under examination. Something that can be reproduced locally would be better.
