### ISSUE TITLE
Hyper-V Socket HV_GUID_WILDCARD not working for WSL2 vms

### ISSUE THREAD

**Issue by jpathy** [microsoft/WSL#5751]
# Environment

```none
Windows build number: [10.0.20185.0]
Your Distribution version: [20.04]
Whether the issue is on WSL 2 and/or WSL 1: [WSL 2]
```

# Steps to reproduce
 If you run a [AF_HYPERV](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/make-integration-service#vmid-wildcards) server with `HV_GUID_WILDCARD` / `HV_GUID_CHILDREN` as `VmId`, the vsock client inside the vm can't connect to it. Only running on the actual `VmId` of the VM (obtained from `hscdiag`, this requires admin priviledge) works. Is there anyway to serve multiple wsl2 vms without needing admin access and listening on all VmIds?

#  Expected behavior
Should be able to communicate with guest without needing the VmId. @benhillis As per your comment here: https://github.com/microsoft/WSL/issues/4131#issuecomment-502287479 , is there a way now for host/guest communication? Thanks in advance.

# Actual behavior
Not working.

**Comment by vivimillin** [comment]
For anyone landing here: the OP's question now has a practical answer.

The missing piece was an *unelevated* way to learn the WSL2 VM id. Since
Store WSL 2.0, `wsl.exe -- wslinfo --vm-id` returns it — no admin rights,
no HCS APIs. With that, a host-side server can bind its listener to the
exact VM id (the only binding WSL2 will match) and rebind when the id
changes at the next WSL boot.

A VcXsrv fork implements exactly this approach: a `-wslvsock` flag that
auto-detects the running WSL2 VM and rebinds the listener automatically
after `wsl --shutdown` or a reboot. Root-cause analysis and details:
https://github.com/marchaesen/vcxsrv/issues/80

(Disclosure: I wrote that fix, and an unofficial build is linked from the
issue. The `wslinfo --vm-id` part is useful regardless of which server
you run.)
