### ISSUE TITLE
Running X server with WSL2 on build 2004 causes hard reboots

### ISSUE THREAD

**Issue by klausman** [microsoft/WSL#5769]
# Environment

```none
> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```
Your Distribution version: Debian 10
```
$ cat /proc/version
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Install Win 10 Enterprise, update all the way to 2004.

```
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
[...]
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

Restart machine, try:

```
wsl --set-default-version 2
```

This results in the well-known error that requires an update from https://aka.ms/wsl2kernel, so install that, reboot again for good measure. `set-default-version` now works.

Install Debian, make sure it is running on WSL2:

```
> wsl -l -v
  NAME      STATE           VERSION
* Debian    Running         2
```

Now everything up to this works fine. But for my use case, I need X11. So I installed VcXsrv, the only really still supported standalone X11 server for Windows: https://vcxsrv.sourceforge.io/

Start the X server with Clipboard sharing, wait between "practically instant" or ten minutes and the machine reboots hard, direct to BIOS/POST. No errors, no slowdown, no BSOD, hard, instant reboot.

I had a WSL1 setup for close to two years using VcXsrv, without any trouble whatsoever. I even tried Windows 2004 with Debian still running as a WSL1 VM, same issue.

I tried to pinpoint it to a particular program, action, time frame, ... nothing. I will keep trying to find a more reproducible case, but I don't want to sink more time into this than strictly necessary. My machine is practically not useful right now, except for games, so I am going to rollback to 1909 soonish. 

# Logs/Traces etc.

I found nothing useful. I doubt that error messages or anything ever actually hit non-volatile storage due to the hard reboot.

#  Expected behavior

Solidly running X11 apps, as they have been for a while.

# Actual behavior

See above: cold boots with no rhyme or reason.

**Comment by therealkenc** [comment]
> I even tried Windows 2004 with Debian still running as a WSL1 VM, same issue.

Make sure to disable the Virtual Machine Platform as well and reboot. WSL1 will still run. If you have already tried that, or you do and it still doesn't help, the cause is something lower down.

**Comment by DHowett** [comment]
The way the original report is worded it sounds like _just running VcXsrv_ is enough to take your machine down. Are you running any X clients in WSL? Does it happen if you don’t even touch WSL?

**Comment by klausman** [comment]
>> I even tried Windows 2004 with Debian still running as a WSL1 VM, same issue.
>
> Make sure to disable the Virtual Machine Platform as well and reboot. WSL1 will still run. If you have already tried that, or you > do and it still doesn't help, the cause is something lower down.

Good point, I've disabled it (`dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /all`) and rebooted. Let's see if it helps.

> The way the original report is worded it sounds like just running VcXsrv is enough to take your machine down. Are you running any X clients in WSL? Does it happen if you don’t even touch WSL?

Yes, the first few times it happened right after boot (I had set vcxsrv to run at boot, as it was for over a year with wsl1) and the machine rebooted while I was trying to set the WSL default to 2, with only Powershell open (and the WSL1 VM running in the background). I had already done the VMP activation mentioned above, so maybe undoing that will help. Will do some testing today.

**Comment by klausman** [comment]
It's been 8.5 hours with `VirtualMachinePlatform` off and VcXsrv running plus a bunch of X clients (urxvt, xload and a few others). Zero reboots so far. I don't think I'm out of the woods yet, but this is looking good, so far. Will do another workday with this setup, then try turning it back on (but staying on WSL1 with the Debian VM), see if the crashes come back.

**Comment by jpiquot** [comment]
I have the same issue on my PC. KB4566782+Hyper-V+Containers causes hard reboots. And on another machine, Docker fails to start after the KB4566782 update. I did dare rebooting it as it has many running VMs.

**Comment by klausman** [comment]
More data: I ran with WSL1 and VMP off for two full days (well over 16h of productive use) without a single reboot.

This morning, I reactivated VMP and switched the VM back to WSL2, and within two hours, got a hard reboot.

I have now only switched the VM to WSL1, but left VMP active, so see what happens.

**Comment by klausman** [comment]
And I just had another crash. So in summart, build 2004 hard-crashes for me every few hours if VMP is activated and VcXsrv (likely other X11 servers with a similar codebase) is running. Whether or not a WSL2 VM is running makes no difference, and neither do the startup options of VcXsrv (clipboard, GL acceleration).

On reddit, [shawnz suggested](https://www.reddit.com/r/bashonubuntuonwindows/comments/iavksc/updating_to_wsl2_makes_windows_do_random_hard/g1rrkak/) using `bcdedit /set hypervisorlaunchtype off`, do the people here think that would be a useful experiment? AIUI, it would be instead of tuning off VMP, but I am willing to try other combinations. Just be aware that any set of options on/off will likely take a day or two to prove stable.

**Comment by FrankHB** [comment]
Suspected NT kernel memory subsystem bug + hypervisor bug.

I have no plan to use WSL2 recently and I have not met such hard reboots, but I have also met strange problems. The problems get worse when using WSL1 + VcXsrv.

First, I have found some bugs like [this](https://github.com/msys2/MINGW-packages/issues/5067) in 2018 after a Windows 1809 update. There are random crashes running various programs (MSYS2, Win32, WSL... at least every GCC I used on these hosts and some other heavy programs like browsers). (Since it seems not to be userland-specific, I finally closed that bug in the link.) Worse, this may finally cause a BSoD with a stop code related to kernel memory (e.g. `MEMORY_MANAGEMENT`, `SPECIAL_POOL_ETECTED_MEMORY_CORRUPTION`). Every time (found in the minidump), it crashed in the `nt` module (`ntoskrnl*.exe`), whatever 3rd-party drivers had been installed. (The driver verifier did not help. It found a misbehaved VirtualBox network driver and I uninstalled VirtualBox but there is nothing else different.) Hence, it should be a NT bug. Every release since 1809 have the same problem on my current machine (a *Microsoft* Surface Book 2). The only "fix" effective is to rollback to 1803. And 3 (all laptops, accidentally) of 4 my computers updated to 1809 or later versions of Windows 10 have the same problem, I don't know why.

The timing to get the said memory corruption is random and likely unrelated to the user processes being running, but probably Windows-version-specific. In 2004 the system would crash (BSoD) in no more than one hour, so I did not test it much. The current machine I used had been recently updated to 20H2 and it could work normally more than 6 hours. I eventually deleted the old Windows instance and found it crashed again... This time I just can't rollback the system. Then I searched the net and come here.

The fact related to this issue I've found: enabling VMP and running VcXsrv (plus some heavy work in WSL1 like parallel compilation) in my current machine can **almost deterministically reproduce the memory corruption in a few minutes** (rather than a few hours), and soon a BSoD. Disabling VMP does work around the issue said here, but it still cannot prevent the crash after several hours in my machine.

I've also noticed there is another related well-known [(performance) bug](https://www.reddit.com/r/Windows10/comments/8kg4xl/emptystandbylist_when_will_they_fix/) since 1803, which can be worked around by using [Empty Standby List](https://wj32.org/wp/software/empty-standby-list/) or sysinternals RAMMap. This does defer some corruption in user programs (by forcing reloading the files on the disk rather than in the cache). Nevertheless, it still does not solve my problem. But it leads to my current workaround: disabling the `SysMain` (previous `Superfetch`) service. **It seems works**: my system now runs normally for more than 24 hours.

I am still testing this and I have not re-enabled VMP. I wonder whether the workaround can help in this issue.

**Comment by klausman** [comment]
For what it's worth, with the most recent cumulative update for 2004 (KB4579311) it seems the crash has gone away. I have been running typical day-long sessions with an X server running and my Debian switched to WSL2 without issue for about a week now.
