### ISSUE TITLE
Pasting from clipboard when language is different than copied is broken

### ISSUE THREAD

**Issue by pavelbrylov** [Microsoft/WSL#580]
There seem to be a bug with current clipboard implementation.

Repro steps:
- Copy english text (say apt-get install vim)
- Switch keyboard to some non-ascii language, say RU
- Right click in bash window
  Result for me is "  - "

If I switch keyboard layout to EN and paste again, it works fine.

It is understandable that it doesn't work as expected because of the current implementation, as described by @bitcrazed here: https://github.com/Microsoft/BashOnWindows/issues/279#issuecomment-215548501, but still worth  tracking because it's super annoying

**Comment by fpqc** [comment]
Hi Pavel, not positive if this problem will be fixed by this, but have you tried running your bash in a VTerm running through an XServer?  I wrote up a step-by-step tutorial on how to do this with XMing and rxvt-unicode-256color https://github.com/Microsoft/BashOnWindows/issues/531

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue has likely been fixed since it was filed
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
