### ISSUE TITLE
WSL2: Strange wsl command execution context

### ISSUE THREAD

**Issue by whitecolor** [microsoft/WSL#5801]
```
D:\Code\chartify>wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```
I 'm running the same conmmand `node --version` using `wsl` and within `wsl` and get different results. Seem like `wsl [cmd]` is run in some different context, not default distro. It is not very expected.
```
D:\Code\chartify>wsl node --version
v10.19.0

D:\Code\chartify>wsl
alexo@WHITECOLOR-PC:/mnt/d/Code/chartify$
--> node --version
v12.18.3
alexo@WHITECOLOR-PC:/mnt/d/Code/chartify$
-->
```
![image](https://user-images.githubusercontent.com/736697/91062528-418bc680-e646-11ea-8f26-e8fa584064e8.png)

**Comment by therealkenc** [comment]
> `D:\Code\chartify>wsl node --version`

Very likely, you've installed `nvm` as an unstated part of the repro. That command above is not an interactive shell. Therefore, the `node` found was not the one in your `$HOME/.nvm/...` path component added by your `.bashrc`, because your `.bashrc` was never fired.

If you wanted equivalence, it would look like:

```
D:\> wsl.exe /bin/bash -ic 'node --version'
```

Whatever the specifics, this is Linux-behavior. The `node` that gets executed is the first one in your `$PATH`. You would get the same behavior with `ssh you@somelinuxbox node --version`.

![image](https://user-images.githubusercontent.com/7049700/91104825-6b7fc180-e623-11ea-9e9c-89857bd8e9f7.png)

**Comment by whitecolor** [comment]
@therealkenc 
Thanks! That's what I needed. Couldn't find this in docs.
