### ISSUE TITLE
When entering UNIX user/pass on debian and powershell it won't let me type in passwd after i type in username

### ISSUE THREAD

**Issue by cuckatoo67** [microsoft/WSL#5820]
# Environment

```none
Windows build number: [run `[OSVersion]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian]
Whether the issue is on WSL 2 and/or WSL 1: [WSL 1]
```

# Steps to reproduce

Download Debian, and install. Then enter UNIX User/Pass. 

**WSL logs**: 

#  Expected behavior

to allow me to enter password

# Actual behavior

WHen i go to enter Password after debian asks me to enter a UNIX password, it freezes up and only let me hit the enter key, resulting in a password incorrect

**Comment by therealkenc** [comment]
Have to assume after "freezes up and only let me hit the enter key" you closed the window (because there wouldn't be a lot of other options). Since you made it to the enter password prompt, your distro is probably installed. Post the output of `wsl.exe -l -d` to confirm. If Debian is listed, you can enter your distro with `wsl.exe -u root` (or `wsl.exe -d Debian -u root`). If you get a root prompt (looks like `#` at the bash prompt), then set up a user after the fact with [`adduser(8)`](https://manpages.debian.org/buster/adduser/adduser.8.en.html).
