### ISSUE TITLE
Access WslGetDistributionConfiguration from Managed Code returns E_ACCESSDENIED 

### ISSUE THREAD

**Issue by creizlein** [microsoft/WSL#5824]
# Environment

```none
Windows build number: Version 10.0.19041.450
Your Distribution version: n/a.
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

**WSL logs**: None needed

I am trying to implement WslGetDistributionConfiguration API function from wslapi and keep getting E_ACCESSDENIED 
Currently I am using .NET managed code to call , either from C# and VB.net i get the same results

```none
 <DllImport("wslapi.dll", SetLastError:=True, CharSet:=CharSet.Unicode)>
  Shared Function WslGetDistributionConfiguration(ByVal distributionName As String, ByRef distributionVersion As ULong, ByRef defaultUID As ULong, ByRef wslDistributionFlags As WSL_DISTRIBUTION_FLAGS, ByRef defaultEnvironmentVariables As String, ByRef defaultEnvironmentVariableCount As ULong) As UInteger
  End Function

  <Flags()> Enum WSL_DISTRIBUTION_FLAGS As UInteger
    WSL_DISTRIBUTION_FLAGS_NONE = 0                  ' No flags are being supplied.
    WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP = 1        ' Allow the distribution to interoperate with Windows processes (for example, the user can invoke "cmd.exe" or "notepad.exe" from within a WSL session).
    WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH = 2        ' Add the Windows %PATH% environment variable values to WSL sessions.
    WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING = 3 ' Automatically mount Windows drives inside of WSL sessions (for example, "C:" will be available under "/mnt/c").
  End Enum
```

Would like to know if this is a know issue or if there is any implementation of this API that works properly.

I am following the documentation from: https://docs.microsoft.com/en-us/windows/win32/api/wslapi/nf-wslapi-wslgetdistributionconfiguration

#  Expected behavior

Function returns proper S_OK

# Actual behavior

Function returns error HRESULT =  E_ACCESSDENIED | General access denied error | 0x80070005

**Comment by licanhua** [comment]
You missed the undocumented CoInitializeSecurity!
You can find it's C# version [here](https://www.pinvoke.net/default.aspx/ole32/CoInitializeSecurity.html)
Because CoInitializeSecurity can only be initialized once, that means you need to set it in the earliest initialization of your application. If it's WPF application, you can set it in [App::App](https://stackoverflow.com/questions/46405530/how-do-i-call-coinitializesecurity-before-an-c-sharp-application-to-deactivate/63362503#63362503)

C# example:
```
      CoInitializeSecurity(IntPtr.Zero, -1, IntPtr.Zero, IntPtr.Zero, RpcAuthnLevel.Default, RpcImpLevel.Impersonate, IntPtr.Zero, EoAuthnCap.StaticCloaking, IntPtr.Zero);
```

Here is the C++ example.
```
CoInitializeSecurity(nullptr,
                                         -1,
                                         nullptr,
                                         nullptr,
                                         RPC_C_AUTHN_LEVEL_DEFAULT,
                                         RPC_C_IMP_LEVEL_IMPERSONATE,
                                         NULL,
                                         EOAC_STATIC_CLOAKING,
                                         0));
```

**Comment by licanhua** [comment]
The reason for that is lxss manager is a service, and the wslapi will access lxss manager via COM. In lxss service, it used impersonate token to get user's configurations. C# initialized the security without IMPERSONATE flag, so it doesn't work.
If you want to know more, please refer [security in COM](https://docs.microsoft.com/en-us/windows/win32/com/security-in-com). (actually I spent half an day to read the document, but I still confused.)

**Comment by creizlein** [comment]
Wow, thanks a lot for your replay and the details, I clearly missed that, big time!
You were very kind in taking the time to address, I will play around with that and implement the CoInitializeSecurity on my code and give it a shoot!

Regards

I need a few hours to test this out, maybe i can close the report tomorrow instead? otherwise just please feel free to close !

**Comment by therealkenc** [comment]
Probably the short answer to latent #4058 too.

**Comment by licanhua** [comment]
@creizlein does it work?

**Comment by creizlein** [comment]
I wasn't able to make it work but I believe it could be my fault, clearly its not easy to invoke CoInitializeSecurity from managed code as I read through the documents provided and I keep getting access denied.

Nonetheless, WslGetDistributionConfiguration does not return if a Distro is running or not (the state) which is one of the main reason i was looking for it, the rest of the information could be queried directly from the Registry which seems easier (unfortunately). 

Thanks for the help Licanhua anyway, you really helped me a lot here by finding the root cause. 
I guess we can close the issue as it doesn't seem to be a bug but rather some functional restriction.

**Comment by licanhua** [comment]
Can you create an sample C# app? It's possible for us to improve the interface for C#, and I want to know what kind of app will have problem. I tried wpf app before and I didn't see any problem.

**Comment by creizlein** [comment]
licanhua, I am currently using VB app as a simple exercise to list WSL distros and their properties (was hopping to list Running State as well) But I doubt VB.net code is any help as an example of this?

However if it helps and will be valued I can just port this simple demo into C# and share its code, basically just populates a Listview control with the details of each distro.

Do let me know, I can put it together in either language as needed. all trough I'm no C# expert.

Besides that, further research on the CoInitializeSecurity function revealed that .net managed app already calls CoInitializeSecurity when it starts so a subsequent second call made no different and returned value 0, thus making WslGetDistributionConfiguration still with access denied.

**Comment by licanhua** [comment]
I create a simple C# console app, and you can build it with x64 configuration, and I didn't see problem.
https://pastebin.com/98AnCbst

**Comment by therealkenc** [comment]
[Beat me](https://gist.github.com/therealkenc/15575525957b59f3f93d556a53544850) by 8 minutes. I should have had dinner. Seems to take here.

**Comment by creizlein** [comment]
> I create a simple C# console app, and you can build it with x64 configuration, and I didn't see problem.
> https://pastebin.com/98AnCbst

Indeed i confirm the code works, clearly the problem seems to be either from the VB port or some kind of the host process running it.
What is more strange is that if i comment out the CoInitializeSecurity call the program still function...

**Comment by licanhua** [comment]
I did the testing on 19041 os:
1. C# console app works fine with/without CoInitializeSecurity 
2. ACCESSDENIED for WPF app with/without CoInitializeSecurity 
3. Below description is not acute. CoInitializeSecurity is not called for console and wpf app in my testing. `You shouldn't call CoInitializeSecurity from managed code. That's because the CLR will almost always call CoInitialize upon startup before execution enters your main method, and CoInitialize will implicitly call CoInitializeSecurity if it hasn't already been called. Therefore, calling this from managed code will usually return RPC_E_TOO_LATE.`

I think we may not use CoInitializeSecurity in lxssmanager and wsl correctly.

**Comment by therealkenc** [comment]
> ACCESSDENIED for WPF app with/without CoInitializeSecurity

Mine was a WPF application, run on 20201, for what it is worth. Ran okay. Difference 19041 ➡️ 20201 seems unlikely, but possible I suppose.

![image](https://user-images.githubusercontent.com/7049700/92021326-71a22c00-ed0e-11ea-8e25-fe392745e504.png)

**Comment by creizlein** [comment]
Interestingly enough, I used the exact same code on a WinForm app and it doesn't work, regardless I call CoInitializeSecurity or not, the WslGetDistributionConfiguration returns  E_ACCESSDENIED 
btw, i am using 19041 here

Seems that the Console application run differently and maybe it doesn't call himself the CoInitializeSecurity stated earlier, so it can be used with WslGetDistributionConfiguration , but either a WPF or WinForm can't.

https://pastebin.com/X3dynyN2

I also confirmed the same behaviour on VB.net, in a Console app the interop to WslGetDistributionConfiguration  works properly but not in a WinForm, no matter we use CoInitializeSecurity or not.

**Comment by therealkenc** [comment]
You are missing `CharSet = CharSet.Unicode`, which will result in 0x80040302. And maybe else.

**Comment by creizlein** [comment]
You are totally correct, I apologize, setting the Unicode Charset resolved the issue on the WinForm app.

**Comment by creizlein** [comment]
Update: this might sound really, really weird, but i was also able to make it work on VB.net WinForm app, the problem was that I had to make a call to WslGetDistributionConfiguration on the Load event, If i do that, then the future calls to WslGetDistributionConfiguration work properly and the flow goes on.
If on the other hand I DO NOT call WslGetDistributionConfiguration  on Load then no matter what I do the function returns error, despite a previous call to CoInitializeSecurity 

This behavior doesn't seem to happen on C#, i was not able to reproduce it, but for VB.net (few ppl will care) you just make a dummy empty call to WslGetDistributionConfiguration on Load and then it will work properly. Which is weird, but might have to do with InitializeSecurity settings clearly.

**Comment by rkttu** [comment]
Maybe this is not an optimal solution (because it involves another process creation inevitably); however, I'm posting here because I think it's worth mentioning.

I created an out-of-process style WSL API wrapper for addressing this issue. If you have interested in this code, please look out for the sample code. Any kind of contribution is welcome.

Recently, I recovered an out-of-process COM server sample code from the All-in-one Code framework in the codeplex.com archive. (which was ancient open-source storage managed by Microsoft)

Then I thought the sample code could help resolve the CoInitializeSecurity issue because the process is apart from the client process. API client gets a stub of the actual COM server, so the CoInitializeSecurity will not bother. Also, when the COM server is called the first time, the server launches automatically, and the server calculates the reference count. If it reaches zero, the process will automatically close.

https://github.com/wslhub/wsl-sdk-com
