### ISSUE TITLE
Don't always scroll to bottom when there is new output in console

### ISSUE THREAD

**Issue by heberallred** [Microsoft/WSL#584]
I'm using this with NodeJS & Meteor.  Currently when there is output to the console, Bash is scrolling to the bottom regardless of whether I have scrolled up to look at previous output.  On my Mac, if I scroll up to look at some previous output, it stops scrolling to bottom when there is new output, allowing me to read through previously output information easily.  Then if I scroll back to the bottom, it will "follow" the new output and stays scrolled to the bottom automatically.

Please make it work similar to how I have described on Mac.  Currently in Bash for Windows, it's very hard to scroll back in the console output and look at previous data since it scrolls to the bottom automatically when there is new output.

**Comment by fpqc** [comment]
This is not a problem with BashOnWindows. It is a console problem, since bash.exe runs like other Windows console apps in the Windows Console Host (conhost.exe).  The upgrades to conhost are planned, but they will not release for the anniversary upgrade in July, and the Windows team is scrambling for the July 30 deadline to actually get what _is_ planned ready by then.  

So in the meantime, I described a nice off-the-shelf workaround  using a Windows Xserver (XMing) and a nice XTerm replacement (rxvt-unicode-256color) that should hold you over until the Console team starts rolling out their planned console upgrades : https://github.com/Microsoft/BashOnWindows/issues/531

**Comment by Sheco** [comment]
BashOnWindows is great, I have always wanted Microsoft to work on updating the console, which has been for such a long time, such an outdated piece of software.

I am glad this project is pushing them to update that.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and has likely been fixed since it was opened. If not, please post a new issue in the [Console GitHub Repo](https://github.com/Microsoft/console)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
