### ISSUE TITLE
Unexpected behavior when running RethinkDB with bind=all

### ISSUE THREAD

**Issue by Baterka** [microsoft/WSL#5844]
**Describe the bug**
When I start RethinkDB service (https://github.com/rethinkdb/rethinkdb) in WSL2 with `bind=all` in the config, service is not accessible from Windows Host with error: `ReqlDriverError: None of the pools have an opened connection and failed to open a new one.`

Not tested on other services. Seems like there is some unexpected behavior when running some service on all interfaces.

**To Reproduce**
1. Install WSL2 on Windows machine
2. Install RethinkDB (https://github.com/rethinkdb/rethinkdb)
3. Set `bind=all` in the config of RethinkDB
4. Start service
5. Try to connect to the server from Windows host (With for example NodeJS module `rethinkdbdash`)

**Expected behavior**
Should connect successfully.

**System info**
 - OS: Windows 10 2004 (Build 19041.450) with latest WSL2 (Debian 9, latest kernel)
 - RethinkDB Version: 2.4.1~0buster (CLANG 7.0.1 (tags/RELEASE_701/final))

**Additional context**
Related issue on RethinkDB: https://github.com/rethinkdb/rethinkdb/issues/6914

If I remove `bind=all` from config it works fine. Seems like there is some unexpected behavior when running on all interfaces in WSL2

**Comment by therealkenc** [comment]
If in step 5 (or step 2) you've got the the string 'localhost' or '127.0.0.1' in the mix, evens you're looking at a variation of #5706. Have a look at `netstat -nl` (Linux side) and `netstat.exe /an` (Windows side) and see what address the RethinkDB port (29015?) is listening. Could possibly coerce a look-see with CLI repro steps.

**Comment by therealkenc** [comment]
/dupe #4851 #5298

![image](https://user-images.githubusercontent.com/7049700/92146766-08362200-edcf-11ea-89a7-3992123f84ad.png)

**Comment by Baterka** [comment]
> ![image](https://user-images.githubusercontent.com/7049700/92146766-08362200-edcf-11ea-89a7-3992123f84ad.png)

The problem is that 8080 works fine and I am able to access RethinkDB admin panel from host by "localhost:8080" url, but I am unable to connect to 28015 server by any driver.

**Comment by therealkenc** [comment]
You need to (a) get (quoth) "any driver" to use ipv6 or (b) get RethinkDB to listen on ipv4.

You can oftentimes achieve (a) with [`avahi-daemon(8)`](http://manpages.ubuntu.com/manpages/cosmic/man8/avahi-daemon.8.html) per earlier cited #5706, since it will cough up an ipv6 address given a name, if it is asked nicely. Looks something like: `sudo service dbus start` and `sudo service avahi-daemon start`, after editing `/etc/avahi/avahi-daemon.conf`.

**Comment by therealkenc** [comment]
Was mildly enough curious to see if `avahi-daemon` would take in the scenario, and it does. I needed to [configure](http://manpages.ubuntu.com/manpages/cosmic/man5/avahi-daemon.conf.5.html) with `ipv4=no` and `ipv6=yes`.

```
server = 'wsl.local';
addr = '';
require('dns').lookup(server, (err, address, family) => {
    addr = address;
});

r = require('rethinkdb')
conn = r.connect({ host: 'wsl.local', port: 28015 }, (err, conn) => {
  if(err) {
      console.log(err);
      throw err;
  }
  console.log('connected to', server, 'on', addr);
  // r.db('test').tableDrop("foo").run(conn);
  tables = r.dbList().run(conn).then((list) => {
    console.log(list);
  });
});
```

![image](https://user-images.githubusercontent.com/7049700/92166164-067b5700-eded-11ea-8572-af9c27d503ff.png)
<br>

You're effectively hitting rethinkdb/rethinkdb#1897 ([message](https://github.com/rethinkdb/rethinkdb/issues/1897#issuecomment-217550480) and [message](https://github.com/rethinkdb/rethinkdb/issues/1897#issuecomment-33098111)). Which like it says over there "[will] usually work for both IPv4 as well as IPv6 interfaces, despite the fact that they are being listed as tcp6". We're not in the "usually" club because #5706.
