### ISSUE TITLE
Commands do not extend past a single line and override themselves. 

### ISSUE THREAD

**Issue by rfaile313** [microsoft/WSL#5865]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.19041.450] but also tested on 1909 and 2004
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Ubuntu  18.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
Tested on both WSL1 and WSL2 
```

# Steps to reproduce

Multi line commands in WSL 1 and 2, whether they're typed or pasted, do not go past a single line, they simply overwrite the previous line. This makes it extremely difficult to double check multi line commands or anything going over a single line.

Facts:

1. This issue occurs in Windows Terminal, CMD, and the "Ubuntu App itself" - I believe this to be unrelated to the terminal emulator.
2. This issue **only** happens in WSL. Powershell and CMD extend to multiple lines as expected, both in Windows Terminal and in their respective "CMD" and "Powershell" applications.
3. This issue extends outside of the local environment, for example, if I SSH into another server. 

Here is a video of the issue in both windows terminal and CMD:

https://d.pr/i/watzNA

**WSL logs**: 

Submitted using "Feedback Hub"

#  Expected behavior

I expect commands that are more than a single line long, or width of the terminal to extend to as many lines as they require instead of continuously overwriting the single line

# Actual behavior

Any text that is longer than the width of the terminal overrides the same, single, current line. 

I cannot recreate this behavior in any other Unix environment, also tested on MacOS Catalina and Ubuntu Desktop 18.04 LTS

cc @craigloewen-msft

**Comment by therealkenc** [comment]
WSL does not control how characters are wrapped in your terminal.

Wild guess, your `$PS1` is borked (it is not the default given the hot purple). As an experiment, do:
```
$ export PS1='$'
```

Then do the 'ddddd....' thing, and see if it wraps. Looks like (note the understated `$` on the left):
![image](https://user-images.githubusercontent.com/7049700/92338839-c7a50580-f067-11ea-8983-0598ccc2d72a.png)


> I believe this to be unrelated to the terminal emulator.
> This issue extends outside of the local environment, for example, if I SSH into another server.

You're right, if you are seeing the same behavior with `ssh` in from a known terminal emulator (like `gnome-terminal`). The problem is from your userspace userspace. Best guess at what was the idea above. Thanks for the motion gif, that went a long way towards making the guess.

If it isn't `$PS`, you can take more drastic measures like `sudo adduser testuser`, exit shell, and then enter with `wsl.exe -d Ubuntu-18.04 -u testuser`. That will ensure you've got a clean user environment.

**Comment by rfaile313** [comment]
Thanks for the response! I will look into this and get back to you with the results. I would be surprised if it were the PS1, but stranger things have happened :)

**Comment by rfaile313** [comment]
@therealkenc that was it 🤦‍♂️, not sure how that happened. Thanks for the quick, detailed, and correct response. Much appreciated!!

**Comment by rfaile313** [comment]
For posterity, an improperly escaped color in my PS1 variable was the culprit :'( 

**https://stackoverflow.com/questions/342093/ps1-line-wrapping-with-colours-problem**
