### ISSUE TITLE
in some cases, mc displays with tiny bugs

### ISSUE THREAD

**Issue by xilun** [Microsoft/WSL#599]
See the areas circled in red in this screenshot:

![mc_display_bug](https://cloud.githubusercontent.com/assets/6464553/16467598/553c82aa-3e48-11e6-9686-012ebf8997c3.png)

**Comment by fpqc** [comment]
@xilun Is this replicated in urxvt?  That would be a good way to determine if it is a console problem or a WSL one.

**Comment by xilun** [comment]
Looks ok in rxvt:

![mc_urxvt](https://cloud.githubusercontent.com/assets/6464553/16467997/38b14114-3e4a-11e6-9137-078bd087b5e2.png)

**Comment by aliceinwire** [comment]
is maybe a character encoding problem ?

**Comment by xilun** [comment]
This seems to be fixed in 14946 (and maybe even before)
(Bug was present in the AU release)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This is an old bug and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
