### ISSUE TITLE
login.microsoftonline.com is not resolved in WSL

### ISSUE THREAD

**Issue by jloaiza** [microsoft/WSL#5991]
# Environment

**Windows build number:** 
Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

**Your Distribution version:**
Ubuntu 20.04

**Whether the issue is on WSL 2 and/or WSL 1:**
WSL1
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020

# Steps to reproduce

In a fresh installed Ubuntu 20.04
```bash
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install -y apt-transport-https lsb-release gnupg curl
```
Then the following command gives the error
```bash
$ nslookup login.microsoftonline.com
;; Truncated, retrying in TCP mode.
;; Connection to fec0:0:0:ffff::1#53(fec0:0:0:ffff::1) for login.microsoftonline.com failed: connection refused.
```
Change the `/etc/resolv.conf` and add google ones 8.8.8.8 and 8.8.8.4. Try again the `nslookup` to that specific domain it will work.

```bash
$ nslookup login.microsoftonline.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
login.microsoftonline.com       canonical name = a.privatelink.msidentity.com.
a.privatelink.msidentity.com    canonical name = prda.aadg.msidentity.com.
prda.aadg.msidentity.com        canonical name = www.tm.a.prd.aadg.trafficmanager.net.
www.tm.a.prd.aadg.trafficmanager.net    canonical name = san.current.a.prd.aadg.trafficmanager.net.
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.67
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.72
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.68
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.73
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.71
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.70
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.66
Name:   san.current.a.prd.aadg.trafficmanager.net
Address: 40.126.0.74
```

Change the Windows DNS settings to the google ones too. Try the `nslookup` again and it will fail.

```bash
$ nslookup login.microsoftonline.com
;; Truncated, retrying in TCP mode.
;; Connection to fec0:0:0:ffff::1#53(fec0:0:0:ffff::1) for login.microsoftonline.com failed: connection refused.
```
It only fails for this domain as far as I've seen and only when the DNS servers are the same in Linux and Windows.

#  Expected behavior

The WSL should successfully resolve the domain without changing the `resolv.conf ` file, using the same DNS configured in windows.

# Actual behavior

The WSL can't resolve the domain.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows. Any insight on what `/etc/resolv.conf` was pointing at before you changed it to eights would also be useful. It is returning ipv6 addresses.

**Comment by jloaiza** [comment]
Thanks for the answer! The thing about the logs is that I can't see what is been collected and this is happening on my corporate machine so I have to be careful with the information that is posted. Do you know a way to review the log information before publishing it?

About third party applications, I have installed Cisco AnyConnect for the VPN (but the problem happens out of the VPN) and McAfee as anti-virus. I can't identify any other software but as I said, this is my work PC so it might have something else.

This is my `resolv.conf` content before the change:
```conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 190.113.97.11
nameserver 190.171.96.10
nameserver fec0:0:0:ffff::1
```

**Comment by mankuuuuu** [comment]
The workaround is to remove auto generated values by WSL in /etc/resolv.conf and adding google NS.


```\# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 8.8.8.8
```

**Comment by n0-0x01** [comment]
Bit old but I think I know why this happens as I ran into this issue today. This was in Kali Linux and not using WSL. The DNS response for login.microsoftonline.com is too large to fit into the DNS UDP packet. Because the original RFC (before eDNS) limited the packet size to 512 bytes. You can see that nslookup shows the UDP response was truncated, so it fails over to use TCP.

└─$ nslookup login.microsoftonline.com
;; Truncated, retrying in TCP mode.

I was using network manager for DNS (default in Kali). I changed over to systemd-resolved and it fails over to TCP just fine now.

**Comment by jiasli** [comment]
This could be related to https://github.com/microsoft/WSL/issues/5256

**Comment by sevenam** [comment]
This happened to me when running a vscode dev container through Docker and WSL2. `/etc/resolv.conf` was showing the Docker internal DNS server (?): 127.0.0.11. Changing this to any other DNS server (1.1.1.1 or 8.8.8.8) fixed the issue for me. The comment from @n0-0x01 put me on the right track. Thank you!

**Comment by mikkorantalainen** [comment]
Is this issue supposed to be fixed for real? I'm running Linux servers on bare metal and I get random DNS timeouts (we have 5 second timeout for resolving the DNS name) when trying to resolve `login.microsoftonline.com`. As such, this issue seems wider than just WSL and it causes random failures for the OpenID Connect protocol documented here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc which requires connecting to login.microsoftonline.com to validate the ID token.

I'm not aware of any other DNS failures at the same time so this is specifically about resolving domain `login.microsoftonline.com`.
