### ISSUE TITLE
Bash.exe not opening in Powershell

### ISSUE THREAD

**Issue by Luukv93** [microsoft/WSL#6024]
## Environment

Windows version: 10.0.19041.508
Ubuntu distribution: 20.04
Issue is on WSL2

## Problem
I can't run ```bash.exe``` in Powershell, it just doesn't run nor produce an error.
Is there anything I could do make this work?

## What I tried to resolve the issue
I tried running ```lxrun.exe /uninstall /full``` but I get the following error ```'lxrun.exe' is not recognized as an internal or external command, operable program or batch file.```

**Comment by therealkenc** [comment]
Same (or similar) symptoms as #5711. `lxrun.exe` has been deprecated and no longer exists. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. What is the output of `wsl.exe -l -v`? Does your distro start with `wsl.exe` (or `wsl.exe -d <distro-name>`)?

**Comment by Luukv93** [comment]
backlink: https://aka.ms/AA9vt32

Output of  ```wsl.exe -l -v```` is ```  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2```

Distro starts with ```wsl.exe```

**Comment by therealkenc** [comment]
Thanks for the logs, very appreciated. Can you post a screencap (win-shift-S) of the `wsl -l -v`; the markdown formatting confuses the output above. If no distributions are listed other than `docker-desktop-data` that would definitely be out of place. Also to test a hypothesis, can you open an Administrator Powershell and do the same `wsl -l -v` with a screencap if the output is different. [Or, if your Powershell was already Admin in the run above, then the reverse, as non-Admin.]

**Comment by Luukv93** [comment]
Hi, see image here below. Output is the same for administrator and non-administrator

![image](https://user-images.githubusercontent.com/53313345/95314085-293bd800-0891-11eb-9e68-cbdc250b916c.png)

**Comment by Luukv93** [comment]
Hi @therealkenc 
Any idea on what I'm doing wrong?

**Comment by therealkenc** [comment]
You aren't doing anything wrong. The `bash.exe` program is has been deprecated; use `wsl.exe`. What steps led to there being no distributions returned by `wsl -l -v` I don't know. Your best hope there is some other folks hitting the same problem and your OP gets upvotes. 

As for the distro being missing from the list, you can try installing a fresh one from the Store. Whatever distro is in your Start menu, pick a different one. So for example, if you installed [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab), install [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab) instead. Back up anything critical from your existing distro with [`tar(1)`](https://man7.org/linux/man-pages/man1/tar.1.html) inside a WSL and copy the tarball to `/mnt/c/somewhere`. There is a nonzero chance the install will run into difficulties because _something_ is in an inconsistent state. Or, just continue along with `wsl.exe` if that is otherwise working for you.
