### ISSUE TITLE
fish repeated prompt

### ISSUE THREAD

**Issue by antoniocanas** [Microsoft/WSL#604]
Installed fish shell, using pure/simple prompts or any that have a line before the prompt (showing directory/git status...).

While typing it repeat the prompt like this:

![image](http://g.recordit.co/M5IG1Gu9uh.gif)

**Comment by fpqc** [comment]
This is another console problem. I tested in urxvt and could not replicate and could replicate in Windows console.

**Comment by antoniocanas** [comment]
Also happening in conemu

**Comment by fpqc** [comment]
@antoniocanas yes conemu either runs conhost directly or has identical output to conhost, not sure exactly although @maximus5 posts here from time to time and will correct me I am sure.

**Comment by Maximus5** [comment]
Sure, ConEmu has conhost undercover.

Also, may be related: https://github.com/fish-shell/fish-shell/issues/789

AFAIK fish prints each one prompt two times.

**Comment by zadjii-msft** [comment]
Okay, this looks to me like fish is trying to move the cursor back to the start of the prompt line to redraw the prompt and the new input, and doesn't move back up one line to redraw over the old text. 

Does someone know which sequence fish is using to move back to the start of the prompt? That would make it easier for me to debug this quickly. About a month ago we added support for another cursor positioning sequence that I'm not sure if it's out to insider's yet.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
