### ISSUE TITLE
"Error" when installing Ubuntu through Microsoft store.

### ISSUE THREAD

**Issue by jessebobrien** [microsoft/WSL#6043]
The Windows Store doesn't provide any further details, it only shows, "error" after a brief download. Retrying the install produces the same result. Win10 Pro 10.0.19041 Build 19041

**Comment by craigloewen-msft** [comment]
Please use the issue template, it's there to help us be able to fix your problems! I'm closing this issue out since there isn't a template for us to go off of. From your description it seems like the error seems to be related to the Microsoft Store, I'd try and verify if you could download any other store apps or different distributions.
