### ISSUE TITLE
WSL 2 uninstalled itself

### ISSUE THREAD

**Issue by Polda18** [microsoft/WSL#6059]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20226.1000]
Your Distribution version: Linux Ubuntu (cannot post exact version)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (as I installed it after I upgraded to Windows Insider)
```

# Steps to reproduce

Well, I installed some updates and while I didn't use the WSL much, I definitely was able to at least see that Linux was still installed like just few days ago (although, I was unable to launch the Linux terminal inside Windows Terminal app). Now I tried it again to see that Linux has disappeared and was replaced with Microsoft Azure Cloud Shell (that thing definitely wasn't there before). I still can run WSL directly, but it doesn't do anything. I think I have lost my Ubuntu installation somehow.

**WSL logs**: 
None, or I cannot retrieve them somehow (or don't know about them).

#  Expected behavior
Start up Linux shell.

# Actual behavior
Does nothing.

**Comment by licanhua** [comment]
what's the output of `wsl -l -v`. 
1, if you see Ubuntu is in the list, then you can try to install small distro like Debian to make sure WSL 2 is fine on your machine.
2. if you didn't see Ubuntu, backup the folder(my distro is Ubuntu20.04) like `C:\Users\your\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState`, then install the distro again, then recover the LocalState.

**Comment by Polda18** [comment]
Calling `wsl` just hangs the process. So I literally have no idea.
![image](https://user-images.githubusercontent.com/25118993/95520397-820d8c80-09c7-11eb-8bc9-a188658b898d.png)
Might as well need to reinstall WSL with the Ubuntu distro all together.

**Comment by licanhua** [comment]
We don't know what's the problem until [collect-wsl-logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by Polda18** [comment]
I accidentally sent bug report in wrong category. The thing is that I have Windows in Czech language, that makes it more difficult to pick the correct category sometimes. Now I have to wait until data collection is available again :(

**Comment by Polda18** [comment]
Okay, sent.

**Comment by licanhua** [comment]
I saw the two logs you submitted, but I didn't find anything interesting in WSL.
There is no crash in the logs, so there is no issue I know may link to your issue.

You can first check if lxssmanager service is running, if not, start it.
if yes, try to restart it. I would expect it hangs there. 

If it hangs, I don't know what your problem is, so I just list some generic solutions:
1. limited resources on cpu, disk and memory. You can check it from task manager and likely you may hit problem if any of problem is too busy
2. Hyper-V problem introduced by Windows update. Sometime disable Virtual machine platform, reboot, then re-enable it may helps.
3. WSL itself. disable Windows subsystem for Linux feature, then enable it.
4. Hyper-V conflicts with VirtualBox or VMWare. I don't have experience on it, but I saw several cases user resolved WSL problem after they uninstalled VirtualBox/VMWare.

**Comment by Polda18** [comment]
Well, uninstalling VMware isn't and option for me since I use virtual machines with various OS, including Windows 98 and MS-DOS v6.22, and I actually have development version of VMware that supports Hyper-V.

The first 3 may actually help, so I'll try these out tomorrow.

**Comment by Polda18** [comment]
So I tried number 1 and 3. From number 1 I cannot clearly say that that's the issue since CPU doesn't seem to be busy with wsl running. It just stops midway and hangs. Number 3 - tried to disable it and reenable it again and same issue.

Well, here's one thing: If I run `wsl --set-default-version 2`, it actually performs the action without any issue:
```
PS C:\Users\Marek Poláček> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```

Anything else just hangs the process. Didn't try out the number 4 for obvious reason that I need VMware for other virtual machines (I have Windows 98, MS-DOS and Windows 2000 virtual machine with VMware), and also didn't try out number 2 because I can't remember how can I do that :(

**Comment by licanhua** [comment]
Try restart lxssmanager first from task manager.

![image](https://user-images.githubusercontent.com/6290692/96173793-3e41e800-0edd-11eb-95c1-38f5efde03f6.png)


number 2:
[turn off](https://www.isunshare.com/windows-10/turn-on-or-off-windows-features-in-windows-10.html#:~:text=%20Steps%20to%20turn%20on%2Foff%20Windows%20features%20in,10%20Turn%20Security%20and%20Maintenance%20Messages...%20More%20) feature Virtual Machine Platform, reboot the machine, turn on it, reboot the machine.

hang is because of lxssmanager, but `--set-default-version` doesn't use lxss service.

**Comment by Polda18** [comment]
Well, now it hangs on stopping 🤔

**Comment by Polda18** [comment]
I have found other issues on the service hanging on stopping as well (#1086 and #2933) and it does seem to be a bug in latest Insider Build snapshot. Still not fixed though... I don't know how can I fix it. As a workaround, I'll have to use Ubuntu virtual machine I installed in VMware until this is fixed.

**Comment by Polda18** [comment]
I might have found the culprit:
![image](https://user-images.githubusercontent.com/25118993/96180333-90f9bf00-0f32-11eb-8e64-3ebab0c15a15.png)

It seems that BOINC client I installed to help with projects development is holding the lxss processes.

**Comment by jsteenri** [comment]
Any advice on whether [suggestion 3 in this comment](https://github.com/microsoft/WSL/issues/6059#issuecomment-706327392) is safe with respect to existing data in WSL?

Also #4144 may be interest to those following this thread.

**Comment by johnaoss** [comment]
Had this too, issue seemingly resolved itself after several reboots over the course of a week or so.
