### ISSUE TITLE
Can't send or receive fragmented UDP packets

### ISSUE THREAD

**Issue by Insomniac66** [microsoft/WSL#6082]
# Environment

```none
Windows build number:                         10.0.19041.0
Your Distribution version:                    Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1:   WSL 2
```

# Steps to reproduce

I only ended up testing this issue with UDP and protocols based on it over IPv4.

1. Listen for incoming UDP packets on port `8080` on some external host using `nc -ul 8080`.
2. Open a socket to the external host inside WSL: `nc -u <remote address> 8080`
3. Send a long (> 1471 characters excluding the `\n`) line / packet from WSL (doesn't arrive at external)
4. Send a short line such as `test` from WSL to punch through the NAT for the next step (does arrive at external)
5. Send a long (as above) reply from the external host (doesn't arrive at WSL)

External host console:

```none
[user@hostname ~]$ nc -ul 8080
test
testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
^C
```
WSL console:
```
user@ubuntu:~$ nc -u <external host address redacted> 8080
testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
test
^C
```

If instead executed directly (outside of WSL) using a version of `nc` compiled for Windows, all packets arrive as expected.

**WSL logs**: Sadly I am not able to include logs due to Feedback being disabled.

#  Expected behavior

All packets are received at their respective destinations.

# Actual behavior

Long packets are dropped somewhere between the physical NIC and WSL. This appears to happen whenever the IP datagram would exceed 1500 bytes in size. This issue seems related to #4517, however the proposed solution of lowering the MTU on WSL doesn't work for UDP since it disregards the MTU entirely and I am not connected to a VPN or similar. Running `sudo tcpdump` under WSL will produce output similar to the following upon sending these packets:
```none
05:03:37.622552 IP 172.30.36.93.50284 > <external host redacted>.8080: UDP, bad length 1476 > 1472
```
Running Wireshark or `tcpdump` on the Windows host while receiving such long packets will show the fragmented package arriving, and Wireshark succeeds in displaying the reassembled UDP packet. Running `sudo tcpdump` in WSL produces no output related to the large packet.

![image](https://user-images.githubusercontent.com/35657048/95812304-5f57dc80-0d15-11eb-95ea-ca75a6aa3ebe.png)

**Comment by therealkenc** [comment]
Great analysis, thank-you. Was able to reproduce here. FWIW, Hyper-V with a bridged network is okay. Your step 3 can be quantified with something like the following, for (eg) 5000 'a' characters plus a newline:
```
$ printf '%*s\n' 5000 | tr ' ' a | nc -u 192.168.0.178 8080
```

> This issue seems related to #4517

It is almost certainly the cause of at least some percentage of people's `ssh` woes as well.

**Comment by hansolav** [comment]
Have experienced the same problem over a long period sending UDP packages from a container in Docker for Windows. This was a problem while running Docker on Hyper-V and still is a problem running Docker in WSL2. Between the Docker containers packages are sent and received correctly. Trying to receive packages from the Docker container at the Windows host, it seems like fragmented UDP packages exceeding MTU are dropped.

**Comment by xamix** [comment]
Experiencing the same problem here.
Any information on how/when this will be fixed?

I have a service which send stats by UDP and so it's unusable from inside the WSL...

**Comment by xamix** [comment]
Until this is fixed, I use `socat` to do UDP tunelling over TCP.
Install it on both server and client (WSL)
```
sudo apt install socat
```
In the following example I forward the 8094 UDP port to the remote server:
Log with SSH on the remote server and launch the following command:

```
socat TCP4-LISTEN:8094,fork UDP4:localhost:8094
```

Finally open a terminal on the local client machine (WSL) and execute the following command:

```
sudo socat UDP4-LISTEN:8094,fork TCP4:172.16.77.55:8094
```

Now on the local client machine (WSL) if you push with UDP on `localhost::8094` then all is redirected on the remote server via TCP

**Comment by JohnyGemityg** [comment]
Hi, I think it also affects TCP traffic through a VPN interface where is lower MTU.

![image](https://user-images.githubusercontent.com/3658238/114299440-7c4e4c00-9abb-11eb-9df6-76ed741fca6a.png)

I workaroud it by ip route change $DEFAULT_ROUTE advmss $ADVMSS. But it is annoying.

**Comment by Aaron-Hartwig** [comment]
This still does not work as of `Kernel version: 5.10.16`.

**Comment by kennethgjohnson** [comment]
Any ETA?

**Comment by KevinPoole** [comment]
This is a major bummer. Took a long time to figure out what was happening. Running `snmpbulkwalk` from within a WSL instance...
```
# Works
snmpbulkwalk -c public -v 2c -192.168.87.203

# Fails - results in fragmented UDP packets that can be seen on wireshark on host but are not routed back to WSL instance
snmpbulkwalk -c public -v 2c -C r1024 192.168.87.203
```

Any update on this?

**Comment by AntoineGlacet** [comment]
Have the same problem to send WakeOnLan (udp) packets from wsl... Will try the TCP routing workaround!

**Comment by gdumke** [comment]
As mentioned by **jstarks** [here](https://github.com/microsoft/WSL/issues/8610#issuecomment-1197053685), there's a workaround that might help you

**Comment by RobinTsai** [comment]
Same problem, waiting for solution.

**Comment by jnorell** [comment]
Just a note that the issue seems to that all fragmented packets from the wsl2 host are dropped; I first experienced it with icmp, confirmed with udp and also tcp.  An easy to reproduce case is to set the mtu in the WSL host lower, say to 1000; then send packets (icmp, udp or tcp) of size 900 and you will see them go through at various points in the network; then send the same packet of size 1100, so the WSL kernel fragments the packet, and it won't make it past the wsl interface to any other interface on the host nor to the network.

As everyone, would sure love a fix.  (I'll probably just switch to a vm, it makes WSL networking pretty flaky.)

**Comment by colinmcintosh** [comment]
It seems like this is still an active issue sending fragmented UDP packets from WSL2 in 2024. Could someone please re-open this issue. Wondering if there are any updates or plans to fix this?

**Comment by Kwisss** [comment]
still here.

**Comment by darsor** [comment]
This is still a major issue. Please re-open.

**Comment by asi-dh** [comment]
Confirming this is still broken as of **August 2026**, on a fully updated WSL2 (kernel `6.18.33.2-microsoft-standard-WSL2`, i.e. current after `wsl --update`). Updating the kernel does **not** fix it.

### Environment

```
Linux kernel: 6.18.33.2-microsoft-standard-WSL2 (Thu Jun 18 21:54:43 UTC 2026)
Distro:       Ubuntu 24.04.1 LTS (Noble)
.wslconfig:   networkingMode=mirrored
```

### Repro

Simple isolated socket test — a UDP "server" bound to a loopback address, and a client in the same WSL2 instance sending payloads of increasing size:

```python
import socket, threading, time

HOST, PORT = "127.0.0.1", 47654
sizes = [500, 1000, 1400, 1450, 1471, 1472, 1473, 1480, 1500, 2000, 4000, 9000, 16384, 30000, 65000]
received = {}

def server():
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((HOST, PORT))
    sock.settimeout(0.5)
    end = time.time() + 8
    while time.time() < end:
        try:
            data, _ = sock.recvfrom(65536)
            received[len(data)] = received.get(len(data), 0) + 1
        except socket.timeout:
            continue

threading.Thread(target=server, daemon=True).start()
time.sleep(0.3)

client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
for size in sizes:
    client.sendto(bytes([size % 256]) * size, (HOST, PORT))
    time.sleep(0.1)
time.sleep(1.5)

for size in sizes:
    print(size, "OK" if received.get(size, 0) else "DROPPED")
```

### Results on `127.0.0.1` (loopback)

| Payload size | Result |
|---|---|
| 500 – 1472 B | received |
| 1473 B and up (tested to 65000 B) | **silently dropped** — no error, no exception, no partial data |

Hard cliff at exactly 1472/1473 bytes, consistent with the vSwitch MTU discussed elsewhere in this thread. No packet in the 1473–65000 B range arrived, ever, across repeated runs.

### Real-world impact

Hit this while running a sensor-simulation pipeline entirely inside one WSL2 instance: a Python process streams ~30 KB UDP datagrams over `127.0.0.1` to a ROS2 C++ node doing a single `recv()` per datagram. Every datagram was silently dropped, manifesting as a downstream timeout with zero indication that the packets were even being sent — this is a nasty one to debug because both ends log correctly and there's no socket error anywhere in the chain to point at the real cause.

### Workaround that worked

Same two processes, same machine, only change: bind/send to the WSL2 instance's `eth0` address (assigned via `networkingMode=mirrored`, e.g. `192.168.x.x`) instead of `127.0.0.1`. Reran the identical size sweep above (500 B–65000 B) against that address — **every single packet arrived, including 65000 B**. So this looks specific to the loopback (`lo`) path through the Hyper-V vSwitch, not a general UDP/fragmentation limitation of the VM — traffic that actually traverses `eth0` handles fragmentation/reassembly correctly.

For anyone else stuck on this: if you can't avoid oversized single UDP datagrams and you're on WSL2 with mirrored networking, routing through the mirrored `eth0` address instead of `127.0.0.1` is a viable workaround (with the obvious caveats — that address isn't as stable as loopback and traffic becomes visible on the LAN).

Given people are still actively hitting this in 2025/2026 comments above, could this be reopened? It's not stale — it's unresolved.
