### ISSUE TITLE
Ethernet drivers blocked by windows 

### ISSUE THREAD

**Issue by Techno-Disaster** [microsoft/WSL#6212]
# Environment

```none
Windows build number: [Version 10.0.20251.1]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]  // None yet
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```
Update issue same as : #5911 
# Steps to reproduce

After enabling the Virtual Machine Platform feature with windows features or using the following command ```dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart```, after rebooting windows blocks my ethernet drivers with a Code 48. The exact error message is as follows: ```The Software For This Device Has Been Blocked From Starting Because it is Known To Have Problems With Windows’ Error on Windows (Code 48)``` . I have VT enabled in bios.  Ethernet Card: Realtek Gaming GbE Family Controller. 

**WSL logs**:  None

#  Expected behavior

I should be able to turn on virtual machine platform and the ethernet port should not break
# Actual behavior
After enabling the above feature, device manager says the code 48 message.

**Comment by MingLu8** [comment]
> /dupe #5911

Well, if you consider the issue is with "Windows Virtualization Platform", then I would agree it is an duplicate.  But if the issue is from Intel side then this issue about need an intel driver update for intel wireless card, where as the other issue is about needing an intel driver for intel ethernet card.
