### ISSUE TITLE
Rust compiler turns my computer off on WSL but not on windows

### ISSUE THREAD

**Issue by slymon99** [microsoft/WSL#6248]
# Environment

```none
Windows build number: 20257.1
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: 1
```

# Steps to reproduce

on either stable/nightly rust toolchain for ubuntu 18.04
```
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
```

create a project

`cargo new explode`

add any moderately sized dependency to the bottom of the Cargo.toml file e.g. reqwest

```
[dependencies]
reqwest = "0.10.8"
```

build the project
`cargo build`

or build on rust nightly
`cargo +nightly build`

**WSL logs**: Tried to follow the instructions, but I can't, as my computer turns off so I can't upload/submit. Let me know how I should get logs, happy to attach whatever you find useful. 

#  Expected behavior

cargo build compiles my project

# Actual behavior

My computer turns off

# Why is this a WSL issue?

I'm fairly confident this is a WSL issue as I can compile the exact same rust project from windows natively without my computer turning off. I assume the rust compiler is doing pretty hardcore parallelized compilation and doing a ton of temporary files and something is exploding with the virtualization of WSL. I'd be curious if someone could replicate my issue on another machine. 

I AM also able to compile the project from WSL2 w/ Ubuntu 20.04 (without my computer turning off).

The problem STILL persists with a different PSU, so I'm fairly confident it's not a hardware problem. Could be something weird with mobo or ram, but I have not found any stress test that causes a similar problem (and I've tried `stress`, prime95, f@h, etc).

**Comment by trallnag** [comment]
lol

**Comment by therealkenc** [comment]
There is a small but nonzero chance this is same #6869. It hard shutdown did not reproduce for me here.

![image](https://user-images.githubusercontent.com/7049700/117225754-ec54a700-adc7-11eb-8074-4695ca83cf96.png)

**Comment by slymon99** [comment]
I'm not encountering this issue on WSL2, but still can repro 100% of the time on WSL1. I know this seems like a strange result from WSL but I have never had a power issue in any other application and have even RMAd my PSU. Event viewer shows "kernel power 41" without much info. 

Happy to provide more repro info but my current solution is "don't use WSL1"

**Comment by therealkenc** [comment]
> I'm not encountering this issue on WSL2, but still can repro 100% of the time on WSL1

I can repro #6869 100% on WSL1 (but not WSL2) as well, which is enough anecdotal evidence for me. Your `[dependencies]` addition causes `cargo` to download stuff, which is at least spiritually similar to `gclient runhooks` doing its thing. Your hypothesis is pretty sound: If your PSU (or hardware in general) were the problem you'd have other grief besides WSL1.

What this one suffers is (a) there isn't much hope of getting logs when the box goes down hard without a bsod, and (much more problematically) there hasn't been a chorus of "WSL1 makes my machine turns off!" since you posted in November 2020. It's a shame your repro didn't take down my machine, in which case at least you wouldn't be alone.

> my current solution is "don't use WSL1"

You've found the right work-around, in the circumstance.
