### ISSUE TITLE
Vmmem using ~400MB without running nothing

### ISSUE THREAD

**Issue by validatedev** [microsoft/WSL#6252]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630]
Your Distribution version: Release: 11
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020 (WSL 2)
```

# Steps to reproduce

If I start a WSL2 instance, without running nothing, Vmmem process uses nearly 400MB. `free -h ` shows that the instance just using ~60MB.

**WSL logs**: 
https://aka.ms/AAad04j

#  Expected behavior

I expect some little overhead due to the structure of VM, but not that much. It should not be using that much RAM.

# Actual behavior
It uses ~300MB overhead.

**Comment by pmdpaula** [comment]
Same for me. And other problems after last update.

**Comment by PavelSosin-320** [comment]
Same for me. WSL never frees allocated memory. **This is memory leak**!

**Comment by ANR2ME** [comment]
This is probably related to the way Linux uses free memory as cache https://github.com/microsoft/WSL/issues/4166#issuecomment-641445502

Since the cache on guest OS (ie. Linux) can only be freed by the guest OS itself, the host OS (Windows) can't do anything about it (other than limiting how much memory a VM can use through `.wslconfig` file), that's why you'll be seeing `vmmem` memory usage to grow, even when not running anything on the guest OS.
