### ISSUE TITLE
Found a security vulnerability.

### ISSUE THREAD

**Issue by Krrishdhaneja** [microsoft/WSL#6254]
# Environment

```none
Windows build number: Windows 10.20257.1
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Yesterday when running command wsl -d Ubuntu-20.04 --user root, I thought that Ubuntu would be asking me for my password but what it did, just started it with the root user. This was really not what I thought.

#  Expected behavior

##### Expected password field when entering command ```wsl -d Ubuntu-20.04 --user root```
![image](https://user-images.githubusercontent.com/65185487/99521070-f15ca000-29b9-11eb-8512-1677f7ae9a2d.png)

# Actual behavior

**Comment by Biswa96** [comment]
> Found a security vulnerability

🤣 

> Ubuntu didn't ask for a password.

WSL is just like a virtual machine. A root user can not harm outside Windows system unless the WSL instance is launched as administrator.

**Comment by Krrishdhaneja** [comment]
I am not talking about windows, I am talking about WSL as it may contain some important information.

**Comment by DHowett** [comment]
The user security boundary for WSL stops at your _Windows user account_. If your Windows account is compromised to the point where somebody could _launch WSL and log in as `root`_, you already had a security problem long before WSL got involved.

**Comment by 0xbadfca11** [comment]
The fact that someone can launch the WSL for a distribution means that they can read and/or copy the ext4.vhdx that contains that distribution.
In that situation they can copy and take it away and mount it on their Linux, or open it with 7-Zip and copy the file from inside ext4.vhdx.
The root password is powerless in the situation you said.

**Comment by Krrishdhaneja** [comment]
For that purpose I opened this issue. Can't the WSL team change this and set password in this situation.

**Comment by Krrishdhaneja** [comment]
@DHowett I am concerning about WSL data. I am not concerning about Windows data.

**Comment by Krrishdhaneja** [comment]
Cuz some developers may have some important code in their WSL distro.

**Comment by craigloewen-msft** [comment]
Hi @Krrishdhaneja , as of right now, this is not a security vulnerability. We know about this behaviour, and we follow the same principles as a regular virtual machine, you have full access to the contents of the VM as a root user, and have full access to the contents of WSL distros. 

However, this is a request that we have heard before from Enterprises to help see if we could add a security surface here. I'm going to close this issue out, since this is not a security vulnerability, but your feedback definitely has been noted and I can tell you we are working on ways to help Enterprises address concerns like these! :)

**Comment by Krrishdhaneja** [comment]
Alright  @craigloewen-msft . Would be definitely waiting for that update.
