### ISSUE TITLE
Perl extensions in urxvt crash or freeze

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#630]
I have urxvt loading some standard perl scripts for clickable links, yet when I do actually click links, urxvt appears to freeze up, and the urxvtd process in the task manager shows as suspended.  

```
! Perl extensions
URxvt.perl-ext-common:      default,matcher
URxvt.matcher.button:       1
URxvt.urlLauncher:          links2
```

The same thing happens with choosing, for example, Firefox.  Is this a Perl problem, Xming problem, or WSL problem?

For the record, doing 
`links2 <url>`
and 
`firefox <url>`
both do correctly launch the url in the correct app.

Also, launching urxvt with the "kuake" perl extension simply quits it instantaneously.

**Comment by therealkenc** [comment]
@fpqc - maybe confirm your `urxvt` scenario works in April update. This one went chirping crickets two years ago.

**Comment by fpqc** [comment]
@therealkenc Oh I have not the foggiest idea of how I had it set up at the time. Since the WSLBridge came out, I have had no interest in running a native-through-X terminal emulator (vcxsrv has weird layer-ordering problems with the Windows layering system that makes quake-style functionality seriously broken).

I also went back into academia in October, so I have a lot less time to test these things while pretending to work… 😉

I've got it on my radar. I'll try to test it on a sleepless night or something.

**Comment by therealkenc** [comment]
> I've got it on my radar. I'll try to test it on a sleepless night or something.

Make it mostly _"or something"_. There's too good a chance it works now to take the effort, and there is an even better chance you are the only one who tried the "kuake perl extension" (whatever [that is](https://github.com/exg/rxvt-unicode/blob/master/src/perl/kuake)) with `urxvt` on WSL. 

The only reason I pinged you was (a) [mostly] because it was you, and (b) on the chance you knew whether `urxvt `perl extensions work now offhand. Closed by fiat is good enough for this one.
