### ISSUE TITLE
update wsl2. RPC The server is unavailable.

### ISSUE THREAD

**Issue by qxkbw** [microsoft/WSL#6326]
wsl --set-default-version 2
RPC The server is unavailable.

**Comment by licanhua** [comment]
There are some threads on it: #5164, #4433, #4474. Hopefully you may find a solution.
If not, please [collect wsl log](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by HunterAP23** [comment]
I don't mean to piggyback on qxkbw's specific issue, but I too have this problem when using Prvate Internet Access (PIA). Specifically it's a VPN, but when using PIA's DNS is when this issue occurs. I have tried unsuccessfully to whitelist any related WSL and distribution related executables from PIA, but the issue persists.

**Comment by rookie-eyes** [comment]
So from a little testing, I believe this is an issue directly with PIA's DNS server. I've tried this with both their DNS server and my own in order to try and mitigate the issue. Their's (PIA's) doesn't work with any of the WSL2 applications, if you switch this to your own or your router's default DNS the issue disappears. This runs a potential security risk in-of-itself, however does indeed give a workaround.
