### ISSUE TITLE
MTR doesn't work

### ISSUE THREAD

**Issue by aronchick** [microsoft/WSL#6331]
I'm running on the latest Windows / WSL.

When I run `mtr` i get:

```
$ sudo mtr 8.8.8.8
[sudo] password for ...:
mtr-packet: Failure to open IPv4 sockets: Permission denied
mtr-packet: Failure to open IPv6 sockets: Permission denied
mtr: Failure to start mtr-packet: Invalid argument
```

I've seen this (https://github.com/microsoft/WSL/issues/717) but I'm running under latest WSL2 and Ubuntu 20.04 and still nothing.

Any suggestions?

**Comment by therealkenc** [comment]
Please post screencap of the output of:
```
$ cat /proc/version
$ cd /mnt/c && cmd.exe /c ver
$ lsb_release -d
$ mtr --version
```

Would look something like:

![image](https://user-images.githubusercontent.com/7049700/102278362-88941500-3ede-11eb-8195-2b130704a435.png)

**Comment by aronchick** [comment]
Sure thing:
```
$ cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
$ cd /mnt/c && cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.685]
$ lsb_release -d
Description:    Ubuntu 20.04.1 LTS
$ mtr --version
mtr 0.93
$
```

**Comment by therealkenc** [comment]
> Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) )

That's WSL 1, making this dupe #717. `wsl --set-version Ubuntu 2`. Assuming `Ubuntu` is your distribution `NAME`, returned by wsl -l -v`. WSL2 looks my screencap (lowercase 'M' on 'microsoft').

**Comment by aronchick** [comment]
Oh interesting - I installed this two months ago, and have all the latest. The default is still WSL 1?

**Comment by therealkenc** [comment]
> The default is still WSL 1?

I think (?) the default is still WSL 1 on 19041, but don't quote me on it. There is no auto-upgrade to WSL 2 even if it becomes the default (or already is). Put another way, upgrading to latest Windows (Insider or otherwise) doesn't make WSL1 distributions already installed become WSL2. You can set the default with `wsl --set-defaut-version <Version>` but that applies only to future distribution installs. In recent Insiders (20262 or better), [`wsl.exe --install`](https://docs.microsoft.com/en-us/windows/wsl/install-win10) bumps the default to WSL2 by fiat. /dupe #717
