### ISSUE TITLE
VHDX corrupted after opening in Disk Management

### ISSUE THREAD

**Issue by Timic3** [microsoft/WSL#6377]
I wasn't sure where to ask for help, so I'm sorry if this isn't entirely the right place. Feel free to close the issue if it's too much "off-topic".

I just got a new PC and didn't know about `--export` and `--import`, so I just copied `ext4.vhdx` to the new disk and formatted the old one. I didn't backup the image because I thought Windows wasn't stupid enough to corrupt the image, so I just opened it in Disk Management (or well, double clicked), because I thought it could read EXT4 partitions - well this didn't end well since it seems like it corrupted the image.

So I spinned up my Debian VM and installed `libguestfs-tools` and did some research.

- Corrupted VHDX:
```
Name       Type       VFS  Label  MBR  Size          Parent
/dev/sda1  partition  -    -      -    16759808      /dev/sda
/dev/sda   device     -    -      -    274877906944  -
```

- Fresh VHDX:
```
Name      Type        VFS   Label  MBR  Size          Parent
/dev/sda  filesystem  ext4  -      -    274877906944  -
/dev/sda  device      -     -      -    274877906944  -
```

I got these using `virt-filesystems -a ext4.vhdx --extra --all --partitions -l`. I tried `guestmount` like:

`guestmount --add ext4.vhdx -o allow_other -m /dev/sda:/:acl,user_xattr:ext4 --ro /mnt/foo` but it just prints an error:
```
libguestfs: error: mount_vfs: mount exited with status 32: mount: /sysroot: wrong fs type, bad option, bad superblock on /dev/sda, missing codepage or helper program, or other error.
```

What do I do at this point? Are the files even retrievable?

**Comment by DHowett** [comment]
You may want to try installing a (sacrificial) WSL distribution, terminating WSL, replacing the sacrificial distribution’s ext4.vhdx with your old one and relaunching the distro.

alternatively: your guestmount command should use “sda1” instead of “sda”, as the ext4 volume is the first _partition_ in the entire device presented by the VHD.

**Comment by DHowett** [comment]
(I know that it may not work- at the same time, i wasn’t aware that disk management would modify vhds on its own. Further recovery could be done with “testdisk”, which should be able to reconstruct the partition table or otherwise produce a usable device image... it’s part of a suite that comes with “photorec,” a tool that will look for file headers in a disk image.)

**Comment by Timic3** [comment]
Mounting sda1 returns same error as mounting sda, as for trying to boot WSL with the corrupted image, it doesn't work, it just hangs and times out.

I tried testdisk, it detects that the partition is ext4 (it doesn't read VHDX very well, so I had to mount it) and it actually works if I build the image and start recovery process, but file names and directories are not recovered. If I list the partition, it says "No file found, filesystem may be damaged." which may be the case, but is there any way to recover the directories and names?

I did a test by opening fresh VHDX and yeah, it indeed is my fault for not seeing this but Disk Management prompted me to initialize new disk (VHDX), so I just clicked OK (it used GPT partition style), which seems to overwrite the image. Is there any way to reverse this?

Thanks for the help.

**Comment by Timic3** [comment]
An update to this: I used DMDE to restore my files; I didn't have many data on there luckily.

I'm closing this, if anyone does find a way to restore VHDX, it would be nice, for future mistakes (if they happen).

Thanks.

**Comment by Str1ker17** [comment]
You can mount VHDX by `diskpart` (which is a part of Windows installation), see there: https://www.nucleustechnologies.com/blog/ways-to-mount-and-unmount-vhd-vhdx-files/

To access ext4 partition, you can run any Linux distrubution you like in VirtualBox, using just mounted raw disk: https://www.serverwatch.com/guides/using-a-physical-hard-drive-with-a-virtualbox-vm/

This helped me right now.

**Comment by syntaxer** [comment]
II know this is old, but I had the same issue after I initialized the vhdx in Disk Manager and nothing found online helped.
I thought I'd share my experience on how I fixed the ext4 partition and recovered my distro
 
You will need a functional WSL2 distro available for the steps below:

- Open diskmgmt.msc
Attach vhd. No need to initialize disk. If you already initialized it's not important.

- From CMD with admin privileges:
List current disks to locate the attached VHD
```
#C:\> wmic diskdrive list brief
Caption                 DeviceID            Model                   Partitions  Size
KXG8AZNV1T02 LA KIOXIA  \\.\PHYSICALDRIVE0  KXG8AZNV1T02 LA KIOXIA  3           1024203640320
Microsoft Virtual Disk  \\.\PHYSICALDRIVE1  Microsoft Virtual Disk  0           274872407040
```

- Mount the disk to a WSL2 distro (Doesn't work with WSL1) and start it. Replace Ubuntu with your own distro name:
```
'#list your available distros
#C:\> wsl -l -v
  NAME          STATE           VERSION
* Ubuntu-Old    Stopped         1
  Debian        Running         1
  Ubuntu        Running         2

#C:\> wsl -d Ubuntu --mount \\.\PHYSICALDRIVE1 --bare
#C:\> wsl -d Ubuntu
```

- Inside the WSL distro, list the disks. The corrupt mounted disk should have a subdevice eg: /dev/sdc1
```
# lsblk
```

- Doulecheck with dumpe2fs. If it's the right disk it will tell you that there is an issue with disk (bad magic number):
```
# sudo dumpe2fs /dev/sdc
```

- Get the block values needed for the fsck command:
You can check the working distro disk for the values.
In my case the distro is partitioned as sda and sdb, with sdc being the corrupt disk
```
# sudo dumpe2fs /dev/sdb | grep -iEm2 'Block size|Backup superblock'
dumpe2fs 1.46.5 (30-Dec-2021)
Block size:               4096
  Backup superblock at 32768, Group descriptors at 32769-32800
```
_Block size_ is used for the **b** parameter below.
_Backup superblock_ is used for the **B** parameter.

- Fix with fsck.ext4 using the backup superblock(or e2fsck):
Unless you have some custom disk created, or you have extended the disk size, these values are default and should be the same as mine
```
# sudo fsck.ext4 -p -b 32768 -B 4096 /dev/sdc
```
You should see a message that it fixed the ext4 partition, or something similar.

- Unmount disk from distro
```
# wsl --unmount \\.\PHYSICALDRIVE1
```

- You can test if the disk is fixed by mounting it without the --bare option.
Remember to unmount it with above command after testing!

- Detach VHD in Disk Manager

**Comment by rijulg** [comment]
@syntaxer you are a life saver, one like here is not enough to justify my gratitude. I must ask how you came across this process, assuming you aren't just a disk recovery wizard?
