### ISSUE TITLE
Interacting with the mini-buffer in Emacs stops Emacs process

### ISSUE THREAD

**Issue by robdaemon** [Microsoft/WSL#639]
Whenever I attempt to use Emacs with [Spacemacs](http://spacemacs.org), interacting with the mini-buffer results in it thinking I've hit Ctrl-Z.

To reproduce:
1. `sudo apt-get install emacs git`
2. `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
3. `emacs` (start Emacs)
4. Answer the "What is your preferred style?" question simply by hitting Enter.
5. Observe bash report the Emacs process was "Stopped" via job control.

See screenshot also. This happens in the normal ConHost window, within ConEmu or PuTTY.

This is on Windows 10 build 14372.0.

![emacs_stopped](https://cloud.githubusercontent.com/assets/287213/16715702/a9a0e460-469c-11e6-9eb1-ce546d322583.png)

**Comment by adouzzy** [comment]
I had the same issue. 
What you can do is install Xming, and run emacs under X11.
For example, emacs -d :0 , where 0 is your X11 port

**Comment by cdegroot** [comment]
FYI, same happens to me using the current slow ring build (14986).

**Comment by cdegroot** [comment]
Building emacs (25.1) from source seems to fix the issue, by the way. I used the instructions on [Reddit](https://www.reddit.com/r/emacs/comments/4vxoug/emacs_on_windows_10_anniversary_update/), which worked well. 

("seems to" because I just did a quick test, setup doesn't have any proper mileage yet to be conclusive).

**Comment by cdegroot** [comment]
Couldn't reproduce so far on build 15063.0 - Spacemacs seems a bit more sluggish (certainly with startup) compared to my macbooks, but overall seems to be well-behaved.

**Comment by kostya-sh** [comment]
I have the same issue with emacs 24 (that comes from the default repo) and with emacs-snapshot (from ppa:ubuntu-elisp/ppa). The issue can be reproduced very easily:
- start emacs in the console
- M-x list-packages
- hit Enter

The same issue also happens when I enter a password prompted by `org-decrypt-entries`

**Comment by kostya-sh** [comment]
this bus is probably dup of #2088

**Comment by talyian** [comment]
Confirmed that like #2088 installing Fall Creators Update fixes this issue for me.
