### ISSUE TITLE
After upgrade to WSL2, Vmmem almost occupy 100% RAM and CPU

### ISSUE THREAD

**Issue by SilenceHe** [microsoft/WSL#6394]
After upgrade to WSL2, Vmmem almost occupy 100% RAM and CPU, and it don't work with below solution:

**.wslconfig**
```
[wsl2]
memory=4GB
swap=0
localhostForwarding=true
```

Is there any other solutions here?

**Comment by ikarstein** [comment]
same for me...

**Comment by Myron-S** [comment]
Out of curiosity, which kernel are you using?  There are two available:
https://www.catalog.update.microsoft.com/Search.aspx?q=Windows%20Subsystem%20for%20Linux%20Update

Versions 4.19.128 and 5.4.72.

**Comment by SilenceHe** [comment]
> Out of curiosity, which kernel are you using? There are two available:
> https://www.catalog.update.microsoft.com/Search.aspx?q=Windows%20Subsystem%20for%20Linux%20Update
> 
> Versions 4.19.128 and 5.4.72.
> 
> (Ref: https://docs.microsoft.com/en-us/windows/wsl/wsl-config )

**4.19.128**-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ikarstein** [comment]
regarding to "update history" of windows I have 4.19.128.

I cannot download 5.4.x from "update catalog".

**Comment by ikarstein** [comment]
I removed WSL completely - including HyperV feature. multiple reboots. Than I reinstalled HyperV and WLS2. The problem occured again.

Than I removed all containers and images (docker system prune -a).

Than I created a .wslconfig file (https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)

```
[wsl2]
memory=4GB
swap=0  
processors=2
```

Now "vmmem" is around 1% CPU and <=4GB RAM.

**Comment by Myron-S** [comment]
In the download CAB file from the catalog extract the MSI file and use that.  It worked for me.  Remember to shutdown WSL first.

I have now got:
`Linux lnx1 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020`

**Comment by craigloewen-msft** [comment]
If you're still seeing this, can you try and run `wsl --shutdown` and then rerun WSL so that you can restart the WSL 2 VM and make sure the changes you specified in .wslconfig took place? The config you listed should resolve your issue.

**Comment by SilenceHe** [comment]
@craigloewen-msft yes, I tried shutdown many times after set .wslconfig file, but it can't did any help, will try to upgrade Linux kernel version  to 5.4.72 as Myron Post to see if something special happens...

**Comment by ikarstein** [comment]
I managed to download the kernel 5.4.72 from MS Update Catalog. I tried to install it using `dism /online /add-package /packagepath:"C:\download\wsl_update_x64_0f6ecd49ea118ab320948fe23bd70f8d3b30077d.cab"` but it says "File not found". - Any ideas or hints how to install it?

**Comment by ikarstein** [comment]
> I managed to download the kernel 5.4.72 from MS Update Catalog. I tried to install it using `dism /online /add-package /packagepath:"C:\download\wsl_update_x64_0f6ecd49ea118ab320948fe23bd70f8d3b30077d.cab"` but it says "File not found". - Any ideas or hints how to install it?

I extracted the MSI from the CAB and was able to install it.

**Comment by SilenceHe** [comment]
@ikarstein Bingo! Looks much better now after upgrade Linux kernel :smile:

**Comment by Myron-S** [comment]
Hmmm....  Where is the source code for 5.4.72 on github?

**Comment by craigloewen-msft** [comment]
You can find the [5.4.72 Linux kernel source code here](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-5.4.72). We also post our kernel release notes [here](https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes) with links to the source as well!

**Comment by NadaSulaiman** [comment]
Same issue here. Very frustrating. I'm using WSL on Windows Build 21301. Running a simple .py script on Ubuntu has consumed ~90% of my CPUs (32 cores), which is absurd. I have used the .wslconfig fix, and it seems to make it work.

**Comment by bpulliam** [comment]
It looks as though this issue can be solved by ensuring the kernel is up to date.  Current values are 5.10.16 for Insiders and 5.4.72 for everyone else. Closing this issue.

**Comment by dhruvinrsoni** [comment]
I found a solution somewhere online. pretty much helps to control the RAM and CPU with wsl's config.

create a .wslconfig file with following content and set the memory as 1GB or 512MB

`[wsl2]
#kernel=<path>              # An absolute Windows path to a custom Linux kernel.
#memory=<size>              # How much memory to assign to the WSL2 VM.
#processors=<number>        # How many processors to assign to the WSL2 VM.
#swap=<size>                # How much swap space to add to the WSL2 VM. 0 for no swap file.
#swapFile=<path>            # An absolute Windows path to the swap vhd.
#localhostForwarding=<bool> # Boolean specifying if ports bound to wildcard or localhost in the WSL2 VM should be connectable from the host via localhost:port (default true).

# <path> entries must be absolute Windows paths with escaped backslashes, for example C:\\Users\\Ben\\kernel
# <size> entries must be size followed by unit, for example 8GB or 512MB
#https://blog.simonpeterdebbarma.com/2020-04-memory-and-wsl/`

**Comment by maxpaj** [comment]
> It looks as though this issue can be solved by ensuring the kernel is up to date. Current values are 5.10.16 for Insiders and 5.4.72 for everyone else. Closing this issue.

This seems to have fixed my memory issue.

**Comment by karato22** [comment]
Hi everyone,
I tried, from my debian virtual machine and root account, to drop the cache and it worked: "echo 3 > /proc/sys/vm/drop_caches".
**DISCLAIMER**
Usually the cache drop is not done "lightly" because it could cause problems in the user space, but in case there are no problems for your applications, it will work.
My advice is to try it only in case you are sure that the cache drop cannot lead to problems or system instability, otherwise refrain. I did it only in case of extreme necessity, when vmmem had occupied almost all the 32GB of RAM on my laptop.

**Comment by bjrukin** [comment]
https://github.com/microsoft/WSL/issues/6394

**Comment by bjrukin** [comment]
https://www.youtube.com/watch?app=desktop&v=JmkysqY5iu8

**Comment by karato22** [comment]
Hi everyone,
I also tried, from my "Debian bullseye" virtual machine as "root" account, to drop the cache when the RAM used by the "Vmmem" reached the entire physical allocation of my laptop and it worked: "echo 3> /proc/sys/vm/drop_caches".
Usually the cache drop is not done "lightly" because it could cause problems in the user space, but in case there are no problems for your applications, it works.
By the VM is not visibile the increase of the used cache (neither by the /proc/meminfo), but for certain operations such as the use of an external disk mounted with cifs, there was a very fast decrease of the available RAM that was proportional to the increase of the Vmmem RAM allocation, so I wrote a very simple pipeline to release the cache when the VM's available RAM goes under a chosen threshold (in my case 5 GB).

*** DISCLAIMER ***
My advice is to try it only in case you are sure that the cache drop cannot lead to problems or system instability, otherwise refrain. I did it only in case of extreme necessity, when vmmem had occupied almost all the 32GB of RAM on my laptop.

**Comment by cusco** [comment]
> It looks as though this issue can be solved by ensuring the kernel is up to date. Current values are 5.10.16 for Insiders and 5.4.72 for everyone else. Closing this issue.

Hi

I have 5.10.16.3-microsoft-standard-WSL2
It does not seem to fix the issue. Most I can do, is create a .wslconfig file with hard limits set..

I just upgraded to wsl2 in order to be able to install docker on the linux environment, and I am already regretting it. This did not happen in wsl1

**Comment by WackyLizard** [comment]
I tried all the fixes mention anywhere I could find.
https://docs.microsoft.com/en-us/windows/wsl/compare-versions
Under the section called 'Exceptions for using WSL 1 rather than WSL 2', one of the points says to use WSL1 if """You have strict memory requirements
WSL 2's memory usage grows and shrinks as you use it. When a process frees memory this is automatically returned to Windows. However, as of right now WSL 2 does not yet release cached pages in memory back to Windows until the WSL instance is shut down. If you have long running WSL sessions, or access a very large amount of files, this cache can take up memory on Windows."""
This applies to my situation, I think, and maybe others? My next step is WSL1
