### ISSUE TITLE
Ubuntu issue-安装问题

### ISSUE THREAD

**Issue by ljy-002** [microsoft/WSL#6424]
Ubuntu issue:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80080005
Error: 0x80080005 ???????

Press any key to continue...

**Comment by ljy-002** [comment]
Ubuntu 20.02 LTS

**Comment by craigloewen-msft** [comment]
We have some previous threads on this error, it seems to be networking related and others have resolved it by restarting. Could you please try that and see if that resolves you?

Here are some relevant threads:
https://github.com/Microsoft/WSL/issues/781
https://github.com/microsoft/WSL/issues/5700
https://github.com/microsoft/WSL/issues/5003

I'll be closing this issue since the issue template was deleted, and we require that information to be able to accurately help any issues that are filed!
