### ISSUE TITLE
Update host.docker.internal and related after network change

### ISSUE THREAD

**Issue by valentijnscholten** [microsoft/WSL#6530]
Forgive if this has been reported / discussed / documented somewhere, but I couldn't find it.

**Is your feature request related to a problem? Please describe.**
When changing networks, for example disconnecting my laptop from the docking, should update the `host.docker.internal` ip mapping and possibly other entries like those in `/etc/resolv.conf`

Currently when undocking, my laptop switches to WiFi, which is to be expected. But WSL2 (or docker for win) isn't aware of this or reacting to it. So everything relying on `host.docker.internal` for connectivity to the windows host will fail.
(i.e. an MSSQL database server).

**Describe the solution you'd like**
Ideally the network change gets picked up so the DNS / host entry for host.docker.internal gets updated.

**Describe alternatives you've considered**
Document this usecase by explaining the steps needed to get host.docker.internal working again.
What worked for me today is `wsl --shutdown`. Sounds easy afterwards, but if you don't know how this works under the hood it can take you a lot of time to find out.

At first I tried:
- closing/opening Ubuntu WSL2
- restarting docker for desktop

Those are not working, it seems you really need to shutdown `wsl` to get it to regenerate the correct ip mapping.

**Additional context**
I am observing that the ip in `/etc/resolv.conf` is always different from what `host.docker.internal` is resolving to. Connecting to `host.docker.internal` from WSL2 works. The ip from `/etc/resolv.conf` can be pinged, but windows programs/services are not listening to it it seems, even though they're bound to `0.0.0.0`.

```
valentijn@LAP0125:~$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.30.16.1
```

```
valentijn@LAP0125:~$ telnet 172.30.16.1 3306
Trying 172.30.16.1...
```

```
valentijn@LAP0125:~$ telnet host.docker.internal 3306
Trying 192.168.1.250...
Connected to host.docker.internal.
Escape character is '^]'.
```

**Comment by valentijnscholten** [comment]
@therealkenc not sure if it is a duplicate. Might be the same root cause, but for me DNS works fine. foreverything It's just the host entry for host.docker.internal is not updated, not even after restart of docker or ubuntu.

**Comment by ilatypov** [comment]
@valentijnscholten , you seem to be getting host.docker.internal from either a static hosts entry or from the DNS.  This host name appears an artificial entry configured by a docker host for its guest containers,

https://docs.docker.com/desktop/networking/

WSL2 is not a Docker container but a Linux co-guest to a hypervisor (small super-kernel) that started both the Windows and the Linux kernel at the system startup.

Perhaps you want to have the laptop's Windows guest "currently live" ethernet address available in your WSL2 Linux guest (and I understand some of the Windows's ethernet addresses are the ones linked to the physical network interfaces just because Microsoft sets up the hypervisor and the Windows kernel this way).  I can see that a virtual WSL2 ethernet address is exposed as a DNS server address in /etc/resolv.conf (but this may miss changes in your physical configurations).  If that is not good enough, then, perhaps, using the WSL2 mount of /mnt/c/Windows/System32/ipconfig.exe and its stdin/stdout/stderr "interop" could help automate polling for the current address.  Pushing the current address could also be made possible with a manual Windows Task Scheduler task that listens for a particular network change eventID and launches a script.
