### ISSUE TITLE
Distros Missing After Drive Upgrade

### ISSUE THREAD

**Issue by outcast** [microsoft/WSL#6604]
***I know I am not using the template***

So strange thing today, I upgraded my nvme drive today. Went from 500GB to 1TB, but now my WSL distros are missing.

what I did:

1. use DD to clone one drive to other `dd if=nvme1n1 of=nvme0n1`
2. deleted recovery partition next to the primary.
3. extended partition to use remaining space.

Is there anything that would have caused my distro's to go missing by doing what I did above. By all rights the drive were identical except for size. Even when I booted up windows, it took the old drive offline because the id's matched.

**Comment by craigloewen-msft** [comment]
@outcast I'll close this issue out since you haven't used the template, and we need that information to be accurately able to help you.

However I want to also give you some advice for troubleshooting. In general, your Distro files are stored in `C:\Users\<yourUserName>\AppData\Local\Packages` with names that start with things like: 'CanonicalGroupLimited.Ubuntu'.. for a Distro like Ubuntu. Are you able to check for that folder and see if your distro files exist there? 

If you'd like further help on this issue please reopen it with the template filled out. Thank you!
