### ISSUE TITLE
Layout Kanas, Kanjis and Hanguls correctly under non-DBCS code page, which is what BOW is using

### ISSUE THREAD

**Issue by be5invis** [Microsoft/WSL#662]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  The current console CP (65001) cannot layout any CJK full-width characters correctly.
- Expected results
  The wide characters are fit into two console cells, instead of one.
- Actual results (with terminal output if applicable)
  The wide characters are shrunk into one console cell and unlegiable.
- Your Windows build number
  14372 (slow ring)
- Steps / commands required to reproduce the error
  1. Open WSL.
  2. Run any program produces CJK output.
  3. Look at it.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by be5invis** [comment]
Any progress?

**Comment by RyanGlScott** [comment]
Silly question: what are some "CJK full-width characters" that we could try out for debugging purposes?

**Comment by be5invis** [comment]
@RyanGlScott like
安あ

**Comment by be5invis** [comment]
@benhillis @miniksa @zadjii-msft 
Any progress?

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. The changes necessary to support MUCH more of the UNICODE text-space is underway, but will take a while to complete. Bear with us while we implement the necessary changes
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
