### ISSUE TITLE
'pip install' is extremely slow in WSL2

### ISSUE THREAD

**Issue by rpw138** [microsoft/WSL#6643]
# Environment

WSL2: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

# Steps to reproduce
git clone https://github.com/NVlabs/stylegan2
cd stylegan2
docker build . -t stylegan2

#  Expected behavior
Pip install is very fast on wsl2:   Download starts immediately and is very fast

# Actual behavior

Pip during docker build is very slow on wsl2 - the install hangs when downloading scipy for ~5 to 10 minutes.  Also noticed similar for google drive downloads.

**Comment by Bartdoekemeijer** [comment]
You may be a variant of [the slow network in WSL2 issue](https://github.com/microsoft/WSL/issues/4901)

**Comment by therealkenc** [comment]
>  install hangs when downloading scipy for ~5 to 10 minutes.

Could be /dupe #4901 or #6365, or (depending on the uncited pwd) #4197

**Comment by ceagan** [comment]
This is not due to a slow network issue. It takes 5-10 minutes to get past something, then the installations continue at a normal pace. Download speeds are fine once the installation of packages starts.

See [On WSL2 `pip install virtualenv` comand hangs for too long](https://stackoverflow.com/questions/68016708/on-wsl2-pip-install-virtualenv-comand-hangs-for-too-long) on Stack Overflow.

**Comment by ppaanngggg** [comment]
> This is not due to a slow network issue. It takes 5-10 minutes to get past something, then the installations continue at a normal pace. Download speeds are fine once the installation of packages starts.
> 
> See [On WSL2 `pip install virtualenv` comand hangs for too long](https://stackoverflow.com/questions/68016708/on-wsl2-pip-install-virtualenv-comand-hangs-for-too-long) on Stack Overflow.

thanks, solve my problem

**Comment by FlorinAndrei** [comment]
@ppaanngggg How did you solve it? That Stack Overflow page does not offer a solution.

**Comment by ppaanngggg** [comment]
> @ppaanngggg How did you solve it? That Stack Overflow page does not offer a solution.

I use this command `DISPLAY= pip install <packagename>`

**Comment by francois-rozet** [comment]
> I use this command `DISPLAY= pip install <packagename>`

IMHO, this is a great temporary fix, but not a good solution and the issue should be reopened.

I don't really understand the problems with `keyrings` and `DISPLAY` and X servers, but I think users should not have to play with them when installing Python packages. It should be as easy on WSL as on a true Linux OS.

**Comment by ppaanngggg** [comment]
> 

I dont know, but it works.

I think it is a new problem after WSLg update for WSL2.

**Comment by ll7** [comment]
Where can I find more about the `DISPLAY=` command? It works, but I don't understand it.

**Comment by ceagan** [comment]
This command sets the environment variable `DISPLAY` to empty. If you are running an XServer, this environment variable enables apps to connect to the XServer to display graphical information. I don’t know the details, but presumably, pip is reading the environment variable and because it is set, it attempts to connect to the XServer and use a long timeout to do so. Since no XServer is running by default in WSL2, the connection to the server fails after awhile. Setting the environment variable to blank lets pip know that no XServer is available, so it skips trying to connect to it.

**Comment by flaccidattempts** [comment]
If its any help for this topic. 
This always happens after i mount from wsl2 to C drive [from wsl2] and use cmd 'python my_script.py'.

for example from the beginning  

>powershell
'
wsl
cd /mnt/c/Users/*/Desktop/Projects/python
python main.py
'
after exiting this windows terminal, python3-pip hangs super bad. Notably when invoking 'pip install'

**Comment by shivangsgangadia** [comment]
Was facing the same issue. However, I have XServer set up with XLaunch because I often use graphical apps. As pointed out by @ceagan , if this xserver host is running on windows, things work as fast as they should but when it is disabled, pip waits a long  time for a timeout. I recommend setting up XLaunch because you might need it at some point in the future anyway.

**Comment by ntbanks** [comment]
I've seen mixed reviews on this but i moved my project from the C mount `/mnt/c/Users/*/Documents....` to the actual linux file system `/home/*/....` and it fixed the slow install times.

**Comment by amrohendawi** [comment]
Instead of adding `DISPLAY=`  every time to your commands, just install a GUI for WSL2 like [GWSL](https://apps.microsoft.com/store/detail/gwsl/9NL6KD1H33V3?hl=en-us&gl=us).

**Comment by tafia** [comment]
Isn't updating *.bash_aliases* enough?
something like
```
alias pip="DISPLAY= pip"
```

**Comment by bat52** [comment]
WSL2 is much slower than WSL1 when accessing files on the windows filesystem, according to what mentioned here
https://stackoverflow.com/questions/68972448/why-is-wsl-extremely-slow-when-compared-with-native-windows-npm-yarn-processing

**Comment by Anutrix** [comment]
Still facing this issue on latest version of WSL2.

**Comment by BramVanroy** [comment]
I found that my installation was very slow, too, but using the `-v` option it seems to hang especially at the end of the installation when it is changing the permissions for installed entrypoints. For instance, if you have tensorboard or streamlit or something like that that you can call from the command-line like `streamlit run ...`, such binaries are modified.

```
changing mode of /mnt/f/python/.venv/bin/google-oauthlib-tool to 777
changing mode of /mnt/f/python/.venv/bin/tensorboard to 777
changing mode of /mnt/f/python/.venv/bin/streamlit to 777
```

This takes quite a long time, at least when using ` /mnt/` drive. That being said, setting `DISPLAY= pip install ...` already made things quite a bit faster.
