### ISSUE TITLE
SSH on WSL2 is all but unuasable.

### ISSUE THREAD

**Issue by pnunn** [microsoft/WSL#6659]
I don't know if its a windows thing or a wsl2 thing, but ssh it just unusable.

I have ssh connections running to the same host, one on wsl2 the other on Linux Mint.

The mint connection has been up for about 4 hours.
The wsl2 connection closes the connection to the server about every 10 minutes (if I'm lucky). It is just totally useless.

Has anyone else seen this?

**Comment by markko1** [comment]
It's a configuration issue. I have in my home folder `.ssh/config` file and among other configuration:
```
ServerAliveInterval 30
ServerAliveCountMax 6
```
I think the first one is most important - it sends a _null_ packet to server every 30 seconds so that the server will not drop the connection as an idle one.
You can read about it here: https://unix.stackexchange.com/questions/3026/what-do-options-serveraliveinterval-and-clientaliveinterval-in-sshd-config-d

**Comment by pnunn** [comment]
OK, I'll give that a try, but I currently have ServerAliveInterval 5 and ServerAliveCountMax 1. Might try bumping them and see what happens.

I'll report back.

**Comment by pnunn** [comment]
OK, that made the connection last longer, but now when it fails, it hangs the entire terminal for ages before it drops the connection.

**Comment by gitbls** [comment]
I (and several others) was having problems with X applications dying. Probably won't help, but might be worth ruling it out. Check out the solution: [https://github.com/microsoft/WSL/issues/5339#issuecomment-771961120](url). It definitely fixes the X apps problem.

**Comment by pnunn** [comment]
I've given up on wsl for ssh. I'm now using a linux VM to do it instead until I get around to getting rid of windows all together.
