### ISSUE TITLE
Not able to start ubuntu 18.04 on Windows 10

### ISSUE THREAD

**Issue by ns-zsyed** [microsoft/WSL#6774]
I followed the instructions on:
https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

and in step 6 I launch ubuntu-18.04 I get the below error

WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.

# Environment

```none
Windows build number: 
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.19042 N/A Build 19042

```

Virtualization is enabled:
![image](https://user-images.githubusercontent.com/61716504/114085206-e8d00d80-9865-11eb-90a4-fb5e87195e29.png)

# Steps to reproduce

https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

**WSL logs**: 

#  Expected behavior

![image](https://user-images.githubusercontent.com/61716504/113931725-a9db8280-97a7-11eb-8c9f-64629c4b3982.png)

# Actual behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.

Press any key to continue...

**Comment by craigloewen-msft** [comment]
We believe this issue is caused by an error with socket connectivity. The best way for us to diagnose this is to see the output of dmesg while your VM is loading. Unfortunately that feature is not available on the Windows build you're on. 

Are you able at all to upgrade to a Windows Insiders build and then create a .wslconfig file in your users profile directory on Windows (e.g: `C:\Users\<yourUsername>\.wslconfig`) and add: 
```
[wsl2]
debugConsole=true
```

If you can do that, and then paste the logs, we'll be able to have an understanding of what's going on. Thanks!
