### ISSUE TITLE
WslRegisterDistribution failed with error: 0x8037011e

### ISSUE THREAD

**Issue by hesand** [microsoft/WSL#6794]
### Windows Build Number

Microsoft Windows [Version 10.0.21354.1]

### WSL Version

WSL 2

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop (Windows), version 3.2.2

### Repro Steps

on a windows 10, running on vmware workstation pro
wsl --install
when ubuntu starts up, gets the error

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8037011e
Error: 0x8037011e The host compute system service has disconnected unexpectedly.

Press any key to continue...

### Expected Behavior

n/a

### Actual Behavior

n/a

### Diagnostic Logs

n/a

**Comment by adrastogi** [comment]
Thanks for reporting this. Would you be able to [submit logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)?

**Comment by hesand** [comment]
[wsl-log.zip](https://github.com/microsoft/WSL/files/6294170/wsl-log.zip)

**Comment by rirlswift** [comment]
did you get a resolution of this problem? I am facing the identical failure.

**Comment by Albert--E** [comment]
I was able to install Ubuntu 20.04 LTS by setting the WSL version to instead of 2 
 wsl --set-default-version 1
![Set WSL version](https://user-images.githubusercontent.com/4931065/116831128-870c7600-ab7b-11eb-9672-9f816a504a4f.jpg)
![Ubuntu Installation](https://user-images.githubusercontent.com/4931065/116831129-870c7600-ab7b-11eb-870e-dfc6222ff804.png)
