### ISSUE TITLE
Graphic control panel not working and animation lag when virtualization enabled 

### ISSUE THREAD

**Issue by levelsevencrew** [microsoft/WSL#6822]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Distro Version

kali 

### Repro Steps

Wanted to setup wsl-2
I already have enabled virtualization in bios and when I enable Virtual machine platform and restart my pc all windows animations starts lagging.

### Expected Behavior

Turn on virtual machine platform for wsl 2

### Actual Behavior

after enabling virtual machine platform and restarting the pc i notice that my intel hd graphics control panel was not there when i right click on desktop and  also my all windows animation like ( scrolling, tile animation etc) looked very sluggish

**Comment by craigloewen-msft** [comment]
The actual bug here is likely inside of the Graphics stack, meaning we on the WSL team aren't directly able to help here. I've asked the Graphics team the best way to file this and they said please use Feedback Hub. Could you please press 'Windows Key + F' to open Feedback Hub, and create this as a new feedback item under 'Display and Graphics'? That would be the best way for them to look into it. I'll close this issue out as there isn't anything actionable on our team to help here, thank you for filing!
