### ISSUE TITLE
Vmmem suddenly using too much CPU when idle

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#6837]
### Windows Build Number

Windows 21364

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 21.04

### Other Software

Docker Desktop 3.1.0 and 3.3.1

### Repro Steps

After updating to Windows 21364 and `wsl --update` I noticed how my fans went crazy after a restart, which is pretty unusual, even that I start Docker automatically after boot.
Inspecting Task Manager, I can see that Vmmem isusing ~ 20% of my CPU and 4/32 GB RAM, when Docker is running.

Also typing in Windows Terminal, would skip key-strokes very often.

The overall CPU usage is at 40%, every other service after "Service Host" uses up to 0.2% CPU.
![image](https://user-images.githubusercontent.com/9553253/115625918-076de400-a2fd-11eb-84d9-888bc46b7a7c.png)

The fan noise when idle is so loud as if I was gaming.

After quitting Docker it drops to 7%CPU, which I think is still a bit to much, for being idle.

### Expected Behavior

Vmmem not utilizing CPU/RAM until heavy tasks are done

### Actual Behavior

Vmmem utilizes high CPU/RAM usage

**Comment by ll931217** [comment]
I am having the exact same issue

# Windows Build Number
19042.928

# WSL Version

- [x] WSL 2
- [ ] WSL 1

# Kernel Version

5.4.72-microsoft-standard-WSL2

# Distro Version

Ubuntu 20.04.2 LTS

# Other Software

* Docker Desktop v3.3.1
  * Engine v20.10.5

# Repro Steps

Just starting the WSL up and leave your computer on idle.

![image](https://user-images.githubusercontent.com/12750413/115641806-673fab80-a34c-11eb-9ed7-fe1e5633728c.png)

Whenever WSL starts up, it will use up 2GB of RAM then slowly crawl up to around 6GB. I see in other issues that a lot of the cases are due to having Docker Desktop installed.

## After executing `wsl --shutdown` in PowerShell:

![image](https://user-images.githubusercontent.com/12750413/115642150-ffd62b80-a34c-11eb-9d95-2dd3c785c799.png)

## Then starting WSL up:

![image](https://user-images.githubusercontent.com/12750413/115642180-0ebcde00-a34d-11eb-8f4a-2b0c79ee202a.png)

The above pic is when docker desktop haven't started, which is practically the same as after executing `wsl --shutdown`, except 100MB difference.

## After starting docker desktop:

![image](https://user-images.githubusercontent.com/12750413/115642415-812dbe00-a34d-11eb-83c0-b5bce01636d8.png)

# Expected Behavior
Vmmem not utilizing CPU/RAM until heavy tasks are done

# Actual Behavior
Vmmem utilizes high CPU/RAM usage

# Diagnostic Logs
No response

**Comment by ad-on-is** [comment]
I rolled back Windows to the previous build (21359) and vmmem is idleing at 0.5% CPU, under the same conditions.

There's definitely some issue with the new Windows update, maybe WSLg related?

**Comment by D1ceWard** [comment]
I had the same problem since `wslg` update but adding the ".wslconfig" file in the user root with the option to disable `wslg` seems to have fixed it.

My `.wslconfig` file
```text
[wsl2]
guiapplications=false
```

**Distro:** Arch linux (from https://github.com/yuk7/ArchWSL) 
**Windows build number:** 21364
**WSL 2**

**Comment by ad-on-is** [comment]
> My `.wslconfig` file
> 
> ```
> [wsl2]
> guiapplications=false
> ```

Thx!
While this solves my issue, it now doesn't allow me to run GUI apps.

**Comment by ad-on-is** [comment]
As per https://github.com/microsoft/wslg/issues/103 they are aware of the problem, and a fix is coming via `wsl --update`
