### ISSUE TITLE
WSLg: GUI emacs will not load config from ~/.config/init.el and sometimes spams a single character on startup.

### ISSUE THREAD

**Issue by landermkerbey** [microsoft/WSL#6955]
**Windows Build Number**

Windows 10 Home, Build 21382.co_release.210511-1416

**WSL Version**
WSL2 (WSLg)

**Distro Version**
Ubuntu 20.04 LTS

**Other Software**
Emacs was installed via apt on WSL Ubuntu.

**Steps to Reproduce**

1. Ensure you are using a WSLg build
2. Open a WSL Ubuntu terminal session.
3. `echo $XDG_CONFIG_HOME`. If it returns a blank line, then in your ~/.bashrc, add the line `export XDG_CONFIG_HOME="$HOME/.config" and restart WSL. Run the `echo` command again to verify the new value has been sourced.
4. `mkdir ~/.config`
5. `sudo apt-get install emacs`
6. `rm -rf ~/.emacs.d`
7. `mkdir ~/.config/emacs
8. `emacs ~/.config/emacs/init.el &`
9. Add some line of configuration that immediately changes the appearance of emacs such as `(menu-bar-mode -1)`, then close emacs.
10. `emacs ~/.config/emacs/init.el &`

**Expected Behavior**
emacs should refer to `.config/emacs/init.el` in the absence of any other preferred file path, and use it to determine its configuration. Additionally, the application should open and allow normal editing of text immediately.

**Actual Behavior**
emacs fails to find or use `.config/emacs/init.el`, instead using the default emacs configuration appearing every time. Additionally, it recreates `~/.emacs.d` no matter how many times you delete it. If you create `.init.el in that` directory, emacs will recognize and use it.

Furthermore, on startup, emacs will spam the primary buffer with the same character over and over again until you enter some other keystroke in that buffer. Usually it will repeatedly enter `c`, though on a few occasions it has entered `z`. Rarely, it will not display this erroneous behavior at all.

**Comment by therealkenc** [comment]
> emacs should refer to .config/emacs/init.el in the absence of any other preferred file path

This is linux behavior; confirmed that `~/.config/emacs/init.el` is not picked up on a native Linux box with the given repro. WSL and WSLg do not control this behavior.

> emacs will spam the primary buffer with the same character

Something vaguely similar came up once in #5468, which was closed at the time because in the scenario the keystrokes were marshalled by VcXsrv. You can try opening a [WSLg issue](https://github.com/microsoft/wslg/issues) and see if others are experiencing the misbehavior. I was not able to reproduce the behavior locally, but maybe it will accumulate a few likes over there.
