### ISSUE TITLE
WSL Bug issue-Temporary failure in name resolution

### ISSUE THREAD

**Issue by kushalaro** [microsoft/WSL#7009]
### Windows Build Number

Microsoft Windows [Version 10.0.18363.1556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 18.04

### Repro Steps

1. Run this command  - sudo apt-get update
2. run this command - ping google.com
ping: google.com: Temporary failure in name resolution

### Expected Behavior

all should work and install packages.

### Actual Behavior

1. 
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'

2. ping: google.com: Temporary failure in name resolution

### Diagnostic Logs

Can anyone help on this issue.

I tried lot of things like- 
1. setup this - 
 cat /etc/wsl.conf
[network]
generateResolvConf = true

2. cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.17.215.193
I have checked with nameserver 8.8.8.8
nameserver 1.1.1.1

but still not working .

**Comment by craigloewen-msft** [comment]
Could you please collect networking logs for this issue and link them here? 

You can find the instructions to collect the logs [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues). Thanks!

**Comment by kushalaro** [comment]
I am not getting the page for recoding  in the 'Additional Details' section

**Comment by kushalaro** [comment]
collected networking logs
[wsl.txt](https://github.com/microsoft/WSL/files/6591228/wsl.txt)

**Comment by PavelSosin-320** [comment]
This thread is the random collection of unrelated problems and solutions! There is nothing common between WSL 1 and WSL 2 networking, different Kernel versions, and different distros that use different network components.
I don't see any means in the discussion of the issues and solutions with WSL 1 networking in aging Ubuntu 20.04 running on the kernel 4.17 together with Networking issues and solutions in Fedora remix WSL 2 distro built for VM with single Eth0 interface. In the  1st case, the Windows stack shared with Linux and VPN client parameters can solve something. in the 2nd case, the issue doesn't exist because of bulletproof Name resolver works perfectly with the default configuration.
