### ISSUE TITLE
Mounting SAMBA/NFS share using CIFS  and Kerberos authentication giving mount error(95): Operation not supported

### ISSUE THREAD

**Issue by pavelmateju** [microsoft/WSL#7041]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 3.3.3 (64133)
Docker version 20.10.6

### Repro Steps

**WSL2 - ubuntu 20.04 (from microsoft store)** 

mapping NFS/samba using cifs:

_Mounting using cifs and username/ password  **works**:_
`mount -t cifs -o username=somedomainuser@somefulldomainname //someserverfuldomainname/somesharename /somelinuxfolder`

_Listing shares from the same server using kerberos ticket (generated by kinit just before)  **works**:_
`smbclient -k -L  //someserverfuldomainname/somesharename`

_Mounting using cifs and  sec=krb5 **does not work**,_
`mount -t cifs -o sec=krb5,vers=3.0 /someserverfuldomainname/somesharename /somelinuxfolder`

-> it fails with error message `mount error(95): Operation not supported`:  
and `dmesg` not listing any error.

Exactly same beahviour as in the WSL2 UBUNTU distro also in the container (from ubuntu 20.04 image) running in the Docker Desktop (set to use WSL2) start via compose file that has set:
`
cap_add:
      - ALL
    privileged: true
`

### Expected Behavior

1. If the `smbclient` can list and also connect to the nfs/smb share using kerberos authentication, why the cifs can not ?

2. Why the `mount -t cifs`  can connect only using username /password  and using the kerberos ? 

3. What is the  recommended / supported **SECURE** way how to map NFS/SAMBA shares from the WSL2 linux distros or Docker desktop containers based on linux images - any documentation ? Is there currently any ?

### Actual Behavior

root@WEB-DT-027:/home/pavel# mount -t cifs -o sec=krb5,vers=1.0 //FQDNhost/sharedFolder  /somelinuxmountpoint
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
root@WEB-DT-027:/home/pavel# dmesg
[640512.077244] WSL2: Performing memory compaction.
[640515.629016] CIFS: Attempting to mount //devdockerhg01.od.rferl.org/docker-recording
[640573.129658] WSL2: Performing memory compaction.
[640634.184655] WSL2: Performing memory compaction.
[640695.261290] WSL2: Performing memory compaction.
root@WEB-DT-027:/home/pavel#

**Comment by therealkenc** [comment]
> If the smbclient can list and also connect to the nfs/smb share using kerberos authentication, why the cifs can not ?

Because they are different implementations of the protocol(s). One is implemented in userspace. And the other is implemented in kernelspace.

> cap_add: - ALL privileged: true

It isn't operation not _permitted_. It is operation not _supported_. At the end of the day that "operation not supported" is by-design linux-kernel. It is unlikely you have a WSL2 networking issue or you wouldn't have made it this far.

> any documentation ? Is there currently any ?

Not in the sense you want, that I am aware of. SOP is to try variations of `vers=` and `sec=` until one works, which will differ depending on the nature of `//someserverfuldomainname`. Try `-o sec=krb5,vers=3.02` on a lark.

It _might_ be that WSL2 lacks `CONFIG_RPCSEC_GSS_KRB5`, but that is a WAG (for my part) without any actual supporting evidence. That particular kconfig is `=m` on a Real Linux box, which at least counts as a WSL diverge. This submission could in principle be discussed its way into a WSL actionable given fail repro steps where `//someserverfuldomainname` is `//127.0.0.1`.

![image](https://user-images.githubusercontent.com/7049700/121107912-a66f7200-c7bd-11eb-93c3-7ac7b83f4241.png)

**Comment by pavelmateju** [comment]
Hello, 

Many thanks for your response and throughout explanation.

When forcing `vers=3.02`   ...  still getting the `mount error(95): Operation not supported`.

But perhaps the  WSL2 lacking `CONFIG_RPCSEC_GSS_KRB5`  that you pointed out  might not be  a WAG , but rather the root cause ?  

See the issue (an even the pull request) here:
[Please support Kerberos protection for NFS by enabling CONFIG_RPCSEC_GSS_KRB5 #6572](https://github.com/microsoft/WSL/issues/6572)

If you can confirm / reject that would be helpful  - at least to know that this is current status quo. 

Without having the option to use Kerberos to map SMB/NFS the only option that we have for mounting the windows smb shares  seems to be using the username / password  from the linux containers running on WSL2 enabled Docker desktop on windows 10  workstations.   :-(

I guess here is another description of the very same issue: 
https://stackoverflow.com/questions/65525400/mounting-cifs-share-using-kerberos-fails-with-operation-not-supported

Many thanks again
