### ISSUE TITLE
WSL2 fails to run any distros with error 0x80370102

### ISSUE THREAD

**Issue by BobbyBaratheon** [microsoft/WSL#7068]
Microsoft Windows [Version 10.0.19043.1052]
Fresh install of WSL, hypervisors platform, virtual machine platform, windows subsystem for Linux, and WSL2 update installed. CPU Virtualization is enabled, but no distro can setup. 
![Screenshot 2021-06-15 163827](https://user-images.githubusercontent.com/85140081/122121271-6cbfec00-cdf9-11eb-8037-fe1f18ddacd0.png)
![Screenshot 2021-06-15 164112](https://user-images.githubusercontent.com/85140081/122121273-6d588280-cdf9-11eb-9d3a-98c831c4c1ab.png)
![Screenshot 2021-06-15 164134](https://user-images.githubusercontent.com/85140081/122121276-6d588280-cdf9-11eb-88cb-b3f74062e1cc.png)
![Screenshot 2021-06-15 164222](https://user-images.githubusercontent.com/85140081/122121278-6d588280-cdf9-11eb-9160-5d96f355126d.png)

can anyone help?

**Comment by therealkenc** [comment]
#4120. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by BobbyBaratheon** [comment]
https://aka.ms/AAcxty9

**Comment by benhillis** [comment]
@BobbyBaratheon - can you verify that virtualization is enabled in your BIOS?

Easiest way is to look at msinfo32.exe

**Comment by jbciardi** [comment]
Says it is right in the cmd picture

> Virtualization Enabled In Firmware: Yes

**Comment by OneBlue** [comment]
Root cause appears to be:

```
{"Error":-2143878910,"ErrorMessage":"The virtual machine could not be started because a required feature is not installed.","ErrorEvents":[{"Message":"Cannot create system 'ECEAFECC-E667-42F2-98BB-59AB37EABD25' since Hyper-V is not installed on the host."
```

Maybe something went wrong when the features were enabled. 
Can you to disable the virtual machine platform, reboot, enable it again, reboot again try to run wsl ?

**Comment by Dalot** [comment]
I am having the same problem. I've tried disabling and enabling Virtual machine platform between restarts and it did not work. I've also did for Virtualization in the BIOS and it also did not work and I've tried a complete wsl reinstall as well without any success.

**Comment by Amondale** [comment]
So I'm looking at the same error in W11 10.0.22000 on a Hyper-V VM. Best guess is problem has to do with missing TPM? I get the impression WSLg won't run on a VM, as no distro will install. Like the OP my error is:

PS C:\WINDOWS\system32> ubuntu
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

Press any key to continue...

**Comment by Amondale** [comment]
If you're using HyperV, shutdown the VM and use this script in PowerShell:

set-vmprocessor nameofyourvm -ExposeVirtualizationExtensions $true

Next, disable dynamic RAM (HyperV) and start the VM.


This comment from another issue allowed WSL2/WSLg to run. The error text Error: 0x80370102 The virtual machine could not be started IMO was misleading, as I was already inside a "virtual machine"??  Maybe I'm overthinking as usual :)?

**Comment by tronix3** [comment]
I'm having the same issue. WSL1 ran perfectly fine but WSL2 has not worked since it was released. I have Virtualization turned on, HyperV, etc. I have tried disabling them and reenabling, restarting, removing the ubuntu app and reinstalling. All to no avial.

**Comment by tfmertz** [comment]
Having this same issue. I was running wsl2 with no issues for around 4 months using docker to develop until around June 12th, 2021. Then I guess I updated windows and it hasn't worked since (or my wife installed Revit 2020, but I uninstalled it and it still doesn't work). I used to get the error that the Virtual Machine Platform wasn't installed so I couldn't open Ubuntu. So I backed up the Local State/ext4.vhdx (because wsl exporting feature won't work without the distro working apparently) And uninstalled VMP, WSL features, and the linux kernel update and my ubuntu distros. Then reinstalled them all following these instructions https://docs.microsoft.com/en-us/windows/wsl/install-win10.

Some system details:
Version 21H1 (OS Build 19043.1165)
Windows 10 Home
Task manager on performance tab has Virtualization: Enabled.

I've tried a bunch of different solutions in a ton of different threads which have included a sampling of, uninstall docker desktop, uninstall and reinstall VMP and WSL features and distros, Set hyper-v launch type in bcdedit to auto, install VMP and WSL features, turn off virtualization in bios, enable virtualization in bios, and reinstall following the installation instructions above, restarting throughout the process, update some weird networking configurations, testing with windows hypervisor platform feature installed or uninstalled.

The one thing I can't do is enable/disable hyper-V feature because (I think) I'm on Windows 10 Home, which doesn't have hyper-V? (idk I just read it on this page https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements) 

Though if I uninstall WSL completely I get information in my systeminfo that says hyper-v is up and running correctly, which is weird. With WSL installed it only says that it has detected a hypervisor so it doesn't show hyper-v info.

System Info:
<img width="732" alt="hypervisor-detected" src="https://user-images.githubusercontent.com/3745225/130120177-4dae5390-8f96-4e3e-9e14-bc9de84957a9.png">

Window Features:
<img width="341" alt="windows-features" src="https://user-images.githubusercontent.com/3745225/130120568-011b0541-f3b7-49c7-a51a-77b635e21c1e.png">

I can't include the .etl file because github doesn't support it, I'll try to run through that weird feedback workflow.

Been stuck on this for at least 2 months, would love to get some of my projects back that are stuck on WSL. Any help is greatly appreciated. Thanks!

**Comment by Manguil** [comment]
Hello, I have the same problem except that my computer does not restart and runs the automatic recovery.

**Comment by jbciardi** [comment]
Lol, after this long, I just upgraded to windows 11 and now it works fine, i can even use the GUI apps which is cool too. I never figured out what caused the original error tho, wish I did.

**Comment by bacchus101** [comment]
Having the exact opposite issue. I upgraded to windows 11 on the same hardware, with the exact same settings and now getting - Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

Virtualization is enabled. The linux subsystem is installed. Ubuntu is installed. Not sure what else I can do. Been running this for years without issue before the change to windows 11.

**Comment by AlienXAXS** [comment]
Hi, I am also having the same issue on Windows 11.

Feedback: https://aka.ms/AAf0rot

**Comment by HunterZ** [comment]
Same issue on Windows 11 Home. If I turn off the hypervisor via bcdedit, it shows all required features available. Setting it back to auto with WSL, VM Platform, and Hypervisor Platform features enabled (and, yes, toggled many times) and rebooting results in Event Log showing failure to run WSL2 due to Hyper-V not installed on host.

**Comment by JuanTorchia** [comment]
Same issue here windows 11

![image](https://user-images.githubusercontent.com/54363948/146696232-0f2c8b38-5bb1-4d3a-8e6f-339cc0fd44e7.png)

![image](https://user-images.githubusercontent.com/54363948/146696254-ea87dd78-0b8f-45c3-9059-85ecaf611820.png)

![image](https://user-images.githubusercontent.com/54363948/146696267-bc040b83-65ae-4be7-92c7-1f69965c0080.png)

**Comment by swanserquack** [comment]
Guess I'm going to be another person to hop on this band of people reporting this. Same issue here, the same error message and everything enabled and setup. Guess this is just going to be ignored.

**Comment by lonestriker** [comment]
I had this same error as well.  Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated.  But still could not get WSL2 to work after many updates and reboots.  

What fixed my problem in the end was:
* Open Control Panel -> Programs -> Turn Windows features on or off
* Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
* Reboot
* Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
* Reboot
* Open a Administrator Powershell and run:
`wsl --set-default-version 2`
`wsl --install -d Ubuntu`
* And it finally worked

Hope that helps others.

**Comment by markjasper** [comment]
This worked for me. Enable Hypervisor using; bcdedit /set hypervisorlaunchtype auto

**Comment by Amondale** [comment]
@markjasper if you are running VirtualBox this setting may work to re-enable wsl, but it will cause some severe issues with VirtualBox (and Hyper-V as I recall).

**Comment by ANIWAIFUS** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 ?? ??????? ????????? ??????????? ??????, ????????? ??????????? ??????? ?? ???????????.

guys what to do with it?

**Comment by JuanTorchia** [comment]
> Error: 0x80370102

Make sure virtualization is enabled within the computer's BIOS. Instructions on how to do this will vary from computer to computer and this feature will most likely be under CPU related options.
WSL2 requires that the CPU support the Second Level Address Translation (SLAT) feature, which was introduced in Intel Nehalem (1st generation Intel Core) and AMD Opteron processors. Older CPUs (such as Intel Core 2 Duo) will not be able to run WSL2, even if the virtual machine platform is installed correctly.

**Comment by kondas** [comment]
Hello, I get the same error on a fresh installed updated Windows 10 Home. Enabled Virtualization, none of the distributions can be started.

**Comment by MADM1k33** [comment]
> I had this same error as well. Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated. But still could not get WSL2 to work after many updates and reboots.
> 
> What fixed my problem in the end was:
> 
> * Open Control Panel -> Programs -> Turn Windows features on or off
> * Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Open a Administrator Powershell and run:
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * And it finally worked
> 
> Hope that helps others.

That helped - thanks!

**Comment by MediaMaquina** [comment]
> I had this same error as well. Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated. But still could not get WSL2 to work after many updates and reboots.
> 
> What fixed my problem in the end was:
> 
> * Open Control Panel -> Programs -> Turn Windows features on or off
> * Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Open a Administrator Powershell and run:
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * And it finally worked
> 
> Hope that helps others.

Thanks woohoo!!!!!!!!

**Comment by davidmold** [comment]
This doesn't work. I have done tried every recommended method. I have a brand new windows 11 machine it is June 2024. Why is this so hard?

**Comment by JoshuaEA54** [comment]
> This doesn't work. I have done tried every recommended method. I have a brand new windows 11 machine it is June 2024. Why is this so hard?

Have you found a solution yet?

**Comment by davidmold** [comment]
> > This doesn't work. I have done tried every recommended method. I have a brand new windows 11 machine it is June 2024. Why is this so hard?
> 
> Have you found a solution yet?

Yes. It is nearly always some weird bios setting that is the problem.

**Comment by SandroCast** [comment]
> Eu tive esse mesmo erro também. A virtualização estava habilitada no BIOS, a aba Desempenho do Gerenciador de Tarefas mostrou que estava ativada. Mas ainda não consegui fazer o WSL2 funcionar depois de muitas atualizações e reinicializações.
> 
> O que resolveu meu problema no final foi:
> 
> * Abra o Painel de Controle -> Programas -> Ativar ou desativar recursos do Windows
> * Desabilitar Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform e Windows Subsystem para Linux
> * Reinício
> * Reative os recursos que foram desabilitados: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform e Windows Subsystem for Linux
> * Reinício
> * Abra um PowerShell de administrador e execute:
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * E finalmente funcionou
> 
> Espero que ajude outros.

Funcionou perfeito. Muito obrigado!!

**Comment by Mozilan1216** [comment]
> I had this same error as well. Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated. But still could not get WSL2 to work after many updates and reboots.
> 
> What fixed my problem in the end was:
> 
> * Open Control Panel -> Programs -> Turn Windows features on or off
> * Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Open a Administrator Powershell and run:
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * And it finally worked
> 
> Hope that helps others.



> 我也遇到了同样的错误。BIOS 中启用了虚拟化，任务管理器性能选项卡显示它已激活。但经过多次更新和重启后，仍然无法让 WSL2 工作。
> 
> 最终解决我的问题的是：
> 
> * 打开控制面板 -> 程序 -> 打开或关闭 Windows 功能
> * 禁用 Hyper-V、虚拟机平台、Windows 虚拟机管理程序平台和适用于 Linux 的 Windows 子系统
> * 重启
> * 重新启用已禁用的功能：Hyper-V、虚拟机平台、Windows 虚拟机管理程序平台和适用于 Linux 的 Windows 子系统
> * 重启
> * 打开管理员 Powershell 并运行：
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * 终于成功了
> 
> 希望这对其他人有帮助。

That works!Thank for your help.I've tried for the whole day!

**Comment by sergiodevelop78** [comment]
> I had this same error as well. Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated. But still could not get WSL2 to work after many updates and reboots.
> 
> What fixed my problem in the end was:
> 
> * Open Control Panel -> Programs -> Turn Windows features on or off
> * Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Open a Administrator Powershell and run:
>   `wsl --set-default-version 2`
>   `wsl --install -d Ubuntu`
> * And it finally worked
> 
> Hope that helps others.

This worked well !! Thank you.
