### ISSUE TITLE
Input/output error on partitions mounted in empty NTFS folders

### ISSUE THREAD

**Issue by gamesharkmike** [microsoft/WSL#7164]
# Windows Build Number

Microsoft Windows [Version 10.0.19042.1052]

# WSL Version

- [ ] WSL 2
- [X] WSL 1

# Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

# Distro Version

Fedora Remix v33 ,  Also tested on Ubuntu

# Repro Steps

### Ex. C:\zzz
![Screenshot 2021-07-09 135005](https://user-images.githubusercontent.com/6124851/125129956-67368880-e0bd-11eb-8895-c285688c4ddf.png)

### Ex. /mnt/c/zzz
```
ls /mnt/c/zzz
ls: cannot access '/mnt/c/zzz': Input/output error
```

# Expected Behavior

Expected behavior: Users should be able to access the partition's folder on WSL's mount point. Ex. ls command should show files and folders.

# Actual Behavior

Actual behavior (Problem): Cannot access the partition's WSL mount point with error "Input/output error"
```
ls: cannot access '/mnt/c/zzz': Input/output error
```

**Comment by craigloewen-msft** [comment]
Can you please take logs for this issue? /logs

**Comment by phoerious** [comment]
@craigloewen-msft Can you reopen this please? It seems to be a general issue, also on WSL 2.
I'm on Windows 11 now and somehow I don't have the feedback hub app that your bot linked to, but I can give you additional details if needed.

The problem is as follows: I can mount folder-mounted NTFS volumes, no problem, but I cannot access any NTFS folders that are already mounted on the host.

For example, I have mounted a storage space at `D:` and also at `%USERPROFILE%/Data`. In WSL when I try to list the folder contents, I only get 
```console
$ ls Data
ls: cannot access 'Data': Input/output error
```
I also cannot mount anything on top of this "dead" folder:
```console
$  sudo mount -t drvfs D: Data
<3>init: (882) ERROR: MountPlan9WithRetry:285: mount drvfs on Data (cache=mmap,rw,msize=262144,trans=virtio,aname=drvfs;path=D:;symlinkroot=/) failed: 5
mount: I/O error
```
Bind-mounting the drive letter mount (or anything else for that matter), isn't possible either:
```console
$ sudo mount -o bind /d Data
mount: Data: can't read superblock on /d.
```

**Comment by terry548** [comment]
> 

I've met the same issue. Any solution for this plz? @phoerious

**Comment by phoerious** [comment]
Unfortunately not.
