### ISSUE TITLE
can not use ctrl+/ (undo) in bash

### ISSUE THREAD

**Issue by chain710** [Microsoft/WSL#728]
ctrl+/ (undo) keyboard shortcut does not work in bash
windows build number: 14393.10

**Comment by fpqc** [comment]
I suggest using an external terminal like rxvt-unicode-256color through vcXsrv at the moment.  The Windows console is still not always up to scratch (iirc there are all kinds of unimplemented escape sequences and also bugs from the built-in UTF-16 to UTF-8 conversion taking place.

**Comment by shlomme** [comment]
Same here. It seems like the keystroke doesn't make it to the running program at all. C-h k in emacs doesn't detect anything when pressing C-/.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
