### ISSUE TITLE
kernel messages are not printed to cmd when they should

### ISSUE THREAD

**Issue by github348** [microsoft/WSL#7281]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Repro Steps

create .wslconfig file with the following contents 
<code>
[wsl2]
<br>
kernelCommandLine=earlyprintk=/dev/ttyS0 console=/dev/ttyS0
</code>
<br>
run wsl --shutdown 
start wsl again 

### Expected Behavior

kernel messages displayed on cmd 

### Actual Behavior

no kernel boot messages displayed

**Comment by cerebrate** [comment]
That's because you aren't on the console when you're interacting with WSL normally. You're on a pseudo-TTY at `/dev/pts/{n}`.

If you want to see the actual console output (including all the kernel boot messages, and so forth, that is usually sent to `/dev/tty0`), you need to enable the debug console by putting

```
[wsl2]
debugConsole=true
```

in your .wslconfig. No kernel command line options required.

(Since the WSL 2 standard kernel doesn't include serial console support - and more importantly, since the WSL2 not-a-VM doesn't support serial ports anyway - serial console-fu, including earlyprintk, is right out.)
