### ISSUE TITLE
Enable using host's .ssh folder

### ISSUE THREAD

**Issue by ashic** [Microsoft/WSL#731]
I tried creating a symlink from /mnt/e/ashic/.ssh to ~/.ssh. The symlink works, but if I try to ssh with it, I get 

```
Bad owner or permissions on /home/ashic/.ssh/config
```

I tried to chown the the config file, but as it's on a mount, it doesn't change the permissions. I tried creating a symlink, and changing the permissions on the symlink. The permissions do change, but I still get the Bad Owner issue. It'd be great if we could allow such owenership modifications, or have some other way to use a shared .ssh folder.

**Comment by fpqc** [comment]
DriveFS doesn't support linux-style permissions or symlinking from the user home's special FS right now, I think.

**Comment by ashic** [comment]
Interesting... do you know where in the host machine the ubuntu folders might be located?

**Comment by fpqc** [comment]
The location of `/home` is 
`%localappdata%\lxss\home`

**Comment by MadLittleMods** [comment]
Related to https://github.com/Microsoft/BashOnWindows/issues/149

**Comment by rodrymbo** [comment]
It can be tricky to get the permissions set up properly on ~/.ssh without symlinks, because things like private keys and authorized_keys are there, and it relies on those (unix) permissions for security. Having other users able to read and/or change those files would be a huge problem. So sshd checks the permissions and is **extraordinarily** picky. 

When I have had occasion to edit files in .ssh in linux, I frequently have to fix permissions so sshd is happy. That's without using symlinks or other fancy techniques.

On the other hand, the files in ~/.ssh aren't that big, and you shouldn't need to mess with them that often. Maybe you could just leave them in ~/.ssh without symlinks?

If you need to edit them from Windows, you could do so in DriveFS somewhere, then copy them into .ssh and then check permissions. But in any case, the "and then check permissions" is pretty much mandatory any time you do anything with ~/.ssh .

**Comment by fpqc** [comment]
@rodrymbo yep that's exactly why it gets deleted.

**Comment by therealkenc** [comment]
This was addressed in [17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063). #81 and friends.
