### ISSUE TITLE
Composant : 'Plateforme d'ordinateur virtuel' Error: 0x800f0819

### ISSUE THREAD

**Issue by Arma713** [microsoft/WSL#7317]
Hello

I have this error when I use wsl --install after 70%

**Comment by licanhua** [comment]
Open PowerShell as Administrator and run:
```
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```
which may provide more information.

Although it's not the same error code, you may still need to check: [Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS](
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed)

**Comment by devin55533** [comment]
not work
