### ISSUE TITLE
wsl2 install errror0x80041002

### ISSUE THREAD

**Issue by micenote** [microsoft/WSL#7404]
### Windows Build Number

Microsoft Windows [版本 10.0.19043.1202]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu18.04

### Repro Steps

1.wsl --set-default-version 2
2.Install Ubuntu18.04 in MS store
3.Installing.....Error:0x80041002
-----------------------------------
1.wsl --set-default-version 1
2.Install Ubuntu18.04 in MS store
3.Install succeed!
4.wsl --set-version Ubuntu18.04 2
5.Error:0x80041002

### Expected Behavior

Bug?

### Actual Behavior

I'm crazy!!!!

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/7118125/wsl.zip)

**Comment by benhillis** [comment]
Looks like a failure to create the virtual network, I'll forward this along to my networking counterparts.

**Comment by Keith-Mange** [comment]
Is the "Virtual Machine Platform" installed?

What does "sc.exe qc vmsmp" show?

**Comment by micenote** [comment]
> Is the "Virtual Machine Platform" installed?
> 
> What does "sc.exe qc vmsmp" show?

installed vmware.
but uninstall vmware error 0x80041002 still exist.

**Comment by micenote** [comment]
> Is the "Virtual Machine Platform" installed?
> 
> What does "sc.exe qc vmsmp" show?

installed vmware.
but uninstall vmware error 0x80041002 still exist.

**Comment by Keith-Mange** [comment]
We need more tracing to understand the failure.  Can you try the following:
1) Reboot
2) https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/starthnstrace.ps1
3) Repro the problem
4) Stop the tracing in step 2.
5) https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1

The tracing step 2 will tell us more about what went wrong.  It includes some key providers missing from wsl.zip.

The logs in step 5 will tell us more about the state of the machine.

Thanks!

**Comment by micenote** [comment]
> We need more tracing to understand the failure. Can you try the following:
> 
> 1. Reboot
> 2. https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/starthnstrace.ps1
> 3. Repro the problem
> 4. Stop the tracing in step 2.
> 5. https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1
> 
> The tracing step 2 will tell us more about what went wrong. It includes some key providers missing from wsl.zip.
> 
> The logs in step 5 will tell us more about the state of the machine.
> 
> Thanks!

[collectlogs.ps1.zip](https://github.com/microsoft/WSL/files/7129289/collectlogs.ps1.zip)
[server.zip](https://github.com/microsoft/WSL/files/7129290/server.zip)

execute collectlogs.ps1 have many error.

**Comment by Keith-Mange** [comment]
Something is interfering with virtual NIC creation.  Can you upload the files in C:\Windows\Logs\NetSetup?

**Comment by micenote** [comment]
> Something is interfering with virtual NIC creation. Can you upload the files in C:\Windows\Logs\NetSetup?

[NetSetup.zip](https://github.com/microsoft/WSL/files/7132448/NetSetup.zip)

**Comment by micenote** [comment]
??????

**Comment by maxboone** [comment]
> Is the "Virtual Machine Platform" installed?
> 
> What does "sc.exe qc vmsmp" show?

I'm running into a similar issue, and do have the "Virtual Machine Platform" installed. However:

```
> sc qc vmsmp
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.
```

Is the `vmsmp` service only available under Hyper-V?

**Comment by Keith-Mange** [comment]
Regarding the NIC creation problem, I've re-asked a partner team here to take a look.

The virtual machine platform should install the hyper-v virtual switch even without Hyper-V.  "vmsmp" might not be the best way to detect that, however, because it only starts when WSL launches.  Try "sc query vmsp"

**Comment by Keith-Mange** [comment]
Regarding the NIC creation problem, a VMWare component appears to be blocking the NIC creation.  If it's still installed, you can try removing the VMWare product.  However, we have seen that even uninstalling it won't always help because they leave behind some cruft.  If you have already uninstalled, a network reset may purge it.  However, that purge may not even be sufficient.  We've reached out to VMWare in the past on the issue but haven't gotten any traction with them.

**Comment by maxboone** [comment]
`sc query vmsp` is indeed showing an installed (and running) kernel driver.

When I try to start WSL version 2 and subsequently run `sc query vmsmp` or `sc query vmsp` it doesn't show either. Even after a clean re-install of Windows, is there a way that I can check (aside from `sfc` or re-enabling the feature with a reboot inbetween) if VMP is still installed correctly?

Or should I be able to figure out what's going wrong from the same logging, as in, if something is blocking the creation of the virtual NICs?

Not trying to hijack this thread, but I think the issue is really similar and another issue was closed with a "we're backporting some stuff" while I'm on the latest version of Windows Insider Builds 😅.

**Comment by Keith-Mange** [comment]
Is c:\Windows\system32\drivers\vmswitch.sys present?

**Comment by maxboone** [comment]
> Is c:\Windows\system32\drivers\vmswitch.sys present?

Yes, present:
`0dd13e65d51b89a25399528c0c7216581a8f99e834f179d5aa88170442835c07  vmswitch.sys`
`-a----         9/11/2021   2:14 PM        2275104 vmswitch.sys`

**Comment by maxboone** [comment]
I see that the [latest build](https://blogs.windows.com/windows-insider/2021/09/22/announcing-windows-11-insider-preview-build-22463/) contains fixes for specifically Hyper-V and WSL not running on ARM64. Hopefully that fixes it.

**Comment by micenote** [comment]
> Regarding the NIC creation problem, a VMWare component appears to be blocking the NIC creation. If it's still installed, you can try removing the VMWare product. However, we have seen that even uninstalling it won't always help because they leave behind some cruft. If you have already uninstalled, a network reset may purge it. However, that purge may not even be sufficient. We've reached out to VMWare in the past on the issue but haven't gotten any traction with them.
> 
> It's also possible a 3rd party anti virus is blocking access to reg keys that need to change.

reinstall system can it be solved?

**Comment by Keith-Mange** [comment]
That should work as long as the offending 3rd party software isn't re-installed.
