### ISSUE TITLE
Roadmap for WSL2 --mount command on stable channel

### ISSUE THREAD

**Issue by mentor-akhalid** [microsoft/WSL#7452]
Hi, was just wondering whether the wsl --mount command would be available in windows 10? Or with the release of windows 11 on October 5 2021? If not then when would it be available in the stable channel?

Thanks

**Comment by benhillis** [comment]
No plans to backport but it will be available in Windows 11.

**Comment by Philipp91** [comment]
That's sad, considering the new hardware requirements of Windows 11.

**Comment by Biswa96** [comment]
But it may be possible to build/make/develop your own tool which can do that. Need some test subjects 🐭

**Comment by Philipp91** [comment]
Sure, if it's open-source and I can review the code in reasonable time.

**Comment by Biswa96** [comment]
⚠️ I am not sure if this breaks anything ⚠️ 

Here is some way to attach disk in WSL2. I have not think of an actual tool. This is just a working concept. The C code is this:

```c
#include <windows.h>
#include <computecore.h>
#include <computenetwork.h>

#pragma comment(lib, "computecore")
#pragma comment(lib, "computenetwork")

int main(void)
{
    HRESULT hRes;
    HCS_OPERATION hcsOp;
    HCS_SYSTEM hcsSystem;
    PWSTR result;

    const wchar_t Disk[] = LR"(
    {
        "ResourcePath":"VirtualMachine/Devices/Scsi/0/Attachments/1",
        "RequestType":"Add",
        "Settings": {
            "Type":"PassThru",
            "Path":"\\\\.\\PHYSICALDRIVE2"
        }
    })";

    PCWSTR VmId = L"E9258C25-E850-4E5A-A117-5D39893646F0";

    hcsOp = HcsCreateOperation(NULL, NULL);
    hRes = HcsOpenComputeSystem(VmId, GENERIC_ALL, &hcsSystem);
    hRes = HcsGrantVmAccess(VmId, L"\\\\.\\PHYSICALDRIVE2");
    hRes = HcsModifyComputeSystem(hcsSystem, hcsOp, Disk, NULL);
    hRes = HcsWaitForOperationResult(hcsOp, INFINITE, &result);
    wprintf(L"result: %ls", result);
    HcsCloseOperation(hcsOp);
    HcsCloseComputeSystem(hcsSystem);

    return 0;
}
```

### Assumptions & Variables:

1. The GUID `VmId` variable can be retried from `hcsdiag list` command.
2. The `\\\\.\\PHYSICALDRIVE2` string can be retrieved from this [official docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk).
3. The `Scsi/0/Attachments/1` assumes that there is only one block device (/dev/sda) in WSL2 VM.
4. Make the disk offline in Disk Management before this. Otherwise the `result` will show an error.

**Comment by Philipp91** [comment]
Cool! It succeeds for me, up to the `HcsWaitForOperationResult()` line, which returns 0x80070057 ("The parameter is incorrect"?) and writes sixteen zeros to `result`.

I picked `\\\\.\\PHYSICALDRIVE0` and my `VmId` and I'm quite confident that they're correct. The `VirtualMachine/Devices/Scsi/0/Attachments/1` I left the same, not sure how this stuff works. But the disk (physical drive 0) that I'm trying to mount only has a single partition on it.

**Comment by Biswa96** [comment]
There are some IOCTLs used in LxssManager with disk device. I need to decode it also.
