### ISSUE TITLE
Can't apt-get update Kali Linux in WSL

### ISSUE THREAD

**Issue by gasayminajj** [microsoft/WSL#7491]
### Windows Build Number

Version 10.0.19042.1237

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Linux DESKTOP-5UAV41V 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

### Repro Steps

I can't install anything in kali, but ubuntu works. Please help me!

### Expected Behavior

![изображение](https://user-images.githubusercontent.com/59529138/136027263-16670763-77d9-4bbd-9561-f2373a38f736.png)

### Actual Behavior

sudo apt-get update
[sudo] password for gasay:
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Ign:2 http://http.kali.org/kali kali-experimental InRelease
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Ign:2 http://http.kali.org/kali kali-experimental InRelease
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Ign:2 http://http.kali.org/kali kali-experimental InRelease
Err:1 http://http.kali.org/kali kali-rolling InRelease
  Temporary failure resolving 'http.kali.org'
Err:2 http://http.kali.org/kali kali-experimental InRelease
  Temporary failure resolving 'http.kali.org'
Reading package lists... Done
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  Temporary failure resolving 'http.kali.org'
W: Failed to fetch http://http.kali.org/kali/dists/kali-experimental/InRelease  Temporary failure resolving 'http.kali.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by MJ-EMIS** [comment]
Found that the issue is due to the WSL image referring to loopback to get DNS routed via the host machine and something like Next Gen-AV is getting in the way of allowing the DNS resolution (so much for next gen-av being "smart".) 

How I fixed it was to point to a different DNS and you can do it by doing the following:

1. Run `sudo nano /etc/resolv. conf` to change the target DNS server
2. In nano overwrite the listed IP (this will be the WSL loopback IP) to your preferred DNS e.g. local DNS server, internet gateway/router or public DNS
3. Press Ctrl+X to exit
4. When prompted press Y and enter to commit write
5. When prompted for filename hit enter to overwrite original file
6. Run `sudo apt-get update` again

**Comment by CelvinBraun** [comment]
Had the same issue. Was trying out following things: https://kalitut.com/how-to-update-kali-linux-and-fix-update/ (Those could solve the issue)
-> At the end the instance decided to magically work, after several times unregistering/rebooting it!

**Comment by BrijeshJagad** [comment]
By changing repo form,

> deb http://http.kali.org/kali kali-rolling main non-free contrib

to ,

> deb https://http.kali.org/kali kali-rolling main non-free contrib

( secure HTTPS)
in file /etc/apt/sources.list fixed my issue.

**Comment by BrijeshJagad** [comment]
By changing repo form,

`deb http://http.kali.org/kali kali-rolling main non-free contrib`

to ,

`deb https://http.kali.org/kali kali-rolling main non-free contrib`

( secure HTTPS)
in file /etc/apt/sources.list fixed my issue.
