### ISSUE TITLE
Revert "by design" behaviour Interop fail once spawning shell closed to the old way so that long running processes do not lose access

### ISSUE THREAD

**Issue by lucyllewy** [microsoft/WSL#7560]
### Version

Microsoft Windows [Version 10.0.22471.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43.3-microsoft-snapd

### Distro Version

Ubuntu 20.04

### Other Software

`ssh-agent` from Windows 11 OOTB set to automatic start on boot.
`socat` in the distro from their package manager
`npiperelay` from https://github.com/NZSmartie/npiperelay

### Repro Steps

Install `npiperelay` from https://github.com/NZSmartie/npiperelay to a location that you can access and copy the path

Enable and start the ssh-agent service in Windows:
```powershell
Set-Service -Name ssh-agent -StartupType Automatic
Start-Service -Name ssh-agent
```

Verify the ssh-agent service is correctly started before continuing:
```powershell
Get-Service -Name ssh-agent
```

Start WSL2 session, and execute:
```
sudo apt-get install -y socat
socat UNIX-LISTEN:$HOME/.ssh/agent.sock,fork EXEC:/mnt/c/path/to/npiperelay.exe -ei -ep -s //./pipe/openssh-ssh-agent,nofork
```

Create and add an ssh key to the agent:
```
ssh-keygen
ssh-add
```

Verify the key has been added to the agent:
```
ssh-add -l
```

The failure occurs in this step: *Close the __terminal__ (do __not__ terminate WSL2 distro __nor__ shutdown WSL2 entirely) session to WSL2* and open a new one. Then, recheck the agent for your key in the new session:
```
ssh-add -l
```

### Expected Behavior

The ssh-agent should continue to respond when the initial socat-spawning sesssion has exited leaving behind the socat process in the background:

```
$ ssh-add -l
2048 SHA256:[removed from paste for privacy/security] /home/dllewellyn/.ssh/id_rsa (RSA)
```

### Actual Behavior

This appears to have resurfaced recently, where it was fixed for issue #2414.

The ssh-agent will fail to respond to queries in any session after the initial socat-spawning session has exited leaving behind the socat process in the background:

```
$ ssh-add -l
error fetching identities: communication with agent failed
```

**Comment by Biswa96** [comment]
Probably the Linux kernel is different than what is used in WSL2.

**Comment by diddledani** [comment]
no, @Biswa96 that is not the issue. it fails with the default kernel, too

**Comment by benhillis** [comment]
@diddledani - This is expected, WSL2 instances are terminated when the session that created them exits. The previous behavior was not intended.

**Comment by diddledani** [comment]
I'm not sure that it is widely expected that a long-running process loses access to resources that it initially has access to just by virtue of the user closing the shell that started the long-running process. I'd like to petition to revert this behaviour to the "not intended" state because that is what users expect.

**Comment by DaveWK** [comment]
There is a workaround for this particular example (as described at: https://github.com/rupor-github/wsl-ssh-agent) -- adding a script to the bash_profile to check if the socat socket is working and recreating it in the background if it isn't in-place. 
add:
```
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0   ]; then
    rm -f $SSH_AUTH_SOCK
    ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"/mnt/c/<Wherever you put this file>/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork & ) >/dev/null 2>&1
fi
```
There used to be an advertised ability to use AF_UNIX within WSL (see: https://devblogs.microsoft.com/commandline/windowswsl-interop-with-af_unix/ ) which no longer works, so it isn't possible any more to start the socket on the windows side, and share it with WSL.
It would be nice if instead of having socat initiate the npiperelay.exe inside WSL, AF_UNIX support worked again, and windows could start the unix socket independently of WSL, and share it into WSL, as I think it's probably better security/safer to have windows initiate any pipes/sockets rather than having pipes/sockets initiated from WSL back into windows.

**Comment by diddledani** [comment]
@DaveWK that doesn't help, because the sockets __are__ still listening in the now closed session. My point here is that WSL2 has not terminated, and the backgrounded tasks are still running, but they are not able to continue doing their job because WSL2 has killed the relevant WSL_INTEROP socket.

Again for completeness and to clear up confusion:

1. Start WSL2 (this is session 1)
2. Start socat forwarding to a file-based pipe (GPG-agent in my case)
3. Start a new WSL2 bash session alongside session 1 (this is session 2)
4. Close session 1 leaving session 2 running
5. observe that the sockets are still in-place and the socat process is still active
6. Try to use gpg in session 2 but fail because WSL_INTEROP has been killed even though there are still active processes
