### ISSUE TITLE
running Windows process from the background opens a new terminal window in WSL preview

### ISSUE THREAD

**Issue by sakai135** [microsoft/WSL#7568]
### Version

Microsoft Windows [Version 10.0.22478.1012]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

WSL version: 0.48.2.0

### Repro Steps

Run the following command:
```
wsl.exe start-stop-daemon --background --exec /mnt/c/WINDOWS/system32/ping.exe --start -- -t example.com
```

### Expected Behavior

I expect ping.exe to run in the background without opening a cmd window like in the current (non-preview) WSL.

### Actual Behavior

With WSL preview (0.48.2.0), the command opens a new terminal for ping.exe.

**Comment by sakai135** [comment]
Just to update that this is still an issue with the new update:
```
WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29
Windows version: 10.0.22499.1010
```

**Comment by allusernamestakenexceptthis** [comment]
I have the same issue with same versions. except in my case I experienced by running shell_exec commands from php running in wsl to run an exe file . and it led to a wsl terminal to open.  doesn't happen with shell commands only windows commands. such as cmd.exe route.exe  ..etc  running the same commands from inside an opened wsl terminal doesn't open new one.  only from the background.

I tried to put the script inside a .sh file and run the sh file from php. but same results.

I can confirm that I didn't experience the problem before preview from the store. but my kernel was very outdated and custom.

**Comment by OneBlue** [comment]
@sakai135 I had a deeper look and I could reproduce the problem. 

This situation this is basically a race between the time the 'ping.exe' process is created and the wsl 'process group' being terminated.
When a Windows process is created, if the 'wsl.exe' that created the session is still running, then this process creates the Windows process.

If this 'wsl.exe' has terminated, then the process is created by wslhost.exe, which isn't attached to the console, which is why ping.exe creates a window as you reported.

So if you do:

```
$ wsl.exe start-stop-daemon [...]
```

wsl.exe might terminate before the process actually starts on the Windows side. If you do:

```
$ wsl.exe
[wsl] $ start-stop-daemon [...]
```

Then the issue doesn't apply because the wsl process group doesn't terminate.

I need to give some thoughts to this, I'll update this issue when I'll have a solution in mind.
