### ISSUE TITLE
Failed to start redis-server on wsl boot

### ISSUE THREAD

**Issue by remainfox** [microsoft/WSL#7633]
### Version

Microsoft Windows [版本 10.0.19043.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 18.04

### Other Software

# redis版本
```
Redis server v=6.2.4 sha=00000000:0 malloc=libc bits=64 build=31bab94b7c80a0cb
```

### Repro Steps

# step 1
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp 加入 vbs脚本

# step2:
vbs脚本内容如下
```
Set ws = WScript.CreateObject("WScript.Shell")
ws.run "wsl sudo /etc/init.wsl start", vbhide
```
# step3
在wsl的/etc目录，新建init.wsl文件

# step4
init.wsl内容如下
```
/usr/local/redis/start_redis_cluster.sh
```

# step5
start_redis_cluster.sh内容
```
#!/bin/sh
redis-server /usr/local/redis/conf/redis-6373.conf
redis-server /usr/local/redis/conf/redis-6374.conf
redis-server /usr/local/redis/conf/redis-6375.conf
redis-server /usr/local/redis/conf/redis-6376.conf
redis-server /usr/local/redis/conf/redis-6377.conf
redis-server /usr/local/redis/conf/redis-6378.conf
```

### Expected Behavior

# result
- 重启windows无法随机启动redis server
- 进入wsl控制台，手动执行start_redis_cluster.sh可以启动redis-server
- 不知道为什么不能随机启动，求助

### Actual Behavior

开机进程没有redis-server

### Diagnostic Logs

没有日志

**Comment by craigloewen-msft** [comment]
Hi, this issue is hard for me to understand as it is written in Chinese, a language that I don't speak. I ran it through a translator to help and I think I understand your issue.

You would like to start the redis server automatically on start up of your Windows machine. You can do this use Task Scheduler in Windows like [this community video shows](https://www.youtube.com/watch?v=ZQPknck1kmo). 

If this doesn't solve you please mention me in this issue so I can see it. Thank you!
