### ISSUE TITLE
ircii - only bottom 3 lines of terminal are used

### ISSUE THREAD

**Issue by sdaugherty** [Microsoft/WSL#766]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

The ancient, but still supported IRC client, ircii (and presumably, any derivatives such as EPIC and BitchX) runs, but once the display fills, it only uses the bottom 3 lines of the window (bottom line of the chat window, status bar, and input line), constantly overwriting the third line from the bottom with new text
- Expected results
  ircII should use the full screen, and new text should appear at the bottom, just above the status bar, pushing the text above up a line.
- Your Windows build number
  14393
- Steps / commands required to reproduce the error
  sudo apt-get install ircII
  ircII
  /server chat.freenode.net
- Strace of the failing command
  didn't try to get a strace, as it was a terminal handling issue and not a failure to start
- Required packages and commands to install
  See STR

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Console problem, launch it in urxvt running through vcXsrv (the Win32 port of x.org server).  There are a million guides on this issues page describing precisely how to do it.

**Comment by fpqc** [comment]
![2016-08-04 1](https://cloud.githubusercontent.com/assets/6083371/17410260/da61ab9a-5a40-11e6-8cee-2ca5a6a9d099.png)
![2016-08-04 2](https://cloud.githubusercontent.com/assets/6083371/17410259/da5a73e8-5a40-11e6-8884-811170b556a1.png)
![2016-08-04](https://cloud.githubusercontent.com/assets/6083371/17410258/da590c2e-5a40-11e6-8416-61f48c8f25a3.png)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
