### ISSUE TITLE
WSL corrupted VirtualBox (I think)

### ISSUE THREAD

**Issue by thissop** [microsoft/WSL#7665]
### Version

Microsoft Windows [Version 10.0.19042.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

I was working in my Ubuntu VM on VirtualBox and simultaneously trying to install WSL. My VM crashed along with 100 GB from two years of work on it which I believe is related to trying to install WSL. 

### Expected Behavior

I've tried removing all HYPER-V features, deleting Ubuntu that was downloaded for WSL, removing WSL (both from prompt and windows features), etc. 

### Actual Behavior

I wrote more about this on stack exchange: [link](https://stackoverflow.com/questions/69924154/wsl-ruined-virtualbox-vm-help)

**Comment by WSLUser** [comment]
If you're trying to run WSL2, then yes there's issue with Virtual Box. There's nothing to be done on the WSL2 end. It's entirely in the hands of the Virtual Box devs to update to work with WSL2. Otherwise you need to choose and WSL2 is the superior option between the 2. Create a tar file after booting with Virtual Box, then re-enable WSL2. Then import the tar file with the `wsl --import `command. Problem solved and now you have superior performance to before.

**Comment by thissop** [comment]
Hi!

Thank you for your email!

At the moment I'm not trying to get WSL to work but just trying to recover
the files in the virtualbox vm that I believe have been corrupted after I
turned WSL on ... even though I've since removed WSL and turned off all
hyper v things. What do you think?

*"Before I came here I was confused about this subject. Having listened to
your lecture I am still confused. But on a higher level."*
-Enrico Fermi

**Comment by Biswa96** [comment]
> just trying to recover the files in the virtualbox vm

This question will be off-topic here. BTW, 7zip can open some VirtualBox files. Alternatively, you can convert the virtual disk file to VHD or VHDX format and mount it in WSL2.

> WSL2 is the superior option between the 2

Think beyond those two options 😉

**Comment by thissop** [comment]
Thank you for your advice! I'm looking forward to just using WSL after I recover the data.
