### ISSUE TITLE
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

### ISSUE THREAD

**Issue by QThans** [microsoft/WSL#7716]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu 20.04

### Repro Steps

![image](https://user-images.githubusercontent.com/18275400/142586934-e73beb8c-c0ef-4896-b8e4-c6bd4f39673c.png)

When I used the installed Ubuntu (Microsoft store name, the version is 20.04) before, the result is COULD NOT communicate. Still, the Ubuntu that I installed the new Ubuntu 20.04 by Microsoft Store is regular and return the expected result. 

### Expected Behavior

![image](https://user-images.githubusercontent.com/18275400/142586833-d44cca54-a37a-4b62-9796-4c3cafa6ccb7.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/18275400/142586811-def11476-d204-447d-b827-194c29760c60.png)

**Comment by EdSeymore** [comment]
I am having the same problem with Windows 11, WSL2, Ubuntu 22.04, Driver NVIDIA-SMI 528.49

**Comment by QThans** [comment]
> I am having the same problem with Windows 11, WSL2, Ubuntu 22.04, Driver NVIDIA-SMI 528.49

Maybe you can create an new WSL2 instance, it is working for me.

![image](https://user-images.githubusercontent.com/18275400/227066733-255b89d7-e420-4be9-9078-7e8683f9470b.png)

**Comment by EdSeymore** [comment]
My environment: 
Three Ubuntu images on WSL2 with Windows 11: 
 - UBuntu 
 - Ubuntu-22.04
 - Ubuntu-20.04 

I Tried the following: 

 - close all ubuntu terminal sessions 
 - wsl --shutdown 
 - wsl -d Ubuntu-22.04                                                          : OK
 - Try: NVIDIA-SMI  [ed@mlSys23:/mnt/c/Users/EdSey]                             : OK 
   - NVIDIA-SMI 525.89.02 Driver Version: 528.49 CUDA Version: 12.0 
 - cd 
 - Try: NVIDIA-SMI                                                              : OK 
   - NVIDIA-SMI 525.89.02 Driver Version: 528.49 CUDA Version: 12.0 
 - wsl --shutdown 
 - wsl -d Ubuntu 
 - Try: NVIDIA-SMI  [ed@mlSys23:/mnt/c/Users/EdSey]                             : NF 

Since Ubuntu was woking in the past: 
 - I was running pyTorch with both CPU & GPU 
 - some sequence of events has caused the link from the display driver 
   to the Ubuntu image to be broken 

Since I have a couple of months of development on the Ubuntu image, 

Does anyone have thoughts on how to re-establish the linkage to the display 
driver for CUDA without removing the Ubuntu image and re-installing?
