### ISSUE TITLE
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by slavong** [microsoft/WSL#7746]
WSL stopped working. Switching Virtual Machine Platform and WSL on and off in Control Panel - Features did not help.

The same error when running wsl command in PS and CMD, even when running as admin.

**Comment by slavong** [comment]
could be solved by reinstalling WSL from Microsoft Store.

**Comment by Galactos-h** [comment]
### The problem was Kaspersky. The solution is simple Open cmd.exe and run the following code

```
sc config LxssManager start=auto
```
Kaspersky will give you a pop-up about a potential thread. Tell Kaspersky to ignore the alert. Please don't click on "Fix it" button for Kaspersky or you will undo the solution.

That should fix it

**Comment by Kewyn-Vieira** [comment]
> ### The problem was Kaspersky. The solution is simple Open cmd.exe and run the following code
> ```
> sc config LxssManager start=auto
> ```
> 
> Kaspersky will give you a pop-up about a potential thread. Tell Kaspersky to ignore the alert. Please don't click on "Fix it" button for Kaspersky or you will undo the solution.
> 
> That should fix it

I love you

**Comment by PatrickOtero** [comment]
> ### The problem was Kaspersky. The solution is simple Open cmd.exe and run the following code
> ```
> sc config LxssManager start=auto
> ```
> 
> Kaspersky will give you a pop-up about a potential thread. Tell Kaspersky to ignore the alert. Please don't click on "Fix it" button for Kaspersky or you will undo the solution.
> 
> That should fix it

Incredible. How have you encountered that solution?

**Comment by evelynhathaway** [comment]
I got the same error when a WSL upgrade must've failed while I was trying to provide information for #9534

I wasn't able to use WSL even after a restart. `wsl --update` also didn't work.

I don't have Kaspersky, so I tried installing the latest `msixbundle` from the [releases page](https://github.com/microsoft/WSL/releases). This fixed my issue and I no longer receive that error.

**Comment by MelekZmerli** [comment]
Use `sc.exe` instead of `sc` if you're encountering a positional argument when executing the command above.

**Comment by sefadogan** [comment]
> ### The problem was Kaspersky. The solution is simple Open cmd.exe and run the following code
> ```
> sc config LxssManager start=auto
> ```
> 
> Kaspersky will give you a pop-up about a potential thread. Tell Kaspersky to ignore the alert. Please don't click on "Fix it" button for Kaspersky or you will undo the solution.
> 
> That should fix it

it worked like a charm, thank you.

**Comment by Xenoxis** [comment]
Hello, I have the same problem but it isn't caused by a service disabled, i have tried to uninstall/repair and reset WSL and check if services like BITS or LxssManager were disable, they were not and I tried everything up to my knowledge to fix that.

I'm running WSL 2.0.9.0

I got this error everytime i'm trying to install a distribution using WSL : 
`Wsl/InstallDistro/0x80070422`

There are my log collected using the powershell tool when i attempted to reproduce the problem :
[WslLogs-2023-12-05_14-40-09.zip](https://github.com/microsoft/WSL/files/13561061/WslLogs-2023-12-05_14-40-09.zip)

**Comment by OneBlue** [comment]
@Xenoxis: You're most likely seeing this because the store is not available. Can you try running: 

```
wsl --install -d <distro> --web-download
```
instead ?

**Comment by Sieboldianus** [comment]
This did also not work for me because:

> To install this application you need either a Windows
developer license or a sideloading-enabled system.

What did it was the following:

1. Download latest AppX WSL manually from [WSL Releases](https://github.com/microsoft/WSL/releases)
2. Use Admin PowerShell and run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
3. This failed, for the following reason as stated above.
4. Enable Developer mode. Use `Show-WindowsDeveloperLicenseRegistration` (powerShell)
5. The Button is greyed out
6. Open Policies `gpedit.msc`
7. Go to Computer Configuration > Administrative Templates > Windows Components > 
  App Package Deployment.
    - Click "Allows development of Windows Store apps." 
    - Change to "Enabled"
8. Developer Mode should now be active
9. Run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
10. Works. Disable Developer mode in Policies

Afterwards, Docker-Desktop would start, including the Docker Engine.

**Comment by gitthangbaby** [comment]
> @Xenoxis: You're most likely seeing this because the store is not available. Can you try running:
> 
> ```
> wsl --install -d <distro> --web-download
> ```
> 
> instead ?

that parameter doesn't exist. But the way of downloading is described in [MS page](https://learn.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions). The list of manual downloads is different from what wsl --install reports, but the URLs work.

It's sad, since I don't have access to MS Store at home or work. It's firmly disabled everywhere I ever been to, so it's not good that we're reduced to use these "curl" methods.

**Comment by shallidesu** [comment]
> This did also not work for me because:
> 
> > To install this application you need either a Windows
> > developer license or a sideloading-enabled system.
> 
> What did it was the following:
> 
>     1. Download latest AppX WSL manually from [WSL Releases](https://github.com/microsoft/WSL/releases)
> 
>     2. Use Admin PowerShell and run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
> 
>     3. This failed, for the following reason as stated above.
> 
>     4. Enable Developer mode. Use `Show-WindowsDeveloperLicenseRegistration` (powerShell)
> 
>     5. The Button is greyed out
> 
>     6. Open Policies `gpedit.msc`
> 
>     7. Go to Computer Configuration > Administrative Templates > Windows Components >
>        App Package Deployment.
>        
>        * Click "Allows development of Windows Store apps."
>        * Change to "Enabled"
> 
>     8. Developer Mode should now be active
> 
>     9. Run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
> 
>     10. Works. Disable Developer mode in Policies
> 
> 
> Afterwards, Docker-Desktop would start, including the Docker Engine.

it works for me, thank you very much #

**Comment by MRAlirad** [comment]
> sc config LxssManager start=auto

it gives me the error:
 OpenService FAILED 1060:
The specified service does not exist as an installed service.

**Comment by mockinbirdy** [comment]
Nothing new, just microsoft forcing everyone to use their bloatware instead of clean, corporate systems. For those, who run older windows versions or don't have win store and need to set up wsl with docker, here is what worked for me:

https://stackoverflow.com/questions/59030287/how-can-i-install-wsl-without-windows-store
and
https://superuser.com/questions/1731365/updating-wsl-2-without-microsoft-store/1754527#1754527

**Comment by dascar5** [comment]
> @Xenoxis: You're most likely seeing this because the store is not available. Can you try running:
> 
> ```
> wsl --install -d <distro> --web-download
> ```
> 
> instead ?

this was it for me, I disabled the store a loooong time ago, thanks

**Comment by hunterhs92** [comment]
> ### The problem was Kaspersky. The solution is simple Open cmd.exe and run the following code
> ```
> sc config LxssManager start=auto
> ```
> 
> Kaspersky will give you a pop-up about a potential thread. Tell Kaspersky to ignore the alert. Please don't click on "Fix it" button for Kaspersky or you will undo the solution.
> 
> That should fix it

awesome!!

**Comment by lelas** [comment]
> ```
> sc config LxssManager start=auto
> ```

Brilliant, thank you. 

For someone else coming here with the issue and if running the above command doesn't do the trick for you, you might have to do the following afterwards: Open `Services`, right-click on `WSL Service` + `Properties` and then change `Startup type` from `Disabled` to `Automatic`. All other options than 'Disabled' were greyed out in my case before I ran `sc config LxssManager start=auto`.

**Comment by Hotziplotzi** [comment]
Similar to the Kaspersky solution mentioned above:
https://github.com/microsoft/WSL/issues/11628#issuecomment-2411796736
and it actually did solve my issue as well.

**So the problem cause is Avast One, specifically the Avast One service "Avast Cleanup" ("C:\Program Files\Avast Software\Cleanup\TuneupSvc.exe").**

Once I disable (set to just "manual" is not enough) this crap Avast service, the WSL service keeps autostarting and running.
The cleanup service also doesnt seem to be any crucial protection service but only related to "system tuning" which is less than important.

**Comment by kebench** [comment]
> ```
> sc config LxssManager start=auto
> ```


On Windows Version 24H2 (OS Build 26100.3476), the LxssManager doesn't exist anymore (as in my case). It's replaced by WSLService so just change the command to:

`sc config WSLService start=auto`

Run the command in an elevated cmd since when I run it on a normal cmd, it gave me an access denied error.

Alternatively, @lelas solution also works:

> > ```
> > sc config LxssManager start=auto
> > ```
> 
> Brilliant, thank you.
> 
> For someone else coming here with the issue and if running the above command doesn't do the trick for you, you might have to do the following afterwards: Open `Services`, right-click on `WSL Service` + `Properties` and then change `Startup type` from `Disabled` to `Automatic`. All other options than 'Disabled' were greyed out in my case before I ran `sc config LxssManager start=auto`.

**Comment by Ajtimstoj** [comment]
> This did also not work for me because:
> 
> > To install this application you need either a Windows
> > developer license or a sideloading-enabled system.
> 
> What did it was the following:
> 
> 1. Download latest AppX WSL manually from [WSL Releases](https://github.com/microsoft/WSL/releases)
> 2. Use Admin PowerShell and run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
> 3. This failed, for the following reason as stated above.
> 4. Enable Developer mode. Use `Show-WindowsDeveloperLicenseRegistration` (powerShell)
> 5. The Button is greyed out
> 6. Open Policies `gpedit.msc`
> 7. Go to Computer Configuration > Administrative Templates > Windows Components >
>    App Package Deployment.
>    
>    * Click "Allows development of Windows Store apps."
>    * Change to "Enabled"
> 8. Developer Mode should now be active
> 9. Run `Add-AppxPackage ./Microsoft.WSL_2.0.15.0_x64_ARM64.msixbundle`
> 10. Works. Disable Developer mode in Policies
> 
> Afterwards, Docker-Desktop would start, including the Docker Engine.

Thank you very much, it works 👍

**Comment by arafatruetbd** [comment]
**Title: WSL integration with Docker fails (0xffffffff) — Fixed by uninstalling CCleaner and resetting Ubuntu**

Hi all,

I encountered the following error when trying to use Docker with WSL:

```
WSL integration with distro 'Ubuntu' unexpectedly stopped.
configuring docker in Ubuntu: docker cli config: failed to write file: exit status 0xffffffff
```

### What didn't work:

* `wsl --install -d Ubuntu` failed with `ERROR_ALREADY_EXISTS`
* Docker integration kept failing
* Restarting WSL, Docker, or enabling integration again didn’t resolve it

### What worked for me:

1. **Uninstalled CCleaner** (which may have interfered with WSL or Docker file operations)
2. **Reset Ubuntu** via `Settings > Apps > Ubuntu > Advanced Options > Reset`

After these steps, Docker Desktop successfully integrated with WSL, and everything started working as expected.

I’m sharing this here in case others run into the same issue. Possibly a conflict between CCleaner and WSL/Docker’s file handling or permissions.

**Comment by patrickhartono** [comment]
> **Title: WSL integration with Docker fails (0xffffffff) — Fixed by uninstalling CCleaner and resetting Ubuntu**
> 
> Hi all,
> 
> I encountered the following error when trying to use Docker with WSL:
> 
> ```
> WSL integration with distro 'Ubuntu' unexpectedly stopped.
> configuring docker in Ubuntu: docker cli config: failed to write file: exit status 0xffffffff
> ```
> 
> ### What didn't work:
> * `wsl --install -d Ubuntu` failed with `ERROR_ALREADY_EXISTS`
> * Docker integration kept failing
> * Restarting WSL, Docker, or enabling integration again didn’t resolve it
> 
> ### What worked for me:
> 1. **Uninstalled CCleaner** (which may have interfered with WSL or Docker file operations)
> 2. **Reset Ubuntu** via `Settings > Apps > Ubuntu > Advanced Options > Reset`
> 
> After these steps, Docker Desktop successfully integrated with WSL, and everything started working as expected.
> 
> I’m sharing this here in case others run into the same issue. Possibly a conflict between CCleaner and WSL/Docker’s file handling or permissions.

Yes, I can confirmed! Once I uninstall CCleaner WLS works perfectly! But on top of that I also added Ubuntu.exe, WLS, WSL config into Norton's whitelist

**Comment by karpado** [comment]
> I got the same error when a WSL upgrade must've failed while I was trying to provide information for [#9534](https://github.com/microsoft/WSL/issues/9534)
> 
> I wasn't able to use WSL even after a restart. `wsl --update` also didn't work.
> 
> I don't have Kaspersky, so I tried installing the latest `msixbundle` from the [releases page](https://github.com/microsoft/WSL/releases). This fixed my issue and I no longer receive that error.

I have Kaspersky, but the Kaspersky fix(Suggested by others) didn't work in my case. Installing wsl.x.x.x.x.x64.msi solved it. Thank you!

**Comment by LegacyFDP** [comment]
For me the solution was to set the Visualization values in BIOS
