### ISSUE TITLE
Support Ubuntu 21.10

### ISSUE THREAD

**Issue by unicomp21** [microsoft/WSL#7802]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by benhillis** [comment]
This is up to Canonical, we're happy to support any distro that wants to be available.

**Comment by KyleRAnderson** [comment]
Perhaps you were looking for Microsoft store support, but it's very possible to get Impish (21.10) in WSL2. I have been using it just about since it released via the following steps:
1. ```bash
    # Make sure that Snap is gone, otherwise the upgrade script tries to invoke it and fails because of the lack of systemd
    sudo apt purge snapd
    ```
1. Follow "Upgrading from Ubuntu 21.04" in [this documentation](https://discourse.ubuntu.com/t/impish-indri-release-notes/21951). Specifically, the section with "To upgrade on a server system". If you're currently on Ubuntu 20.04, these same steps will get you onto Ubuntu 21.04, from where you can repeat the `sudo do-release-upgrade` to get to 21.10.



As a side note, the Ubuntu blog for the 21.10 release explicitly mentions WSL support: https://ubuntu.com/blog/ubuntu-21-10-has-landed. I'd say it's reasonable to assume then that Canonical had WSL in mind with this release.

**Comment by mloskot** [comment]
@benhillis 
> This is up to Canonical, we're happy to support any distro that wants to be available.

As @KyleRAnderson pointed above, the Canonical news from October explicitly states the WSL support in the 21.10, so what else would be "up to Canonical" there?

**Comment by Biswa96** [comment]
Canonical has to provide the full appx package in Windows Store. Alternatively, you can install the latest version from here https://cloud-images.ubuntu.com/releases/

**Comment by mloskot** [comment]
@Biswa96 
> Canonical has to provide the full appx package in Windows Store

I see. Thanks.
