### ISSUE TITLE
Cannot uninstall/reinstall (Error: 0x80080005)

### ISSUE THREAD

**Issue by tylerdq** [Microsoft/WSL#781]
I tried to install bash but it hung during the setup (for hours) so I closed it. When I open bash now it's unresponsive. I sought to uninstall and reinstall from an elevated command prompt using "lxrun.exe /uninstall /full" but I keep getting simply "Error: 0x80080005". I am on Windows Version 1607, Build 14393.10. 

I noticed that [this thread](https://github.com/Microsoft/BashOnWindows/issues/538) also covers error 0x80080005, but the situation seemed very specific, the person with the error seems to have a level of familiarity with BOW that I don't, and I'm wondering if there is a more generally applicable fix to this issue.

**Comment by fpqc** [comment]
Are you using Avast or Kaspersky?

**Comment by tylerdq** [comment]
Hmm, interesting. I use neither, but I do have AVG.

**Comment by fpqc** [comment]
I heard there may be problems with AVG as well.  First try disabling, then closing, then uninstalling (reboot after uninstalling) and see if you can get it working.  I think that the antivirus software is blocking pico processes/lxss.sys in order to prevent things like rootkits from installing with kernel mode drivers (total guess!!!).

**Comment by tylerdq** [comment]
Thank you, this helped. I had to uninstall AVG and then I could uninstall and reinstall.

However, now I have another problem. The feature downloads from the Windows store, but then is stuck on "Extracting filesystem, this will take a few minutes..." for HOURS.

Anyone encountered this before?

**Comment by fpqc** [comment]
Someone said he got that but when he rebooted after uninstalling avast, it just went through

**Comment by tylerdq** [comment]
Thank you for the help. I've tried it a few times, and it's not going through. I'll keep poking around for solutions.

**Comment by pkonovalov-softheme** [comment]
I have no 3d party software on my PC and have the same error Error: 0x80080005 during uninstalling and in Bash there is  just black screen

**Comment by luo4neck** [comment]
Facing same issue now, anyone found any good solution?

**Comment by netbrothers-tr** [comment]
I'm experiencing the same issue. An uninstallation has become necessary (?) after a `mv` operation that took very very long and has been aborted by me. After that, the black screen with a blinking cursor appeared. Bash essentially seemed broken. Then I uninstalled the subsystem with `LxRun.exe /uninstall /full` and installed it again with `LxRun.exe /install`. Both operations (uninstall and install) yielded the same error `0x80080005`.

**Comment by luo4neck** [comment]
@netbrothers-tr dont use 'mv xx/ yy/', use 'mv xx yy', it will be fine

**Comment by netbrothers-tr** [comment]
Thanks @luo4neck ! I will try that. Meanwhile I have deinstalled the subsystem completely via "Remove Windows features" and then reinstalled it. It's usable again. 😉

**Comment by jeffsilverm** [comment]
I was all set to uninstall and reinstall the subsystem.  Then, when I saw:

C:\windows\system32>lxrun.exe /uninstall /full
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: n
Accepting is required to proceed. Exiting...

C:\windows\system32>

I decided to stop and ask if there is another way to recover.  I've invested quite a few hours in this, and I would rather not  blow it all away if possible.  As it happens, all of the application software I've developed is under /mnt/c/Users/$USERNAME/ so that's not a problem.  The public keys in ~/.ssh are a bit of a problem, surmountable, of course, but still a problem.  But the applications: getting both versions of python to not fight with each other, all of the optional applications I've installed with pip and apt-get, getting the .bashrc file just right.

Is there another alternative to just blowing all that away?

**Comment by benhillis** [comment]
@jeffsilverm - if you do not supply the /full flag none of the files in your /home or /root directories will be deleted (this includes ~/.ssh and ~/.bashrc). The applications that you've installed via apt and pip unfortunately are stored outside of those locations so those will have to be reinstalled.

**Comment by jeffsilverm** [comment]
Ben,

You used a double negative.  Are you telling me that if I do **not** use the /full switch, then none of the files in /home or /root will be deleted?

Jeff

**Comment by fpqc** [comment]
/full deletes them. Omitting them makes it not do so.

**Comment by benhillis** [comment]
@jeffsilverm - correct.

**Comment by vitordouzi** [comment]
In my case, any mv or cp command was blocked by the windows firewall. When I cancel one of this command, the problem with the uninstall happens. Try to disable the firewall, reboot the windows and run the uninstall. That work with me.

**Comment by raydecastro** [comment]
@luo4neck I think I'm experiencing the same problem that you described: _dont use 'mv xx/ yy/', use 'mv xx yy', it will be fine_. In my case, I did an `mv foldername/ newfoldername` then this killed my bash, and I'm no longer able to run `bash` anymore. It hangs with the error message: `Error: 0x80080005`. How can I undo the `mv` command? I killed the powershell/bash window, and it did not perform the `mv` operation, but not I'm hosed.

**Comment by raydecastro** [comment]
@luo4neck nevermind. Uninstalling and reinstalling `windows subsystem for linux` fixed it. thanks.

**Comment by charliefpg** [comment]
I have the same issue with my work laptop. I have to guess it's one of the many, many security measures and the corporate network.

**Comment by facorreg** [comment]
@benhillis 
Hello there, I came here because I just had the "Error: 0x80080005" on bash, and from what I've read on many threads when I was looking for a solution you were still looking into this.
I tried to unistall "full" but it would not let me reinstall anyway, the same message would appear.
At the end of the day, all I had to do was:
"Disable Antivirus permanently & Restart (You can enable it after the installation is complete)
Open Command Prompt or Windows PowerShell as admin
Uninstall WSL by running the following command lxrun /uninstall /full
Now stop WSL service - sc stop lxssmanager
Remove App data folders - rmdir /S %LOCALAPPDATA%\lxss. Confirm the folders have been deleted. You might need to change the ownership to delete the folder if you get any access-denied errors.
Once the folders are deleted, try installing WSL again by running lxrun /install /y"
and it worked.
So there's nothing extraordinary in this solution, but at least it worked where the command line did not, I don't know if that's of any use to you, maybe one of these easy step can help pinpoint the issue.

**Comment by fpqc** [comment]
I had an error the other day because something pinned the service.  After rebooting, I was able to restart it.

**Comment by kumarnikhil104** [comment]
can any one help me I am trying to uninstall the linux sub-sytem on windows10
C:\Users\Nikhil>lxrun uninstall/full
Performs administrative operations on the LX subsystem

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Configures the subsystem user that bash will be launched as. If the user does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
    /update - Updates the subsystem's package index

C:\Users\Nikhil>lxrun uninstall/y
Performs administrative operations on the LX subsystem

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Configures the subsystem user that bash will be launched as. If the user does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
    /update - Updates the subsystem's package index

C:\Users\Nikhil>

**Comment by therealkenc** [comment]
The OP here appears to have involved AVG.
