### ISSUE TITLE
Gazebo under WSL2 (Ubuntu 18.04) only uses CPU.

### ISSUE THREAD

**Issue by SaligiaR** [microsoft/WSL#7810]
I'm a robotics researcher and I've been using Gazebo in Ubuntu.
I recently started using WSL2 in Win11 and I found that Gazebo in Ubuntu 18 was only 10-30 FPS because the CPU was running at 100% load and the GPU was not occupied. 
However, Gazebo in Ubuntu 20 reached 60 FPS while the GPU was used and the CPU load was greatly reduced.
I enjoyed the experience of using WSL2 under Win11, and if this one small issue could be fixed, it would be a huge boost to my research.

**Comment by craigloewen-msft** [comment]
This is supported already for Gazebo to use the GPU. My guess is that since you're using Ubuntu 18 it doesn't have the latest mesa version which has support for the GPU. Are you able to try your workflow on the latest Ubuntu version and see if that hits your GPU? 

Also if you run into issues again after trying the above, please file an issue at this repo: https://aka.ms/wslg as that will have the best people to take a look at it it.

[Here's me running Gazebo and RViz with GPU acceleration.](https://youtu.be/f8_nvJzuaSU?t=258)

**Comment by PieterT-CODES** [comment]
I have same problem as SaligiaR. On WSL 2 with ubuntu 18.04 gui simulation consume 4x more CPU than GPU. In WSL 2 with ubuntu 20.04 is CPU/GPU ratio same and simulation goes much better. 

WSL with win11 is great and I would be very disappointed to return to linux.... Thnaks for all answers

**Comment by caldi99** [comment]
Have you solved this problem? If so what did you do? 
Because I'm having issues with hardware accelation with gazebo and rviz through ROS melodic, Ubuntu 18.04 and Wsl2. In particular, when I run the vxsrv server with opengl accelaration enabled, I have a segmentation fault error as well as GPU device not found. Notice that other programs like gedit works fine.
So, what should I do? 
Thanks for all the answer.

**Comment by Starkhen** [comment]
**I have met the same Problem in Ubuntu 18.04.My Nvidia GPU is not used mostly,but the CPU is 100 percent.**
1.I get the info that "you can visit [Mesa official home](https://gitlab.freedesktop.org/mesa/mesa) and build a private version of Mesa with this support. Alternatively, you can try out Canonical recently announced [Ubuntu on Windows Community Preview for WSL 2](https://ubuntu.com/blog/announcing-ubuntu-on-windows-community-preview-wsl-2)."from[https://devblogs.microsoft.com/commandline/wslg-architecture/](url),but my resources are all in ubuntu-18.04 .I am afraid of they can not run nomally on  the others.
2.[https://github.com/microsoft/wslg/issues/86](url)But when I update my driver it don't work.

**Comment by complete-dope** [comment]
> I spent a couple hours of this problem and still am unable to get hardware acceleration working with W11 + WSL2 + Ubuntu 20.04 + Docker. I was however able to install cuda onto my wsl ubuntu 20.04. I also ran the demo provided and ran `nvidia-smi` command with no issues inside my Ubuntu 20.04 and docker instance. However, RVIZ and other GUI apps in my docker are still not using hardware acceleration from my nvidia GPU unfortunately.

@billyliuschill  Even I have the same issue .. did you found any workable method for this ?
