### ISSUE TITLE
wsl --shutdown does not perform its task

### ISSUE THREAD

**Issue by herrwinfried** [microsoft/WSL#7814]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

open task manager and observe vmmem. On the one hand, open terminal and type wsl --shutdown.

### Expected Behavior

vmmem won't run until I open it

### Actual Behavior

It should have turned off but after a while it started up again(vmmem).

https://user-images.githubusercontent.com/52379312/145464019-cdf796b0-5e5f-4717-9f70-c596acd9c1bc.mp4

**Comment by sirredbeard** [comment]
Do you by chance have Rancher Desktop, Docker Desktop, or other tool that uses WSL on the backend running?

**Comment by herrwinfried** [comment]
> Do you by chance have Rancher Desktop, Docker Desktop, or other tool that uses WSL on the backend running?

No. There is WSL.

**Comment by OneBlue** [comment]
Thanks for reporting this @herrwinfried.

Can you please [share logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) to help narrow down the issue ?

**Comment by zenetio** [comment]
I have faced the same issue. When VS code shows lots of warnings and cannot train the model, I close VS code and see there are still some VS code processes running. I try to shutdown wsl but I am guessing the issue is due to VS code still running. Then I do a logout/login and see that all the VS code processes were closed, and only wsl still remains. Then I do a wsl --shutdown but nothing happens. The workaround I use is to restart the vmwp.exe process manually or restart the machine.

**Comment by aminrabinia** [comment]
" restart the vmwp.exe process manually " worked beautifully!

**Comment by herrwinfried** [comment]
> " restart the vmwp.exe process manually " worked beautifully! 

I forgot about this place, thanks for reminding me 🤣

**Comment by kcd83** [comment]
Your mileage may vary... I found `end task` on ` vmwp.exe` results in a blue screen

Next time I will try `Get-Service vmms | Restart-Service` see if that will help
