### ISSUE TITLE
Can't connect to websocket sever deployed in wsl2

### ISSUE THREAD

**Issue by purple-cmd** [microsoft/WSL#7849]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

Whenever I try to connect from windows to a websocket server which deployed inside wsl2 I get 
```
"Error: getaddrinfo ENOTFOUND http".
````

(btw, for self-check, If I deploy it in the window itself, connection works)

### Repro Steps

1. Deploy websocket server in wsl2. 
2. Try to connect from windows. 
3. you will get an error: "Error: getaddrinfo ENOTFOUND http".

You can debug it with postman websocket feature. 

### Expected Behavior

connection is successful.

### Actual Behavior

 "Error: getaddrinfo ENOTFOUND http".

**Comment by OneBlue** [comment]
Thanks for reporting this @purple-cmd.

Can you share more details about how exactly your websocket server is set up ? 
What listening address and port do you use inside WSL and which ip address & port are you connecting to from Windows ?

**Comment by DanPinGF** [comment]
Sounds like a network problem. Do you have any firewalls set up?

**Comment by eluo28** [comment]
Am getting similar error when trying to connect to socket using postman. Works if I use browser as client though.
![image](https://user-images.githubusercontent.com/43073753/149436398-40d92b14-4efa-49ab-a201-f40347f97b51.png)

**Comment by wanderer-s** [comment]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/62498748/152631294-eef63732-ae32-4265-aa65-c8358f3f0d38.png">
I have a same issue with same code but different dev enviroment

when I try same process in **Mac OS** it works properly but when I try this in **WSL2** it shows that error

**Comment by xxSkyy** [comment]
Same Problem connecting from windows to WSL2 websocket
![image](https://user-images.githubusercontent.com/16470866/172715435-04b18906-2431-4f80-abaf-bb73f3640d6e.png)

**Comment by filipe-costa** [comment]
I am currently facing the same problem, although I have referenced this in another thread since I think it might be a network issue between Windows and WSL2 when using applications like Postman since everything seems to work via a browser:

https://github.com/microsoft/WSL/issues/4204#issuecomment-1406549432

**Comment by m-salman-afzal** [comment]
For anyone,
My issue was server was started on ipv6 which was unable to listen. You can use `sudo lsof -i -P -n | grep LISTEN` to check if your port is ipv6 or ipv4. If ipv6, then try putting **0.0.0.0** after port. The issue for connection refused will be solved.

BUT, you might get a new error **socket hang up**. Now, this will be because you are using socket.io library and going through the documentation, it seems like it expects _socket.io-client_, its own library for proper handshake to establish a connection. So, we might not be able to do it from postman at all.

What you can try is using the base **ws** library which is barebone of websockets (upon which socket.io runs). I was able to establish a connection through it. But being barebone, you will have to do everything yourself if you go down this road.

**Comment by lumusitech** [comment]
Same problem. Goodbye WSL2 development environment in windows 11. I Return to others OS like macos or GNU linux to solve this problem.
