### ISSUE TITLE
"wsl.exe --distribution Ubuntu --exec /bin/sh -c" does't load any $PATH variables set in ~/.profile or ~/.bashrc or ~/.bash_profile

### ISSUE THREAD

**Issue by asolopovas** [microsoft/WSL#7861]
### Version

Microsoft Windows [Version 10.0.19043.1415]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

`wsl.exe --distribution Ubuntu --exec /bin/sh -c "echo $PATH"`

### Expected Behavior

Should load $PATH variables set in .profile or .bash_profile or .bashrc

### Actual Behavior

Does not set any $PATH variables

**Comment by OneBlue** [comment]
Thanks for reporting this @asolopovas .

`sh` only loads .profile for login shells, and never loads .profile or .bash_profile since those are for bash.


You can start `sh` with -l to start it as a login shell. It will then load .profile. [More info here](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html).
