### ISSUE TITLE
wsl stops working after update in windows 11 as well as windows 10

### ISSUE THREAD

**Issue by superhero75** [microsoft/WSL#7864]
### Version

Version	10.0.22000 Build 22000.376

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Repro Steps

cant start wsl at all 

### Expected Behavior

should start normally

### Actual Behavior

after entering wsl:-

Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization

### Diagnostic Logs

I have triple checked all bios virtualisation, linux subsystem and virtualisation have been enabled. WSL was working the day before and suddenly after update, it stops working. so it seems the update breaks the setup.

**Comment by mrbahr2021** [comment]
I am having the exact same issue.  I don't know if Windows 11 updated, but last week it was working just fine and today it is not.  I went through and updated the BIOS on my machine, went into task manager to verify virtualization was enabled, reinstalled WSL and still nothing.  I get the exact same message as the person above.

Version	10.0.22000 Build 22000
Virtualization-based security	Enabled but not running
Virtualization-based security Required Security Properties	Base Virtualization Support, Secure Boot
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

I don't know what else to check especially since it was working last week.

**Comment by Leopoldpaul** [comment]
Same problem with my System. From one day to another it stop working and i get the same error message.

**Comment by j0n9hyun** [comment]
I too have the same problem now. i've tried a lot to solve this problem but I haven't been able to solve it.

**Comment by mrbahr2021** [comment]
I decided to try and "update" windows 11 and that worked.  From Windows, run setup on your thumb drive or distribution with windows and update leaving all of your programs and settings.  It took a while, but worked.  I don't know what the problem was or what fixed it, but something was wrong and updating windows fixed it.

**Comment by superhero75** [comment]
> I decided to try and "update" windows 11 and that worked. From Windows, run setup on your thumb drive or distribution with windows and update leaving all of your programs and settings. It took a while, but worked. I don't know what the problem was or what fixed it, but something was wrong and updating windows fixed it.

What do you mean by updating with a thumb drive ?? U meant by downloading  a fresh windows 11 iso onto a thumb drive and perform an install repair ??

**Comment by matt-psaltis** [comment]
Windows 11 here was working two weeks ago. Go to get ready for return to work after Christmas break and WSL no longer starts with the described error message.

**Comment by mrbahr2021** [comment]
yes - the only way I could fix it was to reload windows.  You can leave all
of your apps and files, so the update doesn't change anything, but appears
to fix WSL.  It did for me.


Thanks,
Tom

**Comment by superhero75** [comment]
> yes - the only way I could fix it was to reload windows. You can leave all of your apps and files, so the update doesn't change anything, but appears to fix WSL. It did for me. Thanks, Tom

I reinstalled windows 11 and wsl worked afterwardd for a week but today the same problem returns.

**Comment by Shrimpwr** [comment]
[wsl2-not-starting-after-spacedesk-installation](https://www.spacedesk.net/zh/forums/topic/wsl2-not-starting-after-spacedesk-installation/)
maybe this is the reason

**Comment by Leopoldpaul** [comment]
> [wsl2-not-starting-after-spacedesk-installation](https://www.spacedesk.net/zh/forums/topic/wsl2-not-starting-after-spacedesk-installation/) maybe this is the reason

Thanks this is the forum with the fix for this Error. Finally.

**Comment by mrbahr2021** [comment]
Thanks for the posting regarding Spacedesk.  This is exactly what happened
to me.  I installed Spacedesk and that was when it happened.  I didn't
realize that is what did it.

Thanks,
Tom

**Comment by mwoodpatrick** [comment]
I'm not using spacedesk and my problem is intermittent. As noted if I kill wslservice wsl works normally for a while

**Comment by mwoodpatrick** [comment]
What logs would you like to get and how do I capture them?

**Comment by cibelewatt** [comment]
> I'm not using spacedesk and my problem is intermittent. As noted if I kill wslservice wsl works normally for a while

Counldn't your issue be the same as #7891 ?

**Comment by sn0rlacks** [comment]
It seems as if the problem could be solved by manually re-installing this driver.
Please try the fix below and let us know if it solved the problem.
1. Go to device manager -> Action -> add legacy hardware.
2. Choose Option „Select hardware manual from list“ in the wizard
3. Choose „Systemdevices“ in the list
4. Choose „Microsoft“ in vendors
5. Choose „microsoft hyper-v virtualization infrastructure driver“ in models
6. Follow the wizard to finish the installation
7. Restart the computer

courtesy of https://www.spacedesk.net/zh/forums/users/spacedesk-marcel/ 🤝

**Comment by QQting** [comment]
> It seems as if the problem could be solved by manually re-installing this driver. Please try the fix below and let us know if it solved the problem.
> 
> 1. Go to device manager -> Action -> add legacy hardware.
> 2. Choose Option „Select hardware manual from list“ in the wizard
> 3. Choose „Systemdevices“ in the list
> 4. Choose „Microsoft“ in vendors
> 5. Choose „microsoft hyper-v virtualization infrastructure driver“ in models
> 6. Follow the wizard to finish the installation
> 7. Restart the computer
> 
> courtesy of https://www.spacedesk.net/zh/forums/users/spacedesk-marcel/ 🤝

Hi @sn0rlacks 

It works for me. 
Thank you!
