### ISSUE TITLE
[Question] How do you optimize a WSL vhd without Hyper-V?

### ISSUE THREAD

**Issue by defcon79** [microsoft/WSL#7875]
I have WSL2 working, but haven't installed Hyper-V, since I need VirtualBox.

The standard recommendation to reclaim space is to use Optimize-VHD in PowerShell. However this is not available without Hyper-V, even on Win 10 Pro/Enterprise.

I found an alternate method online (https://blog.suraj-mittal.dev/reduce-wsl2-disk-filesize/) which suggested using diskpart to select the ext4.vhdx file and then use 'compact'. 

However, even after detaching the vhd still seemed to be attached and prevented WSL2 from starting up, even across reboots. Also I'm not sure if its doing the same thing?

What is the recommended way?

**Comment by ZedG2** [comment]
Maybe "export and import" is a solution?

**Comment by owenschupp** [comment]
We are looking into ways to better optimize VHDs within WSL, especially the system VHD you mentioned. Optimize-VHD would be my recommendation but since you are not able to use Hyper-V using `diskpart` may be a good option but this is by no means an official endorsement. I would make sure you are using `wsl --shutdown` before messing with the VHD to avoid bad behavior. It is also unfortunate that you cannot use Hyper-V because the Powershell module includes many helpful VHD-related commands like `Attach-VHD`.
