### ISSUE TITLE
Snap Store Ubuntu WSL Broken

### ISSUE THREAD

**Issue by adgsenpai** [microsoft/WSL#7921]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Run the command

```
sudo snap install vlc
```

### Expected Behavior

`Download snap "vlc" (2344) from channel "stable"`
`vlc 3.0.16 from VideoLAN✓ installed`

### Actual Behavior

Returns console output

```
error: cannot communicate with server: Post http://localhost/v2/snaps/vlc: dial unix /run/snapd.socket: connect: no such file or directory
```

**Comment by sukso96100** [comment]
AFAIK, Snap is not available officialy for now. Because it requires systemd and apparmor which is not available on default WSL environment

**Comment by adgsenpai** [comment]
> AFAIK, Snap is not available officially for now. Because it requires systemd and apparmor which is not available on default WSL environment

Let's see if `Microsoft` will make it happen :-)

**Comment by jabowery** [comment]
With 22.04 this became a critical issue because:

* It requires snap to install some critical applications.
* [The "workaround" offered](apt-get update && sudo apt-get install -yqq daemonize dbus-user-session fontconfig) will "brick" your Ubuntu installation if anything goes wrong during Ubuntu boot, because there is no way to alter your Ubuntu file system from Windows File Explorer.

**Comment by marcIhm** [comment]
Yes I am waiting to make an application available on Ubuntu as a snap; currently this would involve too much hackery for the end user.

**Comment by Biswa96** [comment]
[Systemd Creator Lands At Microsoft](https://www.phoronix.com/scan.php?page=news_item&px=Systemd-Creator-Microsoft). There will be some development around enabling systemd in WSL2.
