### ISSUE TITLE
Issue wish oh my zsh newuser-install

### ISSUE THREAD

**Issue by cummingsk05** [Microsoft/WSL#795]
I am trying to get oh my zsh to work with bashonwindows, but when I open a window and press '2' for the new user configuration I am met with this error. 

![image](https://cloud.githubusercontent.com/assets/8881602/17458028/82830a64-5bd4-11e6-9ece-8004e1661cac.png)

This should allow me to enter into a zsh prompt, but I can't go any further.

Build 14393.10

**Comment by rodrymbo** [comment]
It'd be interesting to know where you got zsh... did you get a package somewhere, or compile it yourself, or use `apt-get install`.

It'd also be interesting to see what the permissions on .zshrc are, or even if it exists. Can you edit it manually, for example, perhaps with nano? Is it perhaps writable only by root or something weird like that?

**Comment by cummingsk05** [comment]
@rodrymbo I installed it using `apt-get install`. As for the .zshrc file, it looks to be read only. I changed permissions and it was still the same. Funny enough, when prompted with the same error again, i typed in `bash` to get back to the bash shell and it ended up working. I have no idea why that would have done it.

**Comment by fpqc** [comment]
cummingsk05, works here if you install oh-my-zsh from github no problems =]

**Comment by neurogenesis** [comment]
A few notes for people running zsh:

1) Install zsh with `sudo apt-get install zsh`

2) bash.exe is the entrypoint to the WSL / linux subsystem. You'll have to modify the windows shortcut to specify `bash -c --login` or modify `~/.bashrc` with `exec /bin/zsh` to properly load a different shell. `/etc/passwd` isn't consulted because it's not a full login process. Be sure to set your SHELL env var as well. See #846 for details.

3) Fix your umask before you start installing things, otherwise tools like zsh will complain. Specifically, "group" and "other" permissions will have the same privileges that owner do. This causes zsh's compaudit and compinit to fail (both are related to command completion). See #352 for details. `umask 022` can be added to your `~/.bashrc`.

**NOTE:** This should be done before trying to install zsh plugin managers like antigen (otherwise the directory/file permissions issues from git clones). You should also do this before installing RVM or rbenv.

I ended up inserting a few lines to the top of my `~/.bashrc`, something like the following:

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

## Fix missing umask value
umask 022

## Launch Zsh
if [ -t 1 ]; then
  cd $HOME
  export SHELL=/bin/zsh
  exec -cl $SHELL
fi
```

**Comment by tara-raj** [comment]
Closing as this now works. Issue resolved
