### ISSUE TITLE
wsl2 - file mounts from windows stop working, loading times with infinite timeout

### ISSUE THREAD

**Issue by newcron** [microsoft/WSL#7977]
### Version

WSL-Version: 0.51.2.0 Kernelversion: 5.10.81.1 WSLg-Version: 1.0.30 Windows-Version: 10.0.22000.434

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.81.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Mon Nov 22 18:52:15 UTC 2021

### Distro Version

Various versions, tried Ubuntu LTS from store and also ubuntu 21.10

### Other Software

explorer.exe 
IntelliJ
docker for Windows

### Repro Steps

After WSL running for a while, the file mounts from windows to WSL stop working. When I try to open \\wsl.localhost$\ubuntu in explorer after that, explorer will keep on loading forever - without a timeout or error message. 

This error seems to happen consistently after using WSL for a while, but seemingly without a trigger. Restarting Windows is the only way to fix this. `wsl --shutdown` will not solve the issue. Eventually the file mount stops working entirely, meaning that even a windows reboot will fix the broken mount. 

### Expected Behavior

file mounts from windows into the WSL distro should just keep working

### Actual Behavior

file mount stops working, trying to open it will cause explorer (or any other software doing so) to freeze and not recover. There seems to be no timeout set to eventually fail the process of opening the folder. 

This will cause applications to just freeze without recovery. 

### Diagnostic Logs

[    0.761550] 9p: Installing v9fs 9p2000 file system support
[    0.763850] FS-Cache: Netfs '9p' registered for caching
[    0.972223] 9pnet: Installing 9P2000 support
[    4.824550] 9pnet_virtio: no channels available for device drvfs
[    5.211454] 9pnet_virtio: no channels available for device drvfs
[    5.867416] 9pnet_virtio: no channels available for device drvfs
[    6.167423] 9pnet_virtio: no channels available for device drvfs
[   16.596315] 9pnet_virtio: no channels available for device drvfs
[   16.897310] 9pnet_virtio: no channels available for device drvfs

**Comment by marco-pm** [comment]
See #7782 
The issue seems to arise only with the WLS version installed from store.

**Comment by megalofauna** [comment]
I'm on the Windows 11 Dev Channel release. That may be my first mistake. 

But on a clean install of Windows 11, with a brand new installation of WSL (completed as per current MS docs), using Ubuntu as my distro, and working from within the Linux filesystem, I can reproduce the behavior described in @newcron's original post by merely attempting to use any sort of hot module replacement in WSL.

Whether trying to run a Vue project with Vite, a Svelte project with rollup, whatever... localhost immediately goes into an eternal spinning state after my first update and the Linux file mount is completely inaccessible from the terminal, from File Explorer, etc. 

I may just have symptoms superficially similar to @newcron with a completely different root cause, but I needed to vent. I'm dead in the water until I can get this sorted.

**Comment by megalofauna** [comment]
> See #7782 The issue seems to arise only with the WLS version installed from store.

Ah, I didn't see your comment until after my venting, @marco-pm. That matches my situation (using store version).

**Comment by edburns** [comment]
I am observing this also. I am using Windows 11.

**Comment by Henryswa** [comment]
I have this on Windows 10 without installing through the Store. It used to be that restarting things would fix it, but not anymore. I tried reinstalling WSL.
