### ISSUE TITLE
DrvFs support for UDF volumes

### ISSUE THREAD

**Issue by BrainwreckedTech** [Microsoft/WSL#802]
Currently, DrvFs only supports NTFS and ReFS.

UDF is another choice in multi-system environments where data portability is desired.  Less common than the FAT family, but completely viable.

Because Windows supports UDF natively, it's expected that this filesystem Just Work.  UDF has support for Named Streams (equivalent of NTFS Alternate Data Streams).

**Comment by Shot2** [comment]
The problem is: DrvFs does not support permissions/ownership at all.
Even if being able to mount a TB-size UDF data drive would be great for interoperability, it would imply having everything on it owned by root with 777 perms - a security risk... or at least very inconvenient when exchanging this data with other "real" systems that do support permissions.

**Comment by xilun** [comment]
I don't see how this is a security risk. If it presented unfiltered Linux perms, it would be (you could have a suid root executable on the volume). On the contrary, everything to 777 is quite the standard way to map unsecured FS under a real Linux (or, 700 for the user who mounted it, but under WSL it would not be really applicable; visibility by only one or some users would map better to the existing user & permissions & isolation model)

**Comment by therealkenc** [comment]
This one fell through cracks. UDF has been supported since 16176, referenced in #1926 ([message](https://github.com/Microsoft/WSL/issues/1926#issuecomment-294332543)).
