### ISSUE TITLE
WSL 

### ISSUE THREAD

**Issue by terminalMaster** [microsoft/WSL#8020]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Visual Studio Code 1.64.0 with Remote WSL v0.64.2

### Repro Steps

Unknown

### Expected Behavior

Visual studio code to run with WSL with the command:
$ code .

### Actual Behavior

mkdir: cannot create directory /home/USER/.vscode-server’: Permission denied

**Comment by owenschupp** [comment]
This appears to be an issue with the WSL-Remote Container extension for VSCode. I would create an issue there https://github.com/microsoft/vscode-remote-release or look at https://github.com/microsoft/vscode-remote-release/issues/2095. Closing this since it is not an WSL-specific issue. Hope this helps.

Also in the future please create issues with more descriptive titles, as it helps us help you faster.
