### ISSUE TITLE
Is WSL 2 (and Ubuntu) supported on Windows 365 Cloud PCs?

### ISSUE THREAD

**Issue by paulg-quantinno** [microsoft/WSL#8076]
I cannot find any official info on this, but currently running wsl --install on a cloud pc just does not work, returning the familiar error that's seen many times on this issues list:

_Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed._

Is this just a feature that's not available on the Windows 365 Cloud PC?

**Comment by Nikkelmann** [comment]
I've tried this and sadly it does not seem to work.

According to MS support, this is by design:
https://techcommunity.microsoft.com/t5/windows-365-feature-requests/docker-desktop-and-or-wsl-not-supported-on-a-windows-365-cloud/idi-p/2834700

https://techcommunity.microsoft.com/t5/windows-365/windows-365-cloud-pc-windows-10-and-wsl-2-ubuntu/m-p/2865068

**Comment by jeliasson** [comment]
WSL on Windows 365 seems to be in General Availability now. However, it's only for the 8vCPU/32GB SKU in supported regions.
https://learn.microsoft.com/en-us/windows-365/enterprise/nested-virtualization
