### ISSUE TITLE
WSL2 shuts down after detached job loses parent session

### ISSUE THREAD

**Issue by fredgalvao** [microsoft/WSL#8161]
### Version

Microsoft Windows [Version 10.0.22572.201]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.93.2

### Distro Version

Ubuntu 18.04

### Other Software

xfce4-terminal 0.8.7.4 (Xfce 4.12)
VcXsrv 1.20.9.0

### Repro Steps

- run a VcXsrv profile
  - the `.xlaunch` file I use is:
```
<?xml version="1.0" encoding="UTF-8"?>
<XLaunch WindowMode="MultiWindow" ClientMode="NoClient" LocalClient="False" Display="-1" LocalProgram="xcalc" RemoteProgram="xterm" RemotePassword="" PrivateKey="" RemoteHost="" RemoteUser="" XDMCPHost="" XDMCPBroadcast="False" XDMCPIndirect="False" Clipboard="True" ClipboardPrimary="False" ExtraParams="" Wgl="True" DisableAC="True" XDMCPTerminate="False"/>
```
- set up a WSL2 distro with XFCE basics installed (might work with other simpler/different environments/binaries, I couldn't test)
- open `Windows Terminal (Preview)`
- make sure WSL2 is not running (`wsl --shutdown`)
- open a new tab profile for a WSL2 shell (for me, it's `wsl.exe -d MyDistroName -u myusername`)
  - **or** open `Windows Subsystem for Linux Preview` as an app directly (which will open a shell in an isolated window) and then `su myusername`
- run `xfce4-terminal &`

-> At this point, the original shell S1 and the child shell S2 will be open, and working

- close S1 completely (either closing the window, or `exit`ing all layers), until the whole window/tab that originated S1 is closed

### Expected Behavior

I expect the child session, on the new terminal window/application, to continue working/alive, and the WSL2 distro to continue running. I've been using this setup and these exact same steps for almost 3 years now, and it worked perfectly so far. S2 is considered a job of S1, as in `jobs -l`, thus closing the source should detach the independent jobs so they continue living. I never had to keep the tab/window open to keep WSL2 alive in the background until now.

### Actual Behavior

After a Windows 11 Insider cumulative update I got recently, now the whole WSL2 distro shuts down whenever S1's window/tab is closed, which naturally kills S2 and whatever was running on top of it (VcXsrv stays up, uninterrupted).

If the only side effect were S2 as a job dying, but the WSL2 distro staying `Running`, I wouldn't have worried too much and would have just switched to some other way to achieve what I need. But the entire distro shutting down is definitely undesired.

There's something about WSL2 that is attaching \<the death of a shell> to \<the death of the window/tab of that shell> too much, which eventually kills the entire WSL2 distro.

### Diagnostic Logs

[wsl.etl.zip](https://github.com/microsoft/WSL/files/8288288/wsl.etl.zip)
Attached is the `wsl.etl` diagnostics file generated with guidance from [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), covering all steps.

VcXsrv doesn't report anything special on its logs that could help.

**Comment by diddledani** [comment]
This is another manifestation of WSL2 being overzealous in shutting down processes that I've reported here as an interop fail #7560

**Comment by bhoppi** [comment]
I have similar problems. After WSL updated to v0.56.1, when the user session closes, the corresponding /init process will exit, no matter whether there are background jobs running or not. If all user sessions close, the root /init exits and all background jobs will get killed.

**Comment by benhillis** [comment]
Looks like we regressed this behavior - I've asked @pmartincic to take a look.

**Comment by SadarSSI** [comment]
I had the same problem with the last update: stopping wsl for processes that work in the background like the ssh daemon. In my case because I was using wsl in the background (like a service) on my windows workstations to access it remotely

I solved the problem by not launching the ssh daemon in the background, as we do in the case of a docker for example, but by leaving it active via a script at startup:
`wsl --distribution mydistrib /pathtoscript/script.sh`
script.sh contains the following commands:
```
sudo mkdir -p /run/sshd
sudo /usr/sbin/sshd -D
```

In my case I run wsl when starting windows with a scheduled task (AtStartup) with a wsl script that will update / recreate the firewall, forwarding and routing rules, if necessary, to the wsl (see [https://github .com/SadarSSI/WSL-WatchDog](url) )

This scheduled task has another trigger allowing WSL to be restarted every xx minutes and to check and update the routing address by comparing the address entered in
`netsh interface portproxy show v4tov4`
and
`wsl --distribution mydistrib hostname -I`

**Comment by pmartincic** [comment]
For those waiting: I'm able to reproduce the issue and am working on it.

**Comment by pmartincic** [comment]
Fix enroute.
