### ISSUE TITLE
Network related issue

### ISSUE THREAD

**Issue by coderboyakash** [microsoft/WSL#8206]
### Version

windows 11

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu

### Repro Steps

installing ubuntu and pushing any git repo will recreate the issue

### Expected Behavior

I am a developer using wsl for more than a year in window 10 and Recently i have updated to windows 11
the issue is when i am pushing anything in git it get stuck multiple time like multiple time doing ctrl+c and push again will work sometime 
for npm install it get stuck and after some time its says timed out like error 

### Actual Behavior

In windows 10 its works fine

**Comment by penguinpages** [comment]
Do you have stable network access externally to code source server.   Ex: ping github/lab etc... for code source
Do you have TCP port access to the target server.  Ex:  wget,  or telnet to specific target port 
Is time sync and configuration correct within WSL.  Ex date  -> check timzone and zone offset.. time mucks with SSL sessions
Do you have solid DNS lookup from WSL instance to external git resource server?  Ex: nslookup forward and reverse

This will set a baseline of connectivity is not the issue. 

If all the above pass, then 

1) take a moment to post how WSL is connected:  NAT vs Bridged  (diagram of packet flow / path)
2) post versions of the WSL, Git, tools for the distro your using.

Post commands your running within shell. it hangs.. many times is time sync / dns / communication.  Last one would be if your doing NAT.... do you have hang up with firewall/ software scanning as it is transfered.  Ex:  Disable for test of baseline

Output system logs and security logs from the OS during the git sync command.

Touch files / folders within git path to make sure you have local write permissions taken care of.  Copy a large local file to that path direct, to rule out some kind of write issue.

I realize above is a kind of basic set of steps to baseline "working state".  This conveys a baseline and then can help those who have deeper code and or debug skills focus on those issues once the basics are ruled out.

**Comment by OneBlue** [comment]
Thanks for reporting this @coderboyakash. What's the expect command you're running and what's the output ?

**Comment by penguinpages** [comment]
Sorry for  delay on response.  In demo setup purgatory for K8...

At this point...I don't know what command to run.  What I can say is that WSL is DOA for me.  Uninstall / reinstall (remove feature) ,  remove Linux image, try different version etc...    All I get is that network not found.  If someone can post for me commands to run to track down what WSL thinks it is connected to, that would help


# wsl
The network was not found.

**Comment by penguinpages** [comment]
I posted via feedback tool the logs.  

One interesting thing..  downloaded test power shell in c:\temp

##
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> wsl
The network was not found.
PS C:\WINDOWS\system32>
##


Ran diag script

###
PS C:\WINDOWS\system32> wsl
ansible@LT-A0070501:/mnt/c/WINDOWS/system32$ ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether f2:7b:a0:d5:6e:d4 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:f3:af:2e:1d:1a brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:21:b9:20 brd ff:ff:ff:ff:ff:ff
    inet 172.28.118.118/20 brd 172.28.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe21:b920/64 scope link
       valid_lft forever preferred_lft forever
ansible@LT-A0070501:/mnt/c/WINDOWS/system32$ sudo ip addr flush dev eth0
[sudo] password for ansible:
ansible@LT-A0070501:/mnt/c/WINDOWS/system32$ ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether f2:7b:a0:d5:6e:d4 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:f3:af:2e:1d:1a brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:21:b9:20 brd ff:ff:ff:ff:ff:ff
ansible@LT-A0070501:/mnt/c/WINDOWS/system32$ sudo dhclient eth0
##
<client request hangs for 2+ min>


![image](https://user-images.githubusercontent.com/17153876/167709042-7428b4ce-f743-420b-8e30-239f633f3ede.png)

Forwarding still enabled
![image](https://user-images.githubusercontent.com/17153876/167709107-8d4285aa-d2aa-4a05-a7c7-01713e8ffab8.png)

No bridge on HV Switch
![image](https://user-images.githubusercontent.com/17153876/167709302-d72dc4e1-afc7-440d-881c-fe3f413e91fb.png)

Or Gb NIC (used by HV switch "WSL" to bridge and also bind management / local windows traffic)
![image](https://user-images.githubusercontent.com/17153876/167709460-29f8461f-21bb-4adc-a558-1aa0d02b60d8.png)

**Comment by penguinpages** [comment]
Windows updates / patch. Reboot.  Back to broken state:

`PS C:\temp\%tmp%\WSL> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
PS C:\temp\%tmp%\WSL> Set-ExecutionPolicy Bypass -Scope Process -Force
PS C:\temp\%tmp%\WSL> .\collect-wsl-logs.ps1


    Directory: C:\temp\%tmp%\WSL


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/11/2022   8:19 AM                WslLogs-2022-05-11_08-19-05
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
get-acl : Cannot find path 'C:\ProgramData\Microsoft\Windows\WindowsApps' because it does not exist.
At C:\temp\%tmp%\WSL\collect-wsl-logs.ps1:35 char:1
+ get-acl "C:\ProgramData\Microsoft\Windows\WindowsApps" | Format-List  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
    + FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand

Log collection is running. Please reproduce the problem and press any key to save the logs.
Saving logs...
Press Ctrl+C to cancel the stop operation.
100%  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
The trace was successfully saved.
Logs saved in: C:\temp\%tmp%\WSL\WslLogs-2022-05-11_08-19-05.zip. Please attach that file to the GitHub issue.


PS C:\temp\%tmp%\WSL>`

Something run in the "networking.bat" is what "fixes" it. 

Attached is the output from the run.
[WSL_network_bat_run_logs.txt](https://github.com/microsoft/WSL/files/8669861/WSL_network_bat_run_logs.txt)

**Comment by penguinpages** [comment]
Update: Fresh windows 11 build /laptop.

I am thinking it is something in my deployment path..  but at least it is consistent.

#####
1) Install Windows
2) Add Feature "HV" "WSL"
3) Add vSwitch WSL.  Bridge to Gb NIC
4) Install WSL per below with Ubuntu

###
`PS C:\Windows\system32> choco feature enable -n allowGlobalConfirmation
Chocolatey v1.1.0
Enabled allowGlobalConfirmation

PS C:\Windows\system32> wsl
W i n d o w s   S u b s y s t e m   f o r   L i n u x   h a s   n o   i n s t a l l e d   d i s t r i b u t i o n s . 
 
 
 D i s t r i b u t i o n s   c a n   b e   i n s t a l l e d   b y   v i s i t i n g   t h e   M i c r o s o f t   S t o r e : 
 
 
 h t t p s : / / a k a . m s / w s l s t o r e 
 
 
 

PS C:\Windows\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.22000.653

Image Version: 10.0.22000.675

Enabling feature(s)

[                           0.1%                           ] 

[                           1.1%                           ] 

[======                     10.6%                          ] 

[======                     11.8%                          ] 

[=======                    13.1%                          ] 

[========                   14.3%                          ] 

[=========                  15.6%                          ] 

[=========                  16.8%                          ] 

[==========                 18.1%                          ] 

[===========                19.3%                          ] 

[===========                20.6%                          ] 

[============               21.8%                          ] 

[=============              23.1%                          ] 

[==============             24.3%                          ] 

[==============             25.6%                          ] 

[===============            26.8%                          ] 

[================           28.1%                          ] 

[================           29.3%                          ] 

[=================          30.4%                          ] 

[==================         31.5%                          ] 

[==================         32.5%                          ] 

[==========================100.0%==========================] 
The operation completed successfully.

PS C:\Windows\system32> wsl --install -d Ubuntu
D o w n l o a d i n g :   U b u n t u 
 
 
 I n s t a l l i n g :   U b u n t u 
 
 
 U b u n t u   h a s   b e e n   i n s t a l l e d . 
 
 
 L a u n c h i n g   U b u n t u . . . 
 
 
 

PS C:\Windows\system32> wsl
W i n d o w s   S u b s y s t e m   f o r   L i n u x   h a s   n o   i n s t a l l e d   d i s t r i b u t i o n s . 
 
 
 D i s t r i b u t i o n s   c a n   b e   i n s t a l l e d   b y   v i s i t i n g   t h e   M i c r o s o f t   S t o r e : 
 
 
 h t t p s : / / a k a . m s / w s l s t o r e 
 
 <<< Ubuntu VM / WSL window pops up>>>
 Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x803b0001
Error: 0x803b0001 The network was not found.

Press any key to continue...
`

Attached is run of log collec
[WslLogs-2022-05-15_07-49-39.zip](https://github.com/microsoft/WSL/files/8694854/WslLogs-2022-05-15_07-49-39.zip)
t

**Comment by penguinpages** [comment]
<update>

I was trolling through services and features on my New fresh Win11 load.. And noted two entries in features about HyperV and "Virtual Machine"

I googled around and found this article
https://www.urtech.ca/2021/07/solved-hyperv-vs-virtual-machine-platform-vs-windows-hypervisor-platform-vs-windows-subsystem-for-linux-vs-windows-sandbox/

So I did a manual installation of Windows feature.

Reboot required

Now that "Windows Features" shows both HyperV and Virtual Machine Platform installed, I re-ran baseline:  <Powershell Administrator mode>

`PS C:\temp> wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\temp> wsl --list --online
The following is a list of valid distributions that can be installed.
Install using 'wsl --install -d <Distro>'.

NAME            FRIENDLY NAME
Ubuntu          Ubuntu
Debian          Debian GNU/Linux
kali-linux      Kali Linux Rolling
openSUSE-42     openSUSE Leap 42
SLES-12         SUSE Linux Enterprise Server v12
Ubuntu-16.04    Ubuntu 16.04 LTS
Ubuntu-18.04    Ubuntu 18.04 LTS
Ubuntu-20.04    Ubuntu 20.04 LTS
PS C:\temp> wsl  --install -d Ubuntu
Ubuntu is already installed.
Launching Ubuntu...
PS C:\temp>
`

Ubuntu start shell
`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x803b0001
Error: 0x803b0001 The network was not found.

Press any key to continue...`

So I ran diag script and attached

`PS C:\temp> Set-ExecutionPolicy Bypass -Scope Process -Force; .\collect-wsl-logs.ps1


    Directory: C:\temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/16/2022  11:01 AM                WslLogs-2022-05-16_11-01-01
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
get-acl : Cannot find path 'C:\ProgramData\Microsoft\Windows\WindowsApps' because it does not exist.
At C:\temp\collect-wsl-logs.ps1:35 char:1
+ get-acl "C:\ProgramData\Microsoft\Windows\WindowsApps" | Format-List  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
    + FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand

Log collection is running. Please reproduce the problem and press any key to save the logs.
Saving logs...
Press Ctrl+C to cancel the stop operation.
100%  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
The trace was successfully saved.
Logs saved in: C:\temp\WslLogs-2022-05-16_11-01-01.zip. Please attach that file to the GitHub issue.


PS C:\temp>`


[WslLogs-2022-05-16_11-01-01.zip](https://github.com/microsoft/WSL/files/8701175/WslLogs-2022-05-16_11-01-01.zip)

I will keep poking around.. but trying to help debug
