### ISSUE TITLE
Windows Server 2022 translation problem

### ISSUE THREAD

**Issue by wsy** [microsoft/WSL#8243]
### Version

Microsoft Windows [Version 10.0.20348.473]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Repro Steps

Fresh install Windows Server 2022 with language Simplified Chinese(zh-cn).
Enable Hyper-V/WSL.
Install WSL2 Kernel.
Run command `wsl --set-default-version 2`

### Expected Behavior

WSL is configured to use WSL2 by default.

### Actual Behavior

WSL does not recognize parameter `--set-default-version` because it has been localized to `--设置-默认-版本`.
Also, I tried to run `wsl --设置-默认-版本 2`. However, WSL still does not recognize.
Currently there's no way that I can configure WSL to WSL2.

### Diagnostic Logs

I tried to run `wsl --help`, and in help message, I see a lot of command line options got translated into Simplified Chinese.
I also tried to run `wsl --set-version Ubuntu 2` and `wsl --设置-版本 2`. Both commands are not recognized.
By the way, I tried Simplified Chinese version of Windows 11, this bug does not exist.

**Comment by wsy** [comment]
![image](https://user-images.githubusercontent.com/2684991/162226767-6aaacd04-7940-4df8-81d6-5643d37573ef.png)

**Comment by wsy** [comment]
Hi @benhillis ,
Although this issue is caused by localization. However, its impact is more than localization.
Currently there's no way I can configure my WSL to WSL2. Do you know any workaround that I can configuration my WSL installation as WSL2?

**Comment by DesktopECHO** [comment]
Windows Server 2019/2022 does not support WSL2.  For a brief time It was in beta builds up to 20298.

What throws people off is that the WSL utilities still reference WSL2, leading to hours of fruitless troubleshooting until they find this is the expected behavior.

**Comment by wsy** [comment]
Well, thanks for your answer.
This is quite frustrating to know this after hours of troubleshooting. (I guess WSL2 wasn't stable enough to get into LTSC?)
So, this issue, have two parts.
About the 'cannot switch to WSL2' part, it's 'by design'.
About the 'help message' part, it's indeed purely localization problem.

By the way, I see a lot of localization problems with Windows Server 2019/2022 Server Core installation.
I wonder where I can report them?

**Comment by DesktopECHO** [comment]
Unfortunately it's just a 'limitation' based on product differentiation.  At this time MS does not want WSL2 in its server OS offerings(1).  There has been some discussion about this limitation being lifted, but I won't hold my breath.

The other unfortunate thing to note is that with builds newer than 19044 (Which means Server 2022 and Windows 11) WSL1 has been [broken](https://github.com/microsoft/WSL/issues/7480) to the point of being unusable, going on 7 months and counting.  This was fixed in recent Beta/Insider builds and should show up in the next generally-available release.

Regarding localization, I suggest reporting your issues [here](https://techcommunity.microsoft.com/t5/all-languages/idb-p/AllLanguages).

(1) Recent Non-LTSC versions of Windows Server (feature-stripped, no GUI) can use WSL2, but my understanding is these SAC builds of Windows Server are going away.

**Comment by wsy** [comment]
Thanks a lot!

**Comment by wsy** [comment]
@DesktopECHO Hi, as Windows Server 2022 now supports WSL2, this problem have become something that Microsoft needs to fix.
