### ISSUE TITLE
Can not open wsl1 ubuntu os from Ubuntu app(Error: 0x80070050), but can from WSL.exe

### ISSUE THREAD

**Issue by lubyrex** [microsoft/WSL#8257]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Kernel version: 5.10.102.1

### Distro Version

20.04

### Repro Steps

I've set the wsl version to 1 after installation

running "C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04LTS_2004.4.5.0_x64__79rhkp1fndgsc\ubuntu2004.exe" (Or from start menu)

### Expected Behavior

System is already installed so it should operate normally. In fact running wsl.exe works fine

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070050
Error: 0x80070050 The file exists.

### Diagnostic Logs

https://aka.ms/AAglv0z

**Comment by NotTheDr01ds** [comment]
For anyone having this issue, please see my answers to a related question on [Ask Ubuntu](https://askubuntu.com/q/1401830/1165986).  And please let me know the results so that I can update the answers accordingly.

**Comment by benhillis** [comment]
This issue is inside Canonical's WSL distro app.

**Comment by NotTheDr01ds** [comment]
> This issue is inside Canonical's WSL distro app.

@benhillis From what I can tell, the issue *was* inside the *previous* version of Canonical's distro (specially "Ubuntu 20.04", the "versioned" distro).  Then Canonical fixed it in a new Store release, but anyone that had installed the previous version is now running into this error since the distro name changed and WSL can no longer find it.

The bad news is that I don't know of a way for Canonical to "fix it" for those that installed the "bad" release.  Unless they maybe release another one that checks for both distro names?

Given that it's possible for users to manually fix it on their own using the instructions I linked to above, *and* the fact that there's going to be a finite (and hopefully non-recurring) number of users that installed the bad version, I'm not sure Canonical's going to make that extra effort.

**Comment by benhillis** [comment]
yeah, best thing to do would be to back-up whatever you need, uninstall the app, then reinstall.
