### ISSUE TITLE
Many normal operations output what "wsl --help" outputs, under sufficiently new versions.

### ISSUE THREAD

**Issue by AuroraTea** [microsoft/WSL#8277]
### Version

Microsoft Windows Server [Version 20348.617]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Other Software

PowerShell
Docker Desktop 4.7.0
In fact, it is caused by WSL itself.

### Repro Steps

When typing "wsl --set-default-version 2", "wsl --set-version <release name> 2"

Including when Docker Desktop is started

### Expected Behavior

Finished converting the default version to wsl2.

### Actual Behavior

**no action, only the CLI will output what "wsl --help" outputs**

an error when Docker Desktop is started, the content of the error is also the output of "wsl --help"

Specific Contents:
```Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.

    --mount <Disk>
        Attaches and mounts a physical disk in all WSL2 distributions.

        Options:
            --bare
                Attach the disk to WSL2, but don't mount it.

            --type <Type>
                Filesystem to use when mounting a disk, if not specified defaults to ext4.

            --options <Options>
                Additional mount options.

            --partition <Index>
                Index of the partition to mount, if not specified defaults to the whole disk.

    --unmount [Disk]
        Unmounts and detaches a disk from all WSL2 distributions.
        Unmounts and detaches all disks if called without argument.```

### Diagnostic Logs

_No response_

**Comment by benhillis** [comment]
We have improved the behavior of wsl.exe output in the version of WSL that is in the Microsoft Store.

**Comment by DerekNonGeneric** [comment]
> We have improved the behavior of wsl.exe output in the version of WSL that is in the Microsoft Store.

@benhillis, I am experiencing the same problem as the OP (@AuroraTea). I am not sure if you have improved the behavior of `wsl.exe` output in the version of WSL that is in the Microsoft Store because I do not have access to that version as I am similarly on Microsoft Windows Server 2022, which generally lacks access to the Microsoft Store, but would imagine that everyone who recently updated is likewise experiencing this glaring bug.

**Version**

Microsoft Windows Server
Version 21H2 (OS Build 20348.643)
WSL Kernel version: 5.10.16

---

I ran into this problem while following the guide on &ldquo;[Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)&rdquo;, so seemingly everyone who follows this guide, will have in their commands that would allow them to use WSL 2 result in displaying the output of `wsl --help` instead of executing the desired following commands:

- `wsl.exe --set-default-version 2`
- `wsl.exe --set-version <Distro> 2`
- `wsl.exe --import <Distro> <InstallLocation> <FileName> --version 2`

![image](https://user-images.githubusercontent.com/17770407/163682000-74d210bd-de3f-439b-a103-ba9f92825430.png)

There are probably others, but from what I can tell, this effectively prevents all users from using WSL 2 at all in its current state and is even causing programs that interface with this CLI (like the latest Docker Desktop as can be seen above) to fail in expected ways.

---

Would anyone be able to provide a short-term fix or workaround for this? It's a bit of a roadblock.

**Comment by AuroraTea** [comment]
> 

Exactly the same.
Thank you for your wonderful and accurate presentation.

**Comment by AuroraTea** [comment]
@DerekNonGeneric Exactly the same.
Thank you for your wonderful and accurate presentation.

**Comment by OneBlue** [comment]
Thanks for reporting this @AuroraTea.

WSL2 isn't supported on Windows server (we're working on adding support, but it hasn't shipped yet).
I agree that the help text is misleading though, this should be fixed once WSL2 support comes to Windows server.

**Comment by AuroraTea** [comment]
@DerekNonGeneric WSL2 was available on Win Server 2022 yesterday!!!
