### ISSUE TITLE
WSL is not working normally. 

### ISSUE THREAD

**Issue by Subhasish-Behera** [microsoft/WSL#8283]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu  20.04

### Repro Steps

currently using zsh and ohmyzsh (THEME=Powerlevel10k)

### Expected Behavior

![Screenshot 2022-04-13 201850](https://user-images.githubusercontent.com/92573882/163208747-dbe0e452-173f-406a-8732-a6c4335b9ff8.png)

### Actual Behavior

![Uploading Screenshot 2022-04-13 124013.png…]()

### Diagnostic Logs

currently the wsl is not showing on which directory it is present.on running pwd its showing /home/greendoor.
if I wsl run on powershell its working fine.

**Comment by benhillis** [comment]
Looks like one of your screenshots did not upload.

**Comment by Subhasish-Behera** [comment]
![Screenshot 2022-04-13 201932](https://user-images.githubusercontent.com/92573882/163310717-f9a85f9c-23ae-4e3a-b00e-f0da3460c5e3.png)

**Comment by OneBlue** [comment]
Thanks for reporting this @Subhasish-Behera.

Displaying the current directory is something that is handled by the shell (zsh in your case). 

The shell prompt is controlled by `$PS1`, which is not something that WSL does (in your case it's probably done in ~/.zshrc, or one of the oh-my-zsh plugins) .

Closing since this is not a WSL issue.
