### ISSUE TITLE
No network access in WSL 2 while ethernet network interface is enabled

### ISSUE THREAD

**Issue by KyleRAnderson** [microsoft/WSL#8287]
### Version

Microsoft Windows [Version 10.0.22000.593]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

All distros, though I use Ubuntu 21.10 mainly

### Repro Steps

With a computer that has both a WiFi network interface and an ethernet one:
1. Attempt to connect to the internet in any WSL 2 distribution, with something like: `ping 8.8.8.8`. For me, no packets get through. The same is true for anything that uses internet (e.g. `apt-get`, `git`, ...).

### Expected Behavior

While connected to ethernet or WiFi, WSL 2 distributions will have network connectivity.

### Actual Behavior

I'm running this on a Surface Book 2, so the ethernet is connected via a USB-C hub. I'm not sure if this would make a difference.

With both a WiFi and ethernet network interface enabled and active (both are connected to a network), I've tried to access the network from within any WSL 2 distribution with commands like `ping 8.8.8.8` and had no success - no network is accessible from within the distribution. This is with no VPNs or any special network configurations. I am however still able to use Windows binaries from the distribution and they have network access, which is my current workaround for things like `git clone` that is far from optimal.
I've tried the same thing after disabling the WiFi interface so that the ethernet interface is the only one, and this still does not work.
However, if I disable the ethernet interface and enable only the WiFi one, then everything works fine. So it seems that if the ethernet interface is enabled at all, I have networking issues.

Other things I have tried:
- Disabling Windows firewall completely.
- Changing the network type from public to private.
- Windows Network reset
- Connecting to a VPN using the OpenVPN client. Oddly enough, this fixes the issue.
- I have not tried plugging in to a different network to see if there's something specific about my current one that's causing this. I can try this soon.

An additional note: I experience the exact same behaviour when using the Windows Sandbox, and since I know the common denominator between Windows Sandbox and WSL 2 is Hyper-V, I believe the issue is there.

Similar issues: #5336, #4731.

### Diagnostic Logs

Networking diagnostics retrieved from [networking.bat](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues):
[wsl.etl.zip](https://github.com/microsoft/WSL/files/8483965/wsl.etl.zip)

**Comment by JCMarques15** [comment]
Seems i have exactly the same issue, but on a Dell laptop. The moment i disabled the Ethernet adapter networking inside the WSL 2 started working, though now i am struggling with name resolution... its not easy to get WSL 2 to work 😆

**Comment by import-shiburin** [comment]
Exactly same issue here, any update?

**Comment by sorryusernameisalreadytaken** [comment]
@KyleRAnderson, @JCMarques15, @huiminghao, @import-shiburin or @mikecirioli does anybody of you facing the problem in all kind of networks. I just want to know if your problems with connecting your wsl2 to the internet could be the same like my one here:
https://github.com/microsoft/WSL/issues/10016

And please fill in your networking logs here. You can check:
['Networking issues']'https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues)

THX :)

**Comment by sfc-gh-kyanderson** [comment]
I have recently been using WSL 2 on a different wired network from the one I originally reported this on and network connectivity was fine with both the WiFi and ethernet interfaces enabled. This plus the fact that connecting to a VPN fixed the issue originally makes me think that there was something peculiar about the network I reported this on that was causing it, though I don't know what. Hopefully that information would be in the network diagnostic  package I attached, though there doesn't seem to be much interest in looking into this issue.

**Comment by Deig0l** [comment]
Ayo, i fixed this with claude. My problem was that everytime I switched from one connection mode to another the WSL connection failed, so if I happen to change from ethernet to wifi or viceversa everything broke, this was annoying because it happened at the worst moments like presenting a project that was in my WSL. Basically what claude did was create an script to restart adapters adn so my wsl updated his connection info.

Here's an example:

<html>
<body>
<html><head></head><body><h1>WSL2 Loses Internet When Switching Between Ethernet and Wi-Fi</h1>
<blockquote>
<p>A permanent fix for WSL2 internet dropping when switching network interfaces on Windows.</p>
</blockquote>
<h2>Why It Happens</h2>
<p>WSL2 uses a <strong>Hyper-V virtual switch</strong> to share Windows' network connection. When you switch between Ethernet and Wi-Fi, that virtual switch dies and takes WSL's internet with it. You'll notice:</p>
<ul>
<li><code>ping 8.8.8.8</code> fails from inside WSL</li>
<li>WSL has an IP but can't reach the gateway</li>
<li>Everything works again after a full Windows reboot</li>
</ul>
<hr>
<h2>The Fix — Automated Network Watch Script</h2>
<p>Instead of rebooting every time, this script watches for network changes and automatically restarts the WSL adapter.</p>
<h3>Step 1 — Create the script</h3>
<p>Open <strong>PowerShell as Administrator</strong> and run:</p>
<pre><code class="language-powershell">$script = @'
$query = "SELECT * FROM Win32_NetworkEvent WHERE EventType = 2"
Register-WmiEvent -Query $query -Action {
    Start-Sleep -Seconds 5
    Get-NetAdapter | Where-Object { $_.Name -like "*WSL*" } | Disable-NetAdapter -Confirm:$false
    Start-Sleep -Seconds 2
    Get-NetAdapter | Where-Object { $_.Name -like "*WSL*" } | Enable-NetAdapter -Confirm:$false
    Start-Sleep -Seconds 3
    &amp; wsl --shutdown
}
'@
Set-Content -Path "$env:USERPROFILE\wsl-network-watch.ps1" -Value $script
</code></pre>
<h3>Step 2 — Register it as a startup task</h3>
<pre><code class="language-powershell">$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -File `"$env:USERPROFILE\wsl-network-watch.ps1`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0
Register-ScheduledTask -TaskName "WSL Network Watch" -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force
</code></pre>
<h3>Step 3 — Start it immediately (no reboot needed)</h3>
<pre><code class="language-powershell">Start-ScheduledTask -TaskName "WSL Network Watch"
</code></pre>
<p>That's it. The task will now run silently on every Windows login.</p>
<hr>
<h2>How It Works</h2>

Step | What happens
-- | --
You switch networks | Windows detects the network change event
5 second delay | Waits for Windows to fully establish the new connection
WSL adapter restart | Disables and re-enables the Hyper-V virtual switch
WSL shutdown | Cleanly restarts WSL so it picks up the new network
Done | WSL comes back online automatically in ~10 seconds


<hr>
<h2>Verify It's Running</h2>
<p>Open <strong>Task Scheduler</strong> (search in Start menu) and look for <strong>"WSL Network Watch"</strong> — it should show as <code>Running</code>.</p>
<p>Or check via PowerShell:</p>
<pre><code class="language-powershell">Get-ScheduledTask -TaskName "WSL Network Watch" | Select-Object TaskName, State
</code></pre>
<hr>
<h2>Manual Fix (if needed)</h2>
<p>If WSL ever gets stuck, run this from PowerShell Admin:</p>
<pre><code class="language-powershell">Get-NetAdapter | Where-Object { $_.Name -like "*WSL*" } | Disable-NetAdapter -Confirm:$false
Start-Sleep -Seconds 2
Get-NetAdapter | Where-Object { $_.Name -like "*WSL*" } | Enable-NetAdapter -Confirm:$false
wsl --shutdown
</code></pre>
<hr>
<h2>Bonus — Stop Postgres From Breaking Too</h2>
<p>If you run PostgreSQL on both Windows and WSL, Windows Postgres often conflicts on port <code>5432</code>. The clean solution is to <strong>run Postgres only inside WSL</strong>.</p>
<h3>1. Uninstall Postgres from Windows</h3>
<p>Remove it via <strong>Add or Remove Programs</strong> in Windows Settings.</p>
<h3>2. Install Postgres inside WSL</h3>
<pre><code class="language-bash">sudo apt install -y postgresql postgresql-contrib
</code></pre>
<h3>3. Enable systemd so it auto-starts</h3>
<p>Add this to <code>/etc/wsl.conf</code> inside WSL:</p>
<pre><code class="language-ini">[boot]
systemd=true
</code></pre>
<p>Then enable Postgres:</p>
<pre><code class="language-bash">sudo systemctl enable postgresql
sudo systemctl start postgresql
</code></pre>
<h3>4. Connect from DataGrip / any client</h3>
<p>Point your database client to:</p>
<pre><code>Host: 127.0.0.1
Port: 5432
</code></pre>
<p>No more killing Windows Postgres processes on every boot.</p>
<hr>
<h2>Recommended Dev Workflow</h2>
<p>Keep <strong>everything inside WSL</strong> and treat Windows purely as the host:</p>
<ol>
<li>Boot Windows → network watch script starts automatically</li>
<li>Open your terminal (Warp, Windows Terminal, etc.) → connect to WSL</li>
<li>Start your IDE (VS Code, Cursor, Antigravity, etc.)</li>
<li>Open DataGrip → connects to WSL Postgres at <code>127.0.0.1:5432</code></li>
<li>Switch networks freely → WSL recovers on its own in ~10 seconds ✅</li>
</ol>
<hr>
<h2>Environment</h2>
<p>Tested on:</p>
<ul>
<li>Windows 11</li>
<li>WSL2 (Debian)</li>
<li>Hyper-V enabled</li>
<li>Switching between Ethernet and Wi-Fi</li>
</ul>
<hr>
<p><em>Found this helpful? Star the repo and share it with others hitting the same issue!</em> 🚀</p></body></html>
</body>
</html>

So yea, hope this helps anyone
