### ISSUE TITLE
WDM Audio playback disrupts (vmwp.exe)

### ISSUE THREAD

**Issue by marc5000** [microsoft/WSL#8346]
Hello,

I use WSL to develop for Linux. I also listen to music while developing :) 

Whenever any task is undertaken by the "virtual machine worker process" (vmwp.exe); audio on Windows is choppy.

It can be disruptive, especially when audio playback should be uninterrupted.

I'm on Windows 10 Pro; 21H2 (19044.1645)

You can replicate the issue with any WDM audio playback device.

1. Start up your WSL machine, so the vmwp.exe task starts.
2. Reboot the WSL machine (Services: LxssManager)

Observe audio breakage.

_Notes:_ 

- Setting a 'Below normal' priority for vmwp.exe does not make a difference.
- My audio settings for the WDM device are to allow 'Exclusive Mode'.
- I'm using Spotify for audio playback, but any playback software can be used (VLC etc.)

If you need any more information, I'd be happy to supply it.

**Comment by owenschupp** [comment]
Hello! Would you mind resubmitting your issue using our issue template (which you can find [here](https://github.com/microsoft/WSL/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.yaml))? That would provide us some more information to help you further. From what it sounds like right now, it seems like this issue may be due to performance with the virtual machine worker process (`vmwp.exe`), which is a component of Hyper-V and not directly related to WSL, although WSL does make use of Hyper-V.
