### ISSUE TITLE
Terminal GUIs Display Issue

### ISSUE THREAD

**Issue by Brandantl** [Microsoft/WSL#836]
For example using something like "sudo apt-get install ttf-mscorefonts-installer" cause the border of the EULA Yes/No Window to become control characters and resizing the window makes it significantly worse.
[True Fonts WSL](http://brandanlasley.com/truefonts.PNG)
[True Fonts Normal](http://www.ihaveapc.com/wp-content/uploads/2011/10/ubuntu-restricted-extras_004.png)

You can still control the GUI and accept the EULA.

**Comment by fpqc** [comment]
=)

Were you trying to run WINE on Ubuntu on Windows?

**Comment by benhillis** [comment]
@fpqc Internally we jokingly refer to this as "Inception"

**Comment by Brandantl** [comment]
It is quite possible I was trying to install wine. Wasn't successful though.

**Comment by zadjii-msft** [comment]
This looks like funky UTF-8 support problems. Out of curiosity, which language/keyboard are you using? 
You should be seeing line drawing characters there ('\u2518', '\u2510', '\u250c', '\u2514', '\u2530', '\u23ba', '\u23bb', etc), but I'd like to find out why those are getting translated to other unicode characters.

**Comment by Brandantl** [comment]
English / US QWERTY keyboard.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
