### ISSUE TITLE
Arch installation failed.

### ISSUE THREAD

**Issue by YeasinTahsin** [microsoft/WSL#8476]
I was trying to install arch in wsl.
I downloaded arch.zip from github.
then i double pressed the arch.exe and it started to installing.
But suddenly load-shedding happen and my pc turned off.
after a few seconds when i again trying to install arch then it gives me this error.
Please, help me.
![Capture](https://user-images.githubusercontent.com/99527781/172164068-0e64a2bd-4e58-473e-9564-f675298eb850.PNG)

**Comment by elsaco** [comment]
@YeasinTahsin the `arch.zip` has two files, `rootfs.tar.gz` and the installer `arch.exe`. Instead of using the installer use `wsl --import` command:

`wsl --import <Distro> <InstallLocation> <FileName> [Options]`

This is the command I've used:

`PS C:\> wsl --import Arch C:\Linux\Arch\ C:\Temp\rootfs.tar.gz`

and the result:

```
[root@RIPPER ~]# cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
IMAGE_ID=archlinux
IMAGE_VERSION=2022.02.01

```
