### ISSUE TITLE
[Question] how to get windows ip address in wsl2?

### ISSUE THREAD

**Issue by suguanYang** [microsoft/WSL#8549]
I have an HTTP proxy server in the windows(bound on the port 7890),  I also want to use that proxy in the wsl2, for now, I was using `export http_proxy=http://<WINDOWS-IP-ADDR>:7890`, but the WINDOWS-IP-ADDR was not a fixed value, it was a little annoying to check the windows IP address every time I changed the network, is there any way to check the windows IP address automatically in wsl2? or maybe we need some kind of IP discovery service?

**Comment by elsaco** [comment]
@suguanYang if you didn't disable interop all the Windows tools are available inside WSL, i.e. `netsh`, `ipconfig`, `wmic`. You'll have to use the full name like `netsh.exe` otherwise it'll fail with command not found.

On the Linux side you could use `host` or `nslookup` and parse the IP from the interface of your choice.
