### ISSUE TITLE
Failed to import a tar file

### ISSUE THREAD

**Issue by Takym** [microsoft/WSL#8593]
### Version

Microsoft Windows [Version 10.0.19044.1766]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-18.04

### Other Software

* Windows Terminal (Version: 1.13.11431.0)

### Repro Steps

```cmd
D:
mkdir .\MyUbuntu\lxss
cd D:\MyUbuntu
wsl --export Ubuntu-18.04 Ubuntu-18.04.tar
wsl --import MyUbuntu D:\MyUbuntu\lxss .\Ubuntu-18.04.tar
```

Also, I tried `--version 1` and `--version 2` options but these still failed.

### Expected Behavior

I expect the WSL command tool should succeed in importing a tar file with no errors.
https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro#importing-centos-example

### Actual Behavior

![image](https://user-images.githubusercontent.com/15681312/178143771-b340781d-b8d3-40b9-93fe-13b97c17e27a.png)
![image](https://user-images.githubusercontent.com/15681312/178144089-95a03640-ca18-481b-b9c6-773be9300392.png)

* Importing a tar file exported from WSL 1 (Ubuntu 18.04) failed on both WSL 1 and WSL 2.
* Importing a tar file exported from WSL 2 (Ubuntu) succeeded on both WSL 1 and WSL 2.
* "エラーを特定できません" means "Could not determine the error."
* "バージョン番号を解析できませんでした。" means "Could not parse the version number."
    * This error is not related to this issue. I just mistyped.
* "仮想ディスク システムの制限により、..." is about compression on the directory.
    * I resolved this error by disabling the compression option on Windows Explorer.

**Comment by Takym** [comment]
https://aka.ms/AAhfhaz

**Comment by OneBlue** [comment]
Thanks for reporting this @Takym.

Looking at the logs it looks like the issue is 

`./var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.6/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.6/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.6/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.6/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.6/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/zlib-1.1.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-LightItali` 

Looks like this is causing the distribution tar to fail to extract. Maybe some links in that directory are broken ?

**Comment by Takym** [comment]
Dear @OneBlue,

Thank you for replying.

For some reason, it looks like a link target does not exist.

**Comment by Takym** [comment]
In my environment, those link files target to a file in a directory `../../../../../../../../share/`. For example, `/var/lib/gems/2.5.0/doc/webrick-1.6.1/rdoc/js/jquery.js` refers to `../../../../../../../../share/javascript/jquery/jquery.min.js`.

I propose to allow to display of archive file errors and ignore them.
