### ISSUE TITLE
wslservice.exe hanging

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#8628]
### Version

Microsoft Windows [Version 10.0.22621.290]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian 11

### Other Software

vscode 1.70.0-insider
podman.exe version 4.2.0-dev

### Repro Steps

It's not really clear exactly what provokes this issue and I'm trying to narrow this down so guidance on best way to gether more information about this would be appreciated.

### Expected Behavior

wslservice does not hang

### Actual Behavior

I'm seeing a problem where after using wsl for a while any command trying to access wslservice hangs. This could be trying to start a new wsl session via the windows terminal menu. Trying to access a distro via vscode or running a command like "wsl..exe --status" or "wsl.exe --shutdown", commands like "wsl.exe --help" or "wsl.exe --version" do not hang. Running process explorer I am able to see several wsl.exe sessions running if I have a PowerShell window open and running "wsl.exe --status" command which is hanging killing the wsl.exe sessions does not affect the hang but killing wslservice.exe allows the wsl.exe command to rxit and when a new wslservice.exe is started I am able to run the  "wsl.exe --status" command without issue. I did see issue :all wsl.exe commands hang · Issue #4144 · microsoft/WSL (github.com)" which is related but this issue is closed with a request to file a new issue. I would like to get guidance on how best to debug this further as I have been unable to find very little information on this service. Does it generate a log file somewhere? Please provide some pointers

Default Distribution: Alpine
Default Version: 2
WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.290

**Comment by extensia** [comment]
I am seeing similar issues along with a completely broken Docker Desktop. Everything was working fine until the latest Windows updates landed. Now Docker Desktop attempts to start on reboot and then shuts down after a couple of minutes since it is failing to start docker-desktop-data. After rebooting, I can able to establish new Linux sessions for a minute or two, then attempting to start new sessions fails with a communications timeout. I suspect that is what is preventing Docker Desktop from starting.

I found that the LxssManager service also hangs when stopping the service. I was able to stop and restart the service by killing the corresponding svchost process. After restarting the service I am temporarily able to start new sessions again, but wsl reverts to the broken state again after a few minutes. Uninstalling Docker Desktop make wsl somewhat more usable, but the hang still problem still occurs only less frequently.

Ongoing stability problems with wsl and Docker Desktop are creating major problems for our development workflow. The amount of time wasted (three man days and counting) is forcing us to revert to remote development on Linux VMs hosted on VMware ESXi. Troubleshooting is proving near impossible due to the dearth of diagnostic tools.

**Comment by benhillis** [comment]
Thanks for reporting. Any clues how you got into this state so we can repro?

also: /logs

**Comment by OneBlue** [comment]
Thanks for reporting this @mwoodpatrick .

Can you please share dump of a hanging wslservice.exe ?

**Comment by mattjuk** [comment]
+1 for this. Since the latest Windows 11 update my WSL now no longer launches at all via Windows Terminal.

**Comment by mwoodpatrick** [comment]
I'm still having this issue see attached log
[WslLogs-2022-08-21_07-19-26.zip](https://github.com/microsoft/WSL/files/9389309/WslLogs-2022-08-21_07-19-26.zip)
s
