### ISSUE TITLE
Interop is broken when WSL is started prior to user logon

### ISSUE THREAD

**Issue by KentoNishi** [microsoft/WSL#8643]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Create a task scheduler entry with the following settings:
![image](https://user-images.githubusercontent.com/38841491/180625655-b92f8162-3586-4957-bb56-2d089bb0ecfb.png)
![image](https://user-images.githubusercontent.com/38841491/180625662-ff2d9caf-7d0e-421b-b8c1-217007f03325.png)
![image](https://user-images.githubusercontent.com/38841491/180625666-1ce793f6-2881-4ea2-b0ac-3ae4a2f5e9db.png)
![image](https://user-images.githubusercontent.com/38841491/180625673-8f4730e3-8a8e-4b5d-8a63-001987907f2f.png)
![image](https://user-images.githubusercontent.com/38841491/180625681-b1e2e3c5-68d0-4f84-b12b-d431f6053c14.png)

2. Restart the machine
3. Log into Windows as usual
4. Open WSL and execute cmd.exe, observe that interop (both wslg and executing .exe files) do not work

### Expected Behavior

WSL should work as intended, regardless of whether it was launched from a command line prior to logon or not.

### Actual Behavior

![image](https://user-images.githubusercontent.com/38841491/180517785-07a84371-228a-450c-8c2b-14b91bba3fd4.png)

### Requested Change

I would like WSL to have an option to launch at system startup. Without such an option, it is impossible to start WSL automatically without breaking interop.

**Comment by NotTheDr01ds** [comment]
This may be the same as #4260.  This can occur if the 9P server isn't working correctly.  If you try to access `\\wsl$\Ubuntu` (or whatever the distribution is named -- could be `Ubuntu-20.04`), does that work?

**Comment by KentoNishi** [comment]
> This may be the same as #4260. This can occur if the 9P server isn't working correctly. If you try to access `\\wsl$\Ubuntu` (or whatever the distribution is named -- could be `Ubuntu-20.04`), does that work?

no, it isn't. is this an issue on my end, or is this a bug with wsl?

**Comment by NotTheDr01ds** [comment]
@KentoNishi Could be either, honestly.  Based on a number of comments in #4260, it may be a permission/ownership issue.

In scanning through #4260, it sounds like that particular issue was due to the WSL distribution being "owned" by the Administrator, rather than your regular user.  One (but not the only) cause of this could be installation via `chocolatey`.

If it is the permission issue, then a common fix for the `\\wsl$\..` problem, at least, is to ...

Start an Admin prompt (PowerShell or CMD):

```
wsl -l -v
# Confirm the correct distro name, and substitute below as needed
subst s: \\wsl$\Ubuntu-20.04\home\
```

If that resolves your `\\wsl$\` issue, then hopefully/perhaps it will also resolve the `Invalid argument` one.

**Comment by elsaco** [comment]
@KentoNishi what is the output of `wslpath -w /mnt/c/Windows/system32/cmd.exe` when run from `/root`? It should be `C:\Windows\system32\cmd.exe`. When you run `cmd.exe` from a WSL prompt it defaults to this path, because of UNC.

Sample output:
```
[root@eleven elsaco]# cd ~
[root@eleven ~]# cmd.exe
'\\wsl.localhost\ArchLinux\root'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Microsoft Windows [Version 10.0.22000.832]
(c) Microsoft Corporation. All rights reserved.

C:\Windows>
```

**Comment by KentoNishi** [comment]
> @KentoNishi what is the output of `wslpath -w /mnt/c/Windows/system32/cmd.exe` when run from `/root`? It should be `C:\Windows\system32\cmd.exe`. When you run `cmd.exe` from a WSL prompt it defaults to `C:\Windows\system32` because of UNC.
> 
> Sample output:
> 
> ```
> [root@eleven elsaco]# cd ~
> [root@eleven ~]# cmd.exe
> '\\wsl.localhost\ArchLinux\root'
> CMD.EXE was started with the above path as the current directory.
> UNC paths are not supported.  Defaulting to Windows directory.
> Microsoft Windows [Version 10.0.22000.832]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Windows>
> ```

it's `C:\Windows\system32\cmd.exe`

**Comment by KentoNishi** [comment]
Update: I think I figured out what was going wrong. I had a task scheduler entry to auto-start my wsl instance on startup without login, and disabling that made it work again. I assume that wsl interop depends on the desktop environment being fully loaded? This error disappeared when I disabled the task scheduler item.

**Comment by NotTheDr01ds** [comment]
@KentoNishi Good find.  And most likely -- It's been a while since I've done that, so I don't remember the exact details, but I did have issues with WSL instances started via Task Scheduler at Computer Startup.  Something has probably changed since then, since I believe my problem was that the instance would self-terminate even if a service was running inside it if it wasn't "associated" with the desktop.  But it's clear that WSL behaves differently when started without a desktop/logged-in user.

You might want to edit the main issue above to make it clear (without reading the comments) how to reproduce the issue.

**Comment by KentoNishi** [comment]
I updated the title and issue content.

**Comment by KentoNishi** [comment]
@OneBlue
[WslLogs-2022-07-26_14-58-28.zip](https://github.com/microsoft/WSL/files/9193578/WslLogs-2022-07-26_14-58-28.zip)
