### ISSUE TITLE
Lenovo Yoga C940 Screen flickering after turning on from hibernation when virtualization is enabled for WSL2

### ISSUE THREAD

**Issue by Richard-code-gig** [microsoft/WSL#8668]
Just as exactly as the headline, turning on Virtual Machine Platform to install WSL2 causes Lenovo Yoga C940 screen to flicker after waking from hibernation. Also, it makes the laptop very slow and unusable when screen sharing on apps like Zoom and Teams.

**Comment by A2ureStone** [comment]
I also found this problem when turning on Virtual Machine Platform. My machine is Lenovo-XIAOXIN-14ARE 2020. After disabling the Virtual Machine Platform, the issue disappered.

**Comment by Faheetah** [comment]
Same issue on ASUS studiobook H5600QM. Screen flickers. Disabled WSL and it stopped for a while. Enabled it again today and instantly flickering. On AMD embedded GPU. Doesn't flicker when it is in game using Nvidia card. Really annoying because other than light gaming the point of this laptop is for development with WSL.
