### ISSUE TITLE
wslvar and wslpath do not work in tmux

### ISSUE THREAD

**Issue by tan-wei-xin-alez** [microsoft/WSL#8706]
### Version

Microsoft Windows [Version 10.0.19042.1466]

### WSL Version

WSL 2

### Kernel Version

Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

### Distro Version

Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy

### Other Software

tmux 3.3a

### Repro Steps

1. Download tarball from https://github.com/tmux/tmux/releases/tag/3.3a (currently latest version, older version i.e. 3.2a installed via `sudo apt install tmux` also encounters same problem)
2. Install tarball based on instructions at https://github.com/tmux/tmux/wiki/Installing#from-source-tarball
3. Run `tmux`
4. Run `wslvar -S` within tmux session
5. Run `wslpath -w "${HOME}"` within tmux session

### Expected Behavior

1. output of `wslvar -S` within tmux should be the same as in bash on WSL2 e.g.
```
Name                           Value                                                                                   
----                           -----                                                                                   
ALLUSERSPROFILE                C:\ProgramData                                                                          
...                   
windir                         C:\Windows                                                                              
ZES_ENABLE_SYSMAN              1
```

2. output of `wslpath -w "${HOME}"` within tmux should be the same as in bash on WSL2 i.e. `\\wsl$\<distro_name>\home\<username>`

### Actual Behavior

1. Running `wslvar -S` within tmux yields no output

2. Running `wslpath -w "${HOME}"` within tmux returns `wslpath: /home/<username>: Invalid argument`

### Diagnostic Logs

Issue opened in tmux repo at https://github.com/tmux/tmux/issues/3295 but tmux developer suggests asking WSL developer as they do not know how `wslvar` and `wslpath` work

**Comment by benhillis** [comment]
FYI: I was not able to reproduce this on 0.65.3.

**Comment by NotTheDr01ds** [comment]
I'm also not able to reproduce it on either 0.64.0 on Windows 11 nor GA 21H2 Windows 10 (19044.1826).  Tried on a freshly install 22.04 on both (with `sudo apt update && sudo apt upgrade -y`, which took a few hours since the repos were down earlier).

@tan-wei-xin-alez Some points of clarification.  `wslvar` is part of the `wslu` package, which isn't installed on 22.04 by default.  I'm assuming you added the PPA for it?

I'm suspecting something in your `~/.tmux.conf` or `~/.bashrc` (or equivalent).

Try starting WSL with `wsl ~ -d Ubuntu-22.04 -e bash --noprofile --norc` to eliminate the bash startup.  Then try it again there.

If it's still not working, try eliminating the Tmux conf by:

```
touch ~/tmux.empty.conf
tmux -f ~/tmux.empty.conf
```

**Comment by tan-wei-xin-alez** [comment]
> @tan-wei-xin-alez Some points of clarification. `wslvar` is part of the `wslu` package, which isn't installed on 22.04 by default. I'm assuming you added the PPA for it?

Oh, now that you mentioned it, my original install was 20.04 before I upgraded to 22.04, this would explain why `sudo apt install ubuntu-wsl` behaves as if I do not have it installed

> I'm suspecting something in your `~/.tmux.conf` or `~/.bashrc` (or equivalent).

My tmux installation is fresh so I do not have `~/.tmux.conf` and my `~/.bashrc` is also the stock version (minus the use of `wslvar` in it which is what caused me to notice the problem in `tmux`)

I'm guessing I need to remove the `wslu` (v3.2.3-1) that was preinstalled in 20.04 and then install a newer version via `apt`
Would you happen to know which directories I need to manually delete?
I can find all the binaries listed on https://wslutiliti.es/wslu/ with `which` but would deleting them alone be enough?

**Comment by NotTheDr01ds** [comment]
> but would deleting them alone be enough?

Unfortunately not.  There are other registrations besides just the binaries that the `wslu` package creates.  I'm not sure what all of them are, personally, but I just came across `/usr/share/applications/wslview.desktop` when looking at [this question](https://askubuntu.com/q/1422920/1165986) on Ask Ubuntu.

**Comment by NotTheDr01ds** [comment]
@tan-wei-xin-alez Well, I'm noticing that the latest version that I installed from the PPA appears to be:

```
wslu v3.2.3-1
```

So that's not going to change.  Still, you should probably add the PPA so that you get future updates now that the package isn't in the 22.04 repos:

```
sudo add-apt-repository ppa:wslutilities/wslu
sudo apt update && sudo apt upgrade -y
```

Note however, that `wslpath` is no longer part of that package (and hasn't been in a while, iirc).  It's actually built-in to WSL now (via a symlink to `/init`), so the fact that it isn't working for you indicates that you aren't experiencing an issue with `wslu` specifically.

**Comment by NotTheDr01ds** [comment]
What's still troubling me is what `tmux` could possibly have to do with it.  I also tried just now with 3.3a, but I'm still not able to reproduce.

You aren't running any type of Systemd script (e.g. Genie or DistroD), right?

What's `ls -l $(command -v wslpath)` show?  It should point to `/init`.

Is interop working in general?  Can you run `notepad.exe` from within tmux (and without)?

**Comment by tan-wei-xin-alez** [comment]
> What's `ls -l $(command -v wslpath)` show? It should point to `/init`.
It returns `lrwxrwxrwx 1 root root 5 Nov  1  2021 /usr/bin/wslpath -> /init` both from outside and within tmux

> You aren't running any type of Systemd script (e.g. Genie or DistroD), right?
> Is interop working in general? Can you run `notepad.exe` from within tmux (and without)?
Ahhh, now this is interesting, I just realized I had another `tmux` session running on an `x2goserver` in the background and if I kill it, then start `tmux` in wsl on my powershell terminal (I'm using pwsh 7) before running `tmux` on the `x2goserver` then `notepad.exe` starts working as well as `wslvar -S` and `wslpath -w "${HOME}"` on both environments

But if I then run `tmux kill-server` and then run `tmux` on the `x2goserver` first before running `tmux` in wsl on my powershell terminal, interop breaks completely in both environments i.e. `notepad.exe` opens nothing, `wslvar -S` outputs nothing and `wslpath -w "${HOME}"` returns `wslpath: /home/<username>: Invalid argument`

I'm guessing it has something to do with the protocol x2go uses which causes interop to mess up if tmux is started on the `x2goserver` first

**Comment by NotTheDr01ds** [comment]
@tan-wei-xin-alez  Now *that* I can reproduce, and it makes sense.  You can easily get around it by starting the second tmux session with a different socket:

```
tmux -L other
```

I'm able to reproduce it with a similar use-case:

* Install and configure Xfce4 and Xrdp (on port 3390) as noted in [this Ask Ubuntu answer](https://askubuntu.com/a/1365455/1165986).
* Connect via Remote Desktop to `localhost:3390`
* Start a terminal
* Note Interop, `wslpath`, and `wslvar` don't work inside Xfce4 (and likely x2go).
* Starting `tmux` will result in the tmux server inheriting *that* environment (in your case x2go's)

When you then start tmux in the "main" WSL instance, it finds the socket created by the first tmux server and connects to it, thus sharing that "bad" (from the WSL perspective) environment.

It's also likely possible to "fix" things inside the x2go environment before starting tmux, but I haven't tried it yet.

But regardless, I'm assuming that you would agree that we've established this isn't a WSL issue?  If so, can you close it?

**Comment by NotTheDr01ds** [comment]
Oops, I just realized that the Xfce4 case and X2go are somewhat different.

In Xfce4 with Xrdp, I *can* access `wslpath` and `wslvar` as expected.

Also, Interop *does* work, although with the `$PATH` reset, none of the Windows paths are on it, so I have to call `/mnt/c/Windows/System32/notepad.exe`, for instance.

I'm guessing that X2go is breaking Interop either because:

* It attempts to run in a namespace with something else as PID1, meaning the WSL `/init` process is no longer available.
* Or, more likely, it calls something that overwrites or re-registers the `binfmt_misc` registration for WSL.

**Comment by tan-wei-xin-alez** [comment]
> But regardless, I'm assuming that you would agree that we've established this isn't a WSL issue? If so, can you close it?

Yes, sure and for anyone in the future who's interested, a bug report has been filed at https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1591
