### ISSUE TITLE
setuid binaries don't work when installed in `/run`

### ISSUE THREAD

**Issue by jaccarmac** [microsoft/WSL#8716]
### Version

WSL version: 0.65.3.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

GuixSD a81706494753ad84754cbb7583ccc783452decc0

### Repro Steps

`sudo` (or any other binary in `/run/setuid-programs`)

### Expected Behavior

`usage: sudo...`

Guix has another copy of sudo in `/run/current-system/profile/bin`, and that works fine. It's a link to a binary in the `/gnu` subtree but is otherwise identical (binary and permissions).

### Actual Behavior

`sudo: effective uid is not 0, is /run/setuid-programs/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

### Diagnostic Logs

`mount -l` suggests that `/run` is indeed mounted with `nosuid`. The error appeared after a kernel upgrade. I'd like to roll back to determine whether the mount options were different before but am not sure how.

**Comment by NotTheDr01ds** [comment]
Can you provide details on how you installed Guix?  I might give it a spin if it's not too time consuming.

> I'd like to roll back to determine whether the mount options were different before but am not sure how.

On recent GA releases of WSL, try:

```
wsl --update --rollback
```

This assumes the presence of a `C:\Windows\System32\lxss\tools\kernel.rollback` file, which is automatically created on a `wsl --update`.

**Comment by jaccarmac** [comment]
> On recent GA releases of WSL, try: ...

Unfortunately, I'm using the Store version, so that didn't work for me. Thanks!

> Can you provide details on how you installed Guix? I might give it a spin if it's not too time consuming.

I can, though I used a mix of two methods and so can't guarantee reproducibility exactly.

[The SystemCrafters guide](https://github.com/SystemCrafters/wiki-site/blob/d4ed68f0bc120c835c15ca79b669774a7711f613/content/guix/wsl.org) is close to my stage 0; I used the first linked Gist to get started before finding the smaller `operating-system` definition.

I wanted to minimize image size and remove the Busybox dependency, and to do that I created a Docker image using `guix system`, ran it, exported the filesystem to the Windows filesystem, and imported it from WSL. That's arguably less fiddly if you have a way to run Guix and Docker already, though it requires reconfiguring the new system, cleaning up the old generations, and rebooting to make sure networking plays nice.

> Alternatively, can you reverse engineer what Guix is doing

I think so. [In a startup script similar to this one](https://gist.github.com/giuliano108/49ec5bd0a9339db98535bc793ceb5ab4#booting-the-guix-wsl-distro-as-if-it-were-a-guixsd-system), I set up `/run/current-system` and boot GuixSD. [Part of that boot process](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/build/activation.scm?id=0dc019e19a23fea614be5623360849ab9bc35e74#n284) involves copying certain binaries to `/run/setuid-programs`.

> enough to reproduce it on another distribution?

Not yet. If that would be helpful, I can try.

**Comment by NotTheDr01ds** [comment]
Ok, I think I understand a few things a bit better now.  Guix System looked interesting enough (perhaps "challenging enough" is a better description) for me to give it a try.  I never did get it *fully* booted properly, but I came pretty close following the same general process as you:

* Pulled `busybox:stable-musl` from Docker in an existing distro
* Ran it
* `docker export`'ed it
* `wsl --import busybox ...`
* Ran that distro
* Pull and install the `guix` package manager in that BusyBox distro.
* `guix system image -t docker-image <config.scm>` with a minimal configuration.  And yes, that's a pretty handy configuration option.
* Back in my main distro, `docker import`'ed it.
* Ran it
* `docker export`'ed
* `wsl --import` that image into a new `guix-minimal` distribution.
* Ran that distribution.

Whew!

But anyway, so yes, examining the *Docker* image, I can see that some of the setuid apps are in `/run/setuid-programs`.  And yes, this is going to be problematic for three reasons:

1. WSL's `init` mounts a *new* `/run` as a tmpfs into that directory.  This is what causes the existing apps there to "disappear".  The System Crafters gist wasn't quite clear on that - The comment there was that ...

    > Guix doesn't have a chance to populate /run at boot time.

    ... which isn't quite accurate.  Guix wouldn't normally populate `/run/setuid-programs` at boot, since it expects that the files are already on the filesystem, if I understand the order of operations correctly.

1. WSL mounts `/run` as `nosuid` (as you noted)
1. WSL mounts `/run` as `noexec`

> The error appeared after a kernel upgrade. I'd like to roll back to determine whether the mount options were different before but am not sure how.

To see if I could figure that out, I tested with:

* Windows 11 using the 5.10.102.1 kernel
* Windows 10 using the 4.19.104 kernel (using a `.wslconfig` file)

I tend to save *every* older kernel binary before upgrading so that I can rollback for testing if needed.

On *both* these systems, `/run` was mounted by WSL the same way.  Tmpfs, `noexec`, and `nosuid`.

So I'm not sure why the error appeared after a kernel upgrade for you.  It could have been a change in behavior in WSL itself.  I don't have anything older than Windows 10 21H2 to test on, but perhaps an older WSL version mounted this differently.  I definitely believe that it was mounted differently at *some* point in the past, otherwise the Gist wouldn't have worked for anyone.

There's really no "security" reason (IMHO) to mount them this way on WSL, given the lack of security/authentication in the first place.  If there was a WSL change, I'm guessing it was because some application somewhere checked the permissions and refused to run if security was too lax.

So possible workarounds:

* Unfortunately, there's no way that I can think of to prevent the `/run` mount on WSL's part.

* A remount should fix it:

    ```
    sudo mount -o remount,suid,exec /run
    ```

    You could add the guide equivalent to the [boot script](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/build/activation.scm?id=0dc019e19a23fea614be5623360849ab9bc35e74#n284) you mentioned.

* Alternatively, you could simply add a new Tmpfs mount for `/run/setuid-programs` that doesn't have the `nosuid,noexec` limitation in place:

    ```
    sudo mount -t tmpfs none /run/setuid-programs
    ```

    Again, I'm not sure what the Guile-equivalent is, but I would think that adding it immediately after the [`mkdir-p %setuid-directory`](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/build/activation.scm?id=0dc019e19a23fea614be5623360849ab9bc35e74#n306) would work.

**Comment by NotTheDr01ds** [comment]
Side note -- This might be better migrated to "Discussions".  Would you agree?

It doesn't seem like there's any WSL "issue" to change here, right?

If so, perhaps one of the Microsoft team can migrate it (if they happen to see it).

**Comment by jaccarmac** [comment]
Thanks for the investigation! I'll definitely look at setting that directory up under a different mount; Forgot you could nest filesystems like that.

The kernel upgrade might be a little bit of a red herring. I suspect this might have more to do with the WSL `init` binary, which AFAIK is opaque. I appreciate you taking a look at multiple Windows versions, as I'm not set up to do so.

> Side note -- This might be better migrated to "Discussions". Would you agree?

Yes.

> It doesn't seem like there's any WSL "issue" to change here, right?

Not unless there was a change to `init` behavior, which is something else we'll need a MS team member for, methinks.

**Comment by OneBlue** [comment]
Closing since NotTheDr01ds's answer is pretty complete
