### ISSUE TITLE
wsl -u root -- <command> should only run if running through privileged session or else prompt for sudo password

### ISSUE THREAD

**Issue by tusharsnn** [microsoft/WSL#8721]
### Version

Microsoft Windows [Version 10.0.22622.575]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-22.04

### Repro Steps

1) open terminal without **run as admin**
2) run `wsl -u root -- <command>` to run any arbitrary command as the root user

### Expected Behavior

The command should throw errors: "do not have enough permission to run this command".

### Actual Behavior

The command simply runs without any restriction and can run anything inside the user-distro.

![Screenshot (88)](https://user-images.githubusercontent.com/55626797/184498984-aadc446d-5345-4015-8045-c235ddc9a0d0.png)

**Comment by NotTheDr01ds** [comment]
So I have some concerns on the security of WSL around `wsl -u root`, but I'll be honest -- I can't convince myself whether they are real threats or not.

However, **requiring WSL to "Run as Admin" in order to run as root without a password would actually *weaken* security**, IMHO.  In general, you should *never* run WSL as a *Windows* Admin escalation (whether as WSL-root or otherwise) unless you are really sure you want it to be able to modify (practically) *anything* on your system.

As it stands, even the root WSL user is limited to the privileges of your *Windows* user account.  But if you "Run as Admin", then even the *default* WSL user has full access to Windows.

Examples:

In a normal, non-UAC elevated PowerShell:

```PowerShell
$ wsl touch /mnt/c/testfile.txt
touch: cannot touch '/mnt/c/testfile.txt': Permission denied

$ wsl -u root touch /mnt/c/testfile.txt
touch: cannot touch '/mnt/c/testfile.txt': Permission denied

$ New-Item -Path C:\testfile.txt
New-Item: Access to the path 'C:\testfile.txt' is denied.
```

Now start PowerShell as Administrator:

```PowerShell
$ wsl touch /mnt/c/testfile.txt
$ wsl ls /mnt/c/testfile.txt
/mnt/c/testfile.txt
$ wsl rm /mnt/c/testfile.txt

$ wsl -u root touch /mnt/c/testfile.txt
$ wsl ls /mnt/c/testfile.txt
/mnt/c/testfile.txt
$ wsl rm /mnt/c/testfile.txt
rm: remove write-protected regular empty file '/mnt/c/testfile.txt'?
# Only if using `metadata` option in `wsl.conf`, otherwise will be deleted without prompting
```

I won't repeat the PowerShell example in the admin session, because the results of that should be obvious.

The thing that should truly scare you is that `wsl rm` is able to delete a file from the root directory (or almost any other protected directory) when in an Admin session.

With that in mind, do you truly want a "security feature" of WSL to require running in an Admin session? ;-)

**Comment by tusharsnn** [comment]
Great explanation @NotTheDr01ds.  You made a good point that we shouldn't have to run wsl inside elevated terminal to run `wsl -u root`. Probably in this case we should really be prompted to enter sudo password to run this command instead. 
In my case, I was trying to automate a script on some network change event using task scheduler, I believe running in a privileged session would make it easier to run the script without being prompted for the UAC every time. 

I think there is two separate concern with wsl at this point, which is how to isolate one from the other as a security layer between windows and wsl. So, if my windows user account gets compromised, It should not be allowed to run root level commands on wsl. IMO windows admin should be allowed to run anything as a root user without any password prompts(user should know the complications). And if wsl detects the shell is not running in an elevated session then it should prompt for the sudo password(not UAC) before running the command.

Anyway I think the issue headline needs to be updated to: 
**wsl -u root -- \<command\> should only run if running through privileged session or else prompt for sudo password**

I am not a security expert and Idk how can running wsl -u root without password or UAC can be exploited in future but I do want to point out that I keep most of the project related stuff including keys and secrets within wsl only.

**Comment by OneBlue** [comment]
Indeed being root inside WSL is orthogonal to having administrator privileges on Windows, so this is the expected behavior. 

Closing.
