### ISSUE TITLE
Ubuntu Version Mismatch

### ISSUE THREAD

**Issue by muhammadsalmanafzal** [microsoft/WSL#8734]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 20.04.4

### Other Software

Microsoft Version: 22206.1401.6.0

### Repro Steps

Update Ubuntu (only Ubuntu) from Microsoft Store

### Expected Behavior

Ubuntu should upgrade from 20.04.4 to 22.04.1

### Actual Behavior

Ubuntu stays at 20.04.4

**Comment by NotTheDr01ds** [comment]
This is expected behavior.

*Short answer:*

To upgrade your existing (unversioned) "Ubuntu" from 20.04 to 22.04, you'll need to use the normal server/CLI Ubuntu upgrade process:

```
sudo do-release-upgrade -d
```

This will take some time.

Side-note:  You might need to uninstall snapd first.  I haven't tried recently, but most `do-release-upgrade`'s on WSL have an issue with the snapd package.  If you'd like to wait a bit before trying this, I can confirm on a test instance here, but it will probably be much later today or tomorrow before I have a definitive answer for you.

*Full explanation on why this is needed and how it really works:*

It's a bit confusing, but to copy/paste from my [Ask Ubuntu answer](https://askubuntu.com/q/1384209/1165986) on this topic:

The "automatic upgrade" part of the Store app is more than a bit confusing.  Yes, "Ubuntu" (without a version number) in the Store "automatically updates", but that probably doesn't mean what you think it means.  It took me a bit to get used to this concept myself.

This is a bit difficult to explain, but when you install "Ubuntu" (no version) from the Store, you actually have (at least) *three* different "installations":

* WSL itself, of course, as a prerequisite.  This is actually where the Linux kernel is installed, since it is shared between all installed WSL2 distributions/instances.

* An "app package" with a rootfs package (`install.tar.gz`) in `C:\Program Files\WindowsApps\CanonicalGroup...`.  You can see this by starting an Administrative PowerShell and running:
* 
    ```
    Get-ChildItem -Recurse 'C:\Program Files\WindowsApps\Canonical*' | Where-Object {$_.Name -eq 'install.tar.gz' }
    ```

* When run for the first time (via `ubuntu.exe`), the installer creates your actual WSL instance in your `%UserProfile%\AppData\Local\Packages\CanonicalGroup...`.

##### What does an "automatic upgrade" of the Store app really do?

When there's a new update of the app on the Store, the only thing that gets updated on your system is the rootfs package.  It does *not* change your installed *instance*.  It does *not* automatically update any of the packages in your *instance*.  It does not even update the WSL2 kernel.

You still need to run `sudo apt update && sudo apt upgrade -y` (or equivalent) to update the packages on a regular basis.  Note that this does not include the kernel -- See below for how to do that.

This is a good thing.  Otherwise, you'd be competing between the "Store" upgraded packages and those from the repo.

(Side note: Credit and thanks to u/zoredache on Reddit who [originally clarified this for me](https://www.reddit.com/r/bashonubuntuonwindows/comments/piqnvu/comment/hbzndfz/?utm_source=share&utm_medium=web2x&context=3).)

##### So what's the point?

Anyway, the upgrade of the Store package is pretty useless for most users unless you:

1.  Unregister the instance (which deletes all configuration) and re-configure it by re-running the `ubuntu.exe` command.  When going through that initial configuration, the rootfs is unpacked, so you would get the "latest and greatest" from the Store at that point.  However, note that Store releases are still fairly infrequent compared to package updates in the official repos.  Even immediately after installing from the Store, you'll still almost always get a number of updates through `apt`.

1.  Want to use that `install.tar.gz` to create a second WSL/Ubuntu instance (using `wsl --import`).  The newly created instance would then use the Store-updated rootfs.  Again, the same caveats apply about the repo packages as in the first scenario.

Neither of these scenarios is very common.  Even though the unversioned Store `Ubuntu` has now been updated to 22.04, it doesn't (and again, isn't expected to) change your *installed* instance of 20.04, just the rootfs *package*.

##### Upgrading the kernel

Note that neither the Store update nor `apt` (or other package methods) update the WSL2 kernel.  Since the kernel is part of WSL2 itself, and shared between all of the installed distributions, it's handled differently.  Use:

```
wsl --update
```

... to check for and download any WSL2 kernel update.  

That does assume that you are using the default kernel.  You do have the option of downloading or building your own kernel from the [WSL2 kernel source](https://github.com/microsoft/WSL2-Linux-Kernel).  It's been my experience that it can take a few days or weeks for the kernel update to become available via `wsl --update`, so if you want to grab the latest and greatest, you can.  Then configure WSL2 to use that kernel via [`.wslconfig`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig).

##### One more thing

All that said, the "Ubuntu" (unversioned) app still has one advantage, and that is that you won't need to worry about changing its name (like in that other question) when you eventually do upgrade to a later release.  The "Ubuntu 20.04" version is going to always have the instance name `Ubuntu-20.04`, even if and when you manually upgraded it to something later.

**Comment by NotTheDr01ds** [comment]
Just a heads-up that we apparently *don't* need to worry about the snapd package when upgrading from 20.04 to 22.04.

Upgrading from 20.04 to 21.10 would error out, IIRC, unless snapd was `apt remove`'d first, but the 22.04 upgrade seems to have fixed this problem.

**Comment by muhammadsalmanafzal** [comment]
Really great explanation. Kudos to you man! It did work. Appreciate it.

**Comment by NotTheDr01ds** [comment]
@muhammadsalmanafzal Great to hear!  And you're welcome!
