### ISSUE TITLE
WSL2/Ubuntu-20.04 accessing 64 threads out of available 128 (Threaddripper 3990x 64-Core)

### ISSUE THREAD

**Issue by oMuransky** [microsoft/WSL#8735]
### Version

Version 10.0.19042.1889

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

Installing WSL2/Ubuntu-20.04 on a machine with AMD Ryzen Threadripper 3990x 64-core processor. 

### Expected Behavior

When using 64-core processor I'm expecting to see all available 128 threads in WSL2/Ubunutu. 

### Actual Behavior

It seems that WSL2 has access only to 64 threads while the other 64 threads remain unused. Is there anything what can be done to address this issue? Sadly, as a result of this, running simulations on a 32-core machine which uses all its threads is faster than running the same job on 64-core machine which uses only half of its threads. I have tried to create .wslconfig file but it did not change the behavior.

![windows_threads](https://user-images.githubusercontent.com/28768162/185260790-a216a2a1-c484-4418-ae71-9d7bf7ffc067.png)
![wsl2_threads](https://user-images.githubusercontent.com/28768162/185260804-77d7fb32-bb5d-481a-b40b-7171be30a76a.PNG)

**Comment by Thernn88** [comment]
This is a longstanding issue on WSL with CPUs with a thread count above 64.

See https://github.com/microsoft/WSL/issues/5423

Also related is the fact that WSL doesn't detect the correct amounts of cache on many CPUs.

See my post https://github.com/microsoft/WSL/issues/8500

Developers have basically ignored these problems. At best we can tell these are Hypervisor bugs, thus in the view of WSL Devs responsibility for fixing the issue is on Windows Devs. Conversely, Windows devs feel it is a WSL issue and responsibility is on WSL devs for fixing it.

Don't expect any resolution soon.

It's a true shame as aside from the above issues and the BSOD on deletion of large files WSL2 would be a fantastic solution for university level bioinformatics.

**Comment by oMuransky** [comment]
Thanks for the info. That's indeed not ideal as we are also trying to run some cpu demanding research simulations so having half of the threads doing nothing is quite bad. I guess we will need to move away from WSL and use Ubuntu as an operating system on our workstations.

**Comment by Thernn88** [comment]
If your workload is CPU demanding and the work occupies the CPU it may not
scale well/at all with SMT.

Try turning off SMT in the bios and seeing if there is a difference in
runtime.

This will cause WSL to use all 64 physical cores.

Dunno if it will help with the cache but it might.

**Comment by oMuransky** [comment]
Thanks for the advice. Playing with BIOS on computers at work is sadly not an option. Let's see if Microsoft addresses this issue, if not then we just move to Ubuntu.

**Comment by donghyeon** [comment]
Is there any progress for this issue? It is very sad to give a rest to the half of cores of the $6500 CPU.
