### ISSUE TITLE
Unable to run Ubuntu after install

### ISSUE THREAD

**Issue by MichaelMc64** [microsoft/WSL#8739]
### Version

Microsoft Windows [Version 10.0.17763.3046]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

no

### Distro Version

Ubuntu 1804

### Other Software

Following directions at https://docs.microsoft.com/en-us/windows/wsl/install-on-server#install-wsl-on-previous-versions-of-windows-server, using Ubuntu 18.04.

After following all directions and attempting to run ubuntu.exe in the extracted folder, the following error appears: 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.

I also attempted to install Ubuntu 20.04, but the appx package does not include ubuntu.exe when unzipped.

Additional details: Get-appxPackage lists CanonicalGroupLimited.Ubuntu18.04onWindows, and appears to be installed.
Running WSL.exe by itself gives the following message:
Windows Subsystem for Linux has no installed distributions.

### Repro Steps

I followed the steps at https://docs.microsoft.com/en-us/windows/wsl/install-on-server#install-wsl-on-previous-versions-of-windows-server.

Installed Ubuntu 18.04 as per instructions.  Running ubuntu.exe from the unzipped package gives the error: .
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.

Get-appxpackage shows CanonicalGroupLimited.Ubuntu18.04onWindows installed.
Running WSL.exe gives the message: 
Windows Subsystem for Linux has no installed distributions.

Logs included below.

### Expected Behavior

Ubuntu WSL should be installed and should launch.

### Actual Behavior

Ubuntu does not run, WSL does not recognize the appx package as installed.

### Diagnostic Logs

[WslLogs-2022-08-18_16-28-41.zip](https://github.com/microsoft/WSL/files/9377777/WslLogs-2022-08-18_16-28-41.zip)

**Comment by diddledani** [comment]
I bashed on this with WSL2, but it's the same cause. I have filed a related issue in the WSL Docs repo: https://github.com/MicrosoftDocs/WSL/issues/1604

**Comment by diddledani** [comment]
Specifically the issue is that with Windows Server installed without the desktop experience you cannot install `appx` packages. You can therefore only use a rootfs `.tar.gz` with `wsl --import`. You can acquire the Ubuntu tarball by either of these means:

- Navigate to https://cloud-images.ubuntu.com/jammy/current/ (replace jammy with the Ubuntu codename of the release of Ubuntu you desire) and download the file suffixed with `-amd64-wsl.rootfs.tar.gz` (or `-arm64-wsl.rootfs.tar.gz` if your system is arm-based)
- Rename the `.appx` suffix on the Store package file to `.zip` and then run `Expand-Archive package-name.zip` where `package-name.zip` is the actual name for your renamed file, and do the same with the `.appx` file inside the extracted directory with the suffix appropriate for your system's architecture. The `.tar.gz` should be within that second package's extracted directory
