### ISSUE TITLE
WSL not update e not recognized 

### ISSUE THREAD

**Issue by MaikoDeizepi** [microsoft/WSL#8790]
### Version

Microsoft Windows [Version 10.0.19044.1889]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

i'm not make update in wsl and cannot apply comands of wsl.

PS C:\WINDOWS\system32> wsl --install -d Ubuntu-20.04
Ubuntu 20.04 LTS is already installed.
Launching Ubuntu 20.04 LTS...
PS C:\WINDOWS\system32> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\WINDOWS\system32>

### Expected Behavior

I want it to work the same https://docs.microsoft.com/pt-br/windows/wsl/basic-commands#install-a-specific-linux-distribution

### Actual Behavior

not recognized wsl and not update for version 2

### Diagnostic Logs

PS C:\WINDOWS\system32> wsl --install -d Ubuntu-20.04
Ubuntu 20.04 LTS is already installed.
Launching Ubuntu 20.04 LTS...
PS C:\WINDOWS\system32> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\WINDOWS\system32>

**Comment by NotTheDr01ds** [comment]
Did you perhaps run `wsl --install -d Ubuntu-20.04` under an Administrator (or different) account?

I would try:

* Checking *Add or Remove Programs* to see if Ubuntu shows installed there.  If so, uninstall it.  I'm assuming that you have no data inside Ubuntu, since it sounds like you haven't been able to launch it yet, right?
* Once uninstalled, reboot
* Open PowerShell, as your regular user (not an administrator account) and try `wsl --install -d Ubuntu-20.04` again.

Note that your issue above says that the Distro version is 22.04, but then talk about 20.04.  Do you have *both* installed?  This is okay, I just want to make sure readers of the issue have a clear picture what you're working with.
