### ISSUE TITLE
Wsl/Service/CreateInstance/CreateVm/HCS_E_SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by KiaWeb** [microsoft/WSL#8793]
### Version

Microsoft Windows [Version 10.0.22621.590]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5

### Distro Version

Kali Linux Rolling

### Repro Steps

Enable WSL and try to run wsl.exe with no arguments in the Command Prompt

### Expected Behavior

Running the Kali Linux App on Microsoft Store should work and/or wsl.exe should work

### Actual Behavior

The operation could not be started because a required feature is not installed.
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_SERVICE_NOT_AVAILABLE

**Comment by SFizAlthaf** [comment]
Any update on this? I'm facing the same issue

**Comment by normanpoh** [comment]
I get the same code but this happens when I issued the following command, trying to change my Ubuntu-22.04 to use wsl2 instead of the default 1.

`PS C:\WINDOWS\system32> wsl --set-version Ubuntu-22.04 2`
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
The operation could not be started because a required feature is not installed.
Error code: Wsl/Service/CreateVm/HCS_E_SERVICE_NOT_AVAILABLE

**Comment by Biswa96** [comment]
Make sure virtualization is on in bios or uefi settings. And the following command in admin command prompt shows the 'auto' result.

```
> bcdedit | find /i "hypervisor"
hypervisorlaunchtype    Auto
```

**Comment by wzhy920127** [comment]
Same problem
```> wsl --version
WSL 版本： 1.0.3.0
内核版本： 5.15.79.1
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.963
```

**Comment by wzhy920127** [comment]
> 同样的问题
> 
> ```
> >>> wsl --version
> WSL 版本： 1.0.3.0
> 内核版本： 5.15.79.1
> WSLg 版本： 1.0.47
> MSRDC 版本： 1.2.3575
> Direct3D 版本： 1.606.4
> DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows版本： 10.0.22621.963
> ```

Check whether the hyper-v function is enabled
![Snipaste_2022-12-28_11-16-32](https://user-images.githubusercontent.com/21121892/209752331-6d587bb5-8ed6-4cbf-b2c4-b0b011360a84.png)

**Comment by okibcn** [comment]
I just got the same issue after upgrading from WSL 1.1.3 to 1.1.5. I never needed Hyper-V feature for running WSL2. Is this a new requirement?

**Comment by okibcn** [comment]
For some reason, `Virtual Machine Platform` feature was deactivated in my Windows 11 Canary preview. As before Hyper-V is not required for WSl2 to work. The only required feature is the mentioned Virtual Machine Platform. It worked again after re-activating that feature.

**Comment by yannDuchateau** [comment]
hello, tried everything untill... 👍 

C:\Windows\System32>wsl --install -d kali-linux
Downloading: Kali Linux Rolling
Installing: Kali Linux Rolling
The operation could not be started because a required feature is not installed.
Error code: Wsl/InstallDistro/Service/RegisterDistro/CreateVm/HCS/HCS_E_SERVICE_NOT_AVAILABLE

C:\Windows\System32>DISM /Online /Enable-Feature /FeatureName:Containers /NoRestart

Deployment Image Servicing and Management tool
Version: 10.0.26100.5074

Image Version: 10.0.26100.6725

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.

C:\Windows\System32>DISM /Online /Enable-Feature /FeatureName:Containers-DisposableClientVM /NoRestart

Deployment Image Servicing and Management tool
Version: 10.0.26100.5074

Image Version: 10.0.26100.6725

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.

C:\Windows\System32>DISM /online /enable-feature /featurename:"VirtualMachinePlatform" /NoRestart

Deployment Image Servicing and Management tool
Version: 10.0.26100.5074

Image Version: 10.0.26100.6725

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.

C:\Windows\System32>DISM /Online /Enable-Feature /FeatureName:HypervisorPlatform /NoRestart

Deployment Image Servicing and Management tool
Version: 10.0.26100.5074

Image Version: 10.0.26100.6725

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.

C:\Windows\System32>wsl --install -d kali-linux
Downloading: Kali Linux Rolling
Installing: Kali Linux Rolling
Distribution successfully installed. It can be launched via 'wsl.exe -d kali-linux'
Launching kali-linux...
Waiting for systemd to start...
