### ISSUE TITLE
WSL failed to open GUI when calling from `C:\WINDOWS\system32\wsl.exe`

### ISSUE THREAD

**Issue by LykorisR** [microsoft/WSL#8818]
### Version

Microsoft Windows [版本 10.0.22622.590]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-18.04

### Other Software

WSLg 1.0.42

### Repro Steps

1. Setup WSLg as instructed
2. Make sure GUI program can be run on WSL, such as `gedit`
3. Run command in cmd like `C:\WINDOWS\system32\wsl.exe --distribution Ubuntu-18.04 --exec /bin/bash -c "gedit"`
4. It would give errors like
```
Unable to init server: Could not connect: Connection refused

(gedit:1000): Gtk-WARNING **: 17:00:47.119: cannot open display:
```

### Expected Behavior

GUI programs run as expected

### Actual Behavior

error
```
Unable to init server: Could not connect: Connection refused

(gedit:1000): Gtk-WARNING **: 17:00:47.119: cannot open display:
```

**Comment by NotTheDr01ds** [comment]
There might be a few possible causes for this, depending on the WSL version you are using (Preview or not).  Can you update the issue with the output of:

```
wsl --status
```

**Comment by LykorisR** [comment]
output for `wsl --status` as below
```
默认分发: Ubuntu-18.04
默认版本: 2
WSL 版本： 0.66.2.0
内核版本： 5.15.57.1
WSLg 版本： 1.0.42
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22622.590
```

**Comment by NotTheDr01ds** [comment]
I'm not sure, but I think this may be related to a problem I'm seeing on 0.66.2 as well.  However, I can't reproduce it the way you describe, so it may not be the same.

In my case, the X11 socket is being recreated (and the display number incremented), but the `DISPLAY` variable isn't updating.

Does `ls /tmp/.X11-unix` show anything other than `X0` when the problem occurs?  If so, then it may be caused by the "system-distro sharing" update mentioned in [this comment on the WSLg issue](https://github.com/microsoft/wslg/issues/820#issuecomment-1241119951).

**Comment by LykorisR** [comment]
`ls /tmp/.X11-unix` only shows X0
actually, when I tried it just now, it worked again.
So for anyone who experience the same issue or have just manually fixed WSLg, do remember to full restart windows
**Just restarting WSL won't work**

**Comment by AoMYgod** [comment]
It seems insufficient on my laptop.
PS C:\Windows\system32> wsl --status
默认分发：Ubuntu
默认版本：2

适用于 Linux 的 Windows 子系统最后更新于 2024/4/11
WSL 自动更新启用。

内核版本： 5.10.102.1
