### ISSUE TITLE
Long-term goal idea: DRM support

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#882]
It seems to me that writing a kernel-mode interface for DRM drivers could actually be done.  I haven't developed drivers for Windows, but companies like Intel, AMD, and NVidia do.  They also happen to write drivers for linux.  It would be interesting to see if MS added a documented interface for DRM within Windows Subsystem for Linux as well as a way for Graphics Driver writers to add an extension to expose their devices through the kernel to the Linux side for DRM.

The idea would be something like:

The Windows Kernel checks if it has a display driver that has an extension for WSL DRM (which would be left up to the driver writers).  If yes, it exposes a DRM interface to WSL X/Wayland clients, and it allows the gfx driver writers to handle how this DMA data works.  If no, it defaults to Indirect rendering.  Microsoft could provide maybe a reference implementation for, say, the default Hyper-V video driver in Windows 10's Hyper-V.

The reason why this could work is as follows: DRM may internally call kernel-mode drivers, but DRM actually has a usermode-kernelmode interface.  The interesting thing is that the kernel-mode drivers themselves could just be actual Windows drivers with a feature flag set or extension enabled. 

So, devs, even if this isn't high on the list now, does something like this sound feasible, especially if you added it to the next, say, DirectX specification (which would encourage MS's partners in the graphics device driver area to write drivers that are also accessible within WSL and can understand DRM calls from WSL programs)?

**Comment by benpye** [comment]
X uses GLX for OpenGL rendering, if the efficiency of passing data between the WSL environment and Windows could be improved I don't think that you'd even need driver involvement. Zero copy IPC does exist between WSL and the Windows host (some details at https://github.com/ionescu007/lxss ). I'm pretty sure Astoria had OpenGL support too, and that was based on the same code!

I'm not even sure if this would require MSFT involvement, using the zero copy IPC, you could possibly do it by modifying the binaries within WSL to be aware of functionality, and then a modified X server on the Windows side that could use the same APIs to provide the GL functionality, rather than using indirect GL and doing it over the network, which is slow.

**Comment by fpqc** [comment]
The problem is that DRM requires DMA, which is much faster than IPC/sockets.  I think in order to get it to work right with DMA (and without rewriting your X/Wayland clients, you would need to have NT drivers that were directly aware of WSL.

**Comment by benpye** [comment]
Hm, my point is you wouldn't need to copy any data. I admit it would still be slower, but I wonder if it would be acceptable. It would certainly be faster than anything we have now. I am curious what MS did for Astoria.

**Comment by therealkenc** [comment]
Yeah, and the IPC is surprisingly beside the point In Real Life. This is why [angrybots](https://webassembly.github.io/demo/) works so shockingly well. That some texture map had to be copied out of a javascript ArrayBuffer by the v8 engine is lost in the noise. [VirtualGL](http://www.virtualgl.org/) is also an interesting approach. I am surprised no one has brought it up before.

Any any rate, someone sooner or later is going to have to address the Elephant in the room: Shared memory between WSL and NT space. I've been waiting for all the obvious low hanging syscall surface to clear before bringing that up.

**Comment by benpye** [comment]
Alex Ionescu has detailed WSL/NT shared memory ( https://github.com/ionescu007/lxss/blob/master/The%20Linux%20kernel%20hidden%20inside%20windows%2010.pdf ), looks like it's possible at this point, but I don't know if it's used anywhere. Hence why I don't think this would actually need MS involvement, though of course private APIs could easily break! It would be really great if they at least documented the APIs that are available, for example LxssManager in 14901 provides a "lxssmanager\createprocess" adss bus service, which should be able to create an NT service, but this nor the struct layout for the message is documented!

**Comment by fpqc** [comment]
@benpye @benhillis already stated they would likely start to document that interface once the interface was stable, iirc.  Also, if you look at Alex Ionescu's presentation, he thanks Deepu Thomas himself for help with various questions on the last page, so I think it is unlikely that this interface is undocumented because it will later be "hidden"

**Comment by therealkenc** [comment]
Fascinating slides; only released Aug 5th (8th) I guess. So what we need now is `libwsl-ipc.deb` and `libwsl-ipc-dev.deb` that wraps up epoll on the message port fd all pretty. With that in the toolbox you can implement just about anything. Like literally anything. Documentation is the man(7) page for the package.

**Comment by fpqc** [comment]
@therealkenc I hope maybe he will put his blackhat presentation up on youtube soon (since blackhat takes a while to do it, it seems)

**Comment by therealkenc** [comment]
You do realize this means it's possible to have a `lxshelld` (on WSL) and `lxshell` (on Windows) now, right? I'm looking into what it will take to hammer the PuTTY terminal emulator [source](http://tartarus.org/~simon-git/gitweb/?p=putty.git) into submission right now.

**Comment by fpqc** [comment]
@therealkenc So, does that mean running CMD, Powershell, bash, zsh, etc through PuTTY instead of conhost?

**Comment by therealkenc** [comment]
I was just talking about PuTTY's terminal emulator code. I don't even know if PuTTY is is the best starting point. Think of it like an `urxvtd/urxvtc` analogy without having to install VcXsrv. The `d` side sits in WSL. The `c` side is a Windows app. The only thing missing before was a transport between the two domains other than inet sockets. So, `bash.exe` without conhost, basically. A `lxshell` is arguably even not all that useful, really. It just console window with different terminal emulation characteristics than `bash.exe`. 

All entirely hypothetical, of course.

**Comment by fpqc** [comment]
@therealkenc I am not sure, but I could have sworn that Mr. Ionescu's lxserver and lxclient allowed launching Windows-side programs from the linux side, kind of like a version of @xilun 's cbwin that uses the undocumented COM interface instead of TCP.

**Comment by fpqc** [comment]
@therealkenc Oh, I get it.  I thought you were talking about lxclient and lxserver in @ionescu007's repo.  You are talking about running a daemon on WSL (hidden or not) but where the client runs natively on Windows instead.  That's a cool idea, since it menas you could run this lxss daemon on boot, like people want with the sshd but connect new bash sessions directly from Windows through PuTTY.

**Comment by therealkenc** [comment]
_Everything_ on WSL is hidden. There is no `/dev/fb0` on WSL. Even `urxvtc` (the client) is hidden as far as WSL is concerned - it is a program that knows how to read and write to ptys and sockets. Yep it'd be launched with a hypothetical lxlaunch.dll or however this shakes out officially.

**Comment by fpqc** [comment]
@therealkenc I guess I somehow missed this: http://www.phoronix.com/scan.php?page=news_item&px=Windows-DRI-Xorg-Server-1.19

The Cygwin port of X1.19 now supports DRI. It looks like someone has already written the usermode compat layer, and it might be relatively straightforward to port to WSL, since it is already meant to work on Windows.  I'm not sure exactly how it works, but this could potentially be as easy as Microsoft making the Win32 API that this uses available to WSL?  Would it be a problem to try to build the Windows version on Linux, but like.. don't cross-compile?

**Comment by therealkenc** [comment]
@fpqc Appreciate the heads up. I follow phoronix now and then but missed that post. I'll try it out. Last time I looked (which was a long time ago and not particularly rigorously) VcXsrv was better behaved than Cygwin/X for the stuff I was playing with. Maybe it's the new go-to now. 

You can't "port" (per se) the new mesa to WSL because, while Cygwin can talk to Windows, WSL cannot except though the exit doors (ip, DriveFS, and lxbus). I haven't looked at the [patch](https://cgit.freedesktop.org/mesa/mesa/commit/?id=533b3530c1292a39ea12437d1376c77bc7e584b9&utm_source=anzwix) cited yet because cgit.freedesktop.org seems to be having issues for me right now. But if the mesa guy's accepted it, it must be at a pretty low level in the GPU stack. So yes this is probably _very_ helpful, but the usermode "Win32 API" you are talking about is still memory maps and ioctls to a device WSL doesn't have. Creating that device on WSL probably just got a lot saner though. And (preemptively) yes, you could almost certainly do said device with ionescu's stuff. I am mildly surprised no one has done more exploration there past returning '42', though perhaps people have and it's just on their hard drives and not github. Or people are just waiting for Microsoft to publish official "here's how you use it" documentation first (which is mostly the camp I've been in).

**Comment by fpqc** [comment]
@therealkenc Thanks for taking a look; just wanted to know, since I'll try pinging @benhillis to let him know that it looks like there might be a sane generic Windows-compatible POSIX version of mesa-libgl.  If Microsoft knows what usermode is doing in this case, maybe they can make the appropriate kernelmode stuff available with much less effort (instead of having to use the Linux mesa's ioctls, they can use ones they already control as part of the Windows graphics stack)

**Comment by therealkenc** [comment]
Sure; just appreciate that Ben&company are pretty on top of what _would_ be necessary to do opengl (or 100 other things) on WSL.

I should probably also take back the hasty _you could almost certainly do said device with ionescu's stuff_ I said earlier. Ben [mentioned](https://github.com/Microsoft/BashOnWindows/issues/1470#issuecomment-265781431) that even if you can map memory there's no synchronization mechanism, and that's probably  (almost certainly?) needed for the mesa "port" too.

And anyway, even if doing `/dev/windri` was easy (for some value of easy), doing `/dev/fb0` (#230) (let alone `/dev/input/*`) is _even easier_ and they've eschewed doing that, because much of the low hanging fruit I mentioned in August is still on the tree. They're [laser-focused](https://github.com/Microsoft/BashOnWindows/issues/1129#issuecomment-250019657) on supporting mainline developer tools, technologies, languages. It's still too early to get excited here, even if it's a nice development.

**Comment by fpqc** [comment]
@therealkenc He did say though that they did actually have a working /dev/framebuffer when WSL was still called Astoria and targeting android.

**Comment by therealkenc** [comment]
I finally looked at the [source](https://github.com/mesa3d/mesa/blob/e66a2b879b73bf48800fec7353dafe8fc693ecdb/src/glx/windows/windowsgl.c) on github mirror. It isn't as helpful (ie low level) as I assumed; and in hindsight the assumption was pretty optimistic. Unfortunately a WGL shim doesn't make things easier for WSL. That's the wrong layer. So another strike-though above, and now I have to apologize for getting your hopes up. Maybe a consolation prize if Cygwin/X got better though.

**Comment by fpqc** [comment]
Oh well!

**Comment by benhillis** [comment]
@therealkenc, @fpqc - This is great information.  Currently graphics is lower on our priority list as we're still focusing on our syscall translation compatibility. However I think soon we will start looking more closely at device support.

A little historical context on how graphics worked back in project Astoria.  At a high level we were doing something similar to what the Android emulator does for graphics.  Sending OpenGL commands from inside a WSL instance over to NT usermode.  This included logic for sharing memory regions (for example textures) and a cross-os synchronization mechanism.

I see a couple possible options for supporting graphics in WSL.
1. Implement whatever kernel surface area is required (or come up with some kind of extensible device framework so others can do so).
2. Something similar to what I described above where WSL usermode is talking to a NT usermode proxy that does graphics for them. Similar to an X11 server.

**Comment by fpqc** [comment]
@benhillis It seems like 2 might be easier to implement, but I guess I don't know how much of the logic of Linux's DRM subsystem is easy to replicate in the Windows driver stack.  Because the libgl on Linux is already implementation-agnostic (everything goes through one of a few providers of libgl), maybe it would be easier to have it work through an NT proxy like you described.  

At least, that seems a lot more reasonable than trying to reverse-engineer and reimplement a kernel surface that is almost entirely driven by pretty horrible ioctls rather than proper syscalls.  Even Linus Torvalds commented recently (in the recent Bus-1 RFC on lkml) on how painful it is for them to maintain interfaces implemented in ioctls.

**Comment by therealkenc** [comment]
There are no plans for a DRM shim (that I know of) as of this writing, and this one has long since run course.

**Comment by bakeiro** [comment]
Hi!

sorry for reopening, just a quick doubt, I'm trying to run a program which uses `drmGetDevices2()`, this seems to interact with the graphic server, also I assume this is part of the DRM (since the function name starts with DRM)

the point: this fails in my WSL, but since this issue was from the 2016, and now do we have graphic apps running on WSL (windows 11 came with WSLg support) did something change so far? (related with DRM)
