### ISSUE TITLE
Can't launch wsl after the update

### ISSUE THREAD

**Issue by shanghaox** [microsoft/WSL#8859]
### Version

Microsoft Windows [版本 10.0.22621.521]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Ubuntu(default)

### Repro Steps

1.wsl --update
2.wsl.exe(then the error happens)

### Expected Behavior

>>wsl.exe
(enter the linux bash)

### Actual Behavior

>>wsl.exe
can not find VmSwitch 'ex'。
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/WSL_E_VMSWITCH_NOT_FOUND

**Comment by hugorosario** [comment]
This issue was driving me nuts after upgrading WSL to 1.0.0 via "wsl --update".

I was having the error :
`O VmSwitch 'Bridge' não foi encontrado.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/WSL_E_VMSWITCH_NOT_FOUND`

Google brought me here without a solution, which is quite easy.

For anyone that find their way here, just go into the Hyper-V manager and create the missing internal switch with the same name specified in the error or run the command with admin privileges:

`New-VMSwitch -Name "Bridge" -SwitchType "Internal"`
