### ISSUE TITLE
Why there are two choices of Ubuntu using WSL2 with windows terminal?

### ISSUE THREAD

**Issue by Hao4977** [microsoft/WSL#8901]
![screenshot](https://user-images.githubusercontent.com/69423227/192484141-90350f87-d4a2-4fcf-8ed8-ba3b1ccfea64.png)
Why there are two choices of Ubuntu and what is the difference? I'm a newcomer to WSL. I'd appreciate it if you could answer this issue. THANKS!

**Comment by NotTheDr01ds** [comment]
This seems to be a bit of a bug (or just timing issue) in the Ubuntu installer, but it seems to be on the Canonical end from my research -- Not a WSL issue, although there may be an additional Windows Terminal bug in play.

The "Ubuntu" with the Penguin icon is created by Windows Terminal as part of the WSL provider.  Terminal will automatically detect all installed WSL distributions and create a profile for each.

The second one, with the Ubuntu icon, is created by a [JSON Fragment Extension](https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions) in the Ubuntu package.

What is *supposed* to happen is that the JSON Fragment Extension is supposed to *hide* the auto-generated one.  But for some reason, the GUID is wrong in the JSON.

It's possible (even likely) to end up in a situation where you can't even hide (or delete) the second one, since it will always be regenerated on restart.  This is due to a "corrupt" (bad state) `state.json` for Windows Terminal.

The easiest way to recover is to delete both `settings.json` and `state.json` from `%userprofile%\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`.  Of course, this means that you'll need to recreate any Terminal settings you've changed.

It's also possible to manually set the GUID in `state.json` if you know how, but I haven't gone through that process myself to document it.  If you need more information on what's going on here, see my answers on these two Super User questions:

* [Can't delete or hide duplicate Ubuntu Profile in Windows Terminal](https://superuser.com/q/1737991/1210833)
* [Different profiles of the same WSL2 linux instance in Windows Terminal](https://superuser.com/q/1737942/1210833)

**Comment by benhillis** [comment]
The Windows Terminal GitHub is probably a better place for this question. They auto-create these.

**Comment by jitvimol** [comment]
![image](https://github.com/user-attachments/assets/fbc052d6-0007-4478-8dd8-23c5a4a4e80e)

note: you can choose to hide profile from dropdown here.
