### ISSUE TITLE
`systemd` doesn't mount `/` as shared

### ISSUE THREAD

**Issue by mangkoran** [microsoft/WSL#8922]
### Version

Windows version: 10.0.22621.521

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1-microsoft-standard-WSL2

### Distro Version

ArchWSL

### Other Software

```
WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

podman 4.2.1-1
systemd 251.4-1
buildah 1.27.2-1
```

### Repro Steps

0. Install/upgrade WSL 0.67.6
1. Enable `systemd` support [[1](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support)]
2. Restart your distro; shutdown first `wsl --shutdown`,
3. then run it back `wsl`
4. Run `podman images`

### Expected Behavior

Podman run without warning and error.

### Actual Behavior

Podman print a warning regarding shared mount.
```sh
❯ podman images
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
```

### Diagnostic Logs

This has been an [issue](https://github.com/microsoft/WSL/issues/7477) for a while. However, back then there is still no native WSL's `systemd` support. The introduction of native `systemd` support made me revisit this issue, and found that it is still persist.

Current workaround is by using WSL's boot command in `wsl.conf`. [[1](https://github.com/microsoft/WSL/issues/7477#issuecomment-1031102105)]

**Comment by cerebrate** [comment]
Yep, looking at the current code (the link in the discussion points to an older release), the root filesystem _should_ be automatically remounted as shared by _systemd_, but it isn't because _systemd_ is running in container mode. See here:

https://cgit.freedesktop.org/systemd/systemd/tree/src/core/mount-setup.c#n383

(Since this is the same root cause as #8840 , it might be worth asking if systemd _needs_ to run in container mode under WSL? To the best of my knowledge, none of the pre-native-support systemd hacks used container mode, and _systemd-detect-virt_ still picked up that it was running under WSL just fine.)

**Comment by cerebrate** [comment]
Well, guess I didn't need to rush that fix into bottle-imp 0.8 after all...

😀

**Comment by wizpresso-steve-cy-fan** [comment]
This is a pretty annoying issue, as if you run Kubernetes with root mount propagation (for example Prometheus root exporter), it will not work out of the box. Same goes for Nvidia GPU Operator which some of the driver installer required host path mount to detect existing Nvidia drivers.

**Comment by mangkoran** [comment]
Any update regarding this ticket?

**Comment by zwn** [comment]
I am on opensuse leap 15.5 and I am also experiencing this issue.

**Comment by mangkoran** [comment]
Revisited this issue as it still persists in WSL 2.0.9
