### ISSUE TITLE
Umlauts not working

### ISSUE THREAD

**Issue by lanthaler** [Microsoft/WSL#895]
I installed the bash on the anniversary update. I have a German Windows and a German keyboard. I can enter special characters that require Alt Gr (such as [ or }, see #11) but I can't enter any umlauts (äöü).

I commented on #11 about the problem but probably nobody will look at it as the issue has been closed.

**Comment by rodrymbo** [comment]
I just tried Alt+0228 on my US keyboard and got `ä` while in a terminal session connecting to WSL via ssh (PuTTY). I tried the same keystroke in the console one gets with bash.exe, and nothing happened. Maybe PuTTY and ssh can be a workaround until the console is fixed?

**Comment by hbrgnr** [comment]
@lanthaler I have a German keyboard and German Windows too, but I can type and see all the umlauts properly. I don't need putty or anything. Have you tried checking whether your bash uses German layout too ([see this Stack Overflow post](http://askubuntu.com/questions/434849/change-keyboard-layout-english-uk-on-command-line-to-english-us))?

I'm on build 14393.10, Win 10 Pro

**Comment by lanthaler** [comment]
I tried to install console-common, didn't work.

Btw. not only entering umlauts doesn't work, also the output fails. Instead of a `benötigt` for instance, it *renders* something like `ben├Âtigt`. I highlighted renders because when I copy and paste it somewhere else it actually turns into an `ö`

**Comment by miniksa** [comment]
This is still UTF-8. We're working on it.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. We are actively working to improve Console's ability to support UNICODE and UTF-8. Bear with us while we complete this work
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
