### ISSUE TITLE
WSL2 upgrade problem

### ISSUE THREAD

**Issue by asdw159632** [microsoft/WSL#9093]
when I'm upgrading WSL1 to WSL2. I find it takes a very long time and still in the stage "it will take few minutes". Then I take a look at the ext4.vhdx file. the size of vhdx is only few MB and not change for a long time. could you help me ?

**Comment by NotTheDr01ds** [comment]
Try `wsl --export`ing the original WSL1 distribution.  If that works, then try `wsl --import`ing that into a new WSL2 version (use the `--version 2` flag).

You may run into the same problem with it stalling out, but that will be useful information if so.  Not sure that I have a solution for you (at least myself) in either case, though.

Just out of curiosity, is there a chance you might have accessed WSL1 files using the [AppData path](https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/) at some point in the past?  I've had a related problem (in the distant past), and, in retrospect, it *may* have been because of filesystem corruption due to me modifying the WSL1 files directly in Windows (well before it was announced that it could cause issues).

**Comment by pmartincic** [comment]
Could you pretty please acquire some logs?

/logs

**Comment by asdw159632** [comment]
>

**Comment by asdw159632** [comment]
> Try `wsl --export`ing the original WSL1 distribution. If that works, then try `wsl --import`ing that into a new WSL2 version (use the `--version 2` flag).
> 
> You may run into the same problem with it stalling out, but that will be useful information if so. Not sure that I have a solution for you (at least myself) in either case, though.
> 
> Just out of curiosity, is there a chance you might have accessed WSL1 files using the [AppData path](https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/) at some point in the past? I've had a related problem (in the distant past), and, in retrospect, it _may_ have been because of filesystem corruption due to me modifying the WSL1 files directly in Windows (well before it was announced that it could cause issues).

Thank you for your advice. I exported the wsl1 and I noticed that I need to unregedit it, so I tried upgrade again before unregedit. This time it upgraded successfully. 
Though I don't know why. It might have something related with my moving of wsl1.
Anyway, thank you for your help!

**Comment by asdw159632** [comment]
> Could you pretty please acquire some logs?
> 
> /logs



> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

[](https://github.com/asdw159632/wsl-logs.git)
I upload the logs here. And I successfuly upgraded it. Though I still do not why.
Thank you for your help. If there is nothing need to notice, you may not reply me, and I will close this issue this weekend.
