### ISSUE TITLE
internal error, please report: running "SNAP" failed: cannot find installed snap "SNAP" at revision "xxxx": missing file /snap/SNAP/xxxx/meta/snap.yaml 

### ISSUE THREAD

**Issue by edurojasr** [microsoft/WSL#9097]
### Version

Microsoft Windows [Version 10.0.22621.755]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.68.1-microsoft-standard-WSL2 

### Distro Version

Ubuntu-22.04

### Repro Steps

1. Enable systemd support with `sudo nano /etc/wsl.conf` and add `[boot] systemd=true`.
2. restart wsl
3. check `snap list` its working
4. `sudo snap refresh` is working and updates installed snaps
5. install any snap like `sudo snap install firefox`
6. open `firefox`
7. error shows.

### Expected Behavior

That the snap app opens or works as intended

### Actual Behavior

running any installed snap shows "internal error, please report: running "SNAP" failed: cannot find installed snap "SNAP" at revision "xxxx": missing file /snap/SNAP/xxxx/meta/snap.yaml "

Some screenshots for reference.

![image](https://user-images.githubusercontent.com/35645729/199260229-f36f5e7c-c95e-4d3c-927b-2be07c02b4fd.png)

As you can see, the /snap/openjdk folder is there so the snap is mounted.

![image](https://user-images.githubusercontent.com/35645729/199260304-c1ca1fd3-4115-452c-a2d8-2297e5886f06.png)

But, when try to navigate to the snap meta folder in the WSL2 Ubuntu the command ls -l didn't show any file or folder, but if I open with explorer.exe . I can see all the folders there an the meta folder with the snap.yaml file. This happens with any snap.

I uninstalled and installed multiple times all WSL2 and Ubuntu infrastructure but didn't work.

Thanks for the help.

Duplicate in [Ubuntu WSL github #318](https://github.com/ubuntu/WSL/issues/318) since I don't know where to report this.

**Comment by edurojasr** [comment]
Just for completeness. I finally figured out what's was my problem. Running the Windows Terminal on Admin level makes this issue happen.

Fix it by running the terminal in a regular way non-admin.

**Comment by lkyu-ly** [comment]
> Just for completeness. I finally figured out what's was my problem. Running the Windows Terminal on Admin level makes this issue happen.
> 
> Fix it by running the terminal in a regular way non-admin.

This problem still exists till today. I successfully run hello-world just following your solution.
And I explored more: I found that if I access WSL2's file system in Windows Explorer, I can see /snap and all it's components. However   if I run a privileged shell to interact with WSL and snap, I can't see any file under the version folder(including the missing snap.yaml) either in shell command such as `ls` or in gui file explorer such as `dolphin`.
This issue is mostly only happened in WSL as I barely find similar problem for native linux.
Hope that this issue could be fixed soon.
