### ISSUE TITLE
WSL console hangs over four minutes to start

### ISSUE THREAD

**Issue by sage393** [microsoft/WSL#9111]
### Version

Microsoft Windows [Versión 10.0.19044.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-22.04

### Repro Steps

Open up a PowerShell terminal and type wsl and press enter

### Expected Behavior

It should take a few seconds to launch the bash terminal

### Actual Behavior

It takes almost 4 or 5 minutes to launch the bash terminal

**Comment by NotTheDr01ds** [comment]
Any difference in startup time with if you use:

```
wsl ~ -e bash --noprofile --norc
# or
wsl ~ -u root
```

Also, does opening a second terminal complete any faster or does it still open slowly?

**Comment by sage393** [comment]
@NotTheDr01ds A big difference, I think it's zsh the one who makes slow the startup, probably before install nodejs but I don't know why

**Comment by NotTheDr01ds** [comment]
@sage393

> I think it's zsh the one who makes slow the startup

Ah, I thought you were using Bash based on ...

> It takes almost 4 or 5 minutes to launch the bash terminal

You can try the same thing, I believe with:

```
wsl ~ -e zsh --no-rcs
```

That would point to a problem somewhere in your startup config files, most likely `~/.zshrc`.  Something in there is hanging for a bit.  You can try debugging that (or the equivalent Bash files such as `~/.bashrc`) to see if you can find the culprit.

You can also try starting up with:

```
wsl ~ -e bash -x
wsl ~ -e zsh -x
```

That will turn on the trace/debug mode for either shell.  You should be able to see the offending section of the startup immediately before it hangs (or it goes into a loop).

I think we've determined that this isn't a WSL issue, though, right?  If you agree, can you close it out?  Thanks!

If you do need additional help debugging, I can try, if you ping me.  But you'll probably get better results on [Ask Ubuntu](https://askubuntu.com).  Alternatively, if you do determine that this is due to something in the Node installation, that would make it "programming related" and you could post on [Stack Overflow](https://stackoverflow.com) (if-and-only-if you are *sure* it's Node).

**Comment by sage393** [comment]
The problem problem was the Angular CLI autocompletion 

Commenting the following line in ~/.zshrc the problem was solved
#source <(ng completion script)

Thank you very much @NotTheDr01ds
