### ISSUE TITLE
nvidia-smi on WSL doesn't work but nvidia-smi.exe on windows works

### ISSUE THREAD

**Issue by anubhavashok** [microsoft/WSL#9134]
I get this error in WSL:
``` 
 NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
  
  Failed to properly shut down NVML: Driver Not Loaded
```

When I run it on Windows, I get:

```
  Wed Nov  9 21:31:58 2022
  +-----------------------------------------------------------------------------+
  | NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
  |-------------------------------+----------------------+----------------------+
  | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |                               |                      |               MIG M. |
  |===============================+======================+======================|
  |   0  NVIDIA GeForce ... WDDM  | 00000000:0A:00.0  On |                  N/A |
  |  0%   31C    P8    16W / 250W |    576MiB / 11264MiB |      0%      Default |
  |                               |                      |                  N/A |
  +-------------------------------+----------------------+----------------------+
  |   1  NVIDIA GeForce ... WDDM  | 00000000:43:00.0  On |                  N/A |
  |  0%   29C    P8    17W / 250W |   2152MiB / 11264MiB |     13%      Default |
  |                               |                      |                  N/A |
  +-------------------------------+----------------------+----------------------+
```
It looks like the binary at "C:\Windows\System32\lxss" that's linked to WSL doesn't match the one that's installed in Windows. Does anyone know how to fix this?

**Comment by elsaco** [comment]
@anubhavashok they don't necessarily have to match.

Here's output on Windows side:

```
PS C:\> nvidia-smi.exe
Wed Nov  9 20:52:51 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.40       Driver Version: 517.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
```

and on WSL side:

```
tux@RIPPER:~$ nvidia-smi
Wed Nov  9 20:52:57 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.75       Driver Version: 517.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+

```

Only the driver version is the same, the utilities aren't.

In WSL, what is the output of `command -v nvidia-smi`?

**Comment by anubhavashok** [comment]
On WSL, output of that command is:
```
/usr/lib/wsl/lib/nvidia-smi
```

**Comment by fzhan** [comment]
@anubhavashok could you please state the version of the WSL, windows and ubuntu?

**Comment by StephenChen2016** [comment]
hello i meet the same problem. do you solve it?

**Comment by muyuuuu** [comment]
hello i meet the same problem. do you solve it?

**Comment by Nasnl** [comment]
Same here. I'm using 560.35.03.

**Comment by rdmtinez** [comment]
Apparently, this is a feature not a bug. NVIDIA-SMI support is limited... although there is not mention of `Segmentation fault` you might be seeing in the following docs: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by esrivas17** [comment]
Facing the same issue as well

**Comment by dberga** [comment]
Same here, no clue why because in another computer I did the same and works with nvidia-smi. Seems an alias needs to be created in .bashrc if you want to solve it...

Here is my version
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 457.51       Driver Version: 457.51       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060   WDDM  | 00000000:01:00.0  On |                  N/A |
| 24%   36C    P8    10W / 160W |    902MiB /  6144MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by muyuuuu** [comment]
I reinstall WSL2 and solved.
