### ISSUE TITLE
Can WSL2 use Windows network proxy, or access Windows services easily?

### ISSUE THREAD

**Issue by dsyx** [microsoft/WSL#9170]
Due to the restricted network environment, I need to use a proxy service. If a static IP address is used in Windows, WSL2 can easily access services on Windows; but if a dynamic IP address is used in Windows, WSL2 needs to change the configuration every time.

I wish WSL2 could simply access services in Windows. In addition, I also hope that the IP of WSL2 can be static. Is there any good way?

Thanks!

**Comment by NotTheDr01ds** [comment]
Should probably be a [discussion](https://github.com/microsoft/WSL/discussions) item rather than an Issue ;-).

> If a static IP address is used in Windows, WSL2 can easily access services on Windows; but if a dynamic IP address is used in Windows, WSL2 needs to change the configuration every time.
>
> I wish WSL2 could simply access services in Windows

WSL provides an mDNS name for the Windows host.  See [this Stack Overflow answer](https://stackoverflow.com/a/69407064/11810933) for details, but to summarize, the Windows host name, with `.local` appended should give you a "fixed" name that you can use to address services in Windows, even when the dynamic IP changes.

But do take note of the other information in my Stack Overflow answer about the service binding rules as well as possible firewall issues that need to be addressed.

> I also hope that the IP of WSL2 can be static

I still need to try this at some point myself, but see [this blog post](https://randombytes.substack.com/p/bridged-networking-under-wsl?s=r) (not mine) for a possibility.  I'm not sure if that will work for providing a static address or not.

It should also provide `localhost` access to the Windows side of things from inside WSL2, meaning an mDNS name wouldn't be needed if so.

**Comment by dsyx** [comment]
@NotTheDr01ds 
The methods described in [this blog post](https://randombytes.substack.com/p/bridged-networking-under-wsl?s=r) may become invalid with updates. I think this need is pretty common, but there is no official way to provide a method, which confuses me a lot.
