### ISSUE TITLE
Access webserver hosted on WSL2 from other devices in same network.

### ISSUE THREAD

**Issue by AbhinasRegmi** [microsoft/WSL#9212]
When I host the webserver from windows with ipv4 as its hostname I was able to access the website
from my mobile devices under the same network. But doing this under wsl2 ubuntu doesn't work.

When I try to run django webserver with the ip assigned to wsl2 instance, I cannot access the webserver
even from same windows device. The webserver is accessible only when it runs on 127.0.0.1 . How can I 
access my wsl2 webserver from other devices under same network.

I would be very happy if you could provide me with a solution or even better release this feature on next update.

**Comment by jack775544** [comment]
A large range of solutions are discussed in this issue https://github.com/microsoft/WSL/issues/4150.

The 2 main approaches are using a TCP proxy on the windows side (docs [here](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan)), or by setting up a bridge mode adapter (this method is undocumented and experimental).

**Comment by icflorescu** [comment]
If you're looking for a quick way (and are familiar with Node.js/npm), simply run `npx expose-wsl` before starting your server.
More details here: https://github.com/icflorescu/expose-wsl

**Comment by diqidoq** [comment]
> If you're looking for a quick way (and are familiar with Node.js/npm), simply run `npx expose-wsl` before starting your server. More details here: https://github.com/icflorescu/expose-wsl

This is the best option so far form my point of view. a) because the chance is high that your dev env already has node, even many IDE's require it for some code and spell checks, etc. and b) it is REALLY doing all by itself. Even installing missing dependencies when running the command. It took me 5 seconds with WSL 2 and Win 11 / Debian after searching and buggin garound for days. This option should be more exposed to researchers, maybe in the windows issue queues or on top of WSL README's etc.
