### ISSUE TITLE
tail: unrecognized file system type 0x53464846 for ‘xxx’. please report this to bug-coreutils@gnu.org. reverting to polling

### ISSUE THREAD

**Issue by fceledon** [Microsoft/WSL#925]
Self explanatory. Even that this is a _warning_, not sure if this is `'tail'` or `file system` related.
In my sample, `xxx` is a regular file.

**Comment by pixelb** [comment]
It did say to report this to the coreutils project :)
Anyway it already has been reported, and will be fixed in the next coreutils release,
so the issue can be closed here

**Comment by fpqc** [comment]
Already reported.

**Comment by ianychoi** [comment]
Just FYI (listserv, as fpqc mentioned): https://lists.gnu.org/archive/html/bug-coreutils/2016-06/msg00019.html

**Comment by sba923** [comment]
I'm running WSL with Ubuntu 14.04 on Windows 10 version 1607, and the coreutils package is coreutils_8.21-1ubuntu5.4_amd64.deb, which still has the bug. How do I get a version of coreutils where this is fixed?

**Comment by DarthSpock** [comment]
If you're running Ubuntu 14.04 still, then what Windows version are you running (I suspect Anniversary). If you're aren't on build 16299, I suggest upgrading and doing an `lxrun uninstall` and reinstalling via the Windows Store. It'll come with 16.04 and an updated coreutils. (You can technically do an in place upgrade to 16.04  with `do-release-upgrade` either with your current or the updated Windows version but it's bit more buggy to keep the existing Ubuntu and upgrade than to do a fresh reinstall if you update Windows.)

**Comment by therealkenc** [comment]
Didn't realise this one was still open. This was WSL by-design and addressed in upstream coreutils. If someone invented a new filesystem on Real Linux that wasn't in the whitelist `tail` uses, it would spew the same warning.

@sba923, if you don't want to upgrade Ubuntu just download coreutils from [here](ftp://alpha.gnu.org/gnu/coreutils/), build, and install into `/usr/local`.

**Comment by sba923** [comment]
This is a corporate machine under IT control that has just been upgraded from TH2/1511 to RS2/1703, and policy disallows upgrading to RS3/1709.

I was able to run `lxrun uninstall` but it seems I can't install WSL from the Store (RS3 needed?)

Where do I go from here?

**Comment by benhillis** [comment]
@sba923 - You'll need rs3 to install from the store, the legacy distro is your only option:

lxrun.exe /install

**Comment by DarthSpock** [comment]
@sba923 If necessary, tell your IT security you need an exemption to policy to upgrade to RS3. This will allow you to download from the Store. Also WSL has significant improvements compared to RS2. See the Release Notes for detail. Of course at this point, you might want to just wait until the next stable release is out but if that's too far forward for them, at least you'll have the multi-distro capability and ability to download from the Store with the current **stable** version.

**Comment by sba923** [comment]
That's not possible, 'cos all machines have to be aligned for IT management reasons. I don't have enough justification to request such an exemption.

I'll stick with the `lxrun /install` option for now.

**Comment by neoadventist** [comment]
Anyone has any specific instructions on how to fix this?

**Comment by therealkenc** [comment]
> Seems like this is still a problem.
> Using ---disable-inotify does the trick

On [9p](https://www.kernel.org/doc/html/latest/filesystems/9p.html) (aka `/mnt/c` since circa 18917) that is variation #4739. But looking at coreutils [`stat.c`](http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=blob;f=src/stat.c;h=7a20ff782d69a972af3fdea12edb88735007d400;hb=v8.25-25-g8c81638#l463), `V9FS_MAGIC` (type `0x01021997`) is labeled as 'local' not 'remote'. You'll find that `tail(1)` doesn't work on native Linux with a 9p filesystem as well (though I didn't actually set up a native Linux 9p to confirm). Unless/until 9p on native Linux gets [`inotify(7)`](https://man7.org/linux/man-pages/man7/inotify.7.html) support (imho unlikely) GNU coreutils could use another patch submission. Like the [OP](https://github.com/microsoft/WSL/issues/925#issue-171779364) (which was `wslfs` type `0x53464846`) the 9p scenario is Linux behavior.
