### ISSUE TITLE
Windows Server 2022: boot wsl2 (and docker) at system start

### ISSUE THREAD

**Issue by sirber** [microsoft/WSL#9346]
**Is your feature request related to a problem? Please describe.**
With the new WSL2 support on Windows Server 2022, I would like to start WSL2 at system boot to start docker. 

**Describe the solution you'd like**
Could be registry keys, could be a service with configs...

**Describe alternatives you've considered**
I tryed Windows Task Scheduler whitout success. "wsl.exe" is a "Windows App".

**Comment by steskalja** [comment]
This is a large issue, unless they bring a way to convert any docker container to aks oci container. I have some docker containers where the developer will not release the code for me to install it locally even though it has no linux dependencies. I need to run them on Windows Server 2022 and on boot.

**Comment by sirredbeard** [comment]
When you say `I tryed Windows Task Scheduler whitout success. ` @sirber, what was the outcome?

I have no issue scheduling WSL commands in WTS (below), though not to necessarily run on boot, should just a matter of setting the right trigger.

![image](https://user-images.githubusercontent.com/33820650/212414538-b871e920-96d8-4acc-a614-3217940a2325.png)

**Comment by ejaquay** [comment]
Scheduler runs in session 0.  Store versions of wsl will not run in session 0.  Non store wsl versions wii run in session 0.  If you want to continue scheduling wsl tasks do not update to store wsl if you can avoid it.  There seems to be no easy way to go back.

**Comment by aki-k** [comment]
I found a way to do it not through task scheduler but through a Windows service:

https://github.com/microsoft/WSL/issues/8835#issuecomment-1446474057

**Comment by jplandry908** [comment]
I had the same issue and finally identified the root cause and fix. It appears that a change was made that prevented WSL from being accessible in Session 0 (what is used when you attempt to launch it via Task Scheduler). The Sept 2023 update fixes this.

https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/#fixes-and-improvements

I was able to update my WSL by running the following commands:
`wsl --update; wsl --update --pre-release`

Once I updated WSL, the scheduled task worked correctly. Hope this helps others.
