### ISSUE TITLE
[RTL/UTF8] Arabic Latters are disjoint in cmd/powershell

### ISSUE THREAD

**Issue by ArabCoders** [Microsoft/WSL#939]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

using Windows Linux Subsystem to curl a webpage and displaying the output of RTL content that has been encoded using UTF-8 causes the latter to be disjoint, please view the attached photo
- Expected results

the output should be correct Arabic word with joined letters the photo should read "المبرمجين" instead of those disjoint letters.
- Actual results (with terminal output if applicable)

posting it here would produce correct output.

![utf-8-bug](https://cloud.githubusercontent.com/assets/1621552/17811841/32a8cf98-662d-11e6-99db-80648b83915e.png)
- Your Windows build number

10.0.14393.0
- Steps / commands required to reproduce the error

curl https://www.abdulmohsen.me/arabic.html
- Required packages and commands to install
  curl

**Comment by bitcrazed** [comment]
Thanks for your bug report. The lack of UTF-8 support is a known issue and one we are currently working to remedy in up-coming Insiders builds.

**Comment by rizwan3d** [comment]
i am build Urdu Programming language and string give same error.

**Comment by ArabCoders** [comment]
@bitcrazed any update on this issue?

**Comment by bitcrazed** [comment]
Hi @ArabCoders. 

We're literally in the middle of a ton of Console re-engineering work that is the first step towards the Console being able to accurately render MUCH more of the UNICODE glyph space. It'll take a while to complete this work, and then replace our renderer, but the work is underway.

Closing this issue since:
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by elswerky** [comment]
@bitcrazed  is there any progress ?? 
also in bash on windows (wsl) ,, there is no arabic suppor
if i installed gui app on wsl ,i can't write arabic ,,only english is supported!
https://github.com/Microsoft/WSL/issues/3739
