### ISSUE TITLE
Error code: Wsl/Service/E_UNEXPECTED

### ISSUE THREAD

**Issue by nehe009** [microsoft/WSL#9490]
### Version

Microsoft Windows [Versión 10.0.19045.2486]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04

### Repro Steps

steps taken until I got the error, in a fresh OS installation
- Activate systemd
sudo nano /etc/wsl.conf
`[boot]
systemd=true`

wsl.exe –shutdown

- Install webmin
sudo nano /etc/apt/sources.list → deb https://download.webmin.com/download/repository sarge contrib
wget https://download.webmin.com/jcameron-key.asc
cat jcameron-key.asc | gpg --dearmor >/etc/apt/trusted.gpg.d/jcameron-key.gpg
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install webmin

- install webinoly (lemp)
wget -qO weby qrok.es/wy && sudo bash weby -clean
sudo stack -php-ver=8.1
sudo stack -mysql-ver=10.6
sudo stack -lemp

So far so good, all services work properly.

### Expected Behavior

When closing the console window where the linux operating system is open, the WSL is expected to stop all services in the background and turn off the virtual machine.

### Actual Behavior

When I start the application again I get the following error:

Fatal Error
Error code: Wsl/Service/E_UNEXPECTED
press any key to continue

and then the window closes.

**Comment by c4artisan** [comment]
this just happened to me after shutting down my ubuntu distro and then rebooting (after installing a few packages from the ubuntu-desktop bundle)

**Comment by c4artisan** [comment]
it somehow automagically revived itself?
installed the rest of the bundle (when i say bundle i mean the packages listed among "the following NEW packages will be installed" thing). working amazing so far

**Comment by vm75** [comment]
[WslLogs-2023-04-14_07-19-36.zip](https://github.com/microsoft/WSL/files/11233802/WslLogs-2023-04-14_07-19-36.zip)

For me WSL runs great initially. I notice this issue if I come back to work after a big gap. Once I hit the error, wsl --shutdown is useful.
    
    Linux home-pc 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    
    Distributor ID: Ubuntu
    Description:    Ubuntu 22.10
    Release:        22.10
    Codename:       kinetic

I am running the following: snaps, microk8s and I use VSCode plugin for WSL.

**Comment by Morrigan-Ship** [comment]
same error

**Comment by Taco0220** [comment]
same error:
Error code: Wsl/Service/E_UNEXPECTED
please.

**Comment by Taco0220** [comment]
> @Taco0220, If you need to restore the WSL "machine" (to recover files, etc.), see if this approach can help you: https://stackoverflow.com/a/76354545/1493870
> 
> It's not the solution to this issue. Only a way to get back the files inside the WSL.

I've tried a lot of things, but nothing worked。

**Comment by 901238746** [comment]
This just happened to me

**Comment by fliespl** [comment]
Get it frequently lately. Much confusion. I feel like it started once I:
- updated to latest
- enabled options="metadata"
- enabled dbus
```
# Check if DBus is running, if not, launch it
if ! pgrep -x "dbus-launch" > /dev/null; then
    eval `dbus-launch --sh-syntax`
#    echo "DBus session started."
fi
```

**Comment by noeldamps** [comment]
I had the same error today. `wsl.exe --shutdown` fixed it on my maschine.

**Comment by skhan87** [comment]
```powershell
wsl.exe --shutdown
``` worked for me

**Comment by LinZexiao** [comment]
the  same error, and `wsl.exe --shutdown` work

**Comment by floation-cutie** [comment]
`wsl --shutdown` works at first, **but every time when i reopen it**, it crash again...

**Comment by noeldamps** [comment]
> `wsl --shutdown` works at first, **but every time when i reopen it**, it crash again...

How do you start your wsl?

**Comment by earonesty** [comment]
crazy this error is 2 years old:
https://github.com/microsoft/WSL/issues/9490#issuecomment-1508653832

i bet it's something to do with sleep mode or battery saving

**Comment by shivshanks** [comment]
I just saw this issue and it did happen after my laptop had been put to sleep and left overnight. 

Had to get check some work stuff so didn't have the time to get logs but if this happens again, I will try to re-activate and submit logs. 

Honestly losing faith in WSL now as I feel like I can't trust it anymore. Network issues. Sleep/Stability issues ...

**Comment by andrewdinunzio** [comment]
Same thing happens for me after I bring it back on from sleep.

**Comment by AdrianoCahete** [comment]
I found that only the first/default distro is affected. So, if you have this problem, install Ubuntu as default, then install other distro that you want to use. You'll see that the default distro will become invalid a few days/months before, but not your selected distro (and idk why tbh).

I'm using Kali as secondary/base use and, apart from Ubuntu returning a 'Service E/Unexpected ', Kali is working flawless. 🤷

**Comment by xgenvn** [comment]
Come here when mounting physical disk for ext4 partition.
Using `--partition 1` working

```sh
wsl --mount \\.\PHYSICALDRIVE2 --partition 1
```

**Comment by heaths** [comment]
This is happening almost every time my machine resumes from hibernation on my aarch64 Surface Laptop 7. Given I work primarily in WSL2 on Rust and Go, this is productivity killer since I lose time, any env vars or some command history, etc.

**Comment by benjgil** [comment]
Anyone at Microsoft/WSL team actually looking into this? Only 2 years down the line...

Getting the same error every time i put my machine to sleep, Windows 11. 
Ubuntu as my only distro (dont want to have to start 'tricking' the system by installing a dummy linux distro just to get this to work)...

**Comment by kyojuu** [comment]
Still not fixed this bug? I still get the same error with my ubuntu once I put my computer into hibernation mode. Honestly, this frustrates me so much after I put a lot of effort into configuring my development env. What a productive killer.

**Comment by heaths** [comment]
If someone else runs into this problem, please collect logs and open a new issue for the team to track. See https://github.com/microsoft/WSL/issues/9490#issuecomment-1385862735 for how to collect necessary logs.

**Comment by Smaza002** [comment]
Every time the PC wakes from hibernation, WSL crashes with the error: Wsl/Service/E_UNEXPECTED.

**Comment by gbaian10** [comment]
In my current situation, as soon as Docker Desktop enters sleep mode, WSL breaks.
The simplest solution for me right now is to prevent Docker Desktop from going into sleep mode. There are two ways to do this:

1. Disable Docker Desktop’s automatic sleep mode (default is 5 minutes).
2. Start a container so that at least one container is running — this will keep Docker Desktop from entering sleep mode.

![Image](https://github.com/user-attachments/assets/d4a5170c-d09b-4b46-a040-fe905b46408a)

**Comment by victorasantos10** [comment]
Have anybody tried the solution proposed on this thread?

https://learn.microsoft.com/en-us/answers/questions/1312694/error-code-wsl-installdistro-e-unexpected-catastro

![Image](https://github.com/user-attachments/assets/fcd1882d-cc03-44d4-8edc-cd126c7868e6)

**Comment by earonesty** [comment]
it's not the same issue.  Ubuntu works great.  I use it everyday.  then
when the system goes to sleep, and wakes up, no new sessions can start
(shells).  but the existing sessions work fine.

**Comment by victorasantos10** [comment]
> it's not the same issue.  Ubuntu works great.  I use it everyday.  then
> when the system goes to sleep, and wakes up, no new sessions can start
> (shells).  but the existing sessions work fine.
> […](#)

For me, ubuntu is the one failing after sleep. If I just go on the Start Menu and search for WSL and press enter, it works. However the Ubuntu distro (which is where my dev containers are running) always stay unresponsive.

Maybe the best approach until M$ does something is just to cut off the sleep function, so I don't need to reload all my VSCode windows...

**Comment by listenerri** [comment]
In my case, disable docker-desktop `Resource Saver`

**Comment by Romain-GABET** [comment]
> In my case, disable docker-desktop `Resource Saver`

This solution worked for me too !

**Comment by eshapiro42** [comment]
> In my case, disable docker-desktop `Resource Saver`

Same here 🙏

**Comment by tourili** [comment]
This is happening to me as well since few months and it is very annoying as I need to restart the wsl2 each time
All my dev environment is on wsl2
Can we have a ETA for a fix ?

**Comment by fmingsl** [comment]
> This is just happen to me today. I have found my solution after searching on internet :
> 
> wsl --shutdown wsl --update wsl --install
> 
> after restart my computer, all worked fine.

Thank you, bro. I also experienced this error for the first time today when waking up from sleep. The WSL subsystem encountered the error upon opening, and VSCode couldn't access the WSL directory, although File Explorer could enter the WSL directory normally. I resolved the issue by updating the WSL subsystem to version 2.5.9 using `wsl --shutdown; wsl --update` and then reopening it, after which it ran normally.

**Comment by afilina** [comment]
I just restarted wsl like this:

`wsl --shutdown; wsl`

Back in business after this. No need to restart the computer. Thumbs up if this worked for you.

**Comment by eritpchy** [comment]
Same here 🙏 latest wsl

**Comment by WorstPIlot** [comment]
[WslLogs-2025-07-28_19-57-41.zip](https://github.com/user-attachments/files/21473871/WslLogs-2025-07-28_19-57-41.zip)

I reproduced issue
Here are the logs, if it can help anyone

**Comment by rafaelclp** [comment]
<img width="1476" height="757" alt="Image" src="https://github.com/user-attachments/assets/dbc49406-f20f-4112-8c0b-d4fa6755fa05" />

This is driving me crazy. After trying every single solution I could find on Google, I decided to reinstall Windows; clean install, didn't even import settings from my microsoft account, just in case it was some broken setting. I installed WSL with Ubuntu LTS and VS Code. Then I did the usual: I opened a WSL project in VS Code, went away for a few minutes (some people have said 30 minutes, I didn't time it, but seems about right), and when I returned WSL was dead. This always happens without fail. I need to manually shut it down (`wsl --shutdown`) and reload the VS Code window.

Since @WorstPIlot has already included logs I won't go through the trouble of doing the same. But it's easy to repro, even on a completely clean windows installation, the issue happens every single time.

Edit: worth noting that it's not 100% true that all I did was install WSL. I have a private repo with my setup (which installs and configures zsh, oh-my-zsh, and a lot of dev tools I use), and the first thing I did was run my setup script. I find it unlikely that my setup would be  the reason, but the possibility does exist.

**Comment by WorstPIlot** [comment]
By the way, after @rafaelclp mentioned it I am using zsh and oh-my-zsh too however, I am using archlinux wsl and as far as I remember It didn't reproduced on Ubuntu WSL on me

**Comment by rafaelclp** [comment]
Another important piece of information.

I started a terminal and ran `wsl`. I left it open, and opened VS Code as well. I left for a while, and when I returned VS Code was dead as usual, but the terminal was working fine. I can run commands on it, no problem.

If I try to start `wsl` on another terminal it fails with the Wsl/Service/E_UNEXPECTED error.

**Comment by roland-kiraly** [comment]
@WorstPIlot I use arch on WSL too, and this just happened now when running paru for package updates

**Comment by rgbygv** [comment]
> [@WorstPIlot](https://github.com/WorstPIlot) I use arch on WSL too, and this just happened now when running paru for package updates

I'm using arch on WSL too. After I updated by `pacman -Syu` then the system was panic.
Solved by `wsl --update`.

**Comment by journeymansix** [comment]
> In my case, disable docker-desktop Resource Saver

Worked for me too. Thanks!

**Comment by Ricaz** [comment]
Mine broke as I did `pacman -Syu` as well.

After running `wsl --update` in an elevated cmd shell, it started working again. It failed to update when running as user.

**Comment by artemsheinacn** [comment]
Same issue, after KMODE_EXCEPTION_NOT_HANDLED BSOD. Why is it closed without a solution?

**Comment by fvelcker** [comment]
Same here.
And same as above, the terminal was still open un running, but vscode couldn't connect, and couldn't start a fresh wsl session.
`wsl --shutdown` did the trick.

It happens to me since recently and often, like one a week. But also I have been provided with a new laptop and a new wsl installation.

**Comment by SpainTrain** [comment]
> Another important piece of information.
> 
> I started a terminal and ran `wsl`. I left it open, and opened VS Code as well. I left for a while, and when I returned VS Code was dead as usual, but the terminal was working fine. I can run commands on it, no problem.
> 
> If I try to start `wsl` on another terminal it fails with the Wsl/Service/E_UNEXPECTED error.

@rafaelclp I am experiencing the exact behavior you have described and tried all the approaches suggested in this issue.  Have you happened to track down and fix this issue yet, or still a mystery? Thanks!

**Comment by christymanthara** [comment]
@SpainTrain hitting the same error. none of the solutions work

**Comment by christymanthara** [comment]
Removed my distribution and reinstalled with the following commands

`wsl --shutdown
wsl --unregister Ubuntu-24.04 
wsl --install Ubuntu-24.04`

**Comment by amitph1207** [comment]
Do we have a permanent fix for this? This is such a productivity killer where I am doing wsl --shutdown wsl literally every single morning since last 1 week.

**Comment by rajphoenix20** [comment]
I had the same error,

<img width="781" height="125" alt="Image" src="https://github.com/user-attachments/assets/87e413d1-d28c-4abd-8686-268e48ad2294" />

solved by `wsl --shutdown` followed by `wsl -d <distro>`

**Comment by byzxc** [comment]
i just got it as well.
`wsl --shutdown` does the job

**Comment by iwangbowen** [comment]
it happened to me

**Comment by iwangbowen** [comment]
Please help us

**Comment by viciousstar** [comment]
i just got it as well.
wsl --shutdown does the job

**Comment by mgcooper** [comment]
> > Another important piece of information.
> > I started a terminal and ran `wsl`. I left it open, and opened VS Code as well. I left for a while, and when I returned VS Code was dead as usual, but the terminal was working fine. I can run commands on it, no problem.
> > If I try to start `wsl` on another terminal it fails with the Wsl/Service/E_UNEXPECTED error.
> 
> [@rafaelclp](https://github.com/rafaelclp) I am experiencing the exact behavior you have described and tried all the approaches suggested in this issue. Have you happened to track down and fix this issue yet, or still a mystery? Thanks!

I'm experiencing the exact same behavior. Weirdly, it just started a few days ago, previously never occurred, whereas this thread suggests it's been a problem for a while. The patch that works is to open a new powershell terminal and run `wsl --shutdown` then relaunch with `wsl` then if I have open wsl terminal tabs press Enter to restart. But I still have to close any open vscode workspaces and reopen them after restarting wsl and restarting each tab.

**Comment by orionnelson** [comment]
I encountered this same issue. 

I was working with a setup similar to this tutorial  https://www.youtube.com/watch?v=AwHP0bI9QLc  but was doing 

```kex --win -s```  as some windows 11 change leads to ```kex --wtstart -s``` being inconsistant since the latest update.  

After multiple sleeps the instance died.  

wsl -d kali-linux
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

Attached Log 

[WslLogs-2025-11-26_21-17-36.zip](https://github.com/user-attachments/files/23783409/WslLogs-2025-11-26_21-17-36.zip)

**Comment by tbn-mm** [comment]
Just happend to me:

PS C:\WINDOWS\system32> wsl
Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED

I was developing via VSC, ng serve, saved the file and rebuild was finished and then it crashed.
Btw windows is installing some updates since 2 hours. Maybe it has replaced or killed some essential files or processes. Memory usage is at 80% according to task manager.

It happend again and again. I have logged it from start until crash:

[WslLogs-2025-12-11_15-30-20.zip](https://github.com/user-attachments/files/24104840/WslLogs-2025-12-11_15-30-20.zip)

**Comment by rafaelclp** [comment]
> > Another important piece of information.
> > I started a terminal and ran `wsl`. I left it open, and opened VS Code as well. I left for a while, and when I returned VS Code was dead as usual, but the terminal was working fine. I can run commands on it, no problem.
> > If I try to start `wsl` on another terminal it fails with the Wsl/Service/E_UNEXPECTED error.
> 
> [@rafaelclp](https://github.com/rafaelclp) I am experiencing the exact behavior you have described and tried all the approaches suggested in this issue. Have you happened to track down and fix this issue yet, or still a mystery? Thanks!

Unfortunately I couldn't figure it out, and given how badly this issue was affecting my productivity, I decided to just delete Windows and install Fedora instead. So I'm not even looking for a fix anymore.

**Comment by argothiel** [comment]
It started happening today. Everything was fine, but suddenly it keeps crashing. Yesterday I've updated from 2.6.0.0 to 2.6.3.0, maybe that's related?

**Comment by CodyJHeiser** [comment]
I get the same issue pretty regularly - happens when I leave my machine running for an extended period of time. wsl --shutdown works to fix the issue but would love a more permanent solution.

**Comment by ert11er** [comment]
### **FOR USERS THAT STILL HAVE THE SAME PROBLEM**
Please type **"wsl --shutdown"** again and open the VM using **"wsl"** again. It worked for me.

**Comment by ZeroMax-dev** [comment]
`wsl --shutdown` cannot be the solution. I have several terminal windows open, shutting down WSL after waking my laptop up from standby kills all of my sessions, building them up again every time sucks hard.

**Comment by bl4ckr0ss3** [comment]
I have got this error after inserting the below code to the /etc/wsl.conf

```
[boot]
systemd=true
```

I've tried all of the methods that is mentioned above, they didn't worked.

**Solution**:
It turns out my WSL wasn't up-to-date, so just basic ```wsl --update``` did the trick.

**Comment by jlumpe** [comment]
Still having the problem constantly in 2026...

**Comment by deveasyclick** [comment]
I got this error today

**Comment by driversat** [comment]
> `wsl --update` did the trick.

thank you m8, done.

**Comment by lokirithm** [comment]
Simple restarting the WSL service worked for me. 

1. In the windows search bar search for "services". 
2. Click on the services.
3. Look for WSL service in the list. 
4. Right click to restart the service.

**Comment by DotaPie** [comment]
`wsl --update` did the job, thanks

**Comment by nopeitsnothing** [comment]
## WSL2 fails to boot intermittently on cold starts

Though I'm not a regular Windows user, I have done some testing. I cannot reproduce this error since, except sometimes after rebooting my entire desktop, but I can fix it. I'll include my logs later in this post. My error occurred after compiling the kernel for WSL myself, which worked for a day; it failed to boot WSL unless I removed the `kernel=...` line.

> [!NOTE] 
> Remember to run in Powershell: `wsl --shutdown` and `get-process docker* | stop-process` and `get-process *docker* | stop-process` to kill all docker instances/processes after you remove the kernel line.

### Step 1: Try a shutdown and restart first

If you have set up your terminal to boot a specific distro:

- First, try to `wsl --update` in a new Powershell window. If it still doesn't start WSL, proceed to the next step.
- Win + "terminal" (start your Terminal / Terminal preview).
- In the app, open a new Powershell window, and type `wsl --shutdown [distro]`.
- In the same window, type `wsl` - it should now boot into the distro. If it doesn't - we have to probably recompile the kernel and verify we have the correct modules (via `make modules_install`), and ensure the correct options for (in my case I have systemd enabled) systemd are actually available each cold boot of the lightweight Hyper-V which boots the WSL kernel.

**Note:** It often persists beyond the 8s that is usually mentioned after `wsl --shutdown` recommendations since that's the sweet spot for restarts. Maybe you got lucky and this worked, otherwise continue...
### Step 2: Parse the logs

Run the following to filter the WSL event log to errors and warnings only:

```powershell
Get-WinEvent -Path "C:\...\logs.etl" -Oldest | Where-Object { $_.LevelDisplayName -in "Error", "Warning" } | Format-List TimeCreated, LevelDisplayName, Message
```

Replace the path with the path to your actual log file.

### Step 3: Identify the errors, in my case they are VPCI errors

Look for a series of repeated errors from `vmvpci.dll` with error code `0x8007139F`, like this:

```plaintext
TimeCreated      : 5/30/2026 12:50:22 AM
LevelDisplayName : Error
Message          : [Virtual machine E4F88556-F267-44AA-AD8A-4190B2E7ACDF]
                   onecore\vm\dv\vpci\core2\comvpcibus.cpp(988)\vmvpci.dll!00007FFFE9BD9E10: (caller:
                   00007FFFCCCAB86C) ReturnHr(68) tid(1eec) 8007139F The group or resource is not in the correct state
                   to perform the requested operation.
                       CallContext:[\VpciComMethod]
```

If you see these, followed by this error:

```plaintext
TimeCreated      : 5/30/2026 12:50:22 AM
LevelDisplayName : Error
Message          : onecore\vm\compute\management\orchestration\shared\vmcommon\virtualgpu.cpp(682)\vmcompute.exe!00007F
                   F7F597B82A: (caller: 00007FF7F5A69AC7) LogHr(18) tid(6308) 80070057 The parameter is incorrect.
                       CallContext:[\VirtualMachine_Destruct]
```

We have a VPCI bus initialization failure. Hyper-V is trying to enumerate virtual PCI devices when the VM is in a state that won't accept them.

- The VM starts booting
- The VPCI bus fails to initialize properly
- Hyper-V gives up and begins tearing the VM down (`VirtualMachine_Destruct`)
- During teardown, Hyper-V tries to clean up the virtual GPU object - but since the GPU was never fully initialized due to the VPCI failure, the cleanup receives an invalid parameter and logs `0x80070057`

So the `virtualgpu.cpp` error is essentially Hyper-V trying to destroy an object that was never fully constructed. This means the actual root failure is still the VPCI bus errors, and the GPU error is just the cleanup **failing gracefully afterward**. So the focus should remain entirely on why the virtual PCI bus is failing to initialize, which points back to the GPU driver/HAGS conflict on the host side. Update your GPU driver as explained above, and hopefully that fixes it. If not, proceed.

### Step 4: Confirm and fix the GPU issue

Add the following to your `.wslconfig`:

```ini
[wsl2]
gpuSupport=false
```

To keep GPU support, explicitly set support to true.

```ini
[wsl2]
gpuSupport=true
```

If WSL now boots successfully, the failure was GPU-related.

- **Update your host GPU driver** - get the latest driver directly from your GPU manufacturer's site rather than Windows Update, as WSL compute driver support can lag there.
- **Check for HAGS conflicts** - if "Hardware Accelerated GPU Scheduling" is enabled in Windows graphics settings, try disabling it.
- **Check for hypervisor conflicts**  - things interfere with Hyper-V's virtualization stack and produce this same error.

If disabling `gpuSupport` does not help, the VPCI failure may have a different cause and the issue may require further investigation beyond this guide. If that's the case then I can't help you. But, if you do have a custom kernel like me, and you want to go the easy route, just go back to the original kernel and save yourself the hassle. But I was able to fix it without doing that, simply by checking event logs and narrowing it down to a faulty config.

```bash
CONFIG_CGROUP_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_PSI=y (and CONFIG_PSI_DEFAULT_DISABLED is not set)
CONFIG_MEMCG=y
CONFIG_IPV6=y
CONFIG_AUTOFS_FS=m
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_TMPFS_XATTR=y
CONFIG_USER_NS=y
CONFIG_SECCOMP=y
CONFIG_SECCOMP_FILTER=y
```

All set. 

```bash
Loading personal and system profiles took 1803ms.
PS > wsl
/mnt/c/Program Files/PowerShell/7 λ >
```

**Comment by thisismypassport** [comment]
For me, the error started happening after the system shut down unexpectedly due to a power outage.

Just doing "wsl --shutdown" didn't work - I had to also temporarily empty out my .wslconfig file. (Had a custom kernel)
Then, I was able to get wsl booting, but it did so in read-only mode.
I followed the steps at https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error - including installing a second distro - and then randomly repeated the commands in arbitrary orders until they actually worked.
That - after some more random "wsl --shutdown"s and wsl start-ups for the changes to mysteriously take - caused wsl to boot normally again.
I was then able to restore my .wslconfig file with no ill effect.

I guess the wsl recovery process doesn't like custom kernels?

**Comment by jayvynl** [comment]
I ran into this same issue. Without any warning while the machine was running fine, VS Code suddenly disconnected from WSL2—one second I was coding normally, and the next I couldn't connect. Attempting to restart WSL2 resulted in this error.

Turn out that my disk is full.
