### ISSUE TITLE
Line buffering 

### ISSUE THREAD

**Issue by NateElliott** [Microsoft/WSL#952]
While using cURL for example, and the UP key (doskey style) the line buffering seems to misplace the cursor location causing any input text to display in the proper location however the submitted command has the augmented text in the wrong location.

eg.

user@user-pc:/home$ cURL -i http:localhost:5000/api/v1.0/echo/echoTest
_command executes_
_press up key_
user@user-pc:/home$ cURL -i http:localhost:5000/api/v1.0/echo/echoTest**numberTwo**
_new text displays in the right location but executes like:_
user@user-pc:/home$ cURL -i http:l**numberTwo**ocalhost:5000/api/v1.0/echo/echoTest

**Comment by zadjii-msft** [comment]
@NateElliott Is there any chance you're on a SurfaceBook? And/or what kind of graphics card setup are you using?

We noticed a problem like this on a colleague's SurfaceBook, that was resolved by switching off the integrated graphics.

**Comment by NateElliott** [comment]
On an Alienware 13 with GTX960M

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
