### ISSUE TITLE
non ascii characters on stdin in cooked mode are not rendered correctly

### ISSUE THREAD

**Issue by xilun** [Microsoft/WSL#958]
- A brief description

non ascii characters on stdin in cooked mode are not rendered correctly
- Expected results

![image](https://cloud.githubusercontent.com/assets/6464553/17839356/7eae83f6-67e5-11e6-8ae7-ba57a4bad064.png)
- Actual results (with terminal output if applicable)

![image](https://cloud.githubusercontent.com/assets/6464553/17839341/295a4da4-67e5-11e6-841c-e03de3546535.png)
- Your Windows build number

pb exists at least on 14393.51 and 14905.1000
- Steps / commands required to reproduce the error

launch hd
press é, press enter, press Ctrl-D 2 times.

**Comment by xilun** [comment]
Note: fixed in 14946

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
