### ISSUE TITLE
Error 0x80040154 when trying to open bash

### ISSUE THREAD

**Issue by aseering** [Microsoft/WSL#960]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

When I run "bash.exe" from a command prompt, or use the Bash start-menu shortcut, I get the following:

```
C:\Users\me>bash
Error: 0x80040154

C:\Users\me>
```
- Expected results
  bash should open and give me a prompt
- Your Windows build number
  14905.1000
- Steps / commands required to reproduce the error
  This only happens for me on one machine.  I have been running the Fast Ring on this machine for some time (a couple months at least); bash was working fine as of the release of the Anniversary Update, but seems to have subsequently stopped working.  I haven't been doing much interesting on this machine lately other than taking new Fast Ring releases (no new software, no intentionally messing with system files, mostly just e-mail and casual Web browsing); nothing that I would expect to affect WSL's basic functionality.

My assumption is that something got uninstalled for some reason.  I plan to go erase and reinstall stuff until it works again.  Let me know if there's any debugging information that I should capture before I do, to help figure out what happened to see if it's a bug or other issue that could be tracked down and fixed.

# -------- HELP! --------
## Sorry for injecting this into Adam's issue report, but we're requesting your help to track-down the root cause of this issue!

If you are experiencing this issue and are willing to help is track this issue down, please gather following logs:

```
C:\windows\panther\*.log
C:\windows.old\logs\cbs\*.*
C:\windows.old\System32\winevt\Logs\System.evtx
```
Then, please email richturn at Microsoft d-o-t c_o_m, so that we can arrange secure transfer of your logs for our engineers to diagnose.

Thanks in advance 
# ----------------

**Comment by russalex** [comment]
Hi @aseering 

I have seen this error in the past.  Normally what happens here is the Windows Subsystem for Linux feature is somehow turned off during the update.  If you go in and re-enable the Windows feature everything should start working for you again.

This happened quite a bit on an old Windows Insider build back when we first started doing Insider builds for the Anniversary Update.  Writing a new bug on the Windows feature team now that we have two instances of it here (#896).

**Comment by Geeknux** [comment]
i had the same error, i just re tick Linux Sub System from control panel to install it once again and it worked now

**Comment by aseering** [comment]
Thanks @russalex for the explanation!  And the link -- I thought I had seen something like this recently; I searched for the error code before posting but forgot to include closed issues.

The first time after I ran the command, I was prompted as follows:

```
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
```

bash then spun for a while and then exited without installing successfully.  (I opened bash from the Start Menu shortcut so it closed before I could read any error output.)

I ran it a second time and the installation proceeded successfully.  So it works fine now.

For what it's worth, when I went to check (before re-enabling WSL), I found that the laptop was in "Developer" mode but a spinner appeared beneath that selection indicating that it was installing some components.  It succeeded and prompted me to reboot.  Maybe WSL got disabled because Developer mode was missing a dependency?  No idea; just passing information along.

**Comment by frnkblk** [comment]
I had the same issue too ... bash support was working before the Windows upgrade.  But it was unchecked when I looked at it again.

**Comment by c0nnex** [comment]
Same problem here. After re-enabling the Unix subsystem, it works again, BUT all my files in /home/myname were gone ... *sigh*

**Comment by ezrosent** [comment]
I just had this issue as well. It took a while for me to find this because I only get the error code when running bash from `cmd`, while I usually just run `bash.exe` from the taskbar .

While` /home/myname` was not gone for me, I ran into an issue where when setting up my login *again*, the setup program was unable to create my login (because `/home/myname` already existed). I had to manually run `adduser myname` to add my login again, but after that my settings were restored. 

Needless to say, this has been a very negative experience. If I have to go through this rigmarole every time there is an update, I probably just wont bother.

**Comment by dpremy** [comment]
Same issue here as well, the unix subsystem feature had become disabled. Once I enabled I had to reboot and on first run it reinstalled. I do seem to have also lost my profile and installed applications.

**Comment by peterromfeldhk** [comment]
Same issue running Windows creator update (free trial, no updates, just enabled developer mode and subsystem) in virtual-box(just standard settings -next,next,next) on OSX

**Comment by Diluka** [comment]
I use ssh from mac to windows. I expect to ssh into WSL, but seems got windows cmd for instead.
And I run bash in the cmd got this error.

**Comment by vjirovsky** [comment]
For everybody with this issue (described by @aseering), there is solution how to fix your computer. 

1. Run this Powershell command, with elevated privileges:
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

2. restart computer
3. go to website https://aka.ms/wslstore (it will open Windows Store app)
4. select subsystem you want
5. finish installation of subsystem

**Comment by benhillis** [comment]
I believe this issue should no longer be present in 1803.  Please let us know if you continue to hit this issue.

**Comment by p3lim** [comment]
Had this happen in 1803, after a restart trying to run `bash` in cmd.exe responded with "Windows Subsystem for Linux has no installed distributions", even though I was using it an hour ago.

**Comment by XoroshiroNOT** [comment]
I've been running WSL for about 6 months without issue, but just recently start launching bash multiple times from a single BAT file, which I've done about 10 times without issue. This time got 'Error: 0x800704d5' for ONLY the first 2 out of 12 bash windows launched by this BAT:

TIMEOUT /T 16500 /NOBREAK
del testxoroshironot
copy testxoroshironot*.log resultsA\*.*
start bash -c "./bigcrushallparallel1.sh" 'this one errored
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel2.sh" 'this one errored
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel3.sh" 'this and the rest were fine
TIMEOUT /T 250 /NOBREAK
start bash -c "./bigcrushallparallel4.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel5.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel6.sh"
TIMEOUT /T 300 /NOBREAK
start bash -c "./bigcrushallparallel7.sh"
TIMEOUT /T 350 /NOBREAK
start bash -c "./bigcrushallparallel8.sh"
TIMEOUT /T 350 /NOBREAK
start bash -c "./bigcrushallparallel9.sh"
TIMEOUT /T 400 /NOBREAK
start bash -c "./bigcrushallparallel10.sh"
TIMEOUT /T 400 /NOBREAK
start bash -c "./bigcrushallparallel11.sh"
TIMEOUT /T 450 /NOBREAK
start bash -c "./bigcrushallparallel12.sh"
pause

Perhaps knowing that, in at least my case, the issue is rare and apparently self-correcting within a 10 minute time frame, will help future efforts to resolve this issue.
