### ISSUE TITLE
Support of Linux Kernel 6.1 (LTS) in WSL

### ISSUE THREAD

**Issue by ohault** [microsoft/WSL#9645]

**Comment by benhillis** [comment]
We will be moving to 6.1 soon(tm).

**Comment by ohault** [comment]
I don't have a time machine!

Can you please do not close any ticket not yet completed ?

Thx.

**Comment by ohault** [comment]
What is the status about this work ?

**Comment by ohault** [comment]
Can we expect to see https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-6.1.y soon as the default branch ?

**Comment by fredizzimo** [comment]
I would really appreciate that the kernel got updated since the journal log spam of "FS-Cache: Duplicate cookie detected" is very annoying. https://github.com/microsoft/WSL/issues/5694.

For the longest time I was running on WSL 1.1.7, which is using Kernel 6.1.21, and it was working great, but due to other issues I need newer version of WSL. So, I'm forced to accept the logpam.
