### ISSUE TITLE
Environment variable WSL_DISTRO_NAME not available as root

### ISSUE THREAD

**Issue by EduardGomezEscandell** [microsoft/WSL#9719]
### Version

Microsoft Windows [Versión 10.0.22623.1325]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu-22.04, reproducible in Ubuntu-23.04 as well

### Repro Steps

Create the following file and make it executable:
```bash
#!/usr/bin/bash
echo "WSL_DISTRO_NAME: $WSL_DISTRO_NAME"
```

Then, compare outputs
```
# As a regular user, the variable is available.
$ ./run.sh
WSL_DISTRO_NAME: Ubuntu-22.04

# With sudo, the variable is unbound
$ sudo ./run.sh
WSL_DISTRO_NAME:

# Switching to root first, the variable is unbound
$ sudo -i
# ./run.sh
WSL_DISTRO_NAME:
```

However, if we log in as root, the variable is available.
```
PS > wsl -d Ubuntu-22.04 -u root
# ./run.sh
WSL_DISTRO_NAME: Ubuntu-22.04
```

This seems a bit silly, but it affects the implementation of WSL-oriented systemd services, as they run as root. To see how, create and enable a simple service that runs `run.sh`, and reboot wsl, and you'll see:
```
$ cat test.service
[Unit]
Description=TestService

[Service]
ExecStart=/path/to/run.sh

[Install]
WantedBy=multi-user.target

$ sudo systemctl enable test.service
Created symlink /etc/systemd/system/multi-user.target.wants/test.service → /etc/systemd/system/test.service.
$ exit
PS > wsl -t Ubuntu-22.04
```

The journal shows that the variable is unbound to the service even when it is available to the user:
```
PS > wsl -d Ubuntu-22.04
$ journalctl -eu test.service --no-pager --boot=0
Mar 01 18:38:58 LAPTOP-AKHDCDJ9 systemd[1]: Started TestService.
Mar 01 18:38:58 LAPTOP-AKHDCDJ9 run.sh[148]: WSL_DISTRO_NAME:
Mar 01 18:38:58 LAPTOP-AKHDCDJ9 systemd[1]: test.service: Deactivated successfully.
$ echo $WSL_DISTRO_NAME
Ubuntu-22.04
```

### Expected Behavior

WSL_DISTRO_NAME should always be available, or at the very least available to systemd services.

### Actual Behavior

It is only available to the user you logged in as.

**Comment by benhillis** [comment]
The fact that systemd services should have this environment variable set is a good callout, I'll fix that. I do want to call out though, that when using sudo, that by design will clear environment variables - so that part is expected.

**Comment by elsaco** [comment]
Ubuntu-22.04 and most other distros have `env_reset` flag enabled. Check `/etc/sudoers`. It's a safety feature. Disable the flag or use the preserve user environment option when running the command.

**Comment by didrocks** [comment]
Let’s put aside the sudo discussion, which is not really the initial request (sorry if that was confusing), and focus on the "service" part of it.

@benhillis: indeed, for security reasons, systemd strips some env variable to the service to have a minimal set of it.
It can be beneficial in some circumstances, to have systemd services having access to the WSL specific variables, especially the WSL distro name.

There are 2 ways to "relax" this rules.

Let’s take a simple service unit (`env.service`):
```ini
[Unit]
Description=Env test

[Service]
Type=oneshot
ExecStart=/usr/bin/env
```

## The preferred approach

1. systemd, spawn by Microsoft's init process, have the `WSL_*` env variables set.
2. At that moment, no services  have access to those extra variables:
```sh
# systemctl start env.service
# systemctl status env.service
○ env.service - Env test
[…]
mars 02 09:51:42 casanier env[132619]: LANG=fr_FR.UTF-8
mars 02 09:51:42 casanier env[132619]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
mars 02 09:51:42 casanier env[132619]: INVOCATION_ID=7500240f85654d538a95819b70fa6ef3
mars 02 09:51:42 casanier env[132619]: JOURNAL_STREAM=8:209194
mars 02 09:51:42 casanier env[132619]: SYSTEMD_EXEC_PID=132619
mars 02 09:51:42 casanier systemd[1]: env.service: Deactivated successfully.
mars 02 09:51:42 casanier systemd[1]: Finished Test.
```
3. However, if I want to now give access `WSL_DISTRO_NAME` to it, I can modify my unit definition to:
```ini
[Unit]
Description=Env test

[Service]
PassEnvironment=WSL_DISTRO_NAME
Type=oneshot
ExecStart=/usr/bin/env
```

And now, my env.service can see this variable:
```sh
# systemctl start env.service
# systemctl status env.service
○ env.service - Env test
[…]
mars 02 09:52:22 casanier env[142086]: LANG=fr_FR.UTF-8
mars 02 09:52:22 casanier env[142086]: WSL_DISTRO_NAME=MyDistro
[…]
mars 02 09:52:22 casanier systemd[1]: env.service: Deactivated successfully.
mars 02 09:52:22 casanier systemd[1]: Finished Test.
```

This thus gives to the service creator the option to have access to the distro name for instance.

The fix for this use case is then for the process spawning systemd in the new PID namespace (Microsoft’s init process probably) to set the environment variables before setting them.

Note that you are already setting the following env variables to systemd: `WSL2_CROSS_DISTRO`, `WSL2_SYSTEM_DISTRO_SHARE=`, `WSL2_GPU_SHARE_ENV_drivers` and `WSL2_GPU_SHARE_ENV_lib`.

## Another approach, giving unconditional access to WSL_* variables (and can be racy)

The other approach is one that is often used with `systemd --user`, where process can set env variable after the fact, the idea is:

1. Systemd is spawn in its own PID namespace, without the additional env variable.
2. Have "something" (probably Microsoft’s init system), in the same PID namespace executes:
```sh
# systemctl set-environment WSL_DISTRO_NAME=MyDistro
```
alternative: do it directly through systemd's dbus API
3. Then, any services, even without `PassEnvironment` is now able to access to the env variable:
```sh
# systemctl start env.service
# systemctl status env.service
○ env.service - Env test
[…]
mars 02 09:53:25 casanier env[142135]: LANG=fr_FR.UTF-8
mars 02 09:53:25 casanier env[142135]: WSL_DISTRO_NAME=MyDistro
[…]
mars 02 09:53:25 casanier systemd[1]: env.service: Deactivated successfully.
mars 02 09:53:25 casanier systemd[1]: Finished Test.
```

However, this means that any services started between systemd initial execute and this set-environment command will not have access to the env variable, hence a race.
