### ISSUE TITLE
WSL2 upgrade just prints `help` text

### ISSUE THREAD

**Issue by baughmann** [microsoft/WSL#9771]
### Windows Version

Microsoft Windows [Version 10.0.20348.587]

### WSL Version

Invalid command line option: --version (followed by help text)

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-2348

### Distro Version

Ubuntu 20.04 LTS

### Other Software

Docker Desktop for Windows v4.17.0

### Repro Steps

On a clean installation of Windows Server 2022 version 10.0.20348.587, follow the guide [official Microsoft guid](https://learn.microsoft.com/en-us/windows/wsl/install-on-server) and simply run `wsl --install` and follow the steps.

### Expected Behavior

I should have had the option to select Ubuntu 22.04, and it would be installed using WSL2.

### Actual Behavior

I was multitasking and do not remember the exact steps I took after running `wsl --install` but everything appeared to set up normally. I *thought* that I had selected Ubuntu 22.04 during that process.

When I tried to use Docker Desktop I was greeting with a strange `Newtonsoft.Json` error and began to troubleshoot.

I noticed that `wsl -l -v` outputs `Ubuntu   Stopped   1` for `NAME   STATE   VERSION`. I attempted to run `wsl --set-version Ubuntu 2` and was greeted with:

```
PS C:\Windows\system32> wsl --set-version Ubuntu 2
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:
...
```

Interestingly, I am also unable to win `wsl --version`, maybe because I'm running version 1 for some odd reason:

```
PS C:\Windows\system32> wsl --version
Invalid command line option: --version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```

Why the heck am I running WSL1 on Server 2022, and how do I upgrade it?

**Comment by benhillis** [comment]
There was an issue in the Server 2022 branch where the --set-version option got removed. We are working on bringing a fix back, but in the meantime you should be able to use `wsl.exe --set-default-version 2` before you register your distro.

**Comment by worgar** [comment]
I try to run ANY wsl command and it prints just the help message (-l, --set-default-version, anything.)

**Comment by islet5** [comment]
hello, is there any updates? i have the same issue

**Comment by JohnnySavages** [comment]
Same problem. <3 windows!

For descendants:
Your problem is probably in the old wsl version. It doesn’t have arguments like ` -l -v, --set-default-version, etc` therefore you get help message. If you need to update your wsl follow this guide https://learn.microsoft.com/en-us/windows/wsl/install-manual and use wsl arguments from your help message.
I myself found some strange thing with `--status` argument. I didn’t have any output from command, therefore I can’t find workflow for my work. That was reason for blaming win and wls. If you have similar situation consider updating. I haven’t found any other option for `get version` problem(
Again <3 windows.
