### ISSUE TITLE
Ubuntu style clipboard

### ISSUE THREAD

**Issue by johnnyalexa** [Microsoft/WSL#978]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- Bash for windows should have similar behavior with bash in Ubuntu
- Ubuntu Clipboard style is needed (right click to select and copy, click on the wheel to paste into bash)
- N/A
- 10.0.14393
- Open bash for windows, select text to copy then click on the wheel. 
- N/A
- N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Thanks @johnnyalexa for your feedback!  I think the WSL team is probably aware of this limitation in the Console; they would probably appreciate it if you could talk about and vote for it in the [UserVoice forum](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) so that they can get a sense on how to prioritize it.

In the meantime, you can actually install gnome-terminal on Windows, though it doesn't work all that well right now.  Other Linux terminals work better.  Either way, you have to [install X-Windows](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=14) first.  @fpqc has recommended `rxvt-unicode` a bunch of times as an alternative terminal; maybe worth writing a post on how to install it?

**Comment by johnnyalexa** [comment]
Thanks for the reply. I am not really sure if that is needed. One option is to install cygwin and then ssh to windows-bash ... then all the select & paste with the mouse work well.

**Comment by SRGOM** [comment]
In X, "ubuntu" style clipboard works just fine... (you'd be glad to know that Windows you can get consistent clipboard behavior). X has a very inconsistent behaviour re clipboard where each application individually (mis) manages its clipboard with no standard definition of middle click.

**Comment by bitcrazed** [comment]
Thanks for the ask @johnnyalexa. This is on our backlog for future consideration. As @aseering pointed out, please upvote the UserVoice  for now as this helps us prioritize our feature work.

**Comment by SRGOM** [comment]
I don't understand what this issue means but god save me from the messy clipboard handling of Linux. Its a major pain in the ass (speaking as a Linux user right now)

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
