### ISSUE TITLE
In windows console, Chinese file name can not be ls correctly.

### ISSUE THREAD

**Issue by xuzhen0107** [Microsoft/WSL#985]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  When I cd to /mnt/d and ls the files in my windows D: , Thers are a lots of directoies with chinese name and long name, I found they can not show right in the default windows console. Just it can show half of chinese word.
- Expected results
  Get the answer how to set 
  ![untitled](https://cloud.githubusercontent.com/assets/21243263/17973160/eaa32022-6b13-11e6-978f-9b857aa9f508.png)
- Actual results (with terminal output if applicable)
- Your Windows build number
- Steps / commands required to reproduce the error
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by SkinnyDaddy** [comment]
hi xuzhen0107,
The same problem happens to both Japanese console and xterm on Xming/VcXsrv. I guess this problem is language independent.
IMHO, the source cause seems the very buggy terminal emulation where escape sequence are not properly handled.
Check if you have alias lines, for instance, alias ls='ls --color=auto'.
Temporary workaround would be life with white and black console (Joke):
opt-1) comment out alias commands in ~/.bashrc where "--color=auto" is specified for cosmetic reason
opt-2) run ls with "--color=none" option
opt-3) run /bin/ls
opt-4) redirect output of ls to cat : ls /mnt/d | cat
I have checked with the script command that the output of ls itself is error free.
Anyway, the real solution seems missing. I also wish for project team's efforts.
/Skinny

**Comment by SkinnyDaddy** [comment]
one more comment on the gargled characters,
Change Keyboard settings for Chinese with less gargled text screen.
$ LANG=en_US.UTF-8 sudo dpkg-reconfigure keyboard-configuration
/Skinny

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
