### ISSUE TITLE
Clear-Host doesn't work in PowerShell on WSL

### ISSUE THREAD

**Issue by alexandair** [Microsoft/WSL#988]
Steps to reproduce

 Clear-Host 

Expected behavior

It should clear a screen.

Actual behavior

Error mesage:

```
Program 'clear' failed to run: SuccessAt line:1 char:1ng
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1ce             Continue
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Environment data

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by russalex** [comment]
Thanks for reporting.

Looks to be related to #933 and #980.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
