### ISSUE TITLE
Network doens't work with WSL 2 and Ubuntu

### ISSUE THREAD

**Issue by filippodicostanzo** [microsoft/WSL#9926]
### Windows Version

Microsoft Windows [Version 10.0.22000 N/D build 22000]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop 4.17.1

### Repro Steps

just open wsl cmd and digit ping www.github.com

when I try to ping any address other than google.com the process stops and does not proceed.

the network works strangely because if I run the apt update command it downloads and installs the required packages.

but if I try to execute a git clone command with the repo to be cloned it gives me a timeout error. or if I even try to ping www.github.com it becomes unresponsive.

i tried to add nameserver to resolv.conf but doesn't work

### Expected Behavior

I expect that if I try to clone a repo from github it will download the chosen package

### Actual Behavior

git clone https://github.com/filippodicostanzo/eldenapp.git
Cloning into 'eldenapp'...
fatal: unable to access 'https://github.com/filippodicostanzo/eldenapp.git/': Failed to connect to github.com port 443 after 131928 ms: Connection timed out

**Comment by mariorecinos** [comment]
WSL Not Starting After Move


Chapin

Cant start WSL after moving from C: to D:

I get the error below


Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:368: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:372: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:574: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:583: Create process not expected to return
PS D:\>


Here are the steps to replicate 

wsl --list -v
wsl --export Ubuntu ubuntu.tar
wsl --unregister Ubuntu
mkdir D:\WSL\
wsl --import Ubuntu20.04 D:\WSL\Ubuntu20.04 C:\Users\marja\AppData\Local\Docker\wsl\data\ext4.vhdx --vhd

wsl --set-default Ubuntu20.04
wsl

It seems like there is an issue with the mount points for your WSL distribution after you moved it from the C: drive to the D: drive.

One possible solution is to update the mount points in the /etc/fstab file of your WSL distribution. You can try the following steps:

Open your WSL distribution by running wsl in the command prompt.
Edit the /etc/fstab file by running sudo nano /etc/fstab.
Update the mount points for your WSL distribution to match the new location on the D: drive. For example, if your WSL distribution was originally located in /mnt/c, you may need to update it to /mnt/d or another appropriate mount point on the D: drive.
Save the changes to the /etc/fstab file and exit the editor.
Run sudo mount -a to apply the changes to the mount points.
Exit the WSL distribution by running exit.
Try starting the WSL distribution again by running wsl.
If the above steps do not work, you may need to try recreating your WSL distribution from scratch on the D: drive. This can be done by following the steps outlined in the Microsoft documentation: https://docs.microsoft.com/en-us/windows/wsl/install-win10#move-your-linux-distros-to-another-drive.




Chapin
git clone https://github.com/filippodicostanzo/eldenapp.git
Cloning into 'eldenapp'...
fatal: unable to access 'https://github.com/filippodicostanzo/eldenapp.git/': Failed to connect to github.com port 443 after 131928 ms: Connection timed out

The error message indicates that Git was not able to connect to GitHub to clone the repository. This can happen for various reasons, such as network connectivity issues or firewall restrictions.

Here are some steps you can try to troubleshoot the issue:

Check your internet connection and ensure that you have a stable network connection.
Try to clone the repository using the SSH protocol instead of HTTPS. To do this, you'll need to add an SSH key to your GitHub account and then use the SSH URL for the repository. The steps for generating an SSH key and adding it to your GitHub account can be found here: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.
If you're using a firewall, ensure that it's not blocking the connection to GitHub. You may need to add an exception to the firewall to allow Git to connect to GitHub.
Try cloning the repository from a different network or location to see if the issue is specific to your current network.
Contact your network administrator or IT support team to see if there are any network restrictions or firewall rules that may be preventing Git from connecting to GitHub.
If none of the above steps work, you may need to contact GitHub support for further assistance.




Chapin
just open wsl cmd and digit ping www.github.com

when I try to ping any address other than google.com the process stops and does not proceed.

the network works strangely because if I run the apt update command it downloads and installs the required packages.

but if I try to execute a git clone command with the repo to be cloned it gives me a timeout error. or if I even try to ping www.github.com it becomes unresponsive.

i tried to add nameserver to resolv.conf but doesn't work

It sounds like there may be an issue with DNS resolution on your WSL distribution. DNS resolution is the process by which domain names (like "github.com") are translated into IP addresses (like "140.82.121.3"), which are then used to establish network connections.

Here are some steps you can try to troubleshoot the issue:

Check that your WSL distribution is using the correct DNS servers. You can do this by running the command cat /etc/resolv.conf in your WSL terminal. If the output doesn't list any DNS servers, or lists incorrect servers, you can try adding the correct DNS servers manually. You can add the DNS server IPs to the /etc/resolv.conf file, for example: nameserver 8.8.8.8 (Google DNS).
Try flushing the DNS cache on your WSL distribution by running the command sudo /etc/init.d/dns-clean start.
Check if there are any issues with your firewall or network configuration that may be blocking DNS requests. You may need to contact your network administrator or IT support team for help with this.
If you're using a VPN or proxy server, try disabling it to see if that resolves the issue.
Try resetting your network settings by running the command sudo service networking restart.

**Comment by thommasjodehl** [comment]
Have you tried "ipconfig /flushdns" in powershell? I have experienced connection issues within WSL recently and running the aforementioned command fixed it for me. Obviously not a good permanent solution.

**Comment by ianw89** [comment]
I am now having this issue too. Ping and apt-get update work, yet git fetch and ssh do not. 

Routine resets like:

wsl --shutdown
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns
netsh winsock reset
shutdown /r

... have not helped. I also tried disabling firewall.

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by craigloewen-msft** [comment]
Closing due to lack of response, if you're hitting this issue please feel free to reopen a new issue!
