### ISSUE TITLE
Updating to new Windows version Deleted .ssh folder

### ISSUE THREAD

**Issue by lolJS** [Microsoft/WSL#995]
I just updated to Windows 10 Pro Insider Preview Build 14905.rs_prerelease.160811-1739. Updating has inconveniently disabled Bash for Windows and deleted my .ssh directory in my user folder. I have therefore lost my SSH keys. I hope you can understand why this is extremely inconvenient. Steps should be taken to prevent this in the future. I simply don't understand why my .ssh folder would be deleted when updating builds.

**Comment by fpqc** [comment]
@lolJS Thanks for reporting the problem, but you are using beta software on an unstable insider build of Windows.  You should always make sure to back up your ssh keys in such a circumstance if they are important.

**Comment by rodrymbo** [comment]
[The Devs say](https://msdn.microsoft.com/en-us/commandline/wsl/reference?f=255&MSPPError=-2147217396) that they try to preserve /home (and maybe /root) when they fiddle with the lxss tree, but sometimes stuff happens.

I have a tar script that makes a backup of /home, /etc, /root, and /usr/local. I suppose I could make it available, maybe save some people time. Or maybe the Devs can tell us how to get System Restore or File History to restore files in lxss that get deleted.

But really ... it's a computer. If you don't have a backup of something, it will get corrupted or deleted, according to the Demon Murphy (and my experience).

**Comment by russalex** [comment]
@lolJS, sorry to hear that the .ssh directory was deleted.  Mind going into a bit more details here?

- Was anything else deleted?
- I assume your ssh keys were under ~/.ssh.  Was anything else lost (like changes to .bashrc)?
- Did you just run "bash" as normal after re-enabling the feature or did you perform any other steps?

**Comment by lolJS** [comment]
@russalex pardon the late reply. My whole home folder was deleted. After re-enabling the only thing in my home folder was a `known_hosts` file. After re-enabling, I simply ran `bash`, which brought up the same prompts that I saw the first time I enabled Bash on Windows.

**Comment by russalex** [comment]
@lolJS Just to clarify, by first prompts you mean the ones where it is asking you to create a username / password?

A few of things that could have happened here:

1) It is possible you signed in with a different Windows user.  The WSL instance is on a per Windows user basis so signing in as a different Windows user would start you from scratch (even if you create a Ubuntu user of the same name)

2) It is possible that your update brought you back to a checkpoint from before WSL was installed.

3) For some reason, your \lxss directory was deleted.  This should not happen during upgrade since the upgrade process does not touch that directory, but it is possible there was a bug.

**Comment by lolJS** [comment]
@russalex Sorry, for the uber late reply. It was a busy month here. Yes, to clarify it asked me to create a new username / password.

1. I did not login as a different user.

2. Seems likely.

3. Possibly. I could find no trace of my old home directory.

**Comment by benhillis** [comment]
This issue is related to the deprecated install mechanism (lxrun). Closing.
