### ISSUE TITLE
WSL/CUDA unsupported on H100

### ISSUE THREAD

**Issue by dje-dev** [microsoft/WSL#9952]
NVIDIA states that CUDA with WSL is fully supported, although they do list a few limitations (e.g. unified memory not available).

However it turns out that WSL does not currently work at all on the latest generation of cards. Specifically for a PCIe  H100 cards the GPUs are not recognized by WSL even though the latest NVIDA drivers are installed. The reason seems to be the following:
- WSL only supports CUDA when running in WDDM mode. This limitation is not clear in the official documentation, given this wording which suggest the limitations applies to Quadro cards but actually is more general: "will not be available on Quadro GPUs in TCC mode or Tesla GPUs yet"
- H100 PCIe cards do not support WDDM mode, only TCC mode (nvidia-smi refuses to switch into TCC mode)

Could it please be confirmed the above is correct, and clarified if WSL is ever expected to be supported on NVIDA cards from H100 forward? Thank you.

**Comment by dje-dev** [comment]
Thank you, understood. I've posted the question over on the NVIDIA CUDA WSL forum.

**Comment by DonnyVerduijn** [comment]
Since Nvidia hasn't been answering your question for over four months, i assume it might be relevant to get some insights about why the WDDM driver model is required in WSL2 to work with any gpu at all, while it doesn't in Windows? Any chance we can reopen this?

**Comment by DonnyVerduijn** [comment]
It seems i found myself an answer to this question here: 
https://web.archive.org/web/20210723012948/https://xdc2020.x.org/event/9/contributions/610/attachments/700/1295/XDC_-_WSL_Graphics_Architecture.pdf

**Comment by cccc11231** [comment]
I still have this issue. Does anyone know if there is any solution?

by the way, @dje-dev can you share the question on the NVIDIA CUDA WSL forum? I cannot find it.

Thanks.

**Comment by DonnyVerduijn** [comment]
> I still have this issue. Does anyone know if there is any solution?
> 
> by the way, @dje-dev can you share the question on the NVIDIA CUDA WSL forum? I cannot find it.
> 
> Thanks.

AFAIK, only WDDM drivers are supported in WSL because they implement gpu paravirtualization on thw WSL architecture relies. Therefore any gpu using TCC driver mode  is currently not supported, which is the only option with headless gpus.

The only option is to run a native Linux Distro.

**Comment by ak3dde** [comment]
Same problem here. Is there any solution so far? Will an A100 PCIe work in WSL?

**Comment by DonnyVerduijn** [comment]
I wouldn't expect a solution from Nvidia, because the A100 is not intended to be compatible with Windows and subsequently WSL2. Nvidia clearly states that it relies on Windows drivers to support WSL2. This means that it is not supported for headless gpus relying on TCC driver mode. Source:  docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by DonnyVerduijn** [comment]
I wouldn't expect a solution from Nvidia, because the A100 is not intended to be compatible with Windows and subsequently WSL2. Nvidia clearly states that it relies on Windows drivers to support WSL2. This means that it is not supported for headless gpus relying on TCC driver mode. Source:  docs.nvidia.com/cuda/wsl-user-guide/index.html
