### ISSUE TITLE
WSL automatic shutdown

### ISSUE THREAD

**Issue by ma-netint** [microsoft/WSL#9985]
### Windows Version

Microsoft Windows [Version 10.0.19044.2728]

### WSL Version

WSL version: 1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

Visual Studio Code with WSL extension v0.77.0

### Repro Steps

No surefire way of reproducing. Best I got is, over the weekend I had
2 Ubuntu terminals running that were started using the default profile in windows terminals
2 VSCode windows on WSL

Come Monday, both the terminals had stopped with `[process exited with code 1 (0x00000001)]`, and VSCode windows were trying to reconnect. 
I opened a new Ubuntu terminal and it took a few seconds to come up, indicating a reboot/power up. Confirmed this via dmesg as well:
```
 $ dmesg -wT
[Mon Apr 17 08:47:12 2023] Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023
[Mon Apr 17 08:47:12 2023] Command line: initrd=\initrd.img WSL_ROOT_INIT=1 panic=-1 nr_cpus=8 bonding.max_bonds=0 dummy.numdummies=0 fb_tunnels=none swiotlb=force console=hvc0 debug pty.legacy_count=0
...
```

### Expected Behavior

All terminals and VSCode connections should remain active indefinitely

### Actual Behavior

WSL shuts down automatically after a day or so of inactivity with open terminals and VSCode.
All sessions are active after 16-17 hours of inactivity.

**Comment by ma-netint** [comment]
Collecting logs, will post once the issue is hit again.

**Comment by friedlinguini** [comment]
I have similar behavior, though I'm not sure if it's the same root cause as the original poster. I see WSL sessions getting shut down on me after "upgrading" WSL to be an app managed by Microsoft Store, including an update that occurred yesterday. Since then, I see forcible terminations correlated with app updates.

I think what should happen is either the update should not run if WSL is running, it should be possible to disable updates manually, or there should be a process for "downgrading" the app to one not managed by Microsoft Store. WSL isn't like a mobile phone app, you can't terminate it at will and restore to "approximately" the same state and get acceptable behavior.

**Comment by ma-netint** [comment]
This is not a duplicate as the issue doesn't happen when an update is performed but rather when terminals/host is inactive.
I was able to reproduce the issue over the the weekend. Attaching logs(link because over 25MB): https://drive.google.com/file/d/1u1BLGPju4c_UmIa9Vq29rQUs2_9UEwMP/view?usp=sharing

**Comment by MrMarvel** [comment]
I have problem with auto closing wsl
Starting wsl.
Closing wsl. Waiting some time
BUT There is wslservice.exe and vmmem (big)
wsl --shutdown
vmmem closed but wsl.service still there
